src.3/objects/Asset.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Notes whether or not the Asset is being billed.</description>
        <inlineHelpText>Notes whether or not the Asset is being billed.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current_Product_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Shows the related subscription that has the most distant Contract End Date that is not Terminated.  Set from trigger.  Trigger activated by Subscription Last Modified field.</description>
        <label>Current Product Subscription</label>
        <referenceTo>RecurSoft__Product_Subscription__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related Provider record for Healthgrades Assets</description>
        <inlineHelpText>The related Provider record for Healthgrades Assets</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.2/objects/AsyncRequest__c.object
<CustomObject>
    <description>Used for logging Async requests to be processed.</description>
    <label>AsyncRequest</label>
    <nameField>
        <displayFormat>ASYNC-{0000000}</displayFormat>
        <label>AsyncRequest Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AsyncRequests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>AsyncType__c</fullName>
        <label>AsyncType</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AppAdmin_AssetSync</fullName>
                </value>
                <value>
                    <fullName>AppAdmin_HGSync</fullName>
                </value>
                <value>
                    <fullName>AppAdmin_OppSync</fullName>
                </value>
                <value>
                    <fullName>Contract_Email</fullName>
                </value>
                <value>
                    <fullName>Process_Dist_Group</fullName>
                </value>
                <value>
                    <fullName>ProdSub_AfterInsert</fullName>
                </value>
                <value>
                    <fullName>Set_DQ_Delete_CI</fullName>
                </value>
                <value>
                    <fullName>Task_ADR_CI</fullName>
                </value>
                <value>
                    <fullName>Update_Opp_Stage_Demo_Completed</fullName>
                </value>
                <value>
                    <fullName>Update_Opp_Stage_Demo_Scheduled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Params__c</fullName>
        <label>Params</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

src.4/objects/Case.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Administrative</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Technical</fullName>
                </value>
                <value>
                    <fullName>Collections</fullName>
                </value>
                <value>
                    <fullName>Generic</fullName>
                </value>
                <value>
                    <fullName>Change Payment Terms</fullName>
                </value>
                <value>
                    <fullName>Feature Enhancement</fullName>
                </value>
                <value>
                    <fullName>Open Invoice</fullName>
                </value>
                <value>
                    <fullName>Past Due</fullName>
                </value>
                <value>
                    <fullName>Setup Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SR Platform</fullName>
                </value>
                <value>
                    <fullName>SR Sync</fullName>
                </value>
                <value>
                    <fullName>PatientReach</fullName>
                </value>
                <value>
                    <fullName>One Desk</fullName>
                </value>
                <value>
                    <fullName>Simpletrac</fullName>
                </value>
                <value>
                    <fullName>SR Enterprise</fullName>
                </value>
                <value>
                    <fullName>Healthgrades</fullName>
                </value>
                <value>
                    <fullName>Limelight</fullName>
                </value>
                <value>
                    <fullName>SR Conversations</fullName>
                </value>
                <value>
                    <fullName>SR Smart Reviews</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Topics__c</fullName>
        <label>Topics</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active Monitor</fullName>
                </value>
                <value>
                    <fullName>Active Push</fullName>
                </value>
                <value>
                    <fullName>Active Review</fullName>
                </value>
                <value>
                    <fullName>Admin</fullName>
                </value>
                <value>
                    <fullName>Birthdays</fullName>
                </value>
                <value>
                    <fullName>Contract Addendum</fullName>
                </value>
                <value>
                    <fullName>Dashboard</fullName>
                </value>
                <value>
                    <fullName>Eyewear</fullName>
                </value>
                <value>
                    <fullName>Filters</fullName>
                </value>
                <value>
                    <fullName>General Training</fullName>
                </value>
                <value>
                    <fullName>Groups</fullName>
                </value>
                <value>
                    <fullName>Installation</fullName>
                </value>
                <value>
                    <fullName>Local Listing</fullName>
                </value>
                <value>
                    <fullName>Maps</fullName>
                </value>
                <value>
                    <fullName>Messaging</fullName>
                </value>
                <value>
                    <fullName>New Integration</fullName>
                </value>
                <value>
                    <fullName>Newsletters</fullName>
                </value>
                <value>
                    <fullName>Password</fullName>
                </value>
                <value>
                    <fullName>Patient Manager</fullName>
                </value>
                <value>
                    <fullName>PatientReach</fullName>
                </value>
                <value>
                    <fullName>PatientView</fullName>
                </value>
                <value>
                    <fullName>Recall</fullName>
                </value>
                <value>
                    <fullName>Referrals</fullName>
                </value>
                <value>
                    <fullName>Reminders</fullName>
                </value>
                <value>
                    <fullName>Reports</fullName>
                </value>
                <value>
                    <fullName>Schedule</fullName>
                </value>
                <value>
                    <fullName>SmileDash</fullName>
                </value>
                <value>
                    <fullName>Social Networking</fullName>
                </value>
                <value>
                    <fullName>Surveys</fullName>
                </value>
                <value>
                    <fullName>Sync Down</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Support</fullName>
        <active>true</active>
        <businessProcess>Support</businessProcess>
        <description>The main case type for Support</description>
        <label>Support</label>
    </recordTypes>
</CustomObject>

src.3/objects/Product2.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Default_Contract_Term__c</fullName>
        <description>If Inherit Opportunity Contract Terms is false, the Contract Term will be set on the Opportunity Product to (Default Contract Term + Product Number of Free Months) and reset to this value when an Opportunity contract term change is made. For month-to-month products.</description>
        <inlineHelpText>If Inherit Opportunity Contract Terms is false, the Contract Term will be set on the Opportunity Product to (Default Contract Term + Product Number of Free Months) and reset to this value when an Opportunity contract term change is made.</inlineHelpText>
        <label>Default Contract Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Default_Co_Terminate__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Sets the default for co-termination on the related Opportunity Products.  Can be overridden at the Opportunity Product level.</description>
        <inlineHelpText>Sets the default for co-termination on the related Opportunity Products.  Can be overridden at the Opportunity Product level.</inlineHelpText>
        <label>Default Co-Terminate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Default_Renewal_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Provides the Default Renewal Rule for this Product. Will be set on Opportunity Products.</description>
        <inlineHelpText>Provides the Default Renewal Rule for this Product. Will be set on Opportunity Products.</inlineHelpText>
        <label>Default Renewal Rule</label>
        <referenceTo>RecurSoft__Renewal_Rule__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Billing_Frequency__c</fullName>
        <inlineHelpText>The frequency at which customer is invoiced.</inlineHelpText>
        <label>Billing Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One-Time</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-annual</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>Milestones</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/Provider__c/Provider__c.object-meta.xml
<CustomObject>
    <description>Used to store information about individual Providers within a Practice.  The Provider information is used for Healthgrades Premium members.</description>
    <label>Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Provider__c/fields/Bill_to_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The related account that will be billed for the Provider&#39;s Healthgrades subscription.</description>
    <inlineHelpText>The related account that will be billed for the Provider&#39;s Healthgrades subscription.</inlineHelpText>
    <label>Bill to Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Providers</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Healthgrades_ID__c.field-meta.xml
<CustomField>
    <fullName>Healthgrades_ID__c</fullName>
    <description>The individual Provider&#39;s unique Healthgrades identifier.</description>
    <externalId>true</externalId>
    <label>Healthgrades ID</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Provider__c/fields/NPI__c.field-meta.xml
<CustomField>
    <fullName>NPI__c</fullName>
    <description>A National Provider Identifier or NPI is a unique 10-digit identification number issued to health care providers in the United States by the Centers for Medicare and Medicaid Services (CMS).</description>
    <label>NPI</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Premium_Member__c.field-meta.xml
<CustomField>
    <fullName>Premium_Member__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the Provider is currently paying for a Healthgrades Premium Profile.</description>
    <inlineHelpText>Checked if the Provider is currently paying for a Healthgrades Premium Profile.</inlineHelpText>
    <label>Premium Member</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Related_Contact__c.field-meta.xml
<CustomField>
    <fullName>Related_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Provider&#39;s contact information is accessed via the Related Contact field.</description>
    <inlineHelpText>The Provider&#39;s contact information is accessed via the Related Contact field.</inlineHelpText>
    <label>Related Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Providers</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

src.2/classes/AssetUtilities.cls
public with sharing class AssetUtilities {

	public static Map<Id, Product2> getRelatedProducts() {
		
		Map<ID, Product2> results = new Map<ID, Product2> (
			[SELECT Id, 
			Family, 
			Default_Renewal_Rule__c, 
		    Default_Contract_Term__c, 
		    Default_Co_Terminate__c, 
		    RecurSoft__Billing_Frequency__c 
			FROM Product2]);

		return results;
	}

	public static Map<Id, Asset> getRelatedSubscriptions(Map<Id, Asset> assetMap) {

		Map<Id, Asset> results = new Map<Id, Asset>(
			[SELECT Id,
			(SELECT Id
				FROM Product_Subscriptions__r 
				WHERE RecurSoft__Billing_Status__c = 'Regular Invoicing'
				ORDER BY RecurSoft__Contract_Term_End_Date__c DESC
				LIMIT 1)
			FROM Asset
			WHERE Id IN :assetMap.keySet()]);

		return results;
	}

	public static Map<Id, Provider__c> getProviderData(Set<Id> providerIds) {

        Map<Id, Provider__c> results = new Map<Id, Provider__c>([SELECT Id,
        Name,
        Bill_to_Account__c,
        Related_Contact__c,
        Healthgrades_ID__c,
        Premium_Member__c,
        NPI__c
        FROM Provider__c
        WHERE Id IN :providerIds]);

        return results;
    }

	public static void setCurrentSubscription(Asset[] updatedAssets, Map<Id, Asset> assetMap) {

		Map<Id, Asset> currentSubscriptionMap = getRelatedSubscriptions(assetMap);

		for(Asset ast : updatedAssets) {

			Asset ast2 = currentSubscriptionMap.get(ast.Id);

			if(ast2.Product_Subscriptions__r.isEmpty()) {

				ast.Current_Product_Subscription__c = null;
				ast.Active__c = false;

			} else {

				ast.Current_Product_Subscription__c = ast2.Product_Subscriptions__r[0].Id;
				ast.Active__c = true;
			}
		}
	}

	public static void scheduleAssetSync(Asset[] updatedAssets, Map<Id, Asset> oldAssetMap, Boolean isUpdate) {

		Set<Id> idsToProcess = new Set<Id>();

		for(Asset ast : updatedAssets) {

			if(!isUpdate && ast.Provider__c == null) {

				idsToProcess.add(ast.Id);
			
			} else if(ast.Active__c != oldAssetMap.get(ast.Id).Active__c && ast.Provider__c == null) {

				idsToProcess.add(ast.Id);
			}
		}

		if(idsToProcess.size() == 0) return;

		AsyncRequest__c[] newRequests = new List<AsyncRequest__c>();
		Id[] idsForRequest = new List<Id>();

		for(Id i : idsToProcess) {

			idsForRequest.add(i);

			if(idsForRequest.size() == 10) {

				newRequests.add(new AsyncRequest__c(AsyncType__c = AsyncMain.TYPE_APPADMIN_ASSETSYNC, 
					Params__c = String.join(idsForRequest, ',')));
				idsForRequest.clear();
			}
		}

		if(idsForRequest.size() > 0) {

			newRequests.add(new AsyncRequest__c(AsyncType__c = AsyncMain.TYPE_APPADMIN_ASSETSYNC, 
				Params__c = String.join(idsForRequest, ',')));
		}

		insert newRequests;
	}

	public static void scheduleHGSync(Asset[] updatedAssets, Map<Id, Asset> oldAssetMap, Boolean isUpdate) {

		Set<Id> idsToProcess = new Set<Id>();

		for(Asset ast : updatedAssets) {

			if(!isUpdate && ast.Provider__c != null) {

				idsToProcess.add(ast.Provider__c);
			
			} else if(ast.Active__c != oldAssetMap.get(ast.Id).Active__c && ast.Provider__c != null) {

				idsToProcess.add(ast.Provider__c);
			}
		}

		if(idsToProcess.size() == 0) return;

		AsyncRequest__c[] newRequests = new List<AsyncRequest__c>();
		Id[] idsForRequest = new List<Id>();

		for(Id i : idsToProcess) {

			idsForRequest.add(i);

			if(idsForRequest.size() == 10) {

				newRequests.add(new AsyncRequest__c(AsyncType__c = AsyncMain.TYPE_APPADMIN_HGSYNC, 
					Params__c = String.join(idsForRequest, ',')));
				idsForRequest.clear();
			}
		}

		if(idsForRequest.size() > 0) {

			newRequests.add(new AsyncRequest__c(AsyncType__c = AsyncMain.TYPE_APPADMIN_HGSYNC, 
				Params__c = String.join(idsForRequest, ',')));
		}

		insert newRequests;
	}

	public static void setProviderStatus(Map<Id, Asset> oldAssetMap, Asset[] updatedAssets) {

		Map<Id, SObject> mapInsertSObject = new Map<Id, SObject>();
      	Map<Id, SObject> mapUpdateSObject = new Map<Id, SObject>();
      	Map<Id, SObject> mapDeleteSObject = new Map<Id, SObject>();
      	Set<Id> providerIds = new Set<Id>();
      	Map<Id, Provider__c> providerMap = new Map<Id, Provider__c>();

      	for(Asset ast : updatedAssets) {

      		if(ast.Provider__c != null) providerIds.add(ast.Provider__c);
      	}

      	if(!providerIds.isEmpty()) {

      		providerMap = getProviderData(providerIds);

	      	for(Asset ast : updatedAssets) {

	      		if(ast.Provider__c == null || !providerMap.containsKey(ast.Provider__c)) continue;

	      		Provider__c p = providerMap.get(ast.Provider__c);
	      		
	      		if(ast.Active__c != p.Premium_Member__c) {

	      			p.Premium_Member__c = ast.Active__c;
	      			mapUpdateSObject.put(p.Id, p);
	      		}
	      	}
	    }

	    SRUtilities.runDml(mapInsertSObject, mapUpdateSObject, mapDeleteSObject, 'AssetUtilities.setProviderStatus');
	}

	/*public static void newAssetCase(Map<Id, Asset> oldAssetMap, Asset[] updatedAssets) {

		String LL_QUEUE_ID = [SELECT Id FROM Group WHERE Type = 'Queue' AND Name = 'Limelight Onboarding Queue'].Id;
		Map<Id, Product2> productMap = getRelatedProducts();
		Map<Id, SObject> mapInsertSObject = new Map<Id, SObject>();
      	Map<Id, SObject> mapUpdateSObject = new Map<Id, SObject>();
      	Map<Id, SObject> mapDeleteSObject = new Map<Id, SObject>();

		for(Asset ast : updatedAssets) {

			Product2 relatedProduct = productMap.get(ast.Product2Id);

			if(oldAssetMap.get(ast.Id).Active__c == false && ast.Active__c == true && relatedProduct.Family == 'Limelight') {

				Case newCase = new Case(Subject = 'Limelight Implementation',
					AccountId = ast.AccountId,
					RecordTypeId = SRUtilities.getRecordTypeMap('Case').get('Support').getRecordTypeId(),
					Product__c = 'Limelight',
					Origin = 'Web',
					Category__c = 'Training',
					Topics__c = 'General Training',
					OwnerId = LL_QUEUE_ID);

				mapInsertSObject.put(ast.Id, newCase);
			}
		}

		SRUtilities.runDml(mapInsertSObject, mapUpdateSObject, mapDeleteSObject, 'AssetUtilities.newAssetCase');
	}*/
}