src.3/objects/Asset.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Notes whether or not the Asset is being billed.</description>
        <inlineHelpText>Notes whether or not the Asset is being billed.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Next_Invoice_Date__c</fullName>
        <description>Used in setting the Contract Term Start Date for &quot;Add Product&quot; Opportunities. Set by rollup summary.</description>
        <inlineHelpText>Used in setting the Contract Term Start Date for &quot;Add Product&quot; Opportunities. Set by rollup summary.</inlineHelpText>
        <label>Next Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related Provider record for Healthgrades Assets</description>
        <inlineHelpText>The related Provider record for Healthgrades Assets</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Last_Modified_Date__c</fullName>
        <description>Last modified date for the related subscriptions. Set by lookup rollup summary.  Triggers update of current subscription field.</description>
        <label>Subscription Last Modified Date</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

src.1/objects/Lead.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>Number_of_Providers__c</fullName>
        <label>Number of Providers</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0-10</fullName>
                </value>
                <value>
                    <fullName>11-29</fullName>
                </value>
                <value>
                    <fullName>30-49</fullName>
                </value>
                <value>
                    <fullName>50+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Approval_Level_Required__c</fullName>
        <label>Approval Level Required</label>
        <summarizedField>OpportunityLineItem.Approval_Level_Required__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Contract_Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Providers__c</fullName>
        <label>Number of Providers</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_PRT__c</fullName>
        <label>Number of PRT</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the related Provider record</description>
        <inlineHelpText>Link to the related Provider record</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill to Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.RecurSoft__Bill_to_Account__c</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>RecurSoft_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Signed_Date__c</fullName>
        <label>Contract Signed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_End_Date__c</fullName>
        <label>Contract Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_Start_Date__c</fullName>
        <label>Contract Term Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Free_Months_Setting__c</fullName>
        <inlineHelpText>Different seting options for contracts with free months.</inlineHelpText>
        <label>Free Months Setting</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RecurSoft__Number_of_Free_Months__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Extend Contract - At the Beginning</fullName>
                </value>
                <value>
                    <fullName>Extend Contract - At the End</fullName>
                </value>
                <value>
                    <fullName>Include in Contract Period - At the Beginning</fullName>
                </value>
                <value>
                    <fullName>Include in Contract Period - At the End</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RecurSoft__Initial_Contract_Term__c</fullName>
        <defaultValue>12</defaultValue>
        <inlineHelpText>Contract duration, in months.</inlineHelpText>
        <label>Contract Term (Months)</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Number_of_Free_Months__c</fullName>
        <inlineHelpText>Free months that can extend the contract or be included in the contract.</inlineHelpText>
        <label>Number of Free Months</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <default>true</default>
                    <label>0</label>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RecurSoft__Trial__c</fullName>
        <description>Trial Period in Days.</description>
        <inlineHelpText>Period during which contracts can be cancelled without penalties.</inlineHelpText>
        <label>Trial Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0 - Waived</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                    <default>true</default>
                    <label>60</label>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.3/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Approval_Level_Required__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Approval Level Required</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Base_Contract_Term__c</fullName>
        <label>Base Contract Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Free_Month_Setting__c</fullName>
        <description>Override opportunity free months</description>
        <label>Orientation Month Setting</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Extend Contract - At the Beginning</fullName>
                </value>
                <value>
                    <fullName>Include in Contract Period - At the Beginning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Free_Months__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Override opportunity free months</description>
        <inlineHelpText>Override opportunity free months</inlineHelpText>
        <label>Number of Orientation Months</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related Provider for the Healthgrades Premium Profile</description>
        <inlineHelpText>The related Provider for the Healthgrades Premium Profile</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_End_Date_Editable__c</fullName>
        <label>Contract Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_End_Date__c</fullName>
        <formula>DATE(
year(RecurSoft__Contract_Term_Start_Date_New__c)+ floor((month(RecurSoft__Contract_Term_Start_Date_New__c) + VALUE(RecurSoft__Contract_Term1__c))/12) + if(and(month(RecurSoft__Contract_Term_Start_Date_New__c)=12,VALUE(RecurSoft__Contract_Term1__c)&gt;=12),-1,0)
,if( mod( month(RecurSoft__Contract_Term_Start_Date_New__c) + VALUE(RecurSoft__Contract_Term1__c) , 12 ) = 0, 12 , mod( month(RecurSoft__Contract_Term_Start_Date_New__c) + VALUE(RecurSoft__Contract_Term1__c) , 12 ))
,min(day(RecurSoft__Contract_Term_Start_Date_New__c),case(max( mod( month(RecurSoft__Contract_Term_Start_Date_New__c) + VALUE(RecurSoft__Contract_Term1__c) , 12 ) , 1),9,30,4,30,6,30,11,30,2,28,31))
)-1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deprecated - Contract Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_Start_Date_New__c</fullName>
        <label>Contract Term Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_Start_Date__c</fullName>
        <formula>Opportunity.RecurSoft__Contract_Term_Start_Date1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deprecated - Contract Term Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Product_Subscription__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This field contains product subscription for current opportunity product.</inlineHelpText>
        <label>Product Subscription</label>
        <referenceTo>RecurSoft__Product_Subscription__c</referenceTo>
        <relationshipLabel>Opportunity Product (Product Subscription)</relationshipLabel>
        <relationshipName>RecurSoft_Opportunity_Product3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial__c</fullName>
        <label>Trial Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>120</fullName>
                </value>
                <value>
                    <fullName>180</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/Provider__c/Provider__c.object-meta.xml
<CustomObject>
    <description>Used to store information about individual Providers within a Practice.  The Provider information is used for Healthgrades Premium members.</description>
    <label>Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Provider__c/fields/Premium_Member__c.field-meta.xml
<CustomField>
    <fullName>Premium_Member__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the Provider is currently paying for a Healthgrades Premium Profile.</description>
    <inlineHelpText>Checked if the Provider is currently paying for a Healthgrades Premium Profile.</inlineHelpText>
    <label>Premium Member</label>
    <type>Checkbox</type>
</CustomField>

src.4/classes/FlowControl.cls
public without sharing class FlowControl {

    //Opportunity FlowControl Static Variables
    public static Boolean opportunityBeforeInsertRecursion = false;
    public static Boolean opportunityBeforeUpdateRecursion = false;
    public static Boolean opportunityAfterInsertRecursion = false;
    public static Boolean opportunityAfterUpdateRecursion = false;
    public static Boolean opportunityAppAdminSyncRecursion = false;
    public static Boolean inOpportunityAfterInsert = false;
    public static Boolean inClass1 = false;
    public static Map<ID, SObject> alreadyDeleted = new Map<ID, SObject>();
    public static Map<ID, SObject> alreadyUpdated = new Map<ID, SObject>();

    //CampaignInfluence FlowControl
    public static Boolean campaignInfluenceBeforeInsertRecursion = false;
    public static Boolean campaignInfluenceBeforeUpdateRecursion = false;
    public static Boolean campaignInfluenceAfterInsertRecursion = false;
    public static Boolean campaignInfluenceAfterUpdateRecursion = false;
    public static Boolean inCampaignInfluenceAfterInsert = false;

    //Task FlowControl
    public static Boolean taskBeforeInsertRecursion = false;
    public static Boolean taskBeforeUpdateRecursion = false;
    public static Boolean taskAfterInsertRecursion = false;
    public static Boolean taskAfterUpdateRecursion = false;
    public static Boolean inTaskAfterInsert = false;

    //Lead FlowControl
    public static Boolean leadBeforeInsertRecursion = false;
    public static Boolean leadBeforeUpdateRecursion = false;
    public static Boolean leadAfterInsertRecursion = false;
    public static Boolean leadAfterUpdateRecursion = false;
    public static Boolean inLeadAfterInsert = false;

    //CampaignMember FlowControl
    public static Boolean campaignMemberBeforeInsertRecursion = false;
    public static Boolean campaignMemberBeforeUpdateRecursion = false;
    public static Boolean campaignMemberAfterInsertRecursion = false;
    public static Boolean campaignMemberAfterUpdateRecursion = false;
    public static Boolean inCampaignMemberAfterInsert = false;

    //Provider FlowControl
    public static Boolean providerBeforeInsertRecursion = false;
    public static Boolean providerBeforeUpdateRecursion = false;
    public static Boolean providerAfterInsertRecursion = false;
    public static Boolean providerAfterUpdateRecursion = false;
    public static Boolean inProviderAfterInsert = false;

    //ProductSubscription FlowControl
    public static Boolean prodSubscriptionBeforeInsertRecursion = false;
    public static Boolean prodSubscriptionBeforeUpdateRecursion = false;
    public static Boolean prodSubscriptionAfterInsertRecursion = false;
    public static Boolean prodSubscriptionAfterUpdateRecursion = false;
    public static Boolean inProdSubscriptionAfterInsert = false;
    public static Boolean prodSubscriptionInsertAsyncRecursion = false;
    public static Boolean prodSubscriptionUpdateAsyncRecursion = false;

    //Transaction FlowControl
    /*public static Boolean transactionBeforeInsertRecursion = false;
    public static Boolean transactionBeforeUpdateRecursion = false;
    public static Boolean transactionAfterInsertRecursion = false;
    public static Boolean transactionAfterUpdateRecursion = false;
    public static Boolean inTransactionAfterInsert = false;*/

    //Asset FlowControl
    public static Boolean assetBeforeInsertRecursion = false;
    public static Boolean assetBeforeUpdateRecursion = false;
    public static Boolean assetAfterInsertRecursion = false;
    public static Boolean assetAfterUpdateRecursion = false;
    public static Boolean inAssetAfterInsert = false;
    public static Boolean assetUpdateAsyncRecursion = false;

    //OpportunityLineItem FlowControl
    public static Boolean oppLineItemRollupRecursion = false;
    public static Boolean oppLineItemBeforeInsertRecursion = false;
    public static Boolean oppLineItemBeforeUpdateRecursion = false;
    public static Boolean oppLineItemAfterInsertRecursion = false;
    public static Boolean oppLineItemAfterUpdateRecursion = false;
    public static Boolean inOppLineItem = false;
    public static Boolean oppLineItemInsertAsyncRecursion = false;
    public static Boolean oppLineItemUpdateAsyncRecursion = false;
    
    public static Boolean suppressRollup = false;
    public static Boolean hgContractDatesSet = false;
    public static Set<String> recordsCreated = new Set<String>();
    public static Boolean isLeadConvert = false;
    public static Boolean isLeadUnConvert = false;

    private static Map<String, SObject> fieldChangeMap = new Map<String, SObject>();
    public static Map<String, Set<Id>> fieldChangeIdMap = new Map<String, Set<Id>>();

    private static Map<String, SObject> priorValueMap = new Map<String, SObject>();
    public static Map<String, Set<Id>> fieldChangeIdMap2 = new Map<String, Set<Id>>();

    public static void checkOpportunityFieldChanges(Opportunity[] newList, Map<Id, Opportunity> oldMap) {

        hasFieldChanged(newList, oldMap, 'StageName', 'Closed Won');
        hasFieldChanged(newList, oldMap, 'RecurSoft__Number_of_Free_Months__c', null);
        hasFieldChanged(newList, oldMap, 'RecurSoft__Free_Months_Setting__c', null);
        hasFieldChanged(newList, oldMap, 'RecurSoft__Initial_Contract_Term__c', null);
        hasFieldChanged(newList, oldMap, 'RecurSoft__Contract_Term_Start_Date__c', null);
        hasFieldChanged(newList, oldMap, 'RecurSoft__Contract_Term_End_Date__c', null);
        hasFieldChanged(newList, oldMap, 'RecurSoft__Billing_Contact__c', null);
        hasFieldChanged(newList, oldMap, 'CampaignId', null);
        hasFieldChanged(newList, oldMap, 'Number_of_Providers__c', null);
        hasFieldChanged(newList, oldMap, 'Number_of_PRT__c', null);
        hasFieldChanged(newList, oldMap, 'RecurSoft__Trial__c', null);
        hasFieldChanged(newList, oldMap, 'Contract_Signed__c', null);
        hasFieldChanged(newList, oldMap, 'IsClosed', null);
        hasFieldChanged(newList, oldMap, 'Pricebook2Id', null);
    }

    public static void checkOppLineItemFieldChanges(OpportunityLineItem[] newList, Map<Id, OpportunityLineItem> oldMap) {

        hasFieldChanged(newList, oldMap, 'RecurSoft__Contract_Term_End_Date_Editable__c', null);
        hasFieldChanged(newList, oldMap, 'RecurSoft__Contract_Term_Start_Date_New__c', null);
        hasFieldChanged(newList, oldMap, 'Number_of_Free_Months__c', null);
        hasFieldChanged(newList, oldMap, 'Free_Month_Setting__c', null);
        hasFieldChanged(newList, oldMap, 'Base_Contract_Term__c', null);
        hasFieldChanged(newList, oldMap, 'Trial__c', null);
        hasFieldChanged(newList, oldMap, 'UnitPrice', null);
        hasFieldChanged(newList, oldMap, 'Approval_Level_Required__c', null);
    }

    public static void checkProdSubscriptionFieldChanges(RecurSoft__Product_Subscription__c[] newList, Map<Id, RecurSoft__Product_Subscription__c> oldMap) {

        hasFieldChanged(newList, oldMap, 'RecurSoft__Billing_Status__c', null);
        hasFieldChanged(newList, oldMap, 'Next_Invoice_Date__c', null);
        hasFieldChanged(newList, oldMap, 'RecurSoft__Contract_Signed_Date__c', null);
        hasFieldChanged(newList, oldMap, 'RecurSoft__Contract_Term_End_Date__c', null);
    }

    public static void checkAssetFieldChanges(Asset[] newList, Map<Id, Asset> oldMap) {

        hasFieldChanged(newList, oldMap, 'Active__c', null);
        hasFieldChanged(newList, oldMap, 'Subscription_Last_Modified_Date__c', null);
    }

    public static void checkProviderFieldChanges(Provider__c[] newList, Map<Id, Provider__c> oldMap) {

        hasFieldChanged(newList, oldMap, 'Premium_Member__c', null);
    }

    public static void checkCancelRequestFieldChanges(Cancel_Request__c[] newList, Map<Id, Cancel_Request__c> oldMap) {

        hasFieldChanged(newList, oldMap, 'Stage__c', 'Save');
        hasFieldChanged(newList, oldMap, 'Stage__c', 'Resume - No Change');
        hasFieldChanged(newList, oldMap, 'Stage__c', 'Cancelled');
        hasFieldChanged(newList, oldMap, 'Stage__c', 'No Sale');
    }

    public static void checkTaskFieldChanges(Task[] newList, Map<Id, Task> oldMap) {

        hasFieldChanged(newList, oldMap, 'Date_Completed_New__c', null);
        hasFieldChanged(newList, oldMap, 'ADR_Set__c', null);
        hasFieldChanged(newList, oldMap, 'Activity_Type__c', 'Group Practice');
    }

    public static Set<Id> hasFieldChanged(SObject[] newList, Map<Id, SObject> oldMap, String fieldName, String fieldValue) {

        Set<Id> results = new Set<Id>();

        for(SObject s : newList) {

            try {

                String objectType = s.getSObjectType().getDescribe().getName();
                String mapKeyChange = fieldValue == null ? objectType + fieldName + s.Id : objectType + fieldName + fieldValue + s.Id;
                String mapKeyValue = fieldValue == null ? objectType + fieldName : objectType + fieldName + fieldValue;             
                
                SObject sOld = fieldChangeMap.containsKey(mapKeyChange) ? fieldChangeMap.get(mapKeyChange) : oldMap.get(s.Id);

                //System.debug(fieldName + ' Old value: ' + sOld.get(fieldName) + ' ' + fieldName + ' New value: ' + s.get(fieldName));
                if(s.get(fieldName) != sOld.get(fieldName)){

                    fieldChangeMap.put(mapKeyChange, s.clone());

                    if((String.valueOf(s.get(fieldName)) == fieldValue || 
                        fieldValue == null)) {
                    
                        results.add(s.Id);
                        if(fieldChangeIdMap.containsKey(mapKeyValue)) {

                            fieldChangeIdMap.get(mapKeyValue).add(s.Id);
                        
                        } else {

                            fieldChangeIdMap.put(mapKeyValue, results);
                        }
                    }

                } else if(fieldChangeIdMap.containsKey(mapKeyValue) && fieldChangeIdMap.get(mapKeyValue).contains(s.Id)) {

                    fieldChangeIdMap.get(mapKeyValue).remove(s.Id);
                }

            } catch(Exception e) {

                System.debug(e);
            }
        }

        return results;
    }

    public static Set<Id> fieldChanges(SObject[] newList, Map<Id, SObject> oldMap, String fieldName, String fieldValue) {

        Set<Id> results = new Set<Id>();

        for(SObject s : newList) {

            try {

                String objectType = s.getSObjectType().getDescribe().getName();
                String mapKeyChange = fieldValue == null ? objectType + fieldName + s.Id : objectType + fieldName + fieldValue + s.Id;
                String mapKeyValue = fieldValue == null ? objectType + fieldName : objectType + fieldName + fieldValue;             
                
                SObject sOld = priorValueMap.containsKey(mapKeyChange) ? priorValueMap.get(mapKeyChange) : oldMap.get(s.Id);

                //System.debug(fieldName + ' Old value: ' + sOld.get(fieldName) + ' ' + fieldName + ' New value: ' + s.get(fieldName));
                if(s.get(fieldName) != sOld.get(fieldName)){

                    priorValueMap.put(mapKeyChange, s.clone());

                    if((String.valueOf(s.get(fieldName)) == fieldValue || 
                        fieldValue == null)) {
                    
                        results.add(s.Id);
                        if(fieldChangeIdMap2.containsKey(mapKeyValue)) {

                            fieldChangeIdMap2.get(mapKeyValue).add(s.Id);
                        
                        } else {

                            fieldChangeIdMap2.put(mapKeyValue, results);
                        }
                    }

                } else if(fieldChangeIdMap2.containsKey(mapKeyValue) && fieldChangeIdMap2.get(mapKeyValue).contains(s.Id)) {

                    fieldChangeIdMap2.get(mapKeyValue).remove(s.Id);
                }

            } catch(Exception e) {

                System.debug(e);
            }
        }

        return results;
    }

    public static Map<String, SObject> oldValuesMap = new Map<String, SObject>();
    public static Map<String, Set<Id>> fieldToIdSetMap = new Map<String, Set<Id>>();
    public static Map<String, Set<Id>> fieldToIdSetMapAfterUpdate = new Map<String, Set<Id>>();
    public static Boolean fieldChangeRecursion = false;

    public static void haveFieldsChanged(SObject[] newList, Map<Id, SObject> oldMap, String[] fieldChanges) 
    {
        for(SObject s : newList) 
        {
            for(String fieldChange : fieldChanges)
            {
                Set<Id> fieldChangedIds = new Set<Id>();
                String fieldName = fieldChange.substringBefore(',');
                String fieldValue = fieldChange.substringAfter(',');

                try 
                {
                    String objectType = s.getSObjectType().getDescribe().getName();
                    String oldValuesMapKey = fieldValue == '' ? objectType + '.' + fieldName + '.' + s.Id : objectType + '.' + fieldName + '.' + fieldValue + '.' + s.Id;
                    String fieldToIdSetMapKey = fieldValue == '' ? objectType + '.' + fieldName : objectType + '.' + fieldName + '.' + fieldValue;             
                    
                    SObject sOld = oldValuesMap.containsKey(oldValuesMapKey) ? oldValuesMap.get(oldValuesMapKey) : oldMap.get(s.Id);

                    System.debug(fieldName + ' Old value: ' + sOld.get(fieldName) + ' ' + fieldName + ' New value: ' + s.get(fieldName));

                    if(s.get(fieldName) != sOld.get(fieldName))
                    {
                        oldValuesMap.put(oldValuesMapKey, s.clone());

                        if((String.valueOf(s.get(fieldName)) == fieldValue || 
                            fieldValue == '')) 
                        {
                            fieldChangedIds.add(s.Id);
                            if(fieldToIdSetMap.containsKey(fieldToIdSetMapKey)) 
                            {
                                fieldToIdSetMap.get(fieldToIdSetMapKey).add(s.Id);
                            } 
                            else 
                            {
                                fieldToIdSetMap.put(fieldToIdSetMapKey, fieldChangedIds);
                            }
                        }

                    } 
                    else if(fieldToIdSetMap.containsKey(fieldToIdSetMapKey) && 
                        fieldToIdSetMap.get(fieldToIdSetMapKey).contains(s.Id)) 
                    {
                        fieldToIdSetMap.get(fieldToIdSetMapKey).remove(s.Id);
                    }

                } 
                catch(Exception e) 
                {
                    System.debug(e);
                }
            }
        }
    }
}