src.3/objects/Asset.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Notes whether or not the Asset is being billed.</description>
        <inlineHelpText>Notes whether or not the Asset is being billed.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract_End_Date__c</fullName>
        <description>Used for setting Contract Term End Date on &quot;Add Product&quot; Opportunities.  Set by a rollup summary.</description>
        <inlineHelpText>Used for setting Contract Term End Date on &quot;Add Product&quot; Opportunities.  Set by a rollup summary.</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Current_Product_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Shows the related subscription that has the most distant Contract End Date that is not Terminated.  Set from trigger.  Trigger activated by Subscription Last Modified field.</description>
        <label>Current Product Subscription</label>
        <referenceTo>RecurSoft__Product_Subscription__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Next_Invoice_Date__c</fullName>
        <description>Used in setting the Contract Term Start Date for &quot;Add Product&quot; Opportunities. Set by rollup summary.</description>
        <inlineHelpText>Used in setting the Contract Term Start Date for &quot;Add Product&quot; Opportunities. Set by rollup summary.</inlineHelpText>
        <label>Next Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related Provider record for Healthgrades Assets</description>
        <inlineHelpText>The related Provider record for Healthgrades Assets</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the related Provider record</description>
        <inlineHelpText>Link to the related Provider record</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Signed_Date__c</fullName>
        <label>Contract Signed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_End_Date__c</fullName>
        <label>Contract Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_Start_Date__c</fullName>
        <label>Contract Term Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Initial_Contract_Term__c</fullName>
        <defaultValue>12</defaultValue>
        <inlineHelpText>Contract duration, in months.</inlineHelpText>
        <label>Contract Term (Months)</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Renewal_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Determines the system behaviour at the time of renewing the subscription.</inlineHelpText>
        <label>Renewal Rule</label>
        <referenceTo>RecurSoft__Renewal_Rule__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>RecurSoft_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Trial__c</fullName>
        <description>Trial Period in Days.</description>
        <inlineHelpText>Period during which contracts can be cancelled without penalties.</inlineHelpText>
        <label>Trial Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0 - Waived</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                    <default>true</default>
                    <label>60</label>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Healthgrades</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <description>For selling Healthgrades Premium Profiles</description>
        <label>Healthgrades</label>
    </recordTypes>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <label>Renewal</label>
    </recordTypes>
</CustomObject>

src.3/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Base_Contract_Term__c</fullName>
        <label>Base Contract Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Co_Terminate__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Determines if the Opportunity Product should be forced to co-terminate with all other Opportunity Products, regardless of free months.</description>
        <inlineHelpText>Determines if the Opportunity Product should be forced to co-terminate with all other Opportunity Products, regardless of free months.</inlineHelpText>
        <label>Co-Terminate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Free_Month_Setting__c</fullName>
        <description>Override opportunity free months</description>
        <label>Orientation Month Setting</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Extend Contract - At the Beginning</fullName>
                </value>
                <value>
                    <fullName>Include in Contract Period - At the Beginning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Promo_Item__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Promo Item</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Free_Months__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Override opportunity free months</description>
        <inlineHelpText>Override opportunity free months</inlineHelpText>
        <label>Number of Orientation Months</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Override_Modified_Subscription__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Override Modified Subscription</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related Provider for the Healthgrades Premium Profile</description>
        <inlineHelpText>The related Provider for the Healthgrades Premium Profile</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Billing_Frequency__c</fullName>
        <formula>IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;One-Time&quot;), &quot;One-Time&quot;,
IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;Monthly&quot;), &quot;Monthly&quot;,
IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;Quarterly&quot;), &quot;Quarterly&quot; ,
IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;Semi-Annual&quot;), &quot;Semi-Annual&quot;,
IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;Yearly&quot;), &quot;Yearly&quot; ,
IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;Milestones&quot;), &quot;Milestones&quot; , &quot;&quot;
)
)
)
)
)
)</formula>
        <inlineHelpText>Default billing frequency of the product.</inlineHelpText>
        <label>Billing Frequency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term1__c</fullName>
        <inlineHelpText>Contract duration.</inlineHelpText>
        <label>Contract Term</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_End_Date_Editable__c</fullName>
        <label>Contract Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_End_Date__c</fullName>
        <formula>DATE(
year(RecurSoft__Contract_Term_Start_Date_New__c)+ floor((month(RecurSoft__Contract_Term_Start_Date_New__c) + VALUE(RecurSoft__Contract_Term1__c))/12) + if(and(month(RecurSoft__Contract_Term_Start_Date_New__c)=12,VALUE(RecurSoft__Contract_Term1__c)&gt;=12),-1,0)
,if( mod( month(RecurSoft__Contract_Term_Start_Date_New__c) + VALUE(RecurSoft__Contract_Term1__c) , 12 ) = 0, 12 , mod( month(RecurSoft__Contract_Term_Start_Date_New__c) + VALUE(RecurSoft__Contract_Term1__c) , 12 ))
,min(day(RecurSoft__Contract_Term_Start_Date_New__c),case(max( mod( month(RecurSoft__Contract_Term_Start_Date_New__c) + VALUE(RecurSoft__Contract_Term1__c) , 12 ) , 1),9,30,4,30,6,30,11,30,2,28,31))
)-1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deprecated - Contract Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_Setting__c</fullName>
        <inlineHelpText>Contract duration options: months, days.</inlineHelpText>
        <label>Contract Term Setting</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Months</fullName>
                </value>
                <value>
                    <fullName>Days</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_Start_Date_New__c</fullName>
        <label>Contract Term Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_Start_Date__c</fullName>
        <formula>Opportunity.RecurSoft__Contract_Term_Start_Date1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deprecated - Contract Term Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Renewal_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Determines the system behaviour at the time of renewing the subscription.</inlineHelpText>
        <label>Renewal Rule</label>
        <referenceTo>RecurSoft__Renewal_Rule__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>RecurSoft_Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial__c</fullName>
        <label>Trial Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>120</fullName>
                </value>
                <value>
                    <fullName>180</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.3/objects/Product2.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Default_Contract_Term__c</fullName>
        <description>If Inherit Opportunity Contract Terms is false, the Contract Term will be set on the Opportunity Product to (Default Contract Term + Product Number of Free Months) and reset to this value when an Opportunity contract term change is made. For month-to-month products.</description>
        <inlineHelpText>If Inherit Opportunity Contract Terms is false, the Contract Term will be set on the Opportunity Product to (Default Contract Term + Product Number of Free Months) and reset to this value when an Opportunity contract term change is made.</inlineHelpText>
        <label>Default Contract Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Default_Co_Terminate__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Sets the default for co-termination on the related Opportunity Products.  Can be overridden at the Opportunity Product level.</description>
        <inlineHelpText>Sets the default for co-termination on the related Opportunity Products.  Can be overridden at the Opportunity Product level.</inlineHelpText>
        <label>Default Co-Terminate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Default_Renewal_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Provides the Default Renewal Rule for this Product. Will be set on Opportunity Products.</description>
        <inlineHelpText>Provides the Default Renewal Rule for this Product. Will be set on Opportunity Products.</inlineHelpText>
        <label>Default Renewal Rule</label>
        <referenceTo>RecurSoft__Renewal_Rule__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Billing_Frequency__c</fullName>
        <inlineHelpText>The frequency at which customer is invoiced.</inlineHelpText>
        <label>Billing Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One-Time</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-annual</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>Milestones</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.2/classes/OppLineItemUtilities.cls
public class OppLineItemUtilities {

	private static String HEALTHGRADES_PRODUCT_CODE = '3005';

	/**
	 * Query used to populate the OppLineItemsTriggerHandler.relatedOpportunitiesMap static variable. Data is cached to prevent repeated SOQL queries
	 * @param newOppLis - Trigger.new
	 * @return Opportunity map for static variable cache
	 * @see OppLineItemTriggerHandler.OnBeforeInsert
	 */
	public static Map<Id, Opportunity> getRelatedOpps(OpportunityLineItem[] newOppLis) {

		Set<ID> newOppIds = new Set<ID>();
		
		for(OpportunityLineItem oppLi : newOppLis) {
			newOppIds.add(oppLi.OpportunityId);
		}
		
		Map<ID, Opportunity> results = new Map<ID, Opportunity> (
			[SELECT Id, 
			RecordType.Name,
			AccountId,
			StageName, 
			RecurSoft__Initial_Contract_Term__c, 
			RecurSoft__Contract_Term_Start_Date__c, 
			RecurSoft__Contract_Signed_Date__c,
			RecurSoft__Contract_Term_End_Date__c, 
			HasOpportunityLineItem,
			CreatedBy.Name,
			(SELECT Id,
		    	Is_Promo_Item__c,
		    	ListPrice,
		    	UnitPrice,
		    	TotalPrice,
		    	Quantity,
		    	Number_of_Free_Months__c,
		    	Free_Month_Setting__c,
		    	Co_Terminate__c,
		    	Base_Contract_Term__c,
		    	RecurSoft__Contract_Term_End_Date_Editable__c,
		    	RecurSoft__Contract_Term_Start_Date_New__c,
		    	RecurSoft__Contract_Term1__c,
		    	RecurSoft__Contract_Term_Setting__c,
		    	RecurSoft__Renewal_Rule__c,
		    	OpportunityId,
		    	PricebookEntryId,
		    	PriceBookEntry.Name,
		    	PriceBookEntry.UnitPrice,
		    	PricebookEntry.Product2Id, 
		    	PricebookEntry.Product2.Name,
		    	PricebookEntry.Product2.ProductCode,
		    	PricebookEntry.Pricebook2Id, 
		    	Product2.Default_Renewal_Rule__c, 
		    	Product2.Family, 
		    	Product2.Default_Contract_Term__c, 
		    	Product2.Default_Co_Terminate__c, 
		    	Product2.RecurSoft__Billing_Frequency__c 
		    	FROM OpportunityLineItems 
		    	ORDER BY RecurSoft__Contract_Term_End_Date_Editable__c ASC)
			FROM Opportunity
			WHERE Id IN :newOppIds]);

		return results;
	}

	public static Map<Id, Product2> getRelatedProducts(OpportunityLineItem[] newOppLis) {

		Set<ID> productIds = new Set<ID>();
		
		for(OpportunityLineItem oppLi : newOppLis) {
			productIds.add(oppLi.Product2Id);
		}
		
		Map<ID, Product2> results = new Map<ID, Product2> (
			[SELECT Id, 
			Family, 
			Default_Renewal_Rule__c, 
		    Default_Contract_Term__c, 
		    Default_Co_Terminate__c, 
		    RecurSoft__Billing_Frequency__c 
			FROM Product2]);

		return results;
	}

	public static Map<Id, Account> getRelatedAccounts(Opportunity[] listOpps) {

		Set<ID> acctIds = new Set<ID>();
		
		for(Opportunity o : listOpps) {
			acctIds.add(o.AccountId);
		}
		
		Map<ID, Account> results = new Map<ID, Account> (
			[SELECT Id,
			(SELECT Id, 
				Next_Invoice_Date__c, 
				Contract_End_Date__c,
				Active__c
				FROM Assets
				WHERE Product2.Family = 'SR Platform'
				AND Active__c = true) 
			FROM Account
			WHERE Id IN :acctIds]);

		return results;
	}

	public static Map<String, Id> getRelatedAcccountAssets(OpportunityLineItem[] listOppLis) {

		Set<ID> acctIds = new Set<ID>();
		Map<String, Id> currentSubscriptionMap = new Map<String, Id>();
		
		for(OpportunityLineItem oppLi : listOppLis) {
			
			acctIds.add(oppLi.Opportunity.AccountId);
		}
		
		Account[] acctList = [SELECT Id,
			(SELECT Id,
				Product2.Family,
				Provider__c,
				Current_Product_Subscription__c 
				FROM Assets)
			FROM Account
			WHERE Id IN :acctIds];

		for(Account a : acctList) {

			if(a.Assets.isEmpty()) continue;

			for(Asset ast : a.Assets) {

				currentSubscriptionMap.put(String.valueOf(a.Id) + ast.Product2.Family + ast.Provider__c, ast.Current_Product_Subscription__c);

				if(ast.Product2.Family == 'SR Platform') currentSubscriptionMap.put(String.valueOf(a.Id), ast.Current_Product_Subscription__c);
			}
		}

		return currentSubscriptionMap;
	}

	public static Map<Id, OpportunityLineItem> getOppLiData(Set<Id> oppLiIds) {

		Map<Id, OpportunityLineItem> results = new Map<Id, OpportunityLineItem>([SELECT Id,
		Opportunity.RecurSoft__Trial__c,
		Product2.Name,
		Product2.ProductCode,
		Product2.Family,
		Provider__c,
		OpportunityId,
		Opportunity.AccountId,
		Opportunity.RecordType.Name,
		Opportunity.StageName,
		Override_Modified_Subscription__c,
		Modified_Subscription__c,
		Override_Current_SR_Subscription__c,
		Current_SR_Subscription__c,
		Trial__c
		FROM OpportunityLineItem
		WHERE Id IN :oppLiIds]);

		return results;
	}

	/**
	 * A Healthgrades product should always be alone on an Opportunity. 
	 * Validation to prevent adding a Healthgrades product to an Opportunity with existing products.
	 * Validation to prevent adding additional products to an Opportunity with an existing Healthgrades product.
	 * @param updatedOppLis - Trigger.new
	 * @param relatedOppMap - previously cached map with related Opportunities
	 * @see OppLineItemTriggerHandler.OnBeforeInsert
	 */
	public static void validateNoMixedProducts(OpportunityLineItem[] updatedOppLis, Map<Id, Opportunity> relatedOppMap) {

		for(OpportunityLineItem oppLi : updatedOppLis) {

			if(relatedOppMap.containsKey(oppLi.OpportunityId) && relatedOppMap.get(oppLi.OpportunityId).HasOpportunityLineItem) {
			
				if(oppLi.Product_Code__c == HEALTHGRADES_PRODUCT_CODE) {

					oppLi.Quantity.addError(Label.Error_Healthgrades_Mix_Products);

				} else {

					for(OpportunityLineItem relatedOppLi : relatedOppMap.get(oppLi.OpportunityId).OpportunityLineItems) {

						if(relatedOppLi.PricebookEntry.Product2.ProductCode == HEALTHGRADES_PRODUCT_CODE) {
							
							oppLi.Quantity.addError(Label.Error_Healthgrades_Mix_Products2);
						}
					}
				}
			}
		}
	}

	public static void validateHealthgradesProvider(OpportunityLineItem[] updatedOppLis) {

		String errorMsg = 'You must add a Provider with the Healthgrades Premium Profile';

		for(OpportunityLineItem oppLi : updatedOppLis) {
			
			if(oppLi.Product_Code__c == HEALTHGRADES_PRODUCT_CODE && oppLi.Provider__c == null) {

				oppLi.Quantity.addError(errorMsg);
			}
		}
	}

	public static void validateNoDuplicateProducts(OpportunityLineItem[] updatedOppLis, Map<Id, Opportunity> relatedOppMap, Map<Id, Product2> relatedProductMap) {

		Map<Id, Set<String>> productFamily = new Map<Id, Set<String>>();
		String errorMsg = 'There can only be one Product from each Product Family';

		for(OpportunityLineItem oppLi : updatedOppLis) {

			productFamily.put(oppLi.OpportunityId, null);
		}

		for(OpportunityLineItem oppLi : updatedOppLis) {

			Opportunity o = relatedOppMap.get(oppLi.OpportunityId);
			if(o == null) continue;
			if(o.RecordType.Name == 'Renewal' || o.RecordType.Name == 'Add-On Business') continue;
			Product2 p = relatedProductMap.get(oppLi.Product2Id);
			Set<String> oppProductFamily = productFamily.get(o.Id) == null ? new Set<String>() : productFamily.get(o.Id);

			if(o.OpportunityLineItems.size() > 0) {

				for(OpportunityLineItem oppLi2 : o.OpportunityLineItems) {

					Product2 p2 = relatedProductMap.get(oppLi2.Product2Id);

					if(p2.Family == null) continue;
					
					oppProductFamily.add(p2.Family);
				}

				productFamily.put(o.Id, oppProductFamily);
			}

			if(p.Family == null) continue;

			if(oppProductFamily.contains(p.Family)) {

				oppLi.addError(errorMsg);
			
			} else {

				oppProductFamily.add(p.Family);
				productFamily.put(o.Id, oppProductFamily);
			}
		}
	}

	/*@future public static void setOppTrialPeriod(Set<Id> oppLiIds) {

		Map<ID, SObject> mapInsertSObject = new Map<ID, SObject>();
		Map<ID, SObject> mapUpdateSObject = new Map<ID, SObject>();
		Map<ID, SObject> mapDeleteSObject = new Map<ID, SObject>();
		Map<Id, OpportunityLineItem> oppLiDataMap = getOppLiData(oppLiIds);

		for(OpportunityLineItem oppLi : oppLiDataMap.values()) {

			if(oppLi.Product2.ProductCode == '3000' && oppLi.Trial__c != oppLi.Opportunity.RecurSoft__Trial__c) {

				Opportunity o = new Opportunity();
				o.Id = oppLi.OpportunityId;
				o.RecurSoft__Trial__c = oppLi.Trial__c;
				mapUpdateSObject.put(o.Id, o);
			}
		}

		SRUtilities.runDml(mapInsertSObject, mapUpdateSObject, mapDeleteSObject, 'OppLineItemUtilities.setOppTrialPeriod');
	}*/

	//Defaults set on insert... will be overwritten for Add Product/Healthgrade Opps
	public static void setContractDefaults(OpportunityLineItem[] updatedOppLis, Map<Id, Product2> relatedProductMap, Map<Id, Opportunity> relatedOppMap) {

		for(OpportunityLineItem oppLi : updatedOppLis) {

			if(!relatedProductMap.containsKey(oppLi.Product2Id)) return;
			if(!relatedOppMap.containsKey(oppLi.OpportunityId)) return;

			Product2 product = relatedProductMap.get(oppLi.Product2Id);
			Opportunity opp = relatedOppMap.get(oppLi.OpportunityId);

			//Co-Terminate flag will determine if contract end date is forced to coterminate or go with product defaults
			oppLi.Co_Terminate__c = product.Default_Co_Terminate__c;

			//Base contract term is set on the product for non-coterminating products(month-to-month), otherwise, it's set on the Opp
			oppLi.Base_Contract_Term__c = !product.Default_Co_Terminate__c ? Integer.valueOf(product.Default_Contract_Term__c) :
				opp.RecurSoft__Initial_Contract_Term__c == null ? 24 : Integer.valueOf(opp.RecurSoft__Initial_Contract_Term__c);

			//Free month setting cleared if no free months added
			oppLi.Free_Month_Setting__c = oppLi.Number_of_Free_Months__c == null || oppLi.Number_of_Free_Months__c == 0 ? null : oppLi.Free_Month_Setting__c;
			
			//RecurSoft contract term field is calculated based on free months and setting
			oppLi.RecurSoft__Contract_Term1__c = oppLi.Free_Month_Setting__c == 'Extend Contract - At the Beginning' ?
					String.valueOf(oppLi.Base_Contract_Term__c + oppLi.Number_of_Free_Months__c) + ' Months' : 
					String.valueOf(oppLi.Base_Contract_Term__c) + ' Months';

			//Always calculated in months
			oppLi.RecurSoft__Contract_Term_Setting__c = 'Months';

			//Set the default renewal rule if blank
			if(oppLi.RecurSoft__Renewal_Rule__c == null) {

				System.debug('renewal rule here');
				System.debug(product.Default_Renewal_Rule__c);
				oppLi.RecurSoft__Renewal_Rule__c = product.Default_Renewal_Rule__c;
			}
		}
	}

	//On insert overwrites defaults, updates if either contract start or end date is edited
	public static void setAddProductDates(OpportunityLineItem[] updatedOppLis) {

		if(FlowControl.hgContractDatesSet) return;

		Map<Id, Opportunity> relatedOppMap = getRelatedOpps(updatedOppLis);
		Map<Id, Account> relatedAccountMap = getRelatedAccounts(relatedOppMap.values());

		for(OpportunityLineItem oppLi : updatedOppLis) {

			Opportunity o = relatedOppMap.get(oppLi.OpportunityId);
			Account a = relatedAccountMap.get(o.AccountId);

			//Exit if not an Add Product or Healthgrades opp, or if opp is closed
			if(o.RecordType.Name != 'Healthgrades' && o.RecordType.Name != 'Add Product') continue;
			if(o.StageName == 'Closed Won' || o.StageName == 'Closed Lost') continue;
			if(o.CreatedBy.Name == 'API User') continue;

			Integer freeMonths;
			Integer contractTerm;

			if(a.Assets.isEmpty()) {

				oppLi.RecurSoft__Contract_Term_Start_Date_New__c = null;
				oppLi.RecurSoft__Contract_Term_End_Date_Editable__c = null;

			} else {

				freeMonths = oppLi.Number_of_Free_Months__c == null ? 0 : Integer.valueOf(oppLi.Number_of_Free_Months__c);
				contractTerm = Integer.valueOf(oppLi.Base_Contract_Term__c);

				System.debug(a.Assets[0].Contract_End_Date__c);

				//Set contract start to next invoice date on SR Platform asset
				oppLi.RecurSoft__Contract_Term_Start_Date_New__c = o.RecurSoft__Contract_Signed_Date__c == null ? Date.today() : o.RecurSoft__Contract_Signed_Date__c;
				//If coterminate set, contract end date set to SR Platform asset end date, otherwise, calculated
				if(a.Assets[0].Contract_End_Date__c != null && oppLi.Co_Terminate__c)
				{
					oppLi.RecurSoft__Contract_Term_End_Date_Editable__c = oppLi.RecurSoft__Contract_Term_Start_Date_New__c
						.addMonths(oppLi.RecurSoft__Contract_Term_Start_Date_New__c.monthsBetween(a.Assets[0].Contract_End_Date__c))
						.addDays(-1);
				}
				else
				{
					oppLi.RecurSoft__Contract_Term_End_Date_Editable__c = oppLi.Free_Month_Setting__c == 'Extend Contract - At the Beginning' ?
						oppLi.RecurSoft__Contract_Term_Start_Date_New__c.addMonths(contractTerm + freeMonths).addDays(-1) : 
						oppLi.RecurSoft__Contract_Term_Start_Date_New__c.addMonths(contractTerm).addDays(-1);
				}
			}
		}
	}

	@future public static void setCoTerminationDates(Set<Id> oppLiIds) {

		Map<ID, SObject> mapInsertSObject = new Map<ID, SObject>();
		Map<ID, SObject> mapUpdateSObject = new Map<ID, SObject>();
		Map<ID, SObject> mapDeleteSObject = new Map<ID, SObject>();

		OpportunityLineItem[] listOppLi = [SELECT Id, OpportunityId FROM OpportunityLineItem WHERE Id IN :oppLiIds];
		Map<Id, Opportunity> relatedOppMap = getRelatedOpps(listOppLi);

		for(Opportunity o : relatedOppMap.values()) {

			if(o.StageName == 'Closed Won' || o.StageName == 'Closed Lost') continue;

			Integer contractTerm;
			Integer freeMonths;
			Date contractEndDate;
			Date maxContractEndDate;

			//Find the max contract end date of all OppLineItems, in order to match all co-terminating products
			for(OpportunityLineItem oppLi : o.OpportunityLineItems) {

				if(oppLi.RecurSoft__Contract_Term_Start_Date_New__c == null) continue;

				//If the product is co-terminating, use the Opportunity base contract term, otherwise use the OppLineItem base contract term
				contractTerm = !oppLi.Co_Terminate__c ? Integer.valueOf(oppLi.Base_Contract_Term__c) :
					o.RecurSoft__Initial_Contract_Term__c == null ? 24 : Integer.valueOf(o.RecurSoft__Initial_Contract_Term__c);
				
				freeMonths = oppLi.Number_of_Free_Months__c == null ? 0 : Integer.valueOf(oppLi.Number_of_Free_Months__c);
				
				contractEndDate = oppLi.Free_Month_Setting__c == 'Extend Contract - At the Beginning' ?
					oppLi.RecurSoft__Contract_Term_Start_Date_New__c.addMonths(contractTerm + freeMonths).addDays(-1) : 
					oppLi.RecurSoft__Contract_Term_Start_Date_New__c.addMonths(contractTerm).addDays(-1);
				
				maxContractEndDate = maxContractEndDate == null ? contractEndDate :
					contractEndDate > maxContractEndDate ? contractEndDate : maxContractEndDate;

				//If the product is not co-terminating, set the contract end date
				if(!oppLi.Co_Terminate__c && oppLi.RecurSoft__Contract_Term_End_Date_Editable__c != contractEndDate) {

					oppLi.RecurSoft__Contract_Term_End_Date_Editable__c = contractEndDate;
					oppLi.Free_Month_Setting__c = oppLi.Number_of_Free_Months__c == null || oppLi.Number_of_Free_Months__c == 0 ? null : oppLi.Free_Month_Setting__c;
					mapUpdateSObject.put(oppLi.Id, oppLi);
				}
			}

			//Set contract end date on all co-terminating products to the max contract end date
			for(OpportunityLineItem oppLi2 : o.OpportunityLineItems) {

				if(oppLi2.Co_Terminate__c) { 

					if(oppLi2.RecurSoft__Contract_Term_End_Date_Editable__c != maxContractEndDate) {

						oppLi2.RecurSoft__Contract_Term_End_Date_Editable__c = maxContractEndDate;
						oppLi2.Free_Month_Setting__c = oppLi2.Number_of_Free_Months__c == null || oppLi2.Number_of_Free_Months__c == 0 ? null : oppLi2.Free_Month_Setting__c;
						mapUpdateSObject.put(oppLi2.Id, oppLi2);
					}
				}
			}
		}

		SRUtilities.runDml(mapInsertSObject, mapUpdateSObject, mapDeleteSObject, 'OppLineItemUtilities.setCoTerminationDates');
	}

	public static void setModifiedSubscription(OpportunityLineItem[] newList, Map<Id, OpportunityLineItem> updatedOppLis, Boolean doDML) {

		Map<ID, SObject> mapInsertSObject = new Map<ID, SObject>();
		Map<ID, SObject> mapUpdateSObject = new Map<ID, SObject>();
		Map<ID, SObject> mapDeleteSObject = new Map<ID, SObject>();

		Set<Id> acctIds = new Set<Id>();

		Map<Id, OpportunityLineItem> oppLiDataMap = getOppLiData(updatedOppLis.keySet());
		Map<String, Id> currentSubscriptionMap = getRelatedAcccountAssets(oppLiDataMap.values());
		System.debug(currentSubscriptionMap);


		for(OpportunityLineItem oppLi : newList) {

			OpportunityLineItem oppLi2 = oppLiDataMap.get(oppLi.Id);

			if((!doDML && oppLi2.Opportunity.StageName != 'Closed Won')
				&& !oppLi.Override_Modified_Subscription__c 
				&& oppLi2.Opportunity.RecordType.Name == 'Add-On Business'
				&& currentSubscriptionMap.containsKey(oppLi2.Opportunity.AccountId + oppLi2.Product2.Family + oppLi2.Provider__c)
				&& oppLi.Modified_Subscription__c != currentSubscriptionMap.get(oppLi2.Opportunity.AccountId + oppLi2.Product2.Family + oppLi2.Provider__c)) {

				oppLi.Modified_Subscription__c = currentSubscriptionMap.get(oppLi2.Opportunity.AccountId + oppLi2.Product2.Family + oppLi2.Provider__c);
				mapUpdateSObject.put(oppLi.Id, oppLi);
			}

			if((!doDML && oppLi2.Opportunity.StageName != 'Closed Won')
				&& !oppLi.Override_Current_SR_Subscription__c
				&& oppLi2.Opportunity.RecordType.Name == 'Add-On Business'
				&& currentSubscriptionMap.containsKey(oppLi2.Opportunity.AccountId)
				&& oppLi.Current_SR_Subscription__c != currentSubscriptionMap.get(oppLi2.Opportunity.AccountId)) {

				oppLi.Current_SR_Subscription__c = currentSubscriptionMap.get(oppLi2.Opportunity.AccountId);
				mapUpdateSObject.put(oppLi.Id, oppLi);
			}
		}

		if(doDML) SRUtilities.runDml(mapInsertSObject, mapUpdateSObject, mapDeleteSObject, 'OppLineItemUtilities.setModifiedSubscription');
	}
}