src.3/objects/CorpDev_Account__c.object
<CustomObject>
    <label>CorpDev Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CorpDev Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src.2/objects/CorpDev_Contact__c.object
<CustomObject>
    <label>CorpDev Contact</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CorpDev Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>CorpDev_Account__c</fullName>
        <label>CorpDev Account</label>
        <referenceTo>CorpDev_Account__c</referenceTo>
        <relationshipLabel>CorpDev Contacts</relationshipLabel>
        <relationshipName>CorpDev_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

src.1/objects/CorpDev_Opportunity__c.object
<CustomObject>
    <label>CorpDev Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CorpDev Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>CorpDev_Account__c</fullName>
        <label>CorpDev Account</label>
        <referenceTo>CorpDev_Account__c</referenceTo>
        <relationshipLabel>CorpDev Opportunities</relationshipLabel>
        <relationshipName>CorpDev_Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

src.2/classes/CorpDevQuickAdd_Controller.cls
public with sharing class CorpDevQuickAdd_Controller 
{
	public CorpDev_Account__c a { get; set; }
	public CorpDev_Opportunity__c o { get; set; }
	public CorpDev_Contact__c c { get; set; }
	
	public CorpDevQuickAdd_Controller(ApexPages.StandardController stdController) 
	{			
        a = new CorpDev_Account__c();
        o = new CorpDev_Opportunity__c();
        c = new CorpDev_Contact__c();
	}

	public PageReference saveRecords()
	{
		if(a.Name != null) insert a;
		if(o.Name != null) 
		{
			o.CorpDev_Account__c = a.Id;
			insert o;
		}
		if(c.Name != null)
		{
			c.CorpDev_Account__c = a.Id;
			insert c;
		}

		PageReference newPage = new PageReference('/' + a.Id);
		newPage.setRedirect(true);
		return newPage;
	}

	public PageReference cancel()
	{
		PageReference homePage = new PageReference('/');
		homePage.setRedirect(true);
		return homePage;
	}
}