src.3/objects/Management_System__c.object
<CustomObject>
    <label>Management System</label>
    <nameField>
        <label>Management System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Management Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Limelight_Available__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SR Schedule Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Engineer_Call_Needed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sales Engineer Call Needed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SYNC_Availability__c</fullName>
        <inlineHelpText>Being Built= an integration engineer is currently building this SYNC
Discovery= research is being done if we can integrate 
Cannot Integrate= DO NOT SELL
Business Negotiation= we are looking into making a business agreement
SYNC Complete= Sail Away</inlineHelpText>
        <label>SYNC Availability</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Discovery</fullName>
                </value>
                <value>
                    <fullName>In Development</fullName>
                    <label>Sales Engineer List</label>
                </value>
                <value>
                    <fullName>SYNC Complete</fullName>
                </value>
                <value>
                    <fullName>Blacklist - DO NOT SELL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

src.1/classes/ManagementSystemsSelector.cls
public class ManagementSystemsSelector extends fflib_SObjectSelector 
{
	public Schema.SObjectField[] getSObjectFieldList() 
	{
		return new List<Schema.SObjectField> {
			Management_System__c.Id,
			Management_System__c.Limelight_Available__c,
			Management_System__c.Name,
			Management_System__c.Sales_Engineer_Call_Needed__c,
			Management_System__c.Version__c
			};
	}

	public Schema.SObjectType getSObjectType()
	{
		return Management_System__c.SObjectType;
	}

	public static ManagementSystemsSelector newInstance()
	{
		return (ManagementSystemsSelector) Application.Selector.newInstance(Management_System__c.SObjectType);
	}

	public Map<String, Id> selectNameToIdMap()
	{
		Map<String, Id> results = new Map<String, Id>();

		fflib_QueryFactory managementSystemQueryFactory = newQueryFactory();

		Management_System__c[] allPms = Database.query(
			managementSystemQueryFactory
			.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList()))
			.addOrdering('Name', fflib_QueryFactory.SortOrder.ASCENDING)
			.toSOQL());

		for(Management_System__c pm : allPms)
		{
			results.put(pm.Name, pm.Id);
		}

		return results;
	}

	public List<Management_System__c> selectNonBlacklistedManagementSystems()
	{
		fflib_QueryFactory managementSystemQueryFactory = newQueryFactory();

		return (Management_System__c[]) Database.query(
				managementSystemQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList())).setCondition('SYNC_Availability__c != \'Blacklist - DO NOT SELL\'').toSOQL());
	}

}