src.3/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Competitor_Buyout__c</fullName>
        <label>Competitor Buyout</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>4 Patient Care</fullName>
                </value>
                <value>
                    <fullName>DemandForce</fullName>
                </value>
                <value>
                    <fullName>eCentral</fullName>
                </value>
                <value>
                    <fullName>eReminders</fullName>
                </value>
                <value>
                    <fullName>Lighthouse</fullName>
                </value>
                <value>
                    <fullName>Patient Activator</fullName>
                </value>
                <value>
                    <fullName>Phone Tree</fullName>
                </value>
                <value>
                    <fullName>PM/EMR</fullName>
                </value>
                <value>
                    <fullName>Practice Mojo</fullName>
                </value>
                <value>
                    <fullName>Sesame</fullName>
                </value>
                <value>
                    <fullName>Teledental</fullName>
                </value>
                <value>
                    <fullName>Televox</fullName>
                </value>
                <value>
                    <fullName>Weave</fullName>
                </value>
                <value>
                    <fullName>Websystem3</fullName>
                </value>
                <value>
                    <fullName>RevenueWell</fullName>
                </value>
                <value>
                    <fullName>ZocDoc</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Free_Month_Setting__c</fullName>
        <description>Override opportunity free months</description>
        <label>Orientation Month Setting</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Extend Contract - At the Beginning</fullName>
                </value>
                <value>
                    <fullName>Include in Contract Period - At the Beginning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Free_Months__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Override opportunity free months</description>
        <inlineHelpText>Override opportunity free months</inlineHelpText>
        <label>Number of Orientation Months</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Promotional_Price__c</fullName>
        <description>Allows for giving promotional months at a discounted price.</description>
        <label>Orientation Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_Start_Date__c</fullName>
        <formula>Opportunity.RecurSoft__Contract_Term_Start_Date1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deprecated - Contract Term Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Product_Subscription__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This field contains product subscription for current opportunity product.</inlineHelpText>
        <label>Product Subscription</label>
        <referenceTo>RecurSoft__Product_Subscription__c</referenceTo>
        <relationshipLabel>Opportunity Product (Product Subscription)</relationshipLabel>
        <relationshipName>RecurSoft_Opportunity_Product3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <formula>IF( Is_Monthly__c ,
IF( TEXT( Trial__c ) = &quot;&quot; ,
 null ,
 RecurSoft__Contract_Term_Start_Date_New__c + VALUE( TEXT( Trial__c ))) ,
null )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

src.4/classes/ProductSubscriptions.cls
public class ProductSubscriptions extends fflib_SObjectDomain 
{
	public ProductSubscriptions(RecurSoft__Product_Subscription__c[] subscriptions) 
	{
		super(subscriptions);	
		Configuration.disableTriggerCRUDSecurity();
	}

	public class Constructor implements fflib_SObjectDomain.IConstructable
	{
		public fflib_SObjectDomain construct(List<SObject> sObjectList)
		{
			return new ProductSubscriptions(sObjectList);
		}
	}

	public override void onBeforeInsert()
	{
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        SRUtilities.SRUnitOfWork sruow = new SRUtilities.SRUnitOfWork();

        this.syncSubscriptionWithOpportunityLineItem(uow, sruow);

        uow.registerWork(sruow);
        uow.commitWork();
	}

	public override void onAfterInsert()
	{
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        SRUtilities.SRUnitOfWork sruow = new SRUtilities.SRUnitOfWork();

        SRUtilities.scheduleAsync(new Map<Id, RecurSoft__Product_Subscription__c>((RecurSoft__Product_Subscription__c[]) Records).keySet(), AsyncMain.TYPE_PRODSUB_AFTERINSERT);

        uow.registerWork(sruow);
        uow.commitWork();
	}

	public override void onBeforeUpdate(Map<Id, SObject> existingRecords)
	{
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        SRUtilities.SRUnitOfWork sruow = new SRUtilities.SRUnitOfWork();

        this.syncSubscriptionWithOpportunityLineItem(uow, sruow);
        
        uow.registerWork(sruow);
        uow.commitWork();
	}

	public void syncSubscriptionWithOpportunityLineItem(fflib_SObjectUnitOfWork uow, SRUtilities.SRUnitOfWork sruow) 
	{
		Map<Id, OpportunityLineItem> oppLiMap = new Map<Id, OpportunityLineItem>(OpportunityLineItemsSelector.newInstance().selectByProductSubscriptions((RecurSoft__Product_Subscription__c[]) Records));

		for(RecurSoft__Product_Subscription__c subscription : (RecurSoft__Product_Subscription__c[]) Records) 
		{
			if(subscription.RecurSoft__Opportunity_Product_ID__c == null || !oppLiMap.containsKey(subscription.RecurSoft__Opportunity_Product_ID__c)) continue;
		
			OpportunityLineItem oppLi = oppLiMap.get(subscription.RecurSoft__Opportunity_Product_ID__c);
				
			if(oppLi.RecurSoft__Product_Subscription__c == null) 
			{	
				oppLi.RecurSoft__Product_Subscription__c = subscription.Id;
				sruow.registerDirtyWithCatch(oppLi);
			}

			if(subscription.Number_of_Free_Months__c == null) 
			{
				subscription.Promotional_Price__c = oppLi.Promotional_Price__c == null ? 0 : oppLi.Promotional_Price__c;
				subscription.Number_of_Free_Months__c = oppLi.Number_of_Free_Months__c;
				subscription.Free_Month_Setting__c = oppLi.Free_Month_Setting__c;
			}

			if(subscription.Competitor_Buyout__c == null) 
			{
				subscription.Competitor_Buyout__c = oppLi.Competitor_Buyout__c;
			}

			if(subscription.Trial_Start_Date__c == null) 
			{
				subscription.Trial_Start_Date__c = oppLi.Trial_End_Date__c != null ? subscription.RecurSoft__Contract_Term_Start_Date__c : null;
			}

			if(subscription.Trial_End_Date__c == null) 
			{
				subscription.Trial_End_Date__c = oppLi.Trial_End_Date__c;
			}
		}
	}
}