src.3/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>RecurSoft__Billing_Frequency__c</fullName>
        <formula>IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;One-Time&quot;), &quot;One-Time&quot;,
IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;Monthly&quot;), &quot;Monthly&quot;,
IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;Quarterly&quot;), &quot;Quarterly&quot; ,
IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;Semi-Annual&quot;), &quot;Semi-Annual&quot;,
IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;Yearly&quot;), &quot;Yearly&quot; ,
IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;Milestones&quot;), &quot;Milestones&quot; , &quot;&quot;
)
)
)
)
)
)</formula>
        <inlineHelpText>Default billing frequency of the product.</inlineHelpText>
        <label>Billing Frequency</label>
        <type>Text</type>
    </fields>
</CustomObject>

src.3/objects/Product2.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>AppAdminProductKey__c</fullName>
        <description>Used as the key for the AppAdmin Products API.</description>
        <label>AppAdminProductKey</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SRP</fullName>
                </value>
                <value>
                    <fullName>SRR</fullName>
                </value>
                <value>
                    <fullName>SRC</fullName>
                </value>
                <value>
                    <fullName>SRSR</fullName>
                </value>
                <value>
                    <fullName>SRSC</fullName>
                </value>
                <value>
                    <fullName>HG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AppAdmin_API_Name__c</fullName>
        <description>Name of Boolean to turn feature on/off in appAdmin.</description>
        <inlineHelpText>Name of Boolean to turn feature on/off in appAdmin.</inlineHelpText>
        <label>AppAdmin API Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Display_Name__c</fullName>
        <label>Contract Display Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Contract_Term__c</fullName>
        <description>If Inherit Opportunity Contract Terms is false, the Contract Term will be set on the Opportunity Product to (Default Contract Term + Product Number of Free Months) and reset to this value when an Opportunity contract term change is made. For month-to-month products.</description>
        <inlineHelpText>If Inherit Opportunity Contract Terms is false, the Contract Term will be set on the Opportunity Product to (Default Contract Term + Product Number of Free Months) and reset to this value when an Opportunity contract term change is made.</inlineHelpText>
        <label>Default Contract Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Default_Co_Terminate__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Sets the default for co-termination on the related Opportunity Products.  Can be overridden at the Opportunity Product level.</description>
        <inlineHelpText>Sets the default for co-termination on the related Opportunity Products.  Can be overridden at the Opportunity Product level.</inlineHelpText>
        <label>Default Co-Terminate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Default_Renewal_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Provides the Default Renewal Rule for this Product. Will be set on Opportunity Products.</description>
        <inlineHelpText>Provides the Default Renewal Rule for this Product. Will be set on Opportunity Products.</inlineHelpText>
        <label>Default Renewal Rule</label>
        <referenceTo>RecurSoft__Renewal_Rule__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsEvergreen__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for setting the related Product Subscription record type to Evergreen for repeated billing.</description>
        <inlineHelpText>Used for setting the related Product Subscription record type to Evergreen for repeated billing.</inlineHelpText>
        <label>IsEvergreen</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Billing_Frequency__c</fullName>
        <inlineHelpText>The frequency at which customer is invoiced.</inlineHelpText>
        <label>Billing Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One-Time</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-annual</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>Milestones</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.2/classes/ProductsSelector.cls
public class ProductsSelector extends fflib_SObjectSelector 
{
	public Schema.SObjectField[] getSObjectFieldList() 
	{
		return new List<Schema.SObjectField> {
			Product2.Id,
			Product2.AppAdmin_API_Name__c,
			Product2.AppAdminProductKey__c, 
			Product2.Contract_Display_Name__c,
			Product2.Default_Contract_Term__c,
			Product2.Default_Co_Terminate__c,
			Product2.Default_Renewal_Rule__c,
			Product2.Family,
			Product2.IsEvergreen__c,
			Product2.Name,
	    	Product2.ProductCode, 
	    	Product2.RecurSoft__Billing_Frequency__c };
	}

	public Schema.SObjectType getSObjectType()
	{
		return Product2.SObjectType;
	}

	public static ProductsSelector newInstance()
	{
		return (ProductsSelector) Application.Selector.newInstance(Product2.SObjectType);
	}

	public Product2[] selectByOpportunityLineItems(OpportunityLineItem[] opportunityLineItems)
	{
		Set<Id> ids = new Set<Id>();
		
		for(OpportunityLineItem oppLi : opportunityLineItems) 
		{	
			ids.add(oppLi.Product2Id);
		}

		fflib_QueryFactory productQueryFactory = newQueryFactory();

		return (Product2[]) Database.query(
			productQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList())).setCondition('Id IN :ids').toSOQL());
	}
}