src.3/objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>Approval_Level_to_Enforce__c</fullName>
        <label>Approval Level to Enforce</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Least Restrictive</fullName>
                    <default>true</default>
                    <label>Least Restrictive</label>
                </value>
                <value>
                    <fullName>Most Restrictive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Auto_Add_Free_Months__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Auto-Add Free Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Auto_Add_Free_Month_Setting__c</fullName>
        <label>Auto-Add Free Month Setting</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Extend Contract - At the Beginning</fullName>
                </value>
                <value>
                    <fullName>Include in Contract Period - At the Beginning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Auto_Add_Price__c</fullName>
        <label>Auto-Add Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Auto_Add_Promotional_Price__c</fullName>
        <label>Auto-Add Promotional Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Auto_Add_Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Auto-Add Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Auto_Add_Trial__c</fullName>
        <label>Auto-Add Trial</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>120</fullName>
                </value>
                <value>
                    <fullName>180</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Auto_Add__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto-Add</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enforce_Limits_Free_Months__c</fullName>
        <label>Enforce Limits - Free Months</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Limits</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Enforce_Limits_Price_Discount__c</fullName>
        <label>Enforce Limits - Price Discount</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Limits</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Enforce_Limits_Term__c</fullName>
        <label>Enforce Limits - Term</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Limits</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Enforce_Limits_Trial__c</fullName>
        <label>Enforce Limits - Trial</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Limits</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Free_Months_Floor__c</fullName>
        <label>Free Months Floor</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Level_0_Limit_Free_Months__c</fullName>
        <label>Level 0 Limit - Free Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Level_0_Limit_Price_Discount__c</fullName>
        <label>Level 0 Limit - Price Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Level_0_Limit_Term__c</fullName>
        <label>Level 0 Limit - Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Level_0_Limit_Trial__c</fullName>
        <label>Level 0 Limit - Trial</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Level_1_Limit_Free_Months__c</fullName>
        <label>Level 1 Limit - Free Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Level_1_Limit_Price_Discount__c</fullName>
        <label>Level 1 Limit - Price Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Level_1_Limit_Term__c</fullName>
        <label>Level 1 Limit - Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Level_1_Limit_Trial__c</fullName>
        <label>Level 1 Limit - Trial</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Level_2_Limit_Free_Months__c</fullName>
        <label>Level 2 Limit - Free Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Level_2_Limit_Price_Discount__c</fullName>
        <label>Level 2 Limit - Price Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Level_2_Limit_Term__c</fullName>
        <label>Level 2 Limit - Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Level_2_Limit_Trial__c</fullName>
        <label>Level 2 Limit - Trial</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_Discount_Floor__c</fullName>
        <label>Price Discount Floor</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Trial_Period_Floor__c</fullName>
        <label>Trial Period Floor</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/default/classes/PricebookEntriesSelector.cls
public class PricebookEntriesSelector extends fflib_SObjectSelector 
{
	public Schema.SObjectField[] getSObjectFieldList() 
	{
		return new List<Schema.SObjectField> {
			PricebookEntry.Id,
			PricebookEntry.Approval_Level_to_Enforce__c,
			PricebookEntry.Auto_Add__c,
			PricebookEntry.Auto_Add_Free_Months__c,
			PricebookEntry.Auto_Add_Free_Month_Setting__c,
			PricebookEntry.Auto_Add_Price__c,
			PricebookEntry.Auto_Add_Promotional_Price__c,
			PricebookEntry.Auto_Add_Quantity__c,
			PricebookEntry.Auto_Add_Trial__c,
			PricebookEntry.Enforce_Limits_Free_Months__c,
			PricebookEntry.Enforce_Limits_Price_Discount__c,
			PricebookEntry.Enforce_Limits_Term__c,
			PricebookEntry.Enforce_Limits_Trial__c,
			PricebookEntry.Free_Months_Floor__c,
			PricebookEntry.IsActive,
			PricebookEntry.Level_0_Limit_Free_Months__c,
			PricebookEntry.Level_0_Limit_Price_Discount__c,
			PricebookEntry.Level_0_Limit_Term__c,
			PricebookEntry.Level_0_Limit_Trial__c,
			PricebookEntry.Level_1_Limit_Free_Months__c,
			PricebookEntry.Level_1_Limit_Price_Discount__c,
			PricebookEntry.Level_1_Limit_Term__c,
			PricebookEntry.Level_1_Limit_Trial__c,
			PricebookEntry.Level_2_Limit_Free_Months__c,
			PricebookEntry.Level_2_Limit_Price_Discount__c,
			PricebookEntry.Level_2_Limit_Term__c,
			PricebookEntry.Level_2_Limit_Trial__c,
			PricebookEntry.Name,
			PricebookEntry.UnitPrice,
			PricebookEntry.Pricebook2Id,
			PricebookEntry.Price_Discount_Floor__c,
			PricebookEntry.Product2Id,
	    	PricebookEntry.ProductCode,
	    	PricebookEntry.Trial_Period_Floor__c };
	}

	public Schema.SObjectType getSObjectType()
	{
		return PricebookEntry.SObjectType;
	}

	public override String getOrderBy()
	{
		return 'Auto_Add__c DESC, Auto_Add_Price__c DESC';
	}

	public static PricebookEntriesSelector newInstance()
	{
		return (PricebookEntriesSelector) Application.Selector.newInstance(PricebookEntry.SObjectType);
	}

	public PricebookEntry[] selectByPricebookId(String pricebookId) 
	{
        fflib_QueryFactory pricebookEntriesQueryFactory = newQueryFactory();

        new ProductsSelector().configureQueryFactoryFields(pricebookEntriesQueryFactory, 'Product2');

        return (PricebookEntry[]) Database.query(
			pricebookEntriesQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList()))
				.setCondition('Pricebook2Id = :pricebookId')
				.toSOQL());
    }

	public PricebookEntry[] selectByOpportunityLineItems(OpportunityLineItem[] opportunityLineItems)
	{
		Set<Id> ids = new Set<Id>();
		
		for(OpportunityLineItem oppLi : opportunityLineItems) 
		{	
			ids.add(oppLi.PricebookEntryId);
		}

		fflib_QueryFactory pricebookEntryQueryFactory = newQueryFactory();

		return (PricebookEntry[]) Database.query(
			pricebookEntryQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList())).setCondition('Id IN :ids').toSOQL());
	}
}