src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account Lookup</description>
        <inlineHelpText>Choose the Account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_of_Calls_Generated_from_HG__c</fullName>
        <description>To be populated from the most recent Milestone Moment</description>
        <label>Current # of Calls Generated from HG</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_of_Competitors_Blocked__c</fullName>
        <description>To be updated from the most recent Milestone Moment</description>
        <label>Current # of Competitors Blocked</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_of_confirms_received_via_SR__c</fullName>
        <description>To be populated from most recent Milestone Moment</description>
        <label>Current # of confirms received via SR</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_of_HG_Profile_Views__c</fullName>
        <description>To be populated by the most recent Milestone Moment</description>
        <label>Current # of HG Profile Views</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_of_LL_Appt_Requests_Received__c</fullName>
        <description>To be populated by the most recent Milestone Moment</description>
        <label>Current # of LL Appt Requests Received</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_of_Patients__c</fullName>
        <description>To be populated by the most recent Milestone Moment</description>
        <label>Current # of Patients</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_of_Patient_Referrals__c</fullName>
        <description>To be populated by the most recent Milestone Moment</description>
        <label>Current # of Patient Referrals</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_of_Reviews_Generated__c</fullName>
        <description>To be populated by the most recent Milestone Moment</description>
        <label>Current # of Reviews Generated</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Recare_Dollars_Generated_via_SR__c</fullName>
        <description>To be populated by the most recent Milestone Moment</description>
        <label>Current Recare Dollars Generated via SR</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.4/objects/Milestone_Moment__c.object
<CustomObject>
    <description>Provides a record of what the subscriber data is at a specific point in time in appAdmin</description>
    <label>Milestone Moment</label>
    <nameField>
        <displayFormat>MM-{0000000000}</displayFormat>
        <label>Milestone Moment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestone Moments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account that the Milestone data is for</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Milestone Moments</relationshipLabel>
        <relationshipName>Milestone_Moments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Number_of_Calls_Generated_from_HG__c</fullName>
        <label>Number of Calls Generated from HG</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Competitors_Blocked__c</fullName>
        <label>Number of Competitors Blocked</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Confirmations_received__c</fullName>
        <label>Number of Confirmations Received via SR</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_HG_Profile_Views__c</fullName>
        <label>Number of HG Profile Views</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_LL_Appt_Requests_Received__c</fullName>
        <label>Number of LL Appt Requests Received</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Patients__c</fullName>
        <label>Number of Patients</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Patient_Referrals__c</fullName>
        <label>Number of Patient Referrals</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Reviews_Generated__c</fullName>
        <label>Number of Reviews Generated</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recare_Dollars_Generated_via_SR__c</fullName>
        <label>Recare Dollars Generated via SR</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src.2/classes/UpdateMilestoneMomentsOnAccount_Test.cls
@isTest
private class UpdateMilestoneMomentsOnAccount_Test {

    @isTest static void UpdateMM(){
        Account a = TestUtilities.insertBasicAccount(true);
        Milestone_Moment__c m = new Milestone_Moment__c();
        m.Number_of_Patients__c                    = 1000;
        m.Number_of_Calls_Generated_from_HG__c     = 100;
        m.Number_of_Competitors_Blocked__c         = 20;
        m.Number_of_Confirmations_received__c      = 200;
        m.Number_of_HG_Profile_Views__c            = 3;
        m.Number_of_LL_Appt_Requests_Received__c   = 5;
        m.Number_of_Patient_Referrals__c           = 2;
        m.Number_of_Reviews_Generated__c           = 25;
        m.Recare_Dollars_Generated_via_SR__c       = 2500;
        m.Account__c                               = a.Id;
        
        insert m;
        
       Account updatedAccount = [SELECT Current_of_Patients__c,
                                  Current_of_Calls_Generated_from_HG__c,
                                  Current_of_Competitors_Blocked__c,
                                  Current_of_confirms_received_via_SR__c,
                                  Current_of_HG_Profile_Views__c,
                                  Current_of_LL_Appt_Requests_Received__c,
                                  Current_of_Patient_Referrals__c,
                                  Current_of_Reviews_Generated__c,
                                  Current_Recare_Dollars_Generated_via_SR__c FROM Account WHERE Id = :a.Id];
        
        System.assert(updatedAccount.Current_of_Patients__c                       == 1000);
        System.assert(updatedAccount.Current_of_Calls_Generated_from_HG__c        == 100);
        System.assert(updatedAccount.Current_of_Competitors_Blocked__c            == 20);
        System.assert(updatedAccount.Current_of_confirms_received_via_SR__c       == 200);
        System.assert(updatedAccount.Current_of_HG_Profile_Views__c               == 3);
        System.assert(updatedAccount.Current_of_LL_Appt_Requests_Received__c      == 5);
        System.assert(updatedAccount.Current_of_Patient_Referrals__c              == 2);
        System.assert(updatedAccount.Current_of_Reviews_Generated__c              == 25);
        System.assert(updatedAccount.Current_Recare_Dollars_Generated_via_SR__c   == 2500);
                
    }
}