src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Account_Sales_Status__c</fullName>
        <label>Account Sales Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Contacted</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Bogus</fullName>
                </value>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Locations__c</fullName>
        <label>Number of Locations</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0-9</fullName>
                </value>
                <value>
                    <fullName>10-49</fullName>
                </value>
                <value>
                    <fullName>50-100</fullName>
                </value>
                <value>
                    <fullName>100+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Practice_Management_Software__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is the practice management software the customer is using.</description>
        <inlineHelpText>This is the practice management software the customer is using.</inlineHelpText>
        <label>Practice Management Software</label>
        <referenceTo>Management_System__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Vertical__c</fullName>
        <label>Sub-Vertical</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Allergy &amp; Immunology</fullName>
                </value>
                <value>
                    <fullName>Bariatric, Metabolic and Weight Health</fullName>
                </value>
                <value>
                    <fullName>Chiropractic</fullName>
                </value>
                <value>
                    <fullName>Cosmetic Surgery</fullName>
                </value>
                <value>
                    <fullName>Dermatology</fullName>
                </value>
                <value>
                    <fullName>Endocrinology</fullName>
                </value>
                <value>
                    <fullName>Endodontistry</fullName>
                </value>
                <value>
                    <fullName>ENT-Otolaryngology</fullName>
                </value>
                <value>
                    <fullName>Family Medicine or General Physician</fullName>
                </value>
                <value>
                    <fullName>Gastroenterology</fullName>
                </value>
                <value>
                    <fullName>General Dentistry</fullName>
                </value>
                <value>
                    <fullName>General Surgery</fullName>
                </value>
                <value>
                    <fullName>Geriatric Medicine</fullName>
                </value>
                <value>
                    <fullName>Heart and Vascular</fullName>
                </value>
                <value>
                    <fullName>HIV/Infectious Disease</fullName>
                </value>
                <value>
                    <fullName>Internal Medicine</fullName>
                </value>
                <value>
                    <fullName>Medical Spa or Aesthetic Medicine</fullName>
                </value>
                <value>
                    <fullName>Neurology</fullName>
                </value>
                <value>
                    <fullName>Non-medical</fullName>
                </value>
                <value>
                    <fullName>OB/GYN or Womens Health</fullName>
                </value>
                <value>
                    <fullName>Oncology</fullName>
                </value>
                <value>
                    <fullName>Ophthalmology</fullName>
                </value>
                <value>
                    <fullName>Optometry</fullName>
                </value>
                <value>
                    <fullName>Oral Surgery</fullName>
                </value>
                <value>
                    <fullName>Orthodontistry</fullName>
                </value>
                <value>
                    <fullName>Orthopedics</fullName>
                </value>
                <value>
                    <fullName>Orthotics/Prosthetics</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pain Management or Physical Medicine or Physiatry</fullName>
                </value>
                <value>
                    <fullName>Pediatrics</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.1/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account_Sales_Status__c</fullName>
        <description>Apex mapping via Parent/Child Mappings</description>
        <label>Account Sales Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Contacted</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Bogus</fullName>
                </value>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Best_Day_to_Contact__c</fullName>
        <label>Best Day to Contact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <label>Contact Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Staff Member</fullName>
                    <default>true</default>
                    <label>Staff Member</label>
                </value>
                <value>
                    <fullName>Decision Maker</fullName>
                </value>
                <value>
                    <fullName>Billing Contact</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>Technical Contact</fullName>
                </value>
                <value>
                    <fullName>Doctor</fullName>
                </value>
                <value>
                    <fullName>Business User</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                    <isActive>false</isActive>
                    <label>Consultant</label>
                </value>
                <value>
                    <fullName>DecisionMaker</fullName>
                    <isActive>false</isActive>
                    <label>DecisionMaker</label>
                </value>
                <value>
                    <fullName>General Dentistry</fullName>
                    <isActive>false</isActive>
                    <label>General Dentistry</label>
                </value>
                <value>
                    <fullName>OfficeContact</fullName>
                    <isActive>false</isActive>
                    <label>OfficeContact</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Locations__c</fullName>
        <label>Number of Locations</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1-5</fullName>
                </value>
                <value>
                    <fullName>6-24</fullName>
                </value>
                <value>
                    <fullName>25-100</fullName>
                </value>
                <value>
                    <fullName>100+</fullName>
                </value>
                <value>
                    <fullName>1-4</fullName>
                </value>
                <value>
                    <fullName>5-24</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Practice_Management_Software__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Set via Parent/Child Mapping in Apex</description>
        <label>Practice Management Software</label>
        <referenceTo>Management_System__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Vertical__c</fullName>
        <description>Used for new Contacts coming from HubSpot to create new Account. Updated via Parent/Child Mapping in Apex</description>
        <label>Sub-Vertical</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Dermatology</fullName>
                </value>
                <value>
                    <fullName>Ophthalmology</fullName>
                </value>
                <value>
                    <fullName>Cosmetic Surgery</fullName>
                </value>
                <value>
                    <fullName>Family Medicine or General Physician</fullName>
                </value>
                <value>
                    <fullName>Pediatrics</fullName>
                </value>
                <value>
                    <fullName>OB/GYN or Womens Health</fullName>
                </value>
                <value>
                    <fullName>Allergy &amp; Immunology</fullName>
                </value>
                <value>
                    <fullName>ENT-Otolaryngology</fullName>
                </value>
                <value>
                    <fullName>Gastroenterology</fullName>
                </value>
                <value>
                    <fullName>Orthopedics</fullName>
                </value>
                <value>
                    <fullName>Bariatric, Metabolic and Weight Health</fullName>
                </value>
                <value>
                    <fullName>Endocrinology</fullName>
                </value>
                <value>
                    <fullName>Geriatric Medicine</fullName>
                </value>
                <value>
                    <fullName>Heart and Vascular</fullName>
                </value>
                <value>
                    <fullName>HIV/Infectious Disease</fullName>
                </value>
                <value>
                    <fullName>Internal Medicine</fullName>
                </value>
                <value>
                    <fullName>Medical Spa or Aesthetic Medicine</fullName>
                </value>
                <value>
                    <fullName>Neurology</fullName>
                </value>
                <value>
                    <fullName>General Surgery</fullName>
                </value>
                <value>
                    <fullName>Oncology</fullName>
                </value>
                <value>
                    <fullName>Pain Management or Physical Medicine or Physiatry</fullName>
                </value>
                <value>
                    <fullName>Podiatry</fullName>
                </value>
                <value>
                    <fullName>Psychiatry or Mental Health or Substance Rehabilitation</fullName>
                </value>
                <value>
                    <fullName>Radiology or Imaging</fullName>
                </value>
                <value>
                    <fullName>Urology</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>General Dentistry</fullName>
                </value>
                <value>
                    <fullName>Orthodontistry</fullName>
                </value>
                <value>
                    <fullName>Endodontistry</fullName>
                </value>
                <value>
                    <fullName>Pedodontistry</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.1/objects/SR_Default_Values__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SR Default Values</label>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

src.3/classes/PowerstoneAPI.cls
@RestResource(urlMapping='/v1/Powerstone/*')
global with sharing class PowerstoneAPI 
{	
	@HttpGet
	global static Map<String, Id> getData()
	{
		return ManagementSystemsSelector.newInstance().selectNameToIdMap();	
	}

	@HttpPut
	global static String updateData(ProspectData data)
	{
		try
		{
			fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
			fflib_SObjectUnitOfWork uow1 = Application.UnitOfWork.newInstance();
			Id powerstoneDistGroup = SR_Default_Values__c.getValues('Powerstone Distribution Group').Value__c;
			Contact[] contact = ContactsSelector.newInstance().selectByIdWithAccount(new Set<Id>{data.contactId});

			if(data.accountData != null)
			{
				Account a = new Account();
				a.Id = contact[0].AccountId;
				a.Name = data.accountData.businessName != null ? data.accountData.businessName : contact[0].Account.Name;
				a.Phone = data.accountData.accountPhone != null ? data.accountData.accountPhone : contact[0].Account.Phone;
				a.Industry = data.accountData.vertical != null ? data.accountData.vertical : contact[0].Account.Industry;
				a.Sub_Vertical__c = data.accountData.subvertical != null ? data.accountData.subvertical : contact[0].Account.Sub_Vertical__c;
				a.Number_of_Locations__c = data.accountData.numberOfLocations != null ? data.accountData.numberOfLocations : contact[0].Account.Number_of_Locations__c;
				a.Practice_Management_Software__c = data.accountData.pmId != null ? data.accountData.pmId : contact[0].Account.Practice_Management_Software__c;
				a.Account_Sales_Status__c = data.accountData.salesStatus != null ? data.accountData.salesStatus : contact[0].Account.Account_Sales_Status__c;
				a.Number_of_Locations__c = data.accountData.numberOfLocations != null ? data.accountData.numberOfLocations : contact[0].Account.Number_of_Locations__c;
				a.RecordTypeId = data.accountData.isHospital || (data.accountData.numberOfLocations != '0-9' && data.accountData.numberOfLocations != null) 
					? SRUtilities.getRecordTypeId('Account','Major Account') : contact[0].Account.RecordTypeId;
				uow.registerDirty(a);
			}
			
			if(data.contactData != null)
			{
				contact[0].FirstName = data.contactData.firstName != null ? data.contactData.firstName : contact[0].FirstName;
				contact[0].LastName = data.contactData.lastName != null ? data.contactData.lastName : contact[0].LastName;
				contact[0].Phone = data.contactData.contactPhone != null ? data.contactData.contactPhone : contact[0].Phone;
				contact[0].Email = data.contactData.email != null ? data.contactData.email : contact[0].Email;
				contact[0].DoNotCall = data.contactData.doNotContact != null ? data.contactData.doNotContact : contact[0].DoNotCall;
				contact[0].Contact_Role__c = data.contactData.contactRole != null ? data.contactData.contactRole : contact[0].Contact_Role__c;
				contact[0].Best_Day_to_Contact__c = data.contactData.bestDayToContact != null ? data.contactData.bestDayToContact : contact[0].Best_Day_to_Contact__c;
				contact[0].Best_Time_to_Contact__c = data.contactData.bestTimeToContact != null ? data.contactData.bestTimeToContact : contact[0].Best_Time_to_Contact__c;
				uow.registerDirty(contact[0]);
			}

			if(data.demoScheduledDateTime != null)
			{
				contact[0].DistGroup__c = powerstoneDistGroup;
				uow.registerDirty(contact[0]);

				String dateTimeString = data.demoScheduledDateTime.format();
				
				Task t = new Task(Subject = 'Powerstone Demo Scheduled with ' + contact[0].FirstName + ' - ' + data.demoScheduledDateTime.format('MM/dd/yyyy h:mm a','America/Denver'),
					ADR_Set__c = true,
					Description = data.comments,
					ActivityDate = Date.valueOf(data.demoScheduledDateTime),
					Activity_Type__c = 'ADR Set',
					Activity_Results__c = 'Future Event',
					Status = 'Scheduled',
					Due_Time__c = Datetime.parse(dateTimeString),
					WhoId = data.contactId,
					WhatId = contact[0].AccountId);
				uow.registerNew(t);
			}
			else
			{
				Task t = new Task(Subject = 'Contacted by Powerstone',
					Description = data.comments,
					ActivityDate = Date.today(),
					Activity_Type__c = '',
					Activity_Results__c = 'Completed',
					Status = 'Completed',
					WhoId = data.contactId,
					WhatId = contact[0].AccountId);
				uow.registerNew(t);
			}

			uow.commitWork();
			return 'Success';
		}
		catch(Exception e)
		{
			return e.getMessage();
		}
		
	}

	global class ProspectData 
	{
		global String contactId;
		global ContactData contactData;
		global AccountData accountData;
		global Datetime demoScheduledDateTime;
		global String comments;
	}

	global class ContactData
	{
		global String firstName;
		global String lastName;
		global String contactPhone;
		global String email;
		global String contactRole;
		global Boolean doNotContact;
		global String bestDayToContact;
		global String bestTimeToContact;
	}

	global class AccountData
	{
		global String businessName;
		global String accountPhone;
		global String pmId;
		global String vertical;
		global String subvertical;
		global String salesStatus;
		global String numberOfLocations;
		global Boolean isHospital;
	}
}