src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Office_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Office Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Practice_Management_Software_Versoin__c</fullName>
        <formula>Practice_Management_Software__r.Version__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Practice Management Software Version</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Practice_Management_Software__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is the practice management software the customer is using.</description>
        <inlineHelpText>This is the practice management software the customer is using.</inlineHelpText>
        <label>Practice Management Software</label>
        <referenceTo>Management_System__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Default Bill to Contact for usage billing.</inlineHelpText>
        <label>Bill to Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>$Source.RecurSoft__Bill_to_Account__c</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.RecurSoft__Bill_to_Account__c</field>
                <operation>equals</operation>
                <value/>
            </filterItems>
            <infoMessage>Contact should have current account.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>RecurSoft_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Bill_to_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Default Bill to Account for usage billing.</inlineHelpText>
        <label>Bill to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Bill to Account)</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.1/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Practice_Management_Software__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Set via Parent/Child Mapping in Apex</description>
        <label>Practice Management Software</label>
        <referenceTo>Management_System__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referred_By__c</fullName>
        <label>Referred By</label>
        <length>200</length>
        <type>Text</type>
    </fields>
</CustomObject>

src.3/objects/Management_System__c.object
<CustomObject>
    <label>Management System</label>
    <nameField>
        <label>Management System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Management Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>RecurSoft__Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill to Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.RecurSoft__Bill_to_Account__c</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>RecurSoft_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Bill_to_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Bill to Account)</relationshipLabel>
        <relationshipName>RecurSoft_OpportunitiesAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Temp_Contract_Term_Total__c</fullName>
        <description>For Contract until rework done.</description>
        <label>Temp Contract Term Total</label>
        <summarizedField>OpportunityLineItem.Total_Contract_Term__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
</CustomObject>

src.3/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Number_of_Free_Months__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Override opportunity free months</description>
        <inlineHelpText>Override opportunity free months</inlineHelpText>
        <label>Number of Orientation Months</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Billing_Frequency__c</fullName>
        <formula>IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;One-Time&quot;), &quot;One-Time&quot;,
IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;Monthly&quot;), &quot;Monthly&quot;,
IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;Quarterly&quot;), &quot;Quarterly&quot; ,
IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;Semi-Annual&quot;), &quot;Semi-Annual&quot;,
IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;Yearly&quot;), &quot;Yearly&quot; ,
IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;Milestones&quot;), &quot;Milestones&quot; , &quot;&quot;
)
)
)
)
)
)</formula>
        <inlineHelpText>Default billing frequency of the product.</inlineHelpText>
        <label>Billing Frequency</label>
        <type>Text</type>
    </fields>
</CustomObject>

src.3/objects/Product2.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>RecurSoft__Billing_Frequency__c</fullName>
        <inlineHelpText>The frequency at which customer is invoiced.</inlineHelpText>
        <label>Billing Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One-Time</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-annual</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>Milestones</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.1/classes/ContractPDFController.cls
/**
 * File:        ContractPDFController.cls
 * Project:     Solutionreach 
 * Date:        Feb, 2014
 * Created By:  Sid Maganti
 * *************************************************************************
 * Description: This is Controller for  ContractPDF Document
 * *************************************************************************
 * History:
 * Date:                Modified By:            Description: 
 * 02/24/2015           Randy Barton		    CRM-20 - Added ContractDateTime parameter
 * 02/24/2015			Randy Barton			Corrected spelling in class name from ContactPDFController to ContractPDFController
 */

public class ContractPDFController extends WebFormsUtilityClass
{
    /*public Opportunity associatedOpportunity {get;set;}
    public AccountDecorator assoAccount {get;set;}
    public ContactDecorator assoOppContact {get; set;}
    public ContactDecorator assoAccContact {get;set;}
    //
    public string BusinessName {get;set;}
    public string address1 {get;set;}
    public string City {get;set;}
    public string State {get;set;}
    public string Zip {get;set;}
    public string Country {get;set;}
    public string OppCCName {get;set;}
    public string email {get;set;}
    public string DirePhone {get;set;}
    public string Officeemail {get;set;}
    public string OfficePhone {get;set;}
    public string OfficeCCName {get;set;}
    public string WebSite {get;set;}
    public string PS {get;set;}
    public string PSV {get;set;}
    public string CCTYPE {get;set;}
    public string CCNO {get;set;}
    public string CCMONTH {get;set;}
    public string CCYEAR {get;set;}
    public string Signer {get;set;}
    //
    public decimal NoProvider {get;set;}
    public decimal NoAddProvider {get;set;}
    public string Licence {get;set;}
    public string LicenceSmall {get;set;}
    public decimal MonthlyTotal {get;set;}
    public decimal OneTimeTotal {get;set;}
    public string ContractSignedIP {get;set;}
    
    public decimal SetupFee {get;set;}
    public decimal AddProFee {get;set;}
    public decimal ServiceFee {get;set;}
    public string SetupFeeProductCode {get;set;}
    public string SetupFeeProductCodeNew {get;set;}
    public list<OpportunityLineItem> listOppl {get;set;}
     public decimal TotalcontractTerm {get;set;}
	 public String ContractDateTime { get; set; }
    /*
    *Constructor for ContactPDFController
    */ 
    /* public ContractPDFController()
     {
        try
        {
           associatedOpportunity = new Opportunity();
            assoAccount = new AccountDecorator();
            assoOppContact = new  ContactDecorator();
            assoAccContact = new  ContactDecorator();
            MonthlyTotal=0;
            Licence='';
            LicenceSmall='';
            NoAddProvider=0;
            NoProvider=0;
            OneTimeTotal=0;
            TotalcontractTerm=0;
            SetupFee=0;
            ServiceFee=0;
            AddProFee=0;
            SetupFeeProductCode=SRHGlobalVariables.SET_UP_FEE;
            SetupFeeProductCodeNew=SRHGlobalVariables.SET_UP_FEE_NEW;
            listOppl= new list<OpportunityLineItem>();
            
            ContractSignedIP = getURParameter('ContractSignedIP') == null ? '' : getURParameter('ContractSignedIP');  
            string oppID=getURParameter('id');
            BusinessName=getURParameter('BusinessName')==null? '':getURParameter('BusinessName');
            address1=getURParameter('address1')==null? '':getURParameter('address1');
            City=getURParameter('City')==null? '':getURParameter('City');
            State=getURParameter('State')==null? '':getURParameter('State');
            Zip=getURParameter('Zip')==null? '':getURParameter('Zip');
            Country=getURParameter('Country')==null? '':getURParameter('Country');
            OppCCName=getURParameter('OppCCName')==null? '':getURParameter('OppCCName');
            email=getURParameter('email')==null? '':getURParameter('email');
            DirePhone=getURParameter('DirePhone')==null? '':getURParameter('DirePhone');
            Officeemail=getURParameter('Officeemail')==null? '':getURParameter('Officeemail');
            OfficePhone=getURParameter('OfficePhone')==null? '':getURParameter('OfficePhone');
            OfficeCCName=getURParameter('OfficeCCName')==null? '':getURParameter('OfficeCCName');
            WebSite=getURParameter('WebSite')==null? '':getURParameter('WebSite');
            PS=getURParameter('PS')==null? '':getURParameter('PS');
            PSV=getURParameter('PSV')==null? '':getURParameter('PSV');
            CCTYPE=getURParameter('CCTYPE')==null? '':getURParameter('CCTYPE');
            CCNO=getURParameter('CCNO')==null? '':getURParameter('CCNO');
            CCMONTH=getURParameter('CCMONTH')==null? '':getURParameter('CCMONTH'); 
            CCYEAR=getURParameter('CCYEAR')==null? '':getURParameter('CCYEAR');
            Signer=getURParameter('Signer')==null? '':getURParameter('Signer');
            Datetime Dt = system.now();
            ContractDateTime = Dt.format('MM/dd/yyyy HH:mm:ss', 'America/Denver');
            
            if(!IsEmptyOrNull(oppID))
            {
                PopulateRecords(oppID);
            }
        }
        catch (Exception Ex)
        {
            system.debug('Error ContactPDFController : '+String.ValueOF(Ex) );
            CreateErrorLog(associatedOpportunity,assoAccount,'Contract_Form_ContactPDFController_54',String.ValueOF(Ex));
        }
     }
     
  
    /*
    *Populate Records
    *@parm OpportunityID
    *Populate records 
    */
    /*public void PopulateRecords(string OppID)
    {
        associatedOpportunity= new Opportunity();
        Account associatedBusinessAccount = new Account();
        Contact associatedOppContact = new Contact();
        Contact associatedAccContact = new Contact();
        assoAccount = new AccountDecorator();
        assoOppContact = new ContactDecorator();
        assoAccContact= new ContactDecorator ();
  
        associatedOpportunity=retrieveOpportunityData(OppID);
        system.debug('associatedOpportunity-->'+associatedOpportunity);

        //system.debug('IsValiedContract(associatedOpportunity)-->'+IsValiedContract(associatedOpportunity));
        if(associatedOpportunity !=null )
        {
            associatedBusinessAccount=retrieveAccountData(associatedOpportunity.RecurSoft__Bill_to_Account__r.id);
            PopulateProviders();
            string ContactID ='';
            if(associatedOpportunity.RecurSoft__Billing_Contact__r.id!= null)
            {
                //for(OpportunityContactRole ContactRole: associatedOpportunity.OpportunityContactRoles )
                //{
                    ContactID= associatedOpportunity.RecurSoft__Billing_Contact__r.id;
                //}
                
                if(!IsEmptyOrNull(ContactID))
                {
                    associatedOppContact=retrieveContactData(ContactID);
                }
            }
            if(associatedBusinessAccount!= null && associatedBusinessAccount.Office_Contact__c!=null)
            {
                associatedAccContact=retrieveContactData(associatedBusinessAccount.Office_Contact__r.id);
            }
            if(associatedBusinessAccount!= null)
            {
                assoAccount.AccountID=associatedBusinessAccount.Id;
                assoAccount.BusinessName=associatedBusinessAccount.Name;
                assoAccount.address1= associatedBusinessAccount.BillingStreet;
                assoAccount.address2='';
                assoAccount.city=associatedBusinessAccount.BillingCity;
                assoAccount.country=associatedBusinessAccount.BillingCountry;
                assoAccount.OfficeContactID=associatedBusinessAccount.Office_Contact__r.id;
                assoAccount.Officeemail=associatedBusinessAccount.Office_Contact__r.Email;
                assoAccount.OfficephoneAreaCode='';
                assoAccount.OfficephoneCode='';
                assoAccount.OfficephoneCountryCode='';
                assoAccount.PractivceSoftware=associatedBusinessAccount.Practice_Management_Software__r.Name;
                assoAccount.PractivceSoftwareVersoin=associatedBusinessAccount.Practice_Management_Software_Versoin__c;         
                assoAccount.website=associatedBusinessAccount.Website==null?'':associatedBusinessAccount.Website;
                assoAccount.state=associatedBusinessAccount.BillingState;
                assoAccount.zip=associatedBusinessAccount.BillingPostalCode;
                assoAccount.TotalAmount=associatedOpportunity.Amount==null ?'0.00':string.ValueOf(associatedOpportunity.Amount);
            }
            if(associatedOppContact!= null)
            {
                assoOppContact.contactID=associatedOppContact.id;
                assoOppContact.DirectPhone=associatedOppContact.Phone;
                assoOppContact.Email=associatedOppContact.Email;
                assoOppContact.FirstName=associatedOppContact.FirstName;
                assoOppContact.LastName=associatedOppContact.LastName;
                assoOppContact.ReferedBY=associatedOppContact.Referred_By__c;
                assoOppContact.Salutation=associatedOppContact.Salutation;
                assoOppContact.Title=associatedOppContact.Title;
            }
            if(associatedAccContact!= null)
            {
                assoAccContact.contactID=associatedAccContact.id;
                assoAccContact.DirectPhone=associatedAccContact.Phone;
                assoAccContact.Email=associatedAccContact.Email;
                assoAccContact.FirstName=associatedAccContact.FirstName;
                assoAccContact.LastName=associatedAccContact.LastName;
                assoAccContact.ReferedBY=associatedAccContact.Referred_By__c==null?'':associatedAccContact.Referred_By__c;
                assoAccContact.Salutation=associatedAccContact.Salutation;
                assoAccContact.Title=associatedAccContact.Title;
                
            }

        }
        else 
        {
            //ShoWError = true;
            //DetailPage=false;
        }
   }
    
    
    /*Will Populate Providers*/
    /*private void PopulateProviders()
    {
        
        TotalcontractTerm = associatedOpportunity.Temp_Contract_Term_Total__c;
        Licence=TotalcontractTerm>12 ?'MULTI-ANNUAL':'ANNUAL';
        LicenceSmall=TotalcontractTerm>12 ?'Multi-Annual':'Annual';
      system.debug('associatedOpportunity.HasOpportunityLineItem-->'+associatedOpportunity.HasOpportunityLineItem);
        if(associatedOpportunity.HasOpportunityLineItem)
        {
            for(OpportunityLineItem Oppl:associatedOpportunity.OpportunityLineItems)
            {
                if(Oppl.PricebookEntry.ProductCode==SRHGlobalVariables.MONTHLY_SERVICE_FEE || Oppl.PricebookEntry.ProductCode==SRHGlobalVariables.MONTHLY_SERVICE_FEE_NEW)
                {
                    NoProvider=NoProvider+3;
                }
                else if(Oppl.PricebookEntry.ProductCode==SRHGlobalVariables.ADDITIONAL_PROVIDERS || Oppl.PricebookEntry.ProductCode==SRHGlobalVariables.ADDITIONAL_PROVIDERS_NEW )
                {
                    NoAddProvider=NoAddProvider+(Oppl.Quantity);
                    AddProFee=Oppl.UnitPrice;
                }
                if(Oppl.PricebookEntry.Product2.RecurSoft__Billing_Frequency__c==SRHGlobalVariables.BILLING_FREQUENCY_MONTHLY || Oppl.PricebookEntry.ProductCode==SRHGlobalVariables.ADDITIONAL_PROVIDERS || Oppl.PricebookEntry.ProductCode==SRHGlobalVariables.MONTHLY_SERVICE_FEE ||Oppl.PricebookEntry.ProductCode==SRHGlobalVariables.ADDITIONAL_PROVIDERS_NEW || Oppl.PricebookEntry.ProductCode==SRHGlobalVariables.MONTHLY_SERVICE_FEE_NEW )
                {
                   // MonthalySetupFee = MonthalySetupFee+(Oppl.UnitPrice*Oppl.Quantity);
                     MonthlyTotal = MonthlyTotal+(Oppl.UnitPrice*Oppl.Quantity);
                    system.debug('MonthlyTotal-->'+MonthlyTotal);
                   if((Oppl.PricebookEntry.ProductCode==SRHGlobalVariables.MONTHLY_SERVICE_FEE||Oppl.PricebookEntry.ProductCode==SRHGlobalVariables.MONTHLY_SERVICE_FEE_NEW) && Oppl.Number_of_Free_Months__c != null && Oppl.Number_of_Free_Months__c > 0)
                    {
                        Oppl.PricebookEntry.Product2.Name=LicenceSmall+' - '+TotalcontractTerm+' Months with '+ Oppl.Number_of_Free_Months__c+' months free (per office for up to 3 practitioners):';
                    }
                    else if(Oppl.PricebookEntry.ProductCode==SRHGlobalVariables.MONTHLY_SERVICE_FEE || Oppl.PricebookEntry.ProductCode==SRHGlobalVariables.MONTHLY_SERVICE_FEE_NEW && (Oppl.Number_of_Free_Months__c == null || (Oppl.Number_of_Free_Months__c != null && Oppl.Number_of_Free_Months__c == 0)))
                    {
                        Oppl.PricebookEntry.Product2.Name=LicenceSmall+' - '+TotalcontractTerm+' Months (per office for up to 3 practitioners): ';
                        
                    }
                    else if(Oppl.PricebookEntry.ProductCode==SRHGlobalVariables.ADDITIONAL_PROVIDERS ||Oppl.PricebookEntry.ProductCode==SRHGlobalVariables.ADDITIONAL_PROVIDERS_NEW )
                    {
                        Oppl.PricebookEntry.Product2.Name='Extended License - number of addtional practitioners ($'+Oppl.UnitPrice+' each): ';
                        
                    }
                }
                if(Oppl.PricebookEntry.Product2.RecurSoft__Billing_Frequency__c==SRHGlobalVariables.BILLING_FREQUENCY_ONE_TIME || Oppl.PricebookEntry.Product2.RecurSoft__Billing_Frequency__c=='' )
                {
                    //OneTime = OneTime+(Oppl.UnitPrice*Oppl.Quantity);
                     OneTimeTotal = OneTimeTotal+(Oppl.UnitPrice*Oppl.Quantity);
                
                }
                 if(Oppl.PricebookEntry.ProductCode==SRHGlobalVariables.SET_UP_FEE || Oppl.PricebookEntry.ProductCode==SRHGlobalVariables.SET_UP_FEE_NEW )
                {
                    SetupFee=SetupFee+(Oppl.UnitPrice*Oppl.Quantity);
                //ServiceFee
                }
                else
                {
                    listOppl.add(Oppl);
                }
                if(Oppl.PricebookEntry.ProductCode==SRHGlobalVariables.MONTHLY_SERVICE_FEE || Oppl.PricebookEntry.ProductCode==SRHGlobalVariables.MONTHLY_SERVICE_FEE_NEW )
                {
                    ServiceFee=ServiceFee+(Oppl.UnitPrice*Oppl.Quantity);
                //ServiceFee
                }
                
                system.debug('Oppl.PricebookEntry.Product2.Name-->'+Oppl.PricebookEntry.Product2.Name);
            }
        }
    }*/
}