src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Limelight_URL_for_Healthgrades__c</fullName>
        <description>Only populated for active Limelight subscribers.

Populated via DLRS- Account Limelight URL</description>
        <label>Limelight URL for Healthgrades</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Probable_Most_Recent_K_Date__c</fullName>
        <description>Stores the most recent contract date</description>
        <inlineHelpText>This is the date the contract was likely signed</inlineHelpText>
        <label>Most Recent Contract Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SR_Price_Book__c</fullName>
        <description>Price book from the SR Asset</description>
        <label>SR Price Book</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.3/objects/Asset.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Notes whether or not the Asset is being billed.</description>
        <inlineHelpText>Notes whether or not the Asset is being billed.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Cancel_Request_Date__c</fullName>
        <label>Most Recent Cancel Request Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Cancel_Request_Stage__c</fullName>
        <label>Most Recent Cancel Request Stage</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Competitor_Buyout__c</fullName>
        <label>Most Recent Competitor Buyout</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>4 Patient Care</fullName>
                </value>
                <value>
                    <fullName>DemandForce</fullName>
                </value>
                <value>
                    <fullName>eCentral</fullName>
                </value>
                <value>
                    <fullName>eReminders</fullName>
                </value>
                <value>
                    <fullName>Lighthouse</fullName>
                </value>
                <value>
                    <fullName>Patient Activator</fullName>
                </value>
                <value>
                    <fullName>Phone Tree</fullName>
                </value>
                <value>
                    <fullName>PM/EMR</fullName>
                </value>
                <value>
                    <fullName>Practice Mojo</fullName>
                </value>
                <value>
                    <fullName>Sesame</fullName>
                </value>
                <value>
                    <fullName>Teledental</fullName>
                </value>
                <value>
                    <fullName>Televox</fullName>
                </value>
                <value>
                    <fullName>Weave</fullName>
                </value>
                <value>
                    <fullName>Websystem3</fullName>
                </value>
                <value>
                    <fullName>RevenueWell</fullName>
                </value>
                <value>
                    <fullName>ZocDoc</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Most_Recent_Contract_Signed_Date__c</fullName>
        <description>Will be the same as the original unless the customer has cancelled and reactivated.</description>
        <inlineHelpText>Will be the same as the original unless the customer has cancelled and reactivated.</inlineHelpText>
        <label>Most Recent Contract Signed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Contract_Term_Start_Date__c</fullName>
        <label>Most Recent Contract Term Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Number_of_Free_Months__c</fullName>
        <label>Most Recent Number of Free Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Termination_Date__c</fullName>
        <label>Most Recent Termination Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related Provider record for Healthgrades Assets</description>
        <inlineHelpText>The related Provider record for Healthgrades Assets</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Ambassador__Ambassador_Referred_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referring Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Signer__c</fullName>
        <label>Contract Signer</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the related Provider record</description>
        <inlineHelpText>Link to the related Provider record</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referred_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the Contact that was referred by an Ambassador</description>
        <label>Referred Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Referred Contact)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Healthgrades</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <description>For selling Healthgrades Premium Profiles</description>
        <label>Healthgrades</label>
    </recordTypes>
    <recordTypes>
        <fullName>Retention</fullName>
        <active>true</active>
        <businessProcess>Save Process</businessProcess>
        <label>Retention</label>
    </recordTypes>
</CustomObject>

force-app/main/default/objects/Provider__c/Provider__c.object-meta.xml
<CustomObject>
    <description>Used to store information about individual Providers within a Practice.  The Provider information is used for Healthgrades Premium members.</description>
    <label>Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Provider__c/fields/Bill_to_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The related account that will be billed for the Provider&#39;s Healthgrades subscription.</description>
    <inlineHelpText>The related account that will be billed for the Provider&#39;s Healthgrades subscription.</inlineHelpText>
    <label>Bill to Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Providers</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Care_Philosophy__c.field-meta.xml
<CustomField>
    <fullName>Care_Philosophy__c</fullName>
    <label>Care Philosophy</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Degree__c.field-meta.xml
<CustomField>
    <fullName>Degree__c</fullName>
    <label>Degree</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CDC</fullName>
            </value>
            <value>
                <fullName>DCNP</fullName>
            </value>
            <value>
                <fullName>DDM</fullName>
            </value>
            <value>
                <fullName>DDS</fullName>
            </value>
            <value>
                <fullName>LCDA</fullName>
            </value>
            <value>
                <fullName>DH</fullName>
            </value>
            <value>
                <fullName>RDA</fullName>
            </value>
            <value>
                <fullName>BDS</fullName>
            </value>
            <value>
                <fullName>CDR</fullName>
            </value>
            <value>
                <fullName>DDSc</fullName>
            </value>
            <value>
                <fullName>MDSc</fullName>
            </value>
            <value>
                <fullName>MDS</fullName>
            </value>
            <value>
                <fullName>MDentTech</fullName>
            </value>
            <value>
                <fullName>CDA</fullName>
            </value>
            <value>
                <fullName>EFDA</fullName>
            </value>
            <value>
                <fullName>DMD</fullName>
            </value>
            <value>
                <fullName>DA</fullName>
            </value>
            <value>
                <fullName>RDH</fullName>
            </value>
            <value>
                <fullName>RDHAP</fullName>
            </value>
            <value>
                <fullName>OPT</fullName>
            </value>
            <value>
                <fullName>OD</fullName>
            </value>
            <value>
                <fullName>LO</fullName>
            </value>
            <value>
                <fullName>RDO</fullName>
            </value>
            <value>
                <fullName>LDO</fullName>
            </value>
            <value>
                <fullName>DOS</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>DO</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Healthgrades Profile data</description>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Healthgrades_ID__c.field-meta.xml
<CustomField>
    <fullName>Healthgrades_ID__c</fullName>
    <description>The individual Provider&#39;s unique Healthgrades identifier.</description>
    <externalId>true</externalId>
    <label>Healthgrades ID</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Insurance_Accepted__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Accepted__c</fullName>
    <description>Healthgrades profile data</description>
    <label>Insurance Accepted</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Last_Profile_Update_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Profile_Update_Date__c</fullName>
    <label>Last Profile Update Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Last_Reported_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Reported_Date__c</fullName>
    <description>Last date sent on HG Daily Profile Data feed. Used to filter and split files for size limitations.</description>
    <label>Last Reported Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Licensing_State__c.field-meta.xml
<CustomField>
    <fullName>Licensing_State__c</fullName>
    <label>Licensing State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/NPI__c.field-meta.xml
<CustomField>
    <fullName>NPI__c</fullName>
    <description>A National Provider Identifier or NPI is a unique 10-digit identification number issued to health care providers in the United States by the Centers for Medicare and Medicaid Services (CMS).</description>
    <label>NPI</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Practice_Name__c.field-meta.xml
<CustomField>
    <fullName>Practice_Name__c</fullName>
    <formula>Bill_to_Account__r.Name</formula>
    <label>Practice Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Practice_URL__c.field-meta.xml
<CustomField>
    <fullName>Practice_URL__c</fullName>
    <label>Practice URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Premium_Member__c.field-meta.xml
<CustomField>
    <fullName>Premium_Member__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the Provider is currently paying for a Healthgrades Premium Profile.</description>
    <inlineHelpText>Checked if the Provider is currently paying for a Healthgrades Premium Profile.</inlineHelpText>
    <label>Premium Member</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Related_Contact__c.field-meta.xml
<CustomField>
    <fullName>Related_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Provider&#39;s contact information is accessed via the Related Contact field.</description>
    <inlineHelpText>The Provider&#39;s contact information is accessed via the Related Contact field.</inlineHelpText>
    <label>Related Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Providers</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/State_License__c.field-meta.xml
<CustomField>
    <fullName>State_License__c</fullName>
    <description>Healthgrades profile data</description>
    <label>State License #</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src.2/classes/HealthgradesDailyProfileData.cls
global class HealthgradesDailyProfileData implements Database.Batchable<sObject>, Database.Stateful, Schedulable {
	
   	String finalDocument = Test.isRunningTest() ? 'Test' : '';
   	String errors = '';
   	Boolean allRecords;
   	String emailDistribution;

   	public HealthgradesDailyProfileData(Boolean allRecords, String emailDistribution)
   	{
   		this.allRecords = allRecords;
   		this.emailDistribution = emailDistribution;
   	}

	global Database.QueryLocator start(Database.BatchableContext BC) 
	{
		String header = 'SR Customer Status,Last Updated,Contract Signed Date,First Bill Date,Billing Status,Cancel Request Date,Termination Date,Free Months Given,LH/RW Competitor,Buyout,First Name,Last Name,NPI,' +
		'Healthgrades URL,IsPremium,Account Name,Street,City,' +
		'State,PostalCode,Country,Phone,Email,Practicing Specialty,Insurance Accepted,State License #,' +
		'Licensing State,Degree,Gender,Practice Name,Primary Specialty,Secondary Specialties,Condition Treated,Procedures Performed,Practice URL,Limelight URL,Practice Logo Link,' +
		'Practice Video Link,Provider Photo Link,Accepting New Patients?,' +
		'Languages Spoken,Date of Birth,Medical/Dental School,Year Graduated,Care Philosophy,Contract Signer,\n';

		Integer totalPremium = [SELECT COUNT() FROM Provider__c WHERE Premium_Member__c = true];
		Integer totalNonPremium = [SELECT COUNT() FROM Provider__c WHERE Id IN (SELECT Provider__c FROM Asset) AND Premium_Member__c = false];
		Integer totalProviders = totalPremium + totalNonPremium;

		String totalRow = 'Total Sales: ' + totalProviders + ',Total Active: ' + totalPremium + ',Total Cancelled: ' + totalNonPremium + ',,,,,,,,,,,,,,,,,,,,,,\n';
		String blankRow = ',,,,,,,,,,,,,,,,,,,,,,,,,,,\n';

		finalDocument = finalDocument == '' ? totalRow + blankRow + blankRow + header : finalDocument;
		
		return ProvidersSelector.newInstance().queryLocatorDailyReport(allRecords);
	}

	/**
	 * Create a csv of all Providers. Email csv as attachment to stakeholders
	 * @param  BC - Database.BatchableContext
	 * @param  scope - List of providers to be executed upon. Comes from query string.
	 * @see See ScheduleHealthgradesReport
	 */
	global void execute(Database.BatchableContext BC, List<Provider__c> scope) 
	{
		for(Provider__c p : scope) 
		{	
			p.Last_Reported_Date__c = Date.today();

			String newOrExisting = '';
			String billingStatus = '';
			String lastUpdated = p.Last_Profile_Update_Date__c != null ? p.Last_Profile_Update_Date__c.format('yyyy-MM-dd','America/Denver') : null;
			String contractSignedDate = null;
			String contractSigner = null;
			Integer monthsToAdd = 1;
			String firstBillDate = null;
			String cancelRequestDate = null;
			String cancelledDate = null;
			String competitor = null;
			Boolean lhrw = p.Bill_to_Account__r.SR_Price_Book__c == 'LH/RW Competitor Offer (18 Mo/6 Sat)' ? true : false;

			String philosophy = p.Care_Philosophy__c != null ? p.Care_Philosophy__c.replace('"','\'') : null;
			String primaryProviderSpecialty = '';
			String providerSpecialties = '';
			String providerConditions = '';
			String providerProcedures = '';
			String freeMonths = '0';
			String dateOfBirth = '';
		
			if(p.Date_of_Birth__c != null)
			{
				Datetime dt = Datetime.newInstance(p.Date_of_Birth__c.year(), p.Date_of_Birth__c.month(), p.Date_of_Birth__c.day());
				dateOfBirth = p.Date_of_Birth__c == null ? '' : dt.format('MM/dd/yyyy');
			}

	        if(!p.Opportunities__r.isEmpty())
	        {
	        	contractSigner = p.Opportunities__r[0].Contract_Signer__c != null ? p.Opportunities__r[0].Contract_Signer__c : null;
	        }

	        if(!p.Assets__r.isEmpty()) 
	        {
        		contractSignedDate = p.Assets__r[0].Most_Recent_Contract_Signed_Date__c != null ? p.Assets__r[0].Most_Recent_Contract_Signed_Date__c.format() : null;

        		monthsToAdd = p.Assets__r[0].Most_Recent_Number_of_Free_Months__c != null ? monthsToAdd + Math.min(2, Integer.valueOf(p.Assets__r[0].Most_Recent_Number_of_Free_Months__c)) : monthsToAdd;
	        	
	        	firstBillDate = p.Assets__r[0].Most_Recent_Contract_Term_Start_Date__c != null ? 
        			p.Assets__r[0].Most_Recent_Contract_Term_Start_Date__c.addMonths(monthsToAdd).format() : null;
        		
        		cancelRequestDate = p.Assets__r[0].Most_Recent_Cancel_Request_Date__c != null ? p.Assets__r[0].Most_Recent_Cancel_Request_Date__c.format() : null;
	        	
	        	freeMonths = p.Assets__r[0].Most_Recent_Number_of_Free_Months__c != null ? String.valueOf(p.Assets__r[0].Most_Recent_Number_of_Free_Months__c) : '0';
	        	
	        	competitor = p.Assets__r[0].Most_Recent_Competitor_Buyout__c != null && p.Assets__r[0].Most_Recent_Competitor_Buyout__c != 'None' ? p.Assets__r[0].Most_Recent_Competitor_Buyout__c : null;
	        	
	        	newOrExisting = p.Assets__r[0].Most_Recent_Contract_Term_Start_Date__c != null && p.Bill_to_Account__r.Probable_Most_Recent_K_Date__c != null ?
        		p.Assets__r[0].Most_Recent_Contract_Term_Start_Date__c <= (p.Bill_to_Account__r.Probable_Most_Recent_K_Date__c + 60) ?
        			'New' : 'Existing' : 'New';

	        	if(p.Assets__r[0].Most_Recent_Termination_Date__c != null && !p.Premium_Member__c) 
	        	{
	        		cancelledDate = p.Assets__r[0].Most_Recent_Termination_Date__c.format();	
	        	} 

	        	if(p.Assets__r[0].Most_Recent_Cancel_Request_Stage__c != null && 
	        		p.Assets__r[0].Most_Recent_Cancel_Request_Date__c != null && 
	        		p.Assets__r[0].Most_Recent_Contract_Signed_Date__c != null &&
	        		p.Assets__r[0].Most_Recent_Cancel_Request_Date__c > p.Assets__r[0].Most_Recent_Contract_Signed_Date__c)
	        	{
	        		billingStatus = (p.Assets__r[0].Most_Recent_Cancel_Request_Stage__c == 'Save' || p.Assets__r[0].Most_Recent_Cancel_Request_Stage__c == 'Resume - No Change') ? 'Saved' : 
	        			(p.Assets__r[0].Most_Recent_Cancel_Request_Stage__c == 'Cancelled' || p.Assets__r[0].Most_Recent_Cancel_Request_Stage__c == 'No Sale')  ? 'Cancelled' :
	        			'In Retention';
	        	}
	        	
	        	if(contractSignedDate == null)
	        	{
	        		errors += p.Id + ', Null Contract Signed Date|';
	        		newOrExisting = 'Data Integrity Issue';
	        	} 
	        	if(p.Premium_Member__c != p.Assets__r[0].Active__c)
	        	{
	        		errors += p.Id + ', Provider and Asset Premium Mismatch|';
	        		newOrExisting = 'Data Integrity Issue';
	        	} 
	        	if(firstBillDate == null) 
	        	{
	        		errors += p.Id + ', Null First Bill Date|';
	        		newOrExisting = 'Data Integrity Issue';
	        	}
	        	if(cancelledDate != null && cancelRequestDate == null) billingStatus = 'On Hold';
	        }
	        else
	        {
	        	errors += p.Id + ', No Related Assets|';
	        	newOrExisting = 'Data Integrity Issue';
	        }

	        primaryProviderSpecialty = ProvidersService.getPrimarySpecialty(p);
	        providerSpecialties = ProvidersService.getSpecialties(p);
	        providerConditions = ProvidersService.getConditions(p);
	        providerProcedures = ProvidersService.getProcedures(p);
         
	        String thisProvider = '\"' + newOrExisting + '\",\"'
	        	+ lastUpdated + '\",\"'
	        	+ contractSignedDate + '\",\"'
	        	+ firstBillDate + '\",\"'
	        	+ billingStatus + '\",\"'
	        	+ cancelRequestDate + '\",\"'
	        	+ cancelledDate + '\",\"'
	        	+ freeMonths + '\",\"'
	        	+ lhrw + '\",\"'
	        	+ competitor + '\",\"'
	        	+ p.Related_Contact__r.FirstName + '\",\"' 
				+ p.Related_Contact__r.LastName + '\",\"'  
				+ p.NPI__c + '\",\"' 
				+ p.Healthgrades_ID__c + '\",\"' 
				+ p.Premium_Member__c + '\",\"' 
				+ p.Bill_to_Account__r.Name + '\",\"' 
				+ p.Bill_to_Account__r.ShippingStreet + '\",\"' 
				+ p.Bill_to_Account__r.ShippingCity + '\",\"' 
				+ p.Bill_to_Account__r.ShippingState + '\",\"' 
				+ p.Bill_to_Account__r.ShippingPostalCode + '\",\"' 
				+ p.Bill_to_Account__r.ShippingCountry + '\",\"' 
				+ p.Bill_to_Account__r.Phone + '\",\"' 
				+ p.Email__c + '\",\"'
	        	+ SRUtilities.getRecordTypeName('Provider__c', p.RecordTypeId) + '\",\"'
	        	+ p.Insurance_Accepted__c + '\",\"'
	        	+ p.State_License__c + '\",\"'
	        	+ p.Licensing_State__c + '\",\"'
	        	+ p.Degree__c + '\",\"'
	        	+ p.Gender__c + '\",\"'
	        	+ p.Practice_Name__c + '\",\"'
	        	+ primaryProviderSpecialty + '\",\"'
	        	+ providerSpecialties + '\",\"'
	        	+ providerConditions + '\",\"'
	        	+ providerProcedures + '\",\"'
	        	+ p.Practice_URL__c + '\",\"'
	        	+ p.Bill_to_Account__r.Limelight_URL_for_Healthgrades__c + '\",\"' 
	        	+ p.Practice_Image_Link__c + '\",\"'
	        	+ p.Practice_Video_Link__c + '\",\"'
	        	+ p.Provider_Photo_Link__c + '\",\"'
	        	+ p.Accepting_New_Patients__c + '\",\"'
	        	+ p.Languages_Spoken__c + '\",\"'
	        	+ dateOfBirth + '\",\"'
	        	+ p.Medical_Dental_School__c + '\",\"'
	        	+ p.Year_Graduated__c + '\",\"'
				+ philosophy + '\",\"'
				+ contractSigner + '\",'
				+ '\n';

			finalDocument = finalDocument + thisProvider;
		}	

		update scope;	
  	}
	
	/**
	 * Finish Apex Batch
	 */
	global void finish(Database.BatchableContext BC) {
		
		Date yesterday = Date.today().addDays(-1);
		Date today	= Date.today();
		String subject = allRecords ? ': Healthgrades Daily Profile Data' : ': Healthgrades Daily Profile Data - Updates Only';

		Messaging.EmailFileAttachment csvAttachment = new Messaging.EmailFileAttachment();
		Blob csvBlob = Blob.valueOf(finalDocument);
      	String csvName = 'HealthgradesDailyProfileData_'
         + System.now().addDays(-1).format('MM/dd/yyyy HH:mm:ss','America/Denver')
         + '.csv';
		csvAttachment.setFileName(csvName);
		csvAttachment.setBody(csvBlob);

		String msg = 'Please see attached Provider list. Lists are limited to 3500 records due to file size limitations.';

		ApexEmailDistributions__c emailSettings = ApexEmailDistributions__c.getValues(emailDistribution);
		String emails = Test.isRunningTest() ? 'randy@solutionreach.com' : emailSettings.Emails__c;
		if(!Test.isRunningTest() && emailSettings.Emails1__c != null) emails += ',' + emailSettings.Emails1__c;
		if(!Test.isRunningTest() && emailSettings.Emails2__c != null) emails += ',' + emailSettings.Emails2__c;
		String[] emailsList = emails.split(',');

		Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
		mail.setSubject(yesterday.year() + '_' + yesterday.month() + '_' + yesterday.day() + subject);
		mail.setPlainTextBody(msg);
		mail.setFileAttachments(new Messaging.EmailFileAttachment[] { csvAttachment });
		mail.setToAddresses(emailsList);

		try{

			Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });

			if(errors != '')
			{
				Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
	    		message.setSubject('HealthgradesDailyProfileData Error');
	    		message.setPlainTextBody('The following errors were detected: ' + errors);
	    		message.setToAddresses(new String[] {'randy@solutionreach.com'});
	    		Messaging.sendEmail(new Messaging.SingleEmailMessage[] { message });
			}

			if(allRecords)
			{
				Provider__c[] remaining = [SELECT Id FROM Provider__c WHERE Id IN (SELECT Provider__c FROM Asset) AND Last_Reported_Date__c != :today LIMIT 3500];
				
				if(remaining.size() > 0)
				{
					HealthgradesDailyProfileData batch = new HealthgradesDailyProfileData(allRecords, emailDistribution);
					Database.executebatch(batch, 2);
				}
			}
		
		} catch(Exception e) {

			mail.setFileAttachments(null);
			Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });

			Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
    		message.setSubject('HealthgradesDailyProfileData Error');
    		message.setPlainTextBody('The following exception details were caught.  Type: ' + e.getTypeName()
    									+ ' Cause: ' + e.getCause() 
    									+ ' Message: ' + e.getMessage() 
    									+ ' Stack Trace: ' + e.getStackTraceString());
    		message.setToAddresses(new String[] {'randy@solutionreach.com'});
    		Messaging.sendEmail(new Messaging.SingleEmailMessage[] { message });
		}
	}

	global void execute(SchedulableContext sc) {
		
		HealthgradesDailyProfileData batch = new HealthgradesDailyProfileData(allRecords, emailDistribution);
		Database.executebatch(batch, 2);
	}	
}