src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>RecurSoft__Status__c</fullName>
        <description>Picklist used to determine if an account is an active customer.</description>
        <inlineHelpText>Determined by the status of subscriptions (not created, created, not activated, or cancelled)</inlineHelpText>
        <label>ISB Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscriber_ID__c</fullName>
        <description>The subscriber ID from App Admin</description>
        <label>Subscriber ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.3/objects/Asset.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Notes whether or not the Asset is being billed.</description>
        <inlineHelpText>Notes whether or not the Asset is being billed.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract_End_Date__c</fullName>
        <description>Used for setting Contract Term End Date on &quot;Add Product&quot; Opportunities.  Set by a rollup summary.</description>
        <inlineHelpText>Used for setting Contract Term End Date on &quot;Add Product&quot; Opportunities.  Set by a rollup summary.</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Current_Product_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Shows the related subscription that has the most distant Contract End Date that is not Terminated.  Set from trigger.  Trigger activated by Subscription Last Modified field.</description>
        <label>Current Product Subscription</label>
        <referenceTo>RecurSoft__Product_Subscription__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Next_Invoice_Date__c</fullName>
        <description>Used in setting the Contract Term Start Date for &quot;Add Product&quot; Opportunities. Set by rollup summary.</description>
        <inlineHelpText>Used in setting the Contract Term Start Date for &quot;Add Product&quot; Opportunities. Set by rollup summary.</inlineHelpText>
        <label>Next Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related Provider record for Healthgrades Assets</description>
        <inlineHelpText>The related Provider record for Healthgrades Assets</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscriber_ID__c</fullName>
        <formula>Case(Account.Subscriber_ID__c,&quot;&quot;,&quot;&quot;,Account.Subscriber_ID__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subscriber ID</label>
        <type>Text</type>
    </fields>
</CustomObject>

src.3/objects/Cancel_Request__c.object
<CustomObject>
    <description>Junction object between Retention Opportunities and Assets</description>
    <label>Cancel Request</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Cancel Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancel Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipName>OpportunityAssets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cancel_Request_Type__c</fullName>
        <label>Cancel Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Trial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_SR_Subscription__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Current SR Subscription</label>
        <referenceTo>RecurSoft__Product_Subscription__c</referenceTo>
        <relationshipLabel>Cancel Requests (Current SR Subscription)</relationshipLabel>
        <relationshipName>Cancel_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Modified_Subscription__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Modified Subscription</label>
        <referenceTo>RecurSoft__Product_Subscription__c</referenceTo>
        <relationshipLabel>Cancel Requests</relationshipLabel>
        <relationshipName>Cancel_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes_for_Accounting__c</fullName>
        <label>Notes for Accounting</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>OpportunityAssets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Override_Current_SR_Subscription__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Override Current SR Subscription</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Override_Modified_Subscription__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Override Modified Subscription</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Actively Working</fullName>
                </value>
                <value>
                    <fullName>Negotiating</fullName>
                </value>
                <value>
                    <fullName>Sent Addendum</fullName>
                </value>
                <value>
                    <fullName>Save</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Resume - No Change</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.4/objects/Case.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the related Opportunity for this drop.</description>
        <inlineHelpText>Use this field to choose the related Opportunity for this drop.</inlineHelpText>
        <label>Related Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No Contact</fullName>
                </value>
                <value>
                    <fullName>Made Contact</fullName>
                </value>
                <value>
                    <fullName>Contact Attempted</fullName>
                </value>
                <value>
                    <fullName>Sync Scheduled</fullName>
                </value>
                <value>
                    <fullName>Sync Installed</fullName>
                </value>
                <value>
                    <fullName>Training Scheduled</fullName>
                </value>
                <value>
                    <fullName>Training Completed</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Resolving Issues</fullName>
                </value>
                <value>
                    <fullName>Made Offer</fullName>
                </value>
                <value>
                    <fullName>Sent Addendum</fullName>
                </value>
                <value>
                    <fullName>Offer Rejected</fullName>
                </value>
                <value>
                    <fullName>Dispute Resolution</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscriber_ID__c</fullName>
        <description>This was created so we can view the Subscriber ID from a List View</description>
        <formula>Account.Subscriber_ID__c</formula>
        <inlineHelpText>This is the Subscriber ID of the Account</inlineHelpText>
        <label>Subscriber ID</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Accounting</fullName>
        <active>true</active>
        <businessProcess>Accounting</businessProcess>
        <description>Used to alert Accounting of changes to customers billing</description>
        <label>Accounting</label>
    </recordTypes>
</CustomObject>

src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Cancel_Request_Type__c</fullName>
        <description>Sugar field for Retention Opportunities</description>
        <label>Cancel Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Trial</fullName>
                </value>
                <value>
                    <fullName>Reactivation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notes_for_Accounting__c</fullName>
        <inlineHelpText>Enter Notes for accounting</inlineHelpText>
        <label>Notes for Accounting</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the related Provider record</description>
        <inlineHelpText>Link to the related Provider record</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscriber_ID__c</fullName>
        <formula>Case(Account.Subscriber_ID__c,&quot;&quot;,&quot;&quot;,Account.Subscriber_ID__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subscriber ID</label>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Provider__c/Provider__c.object-meta.xml
<CustomObject>
    <description>Used to store information about individual Providers within a Practice.  The Provider information is used for Healthgrades Premium members.</description>
    <label>Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Provider__c/fields/Healthgrades_ID__c.field-meta.xml
<CustomField>
    <fullName>Healthgrades_ID__c</fullName>
    <description>The individual Provider&#39;s unique Healthgrades identifier.</description>
    <externalId>true</externalId>
    <label>Healthgrades ID</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src.1/classes/CancelRequestUtilities.cls
public with sharing class CancelRequestUtilities {

	public static Map<Id, Asset> getRelatedAssetMap(Cancel_Request__c[] newList) {

		Set<Id> assetIds = new Set<Id>();

    	for(Cancel_Request__c cr : newList) {

    		assetIds.add(cr.Asset__c);
    	}

    	Map<Id, Asset> results = new Map<Id, Asset>(
    		[SELECT Id,
    		Name,
    		AccountId,
			Product2.Family, 
			Provider__r.Healthgrades_Id__c
    		FROM Asset 
    		WHERE Id IN: assetIds]);

    	return results;
	}

	public static Map<Id, Account> getRelatedAccounts(Opportunity[] listOpps) {

		Set<ID> acctIds = new Set<ID>();
		
		for(Opportunity o : listOpps) {
			acctIds.add(o.AccountId);
		}
		
		Map<ID, Account> results = new Map<ID, Account> (
			[SELECT Id,
			(SELECT Id, 
				Next_Invoice_Date__c, 
				Contract_End_Date__c,
				Active__c
				FROM Assets
				WHERE Product2.Family = 'SR Platform'
				AND Active__c = true) 
			FROM Account
			WHERE Id IN :acctIds]);

		return results;
	}

	public static Map<Id, Opportunity> getRelatedOpps(Set<Id> idsToProcess) {
		
		Map<ID, Opportunity> results = new Map<ID, Opportunity> (
			[SELECT Id,
			(SELECT Id, 
				Stage__c
				FROM OpportunityAssets__r) 
			FROM Opportunity
			WHERE Id IN :idsToProcess]);

		return results;
	}

	public static Map<Id, Account> getRelatedAcctMap(Asset[] relatedAssetsList) {

		Set<Id> acctIds = new Set<Id>();

		for(Asset ast : relatedAssetsList) {

			acctIds.add(ast.AccountId);
		} 

		Map<Id, Account> results = new Map<Id, Account>(
			[SELECT Id,
			RecurSoft__Status__c,
			Subscriber_Id__c,
			(SELECT Id, 
				Product2.Family, 
				Current_Product_Subscription__c
				FROM Assets
				WHERE Product2.Family = 'SR Platform'),
			(SELECT Id,
				RecordType.Name,
				StageName
				FROM
				Opportunities 
				WHERE RecordType.Name = 'Add-On Business'
				AND StageName != 'Closed Won')
			FROM Account
			WHERE Id IN :acctIds]);

		return results;
	}

	public static Map<Id, Cancel_Request__c> getCrData(Cancel_Request__c[] updatedCR) {

		Set<Id> crIds = new Set<Id>();

		for(Cancel_Request__c cr : updatedCR) {

			crIds.add(cr.Id);
		}

		Map<Id, Cancel_Request__c> results = new Map<Id, Cancel_Request__c>(
			[SELECT Id,
			Asset__c,
			Asset__r.Product2.Family,
			Asset__r.AccountId,
			Asset__r.Current_Product_Subscription__c
			FROM Cancel_Request__c
			WHERE Id IN :crIds]);

		return results;
	}

	public static void setCrRecordType(Cancel_Request__c[] updatedCR) {

		Map<ID, SObject> mapInsertSObject = new Map<ID, SObject>();
		Map<ID, SObject> mapUpdateSObject = new Map<ID, SObject>();
		Map<ID, SObject> mapDeleteSObject = new Map<ID, SObject>();

		Map<Id, Cancel_Request__c> crDataMap = getCrData(updatedCR);

		for(Cancel_Request__c cr : updatedCR) {

			Cancel_Request__c cr2 = crDataMap.get(cr.Id);

			if(SRUtilities.getRecordTypeMap('Cancel_Request__c').containsKey(cr2.Asset__r.Product2.Family)) {

				cr.RecordTypeId = SRUtilities.getRecordTypeMap('Cancel_Request__c').get(cr2.Asset__r.Product2.Family).getRecordTypeId();
				mapUpdateSObject.put(cr.Id, cr);
			
			} else {

				cr.RecordTypeId = SRUtilities.getRecordTypeMap('Cancel_Request__c').get('SR Platform').getRecordTypeId();
				mapUpdateSObject.put(cr.Id, cr);
			}
		}

		SRUtilities.runDml(mapInsertSObject, mapUpdateSObject, mapDeleteSObject, 'CancelRequestUtilities.setCrRecordType');
	}

	public static void setModifiedSubscription(Cancel_Request__c[] updatedCR, Map<Id, Cancel_Request__c> oldMap) {

		Map<Id, Cancel_Request__c> crDataMap = getCrData(updatedCR);
		Map<Id, Asset> relatedAssetsMap = getRelatedAssetMap(updatedCR);
		Map<Id, Account> relatedAcctMap = getRelatedAcctMap(relatedAssetsMap.values());

		for(Cancel_Request__c cr : updatedCR) {

			if(!crDataMap.containsKey(cr.Id)) continue;
			Cancel_Request__c cr3 = oldMap.containsKey(cr.Id) ? oldMap.get(cr.Id) : new Cancel_Request__c();

			Cancel_Request__c cr2 = crDataMap.get(cr.Id);
			Account a = relatedAcctMap.get(cr2.Asset__r.AccountId);

			
			if(cr3.Stage__c != 'Save' 
				&& cr3.Stage__c != 'Cancelled'
				&& cr3.Stage__c != 'No Sale'
				&& cr3.Stage__c != 'Resume - No Change'
				&& !cr.Override_Modified_Subscription__c
				&& cr.Modified_Subscription__c != cr2.Asset__r.Current_Product_Subscription__c
				&& cr2.Asset__r.Current_Product_Subscription__c != null) {

				cr.Modified_Subscription__c = cr2.Asset__r.Current_Product_Subscription__c;
			}

			if(cr3.Stage__c != 'Save' 
				&& cr3.Stage__c != 'Cancelled'
				&& cr3.Stage__c != 'No Sale'
				&& cr3.Stage__c != 'Resume - No Change'
				&& !cr.Override_Current_SR_Subscription__c 
				&& !a.Assets.isEmpty()
				&& cr.Current_SR_Subscription__c != a.Assets[0].Current_Product_Subscription__c
				&& a.Assets[0].Current_Product_Subscription__c != null) {

				cr.Current_SR_Subscription__c = a.Assets[0].Current_Product_Subscription__c;
			}
		}
	}

	/*public static void createAssetTransaction(Cancel_Request__c[] newList) {

		Map<ID, SObject> mapInsertSObject = new Map<ID, SObject>();
		Map<ID, SObject> mapUpdateSObject = new Map<ID, SObject>();
		Map<ID, SObject> mapDeleteSObject = new Map<ID, SObject>();
		Map<Id, Asset> relatedAssetsMap = getRelatedAssetMap(newList);

		for(Cancel_Request__c cr : newList) {

			Asset ast = relatedAssetsMap.get(cr.Asset__c);

			if(ast.Number_of_Cancel_Requests__c > ast.Number_of_Cancel_Resolutions__c) continue;

			Transaction__c t = new Transaction__c(Asset__c = ast.Id,
				Transaction_Date__c = Date.today(),
				Type__c = 'Cancel Request');
			mapInsertSObject.put(ast.Id, t);
		}

		SRUtilities.runDml(mapInsertSObject, mapUpdateSObject, mapDeleteSObject, 'CancelRequestUtilities.createAssetTransaction');
	}*/

	public static void createAddendumOpp(Cancel_Request__c[] newList) {

		Map<ID, SObject> mapInsertSObject = new Map<ID, SObject>();
		Map<ID, SObject> mapUpdateSObject = new Map<ID, SObject>();
		Map<ID, SObject> mapDeleteSObject = new Map<ID, SObject>();
		Map<Id, Asset> relatedAssetsMap = getRelatedAssetMap(newList);
		Map<Id, Account> relatedAcctMap = getRelatedAcctMap(relatedAssetsMap.values());

		for(Cancel_Request__c cr : newList) {

			if(cr.Stage__c != 'Save') continue;

			Asset ast = relatedAssetsMap.get(cr.Asset__c);
			Account a = relatedAcctMap.get(ast.AccountId);

			Opportunity o = new Opportunity(RecordTypeId = SRUtilities.getRecordTypeMap('Opportunity').get('Add-On Business').getRecordTypeId(),
				AccountId = ast.AccountId,
				Description = cr.Notes_for_Accounting__c,
				CloseDate = Date.today(),
				StageName = 'Qualified',
				Name = ast.Name + ' - ' + cr.Cancel_Request_Type__c + ' Save',
				OwnerId = '005i0000002gn9T');
			
			if(!FlowControl.recordsCreated.contains(cr.Id + 'Opportunity')) {

				FlowControl.recordsCreated.add(cr.Id + 'Opportunity');
				mapInsertSObject.put(a.Id, o);
			}
		}

		SRUtilities.runDmlNoLock(mapInsertSObject, mapUpdateSObject, mapDeleteSObject, 'CancelRequestUtilities.createAddendumOpp');
	}

	public static void createCancelCase(Cancel_Request__c[] newList) {

		Map<ID, SObject> mapInsertSObject = new Map<ID, SObject>();
		Map<ID, SObject> mapUpdateSObject = new Map<ID, SObject>();
		Map<ID, SObject> mapDeleteSObject = new Map<ID, SObject>();
		Map<Id, Asset> relatedAssetsMap = getRelatedAssetMap(newList);
		Map<Id, Account> relatedAcctMap = getRelatedAcctMap(relatedAssetsMap.values());
		Map<Id, String> closeAllCancelRequestsIdMap = new Map<Id, String>();

		for(Cancel_Request__c cr : newList) {

			if(cr.Stage__c != 'Cancelled' && cr.Stage__c != 'No Sale') continue;

			Asset ast = relatedAssetsMap.get(cr.Asset__c);
			Account a = relatedAcctMap.get(ast.AccountId);

//  This is being handled by a batch process after the Cancel Month
//			if(ast.Product2.Family == 'SR Platform') {
//
//				//closeAllCancelRequestsIdMap.put(cr.Opportunity__c, cr.Stage__c);
//				a.RecurSoft__Status__c = cr.Stage__c;
//
//				mapUpdateSObject.put(a.Id, a);
//			}


			String type = cr.Stage__c == 'Cancelled' ? cr.Cancel_Request_Type__c + ' Cancel' : 'No Sale';
			String subject = type == 'Annual Cancel' ? 'Turn off any Renewals' : type == 'Trial Cancel' ? '' : 'Refund MSF and Setup';

			Case c = new Case(RecordTypeId = SRUtilities.getRecordTypeMap('Case').get('Accounting').getRecordTypeId(),
				AccountId = ast.AccountId,
				Description = cr.Notes_for_Accounting__c,
				Origin = 'Phone',
				OwnerId = '00Gi00000034JUX',
				Reason = type,
				Related_Opportunity__c = cr.Opportunity__c,
				Subject = ast.Name + ' - ' + type + ' - ' + subject);

			if(!FlowControl.recordsCreated.contains(cr.Id + 'Case')) {

				FlowControl.recordsCreated.add(cr.Id + 'Case');
				mapInsertSObject.put(ast.Id, c);
			}	
		}

		//if(!System.isBatch() && !System.isFuture() && !closeAllCancelRequestsIdMap.isEmpty()) closeAllCancelRequests(closeAllCancelRequestsIdMap);

		SRUtilities.runDmlNoLock(mapInsertSObject, mapUpdateSObject, mapDeleteSObject, 'CancelRequestUtilities.createCancelCase');
	}

	@future
	public static void closeAllCancelRequests(Map<Id, String> mapToProcess) {

		Map<ID, SObject> mapInsertSObject = new Map<ID, SObject>();
		Map<ID, SObject> mapUpdateSObject = new Map<ID, SObject>();
		Map<ID, SObject> mapDeleteSObject = new Map<ID, SObject>();
		Map<Id, Opportunity> relatedOppMap = getRelatedOpps(mapToProcess.keySet());

		for(Opportunity o : relatedOppMap.values()) {

			String stageName = mapToProcess.get(o.Id);

			for(Cancel_Request__c cr : o.OpportunityAssets__r) {

				if(cr.Stage__c != stageName) {

					cr.Stage__c = stageName;
					mapUpdateSObject.put(cr.Id, cr);
				}
			}
		}

		SRUtilities.runDml(mapInsertSObject, mapUpdateSObject, mapDeleteSObject, 'CancelRequestUtilities.closeAllCancelRequests');
	}
}