src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Practice_Management_Software__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is the practice management software the customer is using.</description>
        <inlineHelpText>This is the practice management software the customer is using.</inlineHelpText>
        <label>Practice Management Software</label>
        <referenceTo>Management_System__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Channel__c</fullName>
        <description>This field is mapped to the Class dimension in Intacct.</description>
        <inlineHelpText>Maps to the class dimension ID within Intacct.</inlineHelpText>
        <label>Class</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>100</fullName>
                    <default>true</default>
                    <label>100</label>
                </value>
                <value>
                    <fullName>200</fullName>
                </value>
                <value>
                    <fullName>300</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RecurSoft__Intacct_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Determines whether customer records are created at the root or entity level in Intacct.</inlineHelpText>
        <label>Intacct Entity</label>
        <referenceTo>RecurSoft__Intacct_Entity__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>RecurSoft_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Intacct_Vertical__c</fullName>
        <inlineHelpText>Intacct Location Dimension.</inlineHelpText>
        <label>Intacct Location</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Payment_Term__c</fullName>
        <inlineHelpText>As with all values that impact the creation of invoices in Intacct, this and other account fields equivalent to fields in Intacct must match Intacct. Values that are missing or incorrectly mapped will result in failed revenue schedules.</inlineHelpText>
        <label>Payment Term</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Due Upon Receipt</fullName>
                    <default>true</default>
                    <label>Due Upon Receipt</label>
                </value>
                <value>
                    <fullName>Net 30</fullName>
                </value>
                <value>
                    <fullName>Due on Receipt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <formula>Owner.FirstName + &quot; &quot; + Owner.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Rep</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.3/objects/Management_System__c.object
<CustomObject>
    <label>Management System</label>
    <nameField>
        <label>Management System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Management Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Management_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Management System</label>
        <referenceTo>Management_System__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Signed_Date__c</fullName>
        <label>Contract Signed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Intacct_Entity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Intacct Entity</label>
        <referenceTo>RecurSoft__Intacct_Entity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>RecurSoft_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Payment_Term__c</fullName>
        <formula>TEXT( RecurSoft__Bill_to_Account__r.RecurSoft__Payment_Term__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Term</label>
        <type>Text</type>
    </fields>
</CustomObject>

src.2/objects/Sales_Credit__c.object
<CustomObject>
    <label>Sales Credit</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Sales Credit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Credits</pluralLabel>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Individual_Credit_Portion__c</fullName>
        <label>Individual Credit Portion</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Sales Credits (Manager)</relationshipLabel>
        <relationshipName>Mgr_Sales_Credits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Credits</relationshipLabel>
        <relationshipName>Sales_Credits</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Rep Sales Credits</relationshipLabel>
        <relationshipName>Rep_Sales_Credits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Credit_Portion__c</fullName>
        <label>Team Credit Portion</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VP</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Sales Credits (VP)</relationshipLabel>
        <relationshipName>Sales_Credits</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.1/objects/Sales_Target__c.object
<CustomObject>
    <label>Sales Target</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Sales Target ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Targets</pluralLabel>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Actual_Credits__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Actual Credits</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <label>Manager</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Target Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Date__c</fullName>
        <inlineHelpText>Select the first day of the target month.</inlineHelpText>
        <label>Target Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>VP__c</fullName>
        <label>VP</label>
        <length>40</length>
        <type>Text</type>
    </fields>
</CustomObject>

src.4/classes/AssignSalesCreditToTargetHandler_Test.cls
@isTest
private class AssignSalesCreditToTargetHandler_Test {
    
    @testSetup static void testData() 
    {
        TestUtilities.insertCustomSettings();
    }
    
    public static Management_System__c createManagementSystem() {
        return(new Management_System__c(Name = 'test'));
    }
    
    
    public static Account createAccount(Management_System__c management) {
        
        RecurSoft__Intacct_Entity__c intacctEntity = new RecurSoft__Intacct_Entity__c(Name = 'test');
        database.insert(intacctEntity);
        
        return (new Account(Name = 'testAccount',
                            Practice_Management_Software__c = management.Id,
                            Industry = 'Vision',
                            RecurSoft__Intacct_Entity__c = intacctEntity.Id,
                            RecurSoft__Channel__c = '100',
                            RecurSoft__Intacct_Vertical__c = 'E001',
                            RecurSoft__Payment_Term__c = 'Net 30'));
    }

    public static Profile createProfile() {
        return [SELECT Id FROM Profile WHERE Name='Standard User'];
    }
    
    public static Opportunity createOpportunity(Account acct) {
        
        return (new Opportunity(Name = 'testOpp', 
                                StageName = 'Qualified',
                                CloseDate = System.today() + 30,
                                AccountId = acct.Id,
                                RecurSoft__Contract_Signed_Date__c = Date.newInstance(2014, 11, 12)));
    }
    
    
    public static User createUser1(Profile p) {
        return (new User(Alias = 'standt1',
                         Email='standarduser1@testorg.com',
                         EmailEncodingKey='UTF-8',
                         LastName='Testing1',
                         LanguageLocaleKey='en_US',
                         LocaleSidKey='en_US',
                         ProfileId = p.Id,
                         TimeZoneSidKey='America/Los_Angeles',
                         UserName='hfiekd@test.com'));
    }
    
    public static User createUser2(Profile p) {
        return (new User(Alias = 'standt2',
                         Email='standarduser2@testorg.com',
                         EmailEncodingKey='UTF-8',
                         LastName='Testing2',
                         LanguageLocaleKey='en_US',
                         LocaleSidKey='en_US',
                         ProfileId = p.Id,
                         TimeZoneSidKey='America/Los_Angeles',
                         UserName='aisuherb@test.com'));
    }
    
    public static User createUser3(Profile p) {
        return (new User(Alias = 'standt3',
                         Email='standarduser3@testorg.com',
                         EmailEncodingKey='UTF-8',
                         LastName='Testing3',
                         LanguageLocaleKey='en_US',
                         LocaleSidKey='en_US',
                         ProfileId = p.Id,
                         TimeZoneSidKey='America/Los_Angeles',
                         UserName='nzvxlihdf@test.com'));
    }
    
    public static User createUser4(Profile p) {
        return (new User(Alias = 'standt4',
                         Email='standarduser4@testorg.com',
                         EmailEncodingKey='UTF-8',
                         LastName='Testing4',
                         LanguageLocaleKey='en_US',
                         LocaleSidKey='en_US',
                         ProfileId = p.Id,
                         TimeZoneSidKey='America/Los_Angeles',
                         UserName='uvdhoke@test.com'));
    }
    
    public static User createUser5(Profile p) {
        return (new User(Alias = 'standt5',
                         Email='standarduser5@testorg.com',
                         EmailEncodingKey='UTF-8',
                         LastName='Testing5',
                         LanguageLocaleKey='en_US',
                         LocaleSidKey='en_US',
                         ProfileId = p.Id,
                         TimeZoneSidKey='America/Los_Angeles',
                         UserName='mnbvcxz@test.com'));
    }
    
    public static User createUser6(Profile p) {
        return (new User(Alias = 'standt6',
                         Email='standarduser6@testorg.com',
                         EmailEncodingKey='UTF-8',
                         LastName='Testing6',
                         LanguageLocaleKey='en_US',
                         LocaleSidKey='en_US',
                         ProfileId = p.Id,
                         TimeZoneSidKey='America/Los_Angeles',
                         UserName='zxcvbnm@test.com'));
    }

    public static Sales_Target__c createTarget(User usr) {
        Date firstOfMonth = Date.today().toStartOfMonth();
        return (new Sales_Target__c(Owner__c = usr.Id,
                                    Target_Date__c = firstOfMonth));
    }
    
    public static Sales_Credit__c createSalesCredit(Opportunity opp, User usr1, User usr2, User usr3) {
        return (new Sales_Credit__c(Opportunity__c = opp.Id,
                                   Sales_Rep__c = usr1.Id,
                                   Manager__c = usr2.Id,
                                   VP__c = usr3.Id,
                                   Individual_Credit_Portion__c = 0.500,
                                   Team_Credit_Portion__c = 0.500));
    }
    
    static testMethod void createSalesCreditsTest() {
        Management_System__c management = createManagementSystem();
        database.insert(management);
        
        Account acct = createAccount(management);
        database.insert(acct);

        Account acct2 = createAccount(management);
        database.insert(acct2);
        
        Opportunity opp1 = createOpportunity(acct);
        database.insert(opp1);
        
        Opportunity opp2 = createOpportunity(acct2);
        database.insert(opp2);

        Profile p = createProfile();
        
        User usr1 = createUser1(p);
        database.insert(usr1);
        
        User usr2 = createUser2(p);
        database.insert(usr2);
        
        User usr3 = createUser3(p);
        database.insert(usr3);
        
        User usr4 = createUser4(p);
        database.insert(usr4);
        
        User usr5 = createUser5(p);
        database.insert(usr5);
        
        User usr6 = createUser6(p);
        database.insert(usr6);

        Sales_Target__c st = createTarget(usr2);
        database.insert(st);
        
        Test.startTest();
        Sales_Credit__c sc1 = createSalesCredit(opp1, usr1, usr2, usr3);
        database.insert(sc1);

        Sales_Credit__c sc2 = createSalesCredit(opp2, usr1, usr5, usr6);
        database.insert(sc2);

        List<Sales_Target__c> targets = [SELECT Id, Owner__c, Actual_Credits__c, Target_Date__c
                                        FROM Sales_Target__c];

        Sales_Target__c newTarget;
        for (Sales_Target__c t : targets) {
            if (t.Owner__c == usr1.Id) {
                newTarget = t;
            }
        }
        //System.assertEquals(1.0000, newTarget.Actual_Credits__c);
        
        System.assertEquals(6, targets.size());
        Test.stopTest();
    }


    static testMethod void updateSalesCreditTest() {
        Management_System__c management = createManagementSystem();
        database.insert(management);
        
        Account acct = createAccount(management);
        database.insert(acct);
        
        Opportunity opp = createOpportunity(acct);
        database.insert(opp);

        Profile p = createProfile();
        
        User usr1 = createUser1(p);
        database.insert(usr1);
        
        User usr2 = createUser2(p);
        database.insert(usr2);
        
        User usr3 = createUser3(p);
        database.insert(usr3);
        
        User usr4 = createUser4(p);
        database.insert(usr4);

        Sales_Credit__c sc = createSalesCredit(opp, usr1, usr2, usr3);
        database.insert(sc);

        sc.VP__c = usr4.Id;
        database.update(sc);

        List<Sales_Target__c> targets = [SELECT Id, Owner__c
                                        FROM Sales_Target__c];

        Sales_Target__c newTarget;
        for (Sales_Target__c t : targets) {
            if (t.Owner__c == usr4.Id) {
                newTarget = t;
            }
        }
        System.assertEquals(usr4.Id, newTarget.Owner__c);
    }
}