src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Admin_Last_Sync_Date__c</fullName>
        <description>Stores the date of the last Sync</description>
        <inlineHelpText>This is updated every morning and shows when the last time the office had a successful sync</inlineHelpText>
        <label>Admin Last Sync Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>admin_sync_received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Admin Sync Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Practice_Management_Software__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is the practice management software the customer is using.</description>
        <inlineHelpText>This is the practice management software the customer is using.</inlineHelpText>
        <label>Practice Management Software</label>
        <referenceTo>Management_System__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Intacct_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Determines whether customer records are created at the root or entity level in Intacct.</inlineHelpText>
        <label>Intacct Entity</label>
        <referenceTo>RecurSoft__Intacct_Entity__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>RecurSoft_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Status__c</fullName>
        <description>Picklist used to determine if an account is an active customer.</description>
        <inlineHelpText>Determined by the status of subscriptions (not created, created, not activated, or cancelled)</inlineHelpText>
        <label>ISB Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.3/objects/Asset.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Current_Product_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Shows the related subscription that has the most distant Contract End Date that is not Terminated.  Set from trigger.  Trigger activated by Subscription Last Modified field.</description>
        <label>Current Product Subscription</label>
        <referenceTo>RecurSoft__Product_Subscription__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.3/objects/Cancel_Request__c.object
<CustomObject>
    <description>Junction object between Retention Opportunities and Assets</description>
    <label>Cancel Request</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Cancel Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancel Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipName>OpportunityAssets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cancel_Month__c</fullName>
        <label>Cancel Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>OpportunityAssets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Actively Working</fullName>
                </value>
                <value>
                    <fullName>Negotiating</fullName>
                </value>
                <value>
                    <fullName>Sent Addendum</fullName>
                </value>
                <value>
                    <fullName>Save</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Resume - No Change</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.4/objects/Case.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>Last_Sync_Date__c</fullName>
        <formula>Account.Admin_Last_Sync_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Sync Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Resolution__c</fullName>
        <label>Resolution</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>Wont Fix</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Cannot Reproduce</fullName>
                </value>
                <value>
                    <fullName>Resumed</fullName>
                </value>
                <value>
                    <fullName>Max Attempts Reached</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No Contact</fullName>
                </value>
                <value>
                    <fullName>Made Contact</fullName>
                </value>
                <value>
                    <fullName>Contact Attempted</fullName>
                </value>
                <value>
                    <fullName>Sync Scheduled</fullName>
                </value>
                <value>
                    <fullName>Sync Installed</fullName>
                </value>
                <value>
                    <fullName>Training Scheduled</fullName>
                </value>
                <value>
                    <fullName>Training Completed</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Resolving Issues</fullName>
                </value>
                <value>
                    <fullName>Made Offer</fullName>
                </value>
                <value>
                    <fullName>Sent Addendum</fullName>
                </value>
                <value>
                    <fullName>Offer Rejected</fullName>
                </value>
                <value>
                    <fullName>Dispute Resolution</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Accounting</fullName>
        <active>true</active>
        <businessProcess>Accounting</businessProcess>
        <description>Used to alert Accounting of changes to customers billing</description>
        <label>Accounting</label>
    </recordTypes>
    <recordTypes>
        <fullName>Support</fullName>
        <active>true</active>
        <businessProcess>Support</businessProcess>
        <description>The main case type for Support</description>
        <label>Support</label>
    </recordTypes>
</CustomObject>

force-app/main/default/objects/Case/fields/Sync_Case_Account__c.field-meta.xml
<CustomField>
    <fullName>Sync_Case_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sync Case Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sync Cases</relationshipLabel>
    <relationshipName>Sync_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Cancel_Month__c</fullName>
        <description>Sugar field for Save Opportunity</description>
        <label>Cancel Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_Start_Date__c</fullName>
        <label>Contract Term Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Intacct_Entity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Intacct Entity</label>
        <referenceTo>RecurSoft__Intacct_Entity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>RecurSoft_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/classes/CasesService_Test.cls
/**
 * Created by mschetselaar on 8/21/2018.
 */

@IsTest
private class CasesService_Test {
    @testSetup
    static void testData()
    {
        TestUtilities.newInit();
    }

    @isTest
    static void test_closeCancelledAccountsCases()
    {
        Account a = [SELECT Id, RecurSoft__Status__c FROM Account LIMIT 1];
        a.RecurSoft__Status__c = 'Active';
        update a;
        
        RecurSoft__Product_Subscription__c ps = [SELECT Id, RecurSoft__Contract_Term_Start_Date__c FROM RecurSoft__Product_Subscription__c LIMIT 1];
        ps.RecurSoft__Contract_Term_Start_Date__c = Date.today().addDays(-50);
        update ps;
        
        Cancel_Request__c cr = [SELECT Id, Stage__c, Cancel_Month__c FROM Cancel_Request__c LIMIT 1];
        cr.Stage__c = 'Cancelled';
        cr.Cancel_Month__c = Date.today().toStartOfMonth();
        update cr;

        Id supportCase = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Support').getRecordTypeId();
        Id accountCase = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Accounting').getRecordTypeId();
        Id syncCase = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Sync List Case').getRecordTypeId();
        Id crCase = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Cancel Request').getRecordTypeId();

        List<Case> caseList = new List<Case>();
        for(Integer i = 0; i<4; i++) {
            Case c = new Case(Subject = 'Test Support Case',
                    AccountId = a.Id,
                    Status = 'New',
                    RecordTypeId = i == 0 ? supportCase : i==1 ? accountCase : i == 2 ? syncCase : crCase);
            caseList.add(c);
        }
        insert caseList;

        List<Cancel_Request__c> cros = [
                SELECT
                        Id,
                        Stage__c,
                        Cancel_Month__c,
                        Opportunity__c,
                        Opportunity__r.AccountId,
                        Asset__c,
                        Asset__r.Current_Product_Subscription__r.RecurSoft__Contract_Term_Start_Date__c
                FROM Cancel_Request__c];
        
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        Test.startTest();

        CasesService.closeCancelledAccountsCases(cros, uow);
        uow.commitWork();

        Test.stopTest();

        List<Case> updateCaseList = [SELECT Id, Status, Resolution__c, RecordTypeId FROM Case];
        for (Case newCase : updateCaseList)
        {
            if(newCase.RecordTypeId == supportCase || newCase.RecordTypeId == syncCase)
            {
                System.assertEquals('Closed', newCase.Status, 'The Case Was not Closed');
                System.assertEquals('Wont Fix', newCase.Resolution__c);
                System.debug(newCase);
            } else
            {
                System.assertEquals('New', newCase.Status, 'The Case Was not Closed');
                System.debug(newCase);
            }
        }
    }
    
    @isTest
    static void test_closeCancelledAccountsCases_Reactivate()
    {
        Account a = [SELECT Id, RecurSoft__Status__c FROM Account LIMIT 1];
        a.RecurSoft__Status__c = 'Active';
        update a;
        
        RecurSoft__Product_Subscription__c ps = [SELECT Id, RecurSoft__Contract_Term_Start_Date__c FROM RecurSoft__Product_Subscription__c LIMIT 1];
        ps.RecurSoft__Contract_Term_Start_Date__c = Date.today();
        update ps;
        
        Cancel_Request__c cr = [SELECT Id, Stage__c, Cancel_Month__c FROM Cancel_Request__c LIMIT 1];
        cr.Stage__c = 'Cancelled';
        cr.Cancel_Month__c = Date.today().toStartOfMonth().addMonths(-1);
        update cr;
        
        Id supportCase = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Support').getRecordTypeId();
        Id accountCase = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Accounting').getRecordTypeId();
        Id syncCase = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Sync List Case').getRecordTypeId();
        Id crCase = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Cancel Request').getRecordTypeId();
        
        List<Case> caseList = new List<Case>();
        for(Integer i = 0; i<4; i++) {
            Case c = new Case(Subject = 'Test Support Case',
                    AccountId = a.Id,
                    Status = 'New',
                    RecordTypeId = i == 0 ? supportCase : i==1 ? accountCase : i == 2 ? syncCase : crCase);
            caseList.add(c);
        }
        insert caseList;
    
        List<Cancel_Request__c> cros = [
                SELECT
                        Id,
                        Stage__c,
                        Cancel_Month__c,
                        Opportunity__c,
                        Opportunity__r.AccountId,
                        Asset__c,
                        Asset__r.Current_Product_Subscription__r.RecurSoft__Contract_Term_Start_Date__c
                FROM Cancel_Request__c];
    
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        
        Test.startTest();
            CasesService.closeCancelledAccountsCases(cros, uow);
            uow.commitWork();
        Test.stopTest();
        
        List<Case> updateCaseList = [SELECT Id, Status, Resolution__c, RecordTypeId, RecordType.Name FROM Case];
        for (Case newCase : updateCaseList)
        {
            System.assertEquals('New', newCase.Status, 'The Case Was Closed');
        }
    }

    @IsTest
    static void test_autoCloseSyncCases()
    {
        Account a = [SELECT Id, RecurSoft__Status__c, Admin_Last_Sync_Date__c, Admin_Sync_Received__c FROM Account LIMIT 1];
        a.RecurSoft__Status__c = 'Active';
        a.Admin_Last_Sync_Date__c = Date.today().addDays(-1);
        a.Admin_Sync_Received__c = true;
        update a;

        Id caseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Sync List Case').getRecordTypeId();
        Id queueId = [SELECT Id FROM Group WHERE Type = 'Queue' limit 1].Id;

        Case cUser = new Case(AccountId = a.Id,
                Sync_Case_Account__c = a.Id,
                RecordTypeId = caseRecordTypeId,
                Subject = 'Sync Down',
                Status = 'New');
        insert cUser;

        Case qUser = new Case(AccountId = a.Id,
                OwnerId = queueId,
                RecordTypeId = caseRecordTypeId,
                Subject = 'Sync Down',
                Status = 'New');
        insert qUser;

        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        List<Case> caseList = [SELECT Id, OwnerId, RecordTypeId, Subject, Status, Sync_Case_Account__c, Sync_Case_Account__r.Admin_Last_Sync_Date__c, Sync_Case_Account__r.Admin_Sync_Received__c FROM Case];


        Test.startTest();
            CasesService.autoCloseSyncCases(caseList, uow);
            uow.commitWork();
        Test.stopTest();


        Case[] newCaseList = [SELECT Id, OwnerId, Last_Sync_Date__c, Sync_Case_Account__r.Admin_Last_Sync_Date__c,IsClosed FROM Case];
        for(Case c : newCaseList)
        {
            if(c.OwnerId.getSObjectType() == User.SObjectType) System.assert(c.IsClosed);
            if(c.OwnerId.getSObjectType() == Group.SObjectType) System.assert(!c.IsClosed);
        }
    }
    
    @IsTest
    static void test_autoCloseSyncCases_Enterprise()
    {
        Id childMajorAccountId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Child Major Account').getRecordTypeId();
        Id majorAccountId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Major Account').getRecordTypeId();
        Account a = [SELECT Id, RecurSoft__Status__c, Admin_Last_Sync_Date__c, Admin_Sync_Received__c FROM Account LIMIT 1];
        a.RecordTypeId = childMajorAccountId;
        a.RecurSoft__Status__c = 'Active';
        a.Admin_Last_Sync_Date__c = Date.today().addDays(-1);
        a.Admin_Sync_Received__c = true;
        Account parentAccount = new Account();
        parentAccount.Name = 'Parent Account';
        parentAccount.RecordTypeId = majorAccountId;
//        parentAccount.Practice_Management_Software__c = 'a00i000000Mq9oBAAR';
        parentAccount.Industry = 'Dental';
        parentAccount.RecurSoft__Intacct_Entity__c = 'a1Ai0000001ctUXEAY';
        
        insert parentAccount;
        a.ParentId = parentAccount.Id;
        update a;
        
        Id caseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Sync List Case').getRecordTypeId();
        Id queueId = [SELECT Id FROM Group WHERE Type = 'Queue' limit 1].Id;
        
        Case cUser = new Case(AccountId = parentAccount.Id,
                RecordTypeId = caseRecordTypeId,
                Subject = 'Sync Down',
                Status = 'New',
                Sync_Case_Account__c = a.Id);
        insert cUser;
        
        Case qUser = new Case(AccountId = parentAccount.Id,
                OwnerId = queueId,
                RecordTypeId = caseRecordTypeId,
                Subject = 'Sync Down',
                Status = 'New',
                Sync_Case_Account__c = a.Id);
        insert qUser;
        
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        List<Case> caseList = [SELECT Id, OwnerId, RecordTypeId, Subject, Status, Sync_Case_Account__c, Sync_Case_Account__r.Admin_Last_Sync_Date__c, Sync_Case_Account__r.Admin_Sync_Received__c FROM Case];
        
        
        Test.startTest();
            CasesService.autoCloseSyncCases(caseList, uow);
            uow.commitWork();
        Test.stopTest();
        
        
        Case[] newCaseList = [SELECT Id, OwnerId, Last_Sync_Date__c, Sync_Case_Account__r.Admin_Last_Sync_Date__c,IsClosed FROM Case];
        for(Case c : newCaseList)
        {
            if(c.OwnerId.getSObjectType() == User.SObjectType) System.assert(c.IsClosed);
            if(c.OwnerId.getSObjectType() == Group.SObjectType) System.assert(!c.IsClosed);
        }
    }
}