src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Admin_Last_Sync_Date__c</fullName>
        <description>Stores the date of the last Sync</description>
        <inlineHelpText>This is updated every morning and shows when the last time the office had a successful sync</inlineHelpText>
        <label>Admin Last Sync Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>admin_sync_received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Admin Sync Received</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.3/objects/Asset.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Current_Product_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Shows the related subscription that has the most distant Contract End Date that is not Terminated.  Set from trigger.  Trigger activated by Subscription Last Modified field.</description>
        <label>Current Product Subscription</label>
        <referenceTo>RecurSoft__Product_Subscription__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.3/objects/Cancel_Request__c.object
<CustomObject>
    <description>Junction object between Retention Opportunities and Assets</description>
    <label>Cancel Request</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Cancel Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancel Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipName>OpportunityAssets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cancel_Month__c</fullName>
        <label>Cancel Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Initial Details</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>OpportunityAssets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.4/objects/Case.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>Resolution__c</fullName>
        <label>Resolution</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>Wont Fix</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Cannot Reproduce</fullName>
                </value>
                <value>
                    <fullName>Resumed</fullName>
                </value>
                <value>
                    <fullName>Max Attempts Reached</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Accounting</fullName>
        <active>true</active>
        <businessProcess>Accounting</businessProcess>
        <description>Used to alert Accounting of changes to customers billing</description>
        <label>Accounting</label>
    </recordTypes>
    <recordTypes>
        <fullName>Support</fullName>
        <active>true</active>
        <businessProcess>Support</businessProcess>
        <description>The main case type for Support</description>
        <label>Support</label>
    </recordTypes>
</CustomObject>

force-app/main/default/objects/Case/fields/Distribution_Group__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distribution Group</label>
    <referenceTo>Distribution_Group__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sync_Case_Account__c.field-meta.xml
<CustomField>
    <fullName>Sync_Case_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sync Case Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sync Cases</relationshipLabel>
    <relationshipName>Sync_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src.2/objects/Distribution_Group__c.object
<CustomObject>
    <label>Distribution Group</label>
    <nameField>
        <label>Distribution Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src.3/objects/Distribution_Group_History__c.object
<CustomObject>
    <label>Distribution Group History</label>
    <nameField>
        <label>Distribution Group History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Group Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Distribution_Group__c</fullName>
        <label>Distribution Group</label>
        <referenceTo>Distribution_Group__c</referenceTo>
        <relationshipLabel>Distribution Group Histories</relationshipLabel>
        <relationshipName>Distribution_Group_Histories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Distribution_Group_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Distribution_Group_History__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Distribution Group Histories</relationshipLabel>
    <relationshipName>Distribution_Group_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

src.1/objects/Distribution_Group_Member__c.object
<CustomObject>
    <label>Distribution Group Member</label>
    <nameField>
        <displayFormat>DGM-{000}</displayFormat>
        <label>Distribution Group Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Distribution Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Distribution_Group__c</fullName>
        <label>Distribution Group</label>
        <referenceTo>Distribution_Group__c</referenceTo>
        <relationshipLabel>Distribution Group Members</relationshipLabel>
        <relationshipName>Distribution_Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Distribution_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Cancel_Month__c</fullName>
        <description>Sugar field for Save Opportunity</description>
        <label>Cancel Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_Start_Date__c</fullName>
        <label>Contract Term Start Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

src.1/objects/SR_Default_Values__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SR Default Values</label>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

src.4/classes/CasesService.cls
/**
 * Created by mschetselaar on 8/21/2018.
 */
/*
  __  __       _   _   _                      _____      _          _            _
 |  \/  |     | | | | | |                    / ____|    | |        | |          | |
 | \  / | __ _| |_| |_| |__   _____      __ | (___   ___| |__   ___| |_ ___  ___| | __ _  __ _ _ __
 | |\/| |/ _` | __| __| '_ \ / _ \ \ /\ / /  \___ \ / __| '_ \ / _ \ __/ __|/ _ \ |/ _` |/ _` | '__|
 | |  | | (_| | |_| |_| | | |  __/\ V  V /   ____) | (__| | | |  __/ |_\__ \  __/ | (_| | (_| | |
 |_|  |_|\__,_|\__|\__|_| |_|\___| \_/\_/   |_____/ \___|_| |_|\___|\__|___/\___|_|\__,_|\__,_|_|

                                                                                                     
*/
public with sharing class CasesService
{
    public static void closeCancelledAccountsCases(List<Cancel_Request__c> cros, fflib_SObjectUnitOfWork uow)
    {
        Set<Id> acctIDs = new Set<Id>();
        List<ConnectApi.BatchInput> batchInputs = new List<ConnectApi.BatchInput>();
        for(Cancel_Request__c cro : cros)
        {
            if(cro.Cancel_Month__c < cro.Asset__r.Current_Product_Subscription__r.RecurSoft__Contract_Term_Start_Date__c) continue;
            acctIds.add(cro.Opportunity__r.AccountId);
        }

        for(Case c : [SELECT Id, Status, Resolution__c, OwnerId FROM Case WHERE AccountId IN : acctIDs AND IsClosed = false AND RecordType.Name != 'Accounting' AND RecordType.Name != 'Cancel Request'])
        {
            if(c.OwnerId.getSObjectType() != User.SObjectType) continue;
            c.Status = 'Closed';
            c.Resolution__c = 'Wont Fix';
            uow.registerDirty(c);
            
            ConnectApi.FeedItemInput input = new ConnectApi.FeedItemInput();
            input.subjectId = c.id;
            
            ConnectApi.MessageBodyInput body = new ConnectApi.MessageBodyInput();
            body.messageSegments = new List<ConnectApi.MessageSegmentInput>();
    
            ConnectApi.TextSegmentInput textSegment = new ConnectApi.TextSegmentInput();
            textSegment.text = 'Case closed because the Account has Cancelled';
    
            body.messageSegments.add(textSegment);
            input.body = body;
    
            ConnectApi.BatchInput batchInput = new ConnectApi.BatchInput(input);
            batchInputs.add(batchInput);
        }
        
        if(!test.isRunningTest()) ConnectApi.ChatterFeeds.postFeedElementBatch(Network.getNetworkId(), batchInputs);
    }

    public static void autoCloseSyncCases(List<Case> scope, fflib_SObjectUnitOfWork uow)
    {
        List<ConnectApi.BatchInput> batchInputs = new List<ConnectApi.BatchInput>();
        
        for(Case c : scope) {
            if(c.OwnerId.getSObjectType() != User.SObjectType) continue;
            
            if(c.Sync_Case_Account__r.Admin_Last_Sync_Date__c != Date.today().addDays(-1)) continue;
            if(c.Sync_Case_Account__r.Admin_Sync_Received__c == false ) continue;
            
            c.Status = 'Closed';
            c.Resolution__c = 'Resumed';

            uow.registerDirty(c);
    
            ConnectApi.FeedItemInput input = new ConnectApi.FeedItemInput();
            input.subjectId = c.id;
    
            ConnectApi.MessageBodyInput body = new ConnectApi.MessageBodyInput();
            body.messageSegments = new List<ConnectApi.MessageSegmentInput>();
    
            ConnectApi.TextSegmentInput textSegment = new ConnectApi.TextSegmentInput();
            textSegment.text = 'Case closed because the sync ran the previous day';
    
            body.messageSegments.add(textSegment);
            input.body = body;
    
            ConnectApi.BatchInput batchInput = new ConnectApi.BatchInput(input);
            batchInputs.add(batchInput);
        }
    
        if(!test.isRunningTest()) ConnectApi.ChatterFeeds.postFeedElementBatch(Network.getNetworkId(), batchInputs);   
    }

    public static void processDistributionGroup(Map<Id, Id> caseIdToDistGroupId, fflib_SObjectUnitOfWork uow)
    {
        Case[] cases = (Case[]) CasesSelector.newInstance().selectSObjectsById(caseIdToDistGroupId.keySet());   
        
        Map<Id, Distribution_Group__c> distGroupMap = new Map<Id, Distribution_Group__c>(DistributionGroupsSelector.newInstance().selectById(new Set<Id>(caseIdToDistGroupId.values())));

        for(Case c : cases)
        {
            if(!caseIdToDistGroupId.keySet().contains(c.Id)) return;
            Id distGroupId = caseIdToDistGroupId.get(c.Id);
            
            Distribution_Group__c distGroup = distGroupMap.get(distGroupId);            
            c.Distribution_Group__c = null;
            uow.registerDirty(c);

            User user = DistributionGroupsService.getNextUserId(distGroup.Distribution_Group_Members__r, distGroup.Id, uow);

            if(c.OwnerId != user.Id)
            {               
                c.OwnerId = user.Id;
                uow.registerDirty(c);
            }

            createHistory(distGroup, user, c, uow);
        }
    }

    public static void createHistory(Distribution_Group__c distGroup, User user, Case c, fflib_SObjectUnitOfWork uow)
    {
        Distribution_Group_History__c history = new Distribution_Group_History__c(Name = distGroup.Name + String.valueOf(Datetime.now()),
            Description__c = user.AboutMe,
            Case__c = c.Id,         
            Distribution_Group__c = distGroup.Id,
            User__c = user.Id);
        uow.registerNew(history);
    }
    public static void chatCaseQueue(Map <Id, Case> cases, fflib_SObjectUnitOfWork uow)
    {
        Id csSupporQueue  = (Id) SR_Default_Values__c.getValues('CS Support Queue').Value__c;
        for(case c : cases.values())
        {
            c.OwnerId = csSupporQueue;
            uow.registerDirty(c);
        }

    }
}