src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.3/objects/Asset.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Notes whether or not the Asset is being billed.</description>
        <inlineHelpText>Notes whether or not the Asset is being billed.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src.3/objects/Cancel_Request__c.object
<CustomObject>
    <description>Junction object between Retention Opportunities and Assets</description>
    <label>Cancel Request</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Cancel Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancel Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipName>OpportunityAssets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cancellation_Reasons__c</fullName>
        <label>Cancellation Reasons</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Cancel_Sub_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Staff Change/Resistance</fullName>
                    <color>#66FFFF</color>
                    <label>Staff Change/Resistance</label>
                </value>
                <value>
                    <fullName>Patient complaints</fullName>
                    <color>#33CCFF</color>
                    <label>Patient complaints</label>
                </value>
                <value>
                    <fullName>Acquired/Office Closing</fullName>
                    <color>#66CCCC</color>
                    <label>Acquired/Office Closing</label>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                    <color>#000000</color>
                    <label>Unknown</label>
                </value>
                <value>
                    <fullName>Financial Hardship</fullName>
                    <color>#3366FF</color>
                    <label>Financial Hardship</label>
                </value>
                <value>
                    <fullName>Buyer&#39;s Remorse</fullName>
                    <color>#0B6FCE</color>
                    <label>Buyer&#39;s Remorse</label>
                </value>
                <value>
                    <fullName>Contract Averse</fullName>
                    <color>#0B24BE</color>
                    <label>Contract Averse</label>
                </value>
                <value>
                    <fullName>Timing</fullName>
                    <color>#6666CC</color>
                    <label>Timing</label>
                </value>
                <value>
                    <fullName>ROI/Price</fullName>
                    <color>#000099</color>
                    <label>ROI/Price</label>
                </value>
                <value>
                    <fullName>Incorrect Use of PM</fullName>
                </value>
                <value>
                    <fullName>Outdated Technology</fullName>
                </value>
                <value>
                    <fullName>No Access/Permission To Server</fullName>
                </value>
                <value>
                    <fullName>Provisioned</fullName>
                    <color>#333399</color>
                    <label>Provisioned</label>
                </value>
                <value>
                    <fullName>Invoicing Errors</fullName>
                    <color>#78C953</color>
                    <label>Invoicing Errors</label>
                </value>
                <value>
                    <fullName>Unable to Collect</fullName>
                    <color>#419249</color>
                    <label>Unable to Collect</label>
                </value>
                <value>
                    <fullName>Unavailable Feature</fullName>
                    <color>#FF0000</color>
                    <label>Unavailable Feature</label>
                </value>
                <value>
                    <fullName>Functionality of Current Feature</fullName>
                    <color>#F96FB7</color>
                    <label>Functionality of Current Feature</label>
                </value>
                <value>
                    <fullName>User Experience/Interface</fullName>
                    <color>#CC0000</color>
                    <label>User Experience/Interface</label>
                </value>
                <value>
                    <fullName>No Integration</fullName>
                    <color>#FF6666</color>
                    <label>No Integration</label>
                </value>
                <value>
                    <fullName>Quality/Features</fullName>
                    <color>#A53711</color>
                    <label>Quality/Features</label>
                </value>
                <value>
                    <fullName>Export</fullName>
                    <color>#990000</color>
                    <label>Export</label>
                </value>
                <value>
                    <fullName>Contract/Billing</fullName>
                    <color>#A845DC</color>
                    <label>Contract/Billing</label>
                </value>
                <value>
                    <fullName>Product</fullName>
                    <color>#CC33CC</color>
                    <label>Product</label>
                </value>
                <value>
                    <fullName>Integration</fullName>
                    <color>#CC66CC</color>
                    <label>Integration</label>
                </value>
                <value>
                    <fullName>Bundle (HG/LL Only)</fullName>
                    <color>#FF99FF</color>
                    <label>Bundle (HG/LL Only)</label>
                </value>
                <value>
                    <fullName>Experience</fullName>
                    <color>#F3D904</color>
                    <label>Experience</label>
                </value>
                <value>
                    <fullName>Responsiveness</fullName>
                    <color>#FFCC66</color>
                    <label>Responsiveness</label>
                </value>
                <value>
                    <fullName>Recurring issues</fullName>
                    <color>#CC9933</color>
                    <label>Recurring issues</label>
                </value>
                <value>
                    <fullName>Outreach</fullName>
                    <color>#FFCC33</color>
                    <label>Outreach</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cancel_Request_Type__c</fullName>
        <label>Cancel Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Trial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_MSF__c</fullName>
        <label>Current MSF</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Initial Details</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Months_Gained__c</fullName>
        <label>Months Gained</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Months_Paid_Trial__c</fullName>
        <label>Months Paid - Trial</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Contract_Date__c</fullName>
        <label>Most Recent Contract Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>OpportunityAssets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_Setup_Fee__c</fullName>
        <label>Original Setup Fee</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Projected_Contract_Expiration_Renewal__c</fullName>
        <label>Projected Contract Expiration/Renewal</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Save_MSF__c</fullName>
        <label>Save MSF</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Actively Working</fullName>
                </value>
                <value>
                    <fullName>Negotiating</fullName>
                </value>
                <value>
                    <fullName>Sent Addendum</fullName>
                </value>
                <value>
                    <fullName>Save</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Resume - No Change</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Cancellation_Reasons__c</fullName>
        <description>Sugar field for Retention Opportunities</description>
        <label>Cancellation Reasons</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bankruptcy/Collections/Out of business</fullName>
                </value>
                <value>
                    <fullName>Clean-up / Backlog</fullName>
                </value>
                <value>
                    <fullName>Contract term / length</fullName>
                </value>
                <value>
                    <fullName>In contract with other provider</fullName>
                </value>
                <value>
                    <fullName>Integration</fullName>
                </value>
                <value>
                    <fullName>Merged</fullName>
                </value>
                <value>
                    <fullName>Never trained / not ready</fullName>
                </value>
                <value>
                    <fullName>Not interested</fullName>
                </value>
                <value>
                    <fullName>Not satisfied - current features</fullName>
                </value>
                <value>
                    <fullName>Not satisfied - Sales / personnel</fullName>
                </value>
                <value>
                    <fullName>Not satisfied - Support / personnel</fullName>
                </value>
                <value>
                    <fullName>Not satisfied - unavailable features</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Patient complaints</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                </value>
                <value>
                    <fullName>Refused to give reason / unknown</fullName>
                </value>
                <value>
                    <fullName>Staff resistance</fullName>
                </value>
                <value>
                    <fullName>Sync Issue</fullName>
                </value>
                <value>
                    <fullName>Regulation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cancel_Request_Type__c</fullName>
        <description>Sugar field for Retention Opportunities</description>
        <label>Cancel Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Trial</fullName>
                </value>
                <value>
                    <fullName>Reactivation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Months_Gained__c</fullName>
        <label>Months Gained</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Months_Paid_Trial__c</fullName>
        <inlineHelpText>Enter the number of Months the office has paid at the Original MSF</inlineHelpText>
        <label>Months Paid - Trial</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Contract_Date__c</fullName>
        <description>Sugar field for Save Opportunity</description>
        <label>Most Recent Contract Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Original_Setup_Fee__c</fullName>
        <description>Original Setup Fee used in Retention Opportunities</description>
        <inlineHelpText>Enter the</inlineHelpText>
        <label>Original Setup Fee</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Save_MSF__c</fullName>
        <description>Sugar Field for Save Opportunity</description>
        <label>Save MSF</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Retention</fullName>
        <active>true</active>
        <businessProcess>Save Process</businessProcess>
        <label>Retention</label>
    </recordTypes>
</CustomObject>

src.2/classes/CancelRequest_Test.cls
@isTest
private class CancelRequest_Test {
	
	@testSetup static void testData() {

        Account a = TestUtilities.insertBasicAccount(true);

    }

    @isTest static void activeChangeTest() {

    	Account a = [SELECT Id FROM Account LIMIT 1];
    	Product2 p = [SELECT Id FROM Product2 LIMIT 1];

    	Asset ast = new Asset(Name = 'Test Asset',
    		AccountId = a.Id,
    		Product2Id = p.Id,
    		Active__c = false);

    	insert ast;

    	Opportunity o = TestUtilities.insertRecordTypeOpportunity(a.Id, 'Retention');

    	Cancel_Request__c cr = new Cancel_Request__c(Asset__c = ast.Id,
    		Opportunity__c = o.Id);

    	insert cr;

    	Test.startTest();

    	cr.Stage__c = 'Save';
        cr.Original_Setup_Fee__c = 399;
        cr.Current_MSF__c = 379;
        cr.Most_Recent_Contract_Date__c = Date.today().addDays(-30);
        cr.Cancellation_Reasons__c = 'Not interested';
        cr.Cancel_Request_Type__c = 'Trial';
        cr.Save_MSF__c = 359;
        cr.Months_Gained__c = 2;
        cr.Description__c = 'Description';
        cr.Projected_Contract_Expiration_Renewal__c = Date.today().addDays(5);
        cr.Months_Paid_Trial__c = 1;
    	update cr;

    	Test.stopTest();

    }
}