src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Admin_FMS__c</fullName>
        <description>Stores the date the office first sent a message through their SR account</description>
        <inlineHelpText>This is the official Activation Date that is Auto-populated every morning.</inlineHelpText>
        <label>Admin FMS</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Custom_Settings_Completed__c</fullName>
        <description>Holds the value from the Activation Case</description>
        <label>Custom Settings Completed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Custom_Settings_Scheduled_For__c</fullName>
        <description>Holds the value from the Activation Case</description>
        <label>Custom Settings Scheduled For</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sync_Install_Completed__c</fullName>
        <description>Holds the value from the Activation Case</description>
        <label>Sync Install Completed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sync_Install_Scheduled_For__c</fullName>
        <description>Holds the value from the Activation Case</description>
        <label>Sync Install Scheduled For</label>
        <type>DateTime</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.4/objects/Case.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>Custom_Settings_Completed__c</fullName>
        <label>Custom Settings Completed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Custom_Settings_Scheduled_For__c</fullName>
        <label>Custom Settings Scheduled For</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Final_Call_Completed__c</fullName>
        <label>Final Call Completed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Final_Call__c</fullName>
        <label>Final Call</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>First_Contact__c</fullName>
        <description>The date and time of the first activity on this case</description>
        <label>First Contact</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Graphics_Task_Claimed__c</fullName>
        <label>Graphics Task Claimed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Graphics_Task_Completed__c</fullName>
        <label>Graphics Task Completed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Kick_Off_Call_Completed__c</fullName>
        <label>Kick Off Call Completed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Kick_Off_Call__c</fullName>
        <label>Kick Off Call</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Midway_Decision_Maker_Call_Completed__c</fullName>
        <label>Midway Decision Maker Call Completed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Midway_Decision_Maker_Call__c</fullName>
        <label>Midway Decision Maker Call</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sync_Install_Completed__c</fullName>
        <label>Sync Install Completed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sync_Install_Scheduled_For__c</fullName>
        <label>Sync Install Scheduled For</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Training_Completed__c</fullName>
        <description>The date and time the customer attended the webinar</description>
        <label>Training Completed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Training_Scheduled_For__c</fullName>
        <label>Training Scheduled For</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Training_Scheduled__c</fullName>
        <label>X-Training Scheduled - Don&#39;t Use</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

src.2/classes/CaseProgressExt.cls
public class CaseProgressExt {
    private final Case mycase;
    
    public CaseProgressExt(ApexPages.StandardController controller) {
        if(!Test.isRunningTest()){
            controller.addFields(new List<String>{
                'First_Contact__c',
                'Training_Completed__c', 
                'CreatedDate',
                'Graphics_Task_Completed__c',
                'Graphics_Task_Claimed__c',
                'Custom_Settings_Scheduled_For__c',
                'Custom_Settings_Completed__c',
                'Sync_Install_Scheduled_For__c',
                'Sync_Install_Completed__c',
                'Training_Scheduled_For__c',
                'Training_Scheduled__c',
                'Kick_Off_Call__c',
                'Kick_Off_Call_Completed__c',
                'Final_Call__c',
                'Final_Call_Completed__c',
                'Midway_Decision_Maker_Call__c',
                'Midway_Decision_Maker_Call_Completed__c'
            });
        }
        this.mycase = (Case)controller.getRecord();
    }
    
    public String getFirstContactDate() {
        return getDateFormatted(this.mycase.First_Contact__c);
    }

    public String getTrainingScheduledDate() {
        return getDateFormatted(this.mycase.Training_Scheduled_For__c);
    }
    
    public String getTrainingCompletedDate() {
        return getDateFormatted(this.mycase.Training_Completed__c);
    }
    
    public String getGraphicsClaimedDate() {
        return getDateFormatted(this.mycase.Graphics_Task_Claimed__c);
    }
    
    public String getGraphicsSetupDate() {
        return getDateFormatted(this.mycase.Graphics_Task_Completed__c);
    }
    
    public String getSyncInstallScheduledDate() {
        return getDateFormatted(this.mycase.Sync_Install_Scheduled_For__c);
    }
    
    public String getSyncInstallCompletedDate() {
        return getDateFormatted(this.mycase.Sync_Install_Completed__c);
    }
    
    public String getCustomSettingsScheduledDate() {
        return getDateFormatted(this.mycase.Custom_Settings_Scheduled_For__c);
    }
    
    public String getCustomSettingsCompletedDate() {
        return getDateFormatted(this.mycase.Custom_Settings_Completed__c);
    }
    
    public String getKickOffCallScheduledDate(){
        return getDateFormatted(this.mycase.Kick_Off_Call__c);
    }
    
    public String getKickOffCallCompletedDate(){
        return getDateFormatted(this.mycase.Kick_Off_Call_Completed__c);
    }
    
    public String getFinalCallScheduledDate(){
        return getDateFormatted(this.mycase.Final_Call__c);
    }
    
    public String getFinalCallCompletedDate(){
        return getDateFormatted(this.mycase.Final_Call_Completed__c);
    }
    
    public String getMidwayDecisionMakerCallDate(){
        return getDateFormatted(this.mycase.Midway_Decision_Maker_Call__c);
    }
    
    public String getMidwayDecisionMakerCallCompletedDate(){
        return getDateFormatted(this.mycase.Midway_Decision_Maker_Call_Completed__c);
    }
    
    public String getAdminFMSDate(){
        return getDateFormatted(this.mycase.Account.Admin_FMS__c);
    }
    
    //
    // Internal methods for reuse
    //
    private String getDateFormatted(DateTime dt) {
        if (dt == null) {
            return '';
        }
        
        return dt.format('MMM dd, yyyy');
    }
    
}