src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Practice_Management_Software__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is the practice management software the customer is using.</description>
        <inlineHelpText>This is the practice management software the customer is using.</inlineHelpText>
        <label>Practice Management Software</label>
        <referenceTo>Management_System__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Bill_to_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Default Bill to Account for usage billing.</inlineHelpText>
        <label>Bill to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Bill to Account)</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.3/objects/Cancel_Request__c.object
<CustomObject>
    <description>Junction object between Retention Opportunities and Assets</description>
    <label>Cancel Request</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Cancel Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancel Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipName>OpportunityAssets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Processed_Date__c</fullName>
        <label>Processed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Actively Working</fullName>
                </value>
                <value>
                    <fullName>Negotiating</fullName>
                </value>
                <value>
                    <fullName>Sent Addendum</fullName>
                </value>
                <value>
                    <fullName>Save</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Resume - No Change</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.3/objects/Management_System__c.object
<CustomObject>
    <label>Management System</label>
    <nameField>
        <label>Management System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Management Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Limelight_Available__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SR Schedule Available</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/default/classes/AccountBanner_Controller.cls
public class AccountBanner_Controller 
{
	public Boolean srsEligible { get; set; }
	public Boolean srcEligible { get; set; }

	public AccountBanner_Controller(ApexPages.StandardController stdController) 
	{
		Id acctId = stdController.getId();
		Account acct = (Account) stdController.getRecord();
		Date cancelCutoff = Date.today().addDays(-60);
		
		RecurSoft__Product_Subscription__c[] activeSRSSubscription = [SELECT Id 
			FROM RecurSoft__Product_Subscription__c 
			WHERE RecurSoft__Bill_to_Account__c = :acctId 
			AND RecurSoft__Product__r.Family = 'SR Schedule'
			AND RecurSoft__Billing_Status__c = 'Regular Invoicing'];

		RecurSoft__Product_Subscription__c[] activeSRCSubscription = [SELECT Id 
			FROM RecurSoft__Product_Subscription__c 
			WHERE RecurSoft__Bill_to_Account__c = :acctId 
			AND RecurSoft__Product__r.Family = 'SR Conversations'
			AND RecurSoft__Billing_Status__c = 'Regular Invoicing'];

		Cancel_Request__c[] srsCancelRequest = [SELECT Id 
			FROM Cancel_Request__c 
			WHERE Asset__r.AccountId = :acctId 
			AND Asset__r.Product2.Family = 'SR Schedule'
			AND Stage__c IN ('Cancelled','No Sale')
			AND Processed_Date__c > :cancelCutoff];

		Cancel_Request__c[] srcCancelRequest = [SELECT Id 
			FROM Cancel_Request__c 
			WHERE Asset__r.AccountId = :acctId 
			AND Asset__r.Product2.Family = 'SR Conversations'
			AND Stage__c IN ('Cancelled','No Sale')
			AND Processed_Date__c > :cancelCutoff];

		srsEligible = activeSRSSubscription.isEmpty() && srsCancelRequest.isEmpty() && acct.Practice_Management_Software__r.Limelight_Available__c;
		srcEligible = activeSRCSubscription.isEmpty() && srcCancelRequest.isEmpty(); 
	}
}