src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.1/objects/SR_Default_Values__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SR Default Values</label>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

src.4/classes/BatchAccountIntacctSync.cls
global without sharing class BatchAccountIntacctSync implements Database.Batchable<sObject>, Database.AllowsCallouts
{
	SR_Default_Values__c defaultValues = SR_Default_Values__c.getValues('BatchQueryString');

	global Database.QueryLocator start(Database.BatchableContext BC) 
	{	
		return Database.getQueryLocator(defaultValues.Value__c);
	}

	global void execute(Database.BatchableContext BC, List<Account> scope) 
	{
		for(Account a : scope)
		{
			IntacctIntegrationAccountToCustomer acctSync = new IntacctIntegrationAccountToCustomer(a.Id);
			acctSync.syncAccountWithIntacct();
		}
	}
			
	global void finish(Database.BatchableContext BC) 
	{

	}
}