src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Office_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Office Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.4/objects/Case.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>Playbook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Playbook</label>
        <referenceTo>Playbook__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey_to_be_Sent__c</fullName>
        <label>Survey to be Sent</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fast Track Survey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Playbook</fullName>
        <active>true</active>
        <businessProcess>Support</businessProcess>
        <label>Playbook</label>
    </recordTypes>
</CustomObject>

src.4/objects/Playbook__c.object
<CustomObject>
    <label>Playbook</label>
    <nameField>
        <label>Playbook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playbooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Survey_to_be_Sent__c</fullName>
        <label>Survey to be Sent</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fast Track Survey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.2/objects/Task.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Playbook</fullName>
        <active>true</active>
        <label>Playbook</label>
    </recordTypes>
</CustomObject>

force-app/main/default/classes/PlaybooksService.cls
public class PlaybooksService 
{
    public static void addPlaybooks(Id accountId, Set<Id> playbookIds, fflib_SObjectUnitOfWork uow)
    {
        Playbook__c[] playbooks = PlaybooksSelector.newInstance().selectByIdWithTasks(playbookIds);
        Map<Id, Account> accountMap = AccountsSelector.newInstance().selectByIdWithContacts(new Set<Id>{accountId});
//        System.debug(accountMap);

        for(Playbook__c playbook : playbooks)
        {
            Case c = new Case();
            c.Subject = playbook.Name;
            c.RecordTypeId = SRUtilities.getRecordTypeId('Case', 'Playbook');
            c.Playbook__c = playbook.Id;
            c.ContactId = accountMap.get(accountId).Office_Contact__c;
            c.AccountId = accountId;
            c.Survey_to_be_Sent__c = playbook.Survey_to_be_Sent__c;
            uow.registerNew(c);

            for(Task playbookTask : playbook.Tasks)
            {
                Task caseTask = playbookTask.clone(false);
                caseTask.ActivityDate = Date.today().addDays(Integer.valueOf(playbookTask.Playbook_Number_of_Days__c));
                caseTask.WhoId = c.ContactId;
                caseTask.OwnerId = UserInfo.getUserId();
                caseTask.Status = 'Scheduled';
                uow.registerNew(caseTask, Task.WhatId, c);
            }
        }
    }
}