src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Probable_Most_Recent_K_Date__c</fullName>
        <description>Stores the most recent contract date</description>
        <inlineHelpText>This is the date the contract was likely signed</inlineHelpText>
        <label>Most Recent Contract Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Default Bill to Contact for usage billing.</inlineHelpText>
        <label>Bill to Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>$Source.RecurSoft__Bill_to_Account__c</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.RecurSoft__Bill_to_Account__c</field>
                <operation>equals</operation>
                <value/>
            </filterItems>
            <infoMessage>Contact should have current account.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>RecurSoft_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Bill_to_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Default Bill to Account for usage billing.</inlineHelpText>
        <label>Bill to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Bill to Account)</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__IntacctID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>The Intacct ID of the customer.</inlineHelpText>
        <label>Intacct Customer ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RecurSoft__Intacct_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Determines whether customer records are created at the root or entity level in Intacct.</inlineHelpText>
        <label>Intacct Entity</label>
        <referenceTo>RecurSoft__Intacct_Entity__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>RecurSoft_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Shipping_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Default Ship to Contact for usage billing.</inlineHelpText>
        <label>Ship to Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>$Source.RecurSoft__Bill_to_Account__c</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.RecurSoft__Bill_to_Account__c</field>
                <operation>equals</operation>
                <value/>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (Ship to Contact)</relationshipLabel>
        <relationshipName>RecurSoft_Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Synced_With_Intacct_Date__c</fullName>
        <inlineHelpText>Date of the account synchnronization with Intacct.</inlineHelpText>
        <label>Synced With Intacct Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Synced_With_Intacct__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Status of the account synchnronization with Intacct.</inlineHelpText>
        <label>Synced With Intacct</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.1/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>RecurSoft__Intacct_Contact_ID__c</fullName>
        <label>Intacct Contact ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Synced_With_Intacct_Date__c</fullName>
        <label>Synced With Intacct Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Synced_With_Intacct__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Synced With Intacct</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the related Provider record</description>
        <inlineHelpText>Link to the related Provider record</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill to Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.RecurSoft__Bill_to_Account__c</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>RecurSoft_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Bill_to_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Bill to Account)</relationshipLabel>
        <relationshipName>RecurSoft_OpportunitiesAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_Start_Date__c</fullName>
        <label>Contract Term Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Initial_Contract_Term__c</fullName>
        <defaultValue>12</defaultValue>
        <inlineHelpText>Contract duration, in months.</inlineHelpText>
        <label>Contract Term (Months)</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Intacct_Contact_ID__c</fullName>
        <formula>IF(NOT(ISBLANK(RecurSoft__Billing_Contact__c)), RecurSoft__Billing_Contact__r.RecurSoft__Intacct_Contact_ID__c, NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Intacct Billing Contact ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Intacct_Entity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Intacct Entity</label>
        <referenceTo>RecurSoft__Intacct_Entity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>RecurSoft_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Shipping_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship to Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.RecurSoft__Bill_to_Account__c</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Ship to Contact)</relationshipLabel>
        <relationshipName>RecurSoft_Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Synced_With_Intacct_Date__c</fullName>
        <label>Synced With Intacct Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Synced_With_Intacct__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Synced With Intacct</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Healthgrades</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <description>For selling Healthgrades Premium Profiles</description>
        <label>Healthgrades</label>
    </recordTypes>
</CustomObject>

src.3/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related Provider for the Healthgrades Premium Profile</description>
        <inlineHelpText>The related Provider for the Healthgrades Premium Profile</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_Start_Date__c</fullName>
        <formula>Opportunity.RecurSoft__Contract_Term_Start_Date1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deprecated - Contract Term Start Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Provider__c/Provider__c.object-meta.xml
<CustomObject>
    <description>Used to store information about individual Providers within a Practice.  The Provider information is used for Healthgrades Premium members.</description>
    <label>Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src.4/classes/HealthgradesContractController_Test.cls
@isTest
private class HealthgradesContractController_Test {
	
	@isTest static void testHGContractController() {
		
		Map<ID, SObject> insertSObject = new Map<ID, SObject>();
		Map<ID, SObject> updateSObject = new Map<ID, SObject>();
		Map<ID, SObject> deleteSObject = new Map<ID, SObject>();

		Account a = TestUtilities.insertBasicAccount(true);
		Contact c = TestUtilities.insertBasicContact(a.Id);
		Provider__c p = TestUtilities.insertProvider(a.Id, c.Id, '1');
		Opportunity o = TestUtilities.insertRecordTypeOpportunity(a.Id, 'Healthgrades');
		OpportunityLineItem oppLi = TestUtilities.createOpportunityLineItem(o, TestUtilities.standardPricebookEntries.get('Healthgrades Premium Profile'), 1);
		oppLi.Provider__c = p.Id;
		insertSObject.put(o.Id, oppLi);

		o.RecurSoft__Billing_Contact__c = c.Id;
		o.RecurSoft__Shipping_Contact__c = c.Id;
		o.RecurSoft__Bill_to_Account__c = a.Id;
		o.RecurSoft__Initial_Contract_Term__c = 24;
		o.RecurSoft__Contract_Term_Start_Date__c = Date.today();
		o.RecurSoft__Intacct_Entity__c = a.RecurSoft__Intacct_Entity__c;
		updateSObject.put(o.Id, o);
		
		a.RecurSoft__Synced_With_Intacct__c = true;
		a.RecurSoft__Synced_With_Intacct_Date__c = Date.today();
		a.RecurSoft__IntacctID__c = '12345';
		a.Probable_Most_Recent_K_Date__c = Date.today();
		updateSObject.put(a.Id, a);
		
		c.RecurSoft__Synced_With_Intacct__c = true;
		c.RecurSoft__Synced_With_Intacct_Date__c = Date.today();
		c.RecurSoft__Intacct_Contact_ID__c = '12345';
		updateSObject.put(c.Id, c);
		
		SRUtilities.runDml(insertSObject, updateSObject, deleteSObject, 'HealthgradesContractController_Test');

		PageReference pageRef = Page.HealthgradesContractReview;

		pageRef.getParameters().put('id', p.Id);
		pageRef.getParameters().put('oppId', o.Id);

		Test.setCurrentPage(pageRef);

		HealthgradesContractController controller = new HealthgradesContractController();

		controller.submitForm();
		ApexPages.Message[] msgs = ApexPages.getMessages();
		System.assert(msgs.size() > 0);

		controller.acceptedRenewal = true;
		controller.acceptedTerms = true;
		controller.signName = 'signName';
		controller.requestedEmail = true;

		controller.submitForm();
		controller.calculateContractStartDate(Date.today());
		//controller.generateContractPdf();


		//System.assert(controller.renderConfirmation);
	}
}