src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account Lookup</description>
        <inlineHelpText>Choose the Account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Active Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.2/objects/AsyncRequest__c.object
<CustomObject>
    <description>Used for logging Async requests to be processed.</description>
    <label>AsyncRequest</label>
    <nameField>
        <displayFormat>ASYNC-{0000000}</displayFormat>
        <label>AsyncRequest Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AsyncRequests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src.1/objects/Campaign.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <label>Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nurturing</fullName>
                </value>
                <value>
                    <fullName>Demo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.4/objects/Campaign_Influence__c.object
<CustomObject>
    <label>Campaign Influence</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Influence</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Campaign Influence</relationshipLabel>
        <relationshipName>Campaign_Influence</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Associated_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaign_Influence</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campaign_Add_Date__c</fullName>
        <label>Campaign Add Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Influence</relationshipLabel>
        <relationshipName>Campaign_Influence</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Campaign Influence</relationshipLabel>
        <relationshipName>Campaign_Influence</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Demo_Request_Reason__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Demo Request Reason</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Campaign Influence</relationshipLabel>
        <relationshipName>Campaign_Influence</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaign_Influences</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.1/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>CampaignId__c</fullName>
        <description>Populated by HubSpot to create a CampaignMember for the Id specified.</description>
        <label>CampaignId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Demo_Request_Reason__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Demo Request Reason</label>
        <referenceTo>Campaign_Influence__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies the User that created the record.  May be different than CreatedBy because of automations.  Set via Apex.</description>
        <label>Source User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.1/objects/SR_Default_Values__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SR Default Values</label>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

src.2/classes/CampaignInfluencesService_Test.cls
@isTest
private class CampaignInfluencesService_Test 
{	
	@isTest static void test_createCIs() 
	{
		fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
		fflib_ApexMocks mocks = new fflib_ApexMocks();

		Opportunity opp = (Opportunity) TestUtilities2.newOpportunity()
			.toSObject();
		sfab_FabricatedSObject acct = TestUtilities2.newAccount()
			.setField(Account.Active_Opportunity__c, opp.Id);
		Campaign camp1 = (Campaign) TestUtilities2.newCampaign()
			.toSObject();
		Contact c1 = (Contact) TestUtilities2.newContact()	
			.setField(Contact.CampaignId__c, camp1.Id)
			.setField(Contact.AccountId, ((Account) acct.toSObject()).Id)
			.setParent('Account', acct)				
			.toSObject();
		User user = (User) TestUtilities2.newUser()
			.toSObject();	
		AsyncRequest__c async = (AsyncRequest__c) TestUtilities2.newAsyncRequest()
			.setField(AsyncRequest__c.CreatedDate, Datetime.now())
			.toSObject();	

		Map<Id, Id> contactIdToCampaignId = new Map<Id, Id>{ c1.Id => camp1.Id };
		Map<Id, Id> contactIdToUserId = new Map<Id, Id>{ c1.Id => user.Id };

		ContactsSelector mockSelector = (ContactsSelector) mocks.mock(ContactsSelector.class);

        mocks.startStubbing();
        mocks.when(mockSelector.getSObjectType2())
        	.thenReturn(Contact.SObjectType);
        mocks.when(mockSelector.selectByIdWithAccount(contactIdToCampaignId.keySet()))
        	.thenReturn(new List<Contact>{ c1 });
        mocks.stopStubbing();

        Application.Selector.setMock(mockSelector);

		CampaignInfluencesService.createCIs(contactIdToCampaignId, contactIdToUserId, async, uow);	
		List<Campaign_Influence__c> campInfluenceResult = (List<Campaign_Influence__c>)(uow.m_newListByType.get('Campaign_Influence__c'));

		System.assertEquals(1, uow.m_newListByType.get('Campaign_Influence__c').size());
		System.assertEquals(1, uow.m_dirtyMapByType.get('Contact').size());		
		System.assertEquals(null, uow.m_dirtyMapByType.get('Contact').get(c1.Id).get('CampaignId__c'));		
		System.assertEquals(camp1.Id, campInfluenceResult[0].Campaign__c);
		System.assertEquals(c1.Id, campInfluenceResult[0].Contact__c);
		System.assertEquals(((Account) acct.toSObject()).Id, campInfluenceResult[0].Account__c);
		System.assertEquals(opp.Id, campInfluenceResult[0].Opportunity__c);
		System.assertEquals(user.Id, campInfluenceResult[0].Source_User__c);
		System.assertEquals(async.CreatedDate, campInfluenceResult[0].Campaign_Add_Date__c);
	}

	@isTest static void test_createCIsFromOpps1() 
	{
		fflib_SObjectUnitOfWork uow1 = Application.UnitOfWork.newInstance();
		fflib_ApexMocks mocks = new fflib_ApexMocks();
		
		Account ac1 = (Account) TestUtilities2.newAccount().toSObject();
		Opportunity op1 = (Opportunity) TestUtilities2.newOpportunity()
			.setField(Opportunity.AccountId, ac1.Id)
			.toSObject();
		Campaign  cp1 = (Campaign) TestUtilities2.newCampaign().toSObject();
		User  usr1 = (User) TestUtilities2.newUser().toSObject();
		AsyncRequest__c as1 = (AsyncRequest__c) TestUtilities2.newAsyncRequest()
			.setField(AsyncRequest__c.CreatedDate, Datetime.now())
			.toSObject();
		
		Map<Id,Id> oppIdToCampaignId = new Map<Id, Id>{ op1.Id => cp1.Id };
		Map<Id,Id> oppIdToUserId  = new Map<Id, Id>{ op1.Id => usr1.Id };

		OpportunitiesSelector mockSelector = (OpportunitiesSelector) mocks.mock(OpportunitiesSelector.class);

		mocks.startStubbing();
        mocks.when(mockSelector.getSObjectType2())
        	.thenReturn(Opportunity.SObjectType);
        mocks.when(mockSelector.selectByIdWithAccountAndProducts(oppIdToCampaignId.keySet()))
        	.thenReturn(new List<Opportunity>{ op1 });
        mocks.stopStubbing();

        Application.Selector.setMock(mockSelector);

		CampaignInfluencesService.createCIsFromOpps(oppIdToCampaignId, oppIdToUserId, as1, uow1);
		List<Campaign_Influence__c> campInfluenceResult = (List<Campaign_Influence__c>)(uow1.m_newListByType.get('Campaign_Influence__c'));

		System.assertEquals(1, uow1.m_newListByType.get('Campaign_Influence__c').size());
		System.assertEquals(cp1.Id, campInfluenceResult[0].Campaign__c);		
		System.assertEquals(ac1.Id, campInfluenceResult[0].Account__c);
		System.assertEquals(op1.Id, campInfluenceResult[0].Opportunity__c);
		System.assertEquals(usr1.Id, campInfluenceResult[0].Source_User__c);
		System.assertEquals(as1.CreatedDate, campInfluenceResult[0].Campaign_Add_Date__c);
	}


	@isTest static void test_linkOppOnCIs() 
	{
		fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
		fflib_ApexMocks mocks = new fflib_ApexMocks();
		
		insert new SR_Default_Values__c(Name = 'opportunityCiLookback',
			Description__c = 'opportunityCiLookback',
            Value__c = '90');
		
		sfab_FabricatedSObject oppFab =  TestUtilities2.newOpportunity()
			.setField(Opportunity.CreatedDate, Date.newInstance(2017, 01, 20));

		Opportunity opp = (Opportunity) oppFab.toSObject();

		sfab_FabricatedSObject acFab =  TestUtilities2.newAccount()
			.setField(Account.Active_Opportunity__c, opp.Id)
			.setParent('Active_Opportunity__r', oppFab);	
		
		Account ac = (Account) acFab.toSObject();

		Campaign_Influence__c cis = (Campaign_Influence__c) TestUtilities2.newCampaignInfluence()			
			.setField(Campaign_Influence__c.Campaign_Add_Date__c, Date.newInstance(2018, 06, 20))
			.setField(Campaign_Influence__c.Account__c, ac.Id)
			.setParent('Account__r', acFab)							
			.toSObject();

		Set<Id> ids = new Set<Id>();
		ids.add(ac.Id);		

		CampaignInfluencesSelector mockSelector = (CampaignInfluencesSelector) mocks.mock(CampaignInfluencesSelector.class);

        mocks.startStubbing();
        mocks.when(mockSelector.getSObjectType2())
        	.thenReturn(Campaign_Influence__c.SObjectType);
        mocks.when(mockSelector.selectCisByAccountId(ids))
        	.thenReturn(new List<Campaign_Influence__c>{ cis });
        mocks.stopStubbing();

        Application.Selector.setMock(mockSelector);

		CampaignInfluencesService.linkOppOnCIs(ids, uow);	
		
		System.assertEquals(1, uow.m_dirtyMapByType.get('Campaign_Influence__c').size());
		System.assertEquals(opp.Id, cis.Opportunity__c);
	}

	@isTest static void test_setDemoRequestReason() 
	{
		fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
		fflib_ApexMocks mocks = new fflib_ApexMocks();			

		sfab_FabricatedSObject c = TestUtilities2.newCampaign()
			.setField(Campaign.Sub_Type__c, 'Demo');

		sfab_FabricatedSObject ci = TestUtilities2.newCampaignInfluence()			
			.setField(Campaign_Influence__c.Demo_Request_Reason__c, true)
			.setField(Campaign_Influence__c.Campaign_Add_Date__c, Date.today())			
			.setParent('Campaign__r', c);
			
		Campaign_Influence__c cis = (Campaign_Influence__c) ci.toSObject();

		Opportunity opp = (Opportunity) TestUtilities2.newOpportunity()
			.setChildren('Campaign_Influence__r', new List<sfab_FabricatedSObject> { ci })
			.toSObject();			
		
		CampaignInfluencesService.setDemoRequestReason(new List<Opportunity> {opp}, uow);			
		
		System.assertEquals(1, uow.m_dirtyMapByType.get('Campaign_Influence__c').size());				
		System.assertEquals(1, uow.m_dirtyMapByType.get('Opportunity').size());				
		System.assertEquals(cis.Id, opp.Demo_Request_Reason__c);
		System.assertEquals(true, cis.Demo_Request_Reason__c);
	}
}