src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.4/objects/Case.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>HG_Conditions__c</fullName>
        <label>HG Conditions</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>HG_Procedures__c</fullName>
        <label>HG Procedures</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>HG_PWID__c</fullName>
        <formula>Provider__r.PUID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>HG PWID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HG_Specialties__c</fullName>
        <label>HG Specialties</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the related Opportunity for this drop.</description>
        <inlineHelpText>Use this field to choose the related Opportunity for this drop.</inlineHelpText>
        <label>Related Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resolution__c</fullName>
        <label>Resolution</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>Wont Fix</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Cannot Reproduce</fullName>
                </value>
                <value>
                    <fullName>Resumed</fullName>
                </value>
                <value>
                    <fullName>Max Attempts Reached</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sugar_Case_Number__c</fullName>
        <inlineHelpText>This is the Case number in Sugar for your reference.</inlineHelpText>
        <label>Sugar Case Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_to_be_Sent__c</fullName>
        <label>Survey to be Sent</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fast Track Survey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Playbook</fullName>
        <active>true</active>
        <businessProcess>Support</businessProcess>
        <label>Playbook</label>
    </recordTypes>
    <recordTypes>
        <fullName>Support</fullName>
        <active>true</active>
        <businessProcess>Support</businessProcess>
        <description>The main case type for Support</description>
        <label>Support</label>
    </recordTypes>
</CustomObject>

force-app/main/default/objects/Case/fields/Sync_Case_Account__c.field-meta.xml
<CustomField>
    <fullName>Sync_Case_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sync Case Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sync Cases</relationshipLabel>
    <relationshipName>Sync_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Provider__c/Provider__c.object-meta.xml
<CustomObject>
    <description>Used to store information about individual Providers within a Practice.  The Provider information is used for Healthgrades Premium members.</description>
    <label>Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src.1/objects/SR_Default_Values__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SR Default Values</label>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/CasesSelector.cls
public class CasesSelector extends fflib_SObjectSelector 
{
	public Schema.SObjectField[] getSObjectFieldList() 
	{
		return new List<Schema.SObjectField> {
			Case.Id,
			Case.AccountId,
			Case.ContactId,
			Case.HG_Conditions__c,
			Case.HG_PWID__c,
			Case.HG_Procedures__c,
			Case.HG_Specialties__c,
			Case.Origin,
			Case.OwnerId,
			Case.Priority,
			Case.Provider__c,
			Case.RecordTypeId,
			Case.Related_Opportunity__c,
			Case.Resolution__c,
			Case.Status,
			Case.Subject,
			Case.Sugar_Case_Number__c,
            Case.Survey_to_be_Sent__c,
			Case.Sync_Case_Account__c
		};
	}

	public Schema.SObjectType getSObjectType()
	{
		return Case.SObjectType;
	}

	public static CasesSelector newInstance()
	{
		return (CasesSelector) Application.Selector.newInstance(Case.SObjectType);
	}

	public Case[] selectByAccountIdWithTasks(Set<Id> accountIds)
	{
		fflib_QueryFactory caseQueryFactory = newQueryFactory();

		fflib_QueryFactory taskQueryFactory = caseQueryFactory.subselectQuery('Tasks')
        	.selectFields(new TasksSelector().getSObjectFieldList());

		return (Case[]) Database.query(
			caseQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList()))
				.setCondition('AccountId IN :accountIds AND IsClosed = false AND RecordType.Name = \'Playbook\'')
				.toSOQL());
	}

	public Case[] selectSupportAndSyncCasesByAccounts(Account[] accounts)
	{

        Set<Id> ids = new Set<Id>();
        for (Account a : accounts)
        {
            ids.add(a.Id);
        }
		fflib_QueryFactory caseQueryFactory = newQueryFactory();

		return (Case[]) Database.query(
				caseQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList()))
				.setCondition('AccountId IN :ids AND IsClosed = false AND (RecordType.Name = \'Support\' OR RecordType.Name = \'Sync List Case\')')
				.toSOQL());
	}

	public Database.QueryLocator queryLocatorResumedSyncCases()
	{
		Id caseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Sync List Case').getRecordTypeId();
		String condition = 'IsClosed = False AND RecordTypeId = :caseRecordTypeId AND Status != \'Resolved\' AND Status!= \'Scheduled\' AND Status != \'Dedicated\'';

		fflib_QueryFactory caseQueryFactory = newQueryFactory();
		new AccountsSelector().configureQueryFactoryFields(caseQueryFactory, 'Account');
		new AccountsSelector().configureQueryFactoryFields(caseQueryFactory, 'Sync_Case_Account__r');
		
		return Database.getQueryLocator(
				caseQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList())).
						setCondition(condition).
						toSOQL());
	}
	
	public Case[] selectOpenSyncCasesForEnterpriseAccounts(List<Account> accts)
	{
		fflib_QueryFactory caseQueryFactory = newQueryFactory();
		Set<Id> ids = new Set<Id>();
		for(Account a : accts)
		{
			if(a.ParentId != null) ids.add(a.ParentId);
		}
		new AccountsSelector().configureQueryFactoryFields(caseQueryFactory, 'Account');
		
		return (Case[]) Database.query(
				caseQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList()))
				.setCondition('ISClosed = false AND RecordType.Name = \'Sync List Case\' AND ' +
						'(AccountId IN :ids OR Sync_Case_Account__c IN :ids)')
				.toSOQL());
	}

	public Database.QueryLocator selectChatCaseQueue ()
	{
		fflib_QueryFactory caseQueryFactory = newQueryFactory();
		Id chatQueueId = (Id) SR_Default_Values__c.getValues('ChatBotQueueId').Value__c;

		return Database.getQueryLocator(
				caseQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList()))
						//setcondition where like in soql
						.setCondition('OwnerId = :chatQueueId')
						.toSOQL());
	}
}