src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Account_Sales_Status__c</fullName>
        <label>Account Sales Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Contacted</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Bogus</fullName>
                </value>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Active_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Active Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Admin_FMS__c</fullName>
        <description>Stores the date the office first sent a message through their SR account</description>
        <inlineHelpText>This is the official Activation Date that is Auto-populated every morning.</inlineHelpText>
        <label>Admin FMS</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Admin_Last_Sync_Date__c</fullName>
        <description>Stores the date of the last Sync</description>
        <inlineHelpText>This is updated every morning and shows when the last time the office had a successful sync</inlineHelpText>
        <label>Admin Last Sync Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Admin_Status__c</fullName>
        <inlineHelpText>Is this account&#39;s appAdmin Account Active and sending out messages?</inlineHelpText>
        <label>Admin Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>admin_sync_received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Admin Sync Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Care_Credit_Merchant_ID__c</fullName>
        <description>Enter the Care Credit Merchant ID, if this customer has Care Credit. If they do not, leave this field blank.</description>
        <inlineHelpText>Enter the Care Credit Merchant ID, if this customer has Care Credit. If they do not, leave this field blank.</inlineHelpText>
        <label>Care Credit Merchant ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IntacctID__c</fullName>
        <description>Old field that is here temporarily to fix the AppAdmin API</description>
        <label>Old Intacct ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_HG_Scorecard_Date__c</fullName>
        <label>Last HG Scorecard Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Last_ROE_Date__c</fullName>
        <label>Last ROE Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Limelight_URL_for_Healthgrades__c</fullName>
        <description>Only populated for active Limelight subscribers.

Populated via DLRS- Account Limelight URL</description>
        <label>Limelight URL for Healthgrades</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Limelight_URL__c</fullName>
        <label>Limelight URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Active_CI__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Active CI</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Locations__c</fullName>
        <label>Number of Locations</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0-9</fullName>
                </value>
                <value>
                    <fullName>10-49</fullName>
                </value>
                <value>
                    <fullName>50-100</fullName>
                </value>
                <value>
                    <fullName>100+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Open_NPB_Opps__c</fullName>
        <description>Used to validate that only one NPB Opportunity is open at a time.</description>
        <label>Number of Open NPB Opps</label>
        <summaryFilterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>New Practice Business, Add Product, Enterprise New Business</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Opportunity.StageName</field>
            <operation>notEqual</operation>
            <value>Closed Won, Closed Lost, Not Qualified</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Number_of_Providers__c</fullName>
        <label>Number of Providers</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0-10</fullName>
                </value>
                <value>
                    <fullName>11-29</fullName>
                </value>
                <value>
                    <fullName>30-49</fullName>
                </value>
                <value>
                    <fullName>50+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Office_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Office Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>of_Open_Sync_Cases__c</fullName>
        <label># of Open Sync Cases</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Probable_Most_Recent_K_Date__c</fullName>
        <description>Stores the most recent contract date</description>
        <inlineHelpText>This is the date the contract was likely signed</inlineHelpText>
        <label>Most Recent Contract Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.4/objects/Campaign_Influence__c.object
<CustomObject>
    <label>Campaign Influence</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Influence</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Campaign Influence</relationshipLabel>
        <relationshipName>Campaign_Influence</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_ROE_Date__c</fullName>
        <formula>if(  Lead__c != null , Lead__r.Last_ROE_Task_Date__c ,  Opportunity__r.Last_ROE_Task_Date__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last ROE Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Campaign Influence</relationshipLabel>
        <relationshipName>Campaign_Influence</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.1/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account_Sales_Status__c</fullName>
        <description>Apex mapping via Parent/Child Mappings</description>
        <label>Account Sales Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Contacted</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Bogus</fullName>
                </value>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_ROE_Date__c</fullName>
        <description>Apex mapping via Parent/Child Mappings</description>
        <label>Last ROE Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Number_of_Locations__c</fullName>
        <label>Number of Locations</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1-5</fullName>
                </value>
                <value>
                    <fullName>6-24</fullName>
                </value>
                <value>
                    <fullName>25-100</fullName>
                </value>
                <value>
                    <fullName>100+</fullName>
                </value>
                <value>
                    <fullName>1-4</fullName>
                </value>
                <value>
                    <fullName>5-24</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Providers__c</fullName>
        <label>Number of Providers</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1-50</fullName>
                </value>
                <value>
                    <fullName>51-100</fullName>
                </value>
                <value>
                    <fullName>101-300</fullName>
                </value>
                <value>
                    <fullName>300+</fullName>
                </value>
                <value>
                    <fullName>1-20</fullName>
                </value>
                <value>
                    <fullName>21-124</fullName>
                </value>
                <value>
                    <fullName>125+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Admin_FMS__c</fullName>
        <formula>Account.MRFMS__c</formula>
        <label>Admin FMS</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IntacctID__c</fullName>
        <description>Do NOT use. Only created temporarily to fix the broken contract process. When that field has been changed to the Recursoft__IntacctID__c, then we can delete this field.</description>
        <label>Old Intacct ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Locations__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Manually populated by sales rep.  Verified by Deal Desk at close.</description>
        <label>Number of Locations</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Providers__c</fullName>
        <label>Number of Providers</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/default/classes/AccountsSelector.cls
public class AccountsSelector extends fflib_SObjectSelector 
{	
	public Schema.SObjectField[] getSObjectFieldList() 
	{
		return new List<Schema.SObjectField> {
			Account.Id,
			Account.Account_Sales_Status__c,
			Account.Active_Opportunity__c,
			Account.Admin_Last_Sync_Date__c,
            Account.Admin_FMS__c,
            Account.Admin_Status__c,
			Account.Admin_Sync_Received__c,
			Account.BillingStreet,
			Account.BillingCity,
			Account.BillingState,
			Account.BillingStateCode,
			Account.BillingPostalCode,
			Account.BillingCountry,
			Account.BillingCountryCode,
			Account.Care_Credit_Merchant_ID__c,
			Account.Description,
			Account.Fax,
			Account.Industry,
			Account.IntacctID__c,
			Account.Last_HG_Scorecard_Date__c,
			Account.Last_ROE_Date__c,
			Account.Limelight_URL__c,
			Account.Limelight_URL_for_Healthgrades__c,
			Account.Name,
			Account.Number_of_Active_CI__c,
			Account.Number_of_Locations__c,
			Account.Number_of_Open_NPB_Opps__c,
			Account.Number_of_Providers__c,
            Account.of_Open_Sync_Cases__c,
			Account.Office_Contact__c,
			Account.OwnerId,
			Account.ParentId,
			Account.Phone,
			Account.Probable_Most_Recent_K_Date__c,
			Account.Practice_Management_Software__c,
			Account.RecordTypeId,
			Account.RecurSoft__Billing_Email__c,
			Account.RecurSoft__Status__c,
			Account.Sales_Engineer_Call_Completed__c,
			Account.ShippingStreet,
			Account.ShippingCity,
			Account.ShippingState,
			Account.ShippingStateCode,
			Account.ShippingPostalCode,
			Account.ShippingCountry,
			Account.ShippingCountryCode,
			Account.SR_Price_Book__c,
			Account.SR_Timezone__c,
			Account.Subscriber_ID__c,
			Account.Sub_Vertical__c,
			Account.Timed_Distribution_Group_Date__c,
			Account.tz__Timezone__c,
			Account.Website };
	}

	public Schema.SObjectType getSObjectType()
	{
		return Account.SObjectType;
	}

	public static AccountsSelector newInstance()
	{
		return (AccountsSelector) Application.Selector.newInstance(Account.SObjectType);
	}

	public Account[] selectByBillToContact(Set<Id> ids)
	{
		assertIsAccessible();

		OpportunitiesSelector opportunitiesSelector = new OpportunitiesSelector();
		opportunitiesSelector.assertIsAccessible();

		return Database.query(
			String.format(
				'SELECT {0} ' +
				'FROM {1} WHERE Id IN {2} ORDER BY {3}', 
				new List<String>{ 
					getFieldListString(),
					getSObjectName(),
					'(SELECT AccountId FROM Opportunity WHERE RecurSoft__Billing_Contact__c IN :ids)' ,
					getOrderBy()}));
	}

	public Map<Id, Account> selectAccountByContactWithParentAccount(Contact[] contacts)
	{
		Set<Id> ids = new Set<Id>();

		for(Contact contact : contacts)
		{
			ids.add(contact.AccountId);
		}

		fflib_QueryFactory accountQueryFactory = newQueryFactory();

		fflib_QueryFactory opportunityQueryFactory = new OpportunitiesSelector().addQueryFactorySubselect(accountQueryFactory).setCondition('RecordType.Name IN (\'New Practice Business\',\'Add Product\',\'Enterprise New Business\') AND IsClosed = false');

		fflib_QueryFactory taskQueryFactory = new TasksSelector().addQueryFactorySubselect(accountQueryFactory).setCondition('ADR_Set__c = true AND ADR_Set_Received__c = false');

		new AccountsSelector().configureQueryFactoryFields(accountQueryFactory, 'Parent');

		new UsersSelector().configureQueryFactoryFields(accountQueryFactory, 'Owner');

		new UsersSelector().configureQueryFactoryFields(accountQueryFactory, 'Parent.Owner');

		return new Map<Id, Account>((Account[]) Database.query(
			accountQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList())).setCondition('Id IN :ids').toSOQL()));
	}

	public Map<Id, Account> selectParentAccountByAccount(Account[] accounts)
	{
		Set<Id> ids = new Set<Id>();

		for(Account account : accounts)
		{
			if(account.ParentId == null) continue;
			
			ids.add(account.ParentId);
		}

		fflib_QueryFactory accountQueryFactory = newQueryFactory();

		fflib_QueryFactory opportunityQueryFactory = new OpportunitiesSelector().addQueryFactorySubselect(accountQueryFactory).setCondition('RecordType.Name IN (\'New Practice Business\',\'Add Product\',\'Enterprise New Business\') AND IsClosed = false');

		new UsersSelector().configureQueryFactoryFields(accountQueryFactory, 'Owner');

		return new Map<Id, Account>((Account[]) Database.query(
			accountQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList())).setCondition('Id IN :ids').toSOQL()));
	}

	public Map<Id, Account> selectAccountByOpportunityWithAssets(Opportunity[] opportunities)
	{
		Set<Id> ids = new Set<Id>();

		for(Opportunity opportunity : opportunities)
		{
			ids.add(opportunity.AccountId);
		}

		fflib_QueryFactory accountQueryFactory = newQueryFactory();

		fflib_QueryFactory assetQueryFactory = new AssetsSelector().addQueryFactorySubselect(accountQueryFactory);

		new ProductsSelector().configureQueryFactoryFields(assetQueryFactory, 'Product2');

		new ProvidersSelector().configureQueryFactoryFields(assetQueryFactory, 'Provider__r');

		return new Map<Id, Account>((Account[]) Database.query(
			accountQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList())).setCondition('Id IN :ids').toSOQL()));
	}

	public Account[] selectBySubscriberId(Set<String> subscriberIds)
	{
		fflib_QueryFactory accountQueryFactory = newQueryFactory();

		new ContactsSelector().configureQueryFactoryFields(accountQueryFactory, 'Office_Contact__r');

		new ManagementSystemsSelector().configureQueryFactoryFields(accountQueryFactory, 'Practice_Management_Software__r');

		return Database.query(
			accountQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList())).setCondition('Subscriber_Id__c IN :subscriberIds').toSOQL());
	}

	public Account[] selectByIdWithAssets(Set<Id> ids)
	{
		fflib_QueryFactory accountQueryFactory = newQueryFactory();

		fflib_QueryFactory assetQueryFactory = new AssetsSelector().addQueryFactorySubselect(accountQueryFactory);

		new ProductsSelector().configureQueryFactoryFields(assetQueryFactory, 'Product2');

		new ProvidersSelector().configureQueryFactoryFields(assetQueryFactory, 'Provider__r');

		return Database.query(
			accountQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList())).setCondition('Id IN :ids').toSOQL());
	}

	public Map<Id, Account> selectByOpportunityWithCases(Opportunity[] opportunities)
	{
		Set<Id> ids = new Set<Id>();

		for(Opportunity opportunity : opportunities)
		{
			ids.add(opportunity.AccountId);
		}

		fflib_QueryFactory accountQueryFactory = newQueryFactory();

		fflib_QueryFactory caseQueryFactory = new CasesSelector().addQueryFactorySubselect(accountQueryFactory);

		return new Map<Id, Account>((Account[]) Database.query(
			accountQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList())).setCondition('Id IN :ids').toSOQL()));
	}

	public Account[] selectBySubscriptionsWithAssets(RecurSoft__Product_Subscription__c[] subscriptions)
	{
		Set<Id> ids = new Set<Id>();

		for(RecurSoft__Product_Subscription__c subscription : subscriptions)
		{
			ids.add(subscription.RecurSoft__Account__c);
		}

		fflib_QueryFactory accountQueryFactory = newQueryFactory();

		fflib_QueryFactory assetQueryFactory = new AssetsSelector().addQueryFactorySubselect(accountQueryFactory);

		new ProductsSelector().configureQueryFactoryFields(assetQueryFactory, 'Product2');

		new ProvidersSelector().configureQueryFactoryFields(assetQueryFactory, 'Provider__r');

		return (Account[]) Database.query(
			accountQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList())).setCondition('Id IN :ids').toSOQL());
	}

	public Map<Id, Account> selectByIdWithContacts(Set<Id> ids)
	{
		fflib_QueryFactory accountQueryFactory = newQueryFactory();

		fflib_QueryFactory contactQueryFactory = accountQueryFactory.subselectQuery('Contacts')
        	.selectFields(new ContactsSelector().getSObjectFieldList());

		return new Map<Id, Account>((Account[]) Database.query(
			accountQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList())).setCondition('Id IN :ids').toSOQL()));
	}

	public Map<Id, Account> selectByIdWithContacts(Case[] cases)
	{
		Set<Id> ids = new Set<Id>();

		for(Case c : cases)
		{
			ids.add(c.AccountId);
		}

		return this.selectByIdWithContacts(ids);
	}

	public Account[] selectByIdWithParentAccount(Set<Id> ids)
	{
		fflib_QueryFactory accountQueryFactory = newQueryFactory();

		new AccountsSelector().configureQueryFactoryFields(accountQueryFactory, 'Parent');

		return (Account[]) Database.query(
			accountQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList())).setCondition('Id IN :ids').toSOQL());
	}

	public Account[] selectByIdWithContactsAndOpportunities(Set<Id> ids)
	{
		fflib_QueryFactory accountQueryFactory = newQueryFactory();

		fflib_QueryFactory contactQueryFactory = accountQueryFactory.subselectQuery('Contacts')
        	.selectFields(new ContactsSelector().getSObjectFieldList());

        fflib_QueryFactory opportunityQueryFactory = accountQueryFactory.subselectQuery('Opportunities')
        	.selectFields(new OpportunitiesSelector().getSObjectFieldList());

        fflib_QueryFactory taskQueryFactory = accountQueryFactory.subselectQuery('Tasks')
        	.selectFields(new TasksSelector().getSObjectFieldList());

		return (Account[]) Database.query(
			accountQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList())).setCondition('Id IN :ids').toSOQL());
	}

	public Account[] selectByIdWithManagerAndVP(Set<Id> ids)
	{
		fflib_QueryFactory accountQueryFactory = newQueryFactory();

		new UsersSelector().configureQueryFactoryFields(accountQueryFactory, 'Owner');

		new UsersSelector().configureQueryFactoryFields(accountQueryFactory, 'Owner.Manager');

		return (Account[]) Database.query(
			accountQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList())).setCondition('Id IN :ids').toSOQL());
	} 

	public Map<Id, Account> selectByIdWithDemoRequestReason(Set<Id> ids)
	{
		fflib_QueryFactory accountQueryFactory = newQueryFactory();

		new OpportunitiesSelector().configureQueryFactoryFields(accountQueryFactory, 'Active_Opportunity__r');

		fflib_QueryFactory campaignInfluenceQueryFactory = accountQueryFactory.subselectQuery('Campaign_Influence__r')
        	.selectFields(new CampaignInfluencesSelector().getSObjectFieldList())
        	.setCondition('Campaign__r.Sub_Type__c = \'Demo\'')
        	.addOrdering('Campaign_Add_Date__c', fflib_QueryFactory.SortOrder.DESCENDING)
        	.setLimit(1);

		return new Map<Id, Account>((Account[]) Database.query(
			accountQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList())).setCondition('Id IN :ids').toSOQL()));
	}
	
	public Database.QueryLocator queryLocatorSyncDown()
	{
		//String conditionTest = 'Id IN (\'0010Z00001sr1Wy\',\'0010Z00001sr3om\',\'0010Z00001srAIJ\',\'0010Z00001srAvX\' 
		//,\'0010Z00001srM4H\',\'0010Z00001srWw3\',\'0010Z00001srbea\',\'0010Z00001srcZa\',\'0010Z00001srdvY\',\'0010Z00001srfLG\')';
		String condition = 'RecurSoft__Status__c = \'Active\' AND Admin_Sync_Received__c = false ' +
			'AND of_Open_Sync_Cases__c = 0 AND Do_Not_Support_Sync__c = false AND Admin_Last_Sync_Date__c != null';
		
		fflib_QueryFactory accountQueryFactory = newQueryFactory();

		return Database.getQueryLocator(
			accountQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList())).
				setCondition(condition).
				toSOQL());
	}
	
	public Map<Id, Account> selectAccountsBySet(Set<Id>ids)
	{
		fflib_QueryFactory accountQueryFactory = newQueryFactory();
		
		return new Map<Id, Account>((Account[]) Database.query(
				accountQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList())).setCondition('Id IN :ids').toSOQL()));
	}
	
}