src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Account_Sales_Status__c</fullName>
        <label>Account Sales Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Contacted</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Bogus</fullName>
                </value>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.1/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account_Sales_Status__c</fullName>
        <description>Apex mapping via Parent/Child Mappings</description>
        <label>Account Sales Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Contacted</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Bogus</fullName>
                </value>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.4/objects/Five9_Disposition_Mapping__c.object
<CustomObject>
    <label>Five9 Disposition Mapping</label>
    <nameField>
        <displayFormat>F9D-{0000}</displayFormat>
        <label>Five9 Disposition Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Five9 Disposition Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Account_Sales_Status__c</fullName>
        <label>Account Sales Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bogus</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Activity_Results__c</fullName>
        <label>Activity Results</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Future Event</fullName>
                </value>
                <value>
                    <fullName>Left Brochure</fullName>
                </value>
                <value>
                    <fullName>Left Voice Mail</fullName>
                </value>
                <value>
                    <fullName>No Answer/ Busy Signal</fullName>
                </value>
                <value>
                    <fullName>No-Show</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Rescheduled</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Spoke with-</fullName>
                </value>
                <value>
                    <fullName>Ownership Change</fullName>
                </value>
                <value>
                    <fullName>Note</fullName>
                </value>
                <value>
                    <fullName>Reminder</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Remoted in</fullName>
                </value>
                <value>
                    <fullName>Answered Reps Questions</fullName>
                </value>
                <value>
                    <fullName>Missed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <label>Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In-Person Cold Call</fullName>
                </value>
                <value>
                    <fullName>In-Person Demo</fullName>
                </value>
                <value>
                    <fullName>In-Person Follow Up</fullName>
                </value>
                <value>
                    <fullName>Inbound Call</fullName>
                </value>
                <value>
                    <fullName>Outbound Call</fullName>
                </value>
                <value>
                    <fullName>Phone Cold Call</fullName>
                </value>
                <value>
                    <fullName>Phone Demo</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Administrative/Other</fullName>
                </value>
                <value>
                    <fullName>OSR Event</fullName>
                </value>
                <value>
                    <fullName>ESR Event</fullName>
                </value>
                <value>
                    <fullName>Graphics Setup</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Sync Install</fullName>
                </value>
                <value>
                    <fullName>Custom Settings</fullName>
                </value>
                <value>
                    <fullName>Kick Off Call</fullName>
                </value>
                <value>
                    <fullName>Midway Decision Maker Call</fullName>
                </value>
                <value>
                    <fullName>Final Call</fullName>
                </value>
                <value>
                    <fullName>LinkedIn Message</fullName>
                </value>
                <value>
                    <fullName>Group Practice</fullName>
                </value>
                <value>
                    <fullName>PRT</fullName>
                </value>
                <value>
                    <fullName>Newsletters</fullName>
                </value>
                <value>
                    <fullName>Groups</fullName>
                </value>
                <value>
                    <fullName>SR Portal</fullName>
                </value>
                <value>
                    <fullName>Online Presence</fullName>
                </value>
                <value>
                    <fullName>New Integration</fullName>
                </value>
                <value>
                    <fullName>General Training</fullName>
                </value>
                <value>
                    <fullName>Tech Help</fullName>
                </value>
                <value>
                    <fullName>Recall</fullName>
                </value>
                <value>
                    <fullName>Reminders</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Five9_Disposition__c</fullName>
        <label>Five9 Disposition</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Blacklisted</fullName>
                </value>
                <value>
                    <fullName>Bogus</fullName>
                </value>
                <value>
                    <fullName>Cold Call</fullName>
                </value>
                <value>
                    <fullName>Demo</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Existing Customer</fullName>
                </value>
                <value>
                    <fullName>Follow-up</fullName>
                </value>
                <value>
                    <fullName>Inbound-Blacklisted PM</fullName>
                </value>
                <value>
                    <fullName>Inbound-Demo</fullName>
                </value>
                <value>
                    <fullName>Inbound-Existing Customer</fullName>
                </value>
                <value>
                    <fullName>Inbound-Info Requested</fullName>
                </value>
                <value>
                    <fullName>Inbound-Non-healthcare</fullName>
                </value>
                <value>
                    <fullName>Inbound-Sales Transfer</fullName>
                </value>
                <value>
                    <fullName>Left live message</fullName>
                </value>
                <value>
                    <fullName>Left voicemail</fullName>
                </value>
                <value>
                    <fullName>No answer Busy signal</fullName>
                </value>
                <value>
                    <fullName>Non-healthcare</fullName>
                </value>
                <value>
                    <fullName>Spoke with-</fullName>
                </value>
                <value>
                    <fullName>Set 1-Day Callback</fullName>
                </value>
                <value>
                    <fullName>Set 3-Day Callback</fullName>
                </value>
                <value>
                    <fullName>Set 7-Day Callback</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Follow_Up_Days__c</fullName>
        <label>Follow-Up Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Spoke_With__c</fullName>
        <label>Spoke With</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Task_Field_History__c/Task_Field_History__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Task Field History</label>
</CustomObject>

src.4/objects/Task_History__c.object
<CustomObject>
    <label>Task History</label>
    <nameField>
        <label>Task History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Value__c</fullName>
        <label>New Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Old_Value__c</fullName>
        <label>Old Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_ID__c</fullName>
        <label>Task ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

src.2/classes/Tasks.cls
public class Tasks extends fflib_SObjectDomain 
{
	private Five9_Disposition_Mapping__c[] allMappings;
	private Map<String, Five9_Disposition_Mapping__c> dispositionMap;
	private Map<Id, Contact> contactMap;
	private Task_Field_History__c[] fieldsToTrack;

	public Tasks(Task[] tasks) 
	{
		super(tasks);
		Configuration.disableTriggerCRUDSecurity();
	}

	public class Constructor implements fflib_SObjectDomain.IConstructable
	{
		public fflib_SObjectDomain construct(List<SObject> sObjectList)
		{
			return new Tasks(sObjectList);
		}
	}

	public override void onBeforeInsert()
	{
		fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

		for(Task t : (Task[]) Records) 
    	{
			this.mapFive9Dispositions(t, uow);
    	}

        uow.commitWork();
	}

	public override void onAfterUpdate(Map<Id, SObject> existingRecords)
	{
		fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

		for(Task t : (Task[]) Records) 
    	{
    		Task existingTask = (Task) existingRecords.get(t.Id);

    		this.createHistory(t, existingTask, uow);
    	}

        uow.commitWork();
	}

	public override void onBeforeDelete()
	{
		this.blockTaskDelete();
	}

	public void blockTaskDelete()
	{
		Map<Id, Profile> profileMap = new Map<Id, Profile>([SELECT Id, Name FROM Profile WHERE (Name LIKE '%sales%' OR Name LIKE '%Account Development%') AND Name != 'Sales Administrator']);

		for(Task t : (Task[]) Records) 
		{
			if(!profileMap.isEmpty() && profileMap.containsKey(UserInfo.getProfileId())) 
			{
				t.addError('Insufficient Priviledges to Delete a Task');
			}
		}
	}

	public void createHistory(Task t, Task existingTask, fflib_SObjectUnitOfWork uow)
	{
		if(fieldsToTrack == null) fieldsToTrack = Task_Field_History__c.getAll().values();

		for(Task_Field_History__c field : fieldsToTrack)
		{
			if(t.get(field.Name) != existingTask.get(field.Name))
			{
				Task_History__c th = new Task_History__c(Name = t.Id + String.valueOf(Datetime.now()),
					Field__c = (String) field.Name,
					Old_Value__c = (String) String.valueOf(existingTask.get(field.Name)) == null ? 'null' : (String) String.valueOf(existingTask.get(field.Name)),
					New_Value__c = (String) String.valueOf(t.get(field.Name)) == null ? 'null' : (String) String.valueOf(t.get(field.Name)),
					Task_ID__c = t.Id);

				uow.registerNew(th);
			}
		}
	}

	public void mapFive9Dispositions(Task t, fflib_SObjectUnitOfWork uow)
	{
		if(t.CallDisposition == null) return;
		if(allMappings == null) allMappings = [SELECT 
			Id, Five9_Disposition__c, Activity_Results__c, Activity_Type__c, Spoke_With__c, Active__c, Account_Sales_Status__c, Follow_Up_Days__c 
			FROM Five9_Disposition_Mapping__c WHERE Active__c = true];
		if(dispositionMap == null) dispositionMap = new Map<String, Five9_Disposition_Mapping__c>();
		if(contactMap == null) contactMap = ContactsSelector.newInstance().selectContactsWithAccountsByTask((Task[]) Records);

		if(dispositionMap.isEmpty())
		{
			for(Five9_Disposition_Mapping__c disposition : allMappings)
			{
				dispositionMap.put(disposition.Five9_Disposition__c, disposition);
			}
		}

		if(!dispositionMap.containsKey(t.CallDisposition)) return;

		Five9_Disposition_Mapping__c disposition = dispositionMap.get(t.CallDisposition);
		t.Activity_Type__c = disposition.Activity_Type__c;
		t.Activity_Results__c = disposition.Activity_Results__c;
		t.Talked_To__c = disposition.Spoke_With__c;

		if(disposition.Account_Sales_Status__c != null && contactMap != null && contactMap.containsKey(t.WhoId))
		{
			Account a = new Account();
			a.Id = contactMap.get(t.WhoId).AccountId;
			a.Account_Sales_Status__c = disposition.Account_Sales_Status__c;
			uow.registerDirty(a);
		}

		if(disposition.Follow_Up_Days__c != null)
		{
			Task tNew = t.clone(false);
			tNew.Subject = 'Five9 Follow-up';
			tNew.Status = 'Scheduled';
			tNew.CallDisposition = null;
			tNew.ActivityDate = Date.today().addDays(Integer.valueOf(disposition.Follow_Up_Days__c));
			tNew.Activity_Type__c = 'Outbound Call';
			tNew.Activity_Results__c = 'Future Event';
			tNew.Talked_To__c = null;
			uow.registerNew(tNew);
		}
	}
}