src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account Lookup</description>
        <inlineHelpText>Choose the Account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.1/objects/Addendum__c.object
<CustomObject>
    <description>Represents a change to existing contractual terms</description>
    <label>Addendum</label>
    <nameField>
        <label>Addendum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addenda</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addenda</relationshipLabel>
        <relationshipName>Addenda</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.2/objects/Addendum_Line_Item__c.object
<CustomObject>
    <label>Addendum Line Item</label>
    <nameField>
        <displayFormat>ALI-{000000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addendum Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Addendum__c</fullName>
        <label>Addendum</label>
        <referenceTo>Addendum__c</referenceTo>
        <relationshipLabel>Addendum Line Items</relationshipLabel>
        <relationshipName>Addendum_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Addendum Line Items</relationshipLabel>
        <relationshipName>Addendum_Line_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deferred_Months__c</fullName>
        <label>Deferred Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Defer_Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Defer Billing</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>SR</fullName>
        <active>true</active>
        <label>SR</label>
    </recordTypes>
</CustomObject>

src.3/objects/Addendum_Snippet__c.object
<CustomObject>
    <label>Addendum Snippet</label>
    <nameField>
        <label>Addendum Snippet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addendum Snippets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Snippet_Text__c</fullName>
        <label>Snippet Text</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
</CustomObject>

src.3/objects/Asset.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Notes whether or not the Asset is being billed.</description>
        <inlineHelpText>Notes whether or not the Asset is being billed.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/default/classes/AddendaTest.cls
@isTest
private class AddendaTest {
	
	@testSetup static void testData() {

        Account a = TestUtilities.insertBasicAccount(true);
    }

    @isTest static void activeChangeTest() {

    	Account a = [SELECT Id FROM Account LIMIT 1];
    	Product2 p = [SELECT Id FROM Product2 WHERE Family = 'SR Platform' LIMIT 1];

    	Asset ast = new Asset(Name = 'Test Asset',
    		AccountId = a.Id,
    		Product2Id = p.Id,
    		Active__c = false);
    	insert ast;

    	Addendum__c add = new Addendum__c(Account__c = a.Id,
    		Name = 'Test Addendum');

    	insert add;

    	Addendum_Line_Item__c ali = new Addendum_Line_Item__c(Addendum__c = add.Id,
    		Asset__c = ast.Id);

    	insert ali;

    	Addendum_Snippet__c snip = new Addendum_Snippet__c(Name = 'SR_Defer_Billing__c',
    		Snippet_Text__c = 'test snippet text');

    	insert snip;

    	Test.startTest();

    	ali.Defer_Billing__c = true;
    	ali.Deferred_Months__c = 2;
    	update ali;

    	Test.stopTest();

    }
}