src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account Lookup</description>
        <inlineHelpText>Choose the Account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_Contacts_Parent_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies a dummy account that is used for Lead Contact association.</description>
        <inlineHelpText>Identifies a dummy account that is used for Lead Contact association.</inlineHelpText>
        <label>Lead Contacts Parent Account</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.1/objects/Campaign.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>ADR_Set__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ADR Contact no Set</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>List__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Box should be checked if prospects have not yet shown interest. (ie. Attendee Lists, Partner Member Lists, etc.)</inlineHelpText>
        <label>List</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src.4/objects/Campaign_Influence__c.object
<CustomObject>
    <label>Campaign Influence</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Influence</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Campaign Influence</relationshipLabel>
        <relationshipName>Campaign_Influence</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Associated_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaign_Influence</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campaign_Add_Date__c</fullName>
        <label>Campaign Add Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Campaign_Influence_Type__c</fullName>
        <label>Campaign Influence Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SR</fullName>
                    <default>true</default>
                    <label>SR</label>
                </value>
                <value>
                    <fullName>HG</fullName>
                </value>
                <value>
                    <fullName>LL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Influence</relationshipLabel>
        <relationshipName>Campaign_Influence</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Campaign Influence</relationshipLabel>
        <relationshipName>Campaign_Influence</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_Re_warmed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lead Re-warmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Campaign Influence</relationshipLabel>
        <relationshipName>Campaign_Influence</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Lead_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>New Lead Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Campaign Influence</relationshipLabel>
        <relationshipName>Campaign_Influence</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Orphaned_Date__c</fullName>
        <label>Orphaned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Orphaned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Orphaned</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src.1/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Associated_Opp__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Opp</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contacts (Associated Opp)</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.1/classes/CIRecalculateAcct_Batch.cls
global class CIRecalculateAcct_Batch implements Database.Batchable<sObject> {
	
	Datetime dateFilter = Datetime.now().addHours(-23);
	String query = 'SELECT Id FROM Account';

	global Database.QueryLocator start(Database.BatchableContext BC) {
		
		return Database.getQueryLocator(query);
	}

	global void execute(Database.BatchableContext BC, List<Account> scope) {

      	Campaign_Influence__c[] blankCiType = [SELECT Id,
      	Lead__c,
		Account__c, 
		Opportunity__c, 
		Opportunity__r.AccountId, 
		Contact__c, 
		Contact__r.Associated_Opp__c,
		Contact__r.Lead__c,
		Contact__r.AccountId, 
		Contact__r.Account.Lead_Contacts_Parent_Account__c, 
		Campaign__c, 
		Campaign__r.Type, 
		Campaign__r.List__c, 
		Campaign__r.ADR_Set__c, 
		Campaign__r.StartDate, 
		Campaign_Add_Date__c, 
		New_Lead_Created__c, 
		Lead_Re_warmed__c, 
		Orphaned__c, 
		Orphaned_Date__c, 
		Associated_Rep__c 
		FROM Campaign_Influence__c 
		WHERE Campaign_Influence_Type__c = null
		AND Account__c IN :scope];

		CampaignInfluenceUtilities.setCIType(blankCiType, true);

      	Map<ID, Account> srAccts = new Map<ID, Account> ([SELECT Id,
			(SELECT Id,
				Lead__c,
				Account__c, 
				Opportunity__c, 
				Opportunity__r.AccountId, 
				Contact__c, 
				Contact__r.Associated_Opp__c,
				Contact__r.Lead__c,
				Contact__r.AccountId, 
				Contact__r.Account.Lead_Contacts_Parent_Account__c, 
				Campaign__c, 
				Campaign__r.Type, 
				Campaign__r.List__c, 
				Campaign__r.ADR_Set__c, 
				Campaign__r.StartDate, 
				Campaign_Add_Date__c, 
				New_Lead_Created__c, 
				Lead_Re_warmed__c, 
				Orphaned__c, 
				Orphaned_Date__c, 
				Associated_Rep__c 
				FROM Campaign_Influence__r 
				WHERE Campaign_Influence_Type__c IN ('SR','')
				ORDER BY Campaign_Add_Date__c ASC)
			FROM Account 
			WHERE Lead_Contacts_Parent_Account__c = false 
			AND Id IN :scope]);

		CampaignInfluenceUtilities.calculateNewRewarm(new Map<Id, Lead>(), srAccts);

		Map<ID, Account> hgAccts = new Map<ID, Account> ([SELECT Id,
			(SELECT Id,
				Lead__c,
				Account__c, 
				Opportunity__c, 
				Opportunity__r.AccountId, 
				Contact__c, 
				Contact__r.Associated_Opp__c,
				Contact__r.Lead__c,
				Contact__r.AccountId, 
				Contact__r.Account.Lead_Contacts_Parent_Account__c, 
				Campaign__c, 
				Campaign__r.Type, 
				Campaign__r.List__c, 
				Campaign__r.ADR_Set__c, 
				Campaign__r.StartDate, 
				Campaign_Add_Date__c, 
				New_Lead_Created__c, 
				Lead_Re_warmed__c, 
				Orphaned__c, 
				Orphaned_Date__c, 
				Associated_Rep__c 
				FROM Campaign_Influence__r 
				WHERE Campaign_Influence_Type__c = 'HG'
				ORDER BY Campaign_Add_Date__c ASC)
			FROM Account 
			WHERE Lead_Contacts_Parent_Account__c = false 
			AND Id IN :scope]);

		CampaignInfluenceUtilities.calculateNewRewarm(new Map<Id, Lead>(), hgAccts);

		Map<ID, Account> llAccts = new Map<ID, Account> ([SELECT Id,
			(SELECT Id,
				Lead__c,
				Account__c, 
				Opportunity__c, 
				Opportunity__r.AccountId, 
				Contact__c, 
				Contact__r.Associated_Opp__c,
				Contact__r.Lead__c,
				Contact__r.AccountId, 
				Contact__r.Account.Lead_Contacts_Parent_Account__c, 
				Campaign__c, 
				Campaign__r.Type, 
				Campaign__r.List__c, 
				Campaign__r.ADR_Set__c, 
				Campaign__r.StartDate, 
				Campaign_Add_Date__c, 
				New_Lead_Created__c, 
				Lead_Re_warmed__c, 
				Orphaned__c, 
				Orphaned_Date__c, 
				Associated_Rep__c 
				FROM Campaign_Influence__r 
				WHERE Campaign_Influence_Type__c = 'LL'
				ORDER BY Campaign_Add_Date__c ASC)
			FROM Account 
			WHERE Lead_Contacts_Parent_Account__c = false 
			AND Id IN :scope]);

		CampaignInfluenceUtilities.calculateNewRewarm(new Map<Id, Lead>(), llAccts);
	}
			
	global void finish(Database.BatchableContext BC) {
		
	}

	global void execute(SchedulableContext sc) {
		
		CIRecalculateAcct_Batch batch = new CIRecalculateAcct_Batch();
		Database.executebatch(batch);
	}
}