src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Number_of_Locations__c</fullName>
        <label>Number of Locations</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0-9</fullName>
                </value>
                <value>
                    <fullName>10-49</fullName>
                </value>
                <value>
                    <fullName>50-100</fullName>
                </value>
                <value>
                    <fullName>100+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Providers__c</fullName>
        <label>Number of Providers</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0-10</fullName>
                </value>
                <value>
                    <fullName>11-29</fullName>
                </value>
                <value>
                    <fullName>30-49</fullName>
                </value>
                <value>
                    <fullName>50+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>rrpu__Alert_Message__c</fullName>
        <description>This field is installed by Riptide Pop-up Alerts and is used in conjunction with the Pop-up Alert S-Control.</description>
        <inlineHelpText>If you enter text into this field the text will be displayed in a pop-up message whenever someone views this record.</inlineHelpText>
        <label>Alert Message</label>
        <type>TextArea</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.1/objects/Campaign.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>ADR_Set__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ADR Contact no Set</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src.1/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>CampaignId__c</fullName>
        <description>Populated by HubSpot to create a CampaignMember for the Id specified.</description>
        <label>CampaignId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DistGroup__c</fullName>
        <description>Set by HubSpot and used in Apex to set the matching Distribution Group.</description>
        <label>DistGroup</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distribution Group</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This Distribution Group does not currently available to be used.</errorMessage>
            <filterItems>
                <field>Distribution_Group__c.HasNextUser__c</field>
                <operation>equals</operation>
                <value>1</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Distribution_Group__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Locations__c</fullName>
        <label>Number of Locations</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1-5</fullName>
                </value>
                <value>
                    <fullName>6-24</fullName>
                </value>
                <value>
                    <fullName>25-100</fullName>
                </value>
                <value>
                    <fullName>100+</fullName>
                </value>
                <value>
                    <fullName>1-4</fullName>
                </value>
                <value>
                    <fullName>5-24</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Providers__c</fullName>
        <label>Number of Providers</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1-50</fullName>
                </value>
                <value>
                    <fullName>51-100</fullName>
                </value>
                <value>
                    <fullName>101-300</fullName>
                </value>
                <value>
                    <fullName>300+</fullName>
                </value>
                <value>
                    <fullName>1-20</fullName>
                </value>
                <value>
                    <fullName>21-124</fullName>
                </value>
                <value>
                    <fullName>125+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>rrpu__Alert_Message__c</fullName>
        <description>This field is installed by Riptide Pop-up Alerts and is used in conjunction with the Pop-up Alert S-Control.</description>
        <inlineHelpText>If you enter text into this field the text will be displayed in a pop-up message whenever someone views this record.</inlineHelpText>
        <label>Alert Message</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Contact/fields/Demo_Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Demo_Scheduled_Date__c</fullName>
    <description>When this field is set, a Demo Scheduled task is created at this date/time via Apex.  The task will be owned by the user setting the field and will be reassigned if sent to a Distribution Group.</description>
    <label>Demo Scheduled Date</label>
    <type>DateTime</type>
</CustomField>

src.2/objects/Distribution_Group__c.object
<CustomObject>
    <label>Distribution Group</label>
    <nameField>
        <label>Distribution Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>CampaignId__c</fullName>
        <description>Create a Campaign Influence with this Campaign Id</description>
        <label>CampaignId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

src.1/objects/SR_Default_Values__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SR Default Values</label>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

src.2/classes/Contacts_Test.cls
@isTest
private class Contacts_Test {
	
	@isTest static void test_onBeforeInsert() 
	{		
		sfab_FabricatedSObject cFab = TestUtilities2.newContact();

		Contact con = (Contact) cFab.toSObject();

    	Contact existingCon = (Contact) TestUtilities2.existingContact(cFab).toSObject();  

		Contacts contacts = new Contacts(new List<Contact>{ con });         
	    contacts.onBeforeInsert();			
	}

	@isTest static void test_onAfterInsert() 
	{		
		sfab_FabricatedSObject cFab = TestUtilities2.newContact();

		Contact con = (Contact) cFab.toSObject();

    	Contact existingCon = (Contact) TestUtilities2.existingContact(cFab).toSObject();  

		Contacts contacts = new Contacts(new List<Contact>{ con });         
	    contacts.onAfterInsert();			
	}

	@isTest static void test_onBeforeUpdate() 
	{		
		sfab_FabricatedSObject cFab = TestUtilities2.newContact();

		Contact con = (Contact) cFab.toSObject();

    	Contact existingCon = (Contact) TestUtilities2.existingContact(cFab).toSObject();  

		Contacts contacts = new Contacts(new List<Contact>{ con });         
	    contacts.onBeforeUpdate(new Map<Id, SObject>{con.Id =>  cFab.toSObject()});			
	}

    @isTest static void test_createCampaignInfluence()
    {
        Account ac = (Account) TestUtilities2.newAccount().toSObject();

        Campaign camp = (Campaign) TestUtilities2.newCampaign().toSObject();

        User user = (User) TestUtilities2.newUser().toSObject();

        User user2 = (User) TestUtilities2.newUser().toSObject();

    	sfab_FabricatedSObject cFab = TestUtilities2.newContact()
    		.setField(Contact.CampaignId__c, camp.Id)
       		.setField(Contact.AccountId, ac.Id);

		Contact con = (Contact) cFab.toSObject();

    	Contact existingCon = (Contact) TestUtilities2.existingContact(cFab)
    		.setField(Contact.CampaignId__c, '2')
    		.toSObject();

    	Contacts contacts = new Contacts(new List<Contact>{ con });         
	    contacts.createCampaignInfluence(con, existingCon);
	    
	    System.assertEquals(1, contacts.createCI.size()); 
	    System.assert(contacts.createCI.contains(con.Id + '::' + con.CampaignId__c + ':' + UserInfo.getUserId()));  
    }   

    @isTest static void test_createNewAccount()
    {
    	fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

      	Contact con = (Contact) TestUtilities2.newContact()
    		.setField(Contact.FirstName, 'FirstName')
    		.setField(Contact.LastName, 'LastName')
    		.setField(Contact.MailingStreet, 'MailingStreet')
    		.setField(Contact.MailingCity, 'Utah')
    		.setField(Contact.Number_of_Locations__c, 2)
    		.setField(Contact.Number_of_Providers__c, 5)
       		.toSObject();
    	
    	Contacts contacts = new Contacts(new List<Contact>{ con });         
	    contacts.createNewAccount(con, uow);
	    List<Account> acResult = (List<Account>)(uow.m_newListByType.get('Account'));
	    
	    System.assertEquals(1, uow.m_newListByType.get('Account').size()); 
	    System.assertEquals('Account Auto-Created', acResult[0].Description);
	    System.assertEquals('Dental', acResult[0].Industry);
	    System.assertEquals(con.Number_of_Locations__c, acResult[0].Number_of_Locations__c);
	    System.assertEquals(con.Number_of_Providers__c, acResult[0].Number_of_Providers__c);
	    System.assertEquals(con.FirstName + ' ' + con.LastName, acResult[0].Name);
	    System.assertEquals(SRUtilities.getRecordTypeMap('Account').get('Account').getRecordTypeId(), acResult[0].RecordTypeId); 
    }  

    @isTest static void test_createDemoTask()
    {
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        Account ac = (Account) TestUtilities2.newAccount().toSObject();

        Contact c = (Contact) TestUtilities2.newContact()
            .setField(Contact.AccountId, ac.Id)
            .setField(Contact.Demo_Scheduled_Date__c, Datetime.now().addDays(5))
            .toSObject();
        
        Contacts contacts = new Contacts(new List<Contact>{ c });         
        contacts.createDemoTask(c, null, uow);
        List<Task> taskResults = (List<Task>)(uow.m_newListByType.get('Task'));
        
        System.assertEquals(1, taskResults.size()); 
        System.assertEquals(true, taskResults[0].ADR_Set__c);
        System.assertEquals(Date.valueOf(c.Demo_Scheduled_Date__c), taskResults[0].ActivityDate);
        System.assertEquals('Phone Demo', taskResults[0].Activity_Type__c);
        System.assertEquals('Future Event', taskResults[0].Activity_Results__c);
        System.assertEquals('Scheduled', taskResults[0].Status);
        System.assertEquals(c.Demo_Scheduled_Date__c, taskResults[0].Due_Time__c);
        System.assertEquals(c.Id, taskResults[0].WhoId);
        System.assertEquals(c.AccountId, taskResults[0].WhatId);
    }  

    @isTest static void test_processDistributionGroup()
    {
    	Distribution_Group__c distGroup = (Distribution_Group__c) TestUtilities2.newDistributionGroup().toSObject();

    	Distribution_Group__c distGroup2 = (Distribution_Group__c) TestUtilities2.newDistributionGroup().toSObject();

      	sfab_FabricatedSObject cFab = TestUtilities2.newContact()
    		.setField(Contact.DistGroup__c, 'DistGroup1')
       		.setField(Contact.Distribution_Group__c, distGroup.Id);

		Contact con = (Contact) cFab.toSObject();

    	Contact existingCon = (Contact) TestUtilities2.existingContact(cFab)
    		.setField(Contact.DistGroup__c, 'DistGroup2')
    		.setField(Contact.Distribution_Group__c, distGroup2.Id)
    		.toSObject();
    	
    	Contacts contacts = new Contacts(new List<Contact>{ con });         
	    contacts.processDistributionGroup(con, existingCon);
	     
	    System.assertEquals(1, contacts.contactsDistGroup.size()); 
	    System.assert(contacts.contactsDistGroup.contains(con.Id + '::' + con.Distribution_Group__c + ':' + UserInfo.getUserId()));	   
    }  

    @isTest static void test_validateCountryByAreaCode()
    {
    	Distribution_Group__c distGroup = (Distribution_Group__c) TestUtilities2.newDistributionGroup().toSObject();

    	Distribution_Group__c distGroup2 = (Distribution_Group__c) TestUtilities2.newDistributionGroup().toSObject();

      	sfab_FabricatedSObject cFab = TestUtilities2.newContact()
    		.setField(Contact.Phone, '1112223333')
       		.setField(Contact.MailingCountryCode, 'Code1');

		Contact con = (Contact) cFab.toSObject();

    	Contact existingCon = (Contact) TestUtilities2.existingContact(cFab)
    		.setField(Contact.Phone, '4445556666')
    		.setField(Contact.MailingCountryCode, 'Code2')
    		.toSObject();
    	
    	Contacts contacts = new Contacts(new List<Contact>{ con });         
	    contacts.validateCountryByAreaCode(con, existingCon);
	     
	    System.assertEquals(null, con.rrpu__Alert_Message__c); 	    
    }  

    @isTest static void test_validateContactOwnerChange()
    {    	
    	User user = (User) TestUtilities2.newUser().toSObject();

        User user2 = (User) TestUtilities2.newUser().toSObject();

      	sfab_FabricatedSObject cFab = TestUtilities2.newContact()
    		.setField(Contact.OwnerId, user.Id)
       		.setField(Contact.MailingCountryCode, 'Code1');

		Contact con = (Contact) cFab.toSObject();

    	Contact existingCon = (Contact) TestUtilities2.existingContact(cFab)
    		.setField(Contact.OwnerId, user2.Id)
    		.setField(Contact.MailingCountryCode, 'Code2')
    		.toSObject();

    	insert new SR_Default_Values__c(Name = 'noStealingProfiles',
            Description__c = 'noStealingProfiles',
            Value__c = '00ei0000001247zAAA');

    	insert new SR_Default_Values__c(Name = 'jennyPoolUserId',
            Description__c = 'jennyPoolUserId',
            Value__c = con.OwnerId);

    	insert new SR_Default_Values__c(Name = 'contactChangeOwnerErrorMessage',
			Description__c = 'contactChangeOwnerErrorMessage',
	        Value__c = 'Adderror Message');  
    	
    	Contacts contacts = new Contacts(new List<Contact>{ con });         
	    contacts.validateContactOwnerChange(con, existingCon);	     	   
    }    	
}