src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Account_Sales_Status__c</fullName>
        <label>Account Sales Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Contacted</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Bogus</fullName>
                </value>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Do_Not_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Do Not Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_HG_Scorecard_Date__c</fullName>
        <label>Last HG Scorecard Date</label>
        <type>DateTime</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.1/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account_Phone__c</fullName>
        <description>Set via Parent/Child Mapping in Apex</description>
        <label>Account Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Account_Sales_Status__c</fullName>
        <description>Apex mapping via Parent/Child Mappings</description>
        <label>Account Sales Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Contacted</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Bogus</fullName>
                </value>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Do_Not_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Apex mappings via Parent/Child Mappings</description>
        <inlineHelpText>This is the Account DNC field</inlineHelpText>
        <label>Do Not Contact</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src.3/objects/Parent_Child_Mapping__c.object
<CustomObject>
    <label>Parent Child Mapping</label>
    <nameField>
        <displayFormat>PCM-{0000}</displayFormat>
        <label>Parent Child Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parent Child Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Child_Field_Name__c</fullName>
        <label>Child Field Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Child_Object__c</fullName>
        <label>Child Object</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Object_Names</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Field_Name__c</fullName>
        <label>Parent Field Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Object__c</fullName>
        <label>Parent Object</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Object_Names</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

src.2/classes/AccountsService_Test.cls
/**
 * Created by mschetselaar on 10/10/2018.
 */

@IsTest
private class AccountsService_Test
{
    @TestSetup
    static void testSetup()
    {
        TestUtilities.newInit();
    }
    
    @IsTest
    static void test_syncRecordOwners()
    {
        Map<Id,Id> accountIdToOwnerId = new Map<Id,Id>();
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        Account acct = [SELECT Id, OwnerId FROM Account LIMIT 1];
        User user = [SELECT Id FROM User WHERE IsActive = TRUE AND Id != :acct.OwnerId LIMIT 1];
        accountIdToOwnerId.put(acct.Id,user.Id);
        
        Test.startTest();
            AccountsService.syncRecordOwners(accountIdToOwnerId, uow);
            uow.commitWork();
        Test.stopTest();
        
        Account updateAccount = [SELECT Id, OwnerId FROM Account LIMIT 1];
        
        System.assert(updateAccount != null);
        System.assertEquals(user.Id,updateAccount.OwnerId);
    }
    
    @IsTest
    static void test_processParentChildUpdates()
    {
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        Set<Id> ids = new Set<Id>();
        List<Account> accts = [SELECT Id, Account_Sales_Status__c, Do_Not_Contact__c, Phone FROM Account];
        List<Contact> contacts = new List<Contact>();
        for(Account a : accts)
        {
            ids.add(a.Id);
            a.Account_Sales_Status__c = 'Bogus';
            a.Do_Not_Contact__c = true;
            a.Phone = '8013317129';
            contacts.add(new Contact(FirstName = 'Test', LastName = 'Testor', AccountId = a.Id));
        }
        insert contacts;
        update accts;
        
        List<Parent_Child_Mapping__c> mappings = new List<Parent_Child_Mapping__c>();
        mappings.add(new Parent_Child_Mapping__c(Active__c = true, Parent_Object__c = 'Account', Child_Object__c = 'Contact', Parent_Field_Name__c = 'Account_Sales_Status__c', Child_Field_Name__c = 'Account_Sales_Status__c'));
        mappings.add(new Parent_Child_Mapping__c(Active__c = true, Parent_Object__c = 'Account', Child_Object__c = 'Contact', Parent_Field_Name__c = 'Do_Not_Contact__c', Child_Field_Name__c = 'Do_Not_Contact__c'));
        mappings.add(new Parent_Child_Mapping__c(Active__c = true, Parent_Object__c = 'Account', Child_Object__c = 'Contact', Parent_Field_Name__c = 'Phone', Child_Field_Name__c = 'Account_Phone__c'));
        
        Test.startTest();
            AccountsService.processParentChildUpdates(ids, accts, mappings, uow);
            uow.commitWork();
        Test.stopTest();
        
        List<Contact> updatedContacts = [SELECT Id, Account_Sales_Status__c, Do_Not_Contact__c, Account_Phone__c FROM Contact];
        
        System.assert(updatedContacts.size()>0);
        for(Contact c : updatedContacts)
        {
            System.assertEquals('Bogus', c.Account_Sales_Status__c);
            System.assertEquals(true, c.Do_Not_Contact__c);
            System.assertEquals('8013317129', c.Account_Phone__c);
        }
    }
    
    @IsTest
    static void test_processNewScorecards()
    {
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        Account acct = [SELECT Id, Last_HG_Scorecard_Date__c FROM Account LIMIT 1];
        acct.Last_HG_Scorecard_Date__c = Datetime.now().addDays(-10);
        update acct;
        
        Set<Id> ids = new Set<Id>();
        ids.add(acct.Id);
        
        Test.startTest();
            AccountsService.processNewScorecards(ids, uow);
            uow.commitWork();
        Test.stopTest();
        
        Account updatedAccount = [SELECT Id, Last_HG_Scorecard_Date__c FROM Account LIMIT 1];
        System.assert(updatedAccount.Last_HG_Scorecard_Date__c > Datetime.now().addDays(-1));
    }
}