src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Micro_Vertical__c</fullName>
        <label>Micro Vertical</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Sub_Vertical__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Anesthesiology</fullName>
                </value>
                <value>
                    <fullName>Audiology</fullName>
                </value>
                <value>
                    <fullName>Breast</fullName>
                </value>
                <value>
                    <fullName>Cardiology</fullName>
                </value>
                <value>
                    <fullName>Cardiovascular</fullName>
                </value>
                <value>
                    <fullName>Cosmetic Dermatology</fullName>
                </value>
                <value>
                    <fullName>Diabeties Specialist</fullName>
                </value>
                <value>
                    <fullName>Emergency Medicine</fullName>
                </value>
                <value>
                    <fullName>Gynecologic</fullName>
                </value>
                <value>
                    <fullName>Hematology</fullName>
                </value>
                <value>
                    <fullName>Holistic, Integrative, or Naturopathic Medicine</fullName>
                </value>
                <value>
                    <fullName>Hospice &amp; Palliative Medicine</fullName>
                </value>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Medical Dermatology</fullName>
                </value>
                <value>
                    <fullName>Multi-specialty Group</fullName>
                </value>
                <value>
                    <fullName>Nephrology</fullName>
                </value>
                <value>
                    <fullName>Pathology</fullName>
                </value>
                <value>
                    <fullName>Pediatric</fullName>
                </value>
                <value>
                    <fullName>Please Specify --&gt;</fullName>
                </value>
                <value>
                    <fullName>Pulmonary Medicine</fullName>
                </value>
                <value>
                    <fullName>Radiation</fullName>
                </value>
                <value>
                    <fullName>Reproductive Medicine or Fertility Specialist</fullName>
                </value>
                <value>
                    <fullName>Rheumatology</fullName>
                </value>
                <value>
                    <fullName>Skin</fullName>
                </value>
                <value>
                    <fullName>Sleep Disorders</fullName>
                </value>
                <value>
                    <fullName>Thoracic</fullName>
                </value>
                <value>
                    <fullName>Vascular Surgery (veins)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Practice_Software__c</fullName>
        <label>Practice Software</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>rrpu__Alert_Message__c</fullName>
        <description>This field is installed by Riptide Pop-up Alerts and is used in conjunction with the Pop-up Alert S-Control.</description>
        <inlineHelpText>If you enter text into this field the text will be displayed in a pop-up message whenever someone views this record.</inlineHelpText>
        <label>Alert Message</label>
        <type>TextArea</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Affiliate</fullName>
        <active>true</active>
        <description>Any individual, doctor, speaker/consultant, SR customer or non-SR customer who promotes Solutionreach and is signed up through our affiliate program.</description>
        <label>Affiliate/KOL</label>
    </recordTypes>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <label>PM/EHR Partner</label>
    </recordTypes>
</CustomObject>

src.1/objects/Lead.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>Lead_Type__c</fullName>
        <label>Lead Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Enterprise</fullName>
                    <color>#0B6FCE</color>
                    <label>Enterprise</label>
                </value>
                <value>
                    <fullName>Practice</fullName>
                    <color>#78C953</color>
                    <default>true</default>
                    <label>Practice</label>
                </value>
                <value>
                    <fullName>Group Practice</fullName>
                    <color>#E27001</color>
                    <label>Group Practice</label>
                </value>
                <value>
                    <fullName>Partner</fullName>
                    <color>#A845DC</color>
                    <label>Partner</label>
                </value>
                <value>
                    <fullName>Referral Partner</fullName>
                    <color>#F3D904</color>
                    <label>Referral Partner</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Micro_Vertical__c</fullName>
        <label>Micro Vertical</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Sub_industry__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Anesthesiology</fullName>
                </value>
                <value>
                    <fullName>Audiology</fullName>
                </value>
                <value>
                    <fullName>Breast</fullName>
                </value>
                <value>
                    <fullName>Cardiology</fullName>
                </value>
                <value>
                    <fullName>Cardiovascular</fullName>
                </value>
                <value>
                    <fullName>Cosmetic Dermatology</fullName>
                </value>
                <value>
                    <fullName>Diabeties Specialist</fullName>
                </value>
                <value>
                    <fullName>Emergency Medicine</fullName>
                </value>
                <value>
                    <fullName>Gynecologic</fullName>
                </value>
                <value>
                    <fullName>Hematology</fullName>
                </value>
                <value>
                    <fullName>Holistic, Integrative, or Naturopathic Medicine</fullName>
                </value>
                <value>
                    <fullName>Hospice &amp; Palliative Medicine</fullName>
                </value>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Medical Dermatology</fullName>
                </value>
                <value>
                    <fullName>Multi-specialty Group</fullName>
                </value>
                <value>
                    <fullName>Nephrology</fullName>
                </value>
                <value>
                    <fullName>Pathology</fullName>
                </value>
                <value>
                    <fullName>Pediatric</fullName>
                </value>
                <value>
                    <fullName>Pulmonary Medicine</fullName>
                </value>
                <value>
                    <fullName>Radiation</fullName>
                </value>
                <value>
                    <fullName>Reproductive Medicine or Fertility Specialist</fullName>
                </value>
                <value>
                    <fullName>Rheumatology</fullName>
                </value>
                <value>
                    <fullName>Skin</fullName>
                </value>
                <value>
                    <fullName>Sleep Disorders</fullName>
                </value>
                <value>
                    <fullName>Thoracic</fullName>
                </value>
                <value>
                    <fullName>Vascular Surgery (veins)</fullName>
                </value>
                <value>
                    <fullName>Other, Please Specify --&gt;</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Practice_Software__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Practice Software</label>
        <referenceTo>Management_System__c</referenceTo>
        <relationshipLabel>Leads (Management System)</relationshipLabel>
        <relationshipName>Leads_Practice_Software</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>rrpu__Alert_Message__c</fullName>
        <description>This field is installed by Riptide Pop-up Alerts and is used in conjunction with the Pop-up Alert S-Control.</description>
        <inlineHelpText>If you enter text into this field the text will be displayed in a pop-up message whenever someone views this record.</inlineHelpText>
        <label>Alert Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sub_industry__c</fullName>
        <label>Sub-Vertical</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Dermatology</fullName>
                </value>
                <value>
                    <fullName>Ophthalmology</fullName>
                </value>
                <value>
                    <fullName>Cosmetic Surgery</fullName>
                </value>
                <value>
                    <fullName>Family Medicine or General Physician</fullName>
                </value>
                <value>
                    <fullName>Pediatrics</fullName>
                </value>
                <value>
                    <fullName>OB/GYN or Womens Health</fullName>
                </value>
                <value>
                    <fullName>Allergy &amp; Immunology</fullName>
                </value>
                <value>
                    <fullName>ENT-Otolaryngology</fullName>
                </value>
                <value>
                    <fullName>Gastroenterology</fullName>
                </value>
                <value>
                    <fullName>Orthopedics</fullName>
                </value>
                <value>
                    <fullName>Bariatric, Metabolic and Weight Health</fullName>
                </value>
                <value>
                    <fullName>Endocrinology</fullName>
                </value>
                <value>
                    <fullName>Geriatric Medicine</fullName>
                </value>
                <value>
                    <fullName>Heart and Vascular</fullName>
                </value>
                <value>
                    <fullName>HIV/Infectious Disease</fullName>
                </value>
                <value>
                    <fullName>Internal Medicine</fullName>
                </value>
                <value>
                    <fullName>Medical Spa or Aesthetic Medicine</fullName>
                </value>
                <value>
                    <fullName>Neurology</fullName>
                </value>
                <value>
                    <fullName>General Surgery</fullName>
                </value>
                <value>
                    <fullName>Oncology</fullName>
                </value>
                <value>
                    <fullName>Pain Management or Physical Medicine or Physiatry</fullName>
                </value>
                <value>
                    <fullName>Podiatry</fullName>
                </value>
                <value>
                    <fullName>Psychiatry or Mental Health or Substance Rehabilitation</fullName>
                </value>
                <value>
                    <fullName>Radiology or Imaging</fullName>
                </value>
                <value>
                    <fullName>Urology</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>General Dentistry</fullName>
                </value>
                <value>
                    <fullName>Orthodontistry</fullName>
                </value>
                <value>
                    <fullName>Endodontistry</fullName>
                </value>
                <value>
                    <fullName>Pedodontistry</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>rrpu__Alert_Message__c</fullName>
        <description>This field is installed by Riptide Pop-up Alerts and is used in conjunction with the Pop-up Alert S-Control.</description>
        <inlineHelpText>If you enter text into this field the text will be displayed in a pop-up message whenever someone views this record.</inlineHelpText>
        <label>Alert Message</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

src.2/classes/Leads.cls
public class Leads
{	
	/*public Leads(Lead[] leads) 
	{
		super(leads);	
	}

	public class Constructor implements fflib_SObjectDomain.IConstructable
	{
		public fflib_SObjectDomain construct(List<SObject> sObjectList)
		{
			return new Leads(sObjectList);
		}
	}

	public override void onValidate(Map<Id, SObject> existingRecords)
	{
		//if(FlowControl.isLeadConvert) this.validateLeadConverts();
	}

	public override void onBeforeInsert()
	{
		this.validateCountryByAreaCode();
	}

	public override void onBeforeUpdate(Map<Id, SObject> existingRecords)
	{
		this.validateCountryByAreaCode();
	}

	public override void onAfterUpdate(Map<Id, SObject> existingRecords)
	{
		if(FlowControl.isLeadConvert) this.leadConvert();
	}

	public void validateCountryByAreaCode()
	{
		AreaCodes areaCodes = new AreaCodes();
		String msg = 'The phone area code does not belong to the selected country. Please confirm that this is correct.';

		for(Lead l : (Lead[]) Records)
		{
			Boolean requiresValidation = areaCodes.validateCountryByAreaCode(l.Phone, l.CountryCode);

			if(requiresValidation)
			{
				l.rrpu__Alert_Message__c = l.rrpu__Alert_Message__c != null && !l.rrpu__Alert_Message__c.contains(msg) ? 
					l.rrpu__Alert_Message__c + '\n' + msg : 
					l.rrpu__Alert_Message__c == null ?
						msg : l.rrpu__Alert_Message__c;
			}
			else
			{
				l.rrpu__Alert_Message__c = l.rrpu__Alert_Message__c != null && l.rrpu__Alert_Message__c.contains(msg) ? 
					l.rrpu__Alert_Message__c.replace(msg,'') : l.rrpu__Alert_Message__c;
			}
		}
	}

	public void validateLeadConverts()
	{
		for(Lead l : (Lead[]) Records)
		{
			String errors = validateLeadConvert(l, ', ');

			if(errors != null) l.addError('The Lead isn\'t ready to convert.  Please go back and enter the following: ' + errors);
		}
	}

	public static String validateLeadConvert(Lead l, String joinWith)
	{
		String[] errors = new List<String>();

		if(l.Phone == null) errors.add('Phone');         
        if(l.Lead_Type__c != 'Referral Partner' && l.Practice_Software__c == null) errors.add('Practice Software');
        if(l.Company == null) errors.add('Company');
        if(l.FirstName == null) errors.add('FirstName');
        if(l.LastName == null) errors.add('LastName');
        if(l.Email == null) errors.add('Email');
        if(l.Industry == null) errors.add('Vertical');
        if(l.Sub_Industry__c == null) errors.add('Sub-Vertical');
        if(l.LeadSource == null) errors.add('LeadSource');
        if((l.Sub_Industry__c ==  'Dermatology' || 
            l.Sub_Industry__c == 'Heart and Vascular' || 
            l.Sub_Industry__c == 'Oncology' || 
            l.Sub_Industry__c == 'Other' ) && 
        	(l.Micro_Vertical__c == '' || l.Micro_Vertical__c == null )) errors.add('Micro Vertical');
                        
        if(errors.size() >0) 
        {
        	return String.join(errors, joinWith);
        }
        else
        {
        	return null;
        }
	}

	public void leadConvert()
	{
		fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
		Set<Id> acctIds = new Set<Id>();
		Set<Id> oppIds = new Set<Id>();
		Set<Id> contactIds = new Set<Id>();
		Map<Id,AccountLeadConvert> accountLeadConvertMap = new Map<Id,AccountLeadConvert>();
		Map<Id,OpportunityLeadConvert> opportunityLeadConvertMap = new Map<Id,OpportunityLeadConvert>();
		Map<Id,ContactLeadConvert> contactLeadConvertMap = new Map<Id,ContactLeadConvert>();
		Map<String,String> acctRecordTypeName = new Map<String,String>{
			'Practice'=>'Account',
			'Group Practice'=>'Account',
			'Enterprise'=>'Major Account',
			'Partner'=>'Partner',
			'Referral Partner'=>'Affiliate/KOL' };
		Map<String,String> oppRecordTypeName = new Map<String,String>{
			'Practice'=>'New Practice Business',
			'Group Practice'=>'New Practice Business',
			'Enterprise'=>'Enterprise New Business',
			'Partner'=>'New Practice Business',
			'Referral Partner'=>'New Practice Business' };

		for(Lead l : (Lead[]) Records)
		{
			acctIds.add(l.ConvertedAccountId);
			accountLeadConvertMap.put(l.ConvertedAccountId, new AccountLeadConvert(SRUtilities.getRecordTypeId('Account',acctRecordTypeName.get(l.Lead_Type__c)), l.ConvertedContactId));
			oppIds.add(l.ConvertedOpportunityId);
			opportunityLeadConvertMap.put(l.ConvertedOpportunityId, new OpportunityLeadConvert(SRUtilities.getRecordTypeId('Opportunity', oppRecordTypeName.get(l.Lead_Type__c)), l.ConvertedContactId));
			contactIds.add(l.ConvertedContactId);
			contactLeadConvertMap.put(l.ConvertedContactId, new ContactLeadConvert(l.ConvertedOpportunityId));
		}

		//LeadsService.reParentOnConversion(new Map<Id, SObject>(Records).keySet(), uow);
		//AccountsService.processAccountLeadConverts(acctIds, accountLeadConvertMap, uow);
		//OpportunitiesService.processOpportunityLeadConverts(oppIds, opportunityLeadConvertMap, uow);
		//ContactsService.processContactLeadConverts(contactIds, contactLeadConvertMap, uow);
		uow.commitWork();
	}

	public class AccountLeadConvert
	{
		public Id recordTypeId;
		public Id officeContactId;

		public AccountLeadConvert(Id recordTypeId, Id officeContactId)
		{
			this.recordTypeId = recordTypeId;
			this.officeContactId = officeContactId;
		}
	}

	public class OpportunityLeadConvert
	{
		public Id recordTypeId;
		public Id billingContactId;

		public OpportunityLeadConvert(Id recordTypeId, Id billingContactId)
		{
			this.recordTypeId = recordTypeId;
			this.billingContactId = billingContactId;
		}
	}

	public class ContactLeadConvert
	{
		public Id convertedOppId;

		public ContactLeadConvert(Id convertedOppId)
		{
			this.convertedOppId = convertedOppId;
		}
	}*/
}