src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Subscriber_ID__c</fullName>
        <description>The subscriber ID from App Admin</description>
        <label>Subscriber ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.1/objects/Addendum__c.object
<CustomObject>
    <description>Represents a change to existing contractual terms</description>
    <label>Addendum</label>
    <nameField>
        <label>Addendum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addenda</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addenda</relationshipLabel>
        <relationshipName>Addenda</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Addendum_Signer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Addendum Signer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Addenda</relationshipLabel>
        <relationshipName>Addenda</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Addenda</relationshipLabel>
        <relationshipName>Addenda</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;New&quot;</defaultValue>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Needs Accounting Data</fullName>
                </value>
                <value>
                    <fullName>Accounting Data Received</fullName>
                </value>
                <value>
                    <fullName>Ready For Processing</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Signature Requested</fullName>
                </value>
                <value>
                    <fullName>Signature Expired</fullName>
                </value>
                <value>
                    <fullName>Signature Declined</fullName>
                </value>
                <value>
                    <fullName>Signature Received</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscriber_ID__c</fullName>
        <formula>Account__r.Subscriber_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subscriber ID</label>
        <type>Text</type>
    </fields>
</CustomObject>

src.3/objects/Asset.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Most_Recent_Pricebook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Most Recent Pricebook</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_Contract_Signed_Date__c</fullName>
        <label>Original Contract Signed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related Provider record for Healthgrades Assets</description>
        <inlineHelpText>The related Provider record for Healthgrades Assets</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscriber_ID__c</fullName>
        <formula>Case(Account.Subscriber_ID__c,&quot;&quot;,&quot;&quot;,Account.Subscriber_ID__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subscriber ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

src.4/objects/Case.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscriber_ID__c</fullName>
        <description>This was created so we can view the Subscriber ID from a List View</description>
        <formula>Account.Subscriber_ID__c</formula>
        <inlineHelpText>This is the Subscriber ID of the Account</inlineHelpText>
        <label>Subscriber ID</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Activation</fullName>
        <active>true</active>
        <businessProcess>Activation</businessProcess>
        <description>This is used to track and document the activation process of an account</description>
        <label>Activation</label>
    </recordTypes>
    <recordTypes>
        <fullName>Support</fullName>
        <active>true</active>
        <businessProcess>Support</businessProcess>
        <description>The main case type for Support</description>
        <label>Support</label>
    </recordTypes>
</CustomObject>

src.1/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Ambassador__Short_Code__c</fullName>
        <label>Referring Short Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Ambassador_Commission_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set via Apex after successful API call</description>
        <label>Ambassador Commission Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ambassador_Commission_Paid__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set via Apex after successful API call</description>
        <label>Ambassador Commission Paid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ambassador__Short_Code__c</fullName>
        <label>Referring Short Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Monthly_Revenue__c</fullName>
        <label>Monthly Revenue</label>
        <summarizedField>OpportunityLineItem.Total_Monthly_Revenue__c</summarizedField>
        <summaryFilterItems>
            <field>OpportunityLineItem.Is_Monthly__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the related Provider record</description>
        <inlineHelpText>Link to the related Provider record</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Signed_Date__c</fullName>
        <label>Contract Signed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Referred_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the Contact that was referred by an Ambassador</description>
        <label>Referred Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Referred Contact)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SR_Monthly_Revenue__c</fullName>
        <label>SR Monthly Revenue</label>
        <summarizedField>OpportunityLineItem.SR_Monthly_Revenue__c</summarizedField>
        <summaryFilterItems>
            <field>OpportunityLineItem.Is_Monthly__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Actively working</fullName>
                </value>
                <value>
                    <fullName>Dispute Resolution</fullName>
                </value>
                <value>
                    <fullName>Pending Cancel</fullName>
                </value>
                <value>
                    <fullName>Pending Save</fullName>
                </value>
                <value>
                    <fullName>Future Cancel</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscriber_ID__c</fullName>
        <formula>Case(Account.Subscriber_ID__c,&quot;&quot;,&quot;&quot;,Account.Subscriber_ID__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subscriber ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Healthgrades</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <description>For selling Healthgrades Premium Profiles</description>
        <label>Healthgrades</label>
    </recordTypes>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Addendum__c.field-meta.xml
<CustomField>
    <fullName>Addendum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Addendum</label>
    <referenceTo>Addendum__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

src.3/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related Provider for the Healthgrades Premium Profile</description>
        <inlineHelpText>The related Provider for the Healthgrades Premium Profile</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SR_Monthly_Revenue__c</fullName>
        <label>SR Monthly Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <formula>IF( Is_Monthly__c ,
IF( TEXT( Trial__c ) = &quot;&quot; ,
 null ,
 RecurSoft__Contract_Term_Start_Date_New__c + VALUE( TEXT( Trial__c ))) ,
null )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Provider__c/Provider__c.object-meta.xml
<CustomObject>
    <description>Used to store information about individual Providers within a Practice.  The Provider information is used for Healthgrades Premium members.</description>
    <label>Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Provider__c/fields/Healthgrades_ID__c.field-meta.xml
<CustomField>
    <fullName>Healthgrades_ID__c</fullName>
    <description>The individual Provider&#39;s unique Healthgrades identifier.</description>
    <externalId>true</externalId>
    <label>Healthgrades ID</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src.1/objects/SR_Default_Values__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SR Default Values</label>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

src.1/classes/OpportunitiesService.cls
public class OpportunitiesService 
{
    public static void createAmbassadorCommission(Set<Id> ids, fflib_SObjectUnitOfWork uow)
    {
        Opportunity[] opps = OpportunitiesSelector.newInstance().selectByIdWithAmbassadorContacts(ids);
        
        for(Opportunity o : opps)
        {
            JSONGenerator gen = JSON.createGenerator(true);    
            gen.writeStartObject();      
            gen.writeStringField('email', o.Referred_Contact__r.Email);
            gen.writeStringField('first_name', o.Referred_Contact__r.FirstName);
            gen.writeStringField('last_name', o.Referred_Contact__r.LastName);
            gen.writeNumberField('campaign_uid', 33710);
            gen.writeStringField('transaction_uid', o.Id);
            gen.writeStringField('short_code', o.Referred_Contact__r.Ambassador__Short_Code__c); 
            gen.writeStringField('auto_create', '1');
            gen.writeStringField('email_new_ambassador', '0');
            gen.writeStringField('add_to_group_id', '1');
            gen.writeEndObject();    
            String jsonString = gen.getAsString();
            
            Http http = new Http();
            HTTPResponse response = new HTTPResponse();
            HttpRequest req = new HttpRequest();            
            req.setEndpoint('https://getambassador.com/api/v2/solutionreach/03dae48d3d78060be224d6ff48c5d447/json/event/record/');
            req.setHeader('Content-Type', 'application/json');
            req.setMethod('POST');
            req.setBody(jsonString);
            req.setTimeout(12000);

            response = http.send(req);
            
            if(String.valueOf(response.getStatusCode()) == '200')
            {
                o.Ambassador_Commission_Created__c = true;
                uow.registerDirty(o);
            }            
        }          
    }

    public static void completeAmbassadorCommission(Set<Id> ids, fflib_SObjectUnitOfWork uow)
    {
        Opportunity[] opps = OpportunitiesSelector.newInstance().selectByIdWithAmbassadorContacts(ids);
        
        for(Opportunity o : opps)
        {
            JSONGenerator gen = JSON.createGenerator(true);    
            gen.writeStartObject();      
            gen.writeStringField('is_approved', '1');
            gen.writeStringField('transaction_uid', o.Id);
            gen.writeEndObject();    
            String jsonString = gen.getAsString();
            
            Http http = new Http();
            HTTPResponse response = new HTTPResponse();
            HttpRequest req = new HttpRequest();            
            req.setEndpoint('https://getambassador.com/api/v2/solutionreach/03dae48d3d78060be224d6ff48c5d447/json/commission/update/');
            req.setHeader('Content-Type', 'application/json');
            req.setMethod('POST');
            req.setBody(jsonString);
            req.setTimeout(12000);

            response = http.send(req);
            
            if(String.valueOf(response.getStatusCode()) == '200')
            {
                o.Ambassador_Commission_Paid__c = true;
                uow.registerDirty(o);
            }            
        }           
    }

    public static void addRevenueToADRSetTask(Set<Id> ids, fflib_SObjectUnitOfWork uow)
    {
        Opportunity[] opps = OpportunitiesSelector.newInstance().selectByIdWithAccountAndProducts(ids);
        Map<Id, Task> accountToTaskMap = TasksSelector.newInstance().selectByOpportunityAccountId(opps);

        for(Opportunity o : opps)
        {
            if(!accountToTaskMap.containsKey(o.AccountId)) continue;
            addRevenueToADRSetTask(o, accountToTaskMap.get(o.AccountId), uow);
        } 
    }
    public static void addRevenueToADRSetTask(Opportunity o, Task t, fflib_SObjectUnitOfWork uow)
    {
        if(o.RecurSoft__Contract_Signed_Date__c.addDays(-60) < t.CreatedDate &&
            t.ADR_Set__c == true &&
            t.Activity_Results__c == 'Spoke with-')
        {
            t.ADR_Set_SR_Revenue__c = o.RecurSoft__Contract_Signed_Date__c < Date.newInstance(2017,7,1) ? o.SR_Monthly_Revenue__c : o.Monthly_Revenue__c;
            uow.registerDirty(t);
        }
    }

    public static void closeAddendum(Set<Id> ids, fflib_SObjectUnitOfWork uow)
    {
        Opportunity[] opps = OpportunitiesSelector.newInstance().selectByIdWithAddenda(ids);

        for(Opportunity o : opps)
        {
            if(o.Addenda__r.size() == 0 || o.Addenda__r == null) continue;
            closeAddendum(o, uow);
        } 
    }

    public static void closeAddendum(Opportunity o, fflib_SObjectUnitOfWork uow)
    {   
        for(Addendum__c a : o.Addenda__r)
        {
            a.Status__c = 'Closed';
            uow.registerDirty(a);
        }
    }

    public static void createAssetForClosedOpps(Set<Id> ids, fflib_SObjectUnitOfWork uow)
    {
        Opportunity[] opps = OpportunitiesSelector.newInstance().selectByIdWithAccountAndProducts(ids);
        Map<Id, Account> acctMap = new Map<Id, Account>(AccountsSelector.newInstance().selectAccountByOpportunityWithAssets(opps));

        for(Opportunity o : opps)
        {
            createAssetForClosedOpps(o, acctMap.get(o.AccountId), uow);
        } 
    }

    public static void createAssetForClosedOpps(Opportunity o, Account acct, fflib_SObjectUnitOfWork uow) 
    {   
        Set<String> currentAssets = new Set<String>();
        Set<String> eligibleAssets = new Set<String>{'SR Platform','SR Reminders','Healthgrades','SR Schedule','SR Conversations','SR Smart Reviews','Provider'};
        String currentAssetName = '';
        String assetFamilyName = '';

        currentAssets.clear();

        if(acct.Assets.size() > 0) 
        {
            for(Asset a2 : acct.Assets) 
            {
                currentAssetName = a2.Product2.Family == 'Healthgrades' ? 'Healthgrades - ' + 
                    a2.Provider__r.Healthgrades_Id__c.replaceAll('(https?:\\/\\/)?(www\\.healthgrades\\.com\\/(\\w)+\\/)', '') : 
                    a2.Product2.Family;
                currentAssets.add(currentAssetName);
            }
        }

        for(OpportunityLineItem oppLi : o.OpportunityLineItems) 
        {
            if(oppLi.PricebookEntry.Product2.Family == null || !eligibleAssets.contains(oppLi.PricebookEntry.Product2.Family)) continue;

            assetFamilyName = oppLi.PricebookEntry.Product2.Family == 'Healthgrades' ? 'Healthgrades - ' + 
                oppLi.Provider__r.Healthgrades_Id__c.replaceAll('(https?:\\/\\/)?(www\\.healthgrades\\.com\\/(\\w)+\\/)', '') : 
                oppLi.PricebookEntry.Product2.Family;

            if(!currentAssets.contains(assetFamilyName)) 
            {
                Asset a = new Asset(AccountId = o.AccountId,
                    Name = o.Account.Subscriber_Id__c + ': ' + assetFamilyName,
                    Most_Recent_Pricebook__c = o.Pricebook2Id,
                    Price = oppLi.UnitPrice,
                    Product2Id = oppLi.PricebookEntry.Product2Id,
                    Quantity = oppLi.Quantity,
                    Original_Contract_Signed_Date__c = o.RecurSoft__Contract_Signed_Date__c,
                    Trial_End_Date__c = oppLi.Trial_End_Date__c,
                    Status = 'Active',
                    Provider__c = oppLi.Provider__c == null ? null : oppLi.Provider__c);

                uow.registerNew(a);

                //if(accountIdsToSyncToAppAdmin == null) accountIdsToSyncToAppAdmin = new Set<Id>();
                //accountIdsToSyncToAppAdmin.add(o.AccountId);
            }
        }
    }

    public static void newActivationCase(Set<Id> ids, fflib_SObjectUnitOfWork uow) 
    {
        Opportunity[] opps = OpportunitiesSelector.newInstance().selectByIdWithAccountAndProducts(ids);
        Map<Id, Account> accountWithCasesMap = new Map<Id, Account>(AccountsSelector.newInstance().selectByOpportunityWithCases(opps));

        for(Opportunity o : opps)
        {
            newActivationCase(o, accountWithCasesMap.get(o.AccountId), uow);
        } 
    }

    public static void newActivationCase(Opportunity o, Account account, fflib_SObjectUnitOfWork uow) 
    {
        if(!o.Contract_Signed__c) return;

        String SRC_QUEUE_ID = SR_Default_Values__c.getValues('SRC Onboarding Queue').Value__c;
        String SRSR_QUEUE_ID = SR_Default_Values__c.getValues('SRSR Onboarding Queue').Value__c;
        String SRS_QUEUE_ID = SR_Default_Values__c.getValues('SRS Onboarding Queue').Value__c;
        String ROUND_ROBIN_ID = SR_Default_Values__c.getValues('Case Round Robin Owner ID').Value__c;
        Boolean hasSR = false;
        Boolean hasSRR = false;
        Boolean hasSRS = false;
        Boolean hasSRC = false;
        Boolean hasSRSR = false;
        Boolean hasSRcase = false;
        Boolean hasSRRcase = false;
        Boolean hasSRScase = false;
        Boolean hasSRCcase = false;
        Boolean hasSRSRcase = false;
        Boolean hasHG = false;
        Set<Id> providerIds = new Set<Id>();

        Boolean isMajorMultiAccount = o.Account.RecordTypeId == SRUtilities.getRecordTypeId('Account', 'Major Account') ||
            o.Account.RecordTypeId == SRUtilities.getRecordTypeId('Account', 'Child Major Account') ||
            o.Account.RecordTypeId == SRUtilities.getRecordTypeId('Account', 'Multi-Location Account') ||
            o.Account.RecordTypeId == SRUtilities.getRecordTypeId('Account', 'Child Multi-Location Account');
                
        for(OpportunityLineItem oppLi : o.OpportunityLineItems) 
        {
            if(oppLi.PricebookEntry.Product2.Family == 'SR Platform') hasSR = true;
            if(oppLi.PricebookEntry.Product2.Family == 'SR Reminders') hasSRR = true;
            if(oppLi.PricebookEntry.Product2.Family == 'SR Schedule') hasSRS = true;
            if(oppLi.PricebookEntry.Product2.Family == 'SR Conversations') hasSRC = true;
            if(oppLi.PricebookEntry.Product2.Family == 'SR Smart Reviews') hasSRSR = true;
            if(oppLi.PricebookEntry.Product2.Family == 'Healthgrades') 
            {
                hasHG = true;
                providerIds.add(oppLi.Provider__c);
            }
        }

        for(Case c : account.Cases)
        {
            if(c.Subject == null) continue;
            if(c.Subject == 'Activation case for ' + o.Account.Name &&
                c.RecordTypeId == SRUtilities.getRecordTypeId('Case','Activation') &&
                c.Status == 'New') hasSRcase = true;
            if(c.Subject == 'SRC + Reminders Implementation' &&
                c.RecordTypeId == SRUtilities.getRecordTypeId('Case','Activation') &&
                c.Status == 'New') hasSRRcase = true;
            if(c.Subject == 'SR Schedule Implementation' &&
                c.RecordTypeId == SRUtilities.getRecordTypeId('Case','Support') &&
                c.Status == 'New') hasSRScase = true;
            if(c.Subject == 'SR Conversations Implementation' &&
                c.RecordTypeId == SRUtilities.getRecordTypeId('Case','Support') &&
                c.Status == 'New') hasSRCcase = true;
            if(c.Subject == 'SR Smart Reviews Implementation' &&
                c.RecordTypeId == SRUtilities.getRecordTypeId('Case','Support') &&
                c.Status == 'New') hasSRSRcase = true;
            if(c.Subject.startsWith('Healthgrades Implementation') &&
                c.RecordTypeId == SRUtilities.getRecordTypeId('Case','Support') &&
                c.Status == 'New' &&
                c.Provider__c != null) providerIds.remove(c.Provider__c);
        }
            
        if(hasSR && !hasSRcase) 
        {
            uow.registerNew(OpportunitiesService.newCase(o, 'SR Platform', ROUND_ROBIN_ID));    
        } 

        if(hasSRR && !hasSRRcase) 
        {
            uow.registerNew(OpportunitiesService.newCase(o, 'SRC + Reminders', o.OwnerId));   
        } 

        if(hasSRS && !hasSRScase) 
        {
           uow.registerNew(OpportunitiesService.newCase(o, 'SR Schedule', hasSR ? ROUND_ROBIN_ID : isMajorMultiAccount ? o.Account.OwnerId : SRS_QUEUE_ID));
        }

        if(hasSRC && !hasSRCcase)
        {
            uow.registerNew(OpportunitiesService.newCase(o, 'SR Conversations', hasSR ? ROUND_ROBIN_ID : isMajorMultiAccount ? o.Account.OwnerId : SRC_QUEUE_ID));
        }

        if(hasSRSR && !hasSRSRcase)
        {
            uow.registerNew(OpportunitiesService.newCase(o, 'SR Smart Reviews', hasSR ? ROUND_ROBIN_ID : isMajorMultiAccount ? o.Account.OwnerId : SRSR_QUEUE_ID));
        }

        if(hasHG && providerIds.size() > 0)
        {
            ProvidersService.newHealthgradesCase(providerIds, uow);
        }
    }

    public static void setAccountBillingEmailFromBillToContact(Set<Id> ids, fflib_SObjectUnitOfWork uow)
    {
        Opportunity[] opps = OpportunitiesSelector.newInstance().selectByIdWithAccountAndProducts(ids);

        for(Opportunity o : opps)
        {
            setAccountBillingEmailFromBillToContact(o, uow);
        } 
    }
    public static void setAccountBillingEmailFromBillToContact(Opportunity o, fflib_SObjectUnitOfWork uow)
    {
        if(o.RecurSoft__Billing_Contact__c == null) return;
        if(o.RecurSoft__Billing_Contact__r.Email == null) return;
        
        Account a = new Account(Id = o.AccountId,
            RecurSoft__Billing_Email__c = o.RecurSoft__Billing_Contact__r.Email);
        uow.registerDirty(a); 
    }

    public static void syncOpportunityOwners(Id ownerId, Opportunity[] opportunities, fflib_SObjectUnitOfWork uow)
    {
        for(Opportunity o : opportunities)
        {
            if(o.IsClosed) continue;
            if(o.OwnerId == ownerId) continue;
            
            o.OwnerId = ownerId;
            //uow.registerDirty(o);
        }
    }

    public static Case newCase(Opportunity o, String productName, Id ownerId)
    {
        return new Case(Subject = productName == 'SR Platform' ? 'Activation case for ' + o.Account.Name : productName + ' Implementation',
            AccountId = o.AccountId,
            Related_Opportunity__c = o.Id,
            ContactId = o.RecurSoft__Billing_Contact__c,
            RecordTypeId = SRUtilities.getRecordTypeId('Case','Activation'),
            Product__c = productName,
            Origin = 'Web',
            Status = 'New',
            Priority = 'Medium',
            Category__c = 'Training',
            Topics__c = 'General Training',
            OwnerId = ownerId);
    }

    public static void sendContractEmail(AsyncRequest__c ar)
    {
        Opportunity[] opps = OpportunitiesSelector.newInstance().selectByIdWithAccountAndProducts(new Set<Id>{ar.Params__c});
        SR_Default_Values__c contractEmailTemplateID = SR_Default_Values__c.getValues('New Customer Contract Email Template');
        SR_Default_Values__c contractEmailTemplateIDNoSubId = SR_Default_Values__c.getValues('Contract Email Template No Sub ID');
        ContractEmailTemplate__c contractEmailTemplateID_Old = ContractEmailTemplate__c.getValues('Services');
        OrgWideEmailAddress[] owea = [SELECT Id FROM OrgWideEmailAddress WHERE Address = 'support@solutionreach.com'];
        String templateId = contractEmailTemplateID.Value__c;

        for(Opportunity o : opps)
        {
            if(o.RecordTypeId == SRUtilities.getRecordTypeId('Opportunity', 'New Practice Business'))
            {
                templateId = contractEmailTemplateID.Value__c;

                if(o.Account.Subscriber_Id__c == null) 
                {
                    if(ar.Number_of_Attempts__c < 5) 
                    {
                        throw new SRUtilities.SRException('Account doesn\'t have a Subscriber ID');
                    }
                    else
                    {
                        templateId = contractEmailTemplateIDNoSubId.Value__c;
                    }
                }
            }
            else
            {
                templateId = contractEmailTemplateID_Old.TemplateID__c;
            }
            

            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setEntityAttachments(new List<String>{ar.Attachment_Id__c});
            mail.setBccAddresses(new List<String>{'randy@solutionreach.com','applications@solutionreach.com'});
            mail.setUseSignature(false);
            mail.setTemplateId(templateId);
            mail.setOrgWideEmailAddressId(owea[0].Id);
            mail.setWhatId(o.AccountId);
            mail.setTargetObjectId(o.RecurSoft__Billing_Contact__c);
            if(!ar.RequestedEmail__c) mail.setTreatTargetObjectAsRecipient(false);
         
            if(!Test.isRunningTest()) Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }
    }

    @future(callout=true)
    public static void generateAndAttachContractPdf(Id oppId, Boolean source, Boolean requestedEmail)
    {
        Opportunity[] opps = OpportunitiesSelector.newInstance().selectByIdWithAccountAndProducts(new Set<Id>{ oppId });

        for(Opportunity o : opps)
        {
            Blob body;
            String fileName = o.Account.Name.replaceAll(' ', '_').replaceAll(',', '_').replaceAll('//', '_').replaceAll('/', '_') + 
                + '_Service_Agreement_' 
                + System.now().format('MM/dd/yyyy HH:mm:ss','America/Denver')
                + '.pdf';
        
            PageReference pdf = new PageReference('/apex/SRContractPDF');
            pdf.getParameters().put('id', o.Id);
            pdf.getParameters().put('source', source == true ? 'api' : '');
                    
            body = Test.isRunningTest() ? Blob.valueOf('Test') : pdf.getContent();

            Attachment attachment = new Attachment();
            attachment.ParentId = o.Id;
            attachment.Name = fileName;
            attachment.Body = body;
            Database.SaveResult sr = Database.insert(attachment, false);

            if(sr.isSuccess()) 
            {               
                AsyncRequest__c asyncRequest = new AsyncRequest__c(AsyncType__c = 'Contract_Email', 
                   Params__c = o.Id,
                   RequestedEmail__c = requestedEmail, 
                   Attachment_ID__c = sr.getId());
                insert asyncRequest; 
            } 
            else
            {
                throw new SRUtilities.SRException(sr.getErrors()[0].getMessage());
            }
        }
    }

    public static OpportunityLineItem addOpportunityLineItem(Opportunity o, PriceBookEntry pbEntry, Decimal q) 
    {
        OpportunityLineItem results = new OpportunityLineItem(OpportunityId = o.Id,
                                                                PricebookEntryId = pbEntry.Id,
                                                                Quantity = q,
                                                                UnitPrice = pbEntry.UnitPrice);

        return results;
    }
}