src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.1/objects/Addendum__c.object
<CustomObject>
    <description>Represents a change to existing contractual terms</description>
    <label>Addendum</label>
    <nameField>
        <label>Addendum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addenda</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src.2/objects/Addendum_Line_Item__c.object
<CustomObject>
    <label>Addendum Line Item</label>
    <nameField>
        <displayFormat>ALI-{000000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addendum Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Addendum__c</fullName>
        <label>Addendum</label>
        <referenceTo>Addendum__c</referenceTo>
        <relationshipLabel>Addendum Line Items</relationshipLabel>
        <relationshipName>Addendum_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

src.3/objects/Asset.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related Provider record for Healthgrades Assets</description>
        <inlineHelpText>The related Provider record for Healthgrades Assets</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.2/objects/AsyncRequest__c.object
<CustomObject>
    <description>Used for logging Async requests to be processed.</description>
    <label>AsyncRequest</label>
    <nameField>
        <displayFormat>ASYNC-{0000000}</displayFormat>
        <label>AsyncRequest Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AsyncRequests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src.4/objects/Campaign_Influence__c.object
<CustomObject>
    <label>Campaign Influence</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Influence</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src.3/objects/Cancel_Request__c.object
<CustomObject>
    <description>Junction object between Retention Opportunities and Assets</description>
    <label>Cancel Request</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Cancel Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancel Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src.4/objects/Case.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Case/fields/Distribution_Group__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distribution Group</label>
    <referenceTo>Distribution_Group__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src.1/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Distribution_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distribution Group</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This Distribution Group does not currently available to be used.</errorMessage>
            <filterItems>
                <field>Distribution_Group__c.HasNextUser__c</field>
                <operation>equals</operation>
                <value>1</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Distribution_Group__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.2/objects/Distribution_Group__c.object
<CustomObject>
    <label>Distribution Group</label>
    <nameField>
        <label>Distribution Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src.1/objects/Distribution_Group_Member__c.object
<CustomObject>
    <label>Distribution Group Member</label>
    <nameField>
        <displayFormat>DGM-{000}</displayFormat>
        <label>Distribution Group Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Distribution Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Distribution_Group__c</fullName>
        <label>Distribution Group</label>
        <referenceTo>Distribution_Group__c</referenceTo>
        <relationshipLabel>Distribution Group Members</relationshipLabel>
        <relationshipName>Distribution_Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the related Provider record</description>
        <inlineHelpText>Link to the related Provider record</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Renewal_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Determines the system behaviour at the time of renewing the subscription.</inlineHelpText>
        <label>Renewal Rule</label>
        <referenceTo>RecurSoft__Renewal_Rule__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>RecurSoft_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Addendum__c.field-meta.xml
<CustomField>
    <fullName>Addendum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Addendum</label>
    <referenceTo>Addendum__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

src.3/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related Provider for the Healthgrades Premium Profile</description>
        <inlineHelpText>The related Provider for the Healthgrades Premium Profile</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Product_Subscription__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This field contains product subscription for current opportunity product.</inlineHelpText>
        <label>Product Subscription</label>
        <referenceTo>RecurSoft__Product_Subscription__c</referenceTo>
        <relationshipLabel>Opportunity Product (Product Subscription)</relationshipLabel>
        <relationshipName>RecurSoft_Opportunity_Product3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Renewal_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Determines the system behaviour at the time of renewing the subscription.</inlineHelpText>
        <label>Renewal Rule</label>
        <referenceTo>RecurSoft__Renewal_Rule__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>RecurSoft_Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.3/objects/Parent_Child_Mapping__c.object
<CustomObject>
    <label>Parent Child Mapping</label>
    <nameField>
        <displayFormat>PCM-{0000}</displayFormat>
        <label>Parent Child Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parent Child Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Provider__c/Provider__c.object-meta.xml
<CustomObject>
    <description>Used to store information about individual Providers within a Practice.  The Provider information is used for Healthgrades Premium members.</description>
    <label>Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src.2/objects/Sales_Credit__c.object
<CustomObject>
    <label>Sales Credit</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Sales Credit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Credits</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src.1/objects/Sales_Target__c.object
<CustomObject>
    <label>Sales Target</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Sales Target ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Targets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src.3/objects/Stamp_Field_Mapping__c.object
<CustomObject>
    <label>Stamp Field Mapping</label>
    <nameField>
        <displayFormat>SFM-{0000}</displayFormat>
        <label>Stamp Field Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stamp Field Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src.4/objects/Survey__c.object
<CustomObject>
    <description>Surveys from Customers about Sales, Cases and Cancels</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src.4/classes/TestUtilities2.cls
/*
fflib_AnswerTest
fflib_AnyOrderTest
fflib_ApexMocksTest
fflib_ApexMocksUtilsTest
fflib_ApplicationTest
fflib_ArgumentCaptorTest
fflib_IDGeneratorTest
fflib_InheritorTest
fflib_InOrderTest
fflib_MatcherDefinitionsTest
fflib_MatchTest
fflib_MethodArgValuesTest
fflib_QualifiedMethodAndArgValuesTest
fflib_QualifiedMethodTest
fflib_QueryFactoryTest
fflib_SecurityUtilsTest
fflib_SObjectDescribeTest
fflib_SObjectDomainTest
fflib_SObjectSelectorTest
fflib_SObjectUnitOfWorkTest
fflib_StringBuilderTest
fflib_SystemTest

sfab_ChildRelationshipNodeTest
sfab_FabricatedSObjectTest
sfab_FieldValuePairNodeTest
sfab_ParentRelationshipNodeTest
*/

@isTest
public class TestUtilities2 
{
	public static sfab_FabricatedSObject newAccount()
	{
		return new sfab_FabricatedSObject(Account.class)
            .setField(Account.Id, fflib_IDGenerator.generate(Account.SObjectType));
	}	

	public static sfab_FabricatedSObject newAsset()
	{
		return new sfab_FabricatedSObject(Asset.class)
            .setField(Asset.Id, fflib_IDGenerator.generate(Asset.SObjectType));
	}

	public static sfab_FabricatedSObject newAddendum()
	{
		return new sfab_FabricatedSObject(Addendum__c.class)
            .setField(Addendum__c.Id, fflib_IDGenerator.generate(Addendum__c.SObjectType));
	}

	public static sfab_FabricatedSObject newAddendumLineItems()
	{
		return new sfab_FabricatedSObject(Addendum_Line_Item__c.class)
            .setField(Addendum_Line_Item__c.Id, fflib_IDGenerator.generate(Addendum_Line_Item__c.SObjectType));
	}

	public static sfab_FabricatedSObject newOpportunity()
	{
		return new sfab_FabricatedSObject(Opportunity.class)
            .setField(Opportunity.Id, fflib_IDGenerator.generate(Opportunity.SObjectType));
	}

	public static sfab_FabricatedSObject newOpportunityLineItem()
	{
		return new sfab_FabricatedSObject(OpportunityLineItem.class)
            .setField(OpportunityLineItem.Id, fflib_IDGenerator.generate(OpportunityLineItem.SObjectType));
	}
	
	public static sfab_FabricatedSObject newOpportunityContactRole()
	{
		return new sfab_FabricatedSObject(OpportunityContactRole.class)
            .setField(OpportunityContactRole.Id, fflib_IDGenerator.generate(OpportunityContactRole.SObjectType));
	}

	public static sfab_FabricatedSObject newCancelRequest()
	{
		return new sfab_FabricatedSObject(Cancel_Request__c.class)
            .setField(Cancel_Request__c.Id, fflib_IDGenerator.generate(Cancel_Request__c.SObjectType));
	}

	public static sfab_FabricatedSObject newContact()
	{
		return new sfab_FabricatedSObject(Contact.class)
            .setField(Contact.Id, fflib_IDGenerator.generate(Contact.SObjectType));
	}

	public static sfab_FabricatedSObject newCases()
	{
		return new sfab_FabricatedSObject(Case.class)
            .setField(Case.Id, fflib_IDGenerator.generate(Case.SObjectType))
			.setField(Case.OwnerId, fflib_IDGenerator.generate(User.SObjectType));
	}

	public static sfab_FabricatedSObject newParentChildMapping()
	{
		return new sfab_FabricatedSObject(Parent_Child_Mapping__c.class)
            .setField(Parent_Child_Mapping__c.Id, fflib_IDGenerator.generate(Parent_Child_Mapping__c.SObjectType));
	}

	public static sfab_FabricatedSObject newProduct()
	{
		return new sfab_FabricatedSObject(Product2.class)
            .setField(Product2.Id, fflib_IDGenerator.generate(Product2.SObjectType));
	}
	public static sfab_FabricatedSObject newUser()
	{
		return new sfab_FabricatedSObject(User.class)
            .setField(User.Id, fflib_IDGenerator.generate(User.SObjectType));
	}
	public static sfab_FabricatedSObject newCampaign()
	{
		return new sfab_FabricatedSObject(Campaign.class)
            .setField(Campaign.Id, fflib_IDGenerator.generate(Campaign.SObjectType));
	}

	public static sfab_FabricatedSObject newCampaignMember()
	{
		return new sfab_FabricatedSObject(CampaignMember.class)
            .setField(CampaignMember.Id, fflib_IDGenerator.generate(CampaignMember.SObjectType));
	}

	public static sfab_FabricatedSObject newCampaignInfluence()
	{
		return new sfab_FabricatedSObject(Campaign_Influence__c.class)
            .setField(Campaign_Influence__c.Id, fflib_IDGenerator.generate(Campaign_Influence__c.SObjectType));
	}

	public static sfab_FabricatedSObject newAsyncRequest()
	{
		return new sfab_FabricatedSObject(AsyncRequest__c.class)
            .setField(AsyncRequest__c.Id, fflib_IDGenerator.generate(AsyncRequest__c.SObjectType));
	}

	public static sfab_FabricatedSObject newDistributionGroup()
	{
		return new sfab_FabricatedSObject(Distribution_Group__c.class)
            .setField(Distribution_Group__c.Id, fflib_IDGenerator.generate(Distribution_Group__c.SObjectType));
	}

	public static sfab_FabricatedSObject newDistributionGroupMember()
	{
		return new sfab_FabricatedSObject(Distribution_Group_Member__c.class)
            .setField(Distribution_Group_Member__c.Id, fflib_IDGenerator.generate(Distribution_Group_Member__c.SObjectType));
	}

	public static sfab_FabricatedSObject newRecurSoftProductSubscription()
	{
		return new sfab_FabricatedSObject(RecurSoft__Product_Subscription__c.class)
            .setField(RecurSoft__Product_Subscription__c.Id, fflib_IDGenerator.generate(RecurSoft__Product_Subscription__c.SObjectType));
	}

	public static sfab_FabricatedSObject newProvider()
	{
		return new sfab_FabricatedSObject(Provider__c.class)
            .setField(Provider__c.Id, fflib_IDGenerator.generate(Provider__c.SObjectType));
	}

	public static sfab_FabricatedSObject newPricebook2()
	{
		return new sfab_FabricatedSObject(Pricebook2.class)
            .setField(Pricebook2.Id, fflib_IDGenerator.generate(Pricebook2.SObjectType));
	}

	public static sfab_FabricatedSObject newRecurSoftRenewalRule()
	{
		return new sfab_FabricatedSObject(RecurSoft__Renewal_Rule__c.class)
            .setField(RecurSoft__Renewal_Rule__c.Id, fflib_IDGenerator.generate(RecurSoft__Renewal_Rule__c.SObjectType));
	}

	public static sfab_FabricatedSObject newPricebookEntry()
	{
		return new sfab_FabricatedSObject(PricebookEntry.class)
            .setField(PricebookEntry.Id, fflib_IDGenerator.generate(PricebookEntry.SObjectType));
	}

	public static sfab_FabricatedSObject newSalesCredit()
	{
		return new sfab_FabricatedSObject(Sales_Credit__c.class)
            .setField(Sales_Credit__c.Id, fflib_IDGenerator.generate(Sales_Credit__c.SObjectType));
	}

	public static sfab_FabricatedSObject newSalesTarget()
	{
		return new sfab_FabricatedSObject(Sales_Target__c.class)
            .setField(Sales_Target__c.Id, fflib_IDGenerator.generate(Sales_Target__c.SObjectType));
	}

	public static sfab_FabricatedSObject newStampFieldMapping()
	{
		return new sfab_FabricatedSObject(Stamp_Field_Mapping__c.class)
            .setField(Stamp_Field_Mapping__c.Id, fflib_IDGenerator.generate(Stamp_Field_Mapping__c.SObjectType));
	}

	public static sfab_FabricatedSObject newSurvey()
	{
		return new sfab_FabricatedSObject(Survey__c.class)
            .setField(Survey__c.Id, fflib_IDGenerator.generate(Survey__c.SObjectType));
	}

	public static sfab_FabricatedSObject newTask()
	{
		return new sfab_FabricatedSObject(Task.class)
            .setField(Task.Id, fflib_IDGenerator.generate(Task.SObjectType));
	}

	public static sfab_FabricatedSObject existingAccount(sfab_FabricatedSObject existing)
	{
		return new sfab_FabricatedSObject(Account.class)
            .setField(Account.Id, existing.toSObject().Id);
	}

	public static sfab_FabricatedSObject existingOpportunity(sfab_FabricatedSObject existing)
	{
		return new sfab_FabricatedSObject(Opportunity.class)
            .setField(Opportunity.Id, existing.toSObject().Id);
	}

	public static sfab_FabricatedSObject existingOpportunityLineItem(sfab_FabricatedSObject existing)
	{
		return new sfab_FabricatedSObject(OpportunityLineItem.class)
            .setField(OpportunityLineItem.Id, existing.toSObject().Id);
	}

	public static sfab_FabricatedSObject existingContact(sfab_FabricatedSObject existing)
	{
		return new sfab_FabricatedSObject(Contact.class)
            .setField(Contact.Id, existing.toSObject().Id);
	}
	public static sfab_FabricatedSObject existingUser(sfab_FabricatedSObject existing)
	{
		return new sfab_FabricatedSObject(User.class)
            .setField(User.Id, existing.toSObject().Id);
    }

	public static sfab_FabricatedSObject existingCampaign(sfab_FabricatedSObject existing)
	{
		return new sfab_FabricatedSObject(Campaign.class)
            .setField(Campaign.Id, existing.toSObject().Id);
	}

	public static sfab_FabricatedSObject existingCampaignMember(sfab_FabricatedSObject existing)
	{
		return new sfab_FabricatedSObject(CampaignMember.class)
            .setField(CampaignMember.Id, existing.toSObject().Id);
	}

	public static sfab_FabricatedSObject existingCampaignInfluence(sfab_FabricatedSObject existing)
	{
		return new sfab_FabricatedSObject(Campaign_Influence__c.class)
            .setField(Campaign_Influence__c.Id, existing.toSObject().Id);
	}

	public static sfab_FabricatedSObject existingAsyncRequest(sfab_FabricatedSObject existing)
	{
		return new sfab_FabricatedSObject(AsyncRequest__c.class)
            .setField(AsyncRequest__c.Id, existing.toSObject().Id);
	}

	public static sfab_FabricatedSObject existingAccount(Account existing)
	{
		return new sfab_FabricatedSObject(Account.class)
            .setField(Account.Id, existing.Id);
	}

	public static sfab_FabricatedSObject existingOpportunity(Opportunity existing)
	{
		return new sfab_FabricatedSObject(Opportunity.class)
            .setField(Opportunity.Id, existing.Id);
	}

	public static sfab_FabricatedSObject existingOpportunityLineItem(OpportunityLineItem existing)
	{
		return new sfab_FabricatedSObject(OpportunityLineItem.class)
            .setField(OpportunityLineItem.Id, existing.Id);
	}

	public static sfab_FabricatedSObject existingAddendumLineItem(Addendum_Line_Item__c existing)
	{
		return new sfab_FabricatedSObject(Addendum_Line_Item__c.class)
            .setField(Addendum_Line_Item__c.Id, existing.Id);
	}

	public static sfab_FabricatedSObject existingProduct(Product2 existing)
	{
		return new sfab_FabricatedSObject(Product2.class)
            .setField(Product2.Id, existing.Id);
	}

	public static sfab_FabricatedSObject existingSurvey(sfab_FabricatedSObject existing)
	{
		return new sfab_FabricatedSObject(Survey__c.class)
            .setField(Survey__c.Id, existing.toSObject().Id);
	}

	public static sfab_FabricatedSObject existingContact(Contact existing)
	{
		return new sfab_FabricatedSObject(Contact.class)
            .setField(Contact.Id, existing.Id);
	}

	public static sfab_FabricatedSObject existingCampaign(Campaign existing)
	{
		return new sfab_FabricatedSObject(Campaign.class)
            .setField(Campaign.Id, existing.Id);
	}

	public static sfab_FabricatedSObject existingCampaignInfluence(CampaignMember existing)
	{
		return new sfab_FabricatedSObject(CampaignMember.class)
            .setField(CampaignMember.Id, existing.Id);
	}

	public static sfab_FabricatedSObject existingCampaignInfluence(Campaign_Influence__c existing)
	{
		return new sfab_FabricatedSObject(Campaign_Influence__c.class)
            .setField(Campaign_Influence__c.Id, existing.Id);
	}

	public static sfab_FabricatedSObject existingCase(sfab_FabricatedSObject existing)
	{
		return new sfab_FabricatedSObject(Case.class)
				.setField(Case.Id, existing.toSObject().Id);
	}

	public static sfab_FabricatedSObject existingCase(Case existing)
	{
		return new sfab_FabricatedSObject(Case.class)
				.setField(Case.Id, existing.Id);
	}
}