src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>RecurSoft__Intacct_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Determines whether customer records are created at the root or entity level in Intacct.</inlineHelpText>
        <label>Intacct Entity</label>
        <referenceTo>RecurSoft__Intacct_Entity__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>RecurSoft_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <formula>Owner.FirstName + &quot; &quot; + Owner.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Rep</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <label>PM/EHR Partner</label>
    </recordTypes>
</CustomObject>

src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Cancel_Month__c</fullName>
        <description>Sugar field for Save Opportunity</description>
        <label>Cancel Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Signed_Date__c</fullName>
        <label>Contract Signed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Intacct_Entity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Intacct Entity</label>
        <referenceTo>RecurSoft__Intacct_Entity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>RecurSoft_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Target__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep Target</label>
        <referenceTo>Sales_Target__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.1/objects/Pricebook2.object
<CustomObject>
    <sharingModel>ReadSelect</sharingModel>
    <fields>
        <fullName>Number_of_Providers_Included__c</fullName>
        <label>Number of Providers Included</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Add Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.2/objects/Sales_Credit__c.object
<CustomObject>
    <label>Sales Credit</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Sales Credit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Credits</pluralLabel>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Sales Credits (Manager)</relationshipLabel>
        <relationshipName>Mgr_Sales_Credits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Credits</relationshipLabel>
        <relationshipName>Sales_Credits</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Override_Trigger_Logic__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, this will prevent the trigger logic that automatically adds the lookup relationship to the target based on the contract signed date. The total actual credits for each target will still be updated appropriately.</description>
        <inlineHelpText>Check to override the trigger logic. This will allow the Sales Target lookup fields to be changed manually. Unchecking will revert to the trigger logic and automatically assign the Sales Target lookup fields.</inlineHelpText>
        <label>Override Trigger Logic</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Target__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep Target</label>
        <referenceTo>Sales_Target__c</referenceTo>
        <relationshipLabel>Sales Credits (Sales Rep Target)</relationshipLabel>
        <relationshipName>Sales_Credits3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Rep Sales Credits</relationshipLabel>
        <relationshipName>Rep_Sales_Credits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VP</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Sales Credits (VP)</relationshipLabel>
        <relationshipName>Sales_Credits</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.1/objects/Sales_Target__c.object
<CustomObject>
    <label>Sales Target</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Sales Target ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Targets</pluralLabel>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Manager__c</fullName>
        <label>Manager</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Target Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Specifies the type of target. Used to have multiple targets per person in the case of Hybrid Managers. Set on target creation manually by Sales Ops or automatically if a target doesn&#39;t exist for a new Sales Credit.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Rep</fullName>
                </value>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>VP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unique_Target__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Ensures that the combination of Target Owner, Year, and Month are unique for each target.</description>
        <inlineHelpText>Ensures that the combination of Target Owner, Year, and Month are unique for each target.</inlineHelpText>
        <label>Unique Target</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>VP__c</fullName>
        <label>VP</label>
        <length>40</length>
        <type>Text</type>
    </fields>
</CustomObject>

src.1/objects/SR_Default_Values__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SR Default Values</label>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/SalesCreditsService_Test.cls
@isTest
private class SalesCreditsService_Test {
	
	@isTest static void test_assignSalesCreditToSalesTarget() 
	{
		Pricebook2 pb = new Pricebook2(
            Name = 'Custom Pricebook',
            IsActive = true,
            Number_of_Providers_Included__c = 10);
        insert pb;

		insert new SR_Default_Values__c(Name = 'salesTargetRolesProfiles',
			Description__c='salesTargetRolesProfiles',
            Value__c = 'System Administrator');

		insert new SR_Default_Values__c(Name = 'defaultPricebookStage',
            Description__c='defaultPricebookStage',
            Value__c = 'Pre-Qualified');

		insert new SR_Default_Values__c(Name = 'defaultPricebookId',
            Description__c='defaultPricebookId',
            Value__c = pb.Id); 

        insert new SR_Default_Values__c(Name = 'leadSourceToCampaignId',
            Description__c='leadSourceToCampaignId',
            Value__c = 'ADR Set:70131000001lbcW::Cold Call:70131000001lbcR::Direct Mail:70131000001Nmcx::Email:70131000001Nmcd::Other Website:70131000001uCC2::PPC:7010Z000001vKi7::Referral Partner:70131000001uGlJ::SR Website:70131000001uCBx::Trade Show/Event:70131000001Nmci');

        insert new SR_Default_Values__c(Name = 'noStealingProfiles',
            Description__c = 'noStealingProfiles',
            Value__c = String.valueOf(UserInfo.getProfileId()));
		
        User u;
        Account a;        
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        
        RecurSoft__Intacct_Entity__c intacct = new RecurSoft__Intacct_Entity__c(Name = 'TestAccount2');
        insert intacct;
        
        System.runAs (thisUser) 
        {            
            String profileName = 'System Administrator';
            String roleName = 'CSR Enterprise';
            Profile p = [SELECT Id FROM Profile WHERE Name = :profileName LIMIT 1];
            UserRole r = [SELECT Id FROM UserRole WHERE Name = :roleName LIMIT 1];
            u = new User(
                Username = profileName.deleteWhitespace() + '@solutionreach.com',
                Alias = profileName.deleteWhitespace().substring(0,7),
                LastName = 'TestUserLast',
                Email = profileName.deleteWhitespace() + '@solutionreach.com',
                EmailEncodingKey = 'UTF-8',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US',
                TimeZoneSidKey = 'America/Denver',
                ProfileId = p.Id,
                UserRoleId = r.Id);                   
            insert u;

            a = new Account(
                Name = 'TestAccount2',
                RecurSoft__Intacct_Entity__c = intacct.id,
                Industry = 'Dental',
                OwnerId = u.Id);                    
            insert a;
        }

        Opportunity  opp = new Opportunity(
        	Name = 'Test Opportunity',
            StageName = 'No Sale',
            CloseDate = Date.today(),
            AccountId = a.Id,
            OwnerId = u.Id,
            Cancel_Month__c = Date.today().toStartofMonth(),
            RecurSoft__Contract_Signed_Date__c = Date.newInstance(2018,1,1));
        insert opp;

        String monthValue = 'January';
        String yearValue =	String.valueOf(opp.RecurSoft__Contract_Signed_Date__c.year());
        String uniqueValue = yearValue + monthValue + u.Id + 'Rep'; 

        Sales_Target__c st = new Sales_Target__c(
			Owner__c = u.Id,			
			Type__c = 'Rep',			
        	Unique_Target__c = uniqueValue);               
        insert st;
     
        Sales_Credit__c sc = new Sales_Credit__c(
        	Sales_Rep__c = u.Id,
            Manager__c = null,
            VP__c = null,
            Override_Trigger_Logic__c = false,
            Opportunity__c = opp.Id);                   
        insert sc;
		
        System.assertEquals(1, [select count() from Sales_Credit__c where  Sales_Rep_Target__c != null]);

	}
	
}