src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account Lookup</description>
        <inlineHelpText>Choose the Account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Bill_to_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Default Bill to Account for usage billing.</inlineHelpText>
        <label>Bill to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Bill to Account)</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Status__c</fullName>
        <description>Picklist used to determine if an account is an active customer.</description>
        <inlineHelpText>Determined by the status of subscriptions (not created, created, not activated, or cancelled)</inlineHelpText>
        <label>ISB Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Timed_Distribution_Group_Date__c</fullName>
        <description>Stamps the last time an Account goes through a time-based Distribution Group. Time-based Distribution Groups are groups that only allow an Account to pass through once every X hours. The Distribution Group assignment will be blocked by an Apex validation in ContactsService that compares this field with the Timed Distribution Group Hours on the Distribution Group object.</description>
        <label>Timed Distribution Group Date</label>
        <type>DateTime</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.1/objects/Activity.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>ADR_Set_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SAE will check this box to acknowledge receiving an ADR set</description>
        <inlineHelpText>Check this box when an ADR set has been received</inlineHelpText>
        <label>ADR Set Received</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src.1/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Ambassador__Short_Code__c</fullName>
        <label>Referring Short Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CampaignId__c</fullName>
        <description>Populated by HubSpot to create a CampaignMember for the Id specified.</description>
        <label>CampaignId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DistGroup__c</fullName>
        <description>Set by HubSpot and used in Apex to set the matching Distribution Group.</description>
        <label>DistGroup</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distribution Group</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This Distribution Group does not currently available to be used.</errorMessage>
            <filterItems>
                <field>Distribution_Group__c.HasNextUser__c</field>
                <operation>equals</operation>
                <value>1</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Distribution_Group__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Contact/fields/Demo_Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Demo_Scheduled_Date__c</fullName>
    <description>When this field is set, a Demo Scheduled task is created at this date/time via Apex.  The task will be owned by the user setting the field and will be reassigned if sent to a Distribution Group.</description>
    <label>Demo Scheduled Date</label>
    <type>DateTime</type>
</CustomField>

src.2/objects/Distribution_Group__c.object
<CustomObject>
    <label>Distribution Group</label>
    <nameField>
        <label>Distribution Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>CampaignId__c</fullName>
        <description>Create a Campaign Influence with this Campaign Id</description>
        <label>CampaignId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Setting__c</fullName>
        <label>Customer Setting</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Prospects Only</fullName>
                </value>
                <value>
                    <fullName>Customers Only</fullName>
                </value>
                <value>
                    <fullName>Prospects and Customers</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Major_Accounts__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For Distribution Groups that contain only one Major Account rep.  Also, changes the Opportunity Record Type to Enterprise New Practice Business.</description>
        <label>Major Accounts</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Open_Opportunity_Setting__c</fullName>
        <label>Open Opportunity Setting</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Notify Owner</fullName>
                    <default>true</default>
                    <label>Notify Owner</label>
                </value>
                <value>
                    <fullName>Reassign Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Timed_Distribution_Group_Hours__c</fullName>
        <description>Time-based Distribution Groups are groups that only allow an Account to pass through once every X hours. The Distribution Group assignment will be blocked by an Apex validation in ContactsService that compares this field with the Timed Distribution Group Date on the Account object.</description>
        <label>Timed Distribution Group Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Distribution_Group__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Distribution Groups</relationshipLabel>
    <relationshipName>Distribution_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

src.3/objects/Distribution_Group_History__c.object
<CustomObject>
    <label>Distribution Group History</label>
    <nameField>
        <label>Distribution Group History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Group Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Distribution Group Histories</relationshipLabel>
        <relationshipName>Distribution_Group_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Distribution Group Histories</relationshipLabel>
        <relationshipName>Distribution_Group_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Distribution_Group__c</fullName>
        <label>Distribution Group</label>
        <referenceTo>Distribution_Group__c</referenceTo>
        <relationshipLabel>Distribution Group Histories</relationshipLabel>
        <relationshipName>Distribution_Group_Histories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Distribution_Group_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.1/objects/Distribution_Group_Member__c.object
<CustomObject>
    <label>Distribution Group Member</label>
    <nameField>
        <displayFormat>DGM-{000}</displayFormat>
        <label>Distribution Group Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Distribution Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Available__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Distribution_Group__c</fullName>
        <label>Distribution Group</label>
        <referenceTo>Distribution_Group__c</referenceTo>
        <relationshipLabel>Distribution Group Members</relationshipLabel>
        <relationshipName>Distribution_Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Next_Up__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Next Up</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Distribution_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.1/objects/Lead.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>Ambassador__Short_Code__c</fullName>
        <label>Referring Short Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Ambassador__Short_Code__c</fullName>
        <label>Referring Short Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apex_Override_Validation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows Apex code to bypass validation rules.  Reset to false by Workflow field update.</description>
        <label>Apex Override Validation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Bill_to_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Bill to Account)</relationshipLabel>
        <relationshipName>RecurSoft_OpportunitiesAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Initial_Contract_Term__c</fullName>
        <defaultValue>12</defaultValue>
        <inlineHelpText>Contract duration, in months.</inlineHelpText>
        <label>Contract Term (Months)</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Trial__c</fullName>
        <description>Trial Period in Days.</description>
        <inlineHelpText>Period during which contracts can be cancelled without penalties.</inlineHelpText>
        <label>Trial Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0 - Waived</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                    <default>true</default>
                    <label>60</label>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Referred_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the Contact that was referred by an Ambassador</description>
        <label>Referred Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Referred Contact)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies the User that created the record.  May be different than CreatedBy because of automations.  Set via Apex.</description>
        <label>Source User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.1/objects/SR_Default_Values__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SR Default Values</label>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

src.3/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>AtPipelineLimit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set via Apex. Used to validate in Distribution Group</description>
        <label>AtPipelineLimit</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src.2/classes/ContactsService.cls
public class ContactsService 
{
	public static void processDistributionGroup(Map<Id, Id> contactIdToDistGroupId, Map<Id, Id> contactIdToUserId, fflib_SObjectUnitOfWork uow) 
	{
		Contact[] contacts = ContactsSelector.newInstance().selectByIdWithAccount(contactIdToDistGroupId.keySet());
		Set<String> contactToCampaign = new Set<String>();
		Map<Id, Account> accountMap = AccountsSelector.newInstance().selectAccountByContactWithParentAccount(contacts);
		Map<Id, Account> parentAccountMap = AccountsSelector.newInstance().selectParentAccountByAccount(accountMap.values());
		Map<Id, Task[]> accountTaskMap = TasksSelector.newInstance().selectADRSetsByAccountId(contacts);
		OrgWideEmailAddress[] owea = [SELECT Id FROM OrgWideEmailAddress WHERE Address = 'srreplies@solutionreach.com'];
		Id jennyPoolUserId = SR_Default_Values__c.getValues('jennyPoolUserId').Value__c;

		Map<Id, Distribution_Group__c> distGroupMap = new Map<Id, Distribution_Group__c>([SELECT Id, 
			Name, Open_Opportunity_Setting__c, CampaignId__c, Customer_Setting__c, Timed_Distribution_Group_Hours__c, Major_Accounts__c, Price_Book__c,
			(SELECT Id, Name, User__c, User__r.Name, User__r.FirstName, User__r.LastName, Available__c, 
			Next_Up__c, Distribution_Group__c, User__r.AtPipelineLimit__c
				FROM Distribution_Group_Members__r
				WHERE Available__c = true 
				AND User__r.AtPipelineLimit__c = false
				AND User__r.IsActive = true
				ORDER BY User__r.LastName ASC)
			FROM Distribution_Group__c WHERE Id IN :contactIdToDistGroupId.values()]);
		Distribution_Group_Member__c[] distGroupMembers = new List<Distribution_Group_Member__c>();

		for(Contact contact : contacts) 
		{
			if(!contactIdToDistGroupId.keySet().contains(contact.Id)) return;
			Id distGroupId = contactIdToDistGroupId.get(contact.Id);
			Account account = accountMap.get(contact.AccountId);
			Account parentAccount = account.ParentId != null && parentAccountMap.containsKey(account.ParentId) ? parentAccountMap.get(account.ParentId) : null;
			Opportunity opp = parentAccount != null && parentAccount.Opportunities.size() > 0 ? parentAccount.Opportunities[0] : account.Opportunities.size() > 0 ?
				account.Opportunities[0] : null;
			Distribution_Group__c distGroup = distGroupMap.get(distGroupId);
			Boolean isNewOwner = false;
			Id demoTaskId;

			contact.DistGroup__c = null;
			contact.Distribution_Group__c = null;
			uow.registerDirty(contact);

			if(distGroup.CampaignId__c != null) contactToCampaign.add(contact.Id + '::' + distGroup.CampaignId__c + ':' + contactIdToUserId.get(contact.Id));

			if(skipCustomerStatus(account, parentAccount, contact, distGroup, uow)) continue;
			if(skipTimedDistGroup(account, parentAccount, contact, distGroup, uow)) continue;

			User user = getUser(account, parentAccount, opp, distGroup, uow);

			if(opp == null &&
				user.Id != jennyPoolUserId) uow.registerNew(createNewOpp(user.Id, contactIdToUserId.get(contact.Id), distGroup, parentAccount != null ? parentAccount : account, contact.Ambassador__Short_Code__c != null && contact.Ambassador__Short_Code__c != '' ? contact.Id : null));

			if(contact.OwnerId != user.Id)
			{
				isNewOwner = true;
				contact.OwnerId = user.Id;
				uow.registerDirty(contact);
			}

			if(opp != null && 
				distGroup.Open_Opportunity_Setting__c == 'Reassign Opportunity' && 
				opp.OwnerId != user.Id)
			{
				isNewOwner = true;
				opp.OwnerId = user.Id;
				uow.registerDirty(opp);
			}

			if(account.OwnerId != user.Id)
			{
				isNewOwner = true;
				account.OwnerId = user.Id;
				uow.registerDirty(account);
			}

			if(parentAccount != null && parentAccount.OwnerId != user.Id)
			{
				isNewOwner = true;
				parentAccount.OwnerId = user.Id;
				uow.registerDirty(parentAccount);
			}

			if(account.Id != null && accountTaskMap != null && accountTaskMap.containsKey(account.Id) && accountTaskMap.get(account.Id).size() > 0)
			{				
				for(Task t : accountTaskMap.get(account.Id))
				{
					demoTaskId = t.Id;
					t.OwnerId = user.Id;
					t.ADR_Set_Received__c = true;
					uow.registerDirty(t);
				}
			}

			if(user.Id != jennyPoolUserId) uow.registerEmail(buildMessage(owea, account, contact, user.Id, isNewOwner, demoTaskId));
			createHistory(distGroup, user, contact, account, parentAccount, uow);
		}

		if(contactToCampaign != null && 
            !contactToCampaign.isEmpty()) SRUtilities.scheduleAsync(contactToCampaign, 'Create_CI', uow);
	}

	public static Messaging.SingleEmailMessage buildMessage(OrgWideEmailAddress[] owea, Account account, Contact contact, Id userId, Boolean isNewOwner, Id demoTaskId)
	{
		String subject = demoTaskId != null ? '*DEMO REQUEST* ' : '';
		subject += isNewOwner ? 'New Lead Assigned' : 'New Lead Activity';
		String intro = isNewOwner ? 'have been assigned to you: ' : 'need your attention: ';
		String acctName = account != null ? account.ParentId == null ? account.Name : account.Parent.Name : null;
		String acctId = account != null ? account.ParentId == null ? account.Id : account.ParentId : null;
		String acctLink = account != null ? acctName + '\n' + 'https://solutionreach.lightning.force.com/lightning/r/Account/' + acctId + '/view\n\n' : 'Please link to an existing Account or create a new Account.' + '\n\n';
		String demoLink = demoTaskId != null ? '*LINK TO DEMO*: https://solutionreach.lightning.force.com/lightning/r/Task/' + demoTaskId + '/view\n\n' : '';	

		Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        message.setSubject(subject);
        message.setPlainTextBody(demoLink +
        'The following Account and Contact ' + intro + '\n\n' +
        'Account: ' + acctLink +
        'Contact: ' + contact.FirstName + ' ' + contact.LastName + '\n' + 'https://solutionreach.lightning.force.com/lightning/r/Contact/' + contact.Id + '/view');
	    message.setSaveAsActivity(false);
	    message.setTargetObjectId(userId);
	    //message.setBccAddresses(new String[] { '005i0000002fU4O' });
          
        if(owea.size() > 0) 
        {
        	message.setOrgWideEmailAddressId(owea.get(0).Id);
        }

        return message;
	}

	public static void createHistory(Distribution_Group__c distGroup, User user, Contact contact, Account account, Account parentAccount, fflib_SObjectUnitOfWork uow)
	{
		Distribution_Group_History__c history = new Distribution_Group_History__c(Name = distGroup.Name + String.valueOf(Datetime.now()),
			Description__c = user.AboutMe,
			Contact__c = contact.Id,
			Account__c = parentAccount != null ? parentAccount.Id : account.Id,
			Distribution_Group__c = distGroup.Id,
			User__c = user.Id);
		uow.registerNew(history);
	}

	public static Opportunity createNewOpp(Id ownerId, Id sourceUser, Distribution_Group__c distGroup, Account a, Id contactId)
	{
		Opportunity o = new Opportunity(Name = a.Name + '-',
			AccountId = a.Id,
			OwnerId = ownerId,
			Source_User__c = sourceUser,
            StageName = 'Demo Scheduled',
            RecordTypeId = SRUtilities.getRecordTypeMap('Opportunity').get(a.RecurSoft__Status__c == 'Active'  ? 'Add Product' : distGroup.Major_Accounts__c  ? 'Enterprise New Business' : 'New Practice Business').getRecordTypeId(),
            Pricebook2Id = distGroup.Price_Book__c == null ? null : distGroup.Price_Book__c,
            RecurSoft__Trial__c = 'None',
            Apex_Override_Validation__c = true,
            CloseDate = Date.today().addDays(30),
            RecurSoft__Initial_Contract_Term__c = 24,
            Referred_Contact__c = contactId,
            RecurSoft__Bill_to_Account__c = a.Id);
		return o;
	}

	public static Id getDistGroup(Contact c)
	{
		if(c.DistGroup__c == null && c.Distribution_Group__c == null) return null;

		Id distGroupId = c.Distribution_Group__c != null ? c.Distribution_Group__c : c.DistGroup__c InstanceOf Id ? c.DistGroup__c : null;
		return distGroupId;
	}

	public static User getUser(Account account, Account parentAccount, Opportunity opportunity, Distribution_Group__c distGroup, fflib_SObjectUnitOfWork uow)
	{
		if(opportunity != null && distGroup.Open_Opportunity_Setting__c != 'Reassign Opportunity') return new User(Id = parentAccount != null ? parentAccount.OwnerId : account.OwnerId, 
				AboutMe = 'Stayed with owner because of open Opportunity');
		else return DistributionGroupsService.getNextUserId(distGroup.Distribution_Group_Members__r, distGroup.Id, uow);
	}

	public static Boolean skipCustomerStatus(Account account, Account parentAccount, Contact contact, Distribution_Group__c distGroup, fflib_SObjectUnitOfWork uow)
	{
		if(((account.RecurSoft__Status__c == 'Active' || 
					(parentAccount != null && parentAccount.RecurSoft__Status__c == 'Active')) 
					&& distGroup.Customer_Setting__c == 'Prospects Only') ||
				((parentAccount == null && account.RecurSoft__Status__c != 'Active' || 
					(parentAccount != null && parentAccount.RecurSoft__Status__c != 'Active')) 
					&& distGroup.Customer_Setting__c == 'Customers Only') ||
				((account.RecurSoft__Status__c == 'Ineligible' || 
				(parentAccount != null && parentAccount.RecurSoft__Status__c == 'Ineligible'))))
		{
			User user = new User(Id = parentAccount != null ? parentAccount.OwnerId : account.OwnerId, AboutMe = 'Skipped because of customer status');
			createHistory(distGroup, user, contact, account, parentAccount, uow);
			return true;
		}
		return false;
	}

	public static Boolean skipTimedDistGroup(Account account, Account parentAccount, Contact contact, Distribution_Group__c distGroup, fflib_SObjectUnitOfWork uow)
	{
		if(distGroup.Timed_Distribution_Group_Hours__c == null) return false;

		if((account.Timed_Distribution_Group_Date__c != null &&
				account.Timed_Distribution_Group_Date__c.addHours(Integer.valueOf(distGroup.Timed_Distribution_Group_Hours__c)) > Datetime.now()) ||
			(parentAccount != null &&
				parentAccount.Timed_Distribution_Group_Date__c != null &&
				parentAccount.Timed_Distribution_Group_Date__c.addHours(Integer.valueOf(distGroup.Timed_Distribution_Group_Hours__c)) > Datetime.now()))
		{
			User user = new User(Id = parentAccount != null ? parentAccount.OwnerId : account.OwnerId, AboutMe = 'Skipped because of timed Distribution Group');
			createHistory(distGroup, user, contact, account, parentAccount, uow);
			return true;
		}
		else
		{
			account.Timed_Distribution_Group_Date__c = Datetime.now();
			uow.registerDirty(account);
			if(parentAccount != null)
			{
				parentAccount.Timed_Distribution_Group_Date__c = Datetime.now();
				uow.registerDirty(parentAccount);
			} 
			return false;
		}
	}

	public static void syncContactOwners(Map<Id, Id> accountIdToOwnerId, Contact[] contacts, fflib_SObjectUnitOfWork uow)
	{
		for(Contact c : contacts)
		{
			Id ownerId = accountIdToOwnerId.get(c.AccountId);
			if(c.OwnerId == ownerId) continue;					
			c.OwnerId = ownerId;
			uow.registerDirty(c);
		}
	}

	@future
    public static void clearDemoTaskDate(Set<Id> ids)
    {
		fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
    	Contact[] contacts = ContactsSelector.newInstance().selectByIdWithAccount(ids);

    	for(Contact c : contacts)
    	{
    		c.Demo_Scheduled_Date__c = null;
    		c.Demo_Scheduled_Date_Text__c = null;
    		uow.registerDirty(c);
    	}

    	uow.commitWork();
    }
}