src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Last_ROE_Date__c</fullName>
        <label>Last ROE Date</label>
        <type>DateTime</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.1/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Ambassador__Short_Code__c</fullName>
        <label>Referring Short Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assign_to_Distribution_Group__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Assign to Distribution Group</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Associated_Opp__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Opp</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contacts (Associated Opp)</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Best_Day_to_Contact__c</fullName>
        <label>Best Day to Contact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Best_Time_to_Contact__c</fullName>
        <label>Best Time to Contact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Morning</fullName>
                </value>
                <value>
                    <fullName>Afternoon</fullName>
                </value>
                <value>
                    <fullName>Evening</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CampaignId__c</fullName>
        <description>Populated by HubSpot to create a CampaignMember for the Id specified.</description>
        <label>CampaignId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Role_Multi__c</fullName>
        <description>Used for when a contract is signed to assign roles from the contract</description>
        <label>Contact Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Doctor/Owner</fullName>
                </value>
                <value>
                    <fullName>Business Contact</fullName>
                </value>
                <value>
                    <fullName>Billing Contact</fullName>
                </value>
                <value>
                    <fullName>Contract Signer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <label>Contact Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Staff Member</fullName>
                    <default>true</default>
                    <label>Staff Member</label>
                </value>
                <value>
                    <fullName>Decision Maker</fullName>
                </value>
                <value>
                    <fullName>Billing Contact</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>Technical Contact</fullName>
                </value>
                <value>
                    <fullName>Doctor</fullName>
                </value>
                <value>
                    <fullName>Business User</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                    <isActive>false</isActive>
                    <label>Consultant</label>
                </value>
                <value>
                    <fullName>DecisionMaker</fullName>
                    <isActive>false</isActive>
                    <label>DecisionMaker</label>
                </value>
                <value>
                    <fullName>General Dentistry</fullName>
                    <isActive>false</isActive>
                    <label>General Dentistry</label>
                </value>
                <value>
                    <fullName>OfficeContact</fullName>
                    <isActive>false</isActive>
                    <label>OfficeContact</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Created_From_Lead_Convertion__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Tells if the contact is created from Lead Convertion</description>
        <label>Created From Lead Convertion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DistGroup__c</fullName>
        <description>Set by HubSpot and used in Apex to set the matching Distribution Group.</description>
        <label>DistGroup</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distribution Group</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This Distribution Group does not currently available to be used.</errorMessage>
            <filterItems>
                <field>Distribution_Group__c.HasNextUser__c</field>
                <operation>equals</operation>
                <value>1</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Distribution_Group__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_ROE_Date__c</fullName>
        <description>Apex mapping via Parent/Child Mappings</description>
        <label>Last ROE Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Powerstone__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies if the Contact has been sent to Powerstone for a call campaign. The Contact will be removed from Powerstone&#39;s list and this field will be updated if ROE is established on the Account.</description>
        <label>Powerstone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Purchase_Involvement__c</fullName>
        <label>Purchase Involvement</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Uninvolved</fullName>
                </value>
                <value>
                    <fullName>Involved</fullName>
                </value>
                <value>
                    <fullName>Decision Maker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Survey_Opt_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Opts out the Contact from getting Surveys</description>
        <label>Survey Opt Out</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src.2/objects/Distribution_Group__c.object
<CustomObject>
    <label>Distribution Group</label>
    <nameField>
        <label>Distribution Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>CampaignId__c</fullName>
        <description>Create a Campaign Influence with this Campaign Id</description>
        <label>CampaignId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Ambassador__Short_Code__c</fullName>
        <label>Referring Short Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

src.1/objects/SR_Default_Values__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SR Default Values</label>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

src.1/classes/ContactsSelector.cls
public class ContactsSelector extends fflib_SObjectSelector 
{
	public Schema.SObjectField[] getSObjectFieldList() 
	{
		return new List<Schema.SObjectField> {
			Contact.Id,
			Contact.Ambassador__Short_Code__c,
			Contact.AccountId,
			Contact.Associated_Opp__c,
			Contact.Assign_to_Distribution_Group__c,
			Contact.Best_Day_to_Contact__c,
			Contact.Best_Time_to_Contact__c,
			Contact.CampaignId__c,
			Contact.Contact_Role__c,
			Contact.Contact_Role_Multi__c,
			Contact.Created_From_Lead_Convertion__c,
			Contact.Department,
			Contact.Distribution_Group__c,
			Contact.DistGroup__c,
			Contact.DoNotCall,
			Contact.Email,
			Contact.Fax,
			Contact.FirstName,
			Contact.HasOptedOutOfEmail,
			Contact.LastName,
			Contact.Lead__c,
			Contact.MailingStreet,
			Contact.MailingCity,
			Contact.MailingState,
			Contact.MailingStateCode,
			Contact.MailingPostalCode,
			Contact.MailingCountry,
			Contact.MailingCountryCode,
			Contact.MobilePhone,
			Contact.Name, 
			Contact.OwnerId,
			Contact.Phone,
			Contact.Powerstone__c,
			Contact.Primary_Contact__c,
			Contact.Purchase_Involvement__c,
			Contact.Survey_Opt_Out__c,
			Contact.Title 
			};
	}

	public Schema.SObjectType getSObjectType()
	{
		return Contact.SObjectType;
	}

	public static ContactsSelector newInstance()
	{
		return (ContactsSelector) Application.Selector.newInstance(Contact.SObjectType);
	}

	public Contact[] selectContactsByAccountId(Set<Id> acctIds)
	{
		fflib_QueryFactory contactQueryFactory = newQueryFactory();

		return Database.query(
			contactQueryFactory
			.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList()))
			.setCondition('AccountId IN :acctIds')
			.toSOQL());
	}

	public Contact[] selectByIdWithAccount(Set<Id> ids)
	{
		fflib_QueryFactory contactQueryFactory = newQueryFactory();

		new AccountsSelector().configureQueryFactoryFields(contactQueryFactory, 'Account');

		return Database.query(
			contactQueryFactory
			.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList()))
			.setCondition('Id IN :ids')
			.toSOQL());
	}

	public Contact[] selectByIdWithAccountAndTasks(Set<Id> ids)
	{
		fflib_QueryFactory contactQueryFactory = newQueryFactory();

		new AccountsSelector().configureQueryFactoryFields(contactQueryFactory, 'Account');

		fflib_QueryFactory taskQueryFactory = contactQueryFactory.subselectQuery('Tasks')
        	.selectFields(new TasksSelector().getSObjectFieldList());

		return Database.query(
			contactQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList())).setCondition('Id IN :ids').toSOQL());
	}

	public Database.QueryLocator queryLocatorPowerstoneContactsWithAccount()
	{
		SR_Default_Values__c defaultValues = SR_Default_Values__c.getValues('Opportunity Closed Lost Days');
		Integer cutOffDays = Integer.valueOf(defaultValues.Value__c);
		Datetime cutOff = Datetime.now().addDays(-cutOffDays);

		fflib_QueryFactory contactQueryFactory = newQueryFactory();

		new AccountsSelector().configureQueryFactoryFields(contactQueryFactory, 'Account');

		return Database.getQueryLocator(
			contactQueryFactory
				.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList()))
				.setCondition('Powerstone__c = true AND Account.Last_ROE_Date__c != null AND Account.Last_ROE_Date__c > :cutOff')
				.toSOQL());
	}

	public Map<Id, Contact> selectContactsWithAccountsByTask(Task[] tasks)
	{
		Set<Id> ids = new Set<Id>();

		for(Task t : tasks)
		{
			if(t.WhoId != null && t.WhoId.getSObjectType().getDescribe().getName() == 'Contact') ids.add(t.WhoId);
		}

		fflib_QueryFactory contactQueryFactory = newQueryFactory();

		new AccountsSelector().configureQueryFactoryFields(contactQueryFactory, 'Account');

		return new Map<Id, Contact>((Contact[]) Database.query(
			contactQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList())).setCondition('id IN :ids').toSOQL()));
	}

	public Contact[] selectByOpportunityContactRoles(OpportunityContactRole[] ocrs)
	{
		Set<Id> ids = new Set<Id>();

		for(OpportunityContactRole ocr : ocrs)
		{
			ids.add(ocr.ContactId);
		}

		fflib_QueryFactory contactQueryFactory = newQueryFactory();

		return Database.query(
			contactQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList())).setCondition('id IN :ids').toSOQL());
	}
}