src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.2/objects/AsyncRequest__c.object
<CustomObject>
    <description>Used for logging Async requests to be processed.</description>
    <label>AsyncRequest</label>
    <nameField>
        <displayFormat>ASYNC-{0000000}</displayFormat>
        <label>AsyncRequest Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AsyncRequests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>AsyncType__c</fullName>
        <label>AsyncType</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AppAdmin_AssetSync</fullName>
                </value>
                <value>
                    <fullName>AppAdmin_HGSync</fullName>
                </value>
                <value>
                    <fullName>AppAdmin_OppSync</fullName>
                </value>
                <value>
                    <fullName>Contract_Email</fullName>
                </value>
                <value>
                    <fullName>Process_Dist_Group</fullName>
                </value>
                <value>
                    <fullName>ProdSub_AfterInsert</fullName>
                </value>
                <value>
                    <fullName>Set_DQ_Delete_CI</fullName>
                </value>
                <value>
                    <fullName>Task_ADR_CI</fullName>
                </value>
                <value>
                    <fullName>Update_Opp_Stage_Demo_Completed</fullName>
                </value>
                <value>
                    <fullName>Update_Opp_Stage_Demo_Scheduled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Attachment_Id__c</fullName>
        <description>Used for storing the Attachment ID for the PDF contract</description>
        <label>Attachment Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error__c</fullName>
        <label>Error</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Number_of_Attempts__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Attempts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Params__c</fullName>
        <label>Params</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <defaultValue>2</defaultValue>
        <label>Priority</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RequestedEmail__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for the contract process email. Customers can choose to not receive the email.</description>
        <label>RequestedEmail</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/default/objects/AsyncRequestEvent__e/AsyncRequestEvent__e.object-meta.xml
<CustomObject>
    <label>AsyncRequestEvent</label>
    <pluralLabel>AsyncRequestEvents</pluralLabel>
</CustomObject>

src.4/objects/Campaign_Influence__c.object
<CustomObject>
    <label>Campaign Influence</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Influence</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src.1/objects/Error_Log__c.object
<CustomObject>
    <description>Object will store all Contract process error&#39;s and App Admin API errors.</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{0000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>For error messages longer than 255 characters including HTML markup</description>
        <label>Error Message</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Error_Type__c</fullName>
        <description>Contract Review Page,PayPal or AppAdmin</description>
        <label>Error Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error__c</fullName>
        <label>Error</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

src.3/classes/AsyncMain.cls
global class AsyncMain implements Database.Batchable<sObject>, Database.AllowsCallouts 
{	
	global static final String TYPE_ACCOUNT_BILLING_EMAIL = 'Account_Billing_Email';
	global static final String TYPE_ACTIVATION_CASE = 'Activation_Case';
	global static final String TYPE_ADR_TASK_REVENUE = 'ADR_Task_Revenue';
	global static final String TYPE_APPADMIN_ASSETSYNC = 'AppAdmin_AssetSync';
	global static final String TYPE_APPADMIN_HGSYNC = 'AppAdmin_HGSync';
	global static final String TYPE_APPADMIN_OPPSYNC = 'AppAdmin_OppSync';
	global static final String TYPE_CLOSE_ADDENDUM = 'Close_Addendum';
	global static final String TYPE_CONTRACT_EMAIL = 'Contract_Email';
	global static final String TYPE_CREATE_ASSET = 'Create_Asset';
	global static final String TYPE_CREATE_CI = 'Create_CI';
	global static final String TYPE_DEMO_REQUEST_REASON = 'Demo_Request_Reason';
	global static final String TYPE_LINK_OPP_CI = 'Link_Opp_CI';
	global static final String TYPE_PROCESS_DIST_GROUP = 'Process_Dist_Group';
	global static final String TYPE_CASE_PROCESS_DIST_GROUP = 'Case_Process_Dist_Group';
	global static final String TYPE_PRODSUB_AFTERINSERT = 'ProdSub_AfterInsert';
	global static final String TYPE_PRODUCT_TERMS_ROLLUP = 'Product_Terms_Rollup';
	global static final String TYPE_RESET_APPROVALS = 'Reset_Approvals';
	global static final String TYPE_SET_APPROVALS = 'Set_Approvals';
	global static final String TYPE_STAMP_UPDATES = 'Stamp_Updates';
	global static final String TYPE_SYNC_RECORD_OWNERS = 'Sync_Owners';
	global static final String TYPE_AMBASSADOR_CREATE = 'Ambassador_Create';
	global static final String TYPE_AMBASSADOR_COMPLETE = 'Ambassador_Complete';
	global static final String TYPE_USER_LIMITS = 'User_Limits';
	private static Boolean batchRequested = false;
	private static Boolean schedulerRequested = false;

	global Database.Querylocator Start(Database.BatchableContext bc) 
	{
		return Database.getQueryLocator('SELECT Id, CreatedDate, AsyncType__c, Params__c, Number_of_Attempts__c, Error__c, Attachment_Id__c, RequestedEmail__c ' +
			'FROM AsyncRequest__c WHERE Number_of_Attempts__c <= 5 ORDER BY Priority__c, Number_of_Attempts__c LIMIT 50');
	}

	global void Execute(Database.BatchableContext BC, AsyncRequest__c[] scope) 
	{
		Map<Id, SObject> mapInsertSObject = new Map<Id, SObject>();
      	Map<Id, SObject> mapUpdateSObject = new Map<Id, SObject>();
      	Map<Id, SObject> mapDeleteSObject = new Map<Id, SObject>();
      	fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
      	SRUtilities.SRUnitOfWork sruow = new SRUtilities.SRUnitOfWork();
      	Map<AsyncRequest__c, Exception> errorMap = new Map<AsyncRequest__c, Exception>();

		for(AsyncRequest__c ar: scope) 
		{
			if(ar.Number_of_Attempts__c > 5) continue;

			try
			{
				if(ar.AsyncType__c == TYPE_ACCOUNT_BILLING_EMAIL)
				{
					Id[] idsToProcess = ar.Params__c.split(',');
					OpportunitiesService.setAccountBillingEmailFromBillToContact(new Set<Id>(idsToProcess), uow);
					uow.commitWork();
					mapDeleteSObject.put(ar.Id, ar);	
				}

				if(ar.AsyncType__c == TYPE_ACTIVATION_CASE)
				{
					Id[] idsToProcess = ar.Params__c.split(',');
					OpportunitiesService.newActivationCase(new Set<Id>(idsToProcess), uow);
					uow.commitWork();
					mapDeleteSObject.put(ar.Id, ar);	
				}

				if(ar.AsyncType__c == TYPE_ADR_TASK_REVENUE)
				{
					Id[] idsToProcess = ar.Params__c.split(',');
					OpportunitiesService.addRevenueToADRSetTask(new Set<Id>(idsToProcess), uow);
					uow.commitWork();
					mapDeleteSObject.put(ar.Id, ar);	
				}

				if(ar.AsyncType__c == TYPE_APPADMIN_ASSETSYNC) 
				{
					Id[] idsToProcess = ar.Params__c.split(',');
					AppAdminAPIClass.postAssetStatus(new Set<Id>(idsToProcess));
					mapDeleteSObject.put(ar.Id, ar);
				} 

				if(ar.AsyncType__c == TYPE_APPADMIN_HGSYNC) 
				{
					Id[] idsToProcess = ar.Params__c.split(',');
					AppAdminAPIClass.postHealthgradesStatus(new Set<Id>(idsToProcess));
					mapDeleteSObject.put(ar.Id, ar);
				}

				if(ar.AsyncType__c == TYPE_APPADMIN_OPPSYNC) 
				{
					Id[] idsToProcess = ar.Params__c.split(',');
					AppAdminAPIClass.syncOpportunityAppAdmin(new Set<Id>(idsToProcess));
					mapDeleteSObject.put(ar.Id, ar);
				} 

				if(ar.AsyncType__c == TYPE_CLOSE_ADDENDUM)
				{
					Id[] idsToProcess = ar.Params__c.split(',');
					OpportunitiesService.closeAddendum(new Set<Id>(idsToProcess), uow);
					uow.commitWork();
					mapDeleteSObject.put(ar.Id, ar);	
				}

				if(ar.AsyncType__c == TYPE_CONTRACT_EMAIL)
				{
					OpportunitiesService.sendContractEmail(ar);
					mapDeleteSObject.put(ar.Id, ar);	
				}

				if(ar.AsyncType__c == TYPE_CREATE_ASSET)
				{
					Id[] idsToProcess = ar.Params__c.split(',');
					OpportunitiesService.createAssetForClosedOpps(new Set<Id>(idsToProcess), uow);
					uow.commitWork();
					mapDeleteSObject.put(ar.Id, ar);	
				}

				if(ar.AsyncType__c == TYPE_CREATE_CI)
				{
					Map<Id, Id> idToCampaignId = new Map<Id, Id>();
					Map<Id, Id> idToUserId = new Map<Id, Id>();
					String[] idsToProcess = ar.Params__c.split(',');
					for(String s : idsToProcess)
					{
						String[] split = s.split('::');
						String[] split1 = split[1].split(':');
						idToCampaignId.put(split[0], split1[0]);
						if(split1.size() > 1) idToUserId.put(split[0], split1[1]);
					}

					if(new List<Id>(idToCampaignId.keySet())[0].getSObjectType().getDescribe().getName() == 'Contact') CampaignInfluencesService.createCIs(idToCampaignId, idToUserId, ar, uow);
					if(new List<Id>(idToCampaignId.keySet())[0].getSObjectType().getDescribe().getName() == 'Opportunity') CampaignInfluencesService.createCIsFromOpps(idToCampaignId, idToUserId, ar, uow);

					uow.commitWork();
					mapDeleteSObject.put(ar.Id, ar);	
				} 	

				if(ar.AsyncType__c == TYPE_LINK_OPP_CI) 
				{
					Id[] idsToProcess = ar.Params__c.split(',');
					CampaignInfluencesService.linkOppOnCIs(new Set<Id>(idsToProcess), uow);
					uow.commitWork();
					mapDeleteSObject.put(ar.Id, ar);
				} 

				if(ar.AsyncType__c == TYPE_PROCESS_DIST_GROUP)
				{
					Map<Id, Id> idToDistGroupId = new Map<Id, Id>();
					Map<Id, Id> idToUserId = new Map<Id, Id>();
					String[] idsToProcess = ar.Params__c.split(',');
					for(String s : idsToProcess)
					{
						String[] split = s.split('::');
						String[] split1 = split[1].split(':');
						idToDistGroupId.put(split[0], split1[0]);
						if(split1.size() > 1) idToUserId.put(split[0], split1[1]);
					}

					ContactsService.processDistributionGroup(idToDistGroupId, idToUserId, uow);
					uow.commitWork();
					mapDeleteSObject.put(ar.Id, ar);	
				}

				if(ar.AsyncType__c == TYPE_CASE_PROCESS_DIST_GROUP)
				{
					Map<Id, Id> idToDistGroupId = new Map<Id, Id>();
					Map<Id, Id> idToUserId = new Map<Id, Id>();
					String[] idsToProcess = ar.Params__c.split(',');
					for(String s : idsToProcess)
					{
						String[] split = s.split('::');
						String[] split1 = split[1].split(':');
						idToDistGroupId.put(split[0], split1[0]);
						if(split1.size() > 1) idToUserId.put(split[0], split1[1]);
					}

					CasesService.processDistributionGroup(idToDistGroupId, uow);
					uow.commitWork();
					mapDeleteSObject.put(ar.Id, ar);
				} 

				if(ar.AsyncType__c == TYPE_PRODSUB_AFTERINSERT) 
				{
					Id[] idsToProcess = ar.Params__c.split(',');
					Set<Id> ids = new Set<Id>(idsToProcess);
					ProductSubscriptionsService.processRevSchedules(ids, uow, sruow);
					ProductSubscriptionsService.syncSubscriptionWithAsset(ids, uow, sruow);
					uow.registerWork(sruow);
					uow.commitWork();
					mapDeleteSObject.put(ar.Id, ar);	
				}

				if(ar.AsyncType__c == TYPE_DEMO_REQUEST_REASON) 
				{
					Id[] idsToProcess = ar.Params__c.split(',');
					CampaignInfluencesService.setDemoRequestReason(new Set<Id>(idsToProcess), uow);
					uow.commitWork();
					mapDeleteSObject.put(ar.Id, ar);
				} 

				if(ar.AsyncType__c == TYPE_PRODUCT_TERMS_ROLLUP) 
				{
					Id[] idsToProcess = ar.Params__c.split(',');
					OpportunityLineItemsService.updateProductTermsRollup(new Set<Id>(idsToProcess), uow);
					uow.commitWork();
					mapDeleteSObject.put(ar.Id, ar);
				} 

				if(ar.AsyncType__c == TYPE_RESET_APPROVALS) 
				{
					Id[] idsToProcess = ar.Params__c.split(',');
					OpportunityLineItemsService.resetApprovals(new Set<Id>(idsToProcess), uow);
					uow.commitWork();
					mapDeleteSObject.put(ar.Id, ar);
				} 

				if(ar.AsyncType__c == TYPE_SET_APPROVALS) 
				{
					Id[] idsToProcess = ar.Params__c.split(',');
					OpportunityLineItemsService.setApprovals(new Set<Id>(idsToProcess), uow);
					uow.commitWork();
					mapDeleteSObject.put(ar.Id, ar);
				} 

				if(ar.AsyncType__c == TYPE_STAMP_UPDATES)
				{
					SObject[] objectList;
					Map<Id, Set<String>> idToStampIds = new Map<Id, Set<String>>();
					String[] idsToProcess = ar.Params__c.split(',');
					for(String s : idsToProcess)
					{
						String[] split = s.split('::');
						String[] split1 = split[1].split(':');
						idToStampIds.put(split[0], new Set<String>(split1));
					}

					if(new List<Id>(idToStampIds.keySet())[0].getSObjectType().getDescribe().getName() == 'Account')
					{
						objectList = AccountsSelector.newInstance().selectByIdWithManagerAndVP(idToStampIds.keySet());
					}

					if(new List<Id>(idToStampIds.keySet())[0].getSObjectType().getDescribe().getName() == 'Opportunity')
					{
						objectList = OpportunitiesSelector.newInstance().selectByIdWithManagerAndVP(idToStampIds.keySet());
					}

					if(new List<Id>(idToStampIds.keySet())[0].getSObjectType().getDescribe().getName() == 'Campaign_Influence__c')
					{
						objectList = CampaignInfluencesSelector.newInstance().selectByIdWithManagerAndVP(idToStampIds.keySet());
					}

					if(objectList != null) SRUtilities.processStampUpdates(idToStampIds, objectList, uow);

					uow.commitWork();
					mapDeleteSObject.put(ar.Id, ar);	
				} 	

				if(ar.AsyncType__c == TYPE_SYNC_RECORD_OWNERS)
				{
					Map<Id, Id> accountIdToOwnerId = new Map<Id, Id>();
					String[] idsToProcess = ar.Params__c.split(',');
					for(String s : idsToProcess)
					{
						String[] split = s.split(':');
						accountIdToOwnerId.put(split[0], split[1]);
					}					
					AccountsService.syncRecordOwners(accountIdToOwnerId, uow);
					uow.commitWork();                   
					mapDeleteSObject.put(ar.Id, ar);	
				} 

				if(ar.AsyncType__c == TYPE_AMBASSADOR_CREATE)
				{
					Id[] idsToProcess = ar.Params__c.split(',');
					OpportunitiesService.createAmbassadorCommission(new Set<Id>(idsToProcess), uow);
					uow.commitWork();
					mapDeleteSObject.put(ar.Id, ar);
				} 

				if(ar.AsyncType__c == TYPE_AMBASSADOR_COMPLETE)
				{
					Id[] idsToProcess = ar.Params__c.split(',');
					OpportunitiesService.completeAmbassadorCommission(new Set<Id>(idsToProcess), uow);
					uow.commitWork();
					mapDeleteSObject.put(ar.Id, ar);
				} 

				if(ar.AsyncType__c == TYPE_USER_LIMITS)
				{
					Id[] idsToProcess = ar.Params__c.split(',');
					UsersService.updateUserLimits(new Set<Id>(idsToProcess), uow);
					uow.commitWork();
					mapDeleteSObject.put(ar.Id, ar);
				} 
			}
			
			catch(Exception e) 
			{
				errorMap.put(ar, e);
			}
		}

		if(errorMap.size() > 0)
		{
			fflib_SObjectUnitOfWork uow1 = Application.UnitOfWork.newInstance();

			for(AsyncRequest__c ar : errorMap.keySet())
			{
				Exception e = errorMap.get(ar);
				ar.Number_of_Attempts__c += 1;
				ar.Error__c = e.getMessage() + ' Line Number: ' + e.getLineNumber() + ' Stack Trace: ' + e.getStackTraceString();
				uow1.registerDirty(ar);
			}

			uow1.commitWork();
		}

		SRUtilities.runDml(mapInsertSObject, mapUpdateSObject, mapDeleteSObject, 'AsyncMain.Execute');
		if(mapDeleteSObject.size() > 0) Database.emptyRecycleBin(mapDeleteSObject.values());
	}

	global void Finish(Database.BatchableContext BC) 
	{
		AsyncRequest__c[] ars = [SELECT Id, Number_of_Attempts__c FROM AsyncRequest__c WHERE Number_of_Attempts__c <= 5 LIMIT 1];
		
		if(ars.size() > 0 && !Test.isRunningTest()) 
		{
			AsyncRequestEvent__e asyncRequestEvent = new AsyncRequestEvent__e();
			Database.SaveResult sr = EventBus.publish(asyncRequestEvent);

			if(!sr.isSuccess())
			{
				for(Database.Error err : sr.getErrors())
				{
					Error_Log__c log = new Error_Log__c(
			            Error_Message__c = 'Status Code: ' + err.getStatusCode() + '\nMessage: ' + err.getMessage() + '\nFields: ' + err.getFields(),
			            Error_Type__c = 'AsyncRequestEvent Error');
					insert log;
				}
			}
		}
	}

	public class ScheduleHandler implements ScheduledDispatcher.IScheduleDispatched 
	{
        public void execute(SchedulableContext sc) 
        {
        	startBatch();
            System.abortJob(sc.getTriggerID());	// Always abort the job on completion
        } 
    }

	public static void startBatch() 
	{
		if(batchRequested) return;
		if(isAsyncMainRunning()) return;
		AsyncMain am = new AsyncMain();
		Database.executeBatch(am, 1);
		batchRequested = true;
	}
        
    public static void startScheduler() 
    {
    	if(schedulerRequested) return;
        
        // Is the job already running?
        CronTrigger[] jobs = [SELECT Id, 
        	CronJobDetail.Name, 
        	State, 
        	NextFireTime 
        	FROM CronTrigger 
        	WHERE CronJobDetail.Name LIKE 'AsyncMain_Job%'];

    	if(jobs.size() > 0 && 
    		jobs[0].State != 'COMPLETED' && 
    		jobs[0].State != 'ERROR' && 
    		jobs[0].State != 'DELETED') 
    	{
            // It's already running - Is the batch running?
            if(isAsyncMainRunning()) return;  // The batch is running
            
            if(Datetime.now().addSeconds(60) > jobs[0].NextFireTime) return;  // If we're going to run soon, exit 
        }

        // If the job exists, it needs to be deleted
        if(jobs.size() > 0) System.abortJob(jobs[0].id);

        try 
        {
	        System.schedule('AsyncMain_Job' + Datetime.now().getTime(), 
	                        getSchedulerExpression(Datetime.now().addSeconds(10)), 
	                        new ScheduledDispatcher());

	        schedulerRequested = true;
        } 

        catch(Exception ex)
        {

        }
    }

    public static Boolean isAsyncMainRunning()
    {
    	Boolean results = false;
    	Set<String> activeJobStates = new Set<String>{'Holding','Queued','Processing','Preparing'};
        List<AsyncApexJob> apexJobs = [SELECT Id, 
        	ApexClass.Name 
        	FROM AsyncApexJob 
        	WHERE ApexClass.Name = 'AsyncMain' 
        	AND Status IN :activeJobStates];

		if(apexJobs.size() > 0) results = true;
		return results; 
    }

    public static String getSchedulerExpression(Datetime dt) 
    {
        return ('' + dt.second() + ' ' + dt.minute() + ' ' + dt.hour() + ' ' + dt.day() + ' ' + dt.month() + ' ? ' + dt.year());
    }
}