src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Number_of_Locations__c</fullName>
        <label>Number of Locations</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0-9</fullName>
                </value>
                <value>
                    <fullName>10-49</fullName>
                </value>
                <value>
                    <fullName>50-100</fullName>
                </value>
                <value>
                    <fullName>100+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Providers__c</fullName>
        <label>Number of Providers</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0-10</fullName>
                </value>
                <value>
                    <fullName>11-29</fullName>
                </value>
                <value>
                    <fullName>30-49</fullName>
                </value>
                <value>
                    <fullName>50+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>rrpu__Alert_Message__c</fullName>
        <description>This field is installed by Riptide Pop-up Alerts and is used in conjunction with the Pop-up Alert S-Control.</description>
        <inlineHelpText>If you enter text into this field the text will be displayed in a pop-up message whenever someone views this record.</inlineHelpText>
        <label>Alert Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sub_Vertical__c</fullName>
        <label>Sub-Vertical</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Allergy &amp; Immunology</fullName>
                </value>
                <value>
                    <fullName>Bariatric, Metabolic and Weight Health</fullName>
                </value>
                <value>
                    <fullName>Chiropractic</fullName>
                </value>
                <value>
                    <fullName>Cosmetic Surgery</fullName>
                </value>
                <value>
                    <fullName>Dermatology</fullName>
                </value>
                <value>
                    <fullName>Endocrinology</fullName>
                </value>
                <value>
                    <fullName>Endodontistry</fullName>
                </value>
                <value>
                    <fullName>ENT-Otolaryngology</fullName>
                </value>
                <value>
                    <fullName>Family Medicine or General Physician</fullName>
                </value>
                <value>
                    <fullName>Gastroenterology</fullName>
                </value>
                <value>
                    <fullName>General Dentistry</fullName>
                </value>
                <value>
                    <fullName>General Surgery</fullName>
                </value>
                <value>
                    <fullName>Geriatric Medicine</fullName>
                </value>
                <value>
                    <fullName>Heart and Vascular</fullName>
                </value>
                <value>
                    <fullName>HIV/Infectious Disease</fullName>
                </value>
                <value>
                    <fullName>Internal Medicine</fullName>
                </value>
                <value>
                    <fullName>Medical Spa or Aesthetic Medicine</fullName>
                </value>
                <value>
                    <fullName>Neurology</fullName>
                </value>
                <value>
                    <fullName>Non-medical</fullName>
                </value>
                <value>
                    <fullName>OB/GYN or Womens Health</fullName>
                </value>
                <value>
                    <fullName>Oncology</fullName>
                </value>
                <value>
                    <fullName>Ophthalmology</fullName>
                </value>
                <value>
                    <fullName>Optometry</fullName>
                </value>
                <value>
                    <fullName>Oral Surgery</fullName>
                </value>
                <value>
                    <fullName>Orthodontistry</fullName>
                </value>
                <value>
                    <fullName>Orthopedics</fullName>
                </value>
                <value>
                    <fullName>Orthotics/Prosthetics</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pain Management or Physical Medicine or Physiatry</fullName>
                </value>
                <value>
                    <fullName>Pediatrics</fullName>
                </value>
                <value>
                    <fullName>Dental</fullName>
                    <isActive>false</isActive>
                    <label>Dental</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.1/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>CampaignId__c</fullName>
        <description>Populated by HubSpot to create a CampaignMember for the Id specified.</description>
        <label>CampaignId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DistGroup__c</fullName>
        <description>Set by HubSpot and used in Apex to set the matching Distribution Group.</description>
        <label>DistGroup</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distribution Group</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This Distribution Group does not currently available to be used.</errorMessage>
            <filterItems>
                <field>Distribution_Group__c.HasNextUser__c</field>
                <operation>equals</operation>
                <value>1</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Distribution_Group__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Locations__c</fullName>
        <label>Number of Locations</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1-5</fullName>
                </value>
                <value>
                    <fullName>6-24</fullName>
                </value>
                <value>
                    <fullName>25-100</fullName>
                </value>
                <value>
                    <fullName>100+</fullName>
                </value>
                <value>
                    <fullName>1-4</fullName>
                </value>
                <value>
                    <fullName>5-24</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Providers__c</fullName>
        <label>Number of Providers</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1-50</fullName>
                </value>
                <value>
                    <fullName>51-100</fullName>
                </value>
                <value>
                    <fullName>101-300</fullName>
                </value>
                <value>
                    <fullName>300+</fullName>
                </value>
                <value>
                    <fullName>1-20</fullName>
                </value>
                <value>
                    <fullName>21-124</fullName>
                </value>
                <value>
                    <fullName>125+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>rrpu__Alert_Message__c</fullName>
        <description>This field is installed by Riptide Pop-up Alerts and is used in conjunction with the Pop-up Alert S-Control.</description>
        <inlineHelpText>If you enter text into this field the text will be displayed in a pop-up message whenever someone views this record.</inlineHelpText>
        <label>Alert Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sub_Vertical__c</fullName>
        <description>Used for new Contacts coming from HubSpot to create new Account. Updated via Parent/Child Mapping in Apex</description>
        <label>Sub-Vertical</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Dermatology</fullName>
                </value>
                <value>
                    <fullName>Ophthalmology</fullName>
                </value>
                <value>
                    <fullName>Cosmetic Surgery</fullName>
                </value>
                <value>
                    <fullName>Family Medicine or General Physician</fullName>
                </value>
                <value>
                    <fullName>Pediatrics</fullName>
                </value>
                <value>
                    <fullName>OB/GYN or Womens Health</fullName>
                </value>
                <value>
                    <fullName>Allergy &amp; Immunology</fullName>
                </value>
                <value>
                    <fullName>ENT-Otolaryngology</fullName>
                </value>
                <value>
                    <fullName>Gastroenterology</fullName>
                </value>
                <value>
                    <fullName>Orthopedics</fullName>
                </value>
                <value>
                    <fullName>Bariatric, Metabolic and Weight Health</fullName>
                </value>
                <value>
                    <fullName>Endocrinology</fullName>
                </value>
                <value>
                    <fullName>Geriatric Medicine</fullName>
                </value>
                <value>
                    <fullName>Heart and Vascular</fullName>
                </value>
                <value>
                    <fullName>HIV/Infectious Disease</fullName>
                </value>
                <value>
                    <fullName>Internal Medicine</fullName>
                </value>
                <value>
                    <fullName>Medical Spa or Aesthetic Medicine</fullName>
                </value>
                <value>
                    <fullName>Neurology</fullName>
                </value>
                <value>
                    <fullName>General Surgery</fullName>
                </value>
                <value>
                    <fullName>Oncology</fullName>
                </value>
                <value>
                    <fullName>Pain Management or Physical Medicine or Physiatry</fullName>
                </value>
                <value>
                    <fullName>Podiatry</fullName>
                </value>
                <value>
                    <fullName>Psychiatry or Mental Health or Substance Rehabilitation</fullName>
                </value>
                <value>
                    <fullName>Radiology or Imaging</fullName>
                </value>
                <value>
                    <fullName>Urology</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>General Dentistry</fullName>
                </value>
                <value>
                    <fullName>Orthodontistry</fullName>
                </value>
                <value>
                    <fullName>Endodontistry</fullName>
                </value>
                <value>
                    <fullName>Pedodontistry</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vertical__c</fullName>
        <description>Used for new Contacts coming from HubSpot to create new Account. Updated via Parent/Child Mapping in Apex.</description>
        <label>Vertical</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Dental</fullName>
                </value>
                <value>
                    <fullName>Vision</fullName>
                </value>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Non-Medical</fullName>
                </value>
                <value>
                    <fullName>Physical Rehabilitation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/Contact/fields/Demo_Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Demo_Scheduled_Date__c</fullName>
    <description>When this field is set, a Demo Scheduled task is created at this date/time via Apex.  The task will be owned by the user setting the field and will be reassigned if sent to a Distribution Group.</description>
    <label>Demo Scheduled Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Demo_Scheduled_Date_Text__c.field-meta.xml
<CustomField>
    <fullName>Demo_Scheduled_Date_Text__c</fullName>
    <description>HubSpot is unable to sync a Datetime type field.  A UTC datetime string will be synced to this field and then converted to datetime for Demo_Scheduled_Date__c.</description>
    <label>Demo Scheduled Date Text</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src.2/objects/Distribution_Group__c.object
<CustomObject>
    <label>Distribution Group</label>
    <nameField>
        <label>Distribution Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>CampaignId__c</fullName>
        <description>Create a Campaign Influence with this Campaign Id</description>
        <label>CampaignId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

src.1/objects/SR_Default_Values__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SR Default Values</label>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

src.2/classes/Contacts.cls
public class Contacts extends fflib_SObjectDomain 
{
    public Set<String> contactsDistGroup;
    public Set<String> createCI;
    public Set<Id> clearDemoTaskDate;

    public Contacts(Contact[] contacts) 
    {
        super(contacts);    
        Configuration.disableTriggerCRUDSecurity();
    }

    public class Constructor implements fflib_SObjectDomain.IConstructable
    {
        public fflib_SObjectDomain construct(List<SObject> sObjectList)
        {
            return new Contacts(sObjectList);
        }
    }

    public override void onBeforeInsert()
    {
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        for(Contact c : (Contact[]) Records) 
        {
            this.validateCountryByAreaCode(c, null);
            this.createNewAccount(c, uow);
        }

        uow.commitWork();
    }

    public override void onAfterInsert()
    {
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        for(Contact c : (Contact[]) Records) 
        {
            this.createCampaignInfluence(c, null);
            this.processDistributionGroup(c, null);
            this.createDemoTask(c, null, uow);
        }

        if(contactsDistGroup != null && 
            !contactsDistGroup.isEmpty()) SRUtilities.scheduleAsync(contactsDistGroup, 'Process_Dist_Group', uow);

        if(createCI != null && 
            !createCI.isEmpty()) SRUtilities.scheduleAsync(createCI, 'Create_CI', uow);
        
        if(clearDemoTaskDate != null && 
            !clearDemoTaskDate.isEmpty()) ContactsService.clearDemoTaskDate(clearDemoTaskDate);

        uow.commitWork();
    }

    public override void onBeforeUpdate(Map<Id, SObject> existingRecords)
    {
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        for(Contact c : (Contact[]) Records) 
        {
            Contact existingContact = (Contact) existingRecords.get(c.Id);

            this.validateContactOwnerChange(c, existingContact);
            this.validateCountryByAreaCode(c, existingContact);
            this.createNewAccount(c, uow);
            this.createDemoTask(c, existingContact, uow);
            this.createCampaignInfluence(c, existingContact);
            this.processDistributionGroup(c, existingContact);
        }

        if(contactsDistGroup != null && 
            !contactsDistGroup.isEmpty()) SRUtilities.scheduleAsync(contactsDistGroup, 'Process_Dist_Group', uow);

        if(createCI != null && 
            !createCI.isEmpty()) SRUtilities.scheduleAsync(createCI, 'Create_CI', uow);

        uow.commitWork();
    }

    public void createCampaignInfluence(Contact c, Contact existingContact)
    {
        if(c.CampaignId__c == null) return;
        if(existingContact != null &&
            existingContact.CampaignId__c == c.CampaignId__c) return;

        Id campaignId = c.CampaignId__c InstanceOf Id ? c.CampaignId__c : null;
        if(createCI == null) createCI = new Set<String>();
        if(campaignId != null) createCI.add(c.Id + '::' + campaignId + ':' + UserInfo.getUserId());
    }

    public void createNewAccount(Contact c, fflib_SObjectUnitOfWork uow)
    {
        if(c.AccountId != null) return;

        Account account = new Account(Name = c.FirstName + ' ' + c.LastName,
            RecordTypeId = SRUtilities.getRecordTypeMap('Account').get('Account').getRecordTypeId(),
            Phone = c.Phone,
            BillingStreet = c.MailingStreet,
            BillingCity = c.MailingCity,
            //BillingState = c.MailingState, removed because it was failing validations
            BillingPostalCode = c.MailingPostalCode,
            BillingCountry = c.MailingCountry,
            Description = 'Account Auto-Created',
            Industry = c.Vertical__c == null ? 'Dental' : c.Vertical__c,
            //Sub_Vertical__c = c.Sub_Vertical__c == null ? null : c.Sub_Vertical__c, removed because it was failing validations
            Number_of_Locations__c = c.Number_of_Locations__c,
            Number_of_Providers__c = c.Number_of_Providers__c);
        uow.registerNew(account);
        uow.registerRelationship(c, Schema.Contact.AccountId, account);
    }

    public void createDemoTask(Contact c, Contact existingContact, fflib_SObjectUnitOfWork uow)
    {
        if(existingContact != null &&
            existingContact.Demo_Scheduled_Date_Text__c == c.Demo_Scheduled_Date_Text__c &&
            existingContact.Demo_Scheduled_Date__c == c.Demo_Scheduled_Date__c) return;
        if(c.Demo_Scheduled_Date__c == null &&
            c.Demo_Scheduled_Date_Text__c == null) return;

        //Boolean is workaround for Datetime parse not working correctly
        Boolean isText = c.Demo_Scheduled_Date_Text__c == null ? false : true;
        String subject = isText ? Datetime.valueOfGmt(c.Demo_Scheduled_Date_Text__c).format('MM/dd/yyyy h:mm a','America/Denver') : c.Demo_Scheduled_Date__c.format('MM/dd/yyyy h:mm a','America/Denver');

        Task t = new Task(Subject = 'Demo Scheduled with ' + c.FirstName + ' - ' + subject,
            ADR_Set__c = true,
            ActivityDate = Date.valueOf(isText ? Datetime.valueOfGmt(c.Demo_Scheduled_Date_Text__c) : c.Demo_Scheduled_Date__c),
            Activity_Type__c = 'Phone Demo',
            Activity_Results__c = 'Future Event',
            Status = 'Scheduled',
            Due_Time__c = isText ? Datetime.valueOfGmt(c.Demo_Scheduled_Date_Text__c) : c.Demo_Scheduled_Date__c,
            WhoId = c.Id,
            WhatId = c.AccountId);
        uow.registerNew(t);
    }

    public void processDistributionGroup(Contact c, Contact existingContact)
    {
        if(c.DistGroup__c == null && c.Distribution_Group__c == null) return;
        if(existingContact != null &&
            existingContact.DistGroup__c == c.DistGroup__c && 
            existingContact.Distribution_Group__c == c.Distribution_Group__c) return;

        Id distGroupId = c.Distribution_Group__c != null ? c.Distribution_Group__c : c.DistGroup__c InstanceOf Id ? c.DistGroup__c : null;
        if(contactsDistGroup == null) contactsDistGroup = new Set<String>(); 
        if(distGroupId != null) contactsDistGroup.add(c.Id + '::' + distGroupId + ':' + UserInfo.getUserId());
    }

    public void validateCountryByAreaCode(Contact c, Contact existingContact)
    {
        if(existingContact != null &&
            existingContact.Phone == c.Phone && 
            existingContact.MailingCountryCode == c.MailingCountryCode) return;

        AreaCodes areaCodes = new AreaCodes();
        String msg = 'The phone area code does not belong to the selected country. Please confirm that this is correct.';

        Boolean requiresValidation = areaCodes.validateCountryByAreaCode(c.Phone, c.MailingCountryCode);

        if(requiresValidation)
        {
            c.rrpu__Alert_Message__c = c.rrpu__Alert_Message__c != null && !c.rrpu__Alert_Message__c.contains(msg) ? 
                c.rrpu__Alert_Message__c + '\n' + msg : 
                c.rrpu__Alert_Message__c == null ?
                    msg : c.rrpu__Alert_Message__c;
        }
        else
        {
            c.rrpu__Alert_Message__c = c.rrpu__Alert_Message__c != null && c.rrpu__Alert_Message__c.contains(msg) ? 
                c.rrpu__Alert_Message__c.replace(msg,'') : c.rrpu__Alert_Message__c;
        }
    }

    public void validateContactOwnerChange(Contact c, Contact existingContact)
    {
        if(System.isBatch()) return;
        if(existingContact == null) return;
        if(existingContact.OwnerId == c.OwnerId ||
                existingContact.OwnerId == SR_Default_Values__c.getInstance('jennyPoolUserId').Value__c) return;

        if (SR_Default_Values__c.getInstance('noStealingProfiles').Value__c.contains(String.valueOf(UserInfo.getProfileId()) ) )
            c.addError(SR_Default_Values__c.getInstance('contactChangeOwnerErrorMessage').Value__c);
    }
}