src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>RecurSoft__Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Default Bill to Contact for usage billing.</inlineHelpText>
        <label>Bill to Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>$Source.RecurSoft__Bill_to_Account__c</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.RecurSoft__Bill_to_Account__c</field>
                <operation>equals</operation>
                <value/>
            </filterItems>
            <infoMessage>Contact should have current account.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>RecurSoft_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Bill_to_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Default Bill to Account for usage billing.</inlineHelpText>
        <label>Bill to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Bill to Account)</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Shipping_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Default Ship to Contact for usage billing.</inlineHelpText>
        <label>Ship to Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>$Source.RecurSoft__Bill_to_Account__c</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.RecurSoft__Bill_to_Account__c</field>
                <operation>equals</operation>
                <value/>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (Ship to Contact)</relationshipLabel>
        <relationshipName>RecurSoft_Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscriber_ID__c</fullName>
        <description>The subscriber ID from App Admin</description>
        <label>Subscriber ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>RecurSoft__Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill to Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.RecurSoft__Bill_to_Account__c</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>RecurSoft_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Bill_to_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Bill to Account)</relationshipLabel>
        <relationshipName>RecurSoft_OpportunitiesAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_End_Date__c</fullName>
        <label>Contract Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_Start_Date__c</fullName>
        <label>Contract Term Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Initial_Contract_Term__c</fullName>
        <defaultValue>12</defaultValue>
        <inlineHelpText>Contract duration, in months.</inlineHelpText>
        <label>Contract Term (Months)</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Shipping_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship to Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.RecurSoft__Bill_to_Account__c</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Ship to Contact)</relationshipLabel>
        <relationshipName>RecurSoft_Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Trial__c</fullName>
        <description>Trial Period in Days.</description>
        <inlineHelpText>Period during which contracts can be cancelled without penalties.</inlineHelpText>
        <label>Trial Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0 - Waived</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                    <default>true</default>
                    <label>60</label>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscriber_ID__c</fullName>
        <formula>Case(Account.Subscriber_ID__c,&quot;&quot;,&quot;&quot;,Account.Subscriber_ID__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subscriber ID</label>
        <type>Text</type>
    </fields>
</CustomObject>

src.3/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>RecurSoft__Contract_Term_End_Date__c</fullName>
        <formula>DATE(
year(RecurSoft__Contract_Term_Start_Date_New__c)+ floor((month(RecurSoft__Contract_Term_Start_Date_New__c) + VALUE(RecurSoft__Contract_Term1__c))/12) + if(and(month(RecurSoft__Contract_Term_Start_Date_New__c)=12,VALUE(RecurSoft__Contract_Term1__c)&gt;=12),-1,0)
,if( mod( month(RecurSoft__Contract_Term_Start_Date_New__c) + VALUE(RecurSoft__Contract_Term1__c) , 12 ) = 0, 12 , mod( month(RecurSoft__Contract_Term_Start_Date_New__c) + VALUE(RecurSoft__Contract_Term1__c) , 12 ))
,min(day(RecurSoft__Contract_Term_Start_Date_New__c),case(max( mod( month(RecurSoft__Contract_Term_Start_Date_New__c) + VALUE(RecurSoft__Contract_Term1__c) , 12 ) , 1),9,30,4,30,6,30,11,30,2,28,31))
)-1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deprecated - Contract Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_Start_Date__c</fullName>
        <formula>Opportunity.RecurSoft__Contract_Term_Start_Date1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deprecated - Contract Term Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Product_Subscription__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This field contains product subscription for current opportunity product.</inlineHelpText>
        <label>Product Subscription</label>
        <referenceTo>RecurSoft__Product_Subscription__c</referenceTo>
        <relationshipLabel>Opportunity Product (Product Subscription)</relationshipLabel>
        <relationshipName>RecurSoft_Opportunity_Product3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SR_Conversations_Phone_Number__c</fullName>
        <label>SR Conversations Phone Number</label>
        <type>Phone</type>
    </fields>
</CustomObject>

src.1/objects/SR_Default_Values__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SR Default Values</label>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

src.4/classes/AddProductAPI.cls
@RestResource(urlMapping='/add_products/*')
global with sharing class AddProductAPI 
{	
	@HttpGet
	global static String[] getSubscriptions()
	{
		Set<String> results = new Set<String>();

		RestRequest req = RestContext.request;
		String subscriberId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);

		RecurSoft__Product_Subscription__c[] subscriptions = ProductSubscriptionsSelector.newInstance().selectActiveSubscriptionsBySubscriberId(subscriberId);

		for(RecurSoft__Product_Subscription__c subscription : subscriptions)
		{
			results.add(subscription.RecurSoft__Product__r.Family);
		}

		return new List<String>(results);
	}

	@HttpPost
	global static Result addProducts(OppData opp_data)
	{
		Result result = new Result();
		fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
		SR_Default_Values__c isProduction = SR_Default_Values__c.getValues('Current Environment');
		String contractBaseURL = isProduction.Value__c == 'Production' ? SR_Default_Values__c.getValues('Production Contract URL').Value__c : SR_Default_Values__c.getValues('Sandbox Contract URL').Value__c;

		try
		{
			Opportunity existingOpp = getExistingOpp(opp_data.subscriberId);

			if(existingOpp != null)
			{
				uow.registerDeleted(existingOpp);
			}
		}
		catch(Exception e)
		{}

		createNewOpp(uow, opp_data, 30);	

		uow.commitWork();

		Opportunity newOpp = getExistingOpp(opp_data.subscriberId);

		Result.contractUrl = contractBaseURL + '/SRContractForm?id=' + newOpp.Id + '&source=api';
		return Result;
	}

	private static Opportunity getExistingOpp(String subscriberId)
	{
		return [SELECT Id, StageName 
					FROM Opportunity 
					WHERE Account.Subscriber_Id__c = :subscriberId 
					AND RecordType.Name = 'Add Product' 
					AND StageName = 'Qualified' 
					AND CreatedBy.Name = 'API User'
					LIMIT 1];
	}

	private static void createNewOpp(fflib_SObjectUnitOfWork uow, OppData opp_data, Integer daysToAdd)
	{
		Account a = [SELECT Id, Name FROM Account WHERE Subscriber_Id__c = :opp_data.subscriberId];
		RecurSoft__Product_Subscription__c ps = ProductSubscriptionsSelector.newInstance().selectActiveSRSubscriptionsBySubscriberId(opp_data.subscriberId);
		Integer term;
		
		if(ps.RecurSoft__Contract_Term_End_Date__c != null)
		{
			Integer monthsLeft = Date.today().addDays(daysToAdd).monthsBetween(ps.RecurSoft__Contract_Term_End_Date__c);
			term = monthsLeft > 0 ? monthsLeft : monthsLeft + 12;
		}
		else
		{
			term = 12;
		}
	
		Pricebook2[] pBook = PricebooksSelector.newInstance().selectByNameWithPricebookEntries(new Set<String>{'8. Add Product - API Only'});
		PricebookEntry[] pBookEntries = pBook[0].PricebookEntries;

		for(PricebookEntry pbEntry : pBookEntries)
		{
			if(pbEntry.ProductCode == '3022') productToPricebookEntry.put('conversations_contract', pbEntry);
			if(pbEntry.ProductCode == '3021') productToPricebookEntry.put('conversations_monthly', pbEntry);
			if(pbEntry.ProductCode == '3014') productToPricebookEntry.put('schedule_contract', pbEntry);
			if(pbEntry.ProductCode == '3013') productToPricebookEntry.put('schedule_monthly', pbEntry);
			if(pbEntry.ProductCode == '3032') productToPricebookEntry.put('smart_reviews_contract', pbEntry);
			if(pbEntry.ProductCode == '3031') productToPricebookEntry.put('smart_reviews_monthly', pbEntry);
		}

		Opportunity o = new Opportunity(AccountId = a.Id,
			Name = a.Name + ' - Add Products(via Platform): ' + System.now().format('MM/dd/yyyy','America/Denver'),
			StageName = 'Qualified',
			Pricebook2Id = pBook[0].Id,
			RecordTypeId = SRUtilities.getRecordTypeMap('Opportunity').get('Add Product').getRecordTypeId(),
			RecurSoft__Trial__c = 'None',
	        CloseDate = Date.today().addDays(daysToAdd),
	        RecurSoft__Initial_Contract_Term__c = term,
	        RecurSoft__Contract_Term_Start_Date__c = Date.today().addDays(daysToAdd),
	        RecurSoft__Billing_Contact__c = ps != null ? ps.RecurSoft__Bill_to_Contact__c : null,
	        RecurSoft__Shipping_Contact__c = ps != null ? ps.RecurSoft__Ship_to_Contact__c : null,
	        RecurSoft__Bill_to_Account__c = ps != null ? ps.RecurSoft__Bill_to_Account__c : null);

		uow.registerNew(o);

		for(ProductData product : opp_data.products)
		{
			OpportunityLineItem oppLi = new OpportunityLineItem(Quantity = 1, 
				UnitPrice = productToPricebookEntry.get(product.name + '_' + product.term).UnitPrice,
				SR_Conversations_Phone_Number__c = product.conversations_phone,
				PricebookEntryId = productToPricebookEntry.get(product.name + '_' + product.term).Id);
			uow.registerNew(oppLi, OpportunityLineItem.OpportunityId, o);
		}
	}

	private static Map<String, PricebookEntry> productToPricebookEntry = new Map<String, PricebookEntry>();

	global class OppData 
	{
		global String subscriberId;
		global ProductData[] products;
	}

	global class ProductData
	{
		global String name;
		global String term;
		global String conversations_phone;
	}

	global class Result
	{
		global String contractUrl;
	}
}