src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Account_Sales_Status__c</fullName>
        <label>Account Sales Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Contacted</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Bogus</fullName>
                </value>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_ROE_Date__c</fullName>
        <label>Last ROE Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Number_of_Locations__c</fullName>
        <label>Number of Locations</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0-9</fullName>
                </value>
                <value>
                    <fullName>10-49</fullName>
                </value>
                <value>
                    <fullName>50-100</fullName>
                </value>
                <value>
                    <fullName>100+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Practice_Management_Software__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is the practice management software the customer is using.</description>
        <inlineHelpText>This is the practice management software the customer is using.</inlineHelpText>
        <label>Practice Management Software</label>
        <referenceTo>Management_System__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Vertical__c</fullName>
        <label>Sub-Vertical</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Allergy &amp; Immunology</fullName>
                </value>
                <value>
                    <fullName>Bariatric, Metabolic and Weight Health</fullName>
                </value>
                <value>
                    <fullName>Chiropractic</fullName>
                </value>
                <value>
                    <fullName>Cosmetic Surgery</fullName>
                </value>
                <value>
                    <fullName>Dermatology</fullName>
                </value>
                <value>
                    <fullName>Endocrinology</fullName>
                </value>
                <value>
                    <fullName>Endodontistry</fullName>
                </value>
                <value>
                    <fullName>ENT-Otolaryngology</fullName>
                </value>
                <value>
                    <fullName>Family Medicine or General Physician</fullName>
                </value>
                <value>
                    <fullName>Gastroenterology</fullName>
                </value>
                <value>
                    <fullName>General Dentistry</fullName>
                </value>
                <value>
                    <fullName>General Surgery</fullName>
                </value>
                <value>
                    <fullName>Geriatric Medicine</fullName>
                </value>
                <value>
                    <fullName>Heart and Vascular</fullName>
                </value>
                <value>
                    <fullName>HIV/Infectious Disease</fullName>
                </value>
                <value>
                    <fullName>Internal Medicine</fullName>
                </value>
                <value>
                    <fullName>Medical Spa or Aesthetic Medicine</fullName>
                </value>
                <value>
                    <fullName>Neurology</fullName>
                </value>
                <value>
                    <fullName>Non-medical</fullName>
                </value>
                <value>
                    <fullName>OB/GYN or Womens Health</fullName>
                </value>
                <value>
                    <fullName>Oncology</fullName>
                </value>
                <value>
                    <fullName>Ophthalmology</fullName>
                </value>
                <value>
                    <fullName>Optometry</fullName>
                </value>
                <value>
                    <fullName>Oral Surgery</fullName>
                </value>
                <value>
                    <fullName>Orthodontistry</fullName>
                </value>
                <value>
                    <fullName>Orthopedics</fullName>
                </value>
                <value>
                    <fullName>Orthotics/Prosthetics</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pain Management or Physical Medicine or Physiatry</fullName>
                </value>
                <value>
                    <fullName>Pediatrics</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.1/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account_Sales_Status__c</fullName>
        <description>Apex mapping via Parent/Child Mappings</description>
        <label>Account Sales Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Contacted</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Bogus</fullName>
                </value>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_ROE_Date__c</fullName>
        <description>Apex mapping via Parent/Child Mappings</description>
        <label>Last ROE Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Number_of_Locations__c</fullName>
        <label>Number of Locations</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1-5</fullName>
                </value>
                <value>
                    <fullName>6-24</fullName>
                </value>
                <value>
                    <fullName>25-100</fullName>
                </value>
                <value>
                    <fullName>100+</fullName>
                </value>
                <value>
                    <fullName>1-4</fullName>
                </value>
                <value>
                    <fullName>5-24</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Powerstone__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies if the Contact has been sent to Powerstone for a call campaign. The Contact will be removed from Powerstone&#39;s list and this field will be updated if ROE is established on the Account.</description>
        <label>Powerstone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Practice_Management_Software__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Set via Parent/Child Mapping in Apex</description>
        <label>Practice Management Software</label>
        <referenceTo>Management_System__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Vertical__c</fullName>
        <description>Used for new Contacts coming from HubSpot to create new Account. Updated via Parent/Child Mapping in Apex</description>
        <label>Sub-Vertical</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Dermatology</fullName>
                </value>
                <value>
                    <fullName>Ophthalmology</fullName>
                </value>
                <value>
                    <fullName>Cosmetic Surgery</fullName>
                </value>
                <value>
                    <fullName>Family Medicine or General Physician</fullName>
                </value>
                <value>
                    <fullName>Pediatrics</fullName>
                </value>
                <value>
                    <fullName>OB/GYN or Womens Health</fullName>
                </value>
                <value>
                    <fullName>Allergy &amp; Immunology</fullName>
                </value>
                <value>
                    <fullName>ENT-Otolaryngology</fullName>
                </value>
                <value>
                    <fullName>Gastroenterology</fullName>
                </value>
                <value>
                    <fullName>Orthopedics</fullName>
                </value>
                <value>
                    <fullName>Bariatric, Metabolic and Weight Health</fullName>
                </value>
                <value>
                    <fullName>Endocrinology</fullName>
                </value>
                <value>
                    <fullName>Geriatric Medicine</fullName>
                </value>
                <value>
                    <fullName>Heart and Vascular</fullName>
                </value>
                <value>
                    <fullName>HIV/Infectious Disease</fullName>
                </value>
                <value>
                    <fullName>Internal Medicine</fullName>
                </value>
                <value>
                    <fullName>Medical Spa or Aesthetic Medicine</fullName>
                </value>
                <value>
                    <fullName>Neurology</fullName>
                </value>
                <value>
                    <fullName>General Surgery</fullName>
                </value>
                <value>
                    <fullName>Oncology</fullName>
                </value>
                <value>
                    <fullName>Pain Management or Physical Medicine or Physiatry</fullName>
                </value>
                <value>
                    <fullName>Podiatry</fullName>
                </value>
                <value>
                    <fullName>Psychiatry or Mental Health or Substance Rehabilitation</fullName>
                </value>
                <value>
                    <fullName>Radiology or Imaging</fullName>
                </value>
                <value>
                    <fullName>Urology</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>General Dentistry</fullName>
                </value>
                <value>
                    <fullName>Orthodontistry</fullName>
                </value>
                <value>
                    <fullName>Endodontistry</fullName>
                </value>
                <value>
                    <fullName>Pedodontistry</fullName>
                </value>
                <value>
                    <fullName>Optometry</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.3/objects/Management_System__c.object
<CustomObject>
    <label>Management System</label>
    <nameField>
        <label>Management System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Management Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src.1/classes/PowerstoneAPI_Test.cls
@IsTest
private with sharing class PowerstoneAPI_Test 
{
	@testSetup
	private	static void createTestData()
	{
		fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
		Account a = TestUtilities.insertBasicAccount(true);
		Contact c = TestUtilities.insertBasicContact(a.Id);
		a.Last_ROE_Date__c = Datetime.now().addDays(-5);
		uow.registerDirty(a);
		c.Powerstone__c = true;
		uow.registerDirty(c);

		uow.commitWork();
	}

	@IsTest
	private	static void testGET()
	{
		RestRequest req = new RestRequest(); 
		RestResponse res = new RestResponse();

		req.requestURI = '/services/apexrest/v1/Powerstone';  
		req.httpMethod = 'GET';
		RestContext.request = req;
		RestContext.response = res;

		Map<String, Id> pmNameToIdMap = PowerstoneAPI.getData();

		System.assertEquals(1, pmNameToIdMap.size());
	}

	@IsTest
	private	static void testPUT()
	{
		Account a = [SELECT Id FROM Account LIMIT 1];
		Contact c = [SELECT Id FROM Contact LIMIT 1];
		Management_System__c pm = [SELECT Id FROM Management_System__c LIMIT 1];
		
		RestRequest req = new RestRequest(); 
		RestResponse res = new RestResponse();

		req.requestURI = '/services/apexrest/v1/Powerstone';  
		req.httpMethod = 'PUT';
		RestContext.request = req;
		RestContext.response = res;

		JSONGenerator gen = JSON.createGenerator(true);
			gen.writeStartObject();
	            gen.writeStringField('contactId', c.Id);
	            gen.writeFieldName('contactData');
				gen.writeStartObject();
		            gen.writeStringField('firstName', 'TestFirst');
		            gen.writeStringField('lastName', 'TestLast');
		            gen.writeStringField('phone', '123-456-7890');
		            gen.writeStringField('email', 'testemail@testemail.com');
		            gen.writeStringField('contactRole', 'Office Manager');
		            gen.writeBooleanField('doNotContact', false);
		            gen.writeStringField('bestDayToContact', 'Monday');
		            gen.writeStringField('bestTimeToContact', 'Morning');
				gen.writeEndObject();
				gen.writeFieldName('accountData');
				gen.writeStartObject();
		            gen.writeStringField('businessName', 'TestBusinessName');
		            gen.writeStringField('pmId', pm.Id);
		            gen.writeStringField('vertical', 'Vision');
		            gen.writeStringField('subvertical', 'Optometry');
		            gen.writeStringField('salesStatus', 'Contacted');
		            gen.writeStringField('numberOfLocations', '0-9');
		            gen.writeBooleanField('isHospital', false);
				gen.writeEndObject();
	            gen.writeStringField('comments', 'comments');
	            gen.writeDateTimeField('demoScheduledDateTime', Datetime.now().addDays(5));
			gen.writeEndObject();

		req.requestBody = Blob.valueOf(gen.getAsString());

		Test.startTest();

		PowerstoneAPI.ProspectData prospectData = (PowerstoneAPI.ProspectData) JSON.deserialize(req.requestBody.toString(), PowerstoneAPI.ProspectData.class);

		PowerstoneAPI.updateData(prospectData);

		Contact[] c2 = ContactsSelector.newInstance().selectByIdWithAccountAndTasks(new Set<Id>{c.Id});
		String dateTimeString = prospectData.demoScheduledDateTime.format();
		System.debug(prospectData.demoScheduledDateTime);
		System.debug(dateTimeString);
		Test.stopTest();

		/*System.assertEquals(1, c2[0].Tasks.size());
		System.assertEquals(prospectData.contactData.firstName, c2[0].FirstName);
		System.assertEquals(prospectData.contactData.lastName, c2[0].LastName);
		System.assertEquals(prospectData.contactData.phone, c2[0].Phone);
		System.assertEquals(prospectData.contactData.email, c2[0].Email);
		System.assertEquals(prospectData.accountData.businessName, c2[0].Account.Name);
		System.assertEquals(prospectData.accountData.pmId, c2[0].Account.Practice_Management_Software__c);
		System.assertEquals(prospectData.accountData.vertical, c2[0].Account.Industry);
		System.assertEquals(prospectData.accountData.subvertical, c2[0].Account.Sub_Vertical__c);
		System.assertEquals(prospectData.accountData.salesStatus, c2[0].Account.Account_Sales_Status__c);
		System.assertEquals(prospectData.accountData.numberOfLocations, c2[0].Account.Number_of_Locations__c);
		//System.assertEquals(Datetime.parse(dateTimeString), c2[0].Tasks[0].Due_Time__c);
		System.assertEquals(prospectData.demoScheduledDateTime.date(), c2[0].Tasks[0].ActivityDate);
		System.assertEquals(prospectData.comments, c2[0].Tasks[0].Description);
		//System.assertEquals('Powerstone Demo Scheduled ' + prospectData.demoScheduledDateTime.format('MM/dd/yyyy h:mm a','America/Denver'), c2[0].Tasks[0].Subject);
		System.assertEquals(true, c2[0].Tasks[0].ADR_Set__c);
		System.assertEquals('ADR Set', c2[0].Tasks[0].Activity_Type__c);
		System.assertEquals('Future Event', c2[0].Tasks[0].Activity_Results__c);
		System.assertEquals('Scheduled', c2[0].Tasks[0].Status);
		System.assertEquals(c2[0].Id, c2[0].Tasks[0].WhoId);
		System.assertEquals(c2[0].AccountId, c2[0].Tasks[0].WhatId);*/
	}

	@isTest static void testBatch() 
	{
		Test.startTest();

		PowerstoneAPI_Batch batch = new PowerstoneAPI_Batch('Testing');
		//Database.executeBatch(batch);

		Test.stopTest();
	}
}