src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.4/objects/Case.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Administrative</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Technical</fullName>
                </value>
                <value>
                    <fullName>Collections</fullName>
                </value>
                <value>
                    <fullName>Generic</fullName>
                </value>
                <value>
                    <fullName>Change Payment Terms</fullName>
                </value>
                <value>
                    <fullName>Feature Enhancement</fullName>
                </value>
                <value>
                    <fullName>Open Invoice</fullName>
                </value>
                <value>
                    <fullName>Past Due</fullName>
                </value>
                <value>
                    <fullName>Setup Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Support</fullName>
        <active>true</active>
        <businessProcess>Support</businessProcess>
        <description>The main case type for Support</description>
        <label>Support</label>
    </recordTypes>
</CustomObject>

force-app/main/default/objects/Case/fields/Distribution_Group__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distribution Group</label>
    <referenceTo>Distribution_Group__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src.2/objects/Distribution_Group__c.object
<CustomObject>
    <label>Distribution Group</label>
    <nameField>
        <label>Distribution Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src.1/objects/SR_Default_Values__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SR Default Values</label>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

src.4/objects/Survey__c.object
<CustomObject>
    <description>Surveys from Customers about Sales, Cases and Cancels</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Business_Name__c</fullName>
        <label>Business Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>Surveys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>Surveys</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FS_Would_you_Recommend__c</fullName>
        <label>FS Would you Recommend</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>How_can_we_improve__c</fullName>
        <label>How can we improve</label>
        <length>15500</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

src.2/classes/Surveys_Test.cls
@isTest
private class Surveys_Test 
{	
	@isTest static void test_createCaseLowSurveyScore() 
	{
		fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

		Account ac = (Account) TestUtilities2.newAccount().toSObject(); 

		sfab_FabricatedSObject sFab = TestUtilities2.newSurvey()
			.setField(Survey__c.Contact_Name__c, 'Test Name')
			.setField(Survey__c.How_can_we_improve__c, 'Test how can we improve')
			.setField(Survey__c.FS_Would_you_Recommend__c, '4')
			.setField(Survey__c.Business_Name__c, ac.Id);			
		
		Survey__c s = (Survey__c) sFab.toSObject();

		Survey__c existingSurvey = (Survey__c) TestUtilities2.existingSurvey(sFab)
			.toSObject();

		insert new SR_Default_Values__c(Name = 'Case Escalation Queue',
			Description__c = 'Case Escalation Queue',
            Value__c = '00Gi00000034JUX');	

		Surveys survey = new Surveys(new List<Survey__c>{ s });
		survey.createCaseLowSurveyScore(s, existingSurvey, uow);

		List<Case> cases = (List<Case>)(uow.m_newListByType.get('Case'));

		System.assertEquals(1, uow.m_newListByType.get('Case').size());	
		System.assertEquals(ac.Id, cases[0].AccountId);
		System.assertEquals(s.Contact_Name__c, cases[0].ContactId);
		System.assertEquals(s.How_can_we_improve__c, cases[0].Description);
		System.assertEquals('Poor Service Experience', cases[0].Category__c);
		System.assertEquals('Medium', cases[0].Priority);
		System.assertEquals(SR_Default_Values__c.getValues('Case Escalation Queue').Value__c, cases[0].Distribution_Group__c);
		System.assertEquals(SRUtilities.getRecordTypeId('Case','Support'), cases[0].RecordTypeId);
	}	

	@isTest static void test_createCaseLowSurveyScoreFail() 
	{
		fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

		Account ac = (Account) TestUtilities2.newAccount().toSObject(); 

		sfab_FabricatedSObject sFab = TestUtilities2.newSurvey()
			.setField(Survey__c.Contact_Name__c, 'Test Name')
			.setField(Survey__c.How_can_we_improve__c, 'Test how can we improve')
			.setField(Survey__c.FS_Would_you_Recommend__c, '8')
			.setField(Survey__c.Business_Name__c, ac.Id);			
		
		Survey__c s = (Survey__c) sFab.toSObject();

		Survey__c existingSurvey = (Survey__c) TestUtilities2.existingSurvey(sFab)
			.toSObject();

		insert new SR_Default_Values__c(Name = 'Case Escalation Queue',
			Description__c = 'Case Escalation Queue',
            Value__c = '00Gi00000034JUX');	

		Surveys survey = new Surveys(new List<Survey__c>{ s });
		survey.createCaseLowSurveyScore(s, existingSurvey, uow);

		System.assertEquals(0, uow.m_newListByType.get('Case').size());			
	}	

	@isTest static void test_onAfterUpdate() 
    {       
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

		Account ac = (Account) TestUtilities2.newAccount().toSObject(); 

		sfab_FabricatedSObject sFab = TestUtilities2.newSurvey()
			.setField(Survey__c.Contact_Name__c, 'Test Name')
			.setField(Survey__c.How_can_we_improve__c, 'Test how can we improve')
			.setField(Survey__c.FS_Would_you_Recommend__c, '8')
			.setField(Survey__c.Business_Name__c, ac.Id);			
		
		Survey__c s = (Survey__c) sFab.toSObject();

		Surveys survey = new Surveys(new List<Survey__c>{ s });
        survey.onAfterUpdate(new Map<Id, SObject>{s.Id => s});          
    }
}