src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Do_Not_Support_Reason__c</fullName>
        <label>Do Not Support Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billing Concern</fullName>
                </value>
                <value>
                    <fullName>Legal Action</fullName>
                </value>
                <value>
                    <fullName>Client Dispute</fullName>
                </value>
                <value>
                    <fullName>Client Pending Cancel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Do_Not_Support_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if we do not need to auto create sync down cases for this account</inlineHelpText>
        <label>Do Not Support Sync</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.3/objects/Asset.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related Provider record for Healthgrades Assets</description>
        <inlineHelpText>The related Provider record for Healthgrades Assets</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.3/objects/Cancel_Request__c.object
<CustomObject>
    <description>Junction object between Retention Opportunities and Assets</description>
    <label>Cancel Request</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Cancel Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancel Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipName>OpportunityAssets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cancel_Request_Type__c</fullName>
        <label>Cancel Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Trial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_SR_Subscription__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Current SR Subscription</label>
        <referenceTo>RecurSoft__Product_Subscription__c</referenceTo>
        <relationshipLabel>Cancel Requests (Current SR Subscription)</relationshipLabel>
        <relationshipName>Cancel_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Modified_Subscription__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Modified Subscription</label>
        <referenceTo>RecurSoft__Product_Subscription__c</referenceTo>
        <relationshipLabel>Cancel Requests</relationshipLabel>
        <relationshipName>Cancel_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes_for_Accounting__c</fullName>
        <label>Notes for Accounting</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>OpportunityAssets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Actively Working</fullName>
                </value>
                <value>
                    <fullName>Negotiating</fullName>
                </value>
                <value>
                    <fullName>Sent Addendum</fullName>
                </value>
                <value>
                    <fullName>Save</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Resume - No Change</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.4/objects/Case.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the related Opportunity for this drop.</description>
        <inlineHelpText>Use this field to choose the related Opportunity for this drop.</inlineHelpText>
        <label>Related Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No Contact</fullName>
                </value>
                <value>
                    <fullName>Made Contact</fullName>
                </value>
                <value>
                    <fullName>Contact Attempted</fullName>
                </value>
                <value>
                    <fullName>Sync Scheduled</fullName>
                </value>
                <value>
                    <fullName>Sync Installed</fullName>
                </value>
                <value>
                    <fullName>Training Scheduled</fullName>
                </value>
                <value>
                    <fullName>Training Completed</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Resolving Issues</fullName>
                </value>
                <value>
                    <fullName>Made Offer</fullName>
                </value>
                <value>
                    <fullName>Sent Addendum</fullName>
                </value>
                <value>
                    <fullName>Offer Rejected</fullName>
                </value>
                <value>
                    <fullName>Dispute Resolution</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Accounting</fullName>
        <active>true</active>
        <businessProcess>Accounting</businessProcess>
        <description>Used to alert Accounting of changes to customers billing</description>
        <label>Accounting</label>
    </recordTypes>
</CustomObject>

src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Cancel_Request_Type__c</fullName>
        <description>Sugar field for Retention Opportunities</description>
        <label>Cancel Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Trial</fullName>
                </value>
                <value>
                    <fullName>Reactivation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notes_for_Accounting__c</fullName>
        <inlineHelpText>Enter Notes for accounting</inlineHelpText>
        <label>Notes for Accounting</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the related Provider record</description>
        <inlineHelpText>Link to the related Provider record</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Provider__c/Provider__c.object-meta.xml
<CustomObject>
    <description>Used to store information about individual Providers within a Practice.  The Provider information is used for Healthgrades Premium members.</description>
    <label>Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src.3/classes/CancelRequests.cls
public class CancelRequests extends fflib_SObjectDomain
{
    public static Map<String, Id> currentSubscriptionMap;
    public Map<Id, Asset> relatedAssets;

    public CancelRequests(Cancel_Request__c[] cancelRequests)
    {
        super(cancelRequests);
        Configuration.disableTriggerCRUDSecurity();
    }

    public class Constructor implements fflib_SObjectDomain.IConstructable
    {
        public fflib_SObjectDomain construct(List<SObject> sObjectList)
        {
            return new CancelRequests(sObjectList);
        }
    }

    public override void onBeforeInsert()
    {
        CancelRequestUtilities.setModifiedSubscription((Cancel_Request__c[]) Records, new Map<Id, Cancel_Request__c>());

        /*fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        for(Cancel_Request__c cro : (Cancel_Request__c[]) Records)
        {
            this.setModifiedSubscriptions(cro, null, uow);
        }

        uow.commitWork();*/
    }

    public override void onAfterInsert()
    {
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        for(Cancel_Request__c cro : (Cancel_Request__c[]) Records)
        {
            this.updateAccountDNS(cro, null, uow);
        }

        uow.commitWork();
    }

    public override void onBeforeUpdate(Map<Id, SObject> existingRecords)
    {
        FlowControl.checkCancelRequestFieldChanges((Cancel_Request__c[]) Records, (Map<Id, Cancel_Request__c>) existingRecords);

        CancelRequestUtilities.setModifiedSubscription((Cancel_Request__c[]) Records, (Map<Id, Cancel_Request__c>) existingRecords);

        if(FlowControl.fieldChangeIdMap.containsKey('Cancel_Request__cStage__cSave')) {

            CancelRequestUtilities.createAddendumOpp((Cancel_Request__c[]) Records);
        }

        if(FlowControl.fieldChangeIdMap.containsKey('Cancel_Request__cStage__cCancelled') ||
            FlowControl.fieldChangeIdMap.containsKey('Cancel_Request__cStage__cNo Sale')) {

            CancelRequestUtilities.createCancelCase((Cancel_Request__c[]) Records);
        }

        /*fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        for(Cancel_Request__c cro : (Cancel_Request__c[]) Records)
        {
            Cancel_Request__c existingCRO = (Cancel_Request__c) existingRecords.get(cro.Id);

            this.setModifiedSubscriptions(cro, null, uow);
        }

        uow.commitWork();*/
    }

    public override void onAfterUpdate(Map<Id, SObject> existingRecords)
    {
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        for(Cancel_Request__c cro : (Cancel_Request__c[]) Records)
        {
            Cancel_Request__c existingCRO = (Cancel_Request__c) existingRecords.get(cro.Id);

            this.updateAccountDNS(cro, existingCRO, uow);
        }

        uow.commitWork();
    }

    public void createAddendumOpp(Cancel_Request__c cro, Cancel_Request__c existingCRO, fflib_SObjectUnitOfWork uow) 
    {
        if(cro.Stage__c != 'Save') return;
        if(existingCRO != null && 
            cro.Stage__c == existingCRO.Stage__c) return;

        if(relatedAssets == null) relatedAssets = new Map<Id, Asset>(AssetsSelector.newInstance().selectByCancelRequestsWithAccountAndProduct((Cancel_Request__c[]) Records));
        Asset ast = relatedAssets.get(cro.Asset__c);

        Opportunity o = new Opportunity(RecordTypeId = SRUtilities.getRecordTypeMap('Opportunity').get('Add-On Business').getRecordTypeId(),
            AccountId = ast.AccountId,
            Description = cro.Notes_for_Accounting__c,
            CloseDate = Date.today(),
            StageName = 'Qualified',
            Name = ast.Name + ' - ' + cro.Cancel_Request_Type__c + ' Save',
            OwnerId = '005i0000002gn9T');
        uow.registerNew(o);
    }

    public void createCancelCase(Cancel_Request__c cro, Cancel_Request__c existingCRO, fflib_SObjectUnitOfWork uow) 
    {
        if(cro.Stage__c != 'Cancelled' && 
            cro.Stage__c != 'No Sale') return;
        if(existingCRO != null && 
            cro.Stage__c == existingCRO.Stage__c) return;

        if(relatedAssets == null) relatedAssets = new Map<Id, Asset>(AssetsSelector.newInstance().selectByCancelRequestsWithAccountAndProduct((Cancel_Request__c[]) Records));
        Asset ast = relatedAssets.get(cro.Asset__c);

        String cancelType = cro.Stage__c == 'Cancelled' ? cro.Cancel_Request_Type__c + ' Cancel' : 'No Sale';
        String subject = cancelType == 'Annual Cancel' ? 'Turn off any Renewals' : cancelType == 'Trial Cancel' ? '' : 'Refund MSF and Setup';

        Case c = new Case(RecordTypeId = SRUtilities.getRecordTypeMap('Case').get('Accounting').getRecordTypeId(),
            AccountId = ast.AccountId,
            Description = cro.Notes_for_Accounting__c,
            Origin = 'Phone',
            OwnerId = '00Gi00000034JUX',
            Reason = cancelType,
            Related_Opportunity__c = cro.Opportunity__c,
            Subject = ast.Name + ' - ' + cancelType + ' - ' + subject);
        uow.registerNew(c);
    }

    public void setModifiedSubscriptions(Cancel_Request__c cro, Cancel_Request__c existingCRO, fflib_SObjectUnitOfWork uow)
    {
        if(existingCRO != null && 
            (existingCRO.Stage__c == 'Save' || 
            existingCRO.Stage__c == 'Cancelled' ||
            existingCRO.Stage__c == 'No Sale' ||
            existingCRO.Stage__c == 'Resume - No Change')) return;

        this.setModifiedSubscriptions('Modified_Subscription__c', cro, uow);
        this.setModifiedSubscriptions('Current_SR_Subscription__c', cro, uow);
    }

    public void setModifiedSubscriptions(String fieldName, Cancel_Request__c cro, fflib_SObjectUnitOfWork uow) 
    {
        if((Boolean) cro.get('Override_' + fieldName)) return;
        
        if(relatedAssets == null) relatedAssets = new Map<Id, Asset>(AssetsSelector.newInstance().selectByCancelRequestsWithAccountAndProduct((Cancel_Request__c[]) Records));
        Asset ast = relatedAssets.get(cro.Asset__c);

        if(currentSubscriptionMap == null) currentSubscriptionMap = AssetsSelector.newInstance().selectCurrentSubscriptionsByCancelRequests((Cancel_Request__c[]) Records);
        String productName = fieldName == 'Current_SR_Subscription__c' ? 'SR Platform' : ast.Product2.Family;

        if(!currentSubscriptionMap.containsKey(ast.AccountId + productName + ast.Provider__c)) return;
        if(cro.get(fieldName) == currentSubscriptionMap.get(ast.AccountId + productName + ast.Provider__c)) return;

        cro.put(fieldName, currentSubscriptionMap.get(ast.AccountId + productName + ast.Provider__c));
        uow.registerDirty(cro);
    }

    public void updateAccountDNS(Cancel_Request__c cro, Cancel_Request__c existingCRO, fflib_SObjectUnitOfWork uow)
    {
        if(cro.Stage__c != 'Save' &&
                cro.Stage__c != 'Resume - No Change' &&
                cro.Stage__c != 'Cancelled' &&
                cro.Stage__c != 'No Sale') return;

        if(existingCRO != null && 
            cro.Stage__c == existingCRO.Stage__c) return;

        if(relatedAssets == null) relatedAssets = new Map<Id, Asset>(AssetsSelector.newInstance().selectByCancelRequestsWithAccountAndProduct((Cancel_Request__c[]) Records));
        Asset ast = relatedAssets.get(cro.Asset__c);

        System.debug(ast.AccountId);

        Account a = new Account(Id = ast.AccountId,
            Do_Not_Support_Sync__c = false,
            Do_Not_Support_Reason__c = null);
        uow.registerDirty(a);
    }
}