src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Admin_Last_Sync_Date__c</fullName>
        <description>Stores the date of the last Sync</description>
        <inlineHelpText>This is updated every morning and shows when the last time the office had a successful sync</inlineHelpText>
        <label>Admin Last Sync Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>admin_sync_received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Admin Sync Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Do_Not_Support_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if we do not need to auto create sync down cases for this account</inlineHelpText>
        <label>Do Not Support Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>of_Open_Sync_Cases__c</fullName>
        <label># of Open Sync Cases</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Intacct_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Determines whether customer records are created at the root or entity level in Intacct.</inlineHelpText>
        <label>Intacct Entity</label>
        <referenceTo>RecurSoft__Intacct_Entity__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>RecurSoft_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Status__c</fullName>
        <description>Picklist used to determine if an account is an active customer.</description>
        <inlineHelpText>Determined by the status of subscriptions (not created, created, not activated, or cancelled)</inlineHelpText>
        <label>ISB Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.4/objects/Case.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/Distribution_Group__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distribution Group</label>
    <referenceTo>Distribution_Group__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src.2/objects/Distribution_Group__c.object
<CustomObject>
    <label>Distribution Group</label>
    <nameField>
        <label>Distribution Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Distribution_Group__c/fields/Distribution_Type__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Type__c</fullName>
    <label>Distribution Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Linear</fullName>
                <default>true</default>
                <label>Linear</label>
            </value>
            <value>
                <fullName>Load Balanced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Distribution_Group__c/fields/Field_to_Distribute__c.field-meta.xml
<CustomField>
    <fullName>Field_to_Distribute__c</fullName>
    <label>Field to Distribute</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Distribution_Group__c/fields/ParentObject__c.field-meta.xml
<CustomField>
    <fullName>ParentObject__c</fullName>
    <label>Parent Object</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Distribution_Group__c/fields/Relationship_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Criteria__c</fullName>
    <inlineHelpText>SOQL WHERE clause applied when querying Object records, e.g. Amount &gt; 200</inlineHelpText>
    <label>Relationship Criteria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src.1/objects/Distribution_Group_Member__c.object
<CustomObject>
    <label>Distribution Group Member</label>
    <nameField>
        <displayFormat>DGM-{000}</displayFormat>
        <label>Distribution Group Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Distribution Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Available__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Distribution_Group__c</fullName>
        <label>Distribution Group</label>
        <referenceTo>Distribution_Group__c</referenceTo>
        <relationshipLabel>Distribution Group Members</relationshipLabel>
        <relationshipName>Distribution_Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Next_Up__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Next Up</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Distribution_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Distribution_Group_Member__c/fields/Load__c.field-meta.xml
<CustomField>
    <fullName>Load__c</fullName>
    <formula>Total_Open__c / Rep_Limit__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Last calculated Load Percentage</inlineHelpText>
    <label>Load %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Distribution_Group_Member__c/fields/Rep_Limit__c.field-meta.xml
<CustomField>
    <fullName>Rep_Limit__c</fullName>
    <label>Rep Limit</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src.1/objects/SR_Default_Values__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SR Default Values</label>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

src.4/classes/SyncDownCases_Batch_Test.cls
/**
 * Created by mschetselaar on 10/4/2018.
 */

@IsTest
private class SyncDownCases_Batch_Test
{
    @TestSetup
    static void testData()
    {
        Id accountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Child Major Account').getRecordTypeId();
        Id majorAccountId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Major Account').getRecordTypeId();
        Id independentRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId();
        Account a = TestUtilities.insertBasicAccount(true);
        a.Admin_Last_Sync_Date__c = Date.today().addDays(-5);
        a.Admin_Sync_Received__c  = false;
        a.Do_Not_Support_Sync__c = false;
        a.of_Open_Sync_Cases__c = 0;
        a.RecordTypeId = accountRecordTypeId;
        a.RecurSoft__Status__c = 'Active';
        
        Account pAccount = new Account();
        pAccount.Name = 'Parent Account';
        pAccount.RecordTypeId = majorAccountId;
        pAccount.Industry = 'Dental';
        pAccount.RecurSoft__Intacct_Entity__c = 'a1Ai0000001ctUXEAY';
        
        Account independentAccount = new Account(
                Name = 'Independent Account',
                Industry = 'Dental',
                RecurSoft__Intacct_Entity__c = 'a1Ai0000001ctUXEAY',
                Admin_Last_Sync_Date__c = Date.today().addDays(-5),
                Admin_Sync_Received__c  = false,
                Do_Not_Support_Sync__c = false,
                of_Open_Sync_Cases__c = 0,
                RecordTypeId = independentRecordTypeId,
                RecurSoft__Status__c = 'Active'
        );
        
        Id syncCase = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Sync List Case').getRecordTypeId();
        Case entSyncCase = new Case(
                RecordTypeId = syncCase,
                Subject = 'Test SYnc Case',
                Status = 'Assigned'
        );
        
        insert independentAccount;
        insert pAccount;
        a.ParentId = pAccount.Id;
        entSyncCase.AccountId = pAccount.Id;
        
        update a;
        
        User[] techUsers = [SELECT Id, Name FROM User WHERE UserRole.Name = 'CSR - Tech' AND IsActive = TRUE LIMIT 5];
        Distribution_Group__c ind = new Distribution_Group__c(Name = 'Testing' ,
                Distribution_Type__c = 'Load Balanced',
                Relationship_Criteria__c = 'IsClosed = false',
                ParentObject__c = 'Case',
                Field_to_Distribute__c = 'OwnerId');
        Distribution_Group__c ent = new Distribution_Group__c(Name = 'Testing Ent' ,
                Distribution_Type__c = 'Load Balanced',
                Relationship_Criteria__c = 'IsClosed = false',
                ParentObject__c = 'Case',
                Field_to_Distribute__c = 'OwnerId');
        List<Distribution_Group__c> groups = new List<Distribution_Group__c>();
        groups.add(ind);
        groups.add(ent);
        insert groups;
        
        List<SR_Default_Values__c> srDefaults = new List<SR_Default_Values__c>();
        SR_Default_Values__c indTechReps = new SR_Default_Values__c(Name='IND Sync Dist Group Id', Value__c = '' + ind.Id, Description__c = 'Test for Ind');
        SR_Default_Values__c entTechReps = new SR_Default_Values__c(Name='ENT Sync Dist Group Id', Value__c = '' + ent.Id, Description__c = 'Test for Ent');
        srDefaults.add(indTechReps);
        srDefaults.add(entTechReps);
        insert srDefaults;
        
        List<Distribution_Group_Member__c> members = new List<Distribution_Group_Member__c>();
        Distribution_Group_Member__c r1 = new Distribution_Group_Member__c(Distribution_Group__c = ind.Id,
                User__c = techUsers[0].Id,
                Rep_Limit__c = 5,
                Available__c = true,
                Next_Up__c = true);
        members.add(r1);
        Distribution_Group_Member__c r2 = new Distribution_Group_Member__c(Distribution_Group__c = ind.Id,
                User__c = techUsers[1].Id,
                Rep_Limit__c = 5,
                Available__c = true,
                Next_Up__c = false);
        members.add(r2);
        Distribution_Group_Member__c r3 = new Distribution_Group_Member__c(Distribution_Group__c = ent.Id,
                User__c = techUsers[2].Id,
                Rep_Limit__c = 5,
                Available__c = true,
                Next_Up__c = true);
        members.add(r3);
        Distribution_Group_Member__c r4 = new Distribution_Group_Member__c(Distribution_Group__c = ent.Id,
                User__c = techUsers[3].Id,
                Rep_Limit__c = 5,
                Available__c = true,
                Next_Up__c = false);
        members.add(r4);
        insert members;
        
        entSyncCase.OwnerId = techUsers[3].Id;
        insert entSyncCase;
    }
    
    @IsTest
    static void test_SyncDownCases_Batch()
    {
        Test.startTest();
        SyncDownCases_Batch batch = new SyncDownCases_Batch();
        Database.executeBatch(batch);
        Test.stopTest();
        
        Id majorAccountId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Major Account').getRecordTypeId();
        Id independentAccountId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId();
        Case[] cases = [SELECT Id, AccountId, Account.ParentId, Status, OwnerId FROM Case WHERE Account.RecordTypeId = :majorAccountId AND Status = 'New'];
        Case[] casesIndependent = [SELECT Id, AccountId, Account.ParentId, Status, OwnerId FROM Case WHERE Account.RecordTypeId = :independentAccountId];
        Account acct = [SELECT Id FROM Account WHERE RecordTypeId = :majorAccountId LIMIT 1];
        Account acct2 = [SELECT Id FROM Account WHERE RecordTypeId = :independentAccountId LIMIT 1];
        
        Id DistId = (Id)[SELECT Value__c FROM SR_Default_Values__c WHERE Name = 'IND Sync Dist Group Id' LIMIT 1].Value__c;
        Distribution_Group_Member__c[] roundRobinsInd = [SELECT Id,
                User__c,
                Load__c,
                Distribution_Group__r.Name,
                Name
        FROM Distribution_Group_Member__c
        WHERE Distribution_Group__c = :DistId
        ORDER BY Load__c];
        Id entDistId = (Id)[SELECT Value__c FROM SR_Default_Values__c WHERE Name = 'ENT Sync Dist Group Id' LIMIT 1].Value__c;
        Distribution_Group_Member__c[] roundRobinsEnt = [SELECT Id,
                User__c,
                Load__c,
                Distribution_Group__c,
                Name
        FROM Distribution_Group_Member__c
        WHERE Distribution_Group__c = :entDistId
        ORDER BY Load__c];
        
        Distribution_Group__c dg = [SELECT Id, Name, Distribution_Type__c FROM Distribution_Group__c WHERE Id = :roundRobinsEnt[0].Distribution_Group__c];
        
        System.assert(cases.size()>0);
        System.assertEquals(acct.Id, cases[0].AccountId);
        System.assertEquals((Id)roundRobinsEnt[1].User__c,cases[0].OwnerId);
        System.assert(casesIndependent.size()>0);
        System.assertEquals(acct2.Id, casesIndependent[0].AccountId);
        System.assertEquals((Id)roundRobinsInd[1].User__c,casesIndependent[0].OwnerId);
    }
    
    @IsTest
    static void test_SyncDownCases_Batch_New_Account()
    {
        List<Case> syncCases = [SELECT Id FROM Case];
        delete syncCases;
        
        Test.startTest();
        SyncDownCases_Batch batch = new SyncDownCases_Batch();
        Database.executeBatch(batch);
        Test.stopTest();
        
        Id majorAccountId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Major Account').getRecordTypeId();
        Case[] cases = [SELECT Id, AccountId, Account.ParentId, Status, OwnerId FROM Case WHERE Account.RecordTypeId = :majorAccountId AND Status = 'New'];
        Id entDistId = (Id)[SELECT Value__c FROM SR_Default_Values__c WHERE Name = 'ENT Sync Dist Group Id' LIMIT 1].Value__c;
        Distribution_Group_Member__c[] roundRobinsEnt = [SELECT Id,
                User__c,
                Load__c,
                Distribution_Group__c,
                Name
        FROM Distribution_Group_Member__c
        WHERE Distribution_Group__c = :entDistId
        ORDER BY Load__c];
        System.assert(cases.size()>0);
        System.assertEquals(roundRobinsEnt[1].User__c,cases[0].OwnerId);
    
    }
    
    @IsTest static void test_SyncDownCases_Batch_existing_Account()
    {
        Case syncCase = [SELECT Id, OwnerId FROM Case LIMIT 1];
        Id entDistId = (Id)[SELECT Value__c FROM SR_Default_Values__c WHERE Name = 'ENT Sync Dist Group Id' LIMIT 1].Value__c;
        Distribution_Group_Member__c[] roundRobinsEnt = [SELECT Id,
                User__c,
                Load__c,
                Distribution_Group__c,
                Name
        FROM Distribution_Group_Member__c
        WHERE Distribution_Group__c = :entDistId
        ORDER BY Load__c];
        syncCase.OwnerId = roundRobinsEnt[1].User__c;
        
        update syncCase;
        
        Test.startTest();
        SyncDownCases_Batch batch = new SyncDownCases_Batch();
        Database.executeBatch(batch);
        Test.stopTest();
        
        Id majorAccountId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Major Account').getRecordTypeId();
        Case[] cases = [SELECT Id, AccountId, Account.ParentId, Status, OwnerId FROM Case WHERE Account.RecordTypeId = :majorAccountId AND Status = 'New'];
        
        System.assert(cases.size()>0);
        System.assertEquals(roundRobinsEnt[1].User__c,cases[0].OwnerId);
    
    }
    
    @isTest static void SyncDownCases_Batch_Test_Schedule()
    {
        
        SyncDownCases_Batch schedule = new SyncDownCases_Batch();
        Test.startTest();
        System.schedule('Test', '0 0 13 * * ?', schedule);
        Test.stopTest();
        List<AsyncApexJob> jobsScheduled = [select Id, ApexClassID, ApexClass.Name, Status, JobType from AsyncApexJob where JobType = 'ScheduledApex'];
        System.assertEquals(1, jobsScheduled.size());
    
    }
}