src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Contact_Email_Duplicates__c</fullName>
        <formula>Contact_Email_Count__c &gt; 0 &amp;&amp;
Contact_Email_Count_Distinct__c &gt; 0 &amp;&amp;
Contact_Email_Count__c &gt; Contact_Email_Count_Distinct__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Email Duplicates</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.1/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>RecurSoft__Intacct_Contact_ID__c</fullName>
        <label>Intacct Contact ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

src.3/classes/ContactCleanWithinAcct.cls
global class ContactCleanWithinAcct implements Database.Batchable<sObject> 
{	
	String query = 'SELECT Id, (SELECT Id, RecurSoft__Intacct_Contact_ID__c, Email, CreatedDate FROM ' +
	'Contacts ORDER BY RecurSoft__Intacct_Contact_ID__c DESC NULLS LAST, CreatedDate ASC) FROM Account WHERE ' +
	'Contact_Email_Duplicates__c = true';

	global Database.QueryLocator start(Database.BatchableContext BC) 
	{	
		return Database.getQueryLocator(query);
	}

	global void execute(Database.BatchableContext BC, List<Account> scope) 
	{
		Map<Id, SObject> updateMap = new Map<Id, SObject>();
      	Set<String> emailSet = new Set<String>();

		for(Account a : scope) 
		{
			emailSet.clear();

			for(Contact c : a.Contacts)
			{
				if(emailSet.contains(c.Email))
				{
					if(c.RecurSoft__Intacct_Contact_ID__c == null)
					{
						c.Email = null;
						updateMap.put(c.Id, c);
					}
				}
				else
				{
					emailSet.add(c.Email);
				}
			}
		}

		update updateMap.values();
	}
			
	global void finish(Database.BatchableContext BC) 
	{

	}
}