src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>RecurSoft__Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Default Bill to Contact for usage billing.</inlineHelpText>
        <label>Bill to Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>$Source.RecurSoft__Bill_to_Account__c</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.RecurSoft__Bill_to_Account__c</field>
                <operation>equals</operation>
                <value/>
            </filterItems>
            <infoMessage>Contact should have current account.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>RecurSoft_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Bill_to_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Default Bill to Account for usage billing.</inlineHelpText>
        <label>Bill to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Bill to Account)</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Shipping_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Default Ship to Contact for usage billing.</inlineHelpText>
        <label>Ship to Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>$Source.RecurSoft__Bill_to_Account__c</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.RecurSoft__Bill_to_Account__c</field>
                <operation>equals</operation>
                <value/>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (Ship to Contact)</relationshipLabel>
        <relationshipName>RecurSoft_Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.1/objects/Error_Log__c.object
<CustomObject>
    <description>Object will store all Contract process error&#39;s and App Admin API errors.</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{0000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>For error messages longer than 255 characters including HTML markup</description>
        <label>Error Message</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Error_Type__c</fullName>
        <description>Contract Review Page,PayPal or AppAdmin</description>
        <label>Error Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Opportunity</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Error Logs</relationshipLabel>
        <relationshipName>Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Error Logs</relationshipLabel>
        <relationshipName>Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Approval_Level_Required__c</fullName>
        <label>Approval Level Required</label>
        <summarizedField>OpportunityLineItem.Approval_Level_Required__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Contract_Date_Time__c</fullName>
        <description>Contract signed date</description>
        <inlineHelpText>Contract signed date</inlineHelpText>
        <label>Contract Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Contract_Signed_IP__c</fullName>
        <label>Contract Signed IP</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract_Signer__c</fullName>
        <label>Contract Signer</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HGFreeMonths__c</fullName>
        <label>HGFreeMonths</label>
        <summarizedField>OpportunityLineItem.Number_of_Free_Months__c</summarizedField>
        <summaryFilterItems>
            <field>OpportunityLineItem.Product_Code_Formula__c</field>
            <operation>equals</operation>
            <value>3005</value>
        </summaryFilterItems>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the related Provider record</description>
        <inlineHelpText>Link to the related Provider record</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill to Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.RecurSoft__Bill_to_Account__c</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>RecurSoft_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Bill_to_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Bill to Account)</relationshipLabel>
        <relationshipName>RecurSoft_OpportunitiesAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Signed_Date__c</fullName>
        <label>Contract Signed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_End_Date__c</fullName>
        <label>Contract Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_Start_Date__c</fullName>
        <label>Contract Term Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Shipping_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship to Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.RecurSoft__Bill_to_Account__c</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Ship to Contact)</relationshipLabel>
        <relationshipName>RecurSoft_Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Trial__c</fullName>
        <description>Trial Period in Days.</description>
        <inlineHelpText>Period during which contracts can be cancelled without penalties.</inlineHelpText>
        <label>Trial Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0 - Waived</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                    <default>true</default>
                    <label>60</label>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Healthgrades</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <description>For selling Healthgrades Premium Profiles</description>
        <label>Healthgrades</label>
    </recordTypes>
</CustomObject>

src.3/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related Provider for the Healthgrades Premium Profile</description>
        <inlineHelpText>The related Provider for the Healthgrades Premium Profile</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_End_Date__c</fullName>
        <formula>DATE(
year(RecurSoft__Contract_Term_Start_Date_New__c)+ floor((month(RecurSoft__Contract_Term_Start_Date_New__c) + VALUE(RecurSoft__Contract_Term1__c))/12) + if(and(month(RecurSoft__Contract_Term_Start_Date_New__c)=12,VALUE(RecurSoft__Contract_Term1__c)&gt;=12),-1,0)
,if( mod( month(RecurSoft__Contract_Term_Start_Date_New__c) + VALUE(RecurSoft__Contract_Term1__c) , 12 ) = 0, 12 , mod( month(RecurSoft__Contract_Term_Start_Date_New__c) + VALUE(RecurSoft__Contract_Term1__c) , 12 ))
,min(day(RecurSoft__Contract_Term_Start_Date_New__c),case(max( mod( month(RecurSoft__Contract_Term_Start_Date_New__c) + VALUE(RecurSoft__Contract_Term1__c) , 12 ) , 1),9,30,4,30,6,30,11,30,2,28,31))
)-1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deprecated - Contract Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_Start_Date__c</fullName>
        <formula>Opportunity.RecurSoft__Contract_Term_Start_Date1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deprecated - Contract Term Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Product_Subscription__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This field contains product subscription for current opportunity product.</inlineHelpText>
        <label>Product Subscription</label>
        <referenceTo>RecurSoft__Product_Subscription__c</referenceTo>
        <relationshipLabel>Opportunity Product (Product Subscription)</relationshipLabel>
        <relationshipName>RecurSoft_Opportunity_Product3</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Provider__c/Provider__c.object-meta.xml
<CustomObject>
    <description>Used to store information about individual Providers within a Practice.  The Provider information is used for Healthgrades Premium members.</description>
    <label>Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Provider__c/fields/Bill_to_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The related account that will be billed for the Provider&#39;s Healthgrades subscription.</description>
    <inlineHelpText>The related account that will be billed for the Provider&#39;s Healthgrades subscription.</inlineHelpText>
    <label>Bill to Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Providers</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Healthgrades_ID__c.field-meta.xml
<CustomField>
    <fullName>Healthgrades_ID__c</fullName>
    <description>The individual Provider&#39;s unique Healthgrades identifier.</description>
    <externalId>true</externalId>
    <label>Healthgrades ID</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Premium_Member__c.field-meta.xml
<CustomField>
    <fullName>Premium_Member__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the Provider is currently paying for a Healthgrades Premium Profile.</description>
    <inlineHelpText>Checked if the Provider is currently paying for a Healthgrades Premium Profile.</inlineHelpText>
    <label>Premium Member</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Related_Contact__c.field-meta.xml
<CustomField>
    <fullName>Related_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Provider&#39;s contact information is accessed via the Related Contact field.</description>
    <inlineHelpText>The Provider&#39;s contact information is accessed via the Related Contact field.</inlineHelpText>
    <label>Related Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Providers</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

src.2/classes/HealthgradesContractController.cls
public without sharing class HealthgradesContractController extends WebFormsUtilityClass {
    
    public String providerId { get; set; }
    public String oppId { get; set; }
    public String signName { get; set; }
    public String contactSalutation { get; set; }
    public String contactFirstName { get; set; }
    public String contactLastName { get; set; }
    public String contactEmail { get; set; }
    public String contactPhone { get; set; }
    public String contractIP { get; set; }
    public String errorMessage { get; set; }
    public String contractTerm { get; set; }
    public String contractFreeMonths { get; set; }
    public String contractDateTime { get; set; }
    public Boolean renderForm { get; set; }
    public Boolean renderError { get; set; }
    public Boolean renderConfirmation { get; set; }
    public Boolean requestedEmail { get; set; }
    public Boolean acceptedRenewal { get; set; }
    public Boolean acceptedTerms { get; set; }
    public Provider__c prov { get; set; }
    public Opportunity relatedOpportunity { get; set; }
    public Contact relatedContact { get; set; }
    public Account relatedAccount { get; set; }
    public RecurSoft__Product_Subscription__c relatedProdSubscription { get; set; }
    public OpportunityLineItem[] relatedOppLis { get; set; }
    
    /**
     * Constructor to initialize variables. String variables are used for contact information to be displayed and edited on the public facing site.
     * If relatedContact field values are used directly, the update fails because of Guest User permission limitations.
     */
    public HealthgradesContractController() {
          
        providerId = getURParameter('id');
        oppId = getURParameter('oppId');
        signName = '';
        acceptedRenewal = false;
        acceptedTerms = false;
        prov = retrieveProviderData(providerId);

        try {

            relatedProdSubscription = retrieveSubscriptionData(prov.Bill_to_Account__c);
            contractTerm = String.valueOf(calculateContractStartDate(relatedProdSubscription.RecurSoft__Contract_Term_Start_Date__c).monthsBetween(relatedProdSubscription.RecurSoft__Contract_Term_End_Date__c));

        } catch(Exception e) {

            errorMessage = Label.NotCurrentCustomer;
            renderForm = false;
            renderError = true;
            renderConfirmation = false;
            System.debug(e);
        }

        try {
 
            relatedOpportunity = retrieveOpportunityData(oppId);
            relatedContact = retrieveContactData(prov.Related_Contact__r.Id);
            relatedAccount = retrieveAccountData(prov.Bill_to_Account__r.Id);
            relatedOppLis = relatedOpportunity.OpportunityLineItems;
            contactSalutation = relatedContact.Salutation;
            contactFirstName = relatedContact.FirstName;
            contactLastName = relatedContact.LastName;
            contactEmail = relatedContact.Email;
            contactPhone = relatedContact.Phone;
            contractIP = relatedOpportunity.Contract_Signed_IP__c;
            errorMessage = Label.ContractExpired;
            contractFreeMonths = relatedOpportunity.HGFreeMonths__c == null ? '0' : String.valueOf(relatedOpportunity.HGFreeMonths__c);
            contractDateTime = String.valueOf(relatedOpportunity.Contract_Date_Time__c);
            renderForm = readyForContract();
            renderError = !readyForContract();
            renderConfirmation = false;

        } catch(Exception e) {

            errorMessage = Label.ContractExpired;
            renderForm = false;
            renderError = true;
            renderConfirmation = false;
            System.debug(e + ' ' + e.getLineNumber());
        }
    }

    /**
     * Check to see that the relatedOpportunity isn't already closed. 
     * Check that the related Provider has a Healthgrades URL and isn't already Premium.
     */
    public Boolean readyForContract() {

        Boolean results = true;

        Pattern regexPattern = Pattern.compile('(.*)(healthgrades\\.com\\/)(((dentist|physician)\\/([a-z]+\\-){3,}[a-z0-9]{5,10})|(provider\\/([a-z]*\\-){2,}[a-z0-9]{5,10}))((\\?|\\/|#)(.*))?');
        Matcher regexMatcher = regexPattern.matcher(prov.Healthgrades_ID__c);

        if(!validateOpp(relatedOpportunity) ||
            isEmptyOrNull(prov.Healthgrades_ID__c) ||
            prov.Premium_Member__c) {

            results = false;
            errorMessage = Label.Outstanding_Approvals;

        } else if(!regexMatcher.matches()) {

            results = false;
            errorMessage = 'The Healthgrades URL is not formatted correctly.  Please contact your Sales Representative.';

        } else if(relatedProdSubscription == null) { 

            results = false; 
            errorMessage = Label.NotCurrentCustomer;
        } 

        return results;
    }

    /**
     * Update Provider and Contact with any customer-made changes.
     * Update the Opportunity with timestamps, IP address, and Closed Won.
     * Show Confirmation page to customer.
     * Call method to generate PDF of signed contract.
     */
    public void submitForm() {
        
        String errorMsg = 'Please complete all required fields';

        Opportunity currentOpp = retrieveOpportunityData(oppId);

        if(!validateOpp(currentOpp)) {

            errorMsg = Label.Outstanding_Approvals;
            ApexPages.addMessage(returnFailure(errorMsg));
        
        } else {

            if(requiredFieldsComplete()) {
            
                try{

                    update prov;
                
                    relatedContact.FirstName = contactFirstName;
                    relatedContact.LastName = contactLastName;
                    relatedContact.Email = contactEmail;
                    relatedContact.Phone = contactPhone;
                    update relatedContact;

                    relatedOpportunity.RecurSoft__Contract_Signed_Date__c = Date.today();
                    relatedOpportunity.Contract_Date_Time__c = Datetime.now();
                    relatedOpportunity.Contract_Signer__c = signName;
                    relatedOpportunity.CloseDate = Date.today();
                    relatedOpportunity.Contract_Signed_IP__c = ApexPages.currentPage().getHeaders().get('X-Salesforce-SIP');
                    relatedOpportunity.Contract_Signed__c = true;
                    //relatedOpportunity.RecurSoft__Trial__c = 'None';
                    if(relatedProdSubscription != null) {
                        FlowControl.hgContractDatesSet = true;
                        relatedOpportunity.RecurSoft__Contract_Term_End_Date__c = relatedProdSubscription.RecurSoft__Contract_Term_End_Date__c;
                        relatedOpportunity.RecurSoft__Contract_Term_Start_Date__c = calculateContractStartDate(relatedProdSubscription.RecurSoft__Contract_Term_Start_Date__c);
                        contractTerm = String.valueOf(relatedOpportunity.RecurSoft__Contract_Term_Start_Date__c.monthsBetween(relatedOpportunity.RecurSoft__Contract_Term_End_Date__c));
                        relatedOpportunity.RecurSoft__Billing_Contact__c = relatedProdSubscription.RecurSoft__Bill_to_Contact__c;
                        relatedOpportunity.RecurSoft__Shipping_Contact__c = relatedProdSubscription.RecurSoft__Ship_to_Contact__c;
                        relatedOpportunity.RecurSoft__Bill_to_Account__c = relatedProdSubscription.RecurSoft__Bill_to_Account__c;
                    }
                    update relatedOpportunity;

                    if(!System.isFuture() && !System.isBatch()) closeOpp(new Set<Id>{relatedOpportunity.Id});

                    renderForm = false;
                    renderConfirmation = true;
                    contractDateTime = String.valueOf(Datetime.now());
                    contractIP = ApexPages.currentPage().getHeaders().get('X-Salesforce-SIP');
                    generateContractPdf();
                
                } catch(Exception e) {

                    errorMessage = Label.GenericContractError;
                    renderForm = false;
                    renderError = true;
                    renderConfirmation = false;

                    Error_Log__c error = new Error_Log__c(
                        Error_Message__c = 'Healthgrades Contract Error(submitForm): ' + e,
                        Error_Type__c = 'Healthgrades Contract Error(submitForm)',
                        Provider__c = prov.Id,
                        Opportunity__c = relatedOpportunity.Id);
                    insert error;
                }
                
            } else {

                ApexPages.addMessage(returnFailure(errorMsg));
            }
        } 
    }

    @future
    public static void closeOpp(Set<Id> oppIds) {

        Map<ID, SObject> mapInsertSObject = new Map<ID, SObject>();
        Map<ID, SObject> mapUpdateSObject = new Map<ID, SObject>();
        Map<ID, SObject> mapDeleteSObject = new Map<ID, SObject>();

        Opportunity[] oppsToClose = [SELECT Id, StageName FROM Opportunity WHERE Id IN :oppIds];

        for(Opportunity o : oppsToClose) {

            if(o.StageName == 'Closed Won') continue;

            o.StageName = 'Closed Won';
            mapUpdateSObject.put(o.Id, o);
        }

        SRUtilities.runDml(mapInsertSObject, mapUpdateSObject, mapDeleteSObject, 'HealthgradesContractController.closeOpp');
    }

    public Boolean validateOpp(Opportunity opp) {
        
        Boolean result = true;

        if((opp.Approval_Level_Required__c != null && opp.Approval_Level_Required__c > 0) ||
            opp.Contract_Signed__c ||
            opp.StageName == 'Closed Won' ||
            opp.StageName == 'Closed Lost' ||
            opp.CloseDate < Date.today() ||
            !opp.HasOpportunityLineItem) {

            result = false;
        } 
            
        return result;
    }

    /**
     * Check required fields on contract form have been filled in and terms have been accepted.
     */
    public Boolean requiredFieldsComplete() {
        
        Boolean results = true;

        results = (!isEmptyOrNull(contactFirstName) &&
            !isEmptyOrNull(contactLastName) &&
            !isEmptyOrNull(contactPhone) &&
            !isEmptyOrNull(contactEmail) &&
            !isEmptyOrNull(signName) &&
            acceptedRenewal &&
            acceptedTerms);

        return results;
    }

    public Date calculateContractStartDate(Date d) {

        Date results = Date.today();

        if(d >= results) {

            results = d;

        } else if(Date.newInstance(Date.today().year(), Date.today().month(), d.day()) >= Date.today()) {

            results = Date.newInstance(Date.today().year(), Date.today().month(), d.day());

        } else {

            results = Date.newInstance(Date.today().addMonths(1).year(), Date.today().addMonths(1).month(), d.day());
        }

        return results;
    }

    /**
     * Initialize and populate parameters for HealthgradesPDF vf Page with the related contract information.
     * Get content of HealthgradesPDF page as PDF.
     * Call method to send and attach the resulting PDF.
     * PDF not generated in test methods because PageReference.getContent() is not supported in test methods.
     * Any errors logged on related Provider record.
     */
    public void generateContractPdf() {

        Blob body;
        String fileName = relatedContact.FirstName + '_' + relatedContact.LastName 
            + '_Healthgrades_Service_Agreement_' 
            + System.now().format('MM/dd/yyyy HH:mm:ss','America/Denver')
            + '.pdf';

        try {
            PageReference pdf = new PageReference('/apex/HealthgradesPDF');
            pdf.getParameters().put('oppId', oppId);
            pdf.getParameters().put('contractDateTime', contractDateTime);
            pdf.getParameters().put('contractSignedIP', contractIP);
            pdf.getParameters().put('contractSigner', signName);
            pdf.getParameters().put('contractTerm', contractTerm);
            pdf.getParameters().put('contractFreeMonths', contractFreeMonths);
            pdf.getParameters().put('contractDate', Datetime.newInstance(relatedAccount.Probable_Most_Recent_K_Date__c, Datetime.now().time()).format('MMM d, yyyy'));
            pdf.getParameters().put('businessName', relatedAccount.Name);
            pdf.getParameters().put('addressStreet', relatedAccount.BillingStreet);
            pdf.getParameters().put('addressCity', relatedAccount.BillingCity);
            pdf.getParameters().put('addressState', relatedAccount.BillingState);
            pdf.getParameters().put('addressPostalCode', relatedAccount.BillingPostalCode);
            pdf.getParameters().put('addressCountry', relatedAccount.BillingCountry);
            pdf.getParameters().put('providerName', relatedContact.FirstName + ' ' + relatedContact.LastName);
            pdf.getParameters().put('providerEmail', relatedContact.Email);
            pdf.getParameters().put('providerPhone', relatedContact.Phone);
            pdf.getParameters().put('providerNPI', prov.NPI__c);
            pdf.getParameters().put('providerURL', prov.Healthgrades_ID__c);

            body = Test.isRunningTest() ? Blob.valueOf('Test') : pdf.getContent();

            sendAndAttachPdf(body, fileName);

        } catch (VisualforceException e) {
            Error_Log__c error = new Error_Log__c(
                Error__c = 'There was an error creating the Healthgrades PDF: ' + e,
                Error_Type__c = 'Healthgrades PDF Creation Error',
                Provider__c = providerId);
            insert error;
        }
    }

    /**
     * OrgWideEmailAddress(sales@solutionreach.com) and Email Template Ids are set from custom settings.
     * Contract PDF attached and emailed to relatedContact email if customer checks box to receive email.
     * Contract PDF attached and emailed to applications@solutionreach.com.
     * Contract PDF attached to related contact.
     * Any errors are logged on the related Provider record.
     * @param body - PDF version of contract
     * @param fileName - Contract PDF filename
     * @see this.generateContractPdf
     */
    public void sendAndAttachPdf(Blob body, String fileName) {

        ContractEmailTemplate__c contractEmailTemplateID = ContractEmailTemplate__c.getValues('HealthgradesContract');

        Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
        attachment.setContentType('application/pdf');
        attachment.setFileName(fileName);
        attachment.setInline(false);
        attachment.body = body;

        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setUseSignature(false);
        mail.setFileAttachments(new Messaging.EmailFileAttachment[] { attachment }); 
        mail.setTemplateId(contractEmailTemplateID.TemplateID__c);
        mail.setTargetObjectId(relatedContact.Id);

        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        message.setSubject('Thank you for your business!');
        message.setPlainTextBody('Thank you for signing up for a Healthgrades Premium Profile. Please stay tuned for more information regarding our service and your personal Customer Success Representative. This email and attachment are confirmation we have received and processed your contract. Please retain a copy for your records and future reference. If you have any questions or concerns, you may contact support toll free at (866) 605-6867 or by email to support@solutionreach.com.');
        message.setFileAttachments(new Messaging.EmailFileAttachment[] { attachment });
        message.setToAddresses(new String[] { 'applications@solutionreach.com' });

        try {
            if(requestedEmail) {
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail,message });

            } else {
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] { message });
            }
            

        } catch (Exception e) {
            Error_Log__c error = new Error_Log__c(
                Error__c = 'There was an error sending the Healthgrades PDF email: ' + e,
                Error_Type__c = 'Healthgrades PDF Email Error',
                Provider__c = providerId);
            insert error;
        }

        try {
            Attachment accountAttachment = new Attachment();
            accountAttachment.ParentId = relatedOpportunity.Id;
            accountAttachment.Name = fileName;
            accountAttachment.Body = body;
            insert accountAttachment;

        } catch (Exception e) {
            Error_Log__c error = new Error_Log__c(
                Error__c = 'There was an error attaching the Healthgrades PDF to the Opportunity: ' + e,
                Error_Type__c = 'Healthgrades PDF Attachment Error',
                Provider__c = providerId);
            insert error;
        }
    }
}