src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>ApptegicEngagement__c</fullName>
        <description>Engagement score based on activity</description>
        <label>Evergage Engagement</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Day_70_Engagement_Score__c</fullName>
        <description>Records what the Engagement Score was after 70 days from signing up.</description>
        <label>Day 70 Engagement Score</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Probable_Most_Recent_K_Date__c</fullName>
        <description>Stores the most recent contract date</description>
        <inlineHelpText>This is the date the contract was likely signed</inlineHelpText>
        <label>Most Recent Contract Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.1/classes/DaySeventyEngagement.cls
global class DaySeventyEngagement implements Database.Batchable<sObject>, Schedulable {

    Date daySeventy = Date.today().addDays(-70);
    
    String query = 'SELECT Id, Probable_Most_Recent_K_Date__c, Day_70_Engagement_Score__c, ApptegicEngagement__c FROM Account WHERE Probable_Most_Recent_K_Date__c = :daySeventy';
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
    
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Account> scope) {
    
        List<Account> accList = new List<Account>();
                
        for (Account a: scope) {
        
            a.Day_70_Engagement_Score__c = a.ApptegicEngagement__c;
            accList.add(a);
        }
        update accList;
    }
    
    global void finish(Database.BatchableContext BC) {
    
    }
    
    global void execute(SchedulableContext sc) {
    
    DaySeventyEngagement batch = new DaySeventyEngagement();
    Database.executebatch(batch);
    
    }

}