src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account Lookup</description>
        <inlineHelpText>Choose the Account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Active Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.4/objects/Campaign_Influence__c.object
<CustomObject>
    <label>Campaign Influence</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Influence</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Campaign Influence</relationshipLabel>
        <relationshipName>Campaign_Influence</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campaign_Add_Date__c</fullName>
        <label>Campaign Add Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Influence</relationshipLabel>
        <relationshipName>Campaign_Influence</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Campaign Influence</relationshipLabel>
        <relationshipName>Campaign_Influence</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CreatedFromId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>CreatedFromId</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Demo_Request_Reason__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Demo Request Reason</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Campaign Influence</relationshipLabel>
        <relationshipName>Campaign_Influence</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Campaign Influence</relationshipLabel>
        <relationshipName>Campaign_Influence</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Orphaned_Date__c</fullName>
        <label>Orphaned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Orphaned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Orphaned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaign_Influences</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.1/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.3/classes/CampaignInfluencesSelector.cls
public class CampaignInfluencesSelector extends fflib_SObjectSelector 
{

	public Schema.SObjectField[] getSObjectFieldList() 
	{
		return new List<Schema.SObjectField> {
			Campaign_Influence__c.Id,
			Campaign_Influence__c.Account__c, 
        	Campaign_Influence__c.Campaign__c,
        	Campaign_Influence__c.Campaign_Add_Date__c,
        	Campaign_Influence__c.Contact__c, 
        	Campaign_Influence__c.CreatedDate,
        	Campaign_Influence__c.CreatedFromId__c,
        	Campaign_Influence__c.Demo_Request_Reason__c,
			Campaign_Influence__c.Lead__c, 
        	Campaign_Influence__c.Name, 
        	Campaign_Influence__c.Opportunity__c, 
        	Campaign_Influence__c.Orphaned__c,
        	Campaign_Influence__c.Orphaned_Date__c,
        	Campaign_Influence__c.Source_User__c
        };
	}


	public Schema.SObjectType getSObjectType()
	{
		return Campaign_Influence__c.SObjectType;
	}

	public static CampaignInfluencesSelector newInstance()
	{
		return (CampaignInfluencesSelector) Application.Selector.newInstance(Campaign_Influence__c.SObjectType);
	}

	public override String getOrderBy()
	{
		return 'Campaign_Add_Date__c DESC';
	}

	public Campaign_Influence__c[] selectCisByCreatedById(Set<Id> createdByIds)
	{
		fflib_QueryFactory campaignInfluenceQueryFactory = newQueryFactory();

		return (Campaign_Influence__c[]) Database.query(
			campaignInfluenceQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList()))
				.setCondition('CreatedFromId__c IN :createdByIds')
				.toSOQL());
	}

	public Campaign_Influence__c[] selectByIdWithManagerAndVP(Set<Id> ids)
	{
		fflib_QueryFactory campaignInfluenceQueryFactory = newQueryFactory();

		new UsersSelector().configureQueryFactoryFields(campaignInfluenceQueryFactory, 'Source_User__r');

		new UsersSelector().configureQueryFactoryFields(campaignInfluenceQueryFactory, 'Source_User__r.Manager');

		return (Campaign_Influence__c[]) Database.query(
			campaignInfluenceQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList())).setCondition('Id IN :ids').toSOQL());
	} 

	public Campaign_Influence__c[] selectCisByAccountId(Set<Id> ids)
	{
		fflib_QueryFactory campaignInfluenceQueryFactory = newQueryFactory();

		new AccountsSelector().configureQueryFactoryFields(campaignInfluenceQueryFactory, 'Account__r');

		new CampaignsSelector().configureQueryFactoryFields(campaignInfluenceQueryFactory, 'Campaign__r');

		new OpportunitiesSelector().configureQueryFactoryFields(campaignInfluenceQueryFactory, 'Account__r.Active_Opportunity__r');

		return (Campaign_Influence__c[]) Database.query(
			campaignInfluenceQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList()))
				.setCondition('Account__c IN :ids')
				.toSOQL());
	}

	public Database.QueryLocator queryLocatorContactCIWithoutAccount()
	{
		fflib_QueryFactory campaignInfluenceQueryFactory = newQueryFactory();
		
		new AccountsSelector().configureQueryFactoryFields(campaignInfluenceQueryFactory, 'Account__r');
		
		new ContactsSelector().configureQueryFactoryFields(campaignInfluenceQueryFactory, 'Contact__r');
		
		return Database.getQueryLocator(
			campaignInfluenceQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList())).
				setCondition('Contact__c != null AND Contact__r.AccountId != null AND Account__c = null').
				toSOQL());
	}
}