src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>RecurSoft__Billing_Email__c</fullName>
        <inlineHelpText>Primary billing email.</inlineHelpText>
        <label>Billing Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Status__c</fullName>
        <description>Picklist used to determine if an account is an active customer.</description>
        <inlineHelpText>Determined by the status of subscriptions (not created, created, not activated, or cancelled)</inlineHelpText>
        <label>ISB Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team_Assignment__c</fullName>
        <label>Team Assignment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Dentrix 1 Team</fullName>
                </value>
                <value>
                    <fullName>Dentrix 2 Team</fullName>
                </value>
                <value>
                    <fullName>EagleSoft Team</fullName>
                </value>
                <value>
                    <fullName>Global Team</fullName>
                </value>
                <value>
                    <fullName>SCOPE Team</fullName>
                </value>
                <value>
                    <fullName>Vision Team</fullName>
                </value>
                <value>
                    <fullName>Medical 1 Team</fullName>
                </value>
                <value>
                    <fullName>Medical 2 Team</fullName>
                </value>
                <value>
                    <fullName>Enterprise Team</fullName>
                </value>
                <value>
                    <fullName>KOL/VIP Team</fullName>
                </value>
                <value>
                    <fullName>Groups Team</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.4/objects/Case.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>Case_Owner_Team_Assignment__c</fullName>
        <description>Updated by a workflow rule to put the team of the case owner when the case is updated</description>
        <label>Case Owner Team Assignment</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Resolution__c</fullName>
        <label>Resolution</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>Wont Fix</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Cannot Reproduce</fullName>
                </value>
                <value>
                    <fullName>Resumed</fullName>
                </value>
                <value>
                    <fullName>Max Attempts Reached</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject_for_Surveys__c</fullName>
        <description>Used in Surveys when the Subject is too long.</description>
        <formula>Left( Subject , 65 )</formula>
        <label>Subject for Surveys</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Auto checks when a case is closed to ensure a contact only receives one survey per case closed</description>
        <inlineHelpText>Has a Survey been sent out?</inlineHelpText>
        <label>Survey Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Survey_to_be_Sent__c</fullName>
        <label>Survey to be Sent</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fast Track Survey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team_Assignment__c</fullName>
        <formula>text(Account.Team_Assignment__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Team Assignment</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Playbook</fullName>
        <active>true</active>
        <businessProcess>Support</businessProcess>
        <label>Playbook</label>
    </recordTypes>
    <recordTypes>
        <fullName>Support</fullName>
        <active>true</active>
        <businessProcess>Support</businessProcess>
        <description>The main case type for Support</description>
        <label>Support</label>
    </recordTypes>
</CustomObject>

force-app/main/default/objects/Case/fields/Distribution_Group__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distribution Group</label>
    <referenceTo>Distribution_Group__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src.1/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Distribution_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distribution Group</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This Distribution Group does not currently available to be used.</errorMessage>
            <filterItems>
                <field>Distribution_Group__c.HasNextUser__c</field>
                <operation>equals</operation>
                <value>1</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Distribution_Group__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Survey_Sent_Date__c</fullName>
        <description>Records the last time this Contact was sent a Survey</description>
        <label>Last Survey Sent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Survey_Opt_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Opts out the Contact from getting Surveys</description>
        <label>Survey Opt Out</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src.2/objects/Distribution_Group__c.object
<CustomObject>
    <label>Distribution Group</label>
    <nameField>
        <label>Distribution Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src.4/objects/Survey__c.object
<CustomObject>
    <description>Surveys from Customers about Sales, Cases and Cancels</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Business_Name__c</fullName>
        <label>Business Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>Surveys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Case_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Subject__c</fullName>
        <description>The Subject of the Case associated with this Survey</description>
        <label>Case Subject</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <label>Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>Surveys</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rep_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rep Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Assignment__c</fullName>
        <inlineHelpText>Team that the rep was on when closing the case</inlineHelpText>
        <label>Team Assignment</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

src.2/objects/Task.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Playbook</fullName>
        <active>true</active>
        <label>Playbook</label>
    </recordTypes>
</CustomObject>

src.4/classes/Cases.cls
public class Cases extends fflib_SObjectDomain  {

    public static Map<Id,Account> acctMap;
    public static Task[] playbookTasks;
    public Set<String> casesDistGroup;
    public static  Map <Id, Id> distributionQueue;

    public Cases(Case[] cases)
    {
        super(cases);
        Configuration.disableTriggerCRUDSecurity();

    }

    public class Constructor implements fflib_SObjectDomain.IConstructable
    {
        public fflib_SObjectDomain construct(List<SObject> sObjectList)
        {
            return new Cases(sObjectList);
        }
    }

    public override void onBeforeInsert()
    {
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        for(Case c : (Case[]) Records)
        {
            this.createSurvey(c, null, uow);
            this.queueToDistGroup(c, null);
        }

        uow.commitWork();
    }
    
    public override void onAfterInsert()
    {
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        
        for(Case c : (Case[]) Records)
        {
            this.processDistributionGroup(c, null);
        }
        
        if(casesDistGroup != null &&
                !casesDistGroup.isEmpty()) SRUtilities.scheduleAsync(casesDistGroup, 'Case_Process_Dist_Group', uow);
        
        
        
        uow.commitWork();
    }

    public override void onBeforeUpdate(Map<Id, SObject> existingRecords)
    {
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        for(Case c : (Case[]) Records)
        {
            Case existingCase = (Case) existingRecords.get(c.Id);
            this.createSurvey(c, existingCase, uow);
            this.closePlaybookTasks(c, existingCase, uow);
            this.queueToDistGroup(c, existingCase);
            this.processDistributionGroup(c, existingCase);
        }
    
        if(casesDistGroup != null &&
                !casesDistGroup.isEmpty()) SRUtilities.scheduleAsync(casesDistGroup, 'Case_Process_Dist_Group', uow);
    
        
        uow.commitWork();
    }
    
    public void processDistributionGroup(Case c, Case existingCase)
    {
        if(c.Distribution_Group__c == null) return;
        if(existingCase != null &&
                existingCase.Distribution_Group__c == c.Distribution_Group__c) return;
        
        Id distGroupId = c.Distribution_Group__c != null ? c.Distribution_Group__c : null;
        if(casesDistGroup == null) casesDistGroup = new Set<String>();
        if(distGroupId != null) casesDistGroup.add(c.Id + '::' + distGroupId + ':' + UserInfo.getUserId());
    }

    public void createSurvey(Case c, Case existingCase, fflib_SObjectUnitOfWork uow)
    {
        if(existingCase != null &&
            existingCase.Status == c.Status) return;
        if(c.ContactId == null) return;
        if(c.AccountId == null) return;
        if(c.Status != 'Closed') return;
        if(c.Resolution__c != 'Fixed') return;
        if(c.Survey_Sent__c) return;
        if(c.OwnerId == '005i0000003I9Ll') return;
        if(c.OwnerId == '00Gi0000003T8Bg') return;

        String surveyType = surveyType(c);
        if(surveyType == 'No Survey') return;

        if(acctMap == null) acctMap = AccountsSelector.newInstance().selectByIdWithContacts((Case[]) Records);
        if(acctMap.get(c.AccountId).Contacts == null) return;
        Map<Id, Contact> conMap = new Map<Id, Contact>(acctMap.get(c.AccountId).Contacts);

        if(!conMap.containsKey(c.ContactId)) return;
        if(conMap.get(c.ContactId).Survey_Opt_Out__c) return;
        if(acctMap.get(c.AccountId).RecurSoft__Status__c != 'Active') return;

        if(surveyType == 'Post Case Survey' && conMap.get(c.ContactId).HasOptedOutOfEmail) return;

        Id surveyRecordTypeId = SRUtilities.getRecordTypeMap('Survey__c').get(surveyType).getRecordTypeId();

        Survey__c newSurvey = new Survey__c();
        newSurvey.RecordTypeId = surveyRecordTypeId;
        newSurvey.Business_Name__c = c.AccountId;
        newSurvey.Contact_Name__c = c.ContactId;
        newSurvey.Case_Number__c = c.Id;
        newSurvey.Case_Subject__c = c.Subject;
        newSurvey.Contact_Email__c = conMap.get(c.ContactId).Email == '' ? acctMap.get(c.AccountId).RecurSoft__Billing_Email__c : conMap.get(c.ContactId).Email;
        newSurvey.Name = surveyType + ': ' + c.Subject_for_Surveys__c;
        newSurvey.Rep_Name__c = c.OwnerId;
        newSurvey.Team_Assignment__c = c.Case_Owner_Team_Assignment__c;

        uow.registerNew(newSurvey);

        c.Survey_Sent__c = true;
        Contact con = new Contact();
        con.Id = c.ContactId;
        con.Last_Survey_Sent_Date__c = Date.today();
        if(con.Phone == '') con.Phone = acctMap.get(c.AccountId).Phone;

        uow.registerDirty(con);

    }

    public String surveyType(Case c)
    {
        Id supportCaseId = SRUtilities.getRecordTypeMap('Case').get('Support').getRecordTypeId();
        Id syncListCaseId = SRUtilities.getRecordTypeMap('Case').get('Sync List Case').getRecordTypeId();
        Id playbookCaseId = SRUtilities.getRecordTypeMap('Case').get('Playbook').getRecordTypeId();

        if(c.RecordTypeId == playbookCaseId && c.Survey_to_be_Sent__c == 'Fast Track Survey') return 'Playbook Case Survey';
        if(c.RecordTypeId == playbookCaseId && c.Survey_to_be_Sent__c == 'EBR Case Survey') return 'EBR Case Survey';

        return c.RecordTypeId == supportCaseId || c.RecordTypeId == syncListCaseId ? 'Post Case Survey' : 'No Survey';
    }

    public void closePlaybookTasks(Case c, Case existingCase, fflib_SObjectUnitOfWork uow)
    {
        Id playbookId = SRUtilities.getRecordTypeMap('Case').get('Playbook').getRecordTypeId();
        
        if(existingCase != null && existingCase.Status == c.Status) return;
        if(c.AccountId == null) return;
        if(c.RecordTypeId != playbookId) return;
        if(c.Status != 'Closed') return;
        if(c.Resolution__c != 'Fixed') return;
    
    
        if(playbookTasks == null) playbookTasks = TasksSelector.newInstance().getPlaybookTasks((Case[]) Records);

        for(Task t : playbookTasks)
        {
            if(t.WhatId == c.Id)
            {
                t.Status = 'Closed - Not Completed';
                uow.registerDirty(t);
            }
        }
    }
    
    public void queueToDistGroup(Case c, Case existingCase)
    {
        if(String.valueOf(c.OwnerId).startsWith('OO5')) return;
        if(existingCase != null && c.OwnerId == existingCase.OwnerId) return;
        if(distributionQueue == null) distributionQueue = DistributionGroupsSelector.getQueueDistributionMap();
        if(!distributionQueue.containsKey(c.OwnerId)) return;
        
        c.Distribution_Group__c = distributionQueue.get(c.OwnerId) ;
    }
    
}