src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>RecurSoft__Status__c</fullName>
        <description>Picklist used to determine if an account is an active customer.</description>
        <inlineHelpText>Determined by the status of subscriptions (not created, created, not activated, or cancelled)</inlineHelpText>
        <label>ISB Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.4/objects/Case.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Administrative</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Technical</fullName>
                </value>
                <value>
                    <fullName>Collections</fullName>
                </value>
                <value>
                    <fullName>Generic</fullName>
                </value>
                <value>
                    <fullName>Change Payment Terms</fullName>
                </value>
                <value>
                    <fullName>Feature Enhancement</fullName>
                </value>
                <value>
                    <fullName>Open Invoice</fullName>
                </value>
                <value>
                    <fullName>Past Due</fullName>
                </value>
                <value>
                    <fullName>Setup Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SR Platform</fullName>
                </value>
                <value>
                    <fullName>SR Sync</fullName>
                </value>
                <value>
                    <fullName>PatientReach</fullName>
                </value>
                <value>
                    <fullName>One Desk</fullName>
                </value>
                <value>
                    <fullName>Simpletrac</fullName>
                </value>
                <value>
                    <fullName>SR Enterprise</fullName>
                </value>
                <value>
                    <fullName>Healthgrades</fullName>
                </value>
                <value>
                    <fullName>Limelight</fullName>
                </value>
                <value>
                    <fullName>SR Conversations</fullName>
                </value>
                <value>
                    <fullName>SR Smart Reviews</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resolution__c</fullName>
        <label>Resolution</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>Wont Fix</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Cannot Reproduce</fullName>
                </value>
                <value>
                    <fullName>Resumed</fullName>
                </value>
                <value>
                    <fullName>Max Attempts Reached</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Survey_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Auto checks when a case is closed to ensure a contact only receives one survey per case closed</description>
        <inlineHelpText>Has a Survey been sent out?</inlineHelpText>
        <label>Survey Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Survey_to_be_Sent__c</fullName>
        <label>Survey to be Sent</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fast Track Survey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Playbook</fullName>
        <active>true</active>
        <businessProcess>Support</businessProcess>
        <label>Playbook</label>
    </recordTypes>
    <recordTypes>
        <fullName>Support</fullName>
        <active>true</active>
        <businessProcess>Support</businessProcess>
        <description>The main case type for Support</description>
        <label>Support</label>
    </recordTypes>
</CustomObject>

src.1/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Survey_Opt_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Opts out the Contact from getting Surveys</description>
        <label>Survey Opt Out</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src.4/objects/Survey__c.object
<CustomObject>
    <description>Surveys from Customers about Sales, Cases and Cancels</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Business_Name__c</fullName>
        <label>Business Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>Surveys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <label>Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>Surveys</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

src.2/objects/Task.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Playbook</fullName>
        <active>true</active>
        <label>Playbook</label>
    </recordTypes>
</CustomObject>

src.2/classes/Cases_Test.cls
/**
 * Created by mschetselaar on 8/23/2018.
 */

@IsTest
private class Cases_Test {

    @TestSetup
    static void testSetup()
    {
        TestUtilities.newInit();
    }
    
    @isTest
    static void test_onBeforeInsert()
    {
        sfab_FabricatedSObject cFab = TestUtilities2.newCases();

        Case ca = (Case) cFab.toSObject();

        Case existingCase = (Case) TestUtilities2.existingCase(cFab).toSObject();

        Cases cases = new Cases(new List<Case>{ ca });
        Cases.onBeforeInsert();

    }

    @isTest
    static void test_onBeforeUpdate()
    {
        sfab_FabricatedSObject cFab = TestUtilities2.newCases();

        Case ca = (Case) cFab.toSObject();

        Case existingCase = (Case) TestUtilities2.existingCase(cFab).toSObject();

        Cases cases = new Cases(new List<Case> { ca});
        Map<Id, SObject> caseMap = new Map<Id, SObject>( new List<Case>{ ca });
        Cases.onBeforeUpdate(caseMap);
    }

    @isTest
    static void test_createSurvey_NoContacts()
    {
        fflib_ApexMocks mocks = new fflib_ApexMocks();  
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        
        Account acct = (Account) TestUtilities2.newAccount().toSObject(); 

        sfab_FabricatedSObject cFab = TestUtilities2.newCases()
            .setField(Case.AccountId, acct.Id)
            .setField(Case.Subject, 'Test')
            .setField(Case.RecordTypeId, SRUtilities.getRecordTypeMap('Case').get('Support').getRecordTypeId())
            .setField(Case.Status, 'Closed')
            .setField(Case.Survey_Sent__c, false)
            .setField(Case.Resolution__c, 'Fixed');

        Case c = (Case) cFab.toSObject();

        AccountsSelector mockSelector = (AccountsSelector) mocks.mock(AccountsSelector.class);

        mocks.startStubbing();
        mocks.when(mockSelector.getSObjectType2())
            .thenReturn(Account.SObjectType);
        mocks.when(mockSelector.selectByIdWithContacts(new List<Case>{ c }))
            .thenReturn(new Map<Id, Account>(new List<Account>{ acct }));
        mocks.stopStubbing();

        Application.Selector.setMock(mockSelector);

        Cases cases = new Cases(new List<Case>{ c });
        cases.createSurvey(c, null, uow);
        System.assertEquals(0, uow.m_newListByType.get('Survey__c').size());
    }

    @isTest
    static void test_createSurvey_NoStatusChange()
    {
        fflib_ApexMocks mocks = new fflib_ApexMocks();  
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        
        sfab_FabricatedSObject conFab = TestUtilities2.newContact()
            .setField(Contact.FirstName, 'Test')
            .setField(Contact.LastName, 'Last')
            .setField(Contact.Survey_Opt_Out__c, false)
            .setField(Contact.Email, 'test@test.com'); 

        Contact con = (Contact) conFab.toSObject();

        Account acct = (Account) TestUtilities2.newAccount()
            .setField(Account.RecurSoft__Status__c, 'Active')
            .setChildren('Contacts', new List<sfab_FabricatedSObject> { conFab })
            .toSObject();

        sfab_FabricatedSObject cFab = TestUtilities2.newCases()
            .setField(Case.AccountId, acct.Id)
            .setField(Case.ContactId, con.Id)
            .setField(Case.Subject, 'Test')
            .setField(Case.RecordTypeId, SRUtilities.getRecordTypeMap('Case').get('Support').getRecordTypeId())
            .setField(Case.Status, 'Closed')
            .setField(Case.Survey_Sent__c, false)
            .setField(Case.Resolution__c, 'Fixed');

        Case c = (Case) cFab.toSObject();
        Case existingCase = (Case) TestUtilities2.existingCase(cFab)
            .setField(Case.Status, 'Closed')
            .toSObject();

        AccountsSelector mockSelector = (AccountsSelector) mocks.mock(AccountsSelector.class);

        mocks.startStubbing();
        mocks.when(mockSelector.getSObjectType2())
            .thenReturn(Account.SObjectType);
        mocks.when(mockSelector.selectByIdWithContacts(new List<Case>{ c }))
            .thenReturn(new Map<Id, Account>(new List<Account>{ acct }));
        mocks.stopStubbing();

        Application.Selector.setMock(mockSelector);

        Cases cases = new Cases(new List<Case>{ c });
        cases.createSurvey(c, existingCase, uow);

        System.assertEquals(0, uow.m_newListByType.get('Survey__c').size());
    }
    @IsTest
    static void test_createSurvey_SupportCase()
    {
//        TestUtilities.newInit();

        Account a = [SELECT Id, RecurSoft__Status__c FROM Account LIMIT 1];
        a.RecurSoft__Status__c = 'Active';
        update a;

        Contact con = new Contact();
        con.FirstName = 'Test';
        con.LastName = 'Last';
        con.Survey_Opt_Out__c = false;
        con.AccountId = a.Id;
        con.Email = 'test@test.com';
        insert con;

        Case ca = new Case();
        ca.AccountId = a.Id;
        ca.ContactId = con.Id;
        ca.Subject = 'Test';
        ca.RecordTypeId = SRUtilities.getRecordTypeMap('Case').get('Support').getRecordTypeId();
        ca.Status = 'New';
        ca.Survey_Sent__c = false;
        insert ca;

        ca.Status = 'Closed';
        ca.Resolution__c = 'Fixed';
        ca.Category__c = 'Sync';
        ca.Product__c = 'Sync Filters';

        Test.startTest();
            Database.SaveResult sr = Database.update(ca);
        Test.stopTest();

        Survey__c[] surveys = [SELECT Id, Business_Name__c, Contact_Name__c, Contact_Email__c, RecordTypeId FROM Survey__c];
        Id postCaseSurvey = SRUtilities.getRecordTypeMap('Survey__c').get('Post Case Survey').getRecordTypeId();

        System.assert(sr.isSuccess());
        System.assertEquals(1,surveys.size());
        System.assertEquals(a.Id,surveys[0].Business_Name__c);
        System.assertEquals(con.Id,surveys[0].Contact_Name__c);
        System.assertEquals('test@test.com', surveys[0].Contact_Email__c);
        System.assertEquals(postCaseSurvey, surveys[0].RecordTypeId);

    }

    @IsTest
    static void test_createSurvey_FastTrackCase()
    {
//        TestUtilities.newInit();

        Account a = [SELECT Id, RecurSoft__Status__c FROM Account LIMIT 1];
        a.RecurSoft__Status__c = 'Active';
        update a;

        Contact con = new Contact();
        con.FirstName = 'Test';
        con.LastName = 'Last';
        con.Survey_Opt_Out__c = false;
        con.AccountId = a.Id;
        con.Email = 'test@test.com';
        insert con;

        Case ca = new Case();
        ca.AccountId = a.Id;
        ca.ContactId = con.Id;
        ca.Subject = 'Test';
        ca.RecordTypeId = SRUtilities.getRecordTypeMap('Case').get('Playbook').getRecordTypeId();
        ca.Status = 'New';
        ca.Survey_Sent__c = false;
        ca.Survey_to_be_Sent__c = 'Fast Track Survey';
        insert ca;

        ca.Status = 'Closed';
        ca.Resolution__c = 'Fixed';

        Test.startTest();
        Database.SaveResult sr = Database.update(ca);
        Test.stopTest();

        Survey__c[] surveys = [SELECT Id, Business_Name__c, Contact_Name__c, Contact_Email__c, RecordTypeId FROM Survey__c];
        Id postCaseSurvey = SRUtilities.getRecordTypeMap('Survey__c').get('Playbook Case Survey').getRecordTypeId();

        System.assert(sr.isSuccess());
        System.assertEquals(1,surveys.size());
        System.assertEquals(a.Id,surveys[0].Business_Name__c);
        System.assertEquals(con.Id,surveys[0].Contact_Name__c);
        System.assertEquals('test@test.com', surveys[0].Contact_Email__c);
        System.assertEquals(postCaseSurvey, surveys[0].RecordTypeId);

    }

    @IsTest
    static void test_createSurvey_EBRCase()
    {
//        TestUtilities.newInit();

        Account a = [SELECT Id, RecurSoft__Status__c FROM Account LIMIT 1];
        a.RecurSoft__Status__c = 'Active';
        update a;

        Contact con = new Contact();
        con.FirstName = 'Test';
        con.LastName = 'Last';
        con.Survey_Opt_Out__c = false;
        con.AccountId = a.Id;
        con.Email = 'test@test.com';
        insert con;

        Case ca = new Case();
        ca.AccountId = a.Id;
        ca.ContactId = con.Id;
        ca.Subject = 'Test';
        ca.RecordTypeId = SRUtilities.getRecordTypeMap('Case').get('Playbook').getRecordTypeId();
        ca.Status = 'New';
        ca.Survey_Sent__c = false;
        ca.Survey_to_be_Sent__c = 'EBR Case Survey';
        insert ca;

        ca.Status = 'Closed';
        ca.Resolution__c = 'Fixed';

        Test.startTest();
            Database.SaveResult sr = Database.update(ca);
        Test.stopTest();

        Survey__c[] surveys = [SELECT Id, Business_Name__c, Contact_Name__c, Contact_Email__c, RecordTypeId FROM Survey__c];
        Id postCaseSurvey = SRUtilities.getRecordTypeMap('Survey__c').get('EBR Case Survey').getRecordTypeId();

        System.assert(sr.isSuccess());
        System.assertEquals(1,surveys.size());
        System.assertEquals(a.Id,surveys[0].Business_Name__c);
        System.assertEquals(con.Id,surveys[0].Contact_Name__c);
        System.assertEquals('test@test.com', surveys[0].Contact_Email__c);
        System.assertEquals(postCaseSurvey, surveys[0].RecordTypeId);

    }

    @IsTest
    static void test_closePlaybookTasks()
    {
        Account a = [SELECT Id, RecurSoft__Status__c FROM Account LIMIT 1];
        a.RecurSoft__Status__c = 'Active';
        update a;
        
        Case ca = new Case();
        ca.AccountId = a.Id;
        ca.Subject = 'Test';
        ca.RecordTypeId = SRUtilities.getRecordTypeMap('Case').get('Playbook').getRecordTypeId();
        ca.Status = 'New';
        ca.Survey_Sent__c = false;
        insert ca;
    
        Id playbookTask = SRUtilities.getRecordTypeMap('Task').get('Playbook').getRecordTypeId();
        Task t = new Task();
        t.RecordTypeId = playbookTask;
        t.Subject = 'Test Task';
        t.Status = 'Scheduled';
        t.Priority = 'Normal';
        t.WhatId = ca.Id;
        t.ActivityDate = Date.today().addDays(5);
        insert t;
    
        ca.Status = 'Closed';
        ca.Resolution__c = 'Fixed';
        
        Test.startTest();
            Database.SaveResult sr = Database.update(ca);
        Test.stopTest();
        
        Task t1 = [SELECT Id, Subject, Status FROM Task LIMIT 1];
    
        System.assert(sr.isSuccess());
        System.assertEquals('Closed - Not Completed', t1.Status);
    }
}