src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Account_Sales_Status__c</fullName>
        <label>Account Sales Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Contacted</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Bogus</fullName>
                </value>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RecurSoft__Status__c</fullName>
        <description>Picklist used to determine if an account is an active customer.</description>
        <inlineHelpText>Determined by the status of subscriptions (not created, created, not activated, or cancelled)</inlineHelpText>
        <label>ISB Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Affiliate</fullName>
        <active>true</active>
        <description>Any individual, doctor, speaker/consultant, SR customer or non-SR customer who promotes Solutionreach and is signed up through our affiliate program.</description>
        <label>Affiliate/KOL</label>
    </recordTypes>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <label>PM/EHR Partner</label>
    </recordTypes>
</CustomObject>

src.1/objects/SR_Default_Values__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SR Default Values</label>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

src.4/classes/Five9LSP.cls
global class Five9LSP implements Database.Batchable<sObject> 
{
	SR_Default_Values__c defaultValues = SR_Default_Values__c.getValues('Campaign Influence Orphan Days');
	SR_Default_Values__c defaultValues2 = SR_Default_Values__c.getValues('Opportunity Closed Lost Days');
	String listId = defaultValues2.Value__c;
	Integer limitNumber = Integer.valueOf(defaultValues.Value__c);

	String query = 'SELECT Id FROM Account WHERE ' +
	'ParentId = null AND RecurSoft__Status__c != \'Active\' AND Account_Sales_Status__c NOT IN (\'Bogus\',\'Duplicate\') ' +
	'and id not in (select five9lsp__Account__c from Five9LSP__Five9_List_Item__c) ' +
	'and recordtype.name not in (\'Affiliate/KOL\',\'Enterprise DHC\',\'PM/EHR Partner\',\'Partner\') LIMIT :limitNumber';	
	
	global Database.QueryLocator start(Database.BatchableContext BC) 
	{
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) 
   	{
		SObject[] itemsToInsert = new List<SObject>();
		for(Account a : (Account[]) scope)
		{
			Five9LSP__Five9_List_Item__c item = new Five9LSP__Five9_List_Item__c(five9lsp__Account__c = a.Id,
				Five9LSP__Five9_List__c = listId);
			itemsToInsert.add(item);
		}
		insert itemsToInsert;
	}
	
	global void finish(Database.BatchableContext BC) 
	{
		Account[] accts = [SELECT Id FROM Account WHERE 
			ParentId = null AND RecurSoft__Status__c != 'Active' AND Account_Sales_Status__c NOT IN ('Bogus','Duplicate')
			and id not in (select five9lsp__Account__c from Five9LSP__Five9_List_Item__c)
			and recordtype.name not in ('Affiliate/KOL','Enterprise DHC','PM/EHR Partner','Partner') LIMIT :limitNumber];

		Integer nonBatchAsyncApexJobs = [SELECT count() FROM AsyncApexJob WHERE JobType != 'BatchApexWorker' AND JobType != 'BatchApex' AND CreatedDate >= :DateTime.now().addDays(-1)];
		AggregateResult[] ar = [SELECT SUM(JobItemsProcessed) FROM AsyncApexJob WHERE JobType = 'BatchApex' AND CreatedDate >= :DateTime.now().addDays(-1)];
		Integer batchJobItemsProcessed = Integer.valueOf(ar[0].get('expr0'));
		Integer total = nonBatchAsyncApexJobs + batchJobItemsProcessed;

		if(accts.size() > 1000 && total < 300000) 
		{
			Five9LSP batchable = new Five9LSP();
			Database.executeBatch(batchable);
		}		
	}
}