src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Sub_Vertical__c</fullName>
        <label>Sub-Vertical</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Allergy &amp; Immunology</fullName>
                </value>
                <value>
                    <fullName>Bariatric, Metabolic and Weight Health</fullName>
                </value>
                <value>
                    <fullName>Chiropractic</fullName>
                </value>
                <value>
                    <fullName>Cosmetic Surgery</fullName>
                </value>
                <value>
                    <fullName>Dermatology</fullName>
                </value>
                <value>
                    <fullName>Endocrinology</fullName>
                </value>
                <value>
                    <fullName>Endodontistry</fullName>
                </value>
                <value>
                    <fullName>ENT-Otolaryngology</fullName>
                </value>
                <value>
                    <fullName>Family Medicine or General Physician</fullName>
                </value>
                <value>
                    <fullName>Gastroenterology</fullName>
                </value>
                <value>
                    <fullName>General Dentistry</fullName>
                </value>
                <value>
                    <fullName>General Surgery</fullName>
                </value>
                <value>
                    <fullName>Geriatric Medicine</fullName>
                </value>
                <value>
                    <fullName>Heart and Vascular</fullName>
                </value>
                <value>
                    <fullName>HIV/Infectious Disease</fullName>
                </value>
                <value>
                    <fullName>Internal Medicine</fullName>
                </value>
                <value>
                    <fullName>Medical Spa or Aesthetic Medicine</fullName>
                </value>
                <value>
                    <fullName>Neurology</fullName>
                </value>
                <value>
                    <fullName>Non-medical</fullName>
                </value>
                <value>
                    <fullName>OB/GYN or Womens Health</fullName>
                </value>
                <value>
                    <fullName>Oncology</fullName>
                </value>
                <value>
                    <fullName>Ophthalmology</fullName>
                </value>
                <value>
                    <fullName>Optometry</fullName>
                </value>
                <value>
                    <fullName>Oral Surgery</fullName>
                </value>
                <value>
                    <fullName>Orthodontistry</fullName>
                </value>
                <value>
                    <fullName>Orthopedics</fullName>
                </value>
                <value>
                    <fullName>Orthotics/Prosthetics</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pain Management or Physical Medicine or Physiatry</fullName>
                </value>
                <value>
                    <fullName>Pediatrics</fullName>
                </value>
                <value>
                    <fullName>Podiatry</fullName>
                </value>
                <value>
                    <fullName>Dental</fullName>
                    <isActive>false</isActive>
                    <label>Dental</label>
                </value>
                <value>
                    <fullName>Orthodontics</fullName>
                    <isActive>false</isActive>
                    <label>Orthodontics</label>
                </value>
                <value>
                    <fullName>Plastic Surgery</fullName>
                    <isActive>false</isActive>
                    <label>Plastic Surgery</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.4/objects/Case.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Administrative</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Technical</fullName>
                </value>
                <value>
                    <fullName>Collections</fullName>
                </value>
                <value>
                    <fullName>Generic</fullName>
                </value>
                <value>
                    <fullName>Change Payment Terms</fullName>
                </value>
                <value>
                    <fullName>Feature Enhancement</fullName>
                </value>
                <value>
                    <fullName>Open Invoice</fullName>
                </value>
                <value>
                    <fullName>Past Due</fullName>
                </value>
                <value>
                    <fullName>Setup Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SR Platform</fullName>
                </value>
                <value>
                    <fullName>SR Sync</fullName>
                </value>
                <value>
                    <fullName>PatientReach</fullName>
                </value>
                <value>
                    <fullName>One Desk</fullName>
                </value>
                <value>
                    <fullName>Simpletrac</fullName>
                </value>
                <value>
                    <fullName>SR Enterprise</fullName>
                </value>
                <value>
                    <fullName>Healthgrades</fullName>
                </value>
                <value>
                    <fullName>Limelight</fullName>
                </value>
                <value>
                    <fullName>SR Conversations</fullName>
                </value>
                <value>
                    <fullName>SR Smart Reviews</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Topics__c</fullName>
        <label>Topics</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active Monitor</fullName>
                </value>
                <value>
                    <fullName>Active Push</fullName>
                </value>
                <value>
                    <fullName>Active Review</fullName>
                </value>
                <value>
                    <fullName>Admin</fullName>
                </value>
                <value>
                    <fullName>Birthdays</fullName>
                </value>
                <value>
                    <fullName>Contract Addendum</fullName>
                </value>
                <value>
                    <fullName>Dashboard</fullName>
                </value>
                <value>
                    <fullName>Eyewear</fullName>
                </value>
                <value>
                    <fullName>Filters</fullName>
                </value>
                <value>
                    <fullName>General Training</fullName>
                </value>
                <value>
                    <fullName>Groups</fullName>
                </value>
                <value>
                    <fullName>Installation</fullName>
                </value>
                <value>
                    <fullName>Local Listing</fullName>
                </value>
                <value>
                    <fullName>Maps</fullName>
                </value>
                <value>
                    <fullName>Messaging</fullName>
                </value>
                <value>
                    <fullName>New Integration</fullName>
                </value>
                <value>
                    <fullName>Newsletters</fullName>
                </value>
                <value>
                    <fullName>Password</fullName>
                </value>
                <value>
                    <fullName>Patient Manager</fullName>
                </value>
                <value>
                    <fullName>PatientReach</fullName>
                </value>
                <value>
                    <fullName>PatientView</fullName>
                </value>
                <value>
                    <fullName>Recall</fullName>
                </value>
                <value>
                    <fullName>Referrals</fullName>
                </value>
                <value>
                    <fullName>Reminders</fullName>
                </value>
                <value>
                    <fullName>Reports</fullName>
                </value>
                <value>
                    <fullName>Schedule</fullName>
                </value>
                <value>
                    <fullName>SmileDash</fullName>
                </value>
                <value>
                    <fullName>Social Networking</fullName>
                </value>
                <value>
                    <fullName>Surveys</fullName>
                </value>
                <value>
                    <fullName>Sync Down</fullName>
                </value>
                <value>
                    <fullName>Healthgrades</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Support</fullName>
        <active>true</active>
        <businessProcess>Support</businessProcess>
        <description>The main case type for Support</description>
        <label>Support</label>
    </recordTypes>
</CustomObject>

force-app/main/default/objects/Provider__c/Provider__c.object-meta.xml
<CustomObject>
    <description>Used to store information about individual Providers within a Practice.  The Provider information is used for Healthgrades Premium members.</description>
    <label>Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Provider__c/fields/Bill_to_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The related account that will be billed for the Provider&#39;s Healthgrades subscription.</description>
    <inlineHelpText>The related account that will be billed for the Provider&#39;s Healthgrades subscription.</inlineHelpText>
    <label>Bill to Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Providers</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Healthgrades_ID__c.field-meta.xml
<CustomField>
    <fullName>Healthgrades_ID__c</fullName>
    <description>The individual Provider&#39;s unique Healthgrades identifier.</description>
    <externalId>true</externalId>
    <label>Healthgrades ID</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Provider__c/fields/NPI__c.field-meta.xml
<CustomField>
    <fullName>NPI__c</fullName>
    <description>A National Provider Identifier or NPI is a unique 10-digit identification number issued to health care providers in the United States by the Centers for Medicare and Medicaid Services (CMS).</description>
    <label>NPI</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Premium_Member__c.field-meta.xml
<CustomField>
    <fullName>Premium_Member__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the Provider is currently paying for a Healthgrades Premium Profile.</description>
    <inlineHelpText>Checked if the Provider is currently paying for a Healthgrades Premium Profile.</inlineHelpText>
    <label>Premium Member</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/RecordType_Override__c.field-meta.xml
<CustomField>
    <fullName>RecordType_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <label>RecordType Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Related_Contact__c.field-meta.xml
<CustomField>
    <fullName>Related_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Provider&#39;s contact information is accessed via the Related Contact field.</description>
    <inlineHelpText>The Provider&#39;s contact information is accessed via the Related Contact field.</inlineHelpText>
    <label>Related Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Providers</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

src.2/classes/ProviderUtilities.cls
public class ProviderUtilities {

	public static Map<Id, Account> getRelatedAccounts(Provider__c[] newProviders) {

    	Set<ID> acctIds = new Set<ID>();

    	for(Provider__c p : newProviders) {
    		acctIds.add(p.Bill_to_Account__c);
    	}

    	Map<Id, Account> results = new Map<Id, Account>([SELECT Id,
	    	Industry, 
	    	Sub_vertical__c 
	    	FROM Account
	   		WHERE Id IN: acctIds]);

    	return results;
	}

	public static void newHealthgradesCase(Map<Id,Provider__c> oldProviderMap, Provider__c[] updatedProviders) {

		String HG_QUEUE_ID = [SELECT Id FROM Group WHERE Type = 'Queue' AND Name = 'Healthgrades Onboarding Queue'].Id;
		Map<Id, SObject> mapInsertSObject = new Map<Id, SObject>();
      	Map<Id, SObject> mapUpdateSObject = new Map<Id, SObject>();
      	Map<Id, SObject> mapDeleteSObject = new Map<Id, SObject>();

		for(Provider__c p : updatedProviders) {

			if(oldProviderMap.get(p.Id).Premium_Member__c == false && p.Premium_Member__c == true) {

				Case newCase = new Case(Subject = 'Healthgrades Implementation: ' + p.Name,
					AccountId = p.Bill_to_Account__c,
					ContactId = p.Related_Contact__c,
					RecordTypeId = SRUtilities.getRecordTypeMap('Case').get('Support').getRecordTypeId(),
					Product__c = 'Healthgrades',
					Origin = 'Web',
					Category__c = 'Training',
					Topics__c = 'General Training',
					Description = 'Healthgrades URL: ' + p.Healthgrades_ID__c + '\n' + 'Provider NPI: ' + p.NPI__c,
					OwnerId = HG_QUEUE_ID);

				mapInsertSObject.put(p.Id, newCase);
			}
		}

		SRUtilities.runDml(mapInsertSObject, mapUpdateSObject, mapDeleteSObject, 'ProviderUtilities.newHealthgradesCase');
	}

	public static void syncOnPremiumChange(Map<Id,Provider__c> oldProviderMap, Provider__c[] updatedProviders) {

		Set<Id> providerIds = new Set<Id>();

		for(Provider__c p : updatedProviders) {

			if(oldProviderMap.get(p.Id).Premium_Member__c != p.Premium_Member__c) {

				providerIds.add(p.Id);
			}
		}

		if(!providerIds.isEmpty()) { 
			AppAdminAPIClass.postHealthgradesStatus(providerIds); 
		}
	}

	public static void cleanHealthgradesUrl(Provider__c[] newProviders) {

		for(Provider__c p : newProviders) {

			if(p.Healthgrades_ID__c.contains('?')) {

				p.Healthgrades_ID__c = p.Healthgrades_ID__c.split('\\?')[0];
			}
		}
	}

	public static void setRecordType(Provider__c[] updatedProviders, Map<Id, Account> relatedAccountMap) {

		for(Provider__c p : updatedProviders) {

			if(p.RecordType_Override__c) continue;

			Account a = relatedAccountMap.get(p.Bill_to_Account__c);

			if(a.Industry == 'Dental' && a.Sub_vertical__c != 'Orthodontistry') {

				p.RecordTypeId = SRUtilities.getRecordTypeMap('Provider__c').get('Dentistry').getRecordTypeId();
			
			} else if(a.Sub_vertical__c == 'Dermatology') {

				p.RecordTypeId = SRUtilities.getRecordTypeMap('Provider__c').get('Dermatology').getRecordTypeId();
			
			} else if(a.Sub_vertical__c == 'Ophthalmology') {

				p.RecordTypeId = SRUtilities.getRecordTypeMap('Provider__c').get('Ophthalmology').getRecordTypeId();
			
			} else if(a.Sub_vertical__c == 'Optometry') {

				p.RecordTypeId = SRUtilities.getRecordTypeMap('Provider__c').get('Optometry').getRecordTypeId();
			
			} else if(a.Sub_vertical__c == 'Orthodontistry') {

				p.RecordTypeId = SRUtilities.getRecordTypeMap('Provider__c').get('Orthodontics').getRecordTypeId();
			
			} else if(a.Sub_vertical__c == 'Cosmetic Surgery') {

				p.RecordTypeId = SRUtilities.getRecordTypeMap('Provider__c').get('Plastic Surgery').getRecordTypeId();
                
            } else if(a.Sub_Vertical__c == 'Podiatry') {
                
                p.RecordTypeId = SRUtilities.getRecordTypeMap('Provider__c').get('Podiatry').getRecordTypeId();
            
            }
		}
	}
}