src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Subscriber_ID__c</fullName>
        <description>The subscriber ID from App Admin</description>
        <label>Subscriber ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.4/objects/AppAdminAPI_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>AppAdminAPI Settings</label>
    <fields>
        <fullName>isProduction__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isProduction</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>practiceNameLength__c</fullName>
        <description>Allowable practice name length for AppAdmin</description>
        <label>practiceNameLength</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>productionPassword__c</fullName>
        <description>AppAdmin password for Production Server.</description>
        <label>productionPassword</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>productionRequestUrl__c</fullName>
        <description>URL for GET from AppAdmin Production Server</description>
        <label>productionRequestUrl</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>productionTargetUrl__c</fullName>
        <description>URL to POST to AppAdmin Production Server</description>
        <label>productionTargetUrl</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>productionUsername__c</fullName>
        <description>AppAdmin username for Production Server.</description>
        <label>productionUsername</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RequestType__c</fullName>
        <label>RequestType</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sandboxPassword__c</fullName>
        <description>AppAdmin password for Test Server</description>
        <label>sandboxPassword</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sandboxRequestUrl__c</fullName>
        <description>URL for GET from AppAdmin Test Server</description>
        <label>sandboxRequestUrl</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sandboxTargetUrl__c</fullName>
        <description>URL to POST to AppAdmin Test Server</description>
        <label>sandboxTargetUrl</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sandboxUsername__c</fullName>
        <description>AppAdmin username for Test Server</description>
        <label>sandboxUsername</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>successStatusCode__c</fullName>
        <description>Status code returned by AppAdmin for success.</description>
        <label>successStatusCode</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the related Provider record</description>
        <inlineHelpText>Link to the related Provider record</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscriber_ID__c</fullName>
        <formula>Case(Account.Subscriber_ID__c,&quot;&quot;,&quot;&quot;,Account.Subscriber_ID__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subscriber ID</label>
        <type>Text</type>
    </fields>
</CustomObject>

src.3/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related Provider for the Healthgrades Premium Profile</description>
        <inlineHelpText>The related Provider for the Healthgrades Premium Profile</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.1/objects/Pricebook2.object
<CustomObject>
    <sharingModel>ReadSelect</sharingModel>
    <fields>
        <fullName>Number_of_PRT_Included__c</fullName>
        <label>Number of PRT Included</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Provider__c/Provider__c.object-meta.xml
<CustomObject>
    <description>Used to store information about individual Providers within a Practice.  The Provider information is used for Healthgrades Premium members.</description>
    <label>Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AppAdminAPIClassNew_Test.cls
@isTest
private class AppAdminAPIClassNew_Test {
	
	@isTest static void test_providerAPICall() {

		Set<Id> providerIds = new Set<Id>();
		Account a = TestUtilities.insertBasicAccount(true);

		for(Integer i = 0; i < 5; i++) {
			Contact c = TestUtilities.insertBasicContact(a.Id);
			Provider__c p = TestUtilities.insertProvider(a.Id, c.Id, String.valueOf(i));
			providerIds.add(p.Id);
		}

		AppAdminAPIClassNew.postHealthgradesStatus(providerIds);
	}

	@isTest static void test_syncOpportunityAppAdmin() 
	{
		fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
		fflib_ApexMocks mocks = new fflib_ApexMocks();
		Set<Id> oppIds = new Set<Id>();
		Map<String, OpportunityContactRole> oppContactR = new Map<String, OpportunityContactRole>();

		OpportunityContactRole oppContactRole = (OpportunityContactRole) TestUtilities2.newOpportunityContactRole()
			.setField(OpportunityContactRole.Role, 'Billing Contact')
			.toSObject();

		OpportunityContactRole oppContactRole2 = (OpportunityContactRole) TestUtilities2.newOpportunityContactRole()
			.setField(OpportunityContactRole.Role, 'Business Contact')
			.toSObject();

		oppContactR.put('Billing Contact', oppContactRole);
		oppContactR.put('Business Contact', oppContactRole2);

		sfab_FabricatedSObject acFab = TestUtilities2.newAccount()
			.setField(Account.Subscriber_Id__c, 'test')
			.setField(Account.Name, 'testName');
		
		Account ac = (Account) acFab.toSObject();			

		sfab_FabricatedSObject pr = TestUtilities2.newProduct()
			.setField(Product2.Family, 'SR Platform');  

		sfab_FabricatedSObject pbe = TestUtilities2.newPricebookEntry()
			.setField(PricebookEntry.UnitPrice, 1)
			.setParent('Product2', pr);

		sfab_FabricatedSObject pbe2 = TestUtilities2.newPricebookEntry();

		Pricebook2 pb = (Pricebook2) TestUtilities2.newPricebook2()
			.setField(Pricebook2.Number_of_PRT_Included__c, 20)
			.setChildren('PricebookEntries', new List<sfab_FabricatedSObject> { pbe, pbe2 })
			.toSObject();
		
		sfab_FabricatedSObject oppLi = TestUtilities2.newOpportunityLineItem()			
        	.setField(OpportunityLineItem.PricebookEntryId, ((PricebookEntry) pbe2.toSObject()).Id)
        	.setParent('PricebookEntry', pbe); 
      
		sfab_FabricatedSObject opFab = TestUtilities2.newOpportunity() 
			.setField(Opportunity.AccountId, ac.Id)    
			.setParent('Account', acFab)       
            .setChildren('OpportunityLineItems', new List<sfab_FabricatedSObject> {oppLi});               

        insert new AppAdminAPI_Settings__c(Name = 'APISettings',
            isProduction__c = false,
            successStatusCode__c = '201',
            practiceNameLength__c = 33,
            productionUsername__c = 'srsalesforce',
            sandboxUsername__c = 'srsalesforce',
            productionPassword__c = '>%p|8u/.K2E?Ji"Gc-]a',
            sandboxPassword__c = 'nottherealpassword',
            productionTargetUrl__c = 'https://sfapi.solutionreach.com/admin/applications',
            sandboxTargetUrl__c = 'https://salesforce.solutionreach.com/admin/applications',
            productionRequestUrl__c = 'https://sfapi.solutionreach.com/admin/subscribers/',
            sandboxRequestUrl__c = 'https://salesforce.solutionreach.com/admin/subscribers',
            requestType__c = 'POST');

        Opportunity opp = (Opportunity) opFab.toSObject();    

        oppIds.add(opp.Id);  

  		OpportunitiesSelector mockSelector1 = (OpportunitiesSelector) mocks.mock(OpportunitiesSelector.class);

        mocks.startStubbing();
        mocks.when(mockSelector1.getSObjectType2())
        	.thenReturn(Opportunity.SObjectType);
        mocks.when(mockSelector1.selectByIdWithAccountsContactsAndProducts(oppIds))
        	.thenReturn(new List<Opportunity> { opp });
        mocks.stopStubbing();

        Application.Selector.setMock(mockSelector1);

        OpportunityContactRolesSelector mockSelector2 = (OpportunityContactRolesSelector) mocks.mock(OpportunityContactRolesSelector.class);

        mocks.startStubbing();
        mocks.when(mockSelector2.getSObjectType2())
        	.thenReturn(OpportunityContactRole.SObjectType);
        mocks.when(mockSelector2.selectRoleMapByOpportunityIdWithContact(oppIds))
        	.thenReturn(oppContactR);
        mocks.stopStubbing();

        Application.Selector.setMock(mockSelector2);

		AppAdminAPIClassNew.syncOpportunityAppAdmin(oppIds, false, false, uow);		
	}
	
	
}