src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Last_ROE_Date__c</fullName>
        <label>Last ROE Date</label>
        <type>DateTime</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Apex_Override_Validation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows Apex code to bypass validation rules.  Reset to false by Workflow field update.</description>
        <label>Apex Override Validation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reason_for_closing__c</fullName>
        <label>Reason for closing</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Cancelled</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                </value>
                <value>
                    <fullName>Future Interest</fullName>
                </value>
                <value>
                    <fullName>Existing Customer/Duplicate</fullName>
                </value>
                <value>
                    <fullName>No Integration</fullName>
                </value>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>ROE Expired</fullName>
                </value>
                <value>
                    <fullName>Non-Healthcare</fullName>
                </value>
                <value>
                    <fullName>Foreign Prospect</fullName>
                </value>
                <value>
                    <fullName>Did Not See Value</fullName>
                </value>
                <value>
                    <fullName>Workflow Concerns</fullName>
                </value>
                <value>
                    <fullName>Functionality</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.1/objects/SR_Default_Values__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SR Default Values</label>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

src.2/classes/ClosedLostOpps_Batch.cls
global class ClosedLostOpps_Batch implements Database.Batchable<sObject>, Schedulable 
{
	SR_Default_Values__c defaultROEValue = SR_Default_Values__c.getValues('Opportunity Closed Lost Days');
	SR_Default_Values__c defaultCreatedValue = SR_Default_Values__c.getValues('Opportunity Closed Lost Created Days');
	Integer cutOffDays = Integer.valueOf(defaultROEValue.Value__c);
	Integer createdCutOffDays = Integer.valueOf(defaultCreatedValue.Value__c);

	Date cutOff = Date.today().addDays(-cutOffDays);
	Date createdCutOff = Date.today().addDays(-createdCutOffDays);
	String query = 'SELECT Id, Account.Last_ROE_Date__c, Account.Parent.Last_ROE_Date__c, CreatedDate ' +
	'FROM Opportunity ' +
	'WHERE RecordType.Name = \'New Practice Business\' ' +
	'AND StageName NOT IN (\'Closed Lost\',\'Closed Won\',\'Not Qualified\') ' + 
	'AND Owner.Profile.Name NOT IN (\'Client Engagement Rep\',\'Client Engagement Manager\',\'Support\',\'Support Manager\') ' +
	'AND ((Account.ParentId = null ' +
		'AND ((Account.Last_ROE_Date__c < :cutOff OR Account.Last_ROE_Date__c = null) AND CreatedDate < :createdCutOff)) ' +
	'OR (Account.ParentId != null ' +
		'AND ((Account.Parent.Last_ROE_Date__c < :cutOff OR Account.Parent.Last_ROE_Date__c = null) AND CreatedDate < :createdCutOff))) ' +
	'LIMIT 1000';

	global Database.QueryLocator start(Database.BatchableContext BC) 
	{	
		return Database.getQueryLocator(query);
	}

	global void execute(Database.BatchableContext BC, List<Opportunity> scope) 
	{
		Map<Id, SObject> mapInsertSObject = new Map<Id, SObject>();
      	Map<Id, SObject> mapUpdateSObject = new Map<Id, SObject>();
      	Map<Id, SObject> mapDeleteSObject = new Map<Id, SObject>();

		for(Opportunity o : scope) 
		{
			if(o.Account.ParentId != null && 
				((o.Account.Parent.Last_ROE_Date__c < cutOff || o.Account.Parent.Last_ROE_Date__c == null) && o.CreatedDate < createdCutOff))
			{
				o.StageName = 'Closed Lost';
				o.Reason_For_Closing__c = 'ROE Expired';
				o.Apex_Override_Validation__c = true;
				mapUpdateSObject.put(o.Id, o);
			}
			else if(o.Account.ParentId == null && 
				((o.Account.Last_ROE_Date__c < cutOff || o.Account.Last_ROE_Date__c == null) && o.CreatedDate < createdCutOff))
			{
				o.StageName = 'Closed Lost';
				o.Reason_For_Closing__c = 'ROE Expired';
				o.Apex_Override_Validation__c = true;
				mapUpdateSObject.put(o.Id, o);
			}
		}

		SRUtilities.runDml(mapInsertSObject, mapUpdateSObject, mapDeleteSObject, 'ClosedLostOpps_Batch');
	}
			
	global void finish(Database.BatchableContext BC) 
	{
		Opportunity[] remaining = [SELECT Id, Account.Last_ROE_Date__c, CreatedDate 
			FROM Opportunity 
			WHERE RecordType.Name = 'New Practice Business' 
			AND StageName NOT IN ('Closed Lost','Closed Won','Not Qualified')  
			AND Owner.Profile.Name NOT IN ('Client Engagement Rep','Client Engagement Manager','Support','Support Manager')
			AND ((Account.ParentId = null
				AND ((Account.Last_ROE_Date__c < :cutOff OR Account.Last_ROE_Date__c = null) AND CreatedDate < :createdCutOff))
			OR (Account.ParentId != null
				AND ((Account.Parent.Last_ROE_Date__c < :cutOff OR Account.Parent.Last_ROE_Date__c = null) AND CreatedDate < :createdCutOff)))
			LIMIT 1000];

		if(remaining.size() > 100) 
		{
			ClosedLostOpps_Batch batch = new ClosedLostOpps_Batch();
			Database.executebatch(batch, 50);
		}
	}

	global void execute(SchedulableContext sc) 
	{
		ClosedLostOpps_Batch batch = new ClosedLostOpps_Batch();
		Database.executebatch(batch, 50);
	}
}