src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the related Provider record</description>
        <inlineHelpText>Link to the related Provider record</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Initial_Contract_Term__c</fullName>
        <defaultValue>12</defaultValue>
        <inlineHelpText>Contract duration, in months.</inlineHelpText>
        <label>Contract Term (Months)</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Renewal_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Determines the system behaviour at the time of renewing the subscription.</inlineHelpText>
        <label>Renewal Rule</label>
        <referenceTo>RecurSoft__Renewal_Rule__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>RecurSoft_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Healthgrades</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <description>For selling Healthgrades Premium Profiles</description>
        <label>Healthgrades</label>
    </recordTypes>
</CustomObject>

src.3/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Base_Contract_Term__c</fullName>
        <label>Base Contract Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Co_Terminate__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Determines if the Opportunity Product should be forced to co-terminate with all other Opportunity Products, regardless of free months.</description>
        <inlineHelpText>Determines if the Opportunity Product should be forced to co-terminate with all other Opportunity Products, regardless of free months.</inlineHelpText>
        <label>Co-Terminate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related Provider for the Healthgrades Premium Profile</description>
        <inlineHelpText>The related Provider for the Healthgrades Premium Profile</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Renewal_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Determines the system behaviour at the time of renewing the subscription.</inlineHelpText>
        <label>Renewal Rule</label>
        <referenceTo>RecurSoft__Renewal_Rule__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>RecurSoft_Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.3/objects/Product2.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Default_Contract_Term__c</fullName>
        <description>If Inherit Opportunity Contract Terms is false, the Contract Term will be set on the Opportunity Product to (Default Contract Term + Product Number of Free Months) and reset to this value when an Opportunity contract term change is made. For month-to-month products.</description>
        <inlineHelpText>If Inherit Opportunity Contract Terms is false, the Contract Term will be set on the Opportunity Product to (Default Contract Term + Product Number of Free Months) and reset to this value when an Opportunity contract term change is made.</inlineHelpText>
        <label>Default Contract Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Default_Co_Terminate__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Sets the default for co-termination on the related Opportunity Products.  Can be overridden at the Opportunity Product level.</description>
        <inlineHelpText>Sets the default for co-termination on the related Opportunity Products.  Can be overridden at the Opportunity Product level.</inlineHelpText>
        <label>Default Co-Terminate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Default_Renewal_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Provides the Default Renewal Rule for this Product. Will be set on Opportunity Products.</description>
        <inlineHelpText>Provides the Default Renewal Rule for this Product. Will be set on Opportunity Products.</inlineHelpText>
        <label>Default Renewal Rule</label>
        <referenceTo>RecurSoft__Renewal_Rule__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Provider__c/Provider__c.object-meta.xml
<CustomObject>
    <description>Used to store information about individual Providers within a Practice.  The Provider information is used for Healthgrades Premium members.</description>
    <label>Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OppLineItemUtilities_Test.cls
@isTest
private class OppLineItemUtilities_Test {
	
	@testSetup static void testData1() {

        Account a = TestUtilities.insertBasicAccount(true);
        Opportunity o = TestUtilities.insertBasicOpportunity(a.Id); 
        Opportunity hgOpp = TestUtilities.insertRecordTypeOpportunity(a.Id, 'Healthgrades');
        Contact c = TestUtilities.insertBasicContact(a.Id);
        Provider__c p = TestUtilities.insertProvider(a.Id, c.Id, '1');       
    }

    @testSetup static void testData2() {

        Account a2 = [SELECT Id FROM Account LIMIT 1];
        
    }

    @isTest static void checkDefaults() {

    	Opportunity o = TestUtilities.getOppData([SELECT Id FROM Opportunity WHERE RecordType.Name = 'New Practice Business' LIMIT 1].Id);
    	Integer expectedBaseContractTerm;

    	for(OpportunityLineItem oppLi : o.OpportunityLineItems) {

    		System.debug(oppLi);
    		expectedBaseContractTerm = !OppLi.PricebookEntry.Product2.Default_Co_Terminate__c ? Integer.valueOf(OppLi.PricebookEntry.Product2.Default_Contract_Term__c) :
				o.RecurSoft__Initial_Contract_Term__c == null ? 24 : Integer.valueOf(o.RecurSoft__Initial_Contract_Term__c);

    		System.assertEquals(oppLi.PricebookEntry.Product2.Default_Co_Terminate__c, oppLi.Co_Terminate__c);
    		System.assertEquals(expectedBaseContractTerm, oppLi.Base_Contract_Term__c);
    		//System.assertEquals(oppLi.PricebookEntry.Product2.Default_Renewal_Rule__c, oppLi.RecurSoft__Renewal_Rule__c);

    	}

    }

	/*@isTest static void addHgToExistingProducts() {
		
		Opportunity o = [SELECT Id FROM Opportunity WHERE RecordType.Name != 'Healthgrades' LIMIT 1];
		Provider__c p = [SELECT Id FROM Provider__c LIMIT 1];
		PricebookEntry pbEntry = [SELECT Id, UnitPrice FROM PricebookEntry WHERE Name = 'Healthgrades Premium Profile' AND Pricebook2.Name = '1. SR Premier' LIMIT 1];
		System.debug(o);
		System.debug(TestUtilities.standardPricebookEntries.get('Healthgrades Premium Profile'));
		System.debug(pbEntry);

		Test.startTest();

		try{
			OpportunityLineItem oppLi = TestUtilities.createOpportunityLineItem(o, pbEntry, 1);
			oppLi.Provider__c = p.Id;
			insert oppLi;
			System.assertEquals(null, oppLi.Id);

		} catch(Exception e) {
			Boolean expectedErrorMsg = e.getMessage().contains(Label.Error_Healthgrades_Mix_Products);
			System.assert(expectedErrorMsg);
		}

		Test.stopTest();
	}

	@isTest static void addProductsToHGProducts() {
		
		Id pbookId = Test.getStandardPricebookId();
		Opportunity o = [SELECT Id FROM Opportunity WHERE RecordType.Name = 'Healthgrades' LIMIT 1];
		Provider__c p = [SELECT Id FROM Provider__c LIMIT 1];
		PricebookEntry pbEntry = [SELECT Id, UnitPrice FROM PricebookEntry WHERE Name = 'Healthgrades Premium Profile' AND Pricebook2Id = :pbookId LIMIT 1];
		PricebookEntry pbEntry2 = [SELECT Id, UnitPrice FROM PricebookEntry WHERE Name = 'SR Premier' AND Pricebook2Id = :pbookId LIMIT 1];
		System.debug([SELECT Name, Pricebook2.Name FROM PricebookEntry]);

		OpportunityLineItem oppLi = TestUtilities.createOpportunityLineItem(o, pbEntry, 1);
		oppLi.Provider__c = p.Id;

		insert oppLi;

		Test.startTest();
		
		try{
			OpportunityLineItem oppLi2 = TestUtilities.createOpportunityLineItem(o, pbEntry2, 1);
			insert oppLi2;
			System.assertEquals(null, oppLi.Id);
		
		} catch(Exception e) {
			
			Boolean expectedErrorMsg = e.getMessage().contains(Label.Error_Healthgrades_Mix_Products2);
			System.assert(expectedErrorMsg);
		}
		
		Test.stopTest();
	}*/
}