src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Office_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Office Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Practice_Management_Software__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is the practice management software the customer is using.</description>
        <inlineHelpText>This is the practice management software the customer is using.</inlineHelpText>
        <label>Practice Management Software</label>
        <referenceTo>Management_System__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Default Bill to Contact for usage billing.</inlineHelpText>
        <label>Bill to Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>$Source.RecurSoft__Bill_to_Account__c</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.RecurSoft__Bill_to_Account__c</field>
                <operation>equals</operation>
                <value/>
            </filterItems>
            <infoMessage>Contact should have current account.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>RecurSoft_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Bill_to_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Default Bill to Account for usage billing.</inlineHelpText>
        <label>Bill to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Bill to Account)</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Channel__c</fullName>
        <description>This field is mapped to the Class dimension in Intacct.</description>
        <inlineHelpText>Maps to the class dimension ID within Intacct.</inlineHelpText>
        <label>Class</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>100</fullName>
                    <default>true</default>
                    <label>100</label>
                </value>
                <value>
                    <fullName>200</fullName>
                </value>
                <value>
                    <fullName>300</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RecurSoft__Intacct_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Determines whether customer records are created at the root or entity level in Intacct.</inlineHelpText>
        <label>Intacct Entity</label>
        <referenceTo>RecurSoft__Intacct_Entity__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>RecurSoft_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Engineer_Call_Completed__c</fullName>
        <label>Sales Engineer Call Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Engineer_Call_Needed__c</fullName>
        <formula>Practice_Management_Software__r.Sales_Engineer_Call_Needed__c</formula>
        <label>Sales Engineer Call Needed</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.1/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Practice_Management_Software__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Set via Parent/Child Mapping in Apex</description>
        <label>Practice Management Software</label>
        <referenceTo>Management_System__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.3/objects/Management_System__c.object
<CustomObject>
    <label>Management System</label>
    <nameField>
        <label>Management System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Management Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Sales_Engineer_Call_Needed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sales Engineer Call Needed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SYNC_Availability__c</fullName>
        <inlineHelpText>Being Built= an integration engineer is currently building this SYNC
Discovery= research is being done if we can integrate 
Cannot Integrate= DO NOT SELL
Business Negotiation= we are looking into making a business agreement
SYNC Complete= Sail Away</inlineHelpText>
        <label>SYNC Availability</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Discovery</fullName>
                </value>
                <value>
                    <fullName>In Development</fullName>
                    <label>Sales Engineer List</label>
                </value>
                <value>
                    <fullName>SYNC Complete</fullName>
                </value>
                <value>
                    <fullName>Blacklist - DO NOT SELL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Approval_Level_Required__c</fullName>
        <label>Approval Level Required</label>
        <summarizedField>OpportunityLineItem.Approval_Level_Required__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Contract_Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill to Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.RecurSoft__Bill_to_Account__c</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>RecurSoft_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Bill_to_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Bill to Account)</relationshipLabel>
        <relationshipName>RecurSoft_OpportunitiesAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Expected_Contract_Start_Date__c</fullName>
        <description>[CV] Please do not edit this field. It shows up on the layout for testing purposes only.</description>
        <label>Deprecated -Expected Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Initial_Contract_Term__c</fullName>
        <defaultValue>12</defaultValue>
        <inlineHelpText>Contract duration, in months.</inlineHelpText>
        <label>Contract Term (Months)</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Intacct_Entity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Intacct Entity</label>
        <referenceTo>RecurSoft__Intacct_Entity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>RecurSoft_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Number_of_Free_Months__c</fullName>
        <inlineHelpText>Free months that can extend the contract or be included in the contract.</inlineHelpText>
        <label>Number of Free Months</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <default>true</default>
                    <label>0</label>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RecurSoft__Trial__c</fullName>
        <description>Trial Period in Days.</description>
        <inlineHelpText>Period during which contracts can be cancelled without penalties.</inlineHelpText>
        <label>Trial Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0 - Waived</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                    <default>true</default>
                    <label>60</label>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Engineer_Call_Completed__c</fullName>
        <label>Sales Engineer Call Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sync_Availability__c</fullName>
        <formula>Account.Practice_Management_SYNC_Availability_T__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sync Availability</label>
        <type>Text</type>
    </fields>
</CustomObject>

src.1/classes/ValidateOppData.cls
/**
 * File:        ValidateOppData.cls
 * Project:     Solutionreach 
 * Date:        Mar 26, 2014
 * Created By:  Sid Maganti
 * *************************************************************************
 * Description: Apex class to Validate opportunity data before you send the contract. This 
 *              apex class will be revoked from java script.(Send Contract:Button on Opportunity)
 * *************************************************************************
 * History:
 * Date:                Modified By:            Description: 
 * 02/19/2015           Randy Barton		    Added validation for free month approval.
 */

global class ValidateOppData {
    //Webservice method returns string (error message or clear keyword)
    /*Validate
    *@ returns String
    *@ input String OppID
    */
    webService static String Validate(String OppID) {
        //return string value
        string output=null;
        string Error= null;
        //checking the OppID is null or empty
        if(OppID!= null && OppID!='')
        {
            Opportunity Opp = new Opportunity();
            //retriving the Opportunity data
            Opp=[select id,Name,CloseDate,Sync_Availability__c,RecurSoft__Bill_to_Account__r.Office_Contact__c,StageName,RecurSoft__Expected_Contract_Start_Date__c,Account.RecurSoft__Channel__c,Account.Industry,RecurSoft__Bill_to_Account__r.Industry,
            RecurSoft__Bill_to_Account__r.RecurSoft__Channel__c,RecurSoft__Bill_to_Account__c,RecurSoft__Billing_Contact__c,RecurSoft__Trial__c,RecurSoft__Initial_Contract_Term__c, RecurSoft__Bill_to_Account__r.Sales_Engineer_Call_Completed__c,
            Contract_Signed__c, RecurSoft__Bill_to_Account__r.Practice_Management_Software__c, RecurSoft__Bill_to_Account__r.Practice_Management_Software__r.Sales_Engineer_Call_Needed__c,Approval_Level_Required__c,
          RecurSoft__Intacct_Entity__c, RecordType.Name, RecurSoft__Number_Of_Free_Months__c,owner.profile.Name from Opportunity where id =: OppID];
            
            //checking if Opp is null
            if(Opp!=null)
            {
                if(Opp.RecurSoft__Bill_to_Account__c==null || System.Test.isRunningTest())
                { 
                    Error= 'Please specify the Biling Account';
                }
                if(Opp.RecurSoft__Bill_to_Account__r.Office_Contact__c==null || System.Test.isRunningTest())
                { 
                    Error= 'Please specify the Office Contact on Biling Account';
                }
                if(Opp.RecurSoft__Billing_Contact__c==null || System.Test.isRunningTest() )
                {
                    Error= 'Please specify the Biling Contact';
                }
                if(Opp.RecurSoft__Trial__c==null || Opp.RecurSoft__Trial__c=='' || System.Test.isRunningTest())
                {
                    Error= 'Please specify the Trial Period';
                }
                if(Opp.RecurSoft__Initial_Contract_Term__c==null || Opp.RecurSoft__Initial_Contract_Term__c==0 || System.Test.isRunningTest())
                {
                    Error= 'Please specify the Initial Contract Term (months)';
                }
                if(Opp.Contract_Signed__c== true || System.Test.isRunningTest())
                {
                    Error= 'Contract is already signed';
                }
                if(Opp.RecurSoft__Bill_to_Account__r.Practice_Management_Software__c== null || System.Test.isRunningTest())
                {
                    Error= 'Please specify Management System on Biling Account';
                }
                if( Date.today()>Opp.CloseDate || System.Test.isRunningTest())
                {
                    Error= 'Closed date is passed';
                }
                /*
                if(Opp.RecurSoft__Expected_Contract_Start_Date__c == null || System.Test.isRunningTest())
                {
                    Error= 'Please specify Expected Contract Start Date';
                }
                */
                if( Opp.Account.Industry == null || System.Test.isRunningTest())
                {
                    Error= 'Please specify Channel and Industry on Account';
                }
                if(Opp.RecurSoft__Bill_to_Account__r.Industry == null || System.Test.isRunningTest())
                {
                    Error= 'Please specify Channel and Industry on Bill to Account';
                }
                if(Opp.RecurSoft__Intacct_Entity__c == null || System.Test.isRunningTest())
                {
                    Error= 'Please specify Intacct Entity';
                }
                
                // Check to make sure we have no outstanding approvals
                if(Opp.Approval_Level_Required__c != null && Opp.Approval_Level_Required__c > 0) {
                    Error = 'This Opportunity has pricing or free months that require approval prior to sending the contract';
                }

                if((opp.RecurSoft__Bill_to_Account__r.Sales_Engineer_Call_Completed__c == null || opp.RecurSoft__Bill_to_Account__r.Sales_Engineer_Call_Completed__c < Date.today().addDays(-30)) && 
                    opp.RecurSoft__Bill_to_Account__r.Practice_Management_Software__r.Sales_Engineer_Call_Needed__c &&
                    opp.RecordType.Name == 'New Practice Business' &&
                    opp.Owner.Profile.Name != 'Support' &&
                    opp.Owner.Profile.Name != 'Support Team Leads' &&
                    opp.Owner.Profile.Name != 'Support Manager')
                {
                    Error = 'This Management System requires a Sales Engineer call to be completed within the last 30 days before sending the contract.';
                }
                
                if (Opp.Sync_Availability__c == 'Blacklist - DO NOT SELL') {
                    Error = 'This account is using a Management System on the Blacklist. DO NOT SELL!';
                }
                system.debug('Opp.RecurSoft__Bill_to_Account__r.RecurSoft__Channel__c'+Opp.RecurSoft__Bill_to_Account__r.RecurSoft__Channel__c);
            }
        }
        //populate the output string
        output=(Error==null)?'clear':Error;
        //system debug output 
        system.debug('output: '+output);
        //return the output
        return output;
    }
}