src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Practice_Management_Software__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is the practice management software the customer is using.</description>
        <inlineHelpText>This is the practice management software the customer is using.</inlineHelpText>
        <label>Practice Management Software</label>
        <referenceTo>Management_System__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Bill_to_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Default Bill to Account for usage billing.</inlineHelpText>
        <label>Bill to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Bill to Account)</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Intacct_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Determines whether customer records are created at the root or entity level in Intacct.</inlineHelpText>
        <label>Intacct Entity</label>
        <referenceTo>RecurSoft__Intacct_Entity__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>RecurSoft_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <label>PM/EHR Partner</label>
    </recordTypes>
</CustomObject>

src.1/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Practice_Management_Software__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Set via Parent/Child Mapping in Apex</description>
        <label>Practice Management Software</label>
        <referenceTo>Management_System__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.3/objects/Management_System__c.object
<CustomObject>
    <label>Management System</label>
    <nameField>
        <label>Management System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Management Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Management_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Management System</label>
        <referenceTo>Management_System__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Bill_to_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Bill to Account)</relationshipLabel>
        <relationshipName>RecurSoft_OpportunitiesAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Signed_Date__c</fullName>
        <label>Contract Signed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Initial_Contract_Term__c</fullName>
        <defaultValue>12</defaultValue>
        <inlineHelpText>Contract duration, in months.</inlineHelpText>
        <label>Contract Term (Months)</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Intacct_Entity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Intacct Entity</label>
        <referenceTo>RecurSoft__Intacct_Entity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>RecurSoft_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Trial__c</fullName>
        <description>Trial Period in Days.</description>
        <inlineHelpText>Period during which contracts can be cancelled without penalties.</inlineHelpText>
        <label>Trial Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0 - Waived</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                    <default>true</default>
                    <label>60</label>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.1/classes/PartenerNewSaleApxc.cls
public class PartenerNewSaleApxc {

    public class PicklistOptions
    {
        @AuraEnabled
        String label {get; set;}
        @AuraEnabled
        String value {get; set;}
    }
    @AuraEnabled
    public static void createPartnerRecordApxc(Account acct, Contact con, Opportunity opp){
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        System.debug('Account: ' + acct);
        System.debug('I am here');
        System.debug('Contact: ' + con);
        System.debug('Opp: ' + opp);
        acct.industry = acct.industry == null ? 'Dental' : acct.industry;
        acct.ParentId = acct.Practice_Management_Software__c == 'a00i000000Mq9mL' ? '0010Z00001wOggb' : '0010Z00001wOggv';
        uow.registerNew(acct);
        uow.registerNew(con, Contact.AccountId, acct);
            opp.Name = acct.Name;
            opp.StageName = 'Qualified';
//          opp.Pricebook2Id = pBook[0].Id;
            opp.RecordTypeId = SRUtilities.getRecordTypeMap('Opportunity').get('New Practice Business').getRecordTypeId();
            opp.RecurSoft__Trial__c = 'None';
            opp.CloseDate = Date.today();
            opp.RecurSoft__Initial_Contract_Term__c = 24;
//          opp.RecurSoft__Intacct_Entity__c = intacctEntity;
            opp.RecurSoft__Contract_Signed_Date__c = Date.today();
            opp.RecurSoft__Bill_to_Account__c = acct.ParentId;
        uow.registerNew(opp, Opportunity.AccountId, acct);
        uow.commitWork();
        ConnectApi.FeedItemInput feedItemInput = new ConnectApi.FeedItemInput();
        ConnectApi.MentionSegmentInput mentionSegmentInput = new ConnectApi.MentionSegmentInput();
        ConnectApi.MentionSegmentInput mentionSegmentInput2 = new ConnectApi.MentionSegmentInput();
        ConnectApi.MessageBodyInput messageBodyInput = new ConnectApi.MessageBodyInput();
        ConnectApi.TextSegmentInput textSegmentInput = new ConnectApi.TextSegmentInput();

        messageBodyInput.messageSegments = new List<ConnectApi.MessageSegmentInput>();

        mentionSegmentInput.id = '005i0000002gnC6';
        messageBodyInput.messageSegments.add(mentionSegmentInput);

        mentionSegmentInput2.id = '005i0000002gn9T';
        messageBodyInput.messageSegments.add(mentionSegmentInput2);

        textSegmentInput.text = ' New SR Partner sale ';
        messageBodyInput.messageSegments.add(textSegmentInput);

        feedItemInput.body = messageBodyInput;
        feedItemInput.feedElementType = ConnectApi.FeedElementType.FeedItem;
        feedItemInput.subjectId = acct.Id;

        ConnectApi.FeedElement feedElement = ConnectApi.ChatterFeeds.postFeedElement(Network.getNetworkId(), feedItemInput);
    }
    @AuraEnabled
    public static List<String> getPickListValuesIntoList(String objectType, String selectedField){
        List<String> pickListValuesList = new List<String>();
        Schema.SObjectType convertToObj = Schema.getGlobalDescribe().get(objectType);
        Schema.DescribeSObjectResult res = convertToObj.getDescribe();
        Schema.DescribeFieldResult fieldResult = res.fields.getMap().get(selectedField).getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            pickListValuesList.add(pickListVal.getLabel());
        }
        return pickListValuesList;
    }
    @AuraEnabled
    public static List<PicklistOptions> getNonBlacklistedPms()
    {
        Management_System__c[] options = ManagementSystemsSelector.newInstance().selectNonBlacklistedManagementSystems();
        List<PicklistOptions> newList = new List<PicklistOptions>();
        for(Management_System__c pms : options)
        {
            PicklistOptions plo = new PicklistOptions();
            plo.label = pms.Name;
            plo.value = pms.Id;
            newList.add(plo);
        }
        return newList;
    }
}