src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Subscriber_ID__c</fullName>
        <description>The subscriber ID from App Admin</description>
        <label>Subscriber ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.1/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Contact_Role_Multi__c</fullName>
        <description>Used for when a contract is signed to assign roles from the contract</description>
        <label>Contact Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Doctor/Owner</fullName>
                </value>
                <value>
                    <fullName>Business Contact</fullName>
                </value>
                <value>
                    <fullName>Billing Contact</fullName>
                </value>
                <value>
                    <fullName>Contract Signer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Purchase_Involvement__c</fullName>
        <label>Purchase Involvement</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Uninvolved</fullName>
                </value>
                <value>
                    <fullName>Involved</fullName>
                </value>
                <value>
                    <fullName>Decision Maker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Competitor__c</fullName>
        <label>Competitor</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>4 Patient Care</fullName>
                </value>
                <value>
                    <fullName>DemandForce</fullName>
                </value>
                <value>
                    <fullName>eCentral</fullName>
                </value>
                <value>
                    <fullName>eReminders</fullName>
                </value>
                <value>
                    <fullName>Lighthouse</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Other(Note name in Other Competitor)</fullName>
                </value>
                <value>
                    <fullName>Patient Activator</fullName>
                </value>
                <value>
                    <fullName>Phone Tree</fullName>
                </value>
                <value>
                    <fullName>PM/EMR</fullName>
                </value>
                <value>
                    <fullName>Practice Mojo</fullName>
                </value>
                <value>
                    <fullName>RevenueWell</fullName>
                </value>
                <value>
                    <fullName>Sesame</fullName>
                </value>
                <value>
                    <fullName>Teledental</fullName>
                </value>
                <value>
                    <fullName>Televox</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>Weave</fullName>
                </value>
                <value>
                    <fullName>Websystem3</fullName>
                </value>
                <value>
                    <fullName>Yapi</fullName>
                </value>
                <value>
                    <fullName>ZocDoc</fullName>
                </value>
                <value>
                    <fullName>Phresia (Tablet)</fullName>
                </value>
                <value>
                    <fullName>Patient Pop</fullName>
                </value>
                <value>
                    <fullName>Doctable</fullName>
                </value>
                <value>
                    <fullName>Call Point</fullName>
                </value>
                <value>
                    <fullName>Relatient</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Date_Time__c</fullName>
        <description>Contract signed date</description>
        <inlineHelpText>Contract signed date</inlineHelpText>
        <label>Contract Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Other_Competitor__c</fullName>
        <description>Text field for Other Competitor names.</description>
        <label>Other Competitor</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriber_ID__c</fullName>
        <formula>Case(Account.Subscriber_ID__c,&quot;&quot;,&quot;&quot;,Account.Subscriber_ID__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subscriber ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Win_Report_Completed_Date__c</fullName>
        <label>Win Report Completed Date</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

src.3/classes/SRInvocable_ProcessWinReport.cls
public with sharing class SRInvocable_ProcessWinReport 
{
	@InvocableMethod(label='processWinReport' description='Process Win Report Data')
	public static void processWinReport(InputData[] input)
	{
		fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
		Map<Id, String> contactIdToInvolvementMap = new Map<Id, String>();
		Map<Id, String> contactIdToRoleMap = new Map<Id, String>();
		for(String s : input[0].involvement)
		{
			String[] split = s.split(':');
			contactIdToInvolvementMap.put(split[0], split[1]);
		}

		for(Id s1 : contactIdToInvolvementMap.keySet())
		{
			Contact c = new Contact(Id = s1, Purchase_Involvement__c = contactIdToInvolvementMap.get(s1));
			if(contactIdToRoleMap.containsKey(s1)) c.Contact_Role_Multi__c = contactIdToRoleMap.get(s1);
			uow.registerDirty(c);
		}

		Opportunity o = new Opportunity(Id = input[0].opportunityId, 
			Competitor__c = input[0].competitors,
			Other_Competitor__c = input[0].competitorOther,
			Win_Report_Completed_Date__c = Datetime.now());
		uow.registerDirty(o);
		
		uow.commitWork();

		generatePDF(input[0], contactIdToInvolvementMap.keySet());
	}

	public class InputData
	{
		@InvocableVariable(required=false)
		public String opportunityId;

		@InvocableVariable(required=false)
		public String competitors;

		@InvocableVariable(required=false)
		public String competitorOther;

		@InvocableVariable(required=false)
		public String primaryBenefit;

		@InvocableVariable(required=false)
		public String goalsDefined;

		@InvocableVariable(required=false)
		public String otherInformation;

		@InvocableVariable(required=false)
		public String[] involvement;
	}

	public static void generatePDF(InputData input, Set<Id> ids)
	{
		Contact[] contacts = ContactsSelector.newInstance().selectByIdWithAccount(ids);
		Opportunity o = [SELECT Id, Account.Name, Account.Subscriber_Id__c, Contract_Date_Time__c 
			FROM Opportunity WHERE Id = :input.opportunityId];

		String fileName = o.Account.Name.replaceAll(' ', '_').replaceAll(',', '_').replaceAll('//', '_').replaceAll('/', '_') + 
            + '_Win_Report.pdf';

        String contractDate = o.Contract_Date_Time__c != null ? o.Contract_Date_Time__c.format('MM/dd/yyyy HH:mm:ss','America/Denver') : 'Unknown';

		String competitorsCombined = input.competitorOther == null ?
			input.competitors : input.competitors + '; ' + input.competitorOther;

		String pdfString = '<p style="text-align: center;"><strong>Win Report</strong></p>' +
			+ '<p><strong>Subscriber ID: </strong>' + o.Account.Subscriber_Id__c +
			+ '<br /><strong>Account Name: </strong>' + o.Account.Name +
			+ '<br /><strong>Contract Signed Date:</strong>' + contractDate +
			+ '<p>&nbsp;</p>' +
			+ '</p><p style="text-align: center;"><strong>Contact Information</strong></p>' +
			+ '<p>&nbsp;</p>';

		for(Contact c : contacts)
		{
			pdfString += '<p><strong>Role(s): ' + c.Contact_Role_Multi__c + '</strong>' +
				+ '<br />Title: ' + c.Title +
				+ '<br />First Name: ' + c.FirstName +
				+ '<br />Last Name: ' + c.LastName +
				+ '<br />Phone: ' + c.Phone +
				+ '<br />Email: ' + c.Email +
				+ '<br />Involvement in Purchase Decision: ' + c.Purchase_Involvement__c +
				+ '<p>&nbsp;</p>';
		}
			
		pdfString += '</p><p><strong>What competitor(s) was the customer using or evaluating?: ' +
			+ '<br /></strong>' + competitorsCombined +
			+ '</p><p><strong>What is the primary benefit the customer is purchasing Solutionreach for?: ' +
			+ '<br /></strong>' + input.primaryBenefit +
			+ '</p><p><strong>What goals were defined with the customer?: ' +
			+ '<br /></strong>' + input.goalsDefined +
			+ '</p><p><strong>Is there anything else we should know about the customer?: ' +
			+ '<br /></strong>' + input.otherInformation + '</p>';
		
		Blob b = Blob.toPdf(pdfString);

		Attachment opportunityAttachment = new Attachment();
            opportunityAttachment.ParentId = o.Id;
            opportunityAttachment.Name = fileName;
            opportunityAttachment.Body = b;

        insert opportunityAttachment;
	}
}