src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account Lookup</description>
        <inlineHelpText>Choose the Account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_ROE_Date__c</fullName>
        <label>Last ROE Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Last_ROE_Task_Date__c</fullName>
        <label>Last ROE Task Date</label>
        <summarizedField>Opportunity.Last_ROE_Task_Date__c</summarizedField>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Number_of_Active_CI__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Active CI</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Status__c</fullName>
        <description>Picklist used to determine if an account is an active customer.</description>
        <inlineHelpText>Determined by the status of subscriptions (not created, created, not activated, or cancelled)</inlineHelpText>
        <label>ISB Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.4/objects/Campaign_Influence__c.object
<CustomObject>
    <label>Campaign Influence</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Influence</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Campaign Influence</relationshipLabel>
        <relationshipName>Campaign_Influence</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_ROE_Date__c</fullName>
        <formula>if(  Lead__c != null , Lead__r.Last_ROE_Task_Date__c ,  Opportunity__r.Last_ROE_Task_Date__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last ROE Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Last_ROE_Task_Date__c</fullName>
        <formula>if( not(isblank(Opportunity__r.Last_ROE_Task_Date__c)), 
  Opportunity__r.Last_ROE_Task_Date__c, 
 if( not(isblank(Lead__r.Last_ROE_Task_Date__c)), 
  Lead__r.Last_ROE_Task_Date__c,
  Lead__r.SR_Date_Created__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last ROE Task Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Campaign Influence</relationshipLabel>
        <relationshipName>Campaign_Influence</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Orphaned_Date__c</fullName>
        <label>Orphaned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Orphaned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Orphaned</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src.1/objects/Lead.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>Last_ROE_Task_Date__c</fullName>
        <label>Last ROE Task Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Number_of_Active_CI__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Active CI</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src.1/objects/SR_Default_Values__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SR Default Values</label>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/OrphanCI_Batch.cls
global class OrphanCI_Batch implements Database.Batchable<sObject>, Schedulable 
{	
	SR_Default_Values__c defaultValues = SR_Default_Values__c.getValues('Campaign Influence Orphan Days');
	Integer cutOffDays = Integer.valueOf(defaultValues.Value__c);
	Datetime cutOff = Datetime.now().addDays(-cutOffDays);

	String query = 'SELECT Id, Orphaned__c, CreatedDate, Orphaned_Date__c, ' +
		'Lead__c, Lead__r.Number_of_Active_CI__c, Lead__r.Last_ROE_Task_Date__c, ' +
		'Account__c, Account__r.Number_of_Active_CI__c, Account__r.Last_ROE_Date__c ' +
		'FROM Campaign_Influence__c ' +
		'WHERE (Account__r.Last_ROE_Date__c != LAST_N_DAYS:' + cutOffDays + ' OR Account__r.Last_ROE_Date__c = null) ' +
		'AND CreatedDate != LAST_N_DAYS:' + cutOffDays +
		'AND (Orphaned__c = false OR Orphaned_Date__c = null) ' +
		'AND Account__r.RecurSoft__Status__c != \'Active\' ';
		
	global Database.QueryLocator start(Database.BatchableContext BC) 
	{	
		return Database.getQueryLocator(query);
	}

	global void execute(Database.BatchableContext BC, List<Campaign_Influence__c> scope) 
	{
      	fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

		for(Campaign_Influence__c ci : scope) 
		{
			Boolean isOrphan = false;
			Datetime orphanDate;

			if((ci.Orphaned__c && ci.Orphaned_Date__c != null) || (ci.Account__c == null)) continue;

			if(ci.Account__c != null) 
			{
				if(ci.Account__r.Last_Roe_Date__c != null && ci.CreatedDate < ci.Account__r.Last_Roe_Date__c) 
				{
					isOrphan = true;
					orphanDate = ci.Account__r.Last_Roe_Date__c.addDays(cutOffDays);
					ci.Orphaned__c = true;
					ci.Orphaned_Date__c = orphanDate.date();
					uow.registerDirty(ci);
				} 
				else if(ci.CreatedDate < cutOff) 
				{
					isOrphan = true;
					orphanDate = ci.CreatedDate.addDays(cutOffDays);
					ci.Orphaned__c = true;
					ci.Orphaned_Date__c = orphanDate.date();
					uow.registerDirty(ci);
				}
				if(ci.Account__r.Number_of_Active_CI__c != 0 && isOrphan) 
				{
					Account a = new Account(Id = ci.Account__c);
					a.Number_of_Active_CI__c = 0;
					uow.registerDirty(a);	
				}
			} 
		}

		uow.commitWork();
	}
			
	global void finish(Database.BatchableContext BC) 
	{	
		CIRecalculateLead_Batch batch = new CIRecalculateLead_Batch();
		Database.executebatch(batch);
	}

	global void execute(SchedulableContext sc) 
	{	
		OrphanCI_Batch batch = new OrphanCI_Batch();
		Database.executebatch(batch);
	}
}