src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Do_Not_Support_Reason__c</fullName>
        <label>Do Not Support Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billing Concern</fullName>
                </value>
                <value>
                    <fullName>Legal Action</fullName>
                </value>
                <value>
                    <fullName>Client Dispute</fullName>
                </value>
                <value>
                    <fullName>Client Pending Cancel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Do_Not_Support_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if we do not need to auto create sync down cases for this account</inlineHelpText>
        <label>Do Not Support Sync</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.4/objects/Case.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>Resolution__c</fullName>
        <label>Resolution</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>Wont Fix</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Cannot Reproduce</fullName>
                </value>
                <value>
                    <fullName>Resumed</fullName>
                </value>
                <value>
                    <fullName>Max Attempts Reached</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Accounting</fullName>
        <active>true</active>
        <businessProcess>Accounting</businessProcess>
        <description>Used to alert Accounting of changes to customers billing</description>
        <label>Accounting</label>
    </recordTypes>
    <recordTypes>
        <fullName>Support</fullName>
        <active>true</active>
        <businessProcess>Support</businessProcess>
        <description>The main case type for Support</description>
        <label>Support</label>
    </recordTypes>
</CustomObject>

src.3/objects/Parent_Child_Mapping__c.object
<CustomObject>
    <label>Parent Child Mapping</label>
    <nameField>
        <displayFormat>PCM-{0000}</displayFormat>
        <label>Parent Child Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parent Child Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Field_Name__c</fullName>
        <label>Parent Field Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Object__c</fullName>
        <label>Parent Object</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Object_Names</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

src.1/objects/SR_Default_Values__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SR Default Values</label>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

src.3/objects/Stamp_Field_Mapping__c.object
<CustomObject>
    <label>Stamp Field Mapping</label>
    <nameField>
        <displayFormat>SFM-{0000}</displayFormat>
        <label>Stamp Field Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stamp Field Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Field_Changed_Value__c</fullName>
        <label>Field Changed Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Changed__c</fullName>
        <label>Field Changed</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stamp_To_Object__c</fullName>
        <label>Stamp To Object</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Object_Names</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

src.2/classes/Accounts_Test.cls
@isTest
private class Accounts_Test {

    @isTest static void test_onApplyDefaults()
    {
        sfab_FabricatedSObject aFab = TestUtilities2.newAccount();

        Account ac = (Account) aFab.toSObject();

        Account existingAc = (Account) testUtilities2.existingAccount(aFab).toSObject();

        Accounts accounts = new Accounts(new List<Account>{ ac });
        accounts.onApplyDefaults();
    }

    @isTest static void test_onBeforeUpdate()
    {
        sfab_FabricatedSObject aFab = TestUtilities2.newAccount();

        Account ac = (Account) aFab.toSObject();

        Account existingAc = (Account) TestUtilities2.existingAccount(aFab).toSObject();

        Accounts accounts = new Accounts(new List<Account>{ ac });
        accounts.onBeforeUpdate(new Map<Id, SObject>{ac.Id =>  aFab.toSObject()});
    }

    @isTest static void test_checkForSyncOwners()
    {
        User user = (User) TestUtilities2.newUser().toSObject();

        User user2 = (User) TestUtilities2.newUser().toSObject();

        sfab_FabricatedSObject aFab = TestUtilities2.newAccount()
                .setField(Account.OwnerId, user.Id);

        Account ac = (Account) aFab.toSObject();

        Account existingAc = (Account) TestUtilities2.existingAccount(aFab)
                .setField(Account.OwnerId, user2.Id)
                .toSObject();

        Accounts accounts = new Accounts(new List<Account>{ ac });
        accounts.checkForSyncOwners(ac, existingAc);

        System.assertEquals(1, Accounts.syncOwners.size());
        System.assert(Accounts.syncOwners.contains(ac.Id + ':' + ac.OwnerId));
    }

    @isTest static void test_processParentChildUpdates()
    {
        Parent_Child_Mapping__c parent = (Parent_Child_Mapping__c) testUtilities2.newParentChildMapping()
                .setField(Parent_Child_Mapping__c.Parent_Object__c, 'Account')
                .setField(Parent_Child_Mapping__c.Parent_Field_Name__c, 'OwnerId')
                .setField(Parent_Child_Mapping__c.Active__c, true)
                .toSObject();

        User user = (User) TestUtilities2.newUser().toSObject();

        User user2 = (User) TestUtilities2.newUser().toSObject();

        sfab_FabricatedSObject aFab = TestUtilities2.newAccount()
                .setField(Account.OwnerId, user.Id);

        Account ac = (Account) aFab.toSObject();

        Account existingAc = (Account) TestUtilities2.existingAccount(aFab)
                .setField(Account.OwnerId, user2.Id)
                .toSObject();

        Accounts accounts = new Accounts(new List<Account>{ ac });
        accounts.mappings = new List<Parent_Child_Mapping__c>{ parent };
        accounts.processParentChildUpdates(ac, existingAc);

        System.assertEquals(1, Accounts.parentChildUpdates.size());
        System.assert(accounts.parentChildUpdates.keySet().contains(ac.Id));
    }

    @isTest static void test_processStampUpdates()
    {
        User user = (User) TestUtilities2.newUser().toSObject();

        User user2 = (User) TestUtilities2.newUser().toSObject();

        Stamp_Field_Mapping__c stamp1 = (Stamp_Field_Mapping__c) testUtilities2.newStampFieldMapping()
                .setField(Stamp_Field_Mapping__c.Stamp_To_Object__c, 'Account')
                .setField(Stamp_Field_Mapping__c.Active__c, true)
                .setField(Stamp_Field_Mapping__c.Field_Changed__c, 'OwnerId')
                .setField(Stamp_Field_Mapping__c.Field_Changed_Value__c, String.valueOf(user.Id))
                .toSObject();

        sfab_FabricatedSObject aFab = TestUtilities2.newAccount()
                .setField(Account.OwnerId, user.Id);

        Account ac = (Account) aFab.toSObject();

        Account existingAc = (Account) TestUtilities2.existingAccount(aFab)
                .setField(Account.OwnerId, user2.Id)
                .toSObject();

        Accounts accounts = new Accounts(new List<Account>{ ac });
        accounts.stampMappings = new List<Stamp_Field_Mapping__c>{ stamp1 };
        accounts.processStampUpdates(ac, existingAc);

        System.assertEquals(1, accounts.stampUpdates.size());
        System.assert(accounts.stampUpdates.contains(ac.Id + '::' + stamp1.Id));
    }

    @isTest static void test_validateAccountOwnerChange()
    {
        User user = (User) TestUtilities2.newUser().toSObject();

        User user2 = (User) TestUtilities2.newUser().toSObject();

        Stamp_Field_Mapping__c stamp1 = (Stamp_Field_Mapping__c) testUtilities2.newStampFieldMapping()
                .setField(Stamp_Field_Mapping__c.Stamp_To_Object__c, 'Account')
                .setField(Stamp_Field_Mapping__c.Active__c, true)
                .setField(Stamp_Field_Mapping__c.Field_Changed__c, 'OwnerId')
                .setField(Stamp_Field_Mapping__c.Field_Changed_Value__c, String.valueOf(user.Id))
                .toSObject();

        sfab_FabricatedSObject aFab = TestUtilities2.newAccount()
                .setField(Account.OwnerId, user.Id);

        Account ac = (Account) aFab.toSObject();

        Account existingAc = (Account) TestUtilities2.existingAccount(aFab)
                .setField(Account.OwnerId, user2.Id)
                .toSObject();

        insert new SR_Default_Values__c(Name = 'jennyPoolUserId',
                Description__c = 'jennyPoolUserId',
                Value__c = ac.OwnerId);

        insert new SR_Default_Values__c(Name = 'noStealingProfiles',
                Description__c = 'noStealingProfiles',
                Value__c = '00ei0000001247zAAA');

        insert new SR_Default_Values__c(Name = 'acctChangeOwnerErrorMessage',
                Description__c = 'acctChangeOwnerErrorMessage',
                Value__c = 'Adderror Message');

        Accounts accounts = new Accounts(new List<Account>{ ac });
        accounts.validateAccountOwnerChange(ac, existingAc);
    }

    @IsTest static void test_CloseOpenSupportAndSyncCases()
    {
        Account a = TestUtilities.insertBasicAccount(true);
        a.Do_Not_Support_Sync__c  = true;
        a.Do_Not_Support_Reason__c = 'Cancelled';


        Id syncCaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Sync List Case').getRecordTypeId();
        Id supportCaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Support').getRecordTypeId();
        Id accountingCaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Accounting').getRecordTypeId();

        List<Case> caseList = new List<Case>();
        Case syncCase = new Case(AccountId = a.Id,
                RecordTypeId = syncCaseRecordTypeId,
                Subject = 'Sync Down',
                Status = 'New',
                Resolution__c = null);
        caseList.add(syncCase);

        Case supportCase = new Case(AccountId = a.Id,
                RecordTypeId = supportCaseRecordTypeId,
                Subject = 'Support Case',
                Status = 'New',
                Resolution__c = null);
        caseList.add(supportCase);

        Case accountingCase = new Case(AccountId = a.Id,
                RecordTypeId = accountingCaseRecordTypeId,
                Subject = 'Accounting Case',
                Status = 'New',
                Resolution__c = null);
        caseList.add(accountingCase);

        insert caseList;

        Test.startTest();
            update a;
        Test.stopTest();


        Map<Id, Case> updatedCases = new Map<Id, Case>([SELECT Id, Status, Resolution__c, RecordTypeId FROM Case]);

        for (Case c : updatedCases.values())
        {
            if(c.RecordTypeId == accountingCaseRecordTypeId)
            {
                System.assertEquals('New', c.Status);
                System.assertEquals(null,c.Resolution__c);
            }
            else
            {
                System.assertEquals('Closed', c.Status);
                System.assertEquals('Wont Fix', c.Resolution__c);
            }

        }
    }

}