src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account Lookup</description>
        <inlineHelpText>Choose the Account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Active Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.2/objects/AsyncRequest__c.object
<CustomObject>
    <description>Used for logging Async requests to be processed.</description>
    <label>AsyncRequest</label>
    <nameField>
        <displayFormat>ASYNC-{0000000}</displayFormat>
        <label>AsyncRequest Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AsyncRequests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src.1/objects/Campaign.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <label>Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nurturing</fullName>
                </value>
                <value>
                    <fullName>Demo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.4/objects/Campaign_Influence__c.object
<CustomObject>
    <label>Campaign Influence</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Influence</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Campaign Influence</relationshipLabel>
        <relationshipName>Campaign_Influence</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campaign_Add_Date__c</fullName>
        <label>Campaign Add Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Influence</relationshipLabel>
        <relationshipName>Campaign_Influence</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Campaign Influence</relationshipLabel>
        <relationshipName>Campaign_Influence</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Demo_Request_Reason__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Demo Request Reason</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Campaign Influence</relationshipLabel>
        <relationshipName>Campaign_Influence</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaign_Influences</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.1/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>CampaignId__c</fullName>
        <description>Populated by HubSpot to create a CampaignMember for the Id specified.</description>
        <label>CampaignId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Demo_Request_Reason__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Demo Request Reason</label>
        <referenceTo>Campaign_Influence__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies the User that created the record.  May be different than CreatedBy because of automations.  Set via Apex.</description>
        <label>Source User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.1/objects/SR_Default_Values__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SR Default Values</label>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

src.4/classes/CampaignInfluencesService.cls
public class CampaignInfluencesService 
{
	public static void createCIs(Map<Id, Id> contactIdToCampaignId, Map<Id, Id> contactIdToUserId, AsyncRequest__c ar, fflib_SObjectUnitOfWork uow)
	{
		Contact[] contacts = ContactsSelector.newInstance().selectByIdWithAccount(contactIdToCampaignId.keySet());

		for(Contact contact : contacts)
		{
			uow.registerNew(createCI(contactIdToCampaignId.get(contact.Id), contact.Id, contact.AccountId, contact.Account.Active_Opportunity__c, contactIdToUserId.get(contact.Id), ar.CreatedDate));
			if(contact.CampaignId__c != null) 
			{
				contact.CampaignId__c = null;
				uow.registerDirty(contact);
			}
		}
	}

	public static void createCIsFromOpps(Map<Id, Id> oppIdToCampaignId, Map<Id, Id> oppIdToUserId, AsyncRequest__c ar, fflib_SObjectUnitOfWork uow)
	{
		Opportunity[] opportunities = OpportunitiesSelector.newInstance().selectByIdWithAccountAndProducts(oppIdToCampaignId.keySet());

		for(Opportunity opportunity : opportunities)
		{
			if(opportunity.IsClosed) continue;
			if(opportunity.Account.ParentId != null) continue;
			uow.registerNew(createCI(oppIdToCampaignId.get(opportunity.Id), null, opportunity.AccountId, opportunity.Id, oppIdToUserId.get(opportunity.Id), ar.CreatedDate));
		}
	}

	public static Campaign_Influence__c createCI(Id campaignId, Id contactId, Id accountId, Id opportunityId, Id userId, Datetime addDate)
	{
		return new Campaign_Influence__c(Campaign__c = campaignId,
			Contact__c = contactId,
			Account__c = accountId,
			Opportunity__c = opportunityId,
			Source_User__c = userId,
			Campaign_Add_Date__c = addDate);
	}

	public static void linkOppOnCIs(Set<Id> ids, fflib_SObjectUnitOfWork uow)
	{
		Campaign_Influence__c[] cis = CampaignInfluencesSelector.newInstance().selectCisByAccountId(ids);
		Integer opportunityCiLookback = Integer.valueOf(SR_Default_Values__c.getValues('opportunityCiLookback').Value__c);

		for(Campaign_Influence__c ci : cis)
		{
			if(ci.Opportunity__c != null) continue;
			if(ci.Account__r.Active_Opportunity__c == null) continue;
			if(opportunityCiLookback != null && 
				ci.Campaign_Add_Date__c < ci.Account__r.Active_Opportunity__r.CreatedDate.addDays(-opportunityCiLookback)) continue;
			
			ci.Opportunity__c = ci.Account__r.Active_Opportunity__c;
			uow.registerDirty(ci);
		}
	}

	public static void setDemoRequestReason(Opportunity[] opps, fflib_SObjectUnitOfWork uow)
	{
		for(Opportunity o : opps)
		{
			if(o.Campaign_Influence__r.size() == 0) continue;
			Campaign_Influence__c demoRequestReason = null;
			Map<Datetime, Campaign_Influence__c> dateMap = new Map<Datetime, Campaign_Influence__c>();
			Datetime[] sortedCampaignAddDates = new List<Datetime>();

			for(Campaign_Influence__c ci : o.Campaign_Influence__r)
			{
				if(ci.Demo_Request_Reason__c)
				{
					ci.Demo_Request_Reason__c = false;
					uow.registerDirty(ci);
				} 
				if(ci.Campaign__r.Sub_Type__c == 'Demo') dateMap.put(ci.Campaign_Add_Date__c, ci);
			}

			if(dateMap.isEmpty()) 
			{
				if(o.Demo_Request_Reason__c != null)
				{
					o.Demo_Request_Reason__c = null;
					uow.registerDirty(o);
				}
				continue;
			}
			
			sortedCampaignAddDates.addAll(dateMap.keySet());
			sortedCampaignAddDates.sort();

			demoRequestReason = dateMap.get(sortedCampaignAddDates[0]);
			demoRequestReason.Demo_Request_Reason__c = true;
			uow.registerDirty(demoRequestReason);

			if(o.Demo_Request_Reason__c == null || o.Demo_Request_Reason__c != demoRequestReason.Id)
			{
				o.Demo_Request_Reason__c = demoRequestReason.Id;
				uow.registerDirty(o);
			}
		}
	}

	public static void setDemoRequestReason(Set<Id> ids, fflib_SObjectUnitOfWork uow)
	{
		Map<Id, Opportunity> oppMap = OpportunitiesSelector.newInstance().selectByIdWithCIs(ids);
		setDemoRequestReason(oppMap.values(), uow);
	}
}