src.2/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>RecurSoft__Status__c</fullName>
        <description>Picklist used to determine if an account is an active customer.</description>
        <inlineHelpText>Determined by the status of subscriptions (not created, created, not activated, or cancelled)</inlineHelpText>
        <label>ISB Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Parent account for 1-2 offices</description>
        <label>Account</label>
    </recordTypes>
</CustomObject>

src.3/objects/Asset.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Current_Product_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Shows the related subscription that has the most distant Contract End Date that is not Terminated.  Set from trigger.  Trigger activated by Subscription Last Modified field.</description>
        <label>Current Product Subscription</label>
        <referenceTo>RecurSoft__Product_Subscription__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.3/objects/Cancel_Request__c.object
<CustomObject>
    <description>Junction object between Retention Opportunities and Assets</description>
    <label>Cancel Request</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Cancel Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancel Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipName>OpportunityAssets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cancel_Month__c</fullName>
        <label>Cancel Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>OpportunityAssets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Actively Working</fullName>
                </value>
                <value>
                    <fullName>Negotiating</fullName>
                </value>
                <value>
                    <fullName>Sent Addendum</fullName>
                </value>
                <value>
                    <fullName>Save</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Resume - No Change</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Cancel_Month__c</fullName>
        <description>Sugar field for Save Opportunity</description>
        <label>Cancel Month</label>
        <type>Date</type>
    </fields>
</CustomObject>

src.2/classes/CancelRequestsSelector.cls
public class CancelRequestsSelector extends fflib_SObjectSelector 
{	
	public Schema.SObjectField[] getSObjectFieldList() 
	{
		return new List<Schema.SObjectField> {
			Cancel_Request__c.Id,
            Cancel_Request__c.Cancel_Month__c,
            Cancel_Request__c.Stage__c,
            Cancel_Request__c.Opportunity__c,
            Cancel_Request__c.RecordTypeId 
			};
	}

	public Schema.SObjectType getSObjectType()
	{
		return Cancel_Request__c.SObjectType;
	}

	public static CancelRequestsSelector newInstance()
	{
		return (CancelRequestsSelector) Application.Selector.newInstance(Cancel_Request__c.SObjectType);
	}
	
	public Database.QueryLocator queryLocatorCancelledAccounts()
	{
		//String conditionTest = 'Id IN (\'0010Z00001sr1Wy\',\'0010Z00001sr3om\',\'0010Z00001srAIJ\',\'0010Z00001srAvX\' 
		//,\'0010Z00001srM4H\',\'0010Z00001srWw3\',\'0010Z00001srbea\',\'0010Z00001srcZa\',\'0010Z00001srdvY\',\'0010Z00001srfLG\')';
		String condition = 'Stage__c = \'Cancelled\' AND ' +
            'Opportunity__r.Account.RecurSoft__Status__c = \'Active\' AND ' +
            'RecordType.Name = \'SR Platform\' AND ' +
            '(Cancel_Month__c = LAST_N_Months:2 OR Cancel_Month__c = This_Month)';
        
		fflib_QueryFactory cancelRequestQueryFactory = newQueryFactory();

		new AccountsSelector().configureQueryFactoryFields(cancelRequestQueryFactory, 'Opportunity__r.Account');
		
		new ProductSubscriptionsSelector().configureQueryFactoryFields(cancelRequestQueryFactory, 'Asset__r.Current_Product_Subscription__r');
		
		return Database.getQueryLocator(
			cancelRequestQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList())).
				setCondition(condition).
				toSOQL());
	}
}