src.2/objects/AsyncRequest__c.object
<CustomObject>
    <description>Used for logging Async requests to be processed.</description>
    <label>AsyncRequest</label>
    <nameField>
        <displayFormat>ASYNC-{0000000}</displayFormat>
        <label>AsyncRequest Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AsyncRequests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>AsyncType__c</fullName>
        <label>AsyncType</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AppAdmin_AssetSync</fullName>
                </value>
                <value>
                    <fullName>AppAdmin_HGSync</fullName>
                </value>
                <value>
                    <fullName>AppAdmin_OppSync</fullName>
                </value>
                <value>
                    <fullName>Contract_Email</fullName>
                </value>
                <value>
                    <fullName>Process_Dist_Group</fullName>
                </value>
                <value>
                    <fullName>ProdSub_AfterInsert</fullName>
                </value>
                <value>
                    <fullName>Set_DQ_Delete_CI</fullName>
                </value>
                <value>
                    <fullName>Task_ADR_CI</fullName>
                </value>
                <value>
                    <fullName>Update_Opp_Stage_Demo_Completed</fullName>
                </value>
                <value>
                    <fullName>Update_Opp_Stage_Demo_Scheduled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Params__c</fullName>
        <label>Params</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

src.4/classes/AssetSyncButton_Controller.cls
public with sharing class AssetSyncButton_Controller {

    private final Asset a;
    public Set<Id> assetIds = new Set<Id>();

    public AssetSyncButton_Controller(ApexPages.StandardController stdController) {
        
        a = (Asset)stdController.getRecord();
        assetIds.add(a.Id);
    }
     
    public PageReference autoRun() {
 
        String assetId = ApexPages.currentPage().getParameters().get('id');

        if(!assetIds.isEmpty() && assetId != null) {

			AsyncRequest__c ar = new AsyncRequest__c(AsyncType__c = AsyncMain.TYPE_APPADMIN_ASSETSYNC, 
				Params__c = assetId);
			insert ar;

         	PageReference pageRef = new PageReference('/' + assetId);
	        pageRef.setRedirect(true);
	        return pageRef;

        } else {

        	return null;
        }
    }
}