src.2/objects/Comp_Plan__c.object
<CustomObject>
    <description>Contains the Comp Plan Rules for calculating the Sales Target Multiplier, Payout criteria, Spiffs, etc.</description>
    <label>Comp Plan</label>
    <nameField>
        <label>Comp Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comp Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src.1/objects/Sales_Target__c.object
<CustomObject>
    <label>Sales Target</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Sales Target ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Targets</pluralLabel>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Available_Commission__c</fullName>
        <description>Calculated and set via Apex.  Total of commission earned in each tier of the Comp Plan</description>
        <label>Available Commission</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commission_Qualified_Sales__c</fullName>
        <formula>Commission_Qualified_Sales_Credits__c  +  Commission_Qualified_Spiffs__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commission Qualified Sales</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Comp_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Comp Plan</label>
        <referenceTo>Comp_Plan__c</referenceTo>
        <relationshipLabel>Sales Targets</relationshipLabel>
        <relationshipName>Sales_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Multiplier__c</fullName>
        <description>Calculated in Apex from Comp Plan Rules</description>
        <label>Multiplier</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Revenue_of_Target__c</fullName>
        <description>% of Target Revenue achieved.  Used to calculate Bonus &amp; Commission Multiplier</description>
        <formula>ROUND( Total_Revenue_Credit__c / Revenue_Target__c , 2 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Revenue % of Target</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Revenue_Credit__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total of Individual Revenue Credit on related Sales Credits.  Updated by lookup rollup summary.</description>
        <label>Sales Rep Revenue Credit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Tier_Qualify_Sales_Credit__c</fullName>
        <description>Sum of Individual Credit Portion field on the Sales Credit object with an MSF &gt;= $229. Set by DLRS.  Used for calculating the Bonus and Commission Multiplier.</description>
        <label>Sales Rep Tier Qualify Sales Credit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src.3/classes/SalesTargetsSelector.cls
public class SalesTargetsSelector extends fflib_SObjectSelector 
{
	public Schema.SObjectField[] getSObjectFieldList() 
	{
		return new List<Schema.SObjectField> {
			Sales_Target__c.Id,
			Sales_Target__c.Comp_Plan__c,
			Sales_Target__c.Multiplier__c,
			Sales_Target__c.Revenue_of_Target__c,
			Sales_Target__c.Sales_Rep_Revenue_Credit__c,
			Sales_Target__c.Sales_Rep_Tier_Qualify_Sales_Credit__c,
			Sales_Target__c.Commission_Qualified_Sales__c,
			Sales_Target__c.Available_Commission__c
			 };
	}

	public Schema.SObjectType getSObjectType()
	{
		return Sales_Target__c.SObjectType;
	}

	public static SalesTargetsSelector newInstance()
	{
		return (SalesTargetsSelector) Application.Selector.newInstance(Sales_Target__c.SObjectType);
	}
}