src.2/objects/Comp_Plan__c.object
<CustomObject>
    <description>Contains the Comp Plan Rules for calculating the Sales Target Multiplier, Payout criteria, Spiffs, etc.</description>
    <label>Comp Plan</label>
    <nameField>
        <label>Comp Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comp Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src.4/objects/Comp_Plan_Rule__c.object
<CustomObject>
    <description>Defines the specific criteria and result for a Comp Plan calculation.</description>
    <label>Comp Plan Rule</label>
    <nameField>
        <label>Comp Plan Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comp Plan Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Comp_Plan__c</fullName>
        <label>Comp Plan</label>
        <referenceTo>Comp_Plan__c</referenceTo>
        <relationshipLabel>Comp Plan Rules</relationshipLabel>
        <relationshipName>Comp_Plan_Rules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Operator2__c</fullName>
        <label>Operator2</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Comp_Plan_Rule_Operator</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Comp_Plan_Rule_Operator</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Comp_Plan_Rule_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value2__c</fullName>
        <label>Value2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Variable2__c</fullName>
        <label>Variable2</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Comp_Plan_Rule_Variable</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Variable__c</fullName>
        <label>Variable</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Comp_Plan_Rule_Variable</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

src.1/objects/Sales_Target__c.object
<CustomObject>
    <label>Sales Target</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Sales Target ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Targets</pluralLabel>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Available_Commission__c</fullName>
        <description>Calculated and set via Apex.  Total of commission earned in each tier of the Comp Plan</description>
        <label>Available Commission</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Comp_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Comp Plan</label>
        <referenceTo>Comp_Plan__c</referenceTo>
        <relationshipLabel>Sales Targets</relationshipLabel>
        <relationshipName>Sales_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Multiplier__c</fullName>
        <description>Calculated in Apex from Comp Plan Rules</description>
        <label>Multiplier</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Specifies the type of target. Used to have multiple targets per person in the case of Hybrid Managers. Set on target creation manually by Sales Ops or automatically if a target doesn&#39;t exist for a new Sales Credit.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Rep</fullName>
                </value>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>VP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.1/classes/SalesTargetsService.cls
public class SalesTargetsService 
{
	public static void calculateMultiplier(Set<Id> targetIds, fflib_SObjectUnitOfWork uow)
	{
		Sales_Target__c[] targets = SalesTargetsSelector.newInstance().selectSObjectsById(targetIds);
		calculateMultiplier(targets, uow);
	}

	public static void calculateMultiplier(Sales_Target__c[] targets)
	{
		fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
		calculateMultiplier(targets, uow);
	}

	public static void calculateMultiplier(Sales_Target__c[] targets, fflib_SObjectUnitOfWork uow)
	{
		Map<Id, Comp_Plan__c> compPlanMap = new Map<Id, Comp_Plan__c>([SELECT Id, Name, 
			(SELECT Id, Type__c, Variable__c, Variable2__c, Operator__c, Operator2__c, Value__c, Value2__c, Result__c 
				FROM Comp_Plan_Rules__r ORDER BY Name) 
			FROM Comp_Plan__c]);

		for(Sales_Target__c target : targets)
		{
			if(!compPlanMap.containsKey(target.Comp_Plan__c)) continue;
			Comp_Plan__c plan = compPlanMap.get(target.Comp_Plan__c);
			
			Decimal result = calculateMultiplier(target, plan);			
			if(target.Multiplier__c != result)
			{
				target.Multiplier__c = result;
				uow.registerDirty(target);
			}
			
			Decimal availableCommision = calculateAvailableCommission(target, plan);
			if(target.Available_Commission__c != availableCommision)
			{
				target.Available_Commission__c = availableCommision;
				uow.registerDirty(target);
			}
		}
	}

	public static Decimal calculateMultiplier(Sales_Target__c target, Comp_Plan__c plan)
	{
		//List to collect results from multiple rules
		String[] exprResults = new List<String>();
		
		for(Comp_Plan_Rule__c rule : plan.Comp_Plan_Rules__r)
		{
			if(rule.Type__c != 'Multiplier') continue;

			//Multiple Criteria - Final expression to be evaluated
			String expr;
			//List to collect multiple criteria
			String[] exprMultiple = new List<String>();
			
			//Add first criteria
			exprMultiple.add('('+ target.get(rule.Variable__c) + rule.Operator__c + rule.Value__c + ')');
			
			//Add second criteria
			if(rule.Variable2__c != null) exprMultiple.add('(' + target.get(rule.Variable2__c) + rule.Operator2__c + rule.Value2__c + ')');
			
			//Combine criteria for final expression
			if(exprMultiple.size() == 1)
			{
				expr = exprMultiple[0] + ' * ' + rule.Result__c;
			}
			else
			{
				expr = '(' + String.join(exprMultiple, ' && ') + ') * ' + rule.Result__c;
			}

			System.debug(expr);
			//Add result for this criteria
			exprResults.add(String.valueOf(new RT_Expression(expr).eval()));
		}

		//Multiple Rules - Combine rules for final expression to be evaluated
		if (exprResults.isEmpty()) return null;
		String maxExpr = 'MAX(' + String.join(exprResults,',') + ')';
		System.debug(maxExpr);
		Decimal result = new RT_Expression(maxExpr).eval();
		System.debug(result);

		return result;
	}

	public static Double calculateAvailableCommission(Sales_Target__c target, Comp_Plan__c plan)
	{
		Decimal totalCommission = 0;

		for(Integer i = 0; i < plan.Comp_Plan_Rules__r.size(); i++)
		{
			Comp_Plan_Rule__c rule = plan.Comp_Plan_Rules__r[i];
			if(rule.Type__c != 'Marginal') continue;

			String expr;
			String[] exprMultiple = new List<String>();
			
			exprMultiple.add('('+ target.get(rule.Variable__c) + rule.Operator__c + rule.Value__c + ')');
			
			if(rule.Variable2__c != null) exprMultiple.add('(' + target.get(rule.Variable2__c) + rule.Operator2__c + rule.Value2__c + ')');
			
			if(exprMultiple.size() == 1)
			{
				expr = exprMultiple[0] + ' * ' + rule.Result__c;
			}
			else
			{
				expr = '(' + String.join(exprMultiple, ' && ') + ') * ' + rule.Result__c;
			}
			System.debug(expr);

			Double result = new RT_Expression(expr).eval();
			System.debug(result);
			Double salesRepRevenueCredit = Double.valueOf(target.get(rule.Variable__c));
			if (result > 0)
			{
				Double nextValue = (i == plan.Comp_Plan_Rules__r.size()-1) ? salesRepRevenueCredit : Double.valueOf(plan.Comp_Plan_Rules__r[i+1].Value__c);
				
				if (salesRepRevenueCredit > nextValue)
				{
					totalCommission += (Double.valueOf(plan.Comp_Plan_Rules__r[i+1].Value__c) - Double.valueOf(rule.Value__c)) * rule.Result__c;
				}
				else
				{					
					totalCommission += Math.abs(salesRepRevenueCredit - Double.valueOf(rule.Value__c)) * rule.Result__c;							
				}									
			}			
		}		

		return totalCommission;
	}
}