src.2/objects/Distribution_Group__c.object
<CustomObject>
    <label>Distribution Group</label>
    <nameField>
        <label>Distribution Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src.1/objects/Distribution_Group_Member__c.object
<CustomObject>
    <label>Distribution Group Member</label>
    <nameField>
        <displayFormat>DGM-{000}</displayFormat>
        <label>Distribution Group Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Distribution Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Available__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Distribution_Group__c</fullName>
        <label>Distribution Group</label>
        <referenceTo>Distribution_Group__c</referenceTo>
        <relationshipLabel>Distribution Group Members</relationshipLabel>
        <relationshipName>Distribution_Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Next_Up__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Next Up</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Distribution_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.3/objects/Open_Opp_Limit__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Open Opp Limit</label>
    <fields>
        <fullName>Pipeline__c</fullName>
        <description>Demo Scheduled
Demo Complete
Negotiation Review</description>
        <label>Pipeline</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Staging__c</fullName>
        <label>Staging</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src.3/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>AtPipelineLimit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set via Apex. Used to validate in Distribution Group</description>
        <label>AtPipelineLimit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AtStagingLimit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set via Apex. Used to validate in Distribution Group</description>
        <label>AtStagingLimit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Limit_Pipeline_Opps__c</fullName>
        <label>Limit Pipeline Opps</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Limit_Staging_Opps__c</fullName>
        <label>Limit Staging Opps</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Pipeline_Opps__c</fullName>
        <description>Demo Scheduled
Demo Complete
Negotiation Review</description>
        <label>Number of Pipeline Opps</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Staging_Opps__c</fullName>
        <label>Number of Staging Opps</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src.1/classes/UsersService.cls
public class UsersService 
{	
	public static void updateUserLimits(Set<Id> ids, fflib_SObjectUnitOfWork uow) 
	{		
        Map<Id, Decimal> stagingMap;
        Map<Id, Decimal> pipelineMap;
        User[] users = UsersSelector.newInstance().selectSObjectsById(ids);
        
        for(User u : users)
        {
            Open_Opp_Limit__c oppLimit = Open_Opp_Limit__c.getInstance(u.Id);

            if(stagingMap == null) stagingMap = OpportunitiesSelector.newInstance().selectOwnerStagingOpps(ids);
        	if(pipelineMap == null) pipelineMap = OpportunitiesSelector.newInstance().selectOwnerPipelineOpps(ids);
            
            Decimal stagingActual = stagingMap.get(u.Id) == null ? 0 : stagingMap.get(u.Id);
            Decimal pipelineActual = pipelineMap.get(u.Id) == null ? 0 : pipelineMap.get(u.Id);

            if(stagingActual >= oppLimit.Staging__c && !u.AtStagingLimit__c) u.AtStagingLimit__c = true;
            if(pipelineActual >= oppLimit.Pipeline__c && !u.AtPipelineLimit__c) u.AtPipelineLimit__c = true;  
            if(stagingActual < oppLimit.Staging__c && u.AtStagingLimit__c) u.AtStagingLimit__c = false;
            if(pipelineActual < oppLimit.Pipeline__c && u.AtPipelineLimit__c) u.AtPipelineLimit__c = false; 
            u.Limit_Staging_Opps__c = oppLimit.Staging__c;
            u.Limit_Pipeline_Opps__c = oppLimit.Pipeline__c;
            u.Number_of_Staging_Opps__c = stagingActual;
        	u.Number_of_Pipeline_Opps__c = pipelineActual;
            uow.registerDirty(u);
        }
	}

	public static void checkUserLimits(Id userId) 
	{		
		fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();        
        User[] users = UsersSelector.newInstance().selectSObjectsById(new Set<Id> {userId});
        
        for(User u : users)
        {
            if (u.AtPipelineLimit__c) 
            {
            	List<Distribution_Group_Member__c> usersNextUp = new List<Distribution_Group_Member__c> ([SELECT Id, Name, User__c, User__r.Name, User__r.FirstName, User__r.LastName, Available__c, 
				Next_Up__c, Distribution_Group__c 
				FROM Distribution_Group_Member__c 
				WHERE User__r.Id = :userId AND Next_Up__c = true]);			

				//if (usersNextUp != null && !usersNextUp.isEmpty()) DistributionGroupsService.getNextUser(usersNextUp, uow);
            }            
        }
	}
}