src.2/objects/Distribution_Group__c.object
<CustomObject>
    <label>Distribution Group</label>
    <nameField>
        <label>Distribution Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>CampaignId__c</fullName>
        <description>Create a Campaign Influence with this Campaign Id</description>
        <label>CampaignId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Setting__c</fullName>
        <label>Customer Setting</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Prospects Only</fullName>
                </value>
                <value>
                    <fullName>Customers Only</fullName>
                </value>
                <value>
                    <fullName>Prospects and Customers</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Major_Accounts__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For Distribution Groups that contain only one Major Account rep.  Also, changes the Opportunity Record Type to Enterprise New Practice Business.</description>
        <label>Major Accounts</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Open_Opportunity_Setting__c</fullName>
        <label>Open Opportunity Setting</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Notify Owner</fullName>
                    <default>true</default>
                    <label>Notify Owner</label>
                </value>
                <value>
                    <fullName>Reassign Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Timed_Distribution_Group_Hours__c</fullName>
        <description>Time-based Distribution Groups are groups that only allow an Account to pass through once every X hours. The Distribution Group assignment will be blocked by an Apex validation in ContactsService that compares this field with the Timed Distribution Group Date on the Account object.</description>
        <label>Timed Distribution Group Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Distribution_Group__c/fields/Distribution_Type__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Type__c</fullName>
    <label>Distribution Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Linear</fullName>
                <default>true</default>
                <label>Linear</label>
            </value>
            <value>
                <fullName>Load Balanced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Distribution_Group__c/fields/Field_to_Distribute__c.field-meta.xml
<CustomField>
    <fullName>Field_to_Distribute__c</fullName>
    <label>Field to Distribute</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Distribution_Group__c/fields/ParentObject__c.field-meta.xml
<CustomField>
    <fullName>ParentObject__c</fullName>
    <label>Parent Object</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Distribution_Group__c/fields/Relationship_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Criteria__c</fullName>
    <inlineHelpText>SOQL WHERE clause applied when querying Object records, e.g. Amount &gt; 200</inlineHelpText>
    <label>Relationship Criteria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Distribution_Group__c/fields/Relationship_Criteria_Fields__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Criteria_Fields__c</fullName>
    <inlineHelpText>If you have specified a relationship criteria, you must confirm the fields referenced by it here on separate lines, for example for criteria StageName = &#39;Won&#39; list StageName in this field.</inlineHelpText>
    <label>Relationship Criteria Fields</label>
    <type>TextArea</type>
</CustomField>

src.1/objects/Distribution_Group_Member__c.object
<CustomObject>
    <label>Distribution Group Member</label>
    <nameField>
        <displayFormat>DGM-{000}</displayFormat>
        <label>Distribution Group Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Distribution Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Available__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Distribution_Group__c</fullName>
        <label>Distribution Group</label>
        <referenceTo>Distribution_Group__c</referenceTo>
        <relationshipLabel>Distribution Group Members</relationshipLabel>
        <relationshipName>Distribution_Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Distribution_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/classes/DistributionGroupsSelector.cls
public class DistributionGroupsSelector extends fflib_SObjectSelector
{
	public static Map<Id, Id> distributionQueue;
	
	public Schema.SObjectField[] getSObjectFieldList()
	{
		return new List<Schema.SObjectField> {
				Distribution_Group__c.Id,
				Distribution_Group__c.Name,
				Distribution_Group__c.Open_Opportunity_Setting__c,
				Distribution_Group__c.CampaignId__c,
				Distribution_Group__c.Customer_Setting__c,
				Distribution_Group__c.Distribution_Type__c,
				Distribution_Group__c.Field_to_Distribute__c,
				Distribution_Group__c.ParentObject__c,
				Distribution_Group__c.Relationship_Criteria__c,
				Distribution_Group__c.Relationship_Criteria_Fields__c,
				Distribution_Group__c.Timed_Distribution_Group_Hours__c,
				Distribution_Group__c.Major_Accounts__c
		};
	}
	
	public Schema.SObjectType getSObjectType()
	{
		return Distribution_Group__c.SObjectType;
	}
	
	public static DistributionGroupsSelector newInstance()
	{
		return (DistributionGroupsSelector) Application.Selector.newInstance(Distribution_Group__c.SObjectType);
	}
	
	public Distribution_Group__c[] selectById(Set<Id> ids)
	{
		fflib_QueryFactory distGroupQueryFactory = newQueryFactory();
		
		fflib_QueryFactory distGroupMemberQueryFactory = distGroupQueryFactory.subselectQuery('Distribution_Group_Members__r')
				.selectFields(new DistributionGroupMembersSelector().getSObjectFieldList()).setCondition('Available__c = true and User__r.AtPipelineLimit__c = false and User__r.IsActive = true');
		
		new UsersSelector().configureQueryFactoryFields(distGroupMemberQueryFactory, 'User__r');
		
		return (Distribution_Group__c[]) Database.query(
				distGroupQueryFactory
						.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList()))
						.setCondition('Id IN :ids')
						.toSOQL());
	}
	
	public Distribution_Group__c selectById(Id id)
	{
		fflib_QueryFactory distGroupQueryFactory = newQueryFactory();
		
		fflib_QueryFactory distGroupMemberQueryFactory = distGroupQueryFactory.subselectQuery('Distribution_Group_Members__r')
				.selectFields(new DistributionGroupMembersSelector().getSObjectFieldList()).setCondition('Available__c = true and User__r.IsActive = true');
		
		new UsersSelector().configureQueryFactoryFields(distGroupMemberQueryFactory, 'User__r');
		
		return (Distribution_Group__c) Database.query(
				distGroupQueryFactory
						.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList()))
						.setCondition('Id = :id')
						.toSOQL());
	}
	
	public static Map<Id,Id> getQueueDistributionMap()
	{
		distributionQueue = new Map <Id, Id>();
		for (Distribution_Group__c dg : [SELECT Id, Queue_Id__c FROM Distribution_Group__c WHERE Queue_Id__c != '' AND Active__c = true])
		{
			distributionQueue.put((Id)dg.Queue_Id__c, dg.Id);
		}
		return distributionQueue;
	}
}