src.2/objects/Distribution_Group__c.object
<CustomObject>
    <label>Distribution Group</label>
    <nameField>
        <label>Distribution Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src.1/objects/Distribution_Group_Member__c.object
<CustomObject>
    <label>Distribution Group Member</label>
    <nameField>
        <displayFormat>DGM-{000}</displayFormat>
        <label>Distribution Group Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Distribution Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Available__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Distribution_Group__c</fullName>
        <label>Distribution Group</label>
        <referenceTo>Distribution_Group__c</referenceTo>
        <relationshipLabel>Distribution Group Members</relationshipLabel>
        <relationshipName>Distribution_Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Next_Up__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Next Up</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Distribution_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Distribution_Group_Member__c/fields/Load__c.field-meta.xml
<CustomField>
    <fullName>Load__c</fullName>
    <formula>Total_Open__c / Rep_Limit__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Last calculated Load Percentage</inlineHelpText>
    <label>Load %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Distribution_Group_Member__c/fields/Rep_Limit__c.field-meta.xml
<CustomField>
    <fullName>Rep_Limit__c</fullName>
    <label>Rep Limit</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Distribution_Group_Member__c/fields/Total_Open__c.field-meta.xml
<CustomField>
    <fullName>Total_Open__c</fullName>
    <label>Total Open</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src.1/classes/DistributionGroupMembersSelector.cls
public class DistributionGroupMembersSelector extends fflib_SObjectSelector
{
	public Schema.SObjectField[] getSObjectFieldList()
	{
		return new List<Schema.SObjectField> {
				Distribution_Group_Member__c.Id,
				Distribution_Group_Member__c.Name,
				Distribution_Group_Member__c.User__c,
				Distribution_Group_Member__c.Available__c,
				Distribution_Group_Member__c.Next_Up__c,
				Distribution_Group_Member__c.Load__c,
				Distribution_Group_Member__c.Rep_Limit__c,
				Distribution_Group_Member__c.Total_Open__c,
				Distribution_Group_Member__c.Distribution_Group__c
		};
	}
	
	public Schema.SObjectType getSObjectType()
	{
		return Distribution_Group_Member__c.SObjectType;
	}
	
	public static DistributionGroupMembersSelector newInstance()
	{
		return (DistributionGroupMembersSelector) Application.Selector.newInstance(Distribution_Group_Member__c.SObjectType);
	}
}