src.1/objects/Addendum__c.object
<CustomObject>
    <description>Represents a change to existing contractual terms</description>
    <label>Addendum</label>
    <nameField>
        <label>Addendum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addenda</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addenda</relationshipLabel>
        <relationshipName>Addenda</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Term_Months__c</fullName>
        <label>Contract Term Months</label>
        <summarizedField>Addendum_Line_Item__c.New_Contract_Term_Months__c</summarizedField>
        <summaryForeignKey>Addendum_Line_Item__c.Addendum__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>New_Contract_Start_Date__c</fullName>
        <label>New Contract Start Date</label>
        <summarizedField>Addendum_Line_Item__c.New_Contract_Start_Date__c</summarizedField>
        <summaryForeignKey>Addendum_Line_Item__c.Addendum__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>New_Renewal_Date__c</fullName>
        <label>New Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>New_Subscription_Needed__c</fullName>
        <label>New Subscription Needed</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Addenda</relationshipLabel>
        <relationshipName>Addenda</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Addenda</relationshipLabel>
        <relationshipName>Addenda</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;New&quot;</defaultValue>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Needs Accounting Data</fullName>
                </value>
                <value>
                    <fullName>Accounting Data Received</fullName>
                </value>
                <value>
                    <fullName>Ready For Processing</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Signature Requested</fullName>
                </value>
                <value>
                    <fullName>Signature Expired</fullName>
                </value>
                <value>
                    <fullName>Signature Declined</fullName>
                </value>
                <value>
                    <fullName>Signature Received</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.2/objects/Addendum_Line_Item__c.object
<CustomObject>
    <label>Addendum Line Item</label>
    <nameField>
        <displayFormat>ALI-{000000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addendum Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Addendum__c</fullName>
        <label>Addendum</label>
        <referenceTo>Addendum__c</referenceTo>
        <relationshipLabel>Addendum Line Items</relationshipLabel>
        <relationshipName>Addendum_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Addendum Line Items</relationshipLabel>
        <relationshipName>Addendum_Line_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Contract_Start_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <label>New Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>New_Free_Months__c</fullName>
        <label>New Free Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>New_Free_Month_Setting__c</fullName>
        <label>Free Month Setting</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Extend Contract - At the Beginning</fullName>
                </value>
                <value>
                    <fullName>Include in Contract Period - At the Beginning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>New_Price__c</fullName>
        <label>New Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>New_Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <label>New Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>New_Renewal_Date__c</fullName>
        <description>Set via Apex</description>
        <label>New Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>New_Subscription_Needed__c</fullName>
        <formula>IF( Current_Price__c = New_Price__c &amp;&amp; 
Current_Next_Invoice_Date__c = New_Next_Invoice_Date__c &amp;&amp; 
Current_Renewal_Date__c = New_Renewal_Date__c , 
&quot;&quot;, 
&quot;Needs New Subscription&quot; )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>New Subscription Needed</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Trial_End_Date__c</fullName>
        <label>New Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>New_Trial_Period_Days__c</fullName>
        <label>New Trial Period (Days)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pricebook_Entry_Id__c</fullName>
        <formula>Asset__r.Product2.Standard_Pricebook_Entry_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pricebook Entry Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

src.3/objects/Asset.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Current_Product_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Shows the related subscription that has the most distant Contract End Date that is not Terminated.  Set from trigger.  Trigger activated by Subscription Last Modified field.</description>
        <label>Current Product Subscription</label>
        <referenceTo>RecurSoft__Product_Subscription__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>New_Free_Months__c</fullName>
        <description>Used to calculate Keep information on Save opportunities</description>
        <formula>If(ISPICKVAL( Save_Offer_Waived_Months__c , &quot;Accepted&quot;), Number_of_waived_months_offered__c ,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>New Free Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Signed_Date__c</fullName>
        <label>Contract Signed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Initial_Contract_Term__c</fullName>
        <defaultValue>12</defaultValue>
        <inlineHelpText>Contract duration, in months.</inlineHelpText>
        <label>Contract Term (Months)</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Actively working</fullName>
                </value>
                <value>
                    <fullName>Dispute Resolution</fullName>
                </value>
                <value>
                    <fullName>Pending Cancel</fullName>
                </value>
                <value>
                    <fullName>Pending Save</fullName>
                </value>
                <value>
                    <fullName>Future Cancel</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Addendum__c.field-meta.xml
<CustomField>
    <fullName>Addendum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Addendum</label>
    <referenceTo>Addendum__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

src.3/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Free_Month_Setting__c</fullName>
        <description>Override opportunity free months</description>
        <label>Orientation Month Setting</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Extend Contract - At the Beginning</fullName>
                </value>
                <value>
                    <fullName>Include in Contract Period - At the Beginning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Free_Months__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Override opportunity free months</description>
        <inlineHelpText>Override opportunity free months</inlineHelpText>
        <label>Number of Orientation Months</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_End_Date_Editable__c</fullName>
        <label>Contract Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_Start_Date_New__c</fullName>
        <label>Contract Term Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Product_Subscription__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This field contains product subscription for current opportunity product.</inlineHelpText>
        <label>Product Subscription</label>
        <referenceTo>RecurSoft__Product_Subscription__c</referenceTo>
        <relationshipLabel>Opportunity Product (Product Subscription)</relationshipLabel>
        <relationshipName>RecurSoft_Opportunity_Product3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <formula>IF( Is_Monthly__c ,
IF( TEXT( Trial__c ) = &quot;&quot; ,
 null ,
 RecurSoft__Contract_Term_Start_Date_New__c + VALUE( TEXT( Trial__c ))) ,
null )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Trial__c</fullName>
        <label>Trial Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>120</fullName>
                </value>
                <value>
                    <fullName>180</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.2/classes/AddendaService.cls
public class AddendaService 
{
	public static void processSignatureReceived(Set<Id> ids, fflib_SObjectUnitOfWork uow)
	{
		Addendum__c[] addenda = AddendaSelector.newInstance().selectByIdWithAddendumLineItems(ids);

		for(Addendum__c addendum : addenda)
		{
			if(addendum.New_Subscription_Needed__c == null)
			{
				AddendaService.updateTrialDate(addendum, uow);
				addendum.Status__c = 'Closed';
				addendum.OwnerId = addendum.CreatedById;
				uow.registerDirty(addendum);
			}
			else
			{
				AddendaService.newAddendumOpp(addendum, uow);
				AddendaService.newAddendumOppAddProduct(addendum, uow);
			}
		}
	}

	public static void updateTrialDate(Addendum__c addendum, fflib_SObjectUnitOfWork uow)
	{
		for(Addendum_Line_Item__c ali : addendum.Addendum_Line_Items__r)
		{
			if(ali.Asset__r.Current_Product_Subscription__c != null)
			{
				RecurSoft__Product_Subscription__c ps = new RecurSoft__Product_Subscription__c(Id = ali.Asset__r.Current_Product_Subscription__c);
				ps.Trial_End_Date__c = ali.New_Trial_End_Date__c;
				uow.registerDirty(ps);

				Asset a = new Asset(Id = ali.Asset__c);
				a.Trial_End_Date__c = ali.New_Trial_End_Date__c;
				uow.registerDirty(a);
			}
			else
			{
				Asset a = new Asset(Id = ali.Asset__c);
				a.Trial_End_Date__c = ali.New_Trial_End_Date__c;
				uow.registerDirty(a);
			}
		}
	}

	public static void newAddendumOpp(Addendum__c addendum, fflib_SObjectUnitOfWork uow)
	{		
		Opportunity o = new Opportunity(RecordTypeId = SRUtilities.getRecordTypeMap('Opportunity').get('Add-On Business').getRecordTypeId(),
			AccountId = addendum.Account__c,
			CloseDate = Date.today(),
			StageName = 'Qualified',
			RecurSoft__Contract_Signed_Date__c = Date.today(),
			Name = 'Modify Product: ' + addendum.Name,
			RecurSoft__Initial_Contract_Term__c = addendum.Contract_Term_Months__c,
			Pricebook2Id = SRUtilities.getStdPricebookId(),
			Addendum__c = addendum.Id,
			OwnerId = '005i0000002gn9T');
		uow.registerNew(o);			

		for(Addendum_Line_Item__c ali : addendum.Addendum_Line_Items__r)
		{			
			if(ali.Asset__c == null) continue;
			OpportunityLineItem oppLi = new OpportunityLineItem(PricebookEntryId = ali.Pricebook_Entry_Id__c,
				Quantity = 1,
				UnitPrice = ali.New_Price__c,
				Number_of_Free_Months__c = ali.New_Free_Months__c,
				Free_Month_Setting__c = ali.New_Free_Month_Setting__c,
				Trial__c = String.valueOf(ali.New_Trial_Period_Days__c),
				RecurSoft__Contract_Term_Start_Date_New__c = ali.New_Contract_Start_Date__c,
				RecurSoft__Contract_Term_End_Date_Editable__c = ali.New_Renewal_Date__c
				);
			uow.registerNew(oppLi, OpportunityLineItem.OpportunityId, o);			
		}

		addendum.OwnerId = '00Gi00000034JUX';
		uow.registerRelationship(addendum, Addendum__c.Opportunity__c, o);
		uow.registerDirty(addendum);
	}

	public static void newAddendumOppAddProduct(Addendum__c addendum, fflib_SObjectUnitOfWork uow)
	{			
		Opportunity o = new Opportunity(RecordTypeId = SRUtilities.getRecordTypeMap('Opportunity').get('Add Product').getRecordTypeId(),
			AccountId = addendum.Account__c,
			CloseDate = Date.today(),
			StageName = 'Qualified',
			RecurSoft__Contract_Signed_Date__c = Date.today(),
			Name = 'Add Product: ' + addendum.Name,
			RecurSoft__Initial_Contract_Term__c = addendum.Contract_Term_Months__c,
			Pricebook2Id = addendum.Price_Book__c,
			Addendum__c = addendum.Id,
			OwnerId = '005i0000002gn9T');

		for(Addendum_Line_Item__c ali : addendum.Addendum_Line_Items__r)
		{			
			if(ali.Asset__c != null) continue;

			uow.registerNew(o);	

			OpportunityLineItem oppLi = new OpportunityLineItem(PricebookEntryId = ali.Pricebook_Entry_Id__c,
				Quantity = ali.New_Quantity__c,
				UnitPrice = ali.New_Price__c);
			uow.registerNew(oppLi, OpportunityLineItem.OpportunityId, o);			
		}		
	}
}