src.1/objects/Addendum__c.object
<CustomObject>
    <description>Represents a change to existing contractual terms</description>
    <label>Addendum</label>
    <nameField>
        <label>Addendum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addenda</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addenda</relationshipLabel>
        <relationshipName>Addenda</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Term_Months__c</fullName>
        <label>Contract Term Months</label>
        <summarizedField>Addendum_Line_Item__c.New_Contract_Term_Months__c</summarizedField>
        <summaryForeignKey>Addendum_Line_Item__c.Addendum__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>New_Subscription_Needed__c</fullName>
        <label>New Subscription Needed</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Addenda</relationshipLabel>
        <relationshipName>Addenda</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status_Message__c</fullName>
        <formula>IF( Minimum_Number_of_Modifications__c = 0 , &quot;There are still products on this Addendum without any modifications. Either update the product modifications or remove any products not being modified.&quot; ,
    CASE( Status__c ,
    &quot;New&quot; , &quot;Ready&quot; /*&quot;This Addendum hasn&#39;t been submitted for processing yet.&quot;*/ ,
    &quot;Needs Accounting Data&quot; , &quot;This Addendum still requires Accounting data, and hasn&#39;t been submitted for processing yet.&quot; , 
    &quot;Accounting Data Received&quot; , &quot;Ready&quot; /*&quot;This Addendum hasn&#39;t been submitted for processing yet.&quot;*/ ,
    &quot;Ready For Processing&quot; , &quot;Ready&quot; ,
    &quot;Not Approved&quot; , &quot;This Addendum hasn&#39;t been re-submitted for processing yet.&quot; ,
    &quot;Signature Requested&quot; , &quot;This Addendum has already been submitted for processing.&quot; ,
    &quot;Signature Expired&quot; , &quot;The signature request expired for this Addendum and it hasn&#39;t been re-submitted for processing yet.&quot; ,
    &quot;Signature Declined&quot; , &quot;The signature request was declined for this Addendum and it hasn&#39;t been re-submitted for processing yet.&quot; ,
    &quot;Signature Received&quot; , &quot;The signature has been received for this Addendum.&quot; ,
    &quot;Closed&quot; , &quot;The signature has been received for this Addendum.&quot; ,
    &quot;Ready&quot;)
			)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status Message</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;New&quot;</defaultValue>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Needs Accounting Data</fullName>
                </value>
                <value>
                    <fullName>Accounting Data Received</fullName>
                </value>
                <value>
                    <fullName>Ready For Processing</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Signature Requested</fullName>
                </value>
                <value>
                    <fullName>Signature Expired</fullName>
                </value>
                <value>
                    <fullName>Signature Declined</fullName>
                </value>
                <value>
                    <fullName>Signature Received</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscriber_ID__c</fullName>
        <formula>Account__r.Subscriber_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subscriber ID</label>
        <type>Text</type>
    </fields>
</CustomObject>

src.2/classes/AddendaSelector.cls
public class AddendaSelector extends fflib_SObjectSelector 
{
	public Schema.SObjectField[] getSObjectFieldList() 
	{
		return new List<Schema.SObjectField> {
			Addendum__c.Id,
			Addendum__c.Account__c,
			Addendum__c.Contract_Term_Months__c,
			Addendum__c.CreatedById,
			Addendum__c.Name,
			Addendum__c.New_Subscription_Needed__c,
			Addendum__c.OwnerId,
			Addendum__c.Price_Book__c,
			Addendum__c.Status__c,
			Addendum__c.Status_Message__c,
			Addendum__c.Subscriber_ID__c		
			};
	}

	public Schema.SObjectType getSObjectType()
	{
		return Addendum__c.SObjectType;
	}

	public static AddendaSelector newInstance()
	{
		return (AddendaSelector) Application.Selector.newInstance(Addendum__c.SObjectType);
	}

	public Addendum__c[] selectByIdWithAddendumLineItems(Set<Id> ids)
	{
		assertIsAccessible();

		fflib_QueryFactory addendumQueryFactory = newQueryFactory();

		fflib_QueryFactory addendumLineItemQueryFactory = new AddendumLineItemsSelector().addQueryFactorySubselect(addendumQueryFactory);

		new AssetsSelector().configureQueryFactoryFields(addendumLineItemQueryFactory, 'Asset__r');

		return (Addendum__c[]) Database.query(
			addendumQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList())).setCondition('Id IN :ids').toSOQL());
	} 
}