src.1/objects/Addendum__c.object
<CustomObject>
    <description>Represents a change to existing contractual terms</description>
    <label>Addendum</label>
    <nameField>
        <label>Addendum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addenda</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>New_Contract_Start_Date__c</fullName>
        <label>New Contract Start Date</label>
        <summarizedField>Addendum_Line_Item__c.New_Contract_Start_Date__c</summarizedField>
        <summaryForeignKey>Addendum_Line_Item__c.Addendum__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>New_Renewal_Date__c</fullName>
        <label>New Renewal Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

src.2/objects/Addendum_Line_Item__c.object
<CustomObject>
    <label>Addendum Line Item</label>
    <nameField>
        <displayFormat>ALI-{000000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addendum Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Addendum__c</fullName>
        <label>Addendum</label>
        <referenceTo>Addendum__c</referenceTo>
        <relationshipLabel>Addendum Line Items</relationshipLabel>
        <relationshipName>Addendum_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Asset_Type__c</fullName>
        <formula>TEXT( Asset__r.Product2.Family )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Asset Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Addendum Line Items</relationshipLabel>
        <relationshipName>Addendum_Line_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Change_MSF__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Change MSF</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current_Next_Invoice_Date__c</fullName>
        <formula>IF( ( ISBLANK( Asset__r.Current_Product_Subscription__c ) || 
Asset__r.Current_Product_Subscription__r.RecurSoft__Unit_Price__c = 0 ) ,
Asset__r.Next_Payment_Date__c ,
Asset__r.Current_Product_Subscription__r.Next_Payment_Date__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Next Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Current_Price__c</fullName>
        <formula>IF( ( ISBLANK( Asset__r.Current_Product_Subscription__c ) ||
Asset__r.Current_Product_Subscription__r.RecurSoft__Unit_Price__c = 0 ), 
 Asset__r.Price ,
Asset__r.Current_Product_Subscription__r.RecurSoft__Unit_Price__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Renewal_Date__c</fullName>
        <formula>IF( ( ISBLANK( Asset__r.Current_Product_Subscription__c ) || 
Asset__r.Current_Product_Subscription__r.RecurSoft__Unit_Price__c = 0 ) ,
 Asset__r.Contract_End_Date__c ,
Asset__r.Current_Product_Subscription__r.Contract_End_Date__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Current_Trial_End_Date__c</fullName>
        <formula>IF( ( ISBLANK( Asset__r.Current_Product_Subscription__c ) || 
Asset__r.Current_Product_Subscription__r.RecurSoft__Unit_Price__c = 0 ||
ISBLANK( Asset__r.Current_Product_Subscription__r.Trial_End_Date__c )) , 
 Asset__r.Trial_End_Date__c ,
Asset__r.Current_Product_Subscription__r.Trial_End_Date__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deferred_Months__c</fullName>
        <label>Deferred Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Defer_Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Defer Billing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Extend_Satisfaction_Period__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Extend Satisfaction Period</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>New_Contract_Start_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <label>New Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>New_Contract_Term_Months__c</fullName>
        <label>New Contract Term (Months)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>New_Free_Months__c</fullName>
        <label>New Free Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>New_Free_Month_Setting__c</fullName>
        <label>Free Month Setting</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Extend Contract - At the Beginning</fullName>
                </value>
                <value>
                    <fullName>Include in Contract Period - At the Beginning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>New_MSF__c</fullName>
        <label>New MSF</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>New_Next_Invoice_Date__c</fullName>
        <description>Set via Apex</description>
        <label>New Next Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>New_Price__c</fullName>
        <label>New Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>New_Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <label>New Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>New_Renewal_Date__c</fullName>
        <description>Set via Apex</description>
        <label>New Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>New_Trial_End_Date__c</fullName>
        <label>New Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>New_Trial_Period_Days__c</fullName>
        <label>New Trial Period (Days)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Original_Agreement_Date__c</fullName>
        <formula>Asset__r.Most_Recent_Contract_Signed_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Original Agreement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pricebook_Entry_Id__c</fullName>
        <formula>Asset__r.Product2.Standard_Pricebook_Entry_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pricebook Entry Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Waived_Months__c</fullName>
        <label>Waived Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Waive_Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Waive Billing</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Addendum_Line_Item__c/fields/NewTerm__c.field-meta.xml
<CustomField>
    <fullName>NewTerm__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New Term</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Addendum_Line_Item__c/fields/NewTerm_Months__c.field-meta.xml
<CustomField>
    <fullName>NewTerm_Months__c</fullName>
    <label>New Term Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Addendum_Line_Item__c/fields/PriceBookEntry_Contract_Name__c.field-meta.xml
<CustomField>
    <fullName>PriceBookEntry_Contract_Name__c</fullName>
    <description>Contract Display Name for Add Product. Shows up on PDF for customer.  Set via Lightning component.</description>
    <label>PriceBookEntry Contract Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Addendum_Line_Item__c/fields/PriceBookEntry_Name__c.field-meta.xml
<CustomField>
    <fullName>PriceBookEntry_Name__c</fullName>
    <label>Product Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Addendum_Line_Item__c/fields/PriceBookEntry_Price__c.field-meta.xml
<CustomField>
    <fullName>PriceBookEntry_Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Addendum_Line_Item__c/fields/PriceBookEntry_Product_Family__c.field-meta.xml
<CustomField>
    <fullName>PriceBookEntry_Product_Family__c</fullName>
    <description>Product Family for Add Product. Used to validate one product per family.  Set via Lightning component.</description>
    <label>PriceBookEntry Product Family</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Addendum_Line_Item__c/fields/PriceBookEntryId__c.field-meta.xml
<CustomField>
    <fullName>PriceBookEntryId__c</fullName>
    <description>PricebookEntryId for Add Product dependent on Price Book selected on Addendum. Not able to do a lookup to PricebookEntry. Set via Lightning component.</description>
    <label>PriceBookEntryId</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Addendum_Line_Item__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <formula>IF ( ISBLANK(Asset__c), PriceBookEntry_Contract_Name__c , Asset__r.Product2.Contract_Display_Name__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

src.3/objects/Addendum_Snippet__c.object
<CustomObject>
    <label>Addendum Snippet</label>
    <nameField>
        <label>Addendum Snippet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addendum Snippets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Snippet_Text__c</fullName>
        <label>Snippet Text</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
</CustomObject>

src.3/objects/Asset.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

src.3/classes/AddendumLineItemsSelector.cls
public class AddendumLineItemsSelector extends fflib_SObjectSelector 
{
	public Schema.SObjectField[] getSObjectFieldList() 
	{
		return new List<Schema.SObjectField> {
			Addendum_Line_Item__c.Id,
			Addendum_Line_Item__c.Addendum__c,
			Addendum_Line_Item__c.Asset__c,
			Addendum_Line_Item__c.Asset_Type__c,
			Addendum_Line_Item__c.Change_MSF__c,
			Addendum_Line_Item__c.CreatedById,
			Addendum_Line_Item__c.Current_Next_Invoice_Date__c,
			Addendum_Line_Item__c.Current_Renewal_Date__c,
			Addendum_Line_Item__c.Current_Trial_End_Date__c,
			Addendum_Line_Item__c.Current_Price__c,
			Addendum_Line_Item__c.Defer_Billing__c,
			Addendum_Line_Item__c.Deferred_Months__c,
			Addendum_Line_Item__c.Extend_Satisfaction_Period__c,
			Addendum_Line_Item__c.New_Contract_Start_Date__c,
			Addendum_Line_Item__c.New_Contract_Term_Months__c,
			Addendum_Line_Item__c.New_Free_Months__c,
			Addendum_Line_Item__c.New_Free_Month_Setting__c,
			Addendum_Line_Item__c.New_MSF__c,
			Addendum_Line_Item__c.New_Next_Invoice_Date__c,
			Addendum_Line_Item__c.New_Price__c,
			Addendum_Line_Item__c.New_Quantity__c,
			Addendum_Line_Item__c.New_Renewal_Date__c,
			Addendum_Line_Item__c.New_Trial_Period_Days__c,
			Addendum_Line_Item__c.New_Trial_End_Date__c,
			Addendum_Line_Item__c.NewTerm__c,
			Addendum_Line_Item__c.NewTerm_Months__c,
			Addendum_Line_Item__c.Original_Agreement_Date__c,
			Addendum_Line_Item__c.PriceBookEntryId__c,
			Addendum_Line_Item__c.Pricebook_Entry_Id__c,
			Addendum_Line_Item__c.PriceBookEntry_Contract_Name__c,
			Addendum_Line_Item__c.PriceBookEntry_Name__c,
			Addendum_Line_Item__c.PriceBookEntry_Price__c,
			Addendum_Line_Item__c.PriceBookEntry_Product_Family__c,
			Addendum_Line_Item__c.Product_Name__c,
			Addendum_Line_Item__c.Trial_End_Date__c,
			Addendum_Line_Item__c.Waive_Billing__c,
			Addendum_Line_Item__c.Waived_Months__c
			};
	}

	public Schema.SObjectType getSObjectType()
	{
		return Addendum_Line_Item__c.SObjectType;
	}

	public static AddendumLineItemsSelector newInstance()
	{
		return (AddendumLineItemsSelector) Application.Selector.newInstance(Addendum_Line_Item__c.SObjectType);
	}

	public Addendum_Line_Item__c[] selectByAddendumId(Addendum_Line_Item__c[] addendumLineItems)
	{
		Set<Id> ids = new Set<Id>();

		for(Addendum_Line_Item__c addendumLineItem : addendumLineItems)
		{			
			ids.add(addendumLineItem.Addendum__c);
		}

		fflib_QueryFactory addendumLineItemQueryFactory = newQueryFactory();
		new AddendaSelector().configureQueryFactoryFields(addendumLineItemQueryFactory, 'Addendum__r');	
		
		return (Addendum_Line_Item__c[]) Database.query(
				addendumLineItemQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList())).setCondition('Addendum__c IN :ids').toSOQL());
	}

	public Map<String, String> getSnippetMap()
	{
		Map<String, String> snipMap = new Map<String, String>();
		
		Addendum_Snippet__c[] snips = [SELECT Id, Name, Snippet_Text__c FROM Addendum_Snippet__c];

		for(Addendum_Snippet__c snip : snips)
		{
			snipMap.put(snip.Name, snip.Snippet_Text__c);
		}

		return snipMap;
	}

	public Addendum_Line_Item__c[] selectByAddendumIds(Set<Id> ids)
	{		
		fflib_QueryFactory addendumLineItemQueryFactory = newQueryFactory();

		new AddendaSelector().configureQueryFactoryFields(addendumLineItemQueryFactory, 'Addendum__r');	
				
		new AssetsSelector().configureQueryFactoryFields(addendumLineItemQueryFactory, 'Asset__r');
	
		return (Addendum_Line_Item__c[]) Database.query(
				addendumLineItemQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList())).setCondition('Addendum__c IN :ids').toSOQL());
	}

	public Addendum_Line_Item__c[] selectAddProductsByAddendumId(Set<Id> ids)
	{				
		fflib_QueryFactory addendumLineItemQueryFactory = newQueryFactory();		
				
		return (Addendum_Line_Item__c[]) Database.query(
				addendumLineItemQueryFactory
					.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList()))
					.setCondition('Addendum__c IN :ids AND Asset__c = null').toSOQL());
	} 
}