src.4/objects/Bonus_Commission__c.object
<CustomObject>
    <description>Used to calculate and report on the total Bonus &amp; Commissions for a corresponding Sales Target.  Using a different object for Sharing visibility.  Sales Reps should be able to see each others Sales Targets but not each others Bonus &amp; Commissions.</description>
    <label>Bonus &amp; Commission</label>
    <nameField>
        <displayFormat>BC-{00000}</displayFormat>
        <label>Bonus &amp; Commission ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bonus &amp; Commissions</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Sales_Target__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The related Sales Target for the Bonus &amp; Commission</description>
        <label>Sales Target</label>
        <referenceTo>Sales_Target__c</referenceTo>
        <relationshipLabel>Bonus &amp; Commissions</relationshipLabel>
        <relationshipName>Bonus_Commissions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.1/objects/Sales_Target__c.object
<CustomObject>
    <label>Sales Target</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Sales Target ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Targets</pluralLabel>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Sub_Team__c</fullName>
        <label>Sub-Team</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inside Sales</fullName>
                </value>
                <value>
                    <fullName>Territory Sales</fullName>
                </value>
                <value>
                    <fullName>Outside Sales</fullName>
                </value>
                <value>
                    <fullName>Major Accounts</fullName>
                </value>
                <value>
                    <fullName>Mid-Market</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.3/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Sub_Team__c</fullName>
        <label>Sub-Team</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Executive</fullName>
                </value>
                <value>
                    <fullName>Senior Account Executive</fullName>
                </value>
                <value>
                    <fullName>Extended Sales Representative</fullName>
                </value>
                <value>
                    <fullName>Outside Sales Representative</fullName>
                </value>
                <value>
                    <fullName>Enterprise Sales Representative</fullName>
                </value>
                <value>
                    <fullName>Senior Account Executive Manager</fullName>
                </value>
                <value>
                    <fullName>Account Executive Manager</fullName>
                </value>
                <value>
                    <fullName>Extended Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Outside Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Inside Sales</fullName>
                </value>
                <value>
                    <fullName>Extended Sales</fullName>
                </value>
                <value>
                    <fullName>Outside Sales</fullName>
                </value>
                <value>
                    <fullName>Enterprise Sales</fullName>
                </value>
                <value>
                    <fullName>Specialty Team</fullName>
                </value>
                <value>
                    <fullName>Major Accounts Executive</fullName>
                </value>
                <value>
                    <fullName>Major Accounts Manager</fullName>
                </value>
                <value>
                    <fullName>Account Development Rep</fullName>
                </value>
                <value>
                    <fullName>Account Development Manager</fullName>
                </value>
                <value>
                    <fullName>Inside Sales Director</fullName>
                </value>
                <value>
                    <fullName>Territory Sales Director</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.3/classes/SalesTargets.cls
public class SalesTargets extends fflib_SObjectDomain 
{
	public Map<Id, User> userMap;
	
	public SalesTargets(Sales_Target__c[] salesTargets) 
	{
		super(salesTargets);
		Configuration.disableTriggerCRUDSecurity();
	}

	public class Constructor implements fflib_SObjectDomain.IConstructable
	{
		public fflib_SObjectDomain construct(List<SObject> sObjectList)
		{
			return new SalesTargets(sObjectList);
		}
	}

	public override	void onBeforeInsert()
	{
		for(Sales_Target__c st : (Sales_Target__c[]) Records) 
		{
			this.setSubTeam(st);
		}
	}

	public override void onAfterInsert()
	{
		Bonus_Commission__c[] newBCs = new List<Bonus_Commission__c>();

		for(Sales_Target__c t : (Sales_Target__c[]) Records) 
		{
			Bonus_Commission__c bc = new Bonus_Commission__c(Sales_Target__c = t.Id,
				OwnerId = t.OwnerId);
			newBCs.add(bc);
		}

		insert newBCs;
	}

	public override	void onBeforeUpdate(Map<Id, SObject> existingRecords)
	{
		SalesTargetsService.calculateMultiplier((Sales_Target__c[]) Records);
	}

	public void setSubTeam(Sales_Target__c st)
	{
		if(userMap == null) userMap = new Map<Id, User>(UsersSelector.newInstance().selectActiveWithSubTeam());
		if(!userMap.containsKey(st.OwnerId)) return;
		st.Sub_Team__c = userMap.get(st.OwnerId).Sub_Team__c;
	}
}