src.4/objects/Bonus_Commission__c.object
<CustomObject>
    <description>Used to calculate and report on the total Bonus &amp; Commissions for a corresponding Sales Target.  Using a different object for Sharing visibility.  Sales Reps should be able to see each others Sales Targets but not each others Bonus &amp; Commissions.</description>
    <label>Bonus &amp; Commission</label>
    <nameField>
        <displayFormat>BC-{00000}</displayFormat>
        <label>Bonus &amp; Commission ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bonus &amp; Commissions</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Sales_Target__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The related Sales Target for the Bonus &amp; Commission</description>
        <label>Sales Target</label>
        <referenceTo>Sales_Target__c</referenceTo>
        <relationshipLabel>Bonus &amp; Commissions</relationshipLabel>
        <relationshipName>Bonus_Commissions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.1/objects/Bonus_Commission_Credit__c.object
<CustomObject>
    <description>Used to calculate and report on the Bonus &amp; Commissions for a corresponding Sales Credit. Using a different object for Sharing visibility. Sales Reps should be able to see each others Sales Credits but not each others Bonus &amp; Commission Credits.</description>
    <label>Bonus &amp; Commission Credit</label>
    <nameField>
        <displayFormat>BCC-{000000}</displayFormat>
        <label>Bonus &amp; Commission Credit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bonus &amp; Commission Credits</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Bonus_Commission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The related Bonus &amp; Commission record for the Bonus &amp; Commission Credit</description>
        <label>Bonus &amp; Commission</label>
        <referenceTo>Bonus_Commission__c</referenceTo>
        <relationshipLabel>Bonus &amp; Commission Credits</relationshipLabel>
        <relationshipName>Bonus_Commission_Credits</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Credit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The related Sales Credit for the Bonus &amp; Commission Credit</description>
        <label>Sales Credit</label>
        <referenceTo>Sales_Credit__c</referenceTo>
        <relationshipLabel>Bonus &amp; Commission Credits</relationshipLabel>
        <relationshipName>Bonus_Commission_Credits</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.2/objects/Sales_Credit__c.object
<CustomObject>
    <label>Sales Credit</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Sales Credit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Credits</pluralLabel>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Manager_Target__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales Target of the Manager</description>
        <label>Manager Target</label>
        <referenceTo>Sales_Target__c</referenceTo>
        <relationshipLabel>Sales Credits (Manager Target)</relationshipLabel>
        <relationshipName>Sales_Credits1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Sales Credits (Manager)</relationshipLabel>
        <relationshipName>Mgr_Sales_Credits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Contract_Signed_Date__c</fullName>
        <description>The date the contract was signed for the related opportunity object.</description>
        <formula>Opportunity__r.RecurSoft__Contract_Signed_Date__c</formula>
        <inlineHelpText>The date the contract was signed for the related opportunity object.</inlineHelpText>
        <label>Opportunity Contract Signed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity_Contract_Signed_Month__c</fullName>
        <formula>CASE( MONTH( Opportunity_Contract_Signed_Date__c ) , 1, &quot;January&quot;, 2, &quot;February&quot;, 3, &quot;March&quot;, 4, &quot;April&quot;, 5, &quot;May&quot;, 6, &quot;June&quot;, 7, &quot;July&quot;, 8, &quot;August&quot;, 9, &quot;September&quot;, 10, &quot;October&quot;, 11, &quot;November&quot;, 12, &quot;December&quot;, &quot;N/A&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Contract Signed Month</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Contract_Signed_Year__c</fullName>
        <formula>TEXT( YEAR( Opportunity_Contract_Signed_Date__c ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Contract Signed Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Override_Trigger_Logic__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, this will prevent the trigger logic that automatically adds the lookup relationship to the target based on the contract signed date. The total actual credits for each target will still be updated appropriately.</description>
        <inlineHelpText>Check to override the trigger logic. This will allow the Sales Target lookup fields to be changed manually. Unchecking will revert to the trigger logic and automatically assign the Sales Target lookup fields.</inlineHelpText>
        <label>Override Trigger Logic</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Target__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep Target</label>
        <referenceTo>Sales_Target__c</referenceTo>
        <relationshipLabel>Sales Credits (Sales Rep Target)</relationshipLabel>
        <relationshipName>Sales_Credits3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Rep Sales Credits</relationshipLabel>
        <relationshipName>Rep_Sales_Credits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VP_Target__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales Target of the VP</description>
        <label>VP Target</label>
        <referenceTo>Sales_Target__c</referenceTo>
        <relationshipLabel>Sales Credits (VP Target)</relationshipLabel>
        <relationshipName>Sales_Credits2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VP</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Sales Credits (VP)</relationshipLabel>
        <relationshipName>Sales_Credits</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.1/objects/Sales_Target__c.object
<CustomObject>
    <label>Sales Target</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Sales Target ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Targets</pluralLabel>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Manager__c</fullName>
        <label>Manager</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Target Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Date__c</fullName>
        <inlineHelpText>Select the first day of the target month.</inlineHelpText>
        <label>Target Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Specifies the type of target. Used to have multiple targets per person in the case of Hybrid Managers. Set on target creation manually by Sales Ops or automatically if a target doesn&#39;t exist for a new Sales Credit.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Rep</fullName>
                </value>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>VP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unique_Target__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Ensures that the combination of Target Owner, Year, and Month are unique for each target.</description>
        <inlineHelpText>Ensures that the combination of Target Owner, Year, and Month are unique for each target.</inlineHelpText>
        <label>Unique Target</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>VP__c</fullName>
        <label>VP</label>
        <length>40</length>
        <type>Text</type>
    </fields>
</CustomObject>

src.1/objects/SR_Default_Values__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SR Default Values</label>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

src.2/classes/SalesCreditsService.cls
public without sharing class SalesCreditsService 
{
	public static void assignSalesCreditToSalesTarget(Sales_Credit__c[] salesCredits)
	{
		fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
		String[] targetKeys = new List<String>();
		Map<String, Id> targetIdsByKey = new Map<String, Id>();
		Map<String, Sales_Target__c> newTargetsCreated = new Map<String, Sales_Target__c>();
		Set<Id> repIds = new Set<Id>();
		//String salesTargetRolesProfiles = SR_Default_Values__c.getInstance('salesTargetRolesProfiles').Value__c;
		
		for(Sales_Credit__c sc : salesCredits)
		{
			if(sc.Override_Trigger_Logic__c) continue;
			targetKeys.add(sc.Opportunity_Contract_Signed_Year__c + sc.Opportunity_Contract_Signed_Month__c + sc.Sales_Rep__c + 'Rep');
			targetKeys.add(sc.Opportunity_Contract_Signed_Year__c + sc.Opportunity_Contract_Signed_Month__c + sc.Manager__c + 'Manager');
			targetKeys.add(sc.Opportunity_Contract_Signed_Year__c + sc.Opportunity_Contract_Signed_Month__c + sc.VP__c + 'VP');
			repIds.add(sc.Sales_Rep__c);
		}

		if(targetKeys.size() == 0) return;
	
		Sales_Target__c[] targets = [SELECT Id, Owner__c, Unique_Target__c FROM Sales_Target__c WHERE Unique_Target__c IN :targetKeys];
		//Map<Id, User> usersMap = new Map<Id, User>([SELECT Id, Profile.Name, UserName, UserRole.Name FROM User WHERE Id IN :repIds]);

		for(Sales_Target__c st : targets)
		{
			targetIdsByKey.put(st.Unique_Target__c, st.Id);
		}

		for(Sales_Credit__c sc : salesCredits)
		{
			/*String userRoleString = usersMap.containsKey(sc.Sales_Rep__c) && usersMap.get(sc.Sales_Rep__c).UserRole != null ? usersMap.get(sc.Sales_Rep__c).UserRole.Name : 'null';
			if(sc.Override_Trigger_Logic__c) continue;
			if(usersMap.containsKey(sc.Sales_Rep__c) && 
				!salesTargetRolesProfiles.contains(usersMap.get(sc.Sales_Rep__c).Profile.Name) &&
				!salesTargetRolesProfiles.contains(usersMap.get(sc.Sales_Rep__c).UserName) &&
				!salesTargetRolesProfiles.contains(userRoleString)) continue;*/

			if(sc.Sales_Rep__c != null && targetIdsByKey.containsKey(sc.Opportunity_Contract_Signed_Year__c + sc.Opportunity_Contract_Signed_Month__c + sc.Sales_Rep__c + 'Rep'))
			{
				sc.Sales_Rep_Target__c = targetIdsByKey.get(sc.Opportunity_Contract_Signed_Year__c + sc.Opportunity_Contract_Signed_Month__c + sc.Sales_Rep__c + 'Rep');
			}
			else if(sc.Sales_Rep__c != null)
			{
				Sales_Target__c repTarget = createNewTarget(sc.Sales_Rep__c, 'Rep', sc);
				if(newTargetsCreated.containsKey(sc.Opportunity_Contract_Signed_Year__c + sc.Opportunity_Contract_Signed_Month__c + sc.Sales_Rep__c + 'Rep'))
				{
					uow.registerRelationship(sc, Sales_Credit__c.Sales_Rep_Target__c, newTargetsCreated.get(sc.Opportunity_Contract_Signed_Year__c + sc.Opportunity_Contract_Signed_Month__c + sc.Sales_Rep__c + 'Rep'));
				}
				else
				{
					uow.registerNew(repTarget);
					uow.registerRelationship(sc, Sales_Credit__c.Sales_Rep_Target__c, repTarget);
					newTargetsCreated.put(sc.Opportunity_Contract_Signed_Year__c + sc.Opportunity_Contract_Signed_Month__c + sc.Sales_Rep__c + 'Rep', repTarget);
				}
			}

			if(sc.Manager__c != null && targetIdsByKey.containsKey(sc.Opportunity_Contract_Signed_Year__c + sc.Opportunity_Contract_Signed_Month__c + sc.Manager__c + 'Manager'))
			{
				sc.Manager_Target__c = targetIdsByKey.get(sc.Opportunity_Contract_Signed_Year__c + sc.Opportunity_Contract_Signed_Month__c + sc.Manager__c + 'Manager');
			}
			else if(sc.Manager__c != null)
			{
				Sales_Target__c managerTarget = createNewTarget(sc.Manager__c, 'Manager', sc);
				if(newTargetsCreated.containsKey(sc.Opportunity_Contract_Signed_Year__c + sc.Opportunity_Contract_Signed_Month__c + sc.Manager__c + 'Manager'))
				{
					uow.registerRelationship(sc, Sales_Credit__c.Manager_Target__c, newTargetsCreated.get(sc.Opportunity_Contract_Signed_Year__c + sc.Opportunity_Contract_Signed_Month__c + sc.Manager__c + 'Manager'));
				}
				else
				{
					uow.registerNew(managerTarget);
					uow.registerRelationship(sc, Sales_Credit__c.Manager_Target__c, managerTarget);
					newTargetsCreated.put(sc.Opportunity_Contract_Signed_Year__c + sc.Opportunity_Contract_Signed_Month__c + sc.Manager__c + 'Manager', managerTarget);
				}
			}

			if(sc.VP__c != null && targetIdsByKey.containsKey(sc.Opportunity_Contract_Signed_Year__c + sc.Opportunity_Contract_Signed_Month__c + sc.VP__c + 'VP'))
			{
				sc.VP_Target__c = targetIdsByKey.get(sc.Opportunity_Contract_Signed_Year__c + sc.Opportunity_Contract_Signed_Month__c + sc.VP__c + 'VP');
			}
			else if(sc.VP__c != null)
			{
				Sales_Target__c vpTarget = createNewTarget(sc.VP__c, 'VP', sc);
				if(newTargetsCreated.containsKey(sc.Opportunity_Contract_Signed_Year__c + sc.Opportunity_Contract_Signed_Month__c + sc.VP__c + 'VP'))
				{
					uow.registerRelationship(sc, Sales_Credit__c.VP_Target__c, newTargetsCreated.get(sc.Opportunity_Contract_Signed_Year__c + sc.Opportunity_Contract_Signed_Month__c + sc.VP__c + 'VP'));
				}
				else
				{
					uow.registerNew(vpTarget);
					uow.registerRelationship(sc, Sales_Credit__c.VP_Target__c, vpTarget);
					newTargetsCreated.put(sc.Opportunity_Contract_Signed_Year__c + sc.Opportunity_Contract_Signed_Month__c + sc.VP__c + 'VP', vpTarget);
				}
			}
		}

		uow.commitWork();
	}

	public static Sales_Target__c createNewTarget(Id ownerId, String targetType, Sales_Credit__c sc)
	{
		Sales_Target__c newTarget = new Sales_Target__c(OwnerId = ownerId,
			Owner__c = ownerId,
			Target_Date__c = sc.Opportunity_Contract_Signed_Date__c.toStartOfMonth(),
			Type__c = targetType,
			Unique_Target__c = sc.Opportunity_Contract_Signed_Year__c + sc.Opportunity_Contract_Signed_Month__c + ownerId + targetType);

		return newTarget;
	}

	public static void createBonusCommissionCredit(Sales_Credit__c[] salesCredits)
    {
    	Set<Id> salesTargetIds = new Set<Id>();
    	Bonus_Commission_Credit__c[] bccList = new List<Bonus_Commission_Credit__c>();
    	Map<Id, Bonus_Commission__c> bcToTargetMap = new Map<Id, Bonus_Commission__c>();

    	for(Sales_Credit__c sc : salesCredits)
    	{
    		salesTargetIds.add(sc.Sales_Rep_Target__c);
    	}

    	Bonus_Commission__c[] bcList = [SELECT Id, Sales_Target__c, OwnerId FROM Bonus_Commission__c WHERE Sales_Target__c IN :salesTargetIds];

    	for(Bonus_Commission__c bc : bcList)
    	{
    		bcToTargetMap.put(bc.Sales_Target__c, bc);
    	}

    	for(Sales_Credit__c sc : salesCredits)
    	{
    		if(sc.Sales_Rep_Target__c == null ||
    		 !bcToTargetMap.containsKey(sc.Sales_Rep_Target__c) ||
    		 bcToTargetMap.get(sc.Sales_Rep_Target__c) == null) continue;
    		
    		Bonus_Commission_Credit__c bcc = new Bonus_Commission_Credit__c(Sales_Credit__c = sc.Id,
    			Bonus_Commission__c = bcToTargetMap.get(sc.Sales_Rep_Target__c).Id,
    			OwnerId = bcToTargetMap.get(sc.Sales_Rep_Target__c).OwnerId);

    		bccList.add(bcc);
    	}

    	insert bccList;
    }
}