src.4/objects/Campaign_Influence__c.object
<CustomObject>
    <label>Campaign Influence</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Influence</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Campaign Influence</relationshipLabel>
        <relationshipName>Campaign_Influence</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Associated_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaign_Influence</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campaign_Add_Date__c</fullName>
        <label>Campaign Add Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Influence</relationshipLabel>
        <relationshipName>Campaign_Influence</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Campaign Influence</relationshipLabel>
        <relationshipName>Campaign_Influence</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_ROE_Task_Date__c</fullName>
        <formula>if( not(isblank(Opportunity__r.Last_ROE_Task_Date__c)), 
  Opportunity__r.Last_ROE_Task_Date__c, 
 if( not(isblank(Lead__r.Last_ROE_Task_Date__c)), 
  Lead__r.Last_ROE_Task_Date__c,
  Lead__r.SR_Date_Created__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last ROE Task Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Lead_Re_warmed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lead Re-warmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Campaign Influence</relationshipLabel>
        <relationshipName>Campaign_Influence</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Lead_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>New Lead Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Campaign Influence</relationshipLabel>
        <relationshipName>Campaign_Influence</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Orphaned_Date__c</fullName>
        <label>Orphaned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Orphaned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Orphaned</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src.1/objects/Lead.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>isGroup__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Box is checked by LastROETask trigger when Group Practice task is added</description>
        <label>isGroup</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_ROE_Task_Date__c</fullName>
        <label>Last ROE Task Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SR_Date_Created__c</fullName>
        <label>Date Created</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>isGroup__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isGroup</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_ROE_Task_Date__c</fullName>
        <label>Last ROE Task Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SR_Date_Created__c</fullName>
        <description>This is the date the Opportunity was actually created. If migrated from Sugar, this is the Sugar created date. If not, it matches the CreatedDate.</description>
        <label>Date Created</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

force-app/main/default/classes/OppCiDeDupe_Batch.cls
global class OppCiDeDupe_Batch implements Database.Batchable<sObject> {
	
	String query = 'SELECT Id FROM Opportunity';

	global Database.QueryLocator start(Database.BatchableContext BC) {
		
		return Database.getQueryLocator(query);
	}

	global void execute(Database.BatchableContext BC, List<Opportunity> scope) {

		Map<Id, SObject> mapInsertSObject = new Map<Id, SObject>();
      	Map<Id, SObject> mapUpdateSObject = new Map<Id, SObject>();
      	Map<Id, SObject> mapDeleteSObject = new Map<Id, SObject>();
      	Set<String> dupeCheck = new Set<String>();
      	String dupeString = '';

      	Opportunity[] thisList = [SELECT Id, Last_Roe_Task_Date__c, SR_Date_Created__c, isGroup__c, 
      	(SELECT Id, Campaign__c, Campaign__r.Name, New_Lead_Created__c, Lead_Re_Warmed__c, Associated_Rep__c, Account__c, 
		Lead__c, Contact__c, Opportunity__c, Orphaned__c, Orphaned_Date__c, Campaign_Add_Date__c 
		FROM Campaign_Influence__r ORDER BY Campaign_Add_Date__c ASC) FROM Opportunity WHERE Id IN :scope];

		for(Opportunity o : thisList) {

			if(o.Campaign_Influence__r.size() == 0) continue;

			dupeCheck.clear();
			dupeString = '';

			for(Campaign_Influence__c ci : o.Campaign_Influence__r) {

				if(ci.Campaign__r.Name == 'Other - : Existing Lead 9/16') {

					dupeString = String.valueOf(ci.Campaign__c) + 
					String.valueOf(ci.Opportunity__c);
				
				} else {

					dupeString = String.valueOf(ci.Campaign__c) + 
					String.valueOf(ci.New_Lead_Created__c) + 
					String.valueOf(ci.Lead_Re_warmed__c) + 
					String.valueOf(ci.Orphaned__c) + 
					String.valueOf(ci.Orphaned_Date__c) +
					String.valueOf(ci.Associated_Rep__c) + 
					String.valueOf(ci.Account__c) + 
					String.valueOf(ci.Lead__c) + 
					String.valueOf(ci.Contact__c) + 
					String.valueOf(ci.Opportunity__c);
				}
				

				if(!dupeCheck.contains(dupeString)) {
					
					dupeCheck.add(dupeString);

				} else {

					mapDeleteSObject.put(ci.Id, ci);
				}
			}
		}

		SRUtilities.runDml(mapInsertSObject, mapUpdateSObject, mapDeleteSObject, 'OppCiDeDupe_Batch');
	}
			
	global void finish(Database.BatchableContext BC) {
		
	}
}