src.4/objects/Campaign_Influence__c.object
<CustomObject>
    <label>Campaign Influence</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Influence</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Campaign Influence</relationshipLabel>
        <relationshipName>Campaign_Influence</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Campaign Influence</relationshipLabel>
        <relationshipName>Campaign_Influence</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.4/classes/ContactCIWithoutAccount_Batch.cls
global class ContactCIWithoutAccount_Batch implements Database.Batchable<sObject>, Schedulable 
{		
	global Database.QueryLocator start(Database.BatchableContext BC) 
	{	
		return CampaignInfluencesSelector.newInstance().queryLocatorContactCIWithoutAccount();
	}

	global void execute(Database.BatchableContext BC, List<Campaign_Influence__c> scope) 
	{
      	fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

		for(Campaign_Influence__c ci : scope) 
		{
			if(ci.Contact__c == null) continue;
			if(ci.Account__c != null) continue;
			if(ci.Contact__r.AccountId == null) continue;

			ci.Account__c = ci.Contact__r.AccountId;
			uow.registerDirty(ci);
		}

		uow.commitWork();
	}
			
	global void finish(Database.BatchableContext BC) 
	{	
		OrphanCI_Batch batch = new OrphanCI_Batch();
		Database.executebatch(batch);
	}

	global void execute(SchedulableContext sc) 
	{	
		ContactCIWithoutAccount_Batch batch = new ContactCIWithoutAccount_Batch();
		Database.executebatch(batch);
	}
}