src.4/objects/Case.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>FbD_CM__Merge_To_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Merge To Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HG_Conditions__c</fullName>
        <label>HG Conditions</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>HG_Procedures__c</fullName>
        <label>HG Procedures</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>HG_Specialties__c</fullName>
        <label>HG Specialties</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Provider__c/Provider__c.object-meta.xml
<CustomObject>
    <description>Used to store information about individual Providers within a Practice.  The Provider information is used for Healthgrades Premium members.</description>
    <label>Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Provider__c/fields/Conditions__c.field-meta.xml
<CustomField>
    <fullName>Conditions__c</fullName>
    <description>List of Conditions from all the condition fields</description>
    <label>Conditions</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Procedures__c.field-meta.xml
<CustomField>
    <fullName>Procedures__c</fullName>
    <description>List of Procedures gathered from all the procedure fields</description>
    <label>Procedures</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Specialties__c.field-meta.xml
<CustomField>
    <fullName>Specialties__c</fullName>
    <description>List of Specialties combined from all the different specialty fields</description>
    <label>Specialties</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src.3/classes/Providers.cls
public class Providers extends fflib_SObjectDomain 
{
	public Providers(Provider__c[] providers) 
	{
		super(providers);
	}

	public class Constructor implements fflib_SObjectDomain.IConstructable
	{
		public fflib_SObjectDomain construct(List<SObject> sObjectList)
		{
			return new Providers(sObjectList);
		}
	}

	public override void onBeforeUpdate(Map<Id, SObject> existingRecords)
	{
		fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
		Map<Id, Provider__c> providersMap = new Map<Id, Provider__c>(ProvidersSelector.newInstance().selectByIdWithCases(existingRecords.keySet()));

		for(Provider__c p : (Provider__c[]) Records)
		{
			p.Specialties__c = ProvidersService.getSpecialties(p);
			p.Conditions__c = ProvidersService.getConditions(p);
			p.Procedures__c = ProvidersService.getProcedures(p);

			for(Case c : providersMap.get(p.Id).Cases__r)
			{
				c.HG_Specialties__c = p.Specialties__c;
				c.HG_Conditions__c = p.Conditions__c;
				c.HG_Procedures__c = p.Procedures__c;
			}

			uow.registerDirty(providersMap.get(p.Id).Cases__r);
		}

		uow.commitWork();
	}
}