src.4/objects/Case.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/Credit_Memo_Amount__c.field-meta.xml
<CustomField>
    <fullName>Credit_Memo_Amount__c</fullName>
    <label>Credit Memo Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CSCreditMemoLimits__c/CSCreditMemoLimits__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Amount that CS is allowed to submit as credit memo&#39;s each month.</description>
    <label>CS Credit Memo Limit</label>
</CustomObject>

force-app/main/default/objects/CSCreditMemoLimits__c/fields/Limit__c.field-meta.xml
<CustomField>
    <fullName>Limit__c</fullName>
    <label>Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CSCreditMemo.cls
/**
 * Created by abishop on 11/12/18.
 */

public with sharing class CSCreditMemo {
    public class OutputData
    {
        @InvocableVariable(label='Limit Remaining')
        public Double limitRemaining;

    }

    @InvocableMethod
    public static List<OutputData> getCreditLimit() {
        Id UserId = UserInfo.getUserId();
        CSCreditMemoLimits__c userLimit = CSCreditMemoLimits__c.getInstance(UserId);
        Date cmDate = Date.today().toStartOfMonth();
        System.debug(userLimit);
        AggregateResult[] currentCreditMemoLimit = [SELECT SUM(Credit_Memo_Amount__c) FROM Case WHERE CreatedDate >= :cmDate AND CreatedById = :UserId GROUP BY CreatedById];
        List<OutputData> results = new List<OutputData>();
        system.debug(currentCreditMemoLimit);
        If (currentCreditMemoLimit.isEmpty() ||
                currentCreditMemoLimit[0].get('expr0') == null)
        {
            OutputData output = new OutputData();
            output.limitRemaining = (Double) userLimit.Limit__c;
            System.debug('Output Limit: ' + output);
            results.add(output);
            return results;
        }
        OutputData output = new OutputData();
        System.debug(currentCreditMemoLimit);
        output.limitRemaining = userLimit.Limit__c - (Double) currentCreditMemoLimit[0].get('expr0');
        results.add(output);
        return results;
}


}