src.4/objects/Case.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/Distribution_Group__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distribution Group</label>
    <referenceTo>Distribution_Group__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src.2/objects/Distribution_Group__c.object
<CustomObject>
    <label>Distribution Group</label>
    <nameField>
        <label>Distribution Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Distribution_Group__c/fields/Distribution_Type__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Type__c</fullName>
    <label>Distribution Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Linear</fullName>
                <default>true</default>
                <label>Linear</label>
            </value>
            <value>
                <fullName>Load Balanced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Distribution_Group__c/fields/Field_to_Distribute__c.field-meta.xml
<CustomField>
    <fullName>Field_to_Distribute__c</fullName>
    <label>Field to Distribute</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Distribution_Group__c/fields/ParentObject__c.field-meta.xml
<CustomField>
    <fullName>ParentObject__c</fullName>
    <label>Parent Object</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Distribution_Group__c/fields/Relationship_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Criteria__c</fullName>
    <inlineHelpText>SOQL WHERE clause applied when querying Object records, e.g. Amount &gt; 200</inlineHelpText>
    <label>Relationship Criteria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src.3/objects/Distribution_Group_History__c.object
<CustomObject>
    <label>Distribution Group History</label>
    <nameField>
        <label>Distribution Group History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Group Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Distribution_Group__c</fullName>
        <label>Distribution Group</label>
        <referenceTo>Distribution_Group__c</referenceTo>
        <relationshipLabel>Distribution Group Histories</relationshipLabel>
        <relationshipName>Distribution_Group_Histories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Distribution_Group_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.1/objects/Distribution_Group_Member__c.object
<CustomObject>
    <label>Distribution Group Member</label>
    <nameField>
        <displayFormat>DGM-{000}</displayFormat>
        <label>Distribution Group Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Distribution Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Available__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Distribution_Group__c</fullName>
        <label>Distribution Group</label>
        <referenceTo>Distribution_Group__c</referenceTo>
        <relationshipLabel>Distribution Group Members</relationshipLabel>
        <relationshipName>Distribution_Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Next_Up__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Next Up</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Distribution_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Distribution_Group_Member__c/fields/Rep_Limit__c.field-meta.xml
<CustomField>
    <fullName>Rep_Limit__c</fullName>
    <label>Rep Limit</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Distribution_Group_Member__c/fields/Total_Open__c.field-meta.xml
<CustomField>
    <fullName>Total_Open__c</fullName>
    <label>Total Open</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src.2/classes/DistributionGroupsService_Test.cls
/**
 * Created by mschetselaar on 10/26/2018.
 */

@IsTest
private class DistributionGroupsService_Test
{
    @IsTest
    static void test_getNextUserId()
    {
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        
        Distribution_Group__c distGroup = (Distribution_Group__c)TestUtilities2.newDistributionGroup()
                .setField(Distribution_Group__c.Name, 'Testing')
                .toSObject();
        
        sfab_FabricatedSObject uFab1 = TestUtilities2.newUser()
                .setField(User.FirstName, 'Test 1')
                .setField(User.LastName, 'Last 1');
        User user1 = (User)uFab1.toSObject();
        sfab_FabricatedSObject uFab2 = TestUtilities2.newUser()
                .setField(User.FirstName, 'Test 2')
                .setField(User.LastName, 'Last 2');
        User user2 = (User) uFab2.toSObject();
        
        sfab_FabricatedSObject mFab1 = TestUtilities2.newDistributionGroupMember()
                .setField(Distribution_Group_Member__c.Distribution_Group__c, distGroup.Id)
                .setParent('User__r', uFab1)
                .setField(Distribution_Group_Member__c.User__c,user1.Id)
                .setField(Distribution_Group_Member__c.Available__c, true)
                .setField(Distribution_Group_Member__c.Next_Up__c, true);
        Distribution_Group_Member__c member1 = (Distribution_Group_Member__c) mFab1.toSObject();
        
        sfab_FabricatedSObject mFab2 = TestUtilities2.newDistributionGroupMember()
                .setField(Distribution_Group_Member__c.Distribution_Group__c, distGroup.Id)
                .setField(Distribution_Group_Member__c.User__c, user2.Id)
                .setField(Distribution_Group_Member__c.Available__c, true)
                .setField(Distribution_Group_Member__c.Next_Up__c, false);
        Distribution_Group_Member__c member2 = (Distribution_Group_Member__c)mFab2.toSObject();
        
        List<Distribution_Group_Member__c> members = new List<Distribution_Group_Member__c>();
        members.add(member2);
        members.add(member1);
        
        Test.startTest();
        User user = DistributionGroupsService.getNextUserId(members,distGroup.Id,uow);
        Test.stopTest();
        
        System.assertEquals(user1.Id,user.Id);
        System.assertEquals('Assigned to the next user in the Distribution Group', user.AboutMe);
    }
    //
    @IsTest
    static void test_getNextUserIdNonLoadBalanced()
    {
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        
        Distribution_Group__c distGroup = (Distribution_Group__c)TestUtilities2.newDistributionGroup()
                .setField(Distribution_Group__c.Name, 'Testing')
                .setField(Distribution_Group__c.Distribution_Type__c, 'Linear')
                .toSObject();
        
        sfab_FabricatedSObject uFab1 = TestUtilities2.newUser()
                .setField(User.FirstName, 'Test 1')
                .setField(User.LastName, 'Last 1');
        User user1 = (User)uFab1.toSObject();
        sfab_FabricatedSObject uFab2 = TestUtilities2.newUser()
                .setField(User.FirstName, 'Test 2')
                .setField(User.LastName, 'Last 2');
        User user2 = (User) uFab2.toSObject();
        
        sfab_FabricatedSObject mFab1 = TestUtilities2.newDistributionGroupMember()
                .setField(Distribution_Group_Member__c.Distribution_Group__c, distGroup.Id)
                .setParent('User__r', uFab1)
                .setField(Distribution_Group_Member__c.User__c,user1.Id)
                .setField(Distribution_Group_Member__c.Available__c, true)
                .setField(Distribution_Group_Member__c.Next_Up__c, true);
        Distribution_Group_Member__c member1 = (Distribution_Group_Member__c) mFab1.toSObject();
        
        sfab_FabricatedSObject mFab2 = TestUtilities2.newDistributionGroupMember()
                .setField(Distribution_Group_Member__c.Distribution_Group__c, distGroup.Id)
                .setField(Distribution_Group_Member__c.User__c, user2.Id)
                .setField(Distribution_Group_Member__c.Available__c, true)
                .setField(Distribution_Group_Member__c.Next_Up__c, false);
        Distribution_Group_Member__c member2 = (Distribution_Group_Member__c)mFab2.toSObject();
        
        List<Distribution_Group_Member__c> members = new List<Distribution_Group_Member__c>();
        members.add(member1);
        members.add(member2);
        
        List<Distribution_Group__c> distGroups = (List<Distribution_Group__c>) fflib_ApexMocksUtils.makeRelationship(List<Distribution_Group__c>.class, new List<Distribution_Group__c>{distGroup},Distribution_Group_Member__c.Distribution_Group__c, new List<List<Distribution_Group_Member__c>> {members});
        
        Test.startTest();
        User user = DistributionGroupsService.getNextUserId(distGroups[0],uow);
        Test.stopTest();
        
        System.assertEquals(user1.Id,user.Id);
        System.assertEquals('Assigned to the next user in the Distribution Group', user.AboutMe);
    }
    
    @IsTest
    public static void test_getNextUserId_LoadBalanced()
    {
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        
        Distribution_Group__c distGroup = (Distribution_Group__c)TestUtilities2.newDistributionGroup()
                .setField(Distribution_Group__c.Name, 'Testing')
                .setField(Distribution_Group__c.Distribution_Type__c, 'Load Balanced')
                .setField(Distribution_Group__c.Relationship_Criteria__c, 'IsClosed = false')
                .setField(Distribution_Group__c.ParentObject__c, 'Case')
                .setField(Distribution_Group__c.Field_to_Distribute__c, 'OwnerId')
                .toSObject();
        
        sfab_FabricatedSObject uFab1 = TestUtilities2.newUser()
                .setField(User.FirstName, 'Test 1')
                .setField(User.LastName, 'Last 1');
        User user1 = (User)uFab1.toSObject();
        sfab_FabricatedSObject uFab2 = TestUtilities2.newUser()
                .setField(User.FirstName, 'Test 2')
                .setField(User.LastName, 'Last 2');
        User user2 = (User) uFab2.toSObject();
        
        sfab_FabricatedSObject cFab = TestUtilities2.newCases()
                .setField(Case.OwnerId,user1.Id);
        Case case1 = (Case) cFab.toSObject();
        
        sfab_FabricatedSObject mFab1 = TestUtilities2.newDistributionGroupMember()
                .setField(Distribution_Group_Member__c.Distribution_Group__c, distGroup.Id)
                .setParent('User__r', uFab1)
                .setField(Distribution_Group_Member__c.User__c,user1.Id)
                .setField(Distribution_Group_Member__c.Rep_Limit__c, 5)
                .setField(Distribution_Group_Member__c.Available__c, true)
                .setField(Distribution_Group_Member__c.Next_Up__c, true);
        Distribution_Group_Member__c member1 = (Distribution_Group_Member__c) mFab1.toSObject();
        
        sfab_FabricatedSObject mFab2 = TestUtilities2.newDistributionGroupMember()
                .setField(Distribution_Group_Member__c.Distribution_Group__c, distGroup.Id)
                .setField(Distribution_Group_Member__c.User__c, user2.Id)
                .setField(Distribution_Group_Member__c.Rep_Limit__c, 5)
                .setField(Distribution_Group_Member__c.Available__c, true)
                .setField(Distribution_Group_Member__c.Next_Up__c, false);
        Distribution_Group_Member__c member2 = (Distribution_Group_Member__c)mFab2.toSObject();
        
        List<Distribution_Group_Member__c> members = new List<Distribution_Group_Member__c>();
        members.add(member2);
        members.add(member1);
        
        List<Distribution_Group__c> distGroups = (List<Distribution_Group__c>) fflib_ApexMocksUtils.makeRelationship(List<Distribution_Group__c>.class, new List<Distribution_Group__c>{distGroup},Distribution_Group_Member__c.Distribution_Group__c, new List<List<Distribution_Group_Member__c>> {members});
        
        Test.startTest();
        User user = DistributionGroupsService.getNextUserId(distGroups[0],uow);
        Test.stopTest();
        
        System.assertEquals(user2.Id,user.Id);
        System.assertEquals(1, uow.m_dirtyMapByType.get('Distribution_Group_Member__c').get(member2.Id).get('Total_Open__c'));
        System.assertEquals(2, uow.m_dirtyMapByType.get('Distribution_Group_Member__c').size());
    
    }
    
    @IsTest
    public static void test_createHistory()
    {
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        
        Distribution_Group__c distGroup = (Distribution_Group__c) TestUtilities2.newDistributionGroup()
                .setField(Distribution_Group__c.Name, 'Testing')
                .setField(Distribution_Group__c.Distribution_Type__c, 'Load Balanced')
                .setField(Distribution_Group__c.Relationship_Criteria__c, 'IsClosed = false')
                .setField(Distribution_Group__c.ParentObject__c, 'Case')
                .setField(Distribution_Group__c.Field_to_Distribute__c, 'OwnerId')
                .toSObject();
        
        sfab_FabricatedSObject uFab1 = TestUtilities2.newUser()
                .setField(User.FirstName, 'Test 1')
                .setField(User.LastName, 'Last 1');
        User user1 = (User) uFab1.toSObject();
        sfab_FabricatedSObject uFab2 = TestUtilities2.newUser()
                .setField(User.FirstName, 'Test 2')
                .setField(User.LastName, 'Last 2');
        User user2 = (User) uFab2.toSObject();
        
        sfab_FabricatedSObject cFab = TestUtilities2.newCases()
                .setField(Case.OwnerId, user1.Id);
        Case case1 = (Case) cFab.toSObject();
        
        sfab_FabricatedSObject mFab1 = TestUtilities2.newDistributionGroupMember()
                .setField(Distribution_Group_Member__c.Distribution_Group__c, distGroup.Id)
                .setParent('User__r', uFab1)
                .setField(Distribution_Group_Member__c.User__c, user1.Id)
                .setField(Distribution_Group_Member__c.Rep_Limit__c, 5)
                .setField(Distribution_Group_Member__c.Available__c, true)
                .setField(Distribution_Group_Member__c.Next_Up__c, true);
        Distribution_Group_Member__c member1 = (Distribution_Group_Member__c) mFab1.toSObject();
        
        sfab_FabricatedSObject mFab2 = TestUtilities2.newDistributionGroupMember()
                .setField(Distribution_Group_Member__c.Distribution_Group__c, distGroup.Id)
                .setField(Distribution_Group_Member__c.User__c, user2.Id)
                .setField(Distribution_Group_Member__c.Rep_Limit__c, 5)
                .setField(Distribution_Group_Member__c.Available__c, true)
                .setField(Distribution_Group_Member__c.Next_Up__c, false);
        Distribution_Group_Member__c member2 = (Distribution_Group_Member__c) mFab2.toSObject();
        
        List<Distribution_Group_Member__c> members = new List<Distribution_Group_Member__c>();
        members.add(member2);
        members.add(member1);
        
        List<Distribution_Group__c> distGroups = (List<Distribution_Group__c>) fflib_ApexMocksUtils.makeRelationship(List<Distribution_Group__c>.class, new List<Distribution_Group__c>
        {
                distGroup
        }, Distribution_Group_Member__c.Distribution_Group__c, new List<List<Distribution_Group_Member__c>>
        {
                members
        });
        
        Test.startTest();
        DistributionGroupsService.createHistory(distGroups[0], user1, case1, uow);
        Test.stopTest();
        
        System.assertEquals(1,uow.m_newListByType.get('Distribution_Group_History__c').size());
    }
    
    @IsTest
    public static void test_updateOpenCount()
    {
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        
        Distribution_Group__c distGroup = (Distribution_Group__c) TestUtilities2.newDistributionGroup()
                .setField(Distribution_Group__c.Name, 'Testing')
                .setField(Distribution_Group__c.Distribution_Type__c, 'Load Balanced')
                .setField(Distribution_Group__c.Relationship_Criteria__c, 'IsClosed = false')
                .setField(Distribution_Group__c.ParentObject__c, 'Case')
                .setField(Distribution_Group__c.Field_to_Distribute__c, 'OwnerId')
                .toSObject();
        
        sfab_FabricatedSObject uFab1 = TestUtilities2.newUser()
                .setField(User.FirstName, 'Test 1')
                .setField(User.LastName, 'Last 1');
        User user1 = (User) uFab1.toSObject();
        sfab_FabricatedSObject uFab2 = TestUtilities2.newUser()
                .setField(User.FirstName, 'Test 2')
                .setField(User.LastName, 'Last 2');
        User user2 = (User) uFab2.toSObject();
        
        sfab_FabricatedSObject cFab = TestUtilities2.newCases()
                .setField(Case.OwnerId, user1.Id);
        Case case1 = (Case) cFab.toSObject();
        
        sfab_FabricatedSObject mFab1 = TestUtilities2.newDistributionGroupMember()
                .setField(Distribution_Group_Member__c.Distribution_Group__c, distGroup.Id)
                .setParent('User__r', uFab1)
                .setField(Distribution_Group_Member__c.User__c, user1.Id)
                .setField(Distribution_Group_Member__c.Rep_Limit__c, 5)
                .setField(Distribution_Group_Member__c.Available__c, true)
                .setField(Distribution_Group_Member__c.Next_Up__c, true);
        Distribution_Group_Member__c member1 = (Distribution_Group_Member__c) mFab1.toSObject();
        
        sfab_FabricatedSObject mFab2 = TestUtilities2.newDistributionGroupMember()
                .setField(Distribution_Group_Member__c.Distribution_Group__c, distGroup.Id)
                .setField(Distribution_Group_Member__c.User__c, user2.Id)
                .setField(Distribution_Group_Member__c.Rep_Limit__c, 5)
                .setField(Distribution_Group_Member__c.Available__c, true)
                .setField(Distribution_Group_Member__c.Next_Up__c, false);
        Distribution_Group_Member__c member2 = (Distribution_Group_Member__c) mFab2.toSObject();
        
        List<Distribution_Group_Member__c> members = new List<Distribution_Group_Member__c>();
        members.add(member2);
        members.add(member1);
        
        List<Distribution_Group__c> distGroups = (List<Distribution_Group__c>) fflib_ApexMocksUtils.makeRelationship(List<Distribution_Group__c>.class, new List<Distribution_Group__c>
        {
                distGroup
        }, Distribution_Group_Member__c.Distribution_Group__c, new List<List<Distribution_Group_Member__c>>
        {
                members
        });
        
        Test.startTest();
        DistributionGroupsService.updateOpenCount(user1.Id, distGroups[0], uow);
        Test.stopTest();
        
        System.assertEquals(0,uow.m_dirtyMapByType.get('Distribution_Group_Member__c').get(member2.Id).get('Total_Open__c'));
        System.assertEquals(1,uow.m_dirtyMapByType.get('Distribution_Group_Member__c').get(member1.Id).get('Total_Open__c'));
        System.assertEquals(2,uow.m_dirtyMapByType.get('Distribution_Group_Member__c').size());
    }
}