src.4/objects/Case.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/Distribution_Group__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distribution Group</label>
    <referenceTo>Distribution_Group__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src.2/objects/Distribution_Group__c.object
<CustomObject>
    <label>Distribution Group</label>
    <nameField>
        <label>Distribution Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Open_Opportunity_Setting__c</fullName>
        <label>Open Opportunity Setting</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Notify Owner</fullName>
                    <default>true</default>
                    <label>Notify Owner</label>
                </value>
                <value>
                    <fullName>Reassign Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/Distribution_Group__c/fields/Distribution_Type__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Type__c</fullName>
    <label>Distribution Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Linear</fullName>
                <default>true</default>
                <label>Linear</label>
            </value>
            <value>
                <fullName>Load Balanced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Distribution_Group__c/fields/Field_to_Distribute__c.field-meta.xml
<CustomField>
    <fullName>Field_to_Distribute__c</fullName>
    <label>Field to Distribute</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Distribution_Group__c/fields/ParentObject__c.field-meta.xml
<CustomField>
    <fullName>ParentObject__c</fullName>
    <label>Parent Object</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Distribution_Group__c/fields/Relationship_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Criteria__c</fullName>
    <inlineHelpText>SOQL WHERE clause applied when querying Object records, e.g. Amount &gt; 200</inlineHelpText>
    <label>Relationship Criteria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src.3/objects/Distribution_Group_History__c.object
<CustomObject>
    <label>Distribution Group History</label>
    <nameField>
        <label>Distribution Group History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Group Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Distribution_Group__c</fullName>
        <label>Distribution Group</label>
        <referenceTo>Distribution_Group__c</referenceTo>
        <relationshipLabel>Distribution Group Histories</relationshipLabel>
        <relationshipName>Distribution_Group_Histories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Distribution_Group_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Distribution_Group_History__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Distribution Group Histories</relationshipLabel>
    <relationshipName>Distribution_Group_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

src.1/objects/Distribution_Group_Member__c.object
<CustomObject>
    <label>Distribution Group Member</label>
    <nameField>
        <displayFormat>DGM-{000}</displayFormat>
        <label>Distribution Group Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Distribution Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Available__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Distribution_Group__c</fullName>
        <label>Distribution Group</label>
        <referenceTo>Distribution_Group__c</referenceTo>
        <relationshipLabel>Distribution Group Members</relationshipLabel>
        <relationshipName>Distribution_Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Next_Up__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Next Up</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Distribution_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Distribution_Group_Member__c/fields/Rep_Limit__c.field-meta.xml
<CustomField>
    <fullName>Rep_Limit__c</fullName>
    <label>Rep Limit</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Distribution_Group_Member__c/fields/Total_Open__c.field-meta.xml
<CustomField>
    <fullName>Total_Open__c</fullName>
    <label>Total Open</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src.3/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>AtPipelineLimit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set via Apex. Used to validate in Distribution Group</description>
        <label>AtPipelineLimit</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src.2/classes/DistributionGroupsService.cls
public class DistributionGroupsService
{
	public static Map<Id, RoundRobin[]> groupToMembers;
	
	public static User getNextUserId(Distribution_Group_Member__c[] distGroupMembers, Id selectedDistGroup, fflib_SObjectUnitOfWork uow)
	{
		User results;
		Boolean beginAgain = false;
		
		for(Distribution_Group_Member__c distGroupMember : distGroupMembers)
		{
			if(distGroupMember.Next_Up__c && selectedDistGroup == distGroupMember.Distribution_Group__c)
			{
				results = new User(Id = distGroupMember.User__c,
						FirstName = distGroupMember.User__r.FirstName,
						LastName = distGroupMember.User__r.LastName,
						AboutMe = 'Assigned to the next user in the Distribution Group');
				selectedDistGroup = null;
				distGroupMember.Next_Up__c = false;
				uow.registerDirty(distGroupMember);
				beginAgain = true;
			}
			else if(selectedDistGroup != distGroupMember.Distribution_Group__c &&
					!distGroupMember.User__r.AtPipelineLimit__c &&
					!distGroupMember.Next_Up__c)
			{
				distGroupMember.Next_Up__c = true;
				beginAgain = false;
				uow.registerDirty(distGroupMember);
				break;
			}
		}
		if(beginAgain && !distGroupMembers.isEmpty())
		{
			for(Distribution_Group_Member__c distGroupMember : distGroupMembers)
			{
				if(selectedDistGroup != distGroupMember.Distribution_Group__c &&
						!distGroupMember.User__r.AtPipelineLimit__c &&
						!distGroupMember.Next_Up__c)
				{
					distGroupMember.Next_Up__c = true;
					beginAgain = false;
					uow.registerDirty(distGroupMember);
					break;
				}
			}
		}
		return results;
	}
	
	//Load Balanced
	public static User getNextUserId(Distribution_Group__c distGroup, fflib_SObjectUnitOfWork uow)
	{
		if(distGroup.Distribution_Type__c != 'Load Balanced')
		{
			Distribution_Group_Member__c[] distGroupMembers = distGroup.Distribution_Group_Members__r;
			User results = getNextUserId(distGroupMembers, distGroup.Id, uow);
			return results;
		}
		
		if(groupToMembers == null) groupToMembers = new Map<Id, RoundRobin[]>();
		
		if (!groupToMembers.containsKey(distGroup.Id)) groupToMembers.put(distGroup.Id, getRoundRobins(distGroup.Distribution_Group_Members__r,distGroup));
		
		groupToMembers.get(distGroup.Id).sort();
		
		User results = new User(Id = groupToMembers.get(distGroup.Id)[0].userId,
				AboutMe = 'Open Objects: ' + groupToMembers.get(distGroup.Id)[0].openObjects + ', Limit: ' + groupToMembers.get(distGroup.Id)[0].objectLimit + ', Load: ' + groupToMembers.get(distGroup.Id)[0].load);
		
		groupToMembers.get(distGroup.Id)[0].openObjects += 1;
		groupToMembers.get(distGroup.Id)[0].load = (groupToMembers.get(distGroup.Id)[0].openObjects / groupToMembers.get(distGroup.Id)[0].objectLimit) * 100;
		
		updateMembers(groupToMembers, uow);
		
		return results;
	}
	
	public static void resetNextUserAtLimit(fflib_SObjectUnitOfWork uow)
	{
		Distribution_Group__c[] distGroups = ([SELECT Id, Name, Open_Opportunity_Setting__c,
		(SELECT Id, Name, User__c, User__r.Name, User__r.FirstName, User__r.LastName,
				Available__c, Next_Up__c, Distribution_Group__c, User__r.AtPipelineLimit__c
		FROM Distribution_Group_Members__r
		WHERE Available__c = true
		AND User__r.IsActive = true
		ORDER BY User__r.LastName ASC)
		FROM Distribution_Group__c WHERE Id IN
		(SELECT Distribution_Group__c
		FROM Distribution_Group_Member__c
		WHERE User__r.AtPipelineLimit__c = true
		AND Next_Up__c = true)]);
		
		for(Distribution_Group__c distGroup : distGroups)
		{
			DistributionGroupsService.getNextUserId(distGroup.Distribution_Group_Members__r, distGroup.Id, uow);
		}
	}
	
	public static RoundRobin[] getRoundRobins(Distribution_Group_Member__c[] members, Distribution_Group__c distGroup)
	{
		Set<Id> ids = new Set<Id>();
		for(Distribution_Group_Member__c gm : members)
		{
			ids.add(gm.User__c);
		}
		String parentObject = distGroup.ParentObject__c;
		String fieldToDistribute = distGroup.Field_to_Distribute__c == null ? 'OwnerId' : distGroup.Field_to_Distribute__c;
		String whereClause = distGroup.Relationship_Criteria__c == null ? 'WHERE ' + fieldToDistribute + ' IN :ids' :
				'WHERE ' + distGroup.Relationship_Criteria__c + ' AND ' + fieldToDistribute + ' IN :ids';
		String queryString = 'SELECT ' + fieldToDistribute + ', count(Id) open FROM ' + parentObject + ' ' + whereClause + ' GROUP BY ' + fieldToDistribute ;
		System.debug('QueryString: ' + queryString);
		List<AggregateResult> objectList = Database.query(queryString);
		Map<Id,Integer> repToCount = new Map<Id,Integer>();
		for( AggregateResult ar : objectList)
		{
			repToCount.put((Id)ar.get(fieldToDistribute), (Integer)ar.get('open'));
		}
		
		RoundRobin[] roundRobinList = new List<RoundRobin>();
		for(Distribution_Group_Member__c member : members)
		{
			roundRobinList.add(new RoundRobin(member,repToCount.containsKey(member.User__c) ? repToCount.get(member.User__c) : 0));
		}
		
		return roundRobinList;
	}
	
	public static void updateMembers(Map<Id,List<RoundRobin>> groupToMembers, fflib_SObjectUnitOfWork uow)
	{
		Distribution_Group_Member__c[] allMembers = new List<Distribution_Group_Member__c>();
		
		for(List<RoundRobin> roundRobins : groupToMembers.values())
		{
			for(RoundRobin r : roundRobins)
			{
				Distribution_Group_Member__c member = new Distribution_Group_Member__c();
				member.Id = r.groupMember.Id;
				member.Total_Open__c = r.openObjects;
				allMembers.add(member);
			}
		}
		
		uow.registerDirty(allMembers);
	}
	
	public static void updateOpenCount(Id userID, Distribution_Group__c distGroup, fflib_SObjectUnitOfWork uow)
	{
		if(groupToMembers == null) groupToMembers = new Map<Id, RoundRobin[]>();
		
		if (!groupToMembers.containsKey(distGroup.Id)) groupToMembers.put(distGroup.Id, getRoundRobins(distGroup.Distribution_Group_Members__r,distGroup));
		
		for(RoundRobin member : groupToMembers.get(distGroup.Id))
		{
			if(member.userId == userId)
			{
				member.openObjects += 1;
				member.load = (member.openObjects / member.objectLimit) * 100;
				updateMembers(groupToMembers, uow);
				return;
			}
		}
		
		updateMembers(groupToMembers, uow);
	}
	
	public static void createHistory(Distribution_Group__c distGroup, User user, Case c, fflib_SObjectUnitOfWork uow)
	{
		Distribution_Group_History__c history = new Distribution_Group_History__c(Name = distGroup.Name + String.valueOf(Datetime.now()),
				Description__c = user.AboutMe,
				Distribution_Group__c = distGroup.Id,
				User__c = user.Id);
		uow.registerNew(history);
		uow.registerRelationship(history,Schema.Distribution_Group_History__c.Case__c,c);
	}
	
	
	
	
	public class RoundRobin implements Comparable
	{
		public RoundRobin(Distribution_Group_Member__c groupMember, Integer open)
		{
			this.groupMember = groupMember;
			this.openObjects = open;
			this.objectLimit = groupMember.Rep_Limit__c;
			this.load = (open / groupMember.Rep_Limit__c) * 100;
			this.userId = groupMember.User__c;
		}
		
		public Integer compareTo(Object compareTo)
		{
			return Integer.valueOf(load - ((RoundRobin) compareTo).load);
		}
		
		public Distribution_Group_Member__c groupMember;
		public Decimal openObjects;
		public Decimal objectLimit;
		public Decimal load;
		public Id userId;
	}
}