src.4/objects/Case.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>Healthgrades_Status__c</fullName>
        <description>Set on Activation cases for customers who signup with Healthgrades before their SR Activation case has closed.</description>
        <label>Healthgrades Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                    <default>true</default>
                    <label>Not Applicable</label>
                </value>
                <value>
                    <fullName>Setup Required</fullName>
                </value>
                <value>
                    <fullName>Setup Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SR Platform</fullName>
                </value>
                <value>
                    <fullName>SR Sync</fullName>
                </value>
                <value>
                    <fullName>PatientReach</fullName>
                </value>
                <value>
                    <fullName>One Desk</fullName>
                </value>
                <value>
                    <fullName>Simpletrac</fullName>
                </value>
                <value>
                    <fullName>SR Enterprise</fullName>
                </value>
                <value>
                    <fullName>Healthgrades</fullName>
                </value>
                <value>
                    <fullName>Limelight</fullName>
                </value>
                <value>
                    <fullName>SR Conversations</fullName>
                </value>
                <value>
                    <fullName>SR Smart Reviews</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Activation</fullName>
        <active>true</active>
        <businessProcess>Activation</businessProcess>
        <description>This is used to track and document the activation process of an account</description>
        <label>Activation</label>
    </recordTypes>
</CustomObject>

src.3/classes/CaseUtilities.cls
public with sharing class CaseUtilities {

	public static void validateHealthgradesStatusBeforeClose(Case[] updatedCases) {

		Set<Id> acctIds = new Set<Id>();
		Map<Id, Case> mapHGCases = new Map<Id, Case>();

		for(Case c : updatedCases) {

			acctIds.add(c.AccountId);
		}

		Case[] listHGCases = [SELECT 
		AccountId, 
		Id, 
		Product__c, 
		Status, 
		OwnerId 
		FROM Case 
		WHERE Status != 'Closed' 
		AND Product__c = 'Healthgrades' 
		AND AccountId IN : acctIds];
		
		for(Case c : listHGCases) {
			
			mapHGCases.put(c.AccountId, c);
		}

		for(Case c : updatedCases) {

			if(c.RecordTypeId == SRUtilities.getRecordTypeMap('Case').get('Activation').getRecordTypeId() && 
				c.Healthgrades_Status__c != 'Setup Required' && 
				mapHGCases.containsKey(c.AccountId)) {

				c.Healthgrades_Status__c.addError(Label.Error_Open_Healthgrades_Case);
			}
		}
	}
}