src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>HG_Monthly_Revenue__c</fullName>
        <label>HG Monthly Revenue</label>
        <summarizedField>OpportunityLineItem.HG_Monthly_Revenue__c</summarizedField>
        <summaryFilterItems>
            <field>OpportunityLineItem.Is_Monthly__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>LL_Monthly_Revenue__c</fullName>
        <label>LL Monthly Revenue</label>
        <summarizedField>OpportunityLineItem.LL_Monthly_Revenue__c</summarizedField>
        <summaryFilterItems>
            <field>OpportunityLineItem.Is_Monthly__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the related Provider record</description>
        <inlineHelpText>Link to the related Provider record</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Renewal_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Determines the system behaviour at the time of renewing the subscription.</inlineHelpText>
        <label>Renewal Rule</label>
        <referenceTo>RecurSoft__Renewal_Rule__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>RecurSoft_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SRC_Monthly_Revenue__c</fullName>
        <description>Rollup of the SRC Monthly Revenue field on the Opp Products.  This will rollup to the Sales Credit and Sales Targets</description>
        <label>SRC Monthly Revenue</label>
        <summarizedField>OpportunityLineItem.SRC_Monthly_Revenue__c</summarizedField>
        <summaryFilterItems>
            <field>OpportunityLineItem.Is_Monthly__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>SRSR_Monthly_Revenue__c</fullName>
        <description>This will rollup the SRSR Monthly Revenue field from the Opp Product.  This will also rollup to the Sales Credit and Sales Targets.</description>
        <label>SRSR Monthly Revenue</label>
        <summarizedField>OpportunityLineItem.SRSR_Monthly_Revenue__c</summarizedField>
        <summaryFilterItems>
            <field>OpportunityLineItem.Is_Monthly__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>SR_Monthly_Revenue__c</fullName>
        <label>SR Monthly Revenue</label>
        <summarizedField>OpportunityLineItem.SR_Monthly_Revenue__c</summarizedField>
        <summaryFilterItems>
            <field>OpportunityLineItem.Is_Monthly__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <recordTypes>
        <fullName>Healthgrades</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <description>For selling Healthgrades Premium Profiles</description>
        <label>Healthgrades</label>
    </recordTypes>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <label>Renewal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Retention</fullName>
        <active>true</active>
        <businessProcess>Save Process</businessProcess>
        <label>Retention</label>
    </recordTypes>
</CustomObject>

src.3/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Co_Terminate__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Determines if the Opportunity Product should be forced to co-terminate with all other Opportunity Products, regardless of free months.</description>
        <inlineHelpText>Determines if the Opportunity Product should be forced to co-terminate with all other Opportunity Products, regardless of free months.</inlineHelpText>
        <label>Co-Terminate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current_SR_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current SR Subscription</label>
        <referenceTo>RecurSoft__Product_Subscription__c</referenceTo>
        <relationshipLabel>Opportunity Product (Current SR Subscription)</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Free_Month_Setting__c</fullName>
        <description>Override opportunity free months</description>
        <label>Orientation Month Setting</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Extend Contract - At the Beginning</fullName>
                </value>
                <value>
                    <fullName>Include in Contract Period - At the Beginning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HG_Monthly_Revenue__c</fullName>
        <label>HG Monthly Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoiced_Price__c</fullName>
        <label>Invoiced Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Is_Monthly__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Scheduled revenue is monthly</description>
        <label>Is Monthly</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LL_Monthly_Revenue__c</fullName>
        <label>LL Monthly Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Modified_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Modified Subscription</label>
        <referenceTo>RecurSoft__Product_Subscription__c</referenceTo>
        <relationshipLabel>Opportunity Product (Modified Subscription)</relationshipLabel>
        <relationshipName>Opportunity_Product1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Free_Months__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Override opportunity free months</description>
        <inlineHelpText>Override opportunity free months</inlineHelpText>
        <label>Number of Orientation Months</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Code_Formula__c</fullName>
        <label>Product Code Formula</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Family_Duplicate__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Set via Apex.  Creates a key with Opportunity Id and Product Family so that only one Product from each Family can be added to an Opportunity.</description>
        <label>Product Family Duplicate</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related Provider for the Healthgrades Premium Profile</description>
        <inlineHelpText>The related Provider for the Healthgrades Premium Profile</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Billing_Frequency__c</fullName>
        <formula>IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;One-Time&quot;), &quot;One-Time&quot;,
IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;Monthly&quot;), &quot;Monthly&quot;,
IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;Quarterly&quot;), &quot;Quarterly&quot; ,
IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;Semi-Annual&quot;), &quot;Semi-Annual&quot;,
IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;Yearly&quot;), &quot;Yearly&quot; ,
IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;Milestones&quot;), &quot;Milestones&quot; , &quot;&quot;
)
)
)
)
)
)</formula>
        <inlineHelpText>Default billing frequency of the product.</inlineHelpText>
        <label>Billing Frequency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_Setting__c</fullName>
        <inlineHelpText>Contract duration options: months, days.</inlineHelpText>
        <label>Contract Term Setting</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Months</fullName>
                </value>
                <value>
                    <fullName>Days</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_Start_Date_New__c</fullName>
        <label>Contract Term Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Renewal_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Determines the system behaviour at the time of renewing the subscription.</inlineHelpText>
        <label>Renewal Rule</label>
        <referenceTo>RecurSoft__Renewal_Rule__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>RecurSoft_Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SRC_Monthly_Revenue__c</fullName>
        <description>Total revenue from the SR Conversations product family. Updated by WFR.  This will rollup to the Opportunity, Sales Credits, and Sales Targets.</description>
        <label>SRC Monthly Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SRSR_Monthly_Revenue__c</fullName>
        <description>Total revenue from the SR Smart Reviews product family. Updated by WFR. This will rollup to the Opportunity, Sales Credits, and Sales Targets.</description>
        <label>SRSR Monthly Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SR_Monthly_Revenue__c</fullName>
        <label>SR Monthly Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Monthly_Revenue__c</fullName>
        <label>Total Monthly Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Trial__c</fullName>
        <label>Trial Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>120</fullName>
                </value>
                <value>
                    <fullName>180</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.3/objects/Product2.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Contract_Display_Name__c</fullName>
        <label>Contract Display Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Co_Terminate__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Sets the default for co-termination on the related Opportunity Products.  Can be overridden at the Opportunity Product level.</description>
        <inlineHelpText>Sets the default for co-termination on the related Opportunity Products.  Can be overridden at the Opportunity Product level.</inlineHelpText>
        <label>Default Co-Terminate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Default_Renewal_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Provides the Default Renewal Rule for this Product. Will be set on Opportunity Products.</description>
        <inlineHelpText>Provides the Default Renewal Rule for this Product. Will be set on Opportunity Products.</inlineHelpText>
        <label>Default Renewal Rule</label>
        <referenceTo>RecurSoft__Renewal_Rule__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Billing_Frequency__c</fullName>
        <inlineHelpText>The frequency at which customer is invoiced.</inlineHelpText>
        <label>Billing Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One-Time</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-annual</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>Milestones</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.1/classes/OpportunityLineItems.cls
/*
Approvals
 - Need to rollup the MAX Approval Level Required to the Opp
 - Need to recalculate and rollup the MAX Approval Level Required if approval-related terms change
 - Need to set the Approved Values and rollup the MAX Approval Level Required to the Opp(should be 0) when approval is received
 - Need to reset any approvals that were received when the Opp owner changes

Contract Terms
 - Need to set contract start/end dates and term length before going closed won for prod subs creation
 - Need to calculate and set contract term for Add Product opps to end in the same month as SR subscription

*/
public class OpportunityLineItems extends fflib_SObjectDomain 
{
	public Map<Id, OpportunityLineItem> withRelatedObjects;
	public Map<Id, Product2> productMap;
	public static Map<String, Id> currentSubscriptionMap;
	public Map<Id, Date> accountIdToSRContractEndDateMap;
	public Map<Id, Date> opportunityIdToContractEndDateMap;
	public Set<Id> updateAllOppLisOnOpp;
	public Set<Id> productTermsRollup;
	public Set<Id> updateAllOpplisOnOppContractDates;
	public Set<Id> updateAllOpplisOnOppModifiedSubscriptions;
	public static Map<String, String> productFamilyToRevenueFieldMap = new Map<String, String>{
			'SR Platform' => 'SR_Monthly_Revenue__c',
			'SR Conversations' => 'SRC_Monthly_Revenue__c',
			'SR Smart Reviews' => 'SRSR_Monthly_Revenue__c',
			'SR Schedule' => 'LL_Monthly_Revenue__c',
			'Healthgrades' => 'HG_Monthly_Revenue__c'
		};
	public Set<Id> resetApoprovals;

	public OpportunityLineItems(OpportunityLineItem[] opportunityLineItems) 
	{
		super(opportunityLineItems);
		Configuration.disableTriggerCRUDSecurity();
	}

	public class Constructor implements fflib_SObjectDomain.IConstructable
	{
		public fflib_SObjectDomain construct(List<SObject> sObjectList)
		{
			return new OpportunityLineItems(sObjectList);
		}
	}

	public override void onBeforeInsert()
	{
		fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

		for(OpportunityLineItem oppLi : (OpportunityLineItem[]) Records) 
    	{
			this.setDefaultsFromProduct(oppLi);
			this.setMonthlyRevenue(oppLi, null);
			this.updateApprovalLevelRequired(oppLi, null);
			this.checkForProductTermsRollupUpdateNeeded(oppLi, null);
    	}

    	if(productTermsRollup != null && 
            !productTermsRollup.isEmpty()) SRUtilities.scheduleAsync(productTermsRollup, 'Product_Terms_Rollup', uow);

        uow.commitWork();
	}

	public override void onAfterInsert()
	{
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        for(OpportunityLineItem oppLi : (OpportunityLineItem[]) Records) 
    	{
    		this.validateProductFamily(oppLi);
			this.checkForContractDatesUpdateNeeded(oppLi, null);
    	}

    	if(updateAllOppLisOnOpp != null &&
            updateAllOppLisOnOpp.size() > 0) this.updateAllOppLisOnOpp(updateAllOppLisOnOpp, uow);

        uow.commitWork();
	}

	public override void onBeforeUpdate(Map<Id, SObject> existingRecords)
	{
		fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

		for(OpportunityLineItem oppLi : (OpportunityLineItem[]) Records) 
    	{
    		OpportunityLineItem existingOppLi = (OpportunityLineItem) existingRecords.get(oppLi.Id);
			this.setMonthlyRevenue(oppLi, existingOppLi);
			this.updateApprovalLevelRequired(oppLi, existingOppLi);
			this.checkForProductTermsRollupUpdateNeeded(oppLi, existingOppLi);
			this.checkApprovalReset(oppLi, existingOppLi);
    	}

    	if(productTermsRollup != null && 
            !productTermsRollup.isEmpty()) SRUtilities.scheduleAsync(productTermsRollup, 'Product_Terms_Rollup', uow);

    	if(updateAllOppLisOnOpp != null &&
            updateAllOppLisOnOpp.size() > 0) this.updateAllOppLisOnOpp(updateAllOppLisOnOpp, uow);

		if(resetApoprovals != null &&
				resetApoprovals.size() > 0) SRUtilities.scheduleAsync(resetApoprovals, 'Reset_Approvals', uow);

        uow.commitWork();
	}

	public override void onAfterUpdate(Map<Id, SObject> existingRecords)
	{
		fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        
		for(OpportunityLineItem oppLi : (OpportunityLineItem[]) Records) 
    	{
    		OpportunityLineItem existingOppLi = (OpportunityLineItem) existingRecords.get(oppLi.Id);
    		this.checkForContractDatesUpdateNeeded(oppLi, existingOppLi);
    	}

    	if(updateAllOppLisOnOpp != null &&
            updateAllOppLisOnOpp.size() > 0) this.updateAllOppLisOnOpp(updateAllOppLisOnOpp, uow);

        uow.commitWork();
	}
	
	public void checkForProductTermsRollupUpdateNeeded(OpportunityLineItem oppLi, OpportunityLineItem existingOppLi)
    {
    	if(existingOppLi != null && 
			existingOppLi.UnitPrice == oppLi.UnitPrice &&
			existingOppLi.Number_of_Free_Months__c == oppLi.Number_of_Free_Months__c &&
			existingOppLi.Trial__c == oppLi.Trial__c) return;

		if(productTermsRollup == null) productTermsRollup = new Set<Id>();
        productTermsRollup.add(oppLi.OpportunityId);
    }

	public void checkForContractDatesUpdateNeeded(OpportunityLineItem oppLi, OpportunityLineItem existingOppLi)
    {
		if(existingOppLi != null && 
			existingOppLi.Number_of_Free_Months__c == oppLi.Number_of_Free_Months__c &&
			existingOppLi.Free_Month_Setting__c == oppLi.Free_Month_Setting__c &&
			existingOppLi.RecurSoft__Contract_Term_Start_Date_New__c == oppLi.RecurSoft__Contract_Term_Start_Date_New__c) return;

        if(updateAllOppLisOnOpp == null) updateAllOppLisOnOpp = new Set<Id>();
        updateAllOppLisOnOpp.add(oppLi.OpportunityId);

		if(updateAllOpplisOnOppContractDates == null) updateAllOpplisOnOppContractDates = new Set<Id>();
        updateAllOpplisOnOppContractDates.add(oppLi.OpportunityId);
    }

	public void setDefaultsFromProduct(OpportunityLineItem oppLi)
	{
		if(productMap == null) productMap = new Map<Id, Product2>(ProductsSelector.newInstance().selectByOpportunityLineItems((OpportunityLineItem[]) Records));
        Product2 product = productMap.get(oppLi.Product2Id);

		oppLi.Is_Monthly__c = product.RecurSoft__Billing_Frequency__c == 'Monthly' ? true : false;
		oppLi.Product_Code_Formula__c = product.ProductCode;
		if(product.Family != null && product.Family != 'Healthgrades') oppLi.Product_Family_Duplicate__c = product.Family == 'Professional Services' ? oppLi.OpportunityId + product.Family + product.Contract_Display_Name__c : oppLi.OpportunityId + product.Family;
		oppLi.Co_Terminate__c = product.Default_Co_Terminate__c;
		oppLi.Free_Month_Setting__c = oppLi.Number_of_Free_Months__c == null || oppLi.Number_of_Free_Months__c == 0 ? null : oppLi.Free_Month_Setting__c;
		oppLi.RecurSoft__Contract_Term_Setting__c = 'Months';
		if(oppLi.RecurSoft__Renewal_Rule__c == null) oppLi.RecurSoft__Renewal_Rule__c = product.Default_Renewal_Rule__c;
	}

	//Called by updateAllOppLisOnOpp()
	public void setModifiedSubscriptions(OpportunityLineItem[] oppLis, fflib_SObjectUnitOfWork uow)
	{
		for(OpportunityLineItem oppLi : oppLis)
		{
			if(!updateAllOpplisOnOppModifiedSubscriptions.contains(oppLi.OpportunityId)) continue;
			setModifiedSubscriptions(oppLi, 'Modified_Subscription__c', uow);
			setModifiedSubscriptions(oppLi, 'Current_SR_Subscription__c', uow);
		}	
	}

	//Called by setModifiedSubscriptions()
	public void setModifiedSubscriptions(OpportunityLineItem oppLi, String fieldName, fflib_SObjectUnitOfWork uow) 
	{
		if((Boolean) oppLi.get('Override_' + fieldName)) return;
		if(oppLi.Opportunity.RecordTypeId != SRUtilities.getRecordTypeMap('Opportunity').get('Add-On Business').getRecordTypeId() &&
			oppLi.Opportunity.RecordTypeId != SRUtilities.getRecordTypeMap('Opportunity').get('Retention').getRecordTypeId()) return;
		
		if(currentSubscriptionMap == null) currentSubscriptionMap = AssetsSelector.newInstance().selectCurrentSubscriptionsByOpportunityLineItems((OpportunityLineItem[]) Records);
		String productName = fieldName == 'Current_SR_Subscription__c' ? 'SR Platform' : oppLi.Product2.Family;

		if(!currentSubscriptionMap.containsKey(oppLi.Opportunity.AccountId + productName + oppLi.Provider__c)) return;
		if(oppLi.get(fieldName) == currentSubscriptionMap.get(oppLi.Opportunity.AccountId + productName + oppLi.Provider__c)) return;

		oppLi.put(fieldName, currentSubscriptionMap.get(oppLi.Opportunity.AccountId + productName + oppLi.Provider__c));
		uow.registerDirty(oppLi);
	}

	public void setMonthlyRevenue(OpportunityLineItem oppLi, OpportunityLineItem existingOppLi)
	{
		if(existingOppLi != null && 
			existingOppLi.UnitPrice == oppLi.UnitPrice &&
			existingOppLi.Quantity == oppLi.Quantity &&
			existingOppLi.Invoiced_Price__c == oppLi.Invoiced_Price__c) return;

		if(productMap == null) productMap = new Map<Id, Product2>(ProductsSelector.newInstance().selectByOpportunityLineItems((OpportunityLineItem[]) Records));
        Product2 product = productMap.get(oppLi.Product2Id);

		if(product.RecurSoft__Billing_Frequency__c != 'Monthly') return;

		Decimal productPrice = oppLi.Invoiced_Price__c != null && 
			oppLi.Invoiced_Price__c > 0 ? 
			oppLi.Invoiced_Price__c * oppLi.Quantity : oppLi.UnitPrice == null ? 0 : oppLi.UnitPrice * oppLi.Quantity;
		oppLi.Total_Monthly_Revenue__c = productPrice;

		if(productFamilyToRevenueFieldMap.containsKey(product.Family))
		{
			oppLi.put(productFamilyToRevenueFieldMap.get(product.Family), productPrice);
			return;
		}
		else
		{
			oppLi.Other_Monthly_Revenue__c = productPrice;
		}
	}

	public void updateAllOppLisOnOpp(Set<Id> ids, fflib_SObjectUnitOfWork uow)
	{
		OpportunityLineItem[] oppLis = OpportunityLineItemsSelector.newInstance().selectByOpportunityIdWithAccountOpportunityProductPricebookEntry(ids);
		this.updateAllOppLisOnOpp(oppLis, uow);
	}

	//Called by updateAllOppLisOnOpp()
	public void updateAllOppLisOnOpp(OpportunityLineItem[] oppLis, fflib_SObjectUnitOfWork uow)
	{
		if(updateAllOpplisOnOppContractDates != null && !updateAllOpplisOnOppContractDates.isEmpty()) this.updateContractDates(oppLis, uow);
		if(updateAllOpplisOnOppModifiedSubscriptions != null && !updateAllOpplisOnOppModifiedSubscriptions.isEmpty()) this.setModifiedSubscriptions(oppLis, uow);
	}

	public void updateApprovalLevelRequired(OpportunityLineItem oppLi, OpportunityLineItem existingOppLi)
	{
		if(existingOppLi != null && 
			existingOppLi.UnitPrice == oppLi.UnitPrice &&
			existingOppLi.Number_of_Free_Months__c == oppLi.Number_of_Free_Months__c &&
			existingOppLi.Trial__c == oppLi.Trial__c &&
			existingOppLi.Approved_Price_Discount__c == oppLi.Approved_Price_Discount__c &&
			existingOppLi.Approved_Free_Months__c == oppLi.Approved_Free_Months__c &&
			existingOppLi.Approved_Trial__c == oppLi.Approved_Trial__c) return;

		oppLi.Approval_Level_Required__c = Math.max(Math.max(oppLi.Approval_Level_Required_Price_Discount__c,
			oppLi.Approval_Level_Required_Free_Months__c),
			oppLi.Approval_Level_Required_Trial__c);
	}
	
	//Called by updateAllOppLisOnOpp()
	public void updateContractDates(OpportunityLineItem[] oppLis, fflib_SObjectUnitOfWork uow)
	{
		for(OpportunityLineItem oppLi : oppLis)
		{
			if(oppLi.Opportunity.IsClosed) continue;
			if(oppLi.Opportunity.RecordTypeId != SRUtilities.getRecordTypeId('Opportunity', 'Add Product') &&
            	oppLi.Opportunity.RecurSoft__Contract_Signed_Date__c == null) continue;
			if(!updateAllOpplisOnOppContractDates.contains(oppLi.OpportunityId)) continue;
			this.setContractStartDate(oppLi);
			this.setContractEndDate(oppLi);
		}

		for(OpportunityLineItem oppLi : oppLis)
		{
			if(oppLi.Opportunity.IsClosed) continue;
			if(oppLi.Opportunity.RecordTypeId != SRUtilities.getRecordTypeId('Opportunity', 'Add Product') &&
            	oppLi.Opportunity.RecurSoft__Contract_Signed_Date__c == null) continue;
			if(!updateAllOpplisOnOppContractDates.contains(oppLi.OpportunityId)) continue;

			if(oppLi.RecurSoft__Contract_Term_End_Date_Editable__c != opportunityIdToContractEndDateMap.get(oppLi.OpportunityId) &&
				oppLi.Product2.Default_Contract_Term__c != 1)
			{
				oppLi.RecurSoft__Contract_Term_End_Date_Editable__c = opportunityIdToContractEndDateMap.get(oppLi.OpportunityId);
			}
			oppLi.RecurSoft__Contract_Term1__c = String.valueOf(oppLi.RecurSoft__Contract_Term_Start_Date_New__c.monthsBetween(oppLi.RecurSoft__Contract_Term_End_Date_Editable__c));
			oppLi.RecurSoft__Contract_Term_Setting__c = 'Months';
			uow.registerDirty(oppLi);
		}
	}

	//Called by updateContractDates()
	public void setContractStartDate(OpportunityLineItem oppLi)
	{
        if(oppLi.Opportunity.RecordTypeId == SRUtilities.getRecordTypeMap('Opportunity').get('Add-On Business').getRecordTypeId()) return;
		if(oppLi.Opportunity.RecordTypeId == SRUtilities.getRecordTypeMap('Opportunity').get('Renewal').getRecordTypeId()) return;
		
		Decimal offsetDays = oppLi.PricebookEntry.Pricebook2.Contract_Start_Date_Offset__c == null ? 0 : oppLi.PricebookEntry.Pricebook2.Contract_Start_Date_Offset__c;
		
		oppLi.RecurSoft__Contract_Term_Start_Date_New__c = oppLi.Opportunity.RecurSoft__Contract_Signed_Date__c == null ? 
			Date.today() : oppLi.Opportunity.RecurSoft__Contract_Signed_Date__c.addDays(Integer.valueOf(offsetDays)); 
	}

	//Called by updateContractDates()
	public void setContractEndDate(OpportunityLineItem oppLi)
	{
		if(oppLi.RecurSoft__Contract_Term_Start_Date_New__c == null) return;
        
		Integer contractTerm = getContractTerm(oppLi);
		
		oppLi.RecurSoft__Contract_Term_End_Date_Editable__c = oppLi.RecurSoft__Contract_Term_Start_Date_New__c.addMonths(contractTerm).addDays(-1);
			
		if(opportunityIdToContractEndDateMap == null) opportunityIdToContractEndDateMap = new Map<Id, Date>();
		if(!opportunityIdToContractEndDateMap.containsKey(oppLi.OpportunityId) ||
			opportunityIdToContractEndDateMap.get(oppLi.OpportunityId) < oppLi.RecurSoft__Contract_Term_End_Date_Editable__c) 
		{
			opportunityIdToContractEndDateMap.put(oppLi.OpportunityId, oppLi.RecurSoft__Contract_Term_End_Date_Editable__c);
		}
	}

	//Called from setContractEndDate()
	public Integer getContractTerm(OpportunityLineItem oppLi)
	{
		Integer contractTerm;
		Integer freeMonths = oppLi.Number_of_Free_Months__c == null ? 0 : Integer.valueOf(oppLi.Number_of_Free_Months__c);
		
		if(oppLi.Opportunity.RecordTypeId == SRUtilities.getRecordTypeMap('Opportunity').get('Add Product').getRecordTypeId() ||
			oppLi.Opportunity.RecordTypeId == SRUtilities.getRecordTypeMap('Opportunity').get('Healthgrades').getRecordTypeId())
		{
			if(accountIdToSRContractEndDateMap == null) accountIdToSRContractEndDateMap = OpportunityLineItemsSelector.newInstance().getAccountIdToSRContractEndDateMap((OpportunityLineItem[]) Records);
			if(accountIdToSRContractEndDateMap.containsKey(oppLi.Opportunity.AccountId)) 
			{
				Date endDate = accountIdToSRContractEndDateMap.get(oppLi.Opportunity.AccountId);
				Integer monthsLeft = oppLi.RecurSoft__Contract_Term_Start_Date_New__c.monthsBetween(endDate);
				contractTerm = oppLi.Product2.Default_Contract_Term__c == 1 ? 1 : monthsLeft > 0 ? monthsLeft : monthsLeft + 12;
			}
			else
			{
				throw new SRUtilities.SRException('This Account does not have a current SR Platform subscription, you cannot Add Products');
			}
		}
		else
		{
			contractTerm = oppLi.Product2.Default_Contract_Term__c == 1 ? 1 : Integer.valueOf(oppLi.Opportunity.RecurSoft__Initial_Contract_Term__c);
		}	

		if(contractTerm != null && oppLi.Free_Month_Setting__c == 'Extend Contract - At the Beginning') contractTerm = contractTerm + freeMonths;
		return contractTerm;
	}

	public void validateProductFamily(OpportunityLineItem oppLi)
	{
		if(withRelatedObjects == null) withRelatedObjects = new Map<Id, OpportunityLineItem>(OpportunityLineItemsSelector.newInstance().selectByIdWithAccountOpportunityProductPricebookEntry(new Map<Id, OpportunityLineItem>((OpportunityLineItem[]) Records).keySet()));
        OpportunityLineItem oppLiWithRelatedObjects = withRelatedObjects.get(oppLi.Id);

		if(oppLiWithRelatedObjects.Product2.Family == null) return;

		if(currentSubscriptionMap == null) currentSubscriptionMap = AssetsSelector.newInstance().selectCurrentSubscriptionsByOpportunityLineItems((OpportunityLineItem[]) Records);
		if(!currentSubscriptionMap.containsKey(oppLiWithRelatedObjects.Opportunity.AccountId + oppLiWithRelatedObjects.Product2.Family + oppLiWithRelatedObjects.Provider__c) ||
			currentSubscriptionMap.get(oppLiWithRelatedObjects.Opportunity.AccountId + oppLiWithRelatedObjects.Product2.Family + oppLiWithRelatedObjects.Provider__c) == null) return;
		
		throw new SRUtilities.SRException('There is already an active subscription for this product family');
	}

	public void checkApprovalReset(OpportunityLineItem oppLi, OpportunityLineItem existingOppLi)
	{
		 if(existingOppLi != null &&
            existingOppLi.Free_Month_Setting__c == oppLi.Free_Month_Setting__c) return;

        if(resetApoprovals == null) resetApoprovals = new Set<Id>();
		resetApoprovals.add(oppLi.OpportunityId);
	}
}