src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>RecurSoft__Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill to Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.RecurSoft__Bill_to_Account__c</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>RecurSoft_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Initial_Contract_Term__c</fullName>
        <defaultValue>12</defaultValue>
        <inlineHelpText>Contract duration, in months.</inlineHelpText>
        <label>Contract Term (Months)</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Shipping_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship to Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.RecurSoft__Bill_to_Account__c</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Ship to Contact)</relationshipLabel>
        <relationshipName>RecurSoft_Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Healthgrades</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <description>For selling Healthgrades Premium Profiles</description>
        <label>Healthgrades</label>
    </recordTypes>
</CustomObject>

src.3/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Base_Contract_Term__c</fullName>
        <label>Base Contract Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Co_Terminate__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Determines if the Opportunity Product should be forced to co-terminate with all other Opportunity Products, regardless of free months.</description>
        <inlineHelpText>Determines if the Opportunity Product should be forced to co-terminate with all other Opportunity Products, regardless of free months.</inlineHelpText>
        <label>Co-Terminate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Free_Month_Setting__c</fullName>
        <description>Override opportunity free months</description>
        <label>Orientation Month Setting</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Extend Contract - At the Beginning</fullName>
                </value>
                <value>
                    <fullName>Include in Contract Period - At the Beginning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Promo_Item__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Promo Item</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Free_Months__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Override opportunity free months</description>
        <inlineHelpText>Override opportunity free months</inlineHelpText>
        <label>Number of Orientation Months</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Promotional_Price__c</fullName>
        <description>Allows for giving promotional months at a discounted price.</description>
        <label>Orientation Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Billing_Frequency__c</fullName>
        <formula>IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;One-Time&quot;), &quot;One-Time&quot;,
IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;Monthly&quot;), &quot;Monthly&quot;,
IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;Quarterly&quot;), &quot;Quarterly&quot; ,
IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;Semi-Annual&quot;), &quot;Semi-Annual&quot;,
IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;Yearly&quot;), &quot;Yearly&quot; ,
IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;Milestones&quot;), &quot;Milestones&quot; , &quot;&quot;
)
)
)
)
)
)</formula>
        <inlineHelpText>Default billing frequency of the product.</inlineHelpText>
        <label>Billing Frequency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term1__c</fullName>
        <inlineHelpText>Contract duration.</inlineHelpText>
        <label>Contract Term</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_End_Date_Editable__c</fullName>
        <label>Contract Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_Start_Date_New__c</fullName>
        <label>Contract Term Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Trial__c</fullName>
        <label>Trial Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>120</fullName>
                </value>
                <value>
                    <fullName>180</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.3/objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>Free_Months_Floor__c</fullName>
        <label>Free Months Floor</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_Discount_Floor__c</fullName>
        <label>Price Discount Floor</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Trial_Period_Floor__c</fullName>
        <label>Trial Period Floor</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src.3/objects/Product2.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Default_Contract_Term__c</fullName>
        <description>If Inherit Opportunity Contract Terms is false, the Contract Term will be set on the Opportunity Product to (Default Contract Term + Product Number of Free Months) and reset to this value when an Opportunity contract term change is made. For month-to-month products.</description>
        <inlineHelpText>If Inherit Opportunity Contract Terms is false, the Contract Term will be set on the Opportunity Product to (Default Contract Term + Product Number of Free Months) and reset to this value when an Opportunity contract term change is made.</inlineHelpText>
        <label>Default Contract Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Default_Co_Terminate__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Sets the default for co-termination on the related Opportunity Products.  Can be overridden at the Opportunity Product level.</description>
        <inlineHelpText>Sets the default for co-termination on the related Opportunity Products.  Can be overridden at the Opportunity Product level.</inlineHelpText>
        <label>Default Co-Terminate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Default_Renewal_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Provides the Default Renewal Rule for this Product. Will be set on Opportunity Products.</description>
        <inlineHelpText>Provides the Default Renewal Rule for this Product. Will be set on Opportunity Products.</inlineHelpText>
        <label>Default Renewal Rule</label>
        <referenceTo>RecurSoft__Renewal_Rule__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Billing_Frequency__c</fullName>
        <inlineHelpText>The frequency at which customer is invoiced.</inlineHelpText>
        <label>Billing Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One-Time</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-annual</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>Milestones</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.3/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Approval_Exempt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approval Exempt</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src.3/classes/ProductEditController.cls
public with sharing class ProductEditController extends WebFormsUtilityClass {
	
	public ApexPages.StandardController stdCtrl { get; set; }
	public Opportunity opp { get; set; }
	public OpportunityLineItem[] listOppLis { get; set; }
	public Boolean renderEdit { get; set; }
	public Boolean error { get; set; }
	public Map<Id, User> userMap { get; set; }
	
	public ProductEditController(ApexPages.StandardController stdController) {
		
		this.opp = (Opportunity)stdController.getRecord();
		stdCtrl = stdController;
		renderEdit = false;
		error = false;
		userMap = new Map<Id, User>((User[]) UsersSelector.newInstance().selectSObjectsById(new Set<Id>{UserInfo.getUserId()}));
		
        try{

        listOppLis = [SELECT Id,
	    	Is_Promo_Item__c,
	    	ListPrice,
	    	UnitPrice,
	    	TotalPrice,
	    	Quantity,
	    	OpportunityId, 
	    	Opportunity.RecordType.Name,
	    	Opportunity.RecurSoft__Billing_Contact__r.Email,
	    	Opportunity.RecurSoft__Billing_Contact__r.Phone,
	    	Opportunity.RecurSoft__Shipping_Contact__r.Email,
	    	Opportunity.RecurSoft__Shipping_Contact__r.Phone,
	    	Number_of_Free_Months__c, 
	    	Promotional_Price__c,
	    	Co_Terminate__c, 
	    	Trial__c,
	    	Free_Month_Setting__c, 
	    	Base_Contract_Term__c, 
	    	RecurSoft__Contract_Term1__c, 
	    	RecurSoft__Contract_Term_End_Date_Editable__c, 
	    	RecurSoft__Contract_Term_Start_Date_New__c, 
	    	PricebookEntryId,
	    	PriceBookEntry.Name,
	    	PriceBookEntry.UnitPrice,
	    	PricebookEntry.Product2Id, 
	    	PricebookEntry.Product2.Name,
	    	PricebookEntry.Product2.ProductCode,
	    	PricebookEntry.Pricebook2Id, 
	    	PricebookEntry.Price_Discount_Floor__c,
	    	PricebookEntry.Trial_Period_Floor__c,
	    	PricebookEntry.Free_Months_Floor__c,
	    	Product2.Default_Renewal_Rule__c, 
	    	Product2.Family, 
	    	Product2.Default_Contract_Term__c, 
	    	Product2.Default_Co_Terminate__c, 
	    	Product2.RecurSoft__Billing_Frequency__c 
	    	FROM OpportunityLineItem
			WHERE OpportunityId = :opp.Id];

			} catch(Exception e) {}
	}

	public PageReference edit() 
	{
		renderEdit = true;
		return null;
	}

	public PageReference cancel() 
	{
		renderEdit = false;
		return null;
	}

	public PageReference saveOppLis() 
	{
		Boolean hasError = false;

		for(OpportunityLineItem oppLi : listOppLis) 
		{
			if(oppLi.Number_of_Free_Months__c > 0 && (oppLi.Free_Month_Setting__c == null || oppLi.Free_Month_Setting__c == 'None')) 
			{
				hasError = true;
				oppLi.Free_Month_Setting__c.addError('You must select an Orientation Month Setting with Orientation Months');
			}

			if(oppLi.Number_of_Free_Months__c > 0 && oppLi.Promotional_Price__c == null) 
			{
				hasError = true;
				oppLi.Promotional_Price__c.addError('You must set an Orientation Price with Orientation Months');
			}

			if((oppLi.Number_of_Free_Months__c == 0 || oppLi.Number_of_Free_Months__c == null) && oppLi.Promotional_Price__c != null) 
			{
				hasError = true;
				oppLi.Promotional_Price__c.addError('You must set the number of Orientation Months or leave Orientation Price blank');
			}

			if(oppLi.Base_Contract_Term__c <= oppLi.Number_of_Free_Months__c && 
				oppLi.Free_Month_Setting__c == 'Include in Contract Period - At the Beginning') 
			{
				hasError = true;
				oppLi.Free_Month_Setting__c.addError('The number of Orientation Months exceeds the number of months in the Contract period.' +
					'Please adjust the Number of Orientation Months or the Orientation Month Setting.');
			}

			if(oppLi.Opportunity.RecurSoft__Billing_Contact__c != null && (oppLi.Opportunity.RecurSoft__Billing_Contact__r.Email == null || oppLi.Opportunity.RecurSoft__Billing_Contact__r.Phone == null))
			{
				hasError = true;
				oppLi.UnitPrice.addError('The Bill To Contact Needs To Have A Phone & Email');
			}

			if(oppLi.Opportunity.RecurSoft__Shipping_Contact__c != null && (oppLi.Opportunity.RecurSoft__Shipping_Contact__r.Email == null || oppLi.Opportunity.RecurSoft__Shipping_Contact__r.Phone == null))
			{
				hasError = true;
				oppLi.UnitPrice.addError('The Ship To Contact Needs To Have A Phone & Email');
			}

			if(oppLi.Product2.RecurSoft__Billing_Frequency__c == 'One-Time' &&
				oppLi.Number_of_Free_Months__c > 0) 
			{
				hasError = true;
				oppLi.Number_of_Free_Months__c.addError('One-Time products cannot have Orientation Months.');
			}

			if(oppLi.Product2.RecurSoft__Billing_Frequency__c == 'One-Time' &&
				oppLi.Trial__c != null) 
			{
				hasError = true;
				oppLi.Trial__c.addError('One-Time products cannot have a Trial Period.');
			}

			if((oppLi.Opportunity.RecordType.Name == 'Add Product' ||
				oppLi.Opportunity.RecordType.Name == 'Healthgrades') && 
				oppLi.Co_Terminate__c &&
				oppLi.Free_Month_Setting__c == 'Extend Contract - At the Beginning') 
			{
				hasError = true;
				oppLi.Free_Month_Setting__c.addError('This Product is set to Co-Terminate with an existing Subscription. You cannot extend the term.');
			}

			if(oppLi.PricebookEntry.Price_Discount_Floor__c != null &&
				oppLi.PricebookEntry.Price_Discount_Floor__c > oppLi.UnitPrice &&
				UserInfo.getProfileId() != '00ei0000001ZJPd' && //Finance
				!userMap.get(UserInfo.getUserId()).Approval_Exempt__c &&
				oppLi.Opportunity.RecordType.Name != 'Add-On Business') 
			{
				hasError = true;
				oppLi.UnitPrice.addError('The price is lower than the minimum allowable price.');
			}

			if(oppLi.PricebookEntry.Trial_Period_Floor__c != null &&
				oppLi.Trial__c != null &&
				oppLi.PricebookEntry.Trial_Period_Floor__c < Decimal.valueOf(oppLi.Trial__c) &&
				UserInfo.getProfileId() != '00ei0000001ZJPd' && //Finance
				!userMap.get(UserInfo.getUserId()).Approval_Exempt__c &&
				oppLi.Opportunity.RecordType.Name != 'Add-On Business') 
			{
				hasError = true;
				oppLi.Trial__c.addError('The trial period is greater than the maximum allowable period.');
			}

			if(oppLi.PricebookEntry.Free_Months_Floor__c != null &&
				oppLi.PricebookEntry.Free_Months_Floor__c < oppLi.Number_of_Free_Months__c &&
				UserInfo.getProfileId() != '00ei0000001ZJPd' && //Finance
				!userMap.get(UserInfo.getUserId()).Approval_Exempt__c &&
				oppLi.Opportunity.RecordType.Name != 'Add-On Business') 
			{
				hasError = true;
				oppLi.Number_of_Free_Months__c.addError('The number of Orientation Months is greater than the maximum allowable Orientation Months.');
			}

			if(oppLi.Product2.RecurSoft__Billing_Frequency__c == 'Yearly' &&
				opp.RecurSoft__Initial_Contract_Term__c != 12)
			{
				hasError = true;
				opp.RecurSoft__Initial_Contract_Term__c.addError('Annual Billing requires a 12 Month Term');
			}
		}

		if(!hasError) 
		{
			update listOppLis;
			stdCtrl.save();
			renderEdit = false;
			return ApexPages.currentPage();
		} 
		else 
		{
			error = true;
			renderEdit = true;
			return null;
		}
	}
}