src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Approval_Level_Required_Term__c</fullName>
        <formula>IF( Owner.Approval_Exempt__c = true , 0 ,
	IF( RecordType.Name = &quot;New Practice Business&quot; , /*The term is usually set to coterminate in other record types*/
		IF( RecurSoft__Initial_Contract_Term__c  &gt;= 
			MIN( Approved_Term__c, Pricebook2.Level_0_Limit_Term__c ) , 0 , 
			IF( RecurSoft__Initial_Contract_Term__c &gt;= 
				MIN( Approved_Term__c, Pricebook2.Level_1_Limit_Term__c ) , 1 , 
				IF( RecurSoft__Initial_Contract_Term__c  &gt;=
					MIN( Approved_Term__c, Pricebook2.Level_2_Limit_Term__c ) , 2 , 3
				)
			)
		) , 0
	)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Approval Level Required - Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approval_Level_Required__c</fullName>
        <label>Approval Level Required</label>
        <summarizedField>OpportunityLineItem.Approval_Level_Required__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Product_Terms__c</fullName>
        <description>Roll up of Product Terms field on all products.  Set by Apex</description>
        <label>Product Terms</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the related Provider record</description>
        <inlineHelpText>Link to the related Provider record</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src.3/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Approval_Level_Required_Free_Months__c</fullName>
        <formula>IF( Opportunity.Owner.Approval_Exempt__c = true , 0 ,
	IF( Number_of_Free_Months__c &gt; 
		MAX(Approved_Free_Months__c, PricebookEntry.Level_2_Limit_Free_Months__c ) , 3 , 
		IF( Number_of_Free_Months__c &gt; 
			MAX(Approved_Free_Months__c, PricebookEntry.Level_1_Limit_Free_Months__c ) , 2 , 
			IF( Number_of_Free_Months__c &gt; 
				MAX(Approved_Free_Months__c, PricebookEntry.Level_0_Limit_Free_Months__c ) , 1 , 0
			)
		)
	)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Approval Level Required - Free Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approval_Level_Required_Price_Discount__c</fullName>
        <formula>IF( Opportunity.Owner.Approval_Exempt__c = true , 0 ,
	IF( List_Price_Override__c &gt; 0 ,
		IF( UnitPrice &gt;= /*If the price discount is less than level 1 threshold, 0 Approval Level*/ 
			(List_Price_Override__c - 
				(List_Price_Override__c * 
					MAX( Approved_Price_Discount__c,PricebookEntry.Level_0_Limit_Price_Discount__c )
				)
			) , 0 ,
			IF( UnitPrice &gt;= 
				(List_Price_Override__c - 
					(List_Price_Override__c * 
						MAX( Approved_Price_Discount__c, PricebookEntry.Level_1_Limit_Price_Discount__c )
					)
				) , 1 ,
				IF( UnitPrice &gt;= 
					(List_Price_Override__c - 
						(List_Price_Override__c * 
							MAX( Approved_Price_Discount__c, PricebookEntry.Level_2_Limit_Price_Discount__c )
						)
					) , 2 , 3
				)
			)
		)  ,
		IF( UnitPrice &gt;= 
			(PricebookEntry.UnitPrice - 
				(PricebookEntry.UnitPrice * 
					MAX( Approved_Price_Discount__c, PricebookEntry.Level_0_Limit_Price_Discount__c )
				)
			) , 0 ,
			IF( UnitPrice &gt;= 
				(PricebookEntry.UnitPrice - 
					(PricebookEntry.UnitPrice * 
						MAX( Approved_Price_Discount__c, PricebookEntry.Level_1_Limit_Price_Discount__c )
					)
				) , 1 ,
				IF( UnitPrice &gt;= 
					(PricebookEntry.UnitPrice - 
						(PricebookEntry.UnitPrice * 
							MAX( Approved_Price_Discount__c, PricebookEntry.Level_2_Limit_Price_Discount__c )
						)
					) , 2,  3
				)
			)
		)
	)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Approval Level Required - Price Discount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approval_Level_Required_Term__c</fullName>
        <formula>IF( Opportunity.Owner.Approval_Exempt__c = true , 0 ,
	IF( Opportunity.RecordType.Name = &quot;New Practice Business&quot; , /*The term is usually set to coterminate in other record types*/
		IF( Opportunity.RecurSoft__Initial_Contract_Term__c  &gt;= 
			MIN( Approved_Term__c, PricebookEntry.Level_0_Limit_Term__c ) , 0 , 
			IF( Opportunity.RecurSoft__Initial_Contract_Term__c &gt;= 
				MIN( Approved_Term__c, PricebookEntry.Level_1_Limit_Term__c ) , 1 , 
				IF( Opportunity.RecurSoft__Initial_Contract_Term__c  &gt;=
					MIN( Approved_Term__c, PricebookEntry.Level_2_Limit_Term__c ) , 2 , 3
				)
			)
		) , 0
	)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Approval Level Required - Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approval_Level_Required_Trial__c</fullName>
        <formula>IF( Opportunity.Owner.Approval_Exempt__c = true , 0 ,
	IF( VALUE(TEXT( Trial__c)) &gt; 
		MAX( Approved_Trial__c, PricebookEntry.Level_2_Limit_Trial__c ) , 3 , 
		IF( VALUE(TEXT( Trial__c)) &gt; 
			MAX( Approved_Trial__c, PricebookEntry.Level_1_Limit_Trial__c ) , 2 , 
			IF( VALUE(TEXT( Trial__c)) &gt; 
				MAX( Approved_Trial__c, PricebookEntry.Level_0_Limit_Trial__c ) , 1 , 0
			)
		)
	)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Approval Level Required - Trial</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approval_Level_Required__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Approval Level Required</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approved_Price_Discount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Approved - Price Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Base_Contract_Term__c</fullName>
        <label>Base Contract Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Competitor_Buyout__c</fullName>
        <label>Competitor Buyout</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>4 Patient Care</fullName>
                </value>
                <value>
                    <fullName>DemandForce</fullName>
                </value>
                <value>
                    <fullName>eCentral</fullName>
                </value>
                <value>
                    <fullName>eReminders</fullName>
                </value>
                <value>
                    <fullName>Lighthouse</fullName>
                </value>
                <value>
                    <fullName>Patient Activator</fullName>
                </value>
                <value>
                    <fullName>Phone Tree</fullName>
                </value>
                <value>
                    <fullName>PM/EMR</fullName>
                </value>
                <value>
                    <fullName>Practice Mojo</fullName>
                </value>
                <value>
                    <fullName>Sesame</fullName>
                </value>
                <value>
                    <fullName>Teledental</fullName>
                </value>
                <value>
                    <fullName>Televox</fullName>
                </value>
                <value>
                    <fullName>Weave</fullName>
                </value>
                <value>
                    <fullName>Websystem3</fullName>
                </value>
                <value>
                    <fullName>RevenueWell</fullName>
                </value>
                <value>
                    <fullName>ZocDoc</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Co_Terminate__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Determines if the Opportunity Product should be forced to co-terminate with all other Opportunity Products, regardless of free months.</description>
        <inlineHelpText>Determines if the Opportunity Product should be forced to co-terminate with all other Opportunity Products, regardless of free months.</inlineHelpText>
        <label>Co-Terminate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current_SR_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current SR Subscription</label>
        <referenceTo>RecurSoft__Product_Subscription__c</referenceTo>
        <relationshipLabel>Opportunity Product (Current SR Subscription)</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Free_Month_Setting__c</fullName>
        <description>Override opportunity free months</description>
        <label>Orientation Month Setting</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Extend Contract - At the Beginning</fullName>
                </value>
                <value>
                    <fullName>Include in Contract Period - At the Beginning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Promo_Item__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Promo Item</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>List_Price_Override__c</fullName>
        <description>Used for products that are discounted from regular List Price because of a bundle purchase, but shouldn&#39;t be treated as a discount for approval purposes.  

For example, SR Elite with Limelight Bundle discounts the SR Elite List Price by the List Price of Limelight Bundle.  This field is then used as the new base for pricing discount approvals.  

The field is set via Apex.</description>
        <label>List Price Override</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Modified_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Modified Subscription</label>
        <referenceTo>RecurSoft__Product_Subscription__c</referenceTo>
        <relationshipLabel>Opportunity Product (Modified Subscription)</relationshipLabel>
        <relationshipName>Opportunity_Product1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Free_Months__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Override opportunity free months</description>
        <inlineHelpText>Override opportunity free months</inlineHelpText>
        <label>Number of Orientation Months</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Override_Current_SR_Subscription__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Override Current SR Subscription</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Override_Modified_Subscription__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Override Modified Subscription</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Terms__c</fullName>
        <formula>IF( ISPICKVAL( PricebookEntry.Product2.RecurSoft__Billing_Frequency__c , &quot;Monthly&quot; ) ,
			PricebookEntry.Product2.Name &amp; &quot;: &lt;br&gt;&quot;  &amp;
			&quot;$&quot; &amp; TEXT(UnitPrice) &amp; &quot;(&quot; &amp; TEXT(ROUND(Price_Discount__c, 4) * 100) &amp; &quot;% Discount) &lt;br&gt;&quot;  &amp;
			IF(Number_of_Free_Months__c &gt; 0 , 
						TEXT(Number_of_Free_Months__c) &amp; &quot; Orientation Months at $&quot; &amp; TEXT(Promotional_Price__c) &amp; &quot; &lt;br&gt;&quot; , &quot;&quot; ) &amp;
			IF(ISBLANK(TEXT(Trial__c)), 
						&quot;0&quot; , TEXT(Trial__c)) &amp; &quot; Day Trial&quot;,
			PricebookEntry.Product2.Name &amp; &quot;: &lt;br&gt;&quot;  &amp; 
			&quot;$&quot; &amp; TEXT(UnitPrice) &amp; &quot;(&quot; &amp; TEXT(ROUND(Price_Discount__c, 4) * 100) &amp; &quot;% Discount)&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Terms</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Promotional_Price__c</fullName>
        <description>Allows for giving promotional months at a discounted price.</description>
        <label>Orientation Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related Provider for the Healthgrades Premium Profile</description>
        <inlineHelpText>The related Provider for the Healthgrades Premium Profile</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term1__c</fullName>
        <inlineHelpText>Contract duration.</inlineHelpText>
        <label>Contract Term</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trial__c</fullName>
        <label>Trial Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>120</fullName>
                </value>
                <value>
                    <fullName>180</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.3/classes/OpportunityLineItemsSelector.cls
public class OpportunityLineItemsSelector extends fflib_SObjectSelector 
{
	public Schema.SObjectField[] getSObjectFieldList() 
	{
		return new List<Schema.SObjectField> {
			OpportunityLineItem.Id,
			OpportunityLineItem.Approval_Level_Required__c,
			OpportunityLineItem.Approval_Level_Required_Free_Months__c,
			OpportunityLineItem.Approval_Level_Required_Price_Discount__c,
			OpportunityLineItem.Approval_Level_Required_Term__c,
			OpportunityLineItem.Approval_Level_Required_Trial__c,
			OpportunityLineItem.Approved_Price_Discount__c,
			OpportunityLineItem.Base_Contract_Term__c,
			OpportunityLineItem.Competitor_Buyout__c,
			OpportunityLineItem.Co_Terminate__c,
			OpportunityLineItem.Current_SR_Subscription__c,
			OpportunityLineItem.Free_Month_Setting__c,
			OpportunityLineItem.Is_Promo_Item__c,
			OpportunityLineItem.ListPrice,
			OpportunityLineItem.List_Price_Override__c,
			OpportunityLineItem.Modified_Subscription__c,
			OpportunityLineItem.Number_of_Free_Months__c,
			OpportunityLineItem.OpportunityId,
			OpportunityLineItem.Override_Current_SR_Subscription__c,
			OpportunityLineItem.Override_Modified_Subscription__c,
			OpportunityLineItem.PricebookEntryId,
			OpportunityLineItem.Product_Terms__c,
			OpportunityLineItem.Provider__c,
			OpportunityLineItem.Promotional_Price__c,
			OpportunityLineItem.Quantity,
			OpportunityLineItem.RecurSoft__Contract_Term1__c,
			OpportunityLineItem.RecurSoft__Contract_Term_End_Date_Editable__c,
			OpportunityLineItem.RecurSoft__Contract_Term_Setting__c,
			OpportunityLineItem.RecurSoft__Contract_Term_Start_Date_New__c,
			OpportunityLineItem.RecurSoft__Product_Subscription__c,
			OpportunityLineItem.RecurSoft__Renewal_Rule__c,
			OpportunityLineItem.SR_Conversations_Phone_Number__c,
			OpportunityLineItem.Total_Contract_Term__c,
			OpportunityLineItem.TotalPrice,
			OpportunityLineItem.Trial__c,
			OpportunityLineItem.Trial_End_Date__c,
			OpportunityLineItem.UnitPrice };
	}

	public Schema.SObjectType getSObjectType()
	{
		return OpportunityLineItem.SObjectType;
	}

	public static OpportunityLineItemsSelector newInstance()
	{
		return (OpportunityLineItemsSelector) Application.Selector.newInstance(OpportunityLineItem.SObjectType);
	}

	public OpportunityLineItem[] selectByProductSubscriptions(RecurSoft__Product_Subscription__c[] subscriptions)
	{
		Set<Id> ids = new Set<Id>();

		for(RecurSoft__Product_Subscription__c subscription : subscriptions)
		{
			ids.add(subscription.RecurSoft__Opportunity_Product_ID__c);
		}

		fflib_QueryFactory opportunityLineItemQueryFactory = newQueryFactory();

		new PricebookEntriesSelector().configureQueryFactoryFields(opportunityLineItemQueryFactory, 'PricebookEntry');

		new ProductsSelector().configureQueryFactoryFields(opportunityLineItemQueryFactory, 'PricebookEntry.Product2');

		new ProvidersSelector().configureQueryFactoryFields(opportunityLineItemQueryFactory, 'Provider__r');

		return (OpportunityLineItem[]) Database.query(
			opportunityLineItemQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList())).setCondition('Id IN :ids').toSOQL());
	}

	public OpportunityLineItem[] selectByIdWithAccountOpportunityProductPricebookEntry(Set<Id> ids)
	{
		fflib_QueryFactory opportunityLineItemQueryFactory = newQueryFactory();

		new OpportunitiesSelector().configureQueryFactoryFields(opportunityLineItemQueryFactory, 'Opportunity');

		new AccountsSelector().configureQueryFactoryFields(opportunityLineItemQueryFactory, 'Opportunity.Account');

		new PricebookEntriesSelector().configureQueryFactoryFields(opportunityLineItemQueryFactory, 'PricebookEntry');

		new ProductsSelector().configureQueryFactoryFields(opportunityLineItemQueryFactory, 'Product2');

		return (OpportunityLineItem[]) Database.query(
			opportunityLineItemQueryFactory.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList())).setCondition('Id IN :ids').toSOQL());
	}

	public OpportunityLineItem[] selectByOpportunityIdWithAccountOpportunityProductPricebookEntry(Set<Id> ids)
	{
		fflib_QueryFactory opportunityLineItemQueryFactory = newQueryFactory();

		new OpportunitiesSelector().configureQueryFactoryFields(opportunityLineItemQueryFactory, 'Opportunity');

		new AccountsSelector().configureQueryFactoryFields(opportunityLineItemQueryFactory, 'Opportunity.Account');

		new PricebookEntriesSelector().configureQueryFactoryFields(opportunityLineItemQueryFactory, 'PricebookEntry');

		new PricebooksSelector().configureQueryFactoryFields(opportunityLineItemQueryFactory, 'PricebookEntry.Pricebook2');

		new ProductsSelector().configureQueryFactoryFields(opportunityLineItemQueryFactory, 'Product2');

		return (OpportunityLineItem[]) Database.query(
			opportunityLineItemQueryFactory
			.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList()))
			.setCondition('OpportunityId IN :ids')
			.toSOQL());
	}

	public Map<Id, Date> getAccountIdToSRContractEndDateMap(OpportunityLineItem[] oppLis)
	{
		Set<Id> ids = new Set<Id>();
		for(OpportunityLineItem oppLi : oppLis)
		{
			ids.add(oppLi.OpportunityId);
		}

		Map<Id, Date> resultMap = new Map<Id, Date>();
		AggregateResult[] aggregateResults = Database.query('SELECT RecurSoft__Account__c, Max(RecurSoft__Contract_Term_End_Date__c) contractEndDate ' +
			'FROM RecurSoft__Product_Subscription__c ' +
			'WHERE RecurSoft__Product__r.Family = \'SR Platform\' ' +
			'AND RecurSoft__Billing_Status__c = \'Regular Invoicing\' ' +
			'AND RecurSoft__Account__c IN (SELECT AccountId FROM Opportunity WHERE Id IN :ids) ' +
			'GROUP BY RecurSoft__Account__c');

		for(AggregateResult result :aggregateResults)
		{
			resultMap.put((Id) result.get('RecurSoft__Account__c'), (Date) result.get('contractEndDate'));
		}

		return resultMap;
	}

	public Database.QueryLocator queryLocatorUpdateContractTermDate_Batch()
	{
		fflib_QueryFactory opportunityLineItemQueryFactory = newQueryFactory();

		new OpportunitiesSelector().configureQueryFactoryFields(opportunityLineItemQueryFactory, 'Opportunity');

		new PricebooksSelector().configureQueryFactoryFields(opportunityLineItemQueryFactory, 'PricebookEntry.Pricebook2');

		new PricebookEntriesSelector().configureQueryFactoryFields(opportunityLineItemQueryFactory, 'PricebookEntry');

		new ProductsSelector().configureQueryFactoryFields(opportunityLineItemQueryFactory, 'Product2');

		return Database.getQueryLocator(
			opportunityLineItemQueryFactory
				.selectFields(new Set<Schema.SObjectField>(this.getSObjectFieldList()))
				.setCondition('Opportunity.IsClosed != true AND Opportunity.RecordType.Name = \'Add Product\' AND Opportunity.RecurSoft__Contract_Signed_Date__c = null')
				.toSOQL());
	}
}