src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>RecurSoft__Free_Months_Setting__c</fullName>
        <inlineHelpText>Different seting options for contracts with free months.</inlineHelpText>
        <label>Free Months Setting</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RecurSoft__Number_of_Free_Months__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Extend Contract - At the Beginning</fullName>
                </value>
                <value>
                    <fullName>Extend Contract - At the End</fullName>
                </value>
                <value>
                    <fullName>Include in Contract Period - At the Beginning</fullName>
                </value>
                <value>
                    <fullName>Include in Contract Period - At the End</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RecurSoft__Number_of_Free_Months__c</fullName>
        <inlineHelpText>Free months that can extend the contract or be included in the contract.</inlineHelpText>
        <label>Number of Free Months</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <default>true</default>
                    <label>0</label>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RecurSoft__Trial__c</fullName>
        <description>Trial Period in Days.</description>
        <inlineHelpText>Period during which contracts can be cancelled without penalties.</inlineHelpText>
        <label>Trial Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0 - Waived</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                    <default>true</default>
                    <label>60</label>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.4/classes/InvocableUpdateOpps.cls
public with sharing class InvocableUpdateOpps {
    
    @InvocableMethod(label='updateOpps' description='Update Opportunities passed from a flow')
    public static Id[] flowUpdateOpp(Opportunity[] opps) {

    	for(Opportunity o : opps) {
    		o.StageName = 'Qualified';
    		o.RecurSoft__Trial__c = null;
    		o.RecurSoft__Number_of_Free_Months__c = '0';
    		o.RecurSoft__Free_Months_Setting__c = null;

    	}

    	Database.SaveResult[] results = Database.update(opps);
    	Id[] oppIds = new List<Id>();
    	
    	for(Database.SaveResult result : results) {
    		
    		if(result.isSuccess()) {
    			oppIds.add(result.getId());
    		}
    	}

    	return oppIds;
    }
}