src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Approved_Term__c</fullName>
        <defaultValue>24</defaultValue>
        <label>Approved Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src.3/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Approved_Free_Months__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Approved - Free Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approved_Price_Discount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Approved - Price Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Approved_Term__c</fullName>
        <defaultValue>24</defaultValue>
        <label>Approved - Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approved_Trial__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Approved - Trial</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Approved_Date__c</fullName>
        <label>Last Approved Date</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

src.1/classes/ExpireApprovals_Batch.cls
global class ExpireApprovals_Batch implements Database.Batchable<sObject>, Schedulable 
{	
	String query = 'SELECT Id, Approved_Price_Discount__c, Approved_Free_Months__c, Approved_Trial__c, Approved_Term__c ' +
		'FROM OpportunityLineItem ' +
		'WHERE Last_Approved_Date__c != this_month ' + 
		'AND Last_Approved_Date__c != null ' +
		'AND (Approved_Price_Discount__c != null OR Approved_Free_Months__c != null OR Approved_Trial__c != null OR Approved_Term__c != null) ' +
		'AND Opportunity.StageName NOT IN (\'Closed Won\',\'Closed Lost\') ' +
		'AND Opportunity.Owner.Profile.Name LIKE \'%Sales%\'';
		
	global Database.QueryLocator start(Database.BatchableContext BC) 
	{	
		return Database.getQueryLocator(query);
	}

	global void execute(Database.BatchableContext BC, List<OpportunityLineItem> scope) 
	{
		for(OpportunityLineItem oppLi : scope)
		{
			oppLi.Approved_Price_Discount__c = null;
			oppLi.Approved_Free_Months__c = null;
			oppLi.Approved_Trial__c = null;
			oppLi.Approved_Term__c = null;
		}

		update scope;
	}
			
	global void finish(Database.BatchableContext BC) 
	{

	}

	global void execute(SchedulableContext sc) 
	{	
		ExpireApprovals_Batch batch = new ExpireApprovals_Batch();
		Database.executebatch(batch, 1);
	}
}