src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Apex_Override_Validation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows Apex code to bypass validation rules.  Reset to false by Workflow field update.</description>
        <label>Apex Override Validation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Auto_Closed_Won_Date__c</fullName>
        <description>Used by Accounting to set a date in the future that an Opportunity should be set to Closed Won. This allows them to let an existing Opportunity run out without a renewal and setup a new Opportunity without creating the subscription right away.</description>
        <label>Auto Closed Won Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

src.4/classes/ClosedWonOpps_Batch.cls
global class ClosedWonOpps_Batch implements Database.Batchable<sObject>, Schedulable 
{
	String query = 'SELECT Id, StageName, Auto_Closed_Won_Date__c ' +
	'FROM Opportunity ' +
	'WHERE StageName NOT IN (\'Closed Lost\',\'Closed Won\',\'Not Qualified\') ' + 
	'AND Auto_Closed_Won_Date__c <= today ' +
	'LIMIT 1000';

	global Database.QueryLocator start(Database.BatchableContext BC) 
	{	
		return Database.getQueryLocator(query);
	}

	global void execute(Database.BatchableContext BC, List<Opportunity> scope) 
	{
		Map<Id, SObject> mapInsertSObject = new Map<Id, SObject>();
      	Map<Id, SObject> mapUpdateSObject = new Map<Id, SObject>();
      	Map<Id, SObject> mapDeleteSObject = new Map<Id, SObject>();

		for(Opportunity o : scope) 
		{
			o.StageName = 'Closed Won';
			o.Apex_Override_Validation__c = true;
			mapUpdateSObject.put(o.Id, o);
		}

		SRUtilities.runDml(mapInsertSObject, mapUpdateSObject, mapDeleteSObject, 'ClosedWonOpps_Batch');
	}
			
	global void finish(Database.BatchableContext BC) 
	{
		Opportunity[] remaining = [SELECT Id, StageName, Auto_Closed_Won_Date__c
			FROM Opportunity 
			WHERE StageName NOT IN ('Closed Lost','Closed Won','Not Qualified')  
			AND Auto_Closed_Won_Date__c <= today
			LIMIT 1000];

		if(remaining.size() > 100) 
		{
			ClosedWonOpps_Batch batch = new ClosedWonOpps_Batch();
			Database.executebatch(batch, 50);
		}
	}

	global void execute(SchedulableContext sc) 
	{
		ClosedWonOpps_Batch batch = new ClosedWonOpps_Batch();
		Database.executebatch(batch, 50);
	}
}