src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Approved_Term__c</fullName>
        <defaultValue>24</defaultValue>
        <label>Approved Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Terms__c</fullName>
        <description>Roll up of Product Terms field on all products.  Set by Apex</description>
        <label>Product Terms</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the related Provider record</description>
        <inlineHelpText>Link to the related Provider record</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Initial_Contract_Term__c</fullName>
        <defaultValue>12</defaultValue>
        <inlineHelpText>Contract duration, in months.</inlineHelpText>
        <label>Contract Term (Months)</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src.3/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Approved_Free_Months__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Approved - Free Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approved_Price_Discount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Approved - Price Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Approved_Term__c</fullName>
        <defaultValue>24</defaultValue>
        <label>Approved - Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approved_Trial__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Approved - Trial</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_SR_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current SR Subscription</label>
        <referenceTo>RecurSoft__Product_Subscription__c</referenceTo>
        <relationshipLabel>Opportunity Product (Current SR Subscription)</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Approved_Date__c</fullName>
        <label>Last Approved Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Modified_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Modified Subscription</label>
        <referenceTo>RecurSoft__Product_Subscription__c</referenceTo>
        <relationshipLabel>Opportunity Product (Modified Subscription)</relationshipLabel>
        <relationshipName>Opportunity_Product1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Free_Months__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Override opportunity free months</description>
        <inlineHelpText>Override opportunity free months</inlineHelpText>
        <label>Number of Orientation Months</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Override_Modified_Subscription__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Override Modified Subscription</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Terms__c</fullName>
        <formula>IF( ISPICKVAL( PricebookEntry.Product2.RecurSoft__Billing_Frequency__c , &quot;Monthly&quot; ) ,
			PricebookEntry.Product2.Name &amp; &quot;: &lt;br&gt;&quot;  &amp;
			&quot;$&quot; &amp; TEXT(UnitPrice) &amp; &quot;(&quot; &amp; TEXT(ROUND(Price_Discount__c, 4) * 100) &amp; &quot;% Discount) &lt;br&gt;&quot;  &amp;
			IF(Number_of_Free_Months__c &gt; 0 , 
						TEXT(Number_of_Free_Months__c) &amp; &quot; Orientation Months at $&quot; &amp; TEXT(Promotional_Price__c) &amp; &quot; &lt;br&gt;&quot; , &quot;&quot; ) &amp;
			IF(ISBLANK(TEXT(Trial__c)), 
						&quot;0&quot; , TEXT(Trial__c)) &amp; &quot; Day Trial&quot;,
			PricebookEntry.Product2.Name &amp; &quot;: &lt;br&gt;&quot;  &amp; 
			&quot;$&quot; &amp; TEXT(UnitPrice) &amp; &quot;(&quot; &amp; TEXT(ROUND(Price_Discount__c, 4) * 100) &amp; &quot;% Discount)&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Terms</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related Provider for the Healthgrades Premium Profile</description>
        <inlineHelpText>The related Provider for the Healthgrades Premium Profile</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Provider__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial__c</fullName>
        <label>Trial Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>120</fullName>
                </value>
                <value>
                    <fullName>180</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/Provider__c/Provider__c.object-meta.xml
<CustomObject>
    <description>Used to store information about individual Providers within a Practice.  The Provider information is used for Healthgrades Premium members.</description>
    <label>Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src.3/classes/OpportunityLineItemsService.cls
public class OpportunityLineItemsService 
{
    public static void resetApprovals(Set<Id> ids, fflib_SObjectUnitOfWork uow)
    {
         
        OpportunityLineItem[] oppLis = OpportunityLineItemsSelector.newInstance().selectByOpportunityIdWithAccountOpportunityProductPricebookEntry(ids);
        OpportunityLineItems opportunityLineItems = new OpportunityLineItems(oppLis);
        
        for(OpportunityLineItem oppLi : oppLis)
        {
            oppLi.Approved_Free_Months__c = 0;
            oppLi.Approved_Price_Discount__c = 0;
            oppLi.Approved_Trial__c = 0;
            opportunityLineItems.updateApprovalLevelRequired(oppLi, null);
            uow.registerDirty(oppLi);
        }   
    }

    public static void setApprovals(Set<Id> ids, fflib_SObjectUnitOfWork uow)
    {
        OpportunityLineItem[] oppLis = OpportunityLineItemsSelector.newInstance().selectByOpportunityIdWithAccountOpportunityProductPricebookEntry(ids);

        for(OpportunityLineItem oppLi : oppLis)
        {
            oppLi.Approved_Free_Months__c = oppLi.Number_of_Free_Months__c;
            oppLi.Approved_Price_Discount__c = oppLi.PricebookEntry.UnitPrice == 0 ? 0 : (((oppLi.PricebookEntry.UnitPrice - oppLi.UnitPrice) / oppLi.PricebookEntry.UnitPrice) + 0.00001) * 100;
            oppLi.Approved_Trial__c = oppLi.Trial__c == null ? 0 : Decimal.valueOf(oppLi.Trial__c);
            oppLi.Last_Approved_Date__c = Datetime.now();
            uow.registerDirty(oppLi);
        }   
    }

    public static void updateProductTermsRollup(Set<Id> ids, fflib_SObjectUnitOfWork uow)
    {
        OpportunityLineItem[] oppLis = OpportunityLineItemsSelector.newInstance().selectByOpportunityIdWithAccountOpportunityProductPricebookEntry(ids);
        Map<Id, String> opportunityIdToProductTermsMap;

        for(OpportunityLineItem oppLi : oppLis)
        {
            if(opportunityIdToProductTermsMap == null) opportunityIdToProductTermsMap = new Map<Id, String>();
            String productTerms = opportunityIdToProductTermsMap.containsKey(oppLi.OpportunityId) ? 
                opportunityIdToProductTermsMap.get(oppLi.OpportunityId) + '\n\n' + oppLi.Product_Terms__c : oppLi.Product_Terms__c;
            opportunityIdToProductTermsMap.put(oppLi.OpportunityId, productTerms);
        }
        
        for(Id i : opportunityIdToProductTermsMap.keySet())
        {
            Opportunity o = new Opportunity(Id = i, Product_Terms__c = opportunityIdToProductTermsMap.get(i).replaceAll('<br>', '\n'));
            uow.registerDirty(o);
        }
    }


    @future
	public static void setModifiedSubscription(Set<Id> ids) 
	{
		Opportunity[] opps = OpportunitiesSelector.newInstance().selectByIdWithAccountAndProducts(ids);
		Map<String, Id> currentSubscriptionMap;// = AssetsSelector.newInstance().selectCurrentSubscriptionsByOpportunityLineItems(opps);
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        for(Opportunity o : opps) 
        {
            if(!o.HasOpportunityLineItem) continue;
            if(o.StageName == 'Closed Won') continue;
            if(o.RecordTypeId != SRUtilities.getRecordTypeMap('Opportunity').get('Add-On Business').getRecordTypeId()) continue;

            for(OpportunityLineItem oppLi : o.OpportunityLineItems) 
            {
            	if(oppLi.Override_Modified_Subscription__c) continue;
				
				if(currentSubscriptionMap.containsKey(oppLi.Opportunity.AccountId + oppLi.Product2.Family + oppLi.Provider__c)
					&& oppLi.Modified_Subscription__c != currentSubscriptionMap.get(oppLi.Opportunity.AccountId + oppLi.Product2.Family + oppLi.Provider__c)) 
				{
					oppLi.Modified_Subscription__c = currentSubscriptionMap.get(oppLi.Opportunity.AccountId + oppLi.Product2.Family + oppLi.Provider__c);
					uow.registerDirty(oppLi);
				}

				if(currentSubscriptionMap.containsKey(oppLi.Opportunity.AccountId)
					&& oppLi.Current_SR_Subscription__c != currentSubscriptionMap.get(oppLi.Opportunity.AccountId)) 
				{
					oppLi.Current_SR_Subscription__c = currentSubscriptionMap.get(oppLi.Opportunity.AccountId);
					uow.registerDirty(oppLi);
				}
			}
		}
		uow.commitWork();
	}

	@future
    public static void setProductApprovals(Set<Id> ids)
    {
        Opportunity[] opps = OpportunitiesSelector.newInstance().selectByIdWithAccountAndProducts(ids);
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        for(Opportunity o : opps) 
        {
            if(!o.HasOpportunityLineItem) continue;

            for(OpportunityLineItem oppLi : o.OpportunityLineItems) 
            {
                oppLi.Approved_Free_Months__c = oppLi.Number_of_Free_Months__c;
                oppLi.Approved_Price_Discount__c = oppLi.PricebookEntry.UnitPrice == 0 ? 0 : (((oppLi.PricebookEntry.UnitPrice - oppLi.UnitPrice) / oppLi.PricebookEntry.UnitPrice) + 0.00001) * 100;
                oppLi.Approved_Term__c = o.RecurSoft__Initial_Contract_Term__c;
                oppLi.Approved_Trial__c = oppLi.Trial__c == null ? 0 : Decimal.valueOf(oppLi.Trial__c);
                oppLi.Last_Approved_Date__c = Datetime.now();
                uow.registerDirty(oppLi);
            }
        }
        uow.commitWork();
    }
}