src.4/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Approval_Level_Required_Term__c</fullName>
        <formula>IF( Owner.Approval_Exempt__c = true , 0 ,
	IF( RecordType.Name = &quot;New Practice Business&quot; , /*The term is usually set to coterminate in other record types*/
		IF( RecurSoft__Initial_Contract_Term__c  &gt;= 
			MIN( Approved_Term__c, Pricebook2.Level_0_Limit_Term__c ) , 0 , 
			IF( RecurSoft__Initial_Contract_Term__c &gt;= 
				MIN( Approved_Term__c, Pricebook2.Level_1_Limit_Term__c ) , 1 , 
				IF( RecurSoft__Initial_Contract_Term__c  &gt;=
					MIN( Approved_Term__c, Pricebook2.Level_2_Limit_Term__c ) , 2 , 3
				)
			)
		) , 0
	)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Approval Level Required - Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approval_Level_Required__c</fullName>
        <label>Approval Level Required</label>
        <summarizedField>OpportunityLineItem.Approval_Level_Required__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Approved_Term__c</fullName>
        <defaultValue>24</defaultValue>
        <label>Approved Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Signed_Date__c</fullName>
        <label>Contract Signed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Initial_Contract_Term__c</fullName>
        <defaultValue>12</defaultValue>
        <inlineHelpText>Contract duration, in months.</inlineHelpText>
        <label>Contract Term (Months)</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Renewal_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Determines the system behaviour at the time of renewing the subscription.</inlineHelpText>
        <label>Renewal Rule</label>
        <referenceTo>RecurSoft__Renewal_Rule__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>RecurSoft_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <label>Renewal</label>
    </recordTypes>
</CustomObject>

src.3/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Approval_Level_Required_Free_Months__c</fullName>
        <formula>IF( Opportunity.Owner.Approval_Exempt__c = true , 0 ,
	IF( Number_of_Free_Months__c &gt; 
		MAX(Approved_Free_Months__c, PricebookEntry.Level_2_Limit_Free_Months__c ) , 3 , 
		IF( Number_of_Free_Months__c &gt; 
			MAX(Approved_Free_Months__c, PricebookEntry.Level_1_Limit_Free_Months__c ) , 2 , 
			IF( Number_of_Free_Months__c &gt; 
				MAX(Approved_Free_Months__c, PricebookEntry.Level_0_Limit_Free_Months__c ) , 1 , 0
			)
		)
	)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Approval Level Required - Free Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approval_Level_Required_Price_Discount__c</fullName>
        <formula>IF( Opportunity.Owner.Approval_Exempt__c = true , 0 ,
	IF( List_Price_Override__c &gt; 0 ,
		IF( UnitPrice &gt;= /*If the price discount is less than level 1 threshold, 0 Approval Level*/ 
			(List_Price_Override__c - 
				(List_Price_Override__c * 
					MAX( Approved_Price_Discount__c,PricebookEntry.Level_0_Limit_Price_Discount__c )
				)
			) , 0 ,
			IF( UnitPrice &gt;= 
				(List_Price_Override__c - 
					(List_Price_Override__c * 
						MAX( Approved_Price_Discount__c, PricebookEntry.Level_1_Limit_Price_Discount__c )
					)
				) , 1 ,
				IF( UnitPrice &gt;= 
					(List_Price_Override__c - 
						(List_Price_Override__c * 
							MAX( Approved_Price_Discount__c, PricebookEntry.Level_2_Limit_Price_Discount__c )
						)
					) , 2 , 3
				)
			)
		)  ,
		IF( UnitPrice &gt;= 
			(PricebookEntry.UnitPrice - 
				(PricebookEntry.UnitPrice * 
					MAX( Approved_Price_Discount__c, PricebookEntry.Level_0_Limit_Price_Discount__c )
				)
			) , 0 ,
			IF( UnitPrice &gt;= 
				(PricebookEntry.UnitPrice - 
					(PricebookEntry.UnitPrice * 
						MAX( Approved_Price_Discount__c, PricebookEntry.Level_1_Limit_Price_Discount__c )
					)
				) , 1 ,
				IF( UnitPrice &gt;= 
					(PricebookEntry.UnitPrice - 
						(PricebookEntry.UnitPrice * 
							MAX( Approved_Price_Discount__c, PricebookEntry.Level_2_Limit_Price_Discount__c )
						)
					) , 2,  3
				)
			)
		)
	)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Approval Level Required - Price Discount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approval_Level_Required_Term__c</fullName>
        <formula>IF( Opportunity.Owner.Approval_Exempt__c = true , 0 ,
	IF( Opportunity.RecordType.Name = &quot;New Practice Business&quot; , /*The term is usually set to coterminate in other record types*/
		IF( Opportunity.RecurSoft__Initial_Contract_Term__c  &gt;= 
			MIN( Approved_Term__c, PricebookEntry.Level_0_Limit_Term__c ) , 0 , 
			IF( Opportunity.RecurSoft__Initial_Contract_Term__c &gt;= 
				MIN( Approved_Term__c, PricebookEntry.Level_1_Limit_Term__c ) , 1 , 
				IF( Opportunity.RecurSoft__Initial_Contract_Term__c  &gt;=
					MIN( Approved_Term__c, PricebookEntry.Level_2_Limit_Term__c ) , 2 , 3
				)
			)
		) , 0
	)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Approval Level Required - Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approval_Level_Required_Trial__c</fullName>
        <formula>IF( Opportunity.Owner.Approval_Exempt__c = true , 0 ,
	IF( VALUE(TEXT( Trial__c)) &gt; 
		MAX( Approved_Trial__c, PricebookEntry.Level_2_Limit_Trial__c ) , 3 , 
		IF( VALUE(TEXT( Trial__c)) &gt; 
			MAX( Approved_Trial__c, PricebookEntry.Level_1_Limit_Trial__c ) , 2 , 
			IF( VALUE(TEXT( Trial__c)) &gt; 
				MAX( Approved_Trial__c, PricebookEntry.Level_0_Limit_Trial__c ) , 1 , 0
			)
		)
	)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Approval Level Required - Trial</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approval_Level_Required__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Approval Level Required</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approved_Free_Months__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Approved - Free Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approved_Price_Discount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Approved - Price Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Approved_Term__c</fullName>
        <defaultValue>24</defaultValue>
        <label>Approved - Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approved_Trial__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Approved - Trial</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Free_Month_Setting__c</fullName>
        <description>Override opportunity free months</description>
        <label>Orientation Month Setting</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Extend Contract - At the Beginning</fullName>
                </value>
                <value>
                    <fullName>Include in Contract Period - At the Beginning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Invoiced_Price__c</fullName>
        <label>Invoiced Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Is_Monthly__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Scheduled revenue is monthly</description>
        <label>Is Monthly</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Approved_Date__c</fullName>
        <label>Last Approved Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Number_of_Free_Months__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Override opportunity free months</description>
        <inlineHelpText>Override opportunity free months</inlineHelpText>
        <label>Number of Orientation Months</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Code_Formula__c</fullName>
        <label>Product Code Formula</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Billing_Frequency__c</fullName>
        <formula>IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;One-Time&quot;), &quot;One-Time&quot;,
IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;Monthly&quot;), &quot;Monthly&quot;,
IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;Quarterly&quot;), &quot;Quarterly&quot; ,
IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;Semi-Annual&quot;), &quot;Semi-Annual&quot;,
IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;Yearly&quot;), &quot;Yearly&quot; ,
IF (ISPICKVAL(PricebookEntry.Product2.RecurSoft__Billing_Frequency__c, &quot;Milestones&quot;), &quot;Milestones&quot; , &quot;&quot;
)
)
)
)
)
)</formula>
        <inlineHelpText>Default billing frequency of the product.</inlineHelpText>
        <label>Billing Frequency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_End_Date_Editable__c</fullName>
        <label>Contract Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_Setting__c</fullName>
        <inlineHelpText>Contract duration options: months, days.</inlineHelpText>
        <label>Contract Term Setting</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Months</fullName>
                </value>
                <value>
                    <fullName>Days</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RecurSoft__Contract_Term_Start_Date_New__c</fullName>
        <label>Contract Term Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Renewal_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Determines the system behaviour at the time of renewing the subscription.</inlineHelpText>
        <label>Renewal Rule</label>
        <referenceTo>RecurSoft__Renewal_Rule__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>RecurSoft_Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial__c</fullName>
        <label>Trial Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>120</fullName>
                </value>
                <value>
                    <fullName>180</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.1/objects/Pricebook2.object
<CustomObject>
    <sharingModel>ReadSelect</sharingModel>
    <fields>
        <fullName>Contract_Start_Date_Offset__c</fullName>
        <label>Contract Start Date Offset</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src.3/objects/Product2.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Default_Contract_Term__c</fullName>
        <description>If Inherit Opportunity Contract Terms is false, the Contract Term will be set on the Opportunity Product to (Default Contract Term + Product Number of Free Months) and reset to this value when an Opportunity contract term change is made. For month-to-month products.</description>
        <inlineHelpText>If Inherit Opportunity Contract Terms is false, the Contract Term will be set on the Opportunity Product to (Default Contract Term + Product Number of Free Months) and reset to this value when an Opportunity contract term change is made.</inlineHelpText>
        <label>Default Contract Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Default_Co_Terminate__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Sets the default for co-termination on the related Opportunity Products.  Can be overridden at the Opportunity Product level.</description>
        <inlineHelpText>Sets the default for co-termination on the related Opportunity Products.  Can be overridden at the Opportunity Product level.</inlineHelpText>
        <label>Default Co-Terminate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RecurSoft__Billing_Frequency__c</fullName>
        <inlineHelpText>The frequency at which customer is invoiced.</inlineHelpText>
        <label>Billing Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One-Time</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-annual</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>Milestones</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src.3/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Approval_Exempt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approval Exempt</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src.2/classes/OpportunityLineItems_Test.cls
@isTest
private class OpportunityLineItems_Test 
{
    @testSetup static void testData() 
    {
        TestUtilities.insertCustomSettings();
    }

    /*@isTest static void test_beforeInsert() 
    {       
        sfab_FabricatedSObject oppLiFab = TestUtilities2.newOpportunityLineItem();            
        
        OpportunityLineItem oppLi = (OpportunityLineItem) oppLiFab.toSObject();

        OpportunityLineItems opportunityLineItems = new OpportunityLineItems(new List<OpportunityLineItem> {oppLi});       
        opportunityLineItems.onBeforeInsert();
    }

    @isTest static void test_afterInsert() 
    {       
        sfab_FabricatedSObject oppLiFab = TestUtilities2.newOpportunityLineItem();            
        
        OpportunityLineItem oppLi = (OpportunityLineItem) oppLiFab.toSObject();
        
        OpportunityLineItems opportunityLineItems = new OpportunityLineItems(new List<OpportunityLineItem> {oppLi});       
        opportunityLineItems.onAfterInsert();
    }*/

    @isTest static void test_beforeUpdate() 
    {       
        sfab_FabricatedSObject oppLiFab = TestUtilities2.newOpportunityLineItem();            
        
        OpportunityLineItem oppLi = (OpportunityLineItem) oppLiFab.toSObject();
        
        OpportunityLineItem existingOppLi = (OpportunityLineItem) TestUtilities2.existingOpportunityLineItem(oppLiFab)
            .toSObject();

        OpportunityLineItems opportunityLineItems = new OpportunityLineItems(new List<OpportunityLineItem> {oppLi});       
        opportunityLineItems.onBeforeUpdate(new Map<Id, SObject>(new List<OpportunityLineItem> {existingOppLi}));   
    }

    @isTest static void test_afterUpdate() 
    {       
       sfab_FabricatedSObject oppLiFab = TestUtilities2.newOpportunityLineItem();            
        
        OpportunityLineItem oppLi = (OpportunityLineItem) oppLiFab.toSObject();
        
        OpportunityLineItem existingOppLi = (OpportunityLineItem) TestUtilities2.existingOpportunityLineItem(oppLiFab)
            .toSObject();

        OpportunityLineItems opportunityLineItems = new OpportunityLineItems(new List<OpportunityLineItem> {oppLi});       
        opportunityLineItems.onAfterUpdate(new Map<Id, SObject>(new List<OpportunityLineItem> {existingOppLi}));   
    }

    @isTest static void test_checkForContractDatesUpdateNeeded()
	{
        OpportunityLineItem oppLi = (OpportunityLineItem) TestUtilities2.newOpportunityLineItem()
        	.setField(OpportunityLineItem.Number_of_Free_Months__c, 0)
        	.setField(OpportunityLineItem.Free_Month_Setting__c, 'SettingNew')
        	.setField(OpportunityLineItem.RecurSoft__Contract_Term_Start_Date_New__c, Date.today().addDays(-10))
        	.toSObject();

        OpportunityLineItem existingOppLi = (OpportunityLineItem) TestUtilities2.existingOpportunityLineItem(oppLi)
            .setField(OpportunityLineItem.Number_of_Free_Months__c, 1)
        	.setField(OpportunityLineItem.Free_Month_Setting__c, 'SettingOld')
        	.setField(OpportunityLineItem.RecurSoft__Contract_Term_Start_Date_New__c, Date.today().addDays(-5))
        	.toSObject();

        OpportunityLineItems opportunityLineItems = new OpportunityLineItems(new List<OpportunityLineItem>{ oppLi });
        opportunityLineItems.checkForContractDatesUpdateNeeded(oppLi, existingOppLi);

        System.assertEquals(1, opportunityLineItems.updateAllOppLisOnOpp.size());
        System.assertEquals(1, opportunityLineItems.updateAllOpplisOnOppContractDates.size());
	}

    @isTest static void test_getContractTerm()
    {           
        Account ac = (Account) TestUtilities2.newAccount().toSObject(); 

        sfab_FabricatedSObject pr = TestUtilities2.newProduct();         

        sfab_FabricatedSObject opp = TestUtilities2.newOpportunity()
            .setField(Opportunity.AccountId, ac.Id)
            .setField(Opportunity.RecurSoft__Initial_Contract_Term__c, 5)
            .setField(Opportunity.RecordTypeId, SRUtilities.getRecordTypeMap('Opportunity').get('Renewal').getRecordTypeId());

        Date createdDate = Date.newInstance(2018, 01, 20);
        OpportunityLineItem oppLi = (OpportunityLineItem) TestUtilities2.newOpportunityLineItem()
            .setField(OpportunityLineItem.OpportunityId, ((Opportunity) opp.toSObject()).Id)
            .setField(OpportunityLineItem.Product2Id, ((Product2) pr.toSObject()).Id)
            .setField(OpportunityLineItem.Number_of_Free_Months__c, 2)
            .setField(OpportunityLineItem.RecurSoft__Contract_Term_Start_Date_New__c, createdDate)
            .setParent('Product', pr)
            .setParent('Opportunity', opp)
            .toSObject();
       
        OpportunityLineItems opportunityLineItems = new OpportunityLineItems(new List<OpportunityLineItem>{ oppLi });        
        Integer contractTerm = opportunityLineItems.getContractTerm(oppLi);

        System.assertEquals(5, contractTerm);        
    } 

    /*@isTest static void test_resetApprovals()
    {           
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
       
        sfab_FabricatedSObject user = TestUtilities2.newUser()
            .setField(User.Approval_Exempt__c, true);

        sfab_FabricatedSObject pr = TestUtilities2.newProduct();      

        sfab_FabricatedSObject pbe = TestUtilities2.newPricebookEntry();          

        sfab_FabricatedSObject opp = TestUtilities2.newOpportunity()
            .setField(Opportunity.OwnerId, ((User) user.toSObject()).Id)
            .setParent('Owner', user);          

        OpportunityLineItem oppLi = (OpportunityLineItem) TestUtilities2.newOpportunityLineItem()
            .setField(OpportunityLineItem.OpportunityId, ((Opportunity) opp.toSObject()).Id)  
            .setField(OpportunityLineItem.Approval_Level_Required_Price_Discount__c, 2)
            .setField(OpportunityLineItem.Approval_Level_Required__c, 3) 
            .setField(OpportunityLineItem.Approval_Level_Required_Free_Months__c, 4) 
            .setField(OpportunityLineItem.Approval_Level_Required_Term__c, 5) 
            .setField(OpportunityLineItem.Approval_Level_Required_Trial__c, 6) 
            .setField(OpportunityLineItem.PricebookEntryId, ((PricebookEntry) pbe.toSObject()).Id) 
            .setField(OpportunityLineItem.Product2Id, ((Product2) pr.toSObject()).Id)                                       
            .setParent('Opportunity', opp)
            .toSObject();
       
        OpportunityLineItems opportunityLineItems = new OpportunityLineItems(new List<OpportunityLineItem>{ oppLi });        
        opportunityLineItems.updateAllOpplisOnOppResetApprovals = new Set<Id>();
        opportunityLineItems.updateAllOpplisOnOppResetApprovals.Add(oppLi.OpportunityId);
        opportunityLineItems.resetApprovals(new List<OpportunityLineItem> {oppLi}, uow);

        System.assertEquals(1, uow.m_dirtyMapByType.get('OpportunityLineItem').size()); 
        System.assertEquals(0, oppLi.Approved_Free_Months__c);  
        System.assertEquals(0, oppLi.Approved_Price_Discount__c);   
        System.assertEquals(24, oppLi.Approved_Term__c);    
        System.assertEquals(0, oppLi.Approved_Trial__c);    
    } 

    @isTest static void test_setApprovals()
    {           
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
       
        sfab_FabricatedSObject pbe = TestUtilities2.newPricebookEntry()
            .setField(PricebookEntry.UnitPrice, 100);

        sfab_FabricatedSObject opp = TestUtilities2.newOpportunity()
            .setField(Opportunity.RecurSoft__Initial_Contract_Term__c, 20);     

        OpportunityLineItem oppLi = (OpportunityLineItem) TestUtilities2.newOpportunityLineItem()
            .setField(OpportunityLineItem.OpportunityId, ((Opportunity) opp.toSObject()).Id)  
            .setField(OpportunityLineItem.Number_of_Free_Months__c, 2)
            .setField(OpportunityLineItem.Trial__c, 3)
            .setField(OpportunityLineItem.UnitPrice, 50)
            .setField(OpportunityLineItem.PricebookEntryId, ((PricebookEntry) pbe.toSObject()).Id)          
            .setParent('Opportunity', opp)
            .setParent('PricebookEntry', pbe)
            .toSObject();
       
        OpportunityLineItems opportunityLineItems = new OpportunityLineItems(new List<OpportunityLineItem>{ oppLi });        
        opportunityLineItems.updateAllOpplisOnOppSetApprovals = new Set<Id>();
        opportunityLineItems.updateAllOpplisOnOppSetApprovals.Add(oppLi.OpportunityId);
        opportunityLineItems.setApprovals(new List<OpportunityLineItem> {oppLi}, uow, suow);

        System.assertEquals(oppLi.Number_of_Free_Months__c, oppLi.Approved_Free_Months__c); 
        System.assertEquals((oppLi.PricebookEntry.UnitPrice == 0 ? 0 : (((oppLi.PricebookEntry.UnitPrice - oppLi.UnitPrice) / oppLi.PricebookEntry.UnitPrice) + 0.00001) * 100), oppLi.Approved_Price_Discount__c); 
        System.assertEquals(oppLi.Opportunity.RecurSoft__Initial_Contract_Term__c, oppLi.Approved_Term__c); 
        System.assertEquals(oppLi.Trial__c == null ? 0 : Decimal.valueOf(oppLi.Trial__c), oppLi.Approved_Trial__c); 
        System.assertEquals(Datetime.now(), oppLi.Last_Approved_Date__c);                           
    } */

    @isTest static void test_setContractEndDate()
    {                      
        sfab_FabricatedSObject pr = TestUtilities2.newProduct() 
            .setField(Product2.Default_Contract_Term__c, 1);  

        Account ac = (Account) TestUtilities2.newAccount().toSObject();              

        sfab_FabricatedSObject opp = TestUtilities2.newOpportunity()
            .setField(Opportunity.RecurSoft__Initial_Contract_Term__c, 5)
            .setField(Opportunity.AccountId, ac.Id)
            .setField(Opportunity.RecordTypeId, SRUtilities.getRecordTypeMap('Opportunity').get('Renewal').getRecordTypeId());
        
        OpportunityLineItem oppLi = (OpportunityLineItem) TestUtilities2.newOpportunityLineItem()
            .setField(OpportunityLineItem.OpportunityId, ((Opportunity) opp.toSObject()).Id)  
            .setField(OpportunityLineItem.RecurSoft__Contract_Term_Start_Date_New__c, Date.today())
            .setField(OpportunityLineItem.Product2Id, ((Product2) pr.toSObject()).Id)
            .setField(OpportunityLineItem.Number_of_Free_Months__c, 2)  
            .setField(OpportunityLineItem.Product2Id, ((Product2) pr.toSObject()).Id)                              
            .setParent('Product2', pr)
            .setParent('Opportunity', opp)
            .toSObject();
           
        OpportunityLineItems opportunityLineItems = new OpportunityLineItems(new List<OpportunityLineItem>{ oppLi });         
        opportunityLineItems.setContractEndDate(oppLi);

        System.assertEquals(Date.today().addMonths(opportunityLineItems.getContractTerm(oppLi)).addDays(-1), oppLi.RecurSoft__Contract_Term_End_Date_Editable__c);                      
    }     

    @isTest static void test_setContractStartDate()
    {                   
        sfab_FabricatedSObject pr = TestUtilities2.newProduct() 
            .setField(Product2.Default_Contract_Term__c, 1);  

        Account ac = (Account) TestUtilities2.newAccount().toSObject();  

        sfab_FabricatedSObject pb = TestUtilities2.newPricebook2()
            .setField(Pricebook2.Contract_Start_Date_Offset__c, 3);

        sfab_FabricatedSObject pbe = TestUtilities2.newPricebookEntry()
            .setField(PricebookEntry.Pricebook2Id,((Pricebook2) pb.toSObject()).Id)
            .setParent('Pricebook2', pb);                   

        sfab_FabricatedSObject opp = TestUtilities2.newOpportunity()
            .setField(Opportunity.RecurSoft__Contract_Signed_Date__c, Date.today())
            .setField(Opportunity.AccountId, ac.Id)
            .setField(Opportunity.RecordTypeId, SRUtilities.getRecordTypeMap('Opportunity').get('Add Product').getRecordTypeId());
    
        OpportunityLineItem oppLi = (OpportunityLineItem) TestUtilities2.newOpportunityLineItem()
            .setField(OpportunityLineItem.OpportunityId, ((Opportunity) opp.toSObject()).Id)  
            .setField(OpportunityLineItem.RecurSoft__Contract_Term_Start_Date_New__c, Date.today())
            .setField(OpportunityLineItem.Product2Id, ((Product2) pr.toSObject()).Id)
            .setField(OpportunityLineItem.Number_of_Free_Months__c, 2)   
            .setField(OpportunityLineItem.RecurSoft__Contract_Term_Start_Date_New__c, Date.today())                            
            .setField(OpportunityLineItem.PricebookEntryId, ((PricebookEntry) pbe.toSObject()).Id) 
            .setParent('PricebookEntry', pbe)
            .setParent('Opportunity', opp)
            .toSObject();
       
        OpportunityLineItems opportunityLineItems = new OpportunityLineItems(new List<OpportunityLineItem>{ oppLi });         
        opportunityLineItems.setContractStartDate(oppLi);

        System.assertEquals(Date.today().addDays(3), oppLi.RecurSoft__Contract_Term_Start_Date_New__c);        
    }

    @isTest static void test_setDefaultsFromProduct()
    {           
        fflib_ApexMocks mocks = new fflib_ApexMocks();

        sfab_FabricatedSObject pr = TestUtilities2.newProduct() 
            .setField(Product2.RecurSoft__Billing_Frequency__c, 'Monthly')
            .setField(Product2.Default_Co_Terminate__c, true)
            .setField(Product2.ProductCode, '00123');       
                        
        sfab_FabricatedSObject opp = TestUtilities2.newOpportunity();

        sfab_FabricatedSObject re = TestUtilities2.newRecurSoftRenewalRule();
    
        OpportunityLineItem oppLi = (OpportunityLineItem) TestUtilities2.newOpportunityLineItem()
            .setField(OpportunityLineItem.OpportunityId, ((Opportunity) opp.toSObject()).Id)            
            .setField(OpportunityLineItem.Product2Id, ((Product2) pr.toSObject()).Id)                                                                         
            .setField(OpportunityLineItem.RecurSoft__Renewal_Rule__c, ((RecurSoft__Renewal_Rule__c) re.toSObject()).Id)   
            .setParent('Opportunity', opp)
            .setParent('Product2', pr)
            .toSObject();

        ProductsSelector mockSelector = (ProductsSelector) mocks.mock(ProductsSelector.class);

        mocks.startStubbing();
        mocks.when(mockSelector.getSObjectType2())
            .thenReturn(Product2.SObjectType);
        mocks.when(mockSelector.selectByOpportunityLineItems(new List<OpportunityLineItem> {oppLi}))
            .thenReturn(new List<Product2> {(Product2) pr.toSObject()});
        mocks.stopStubbing();

        Application.Selector.setMock(mockSelector);
       
        OpportunityLineItems opportunityLineItems = new OpportunityLineItems(new List<OpportunityLineItem>{ oppLi });         
        opportunityLineItems.setDefaultsFromProduct(oppLi);

        System.assertEquals('Months', oppLi.RecurSoft__Contract_Term_Setting__c);        
        System.assertEquals('00123', oppLi.Product_Code_Formula__c);  
        System.assertEquals(true, oppLi.Is_Monthly__c);       
    }

    @isTest static void test_setMonthlyRevenue()
    {       
        fflib_ApexMocks mocks = new fflib_ApexMocks();       

        sfab_FabricatedSObject pr = TestUtilities2.newProduct()     
            .setField(Product2.Family, 'SR Platform')
            .setField(Product2.RecurSoft__Billing_Frequency__c, 'Monthly');   

        sfab_FabricatedSObject opp = TestUtilities2.newOpportunity();       

        sfab_FabricatedSObject oppLi = TestUtilities2.newOpportunityLineItem()
            .setField(OpportunityLineItem.OpportunityId, ((Opportunity) opp.toSObject()).Id) 
            .setField(OpportunityLineItem.UnitPrice, 100)    
            .setField(OpportunityLineItem.Invoiced_Price__c, 0)    
            .setField(OpportunityLineItem.Quantity, 10)  
            .setField(OpportunityLineItem.Product2Id, ((Product2) pr.toSObject()).Id)           
            .setParent('Opportunity', opp)          
            .setParent('Product2', pr);

        OpportunityLineItem oppLis = (OpportunityLineItem) oppLi.toSObject();

        OpportunityLineItem existingOppLi = (OpportunityLineItem) TestUtilities2.existingOpportunityLineItem(oppLi)
            .setField(OpportunityLineItem.OpportunityId, ((Opportunity) opp.toSObject()).Id)            
            .setField(OpportunityLineItem.UnitPrice, 200)   
            .setField(OpportunityLineItem.Invoiced_Price__c, 0)    
            .setField(OpportunityLineItem.Quantity, 20)   
            .setParent('Opportunity', opp)          
            .toSObject();               
       
        ProductsSelector mockSelector = (ProductsSelector) mocks.mock(ProductsSelector.class);

        mocks.startStubbing();
        mocks.when(mockSelector.getSObjectType2())
            .thenReturn(Product2.SObjectType);
        mocks.when(mockSelector.selectByOpportunityLineItems(new List<OpportunityLineItem> { oppLis }))
            .thenReturn(new List<Product2> { ((Product2) pr.toSObject()) });
        mocks.stopStubbing();

        Application.Selector.setMock(mockSelector);
       
        OpportunityLineItems opportunityLineItems = new OpportunityLineItems(new List<OpportunityLineItem>{ oppLis });         
        opportunityLineItems.setMonthlyRevenue(oppLis, existingOppLi);

        System.assertEquals(1000, oppLis.SR_Monthly_Revenue__c);     
    }

    @isTest static void test_updateAllOppLisOnOppList()
    {       
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        sfab_FabricatedSObject pbe = TestUtilities2.newPricebookEntry()
            .setField(PricebookEntry.UnitPrice, 0);
    
        sfab_FabricatedSObject opp = TestUtilities2.newOpportunity()
            .setField(Opportunity.IsClosed, false)
            .setField(Opportunity.RecordTypeId, SRUtilities.getRecordTypeMap('Opportunity').get('Add-On Business').getRecordTypeId())
            .setField(Opportunity.RecurSoft__Initial_Contract_Term__c, 5)
            .setField(Opportunity.RecurSoft__Contract_Signed_Date__c, Date.today());      

        OpportunityLineItem oppLi = (OpportunityLineItem) TestUtilities2.newOpportunityLineItem()
            .setField(OpportunityLineItem.OpportunityId, ((Opportunity) opp.toSObject()).Id) 
            .setField(OpportunityLineItem.Approval_Level_Required_Price_Discount__c, 1)    
            .setField(OpportunityLineItem.Approval_Level_Required_Free_Months__c, 2)    
            .setField(OpportunityLineItem.Approval_Level_Required_Term__c, 3)  
            .setField(OpportunityLineItem.Approval_Level_Required_Trial__c, 4)              
            .setField(OpportunityLineItem.Number_of_Free_Months__c, 10)             
            .setField(OpportunityLineItem.Trial__c, 4) 
            .setField(OpportunityLineItem.RecurSoft__Contract_Term_Start_Date_New__c, Date.newInstance(2018, 01, 20)) 
            .setField(OpportunityLineItem.RecurSoft__Contract_Term_End_Date_Editable__c, Date.today())          
            .setField(OpportunityLineItem.PricebookEntryId, ((PricebookEntry) pbe.toSObject()).Id)
            .setField(OpportunityLineItem.Override_Modified_Subscription__c, true) 
            .setField(OpportunityLineItem.Override_Current_SR_Subscription__c, true) 
            .setParent('Opportunity', opp)          
            .setParent('PricebookEntry', pbe)  
            .toSObject();  
        
        OpportunityLineItems opportunityLineItems = new OpportunityLineItems(new List<OpportunityLineItem>{ oppLi });         
        opportunityLineItems.updateAllOpplisOnOppContractDates = new Set<Id>();       
        opportunityLineItems.updateAllOpplisOnOppContractDates.Add(oppLi.OpportunityId);        
        opportunityLineItems.updateAllOpplisOnOppModifiedSubscriptions = new Set<Id>();       
        opportunityLineItems.updateAllOpplisOnOppModifiedSubscriptions.Add(oppLi.OpportunityId);                
        opportunityLineItems.updateAllOppLisOnOpp(new List<OpportunityLineItem> {oppLi}, uow);
        String recursofContractTerm = String.valueOf(oppLi.RecurSoft__Contract_Term_Start_Date_New__c.monthsBetween(oppLi.RecurSoft__Contract_Term_End_Date_Editable__c));
        
        System.assertEquals(1, uow.m_dirtyMapByType.get('OpportunityLineItem').size());  
        //System.assertEquals(10, oppLi.Approved_Free_Months__c);  
        System.assertEquals(recursofContractTerm, oppLi.RecurSoft__Contract_Term1__c); 
    }
    
    @isTest static void test_updateAllOppLisOnOpp()
    {       
        fflib_ApexMocks mocks = new fflib_ApexMocks();

        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        sfab_FabricatedSObject pbe = TestUtilities2.newPricebookEntry()
            .setField(PricebookEntry.UnitPrice, 0);
    
        sfab_FabricatedSObject opp = TestUtilities2.newOpportunity()
            .setField(Opportunity.IsClosed, false)
            .setField(Opportunity.RecordTypeId, SRUtilities.getRecordTypeMap('Opportunity').get('Add-On Business').getRecordTypeId())
            .setField(Opportunity.RecurSoft__Initial_Contract_Term__c, 5)
            .setField(Opportunity.RecurSoft__Contract_Signed_Date__c, Date.today());      

        OpportunityLineItem oppLi = (OpportunityLineItem) TestUtilities2.newOpportunityLineItem()
            .setField(OpportunityLineItem.OpportunityId, ((Opportunity) opp.toSObject()).Id) 
            .setField(OpportunityLineItem.Approval_Level_Required_Price_Discount__c, 1)    
            .setField(OpportunityLineItem.Approval_Level_Required_Free_Months__c, 2)    
            .setField(OpportunityLineItem.Approval_Level_Required_Term__c, 3)  
            .setField(OpportunityLineItem.Approval_Level_Required_Trial__c, 4)              
            .setField(OpportunityLineItem.Number_of_Free_Months__c, 10)             
            .setField(OpportunityLineItem.Trial__c, 4) 
            .setField(OpportunityLineItem.RecurSoft__Contract_Term_Start_Date_New__c, Date.newInstance(2018, 01, 20)) 
            .setField(OpportunityLineItem.RecurSoft__Contract_Term_End_Date_Editable__c, Date.today())                      
            .setField(OpportunityLineItem.PricebookEntryId, ((PricebookEntry) pbe.toSObject()).Id)
            .setField(OpportunityLineItem.Override_Modified_Subscription__c, true) 
            .setField(OpportunityLineItem.Override_Current_SR_Subscription__c, true) 
            .setParent('Opportunity', opp)          
            .setParent('PricebookEntry', pbe)  
            .toSObject();  
        
        OpportunityLineItemsSelector mockSelector = (OpportunityLineItemsSelector) mocks.mock(OpportunityLineItemsSelector.class);

        mocks.startStubbing();
        mocks.when(mockSelector.getSObjectType2())
            .thenReturn(OpportunityLineItem.SObjectType);
        mocks.when(mockSelector.selectByOpportunityIdWithAccountOpportunityProductPricebookEntry(new Set<Id>{ oppLi.OpportunityId }))
            .thenReturn(new List<OpportunityLineItem>{ oppLi });
        mocks.stopStubbing();

        Application.Selector.setMock(mockSelector);
        
        Set<Id> ids = new Set<Id>();
        ids.Add(oppLi.OpportunityId);

        OpportunityLineItems opportunityLineItems = new OpportunityLineItems(new List<OpportunityLineItem>{ oppLi });         
        opportunityLineItems.updateAllOpplisOnOppContractDates = new Set<Id>();       
        opportunityLineItems.updateAllOpplisOnOppContractDates.Add(oppLi.OpportunityId);        
        opportunityLineItems.updateAllOpplisOnOppModifiedSubscriptions = new Set<Id>();       
        opportunityLineItems.updateAllOpplisOnOppModifiedSubscriptions.Add(oppLi.OpportunityId);                
        opportunityLineItems.updateAllOppLisOnOpp(ids, uow);
        String recursofContractTerm = String.valueOf(oppLi.RecurSoft__Contract_Term_Start_Date_New__c.monthsBetween(oppLi.RecurSoft__Contract_Term_End_Date_Editable__c));        

        System.assertEquals(1, uow.m_dirtyMapByType.get('OpportunityLineItem').size()); 
        //System.assertEquals(10, oppLi.Approved_Free_Months__c);          
        System.assertEquals(recursofContractTerm, oppLi.RecurSoft__Contract_Term1__c);          
    }

    @isTest static void test_setModifiedSubscriptions()
    {  
        String fieldName = 'Current_SR_Subscription__c';        
        
        fflib_ApexMocks mocks = new fflib_ApexMocks();

        fflib_ApexMocks mocks2 = new fflib_ApexMocks();

        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        Account ac = (Account) TestUtilities2.newAccount().toSObject(); 

        sfab_FabricatedSObject pv =  TestUtilities2.newProvider(); 

        RecurSoft__Renewal_Rule__c re = (RecurSoft__Renewal_Rule__c) TestUtilities2.newRecurSoftRenewalRule().toSObject(); 

        sfab_FabricatedSObject ps = TestUtilities2.newRecurSoftProductSubscription();       

        RecurSoft__Product_Subscription__c ps2 = (RecurSoft__Product_Subscription__c) TestUtilities2.newRecurSoftProductSubscription().toSObject(); 

        sfab_FabricatedSObject pr = TestUtilities2.newProduct() 
            .setField(Product2.Family, 'SR Platform')
            .setField(Product2.Default_Co_Terminate__c, true)
            .setField(Product2.ProductCode, '00123');    

        sfab_FabricatedSObject a = TestUtilities2.newAsset()
            .setField(Asset.Product2Id, ((Product2) pr.toSObject()).Id)
            .setField(Asset.AccountId, ac.Id)
            .setField(Asset.Provider__c, ((Provider__c) pv.toSObject()).Id)
            .setField(Asset.Current_Product_Subscription__c, ps2.Id)            
            .setParent('Product2', pr);

        Asset ast = (Asset) a.toSObject();
                    
        sfab_FabricatedSObject opp = TestUtilities2.newOpportunity()
            .setField(Opportunity.AccountId, ac.Id)
            .setField(Opportunity.RecordTypeId, SRUtilities.getRecordTypeMap('Opportunity').get('Add-On Business').getRecordTypeId());

        OpportunityLineItem oppLi = (OpportunityLineItem) TestUtilities2.newOpportunityLineItem()
            .setField(OpportunityLineItem.OpportunityId, ((Opportunity) opp.toSObject()).Id)            
            .setField(OpportunityLineItem.Override_Modified_Subscription__c, false)                                                                       
            .setField(OpportunityLineItem.Override_Current_SR_Subscription__c, false)                                                                         
            .setField(OpportunityLineItem.RecurSoft__Renewal_Rule__c, re.Id)   
            .setField(OpportunityLineItem.Modified_Subscription__c, ((RecurSoft__Product_Subscription__c) ps.toSObject()).Id) 
            .setField(OpportunityLineItem.Current_SR_Subscription__c, null) 
            .setField(OpportunityLineItem.Provider__c, ((Provider__c) pv.toSObject()).Id)
            .setField(OpportunityLineItem.Product2Id, ((Product2) pr.toSObject()).Id)
            .setParent('Opportunity', opp)
            .setParent('Product2', pr)
            .setParent('RecurSoft__Product_Subscription__r', ps)
            .toSObject();           

        AssetsSelector mockSelector2 = (AssetsSelector) mocks2.mock(AssetsSelector.class);

        mocks2.startStubbing();
        mocks2.when(mockSelector2.getSObjectType2())
            .thenReturn(Asset.SObjectType);
        mocks2.when(mockSelector2.selectCurrentSubscriptionsByOpportunityLineItems(new List<OpportunityLineItem> {oppLi}))
            .thenReturn(new Map<String,Id> {String.valueOf(ast.AccountId) + (((Product2) pr.toSObject()).Family) + ast.Provider__c => ast.Current_Product_Subscription__c});
        mocks2.stopStubbing();

        Application.Selector.setMock(mockSelector2);

        OpportunityLineItems opportunityLineItems = new OpportunityLineItems(new List<OpportunityLineItem>{ oppLi });             
        opportunityLineItems.setModifiedSubscriptions(oppLi, fieldName, uow);
       
        System.assertEquals(1, uow.m_dirtyMapByType.get('OpportunityLineItem').size()); 
        System.assertEquals(ps2.Id, oppLi.Current_SR_Subscription__c);      
    }

    @isTest static void test_setModifiedSubscriptionsList()
    {       
        fflib_ApexMocks mocks = new fflib_ApexMocks();

        fflib_ApexMocks mocks2 = new fflib_ApexMocks();

        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        Account ac = (Account) TestUtilities2.newAccount().toSObject(); 

        sfab_FabricatedSObject pv =  TestUtilities2.newProvider(); 

        RecurSoft__Renewal_Rule__c re = (RecurSoft__Renewal_Rule__c) TestUtilities2.newRecurSoftRenewalRule().toSObject(); 

        sfab_FabricatedSObject ps = TestUtilities2.newRecurSoftProductSubscription();       

        RecurSoft__Product_Subscription__c ps2 = (RecurSoft__Product_Subscription__c) TestUtilities2.newRecurSoftProductSubscription().toSObject(); 

        sfab_FabricatedSObject pr = TestUtilities2.newProduct() 
            .setField(Product2.Family, 'SR Platform')
            .setField(Product2.Default_Co_Terminate__c, true)
            .setField(Product2.ProductCode, '00123');    

        sfab_FabricatedSObject a = TestUtilities2.newAsset()
            .setField(Asset.Product2Id, ((Product2) pr.toSObject()).Id)
            .setField(Asset.AccountId, ac.Id)
            .setField(Asset.Provider__c, ((Provider__c) pv.toSObject()).Id)
            .setField(Asset.Current_Product_Subscription__c, ps2.Id)            
            .setParent('Product2', pr);

        Asset ast = (Asset) a.toSObject();
                    
        sfab_FabricatedSObject opp = TestUtilities2.newOpportunity()
            .setField(Opportunity.AccountId, ac.Id)
            .setField(Opportunity.RecordTypeId, SRUtilities.getRecordTypeMap('Opportunity').get('Add-On Business').getRecordTypeId());

        OpportunityLineItem oppLi = (OpportunityLineItem) TestUtilities2.newOpportunityLineItem()
            .setField(OpportunityLineItem.OpportunityId, ((Opportunity) opp.toSObject()).Id)            
            .setField(OpportunityLineItem.Override_Modified_Subscription__c, false)                                                                       
            .setField(OpportunityLineItem.Override_Current_SR_Subscription__c, false)                                                                         
            .setField(OpportunityLineItem.RecurSoft__Renewal_Rule__c, re.Id)   
            .setField(OpportunityLineItem.Modified_Subscription__c, null) 
            .setField(OpportunityLineItem.Current_SR_Subscription__c, null) 
            .setField(OpportunityLineItem.Provider__c, ((Provider__c) pv.toSObject()).Id)
            .setField(OpportunityLineItem.Product2Id, ((Product2) pr.toSObject()).Id)
            .setParent('Opportunity', opp)
            .setParent('Product2', pr)
            .setParent('RecurSoft__Product_Subscription__r', ps)
            .toSObject();           

        AssetsSelector mockSelector2 = (AssetsSelector) mocks2.mock(AssetsSelector.class);

        mocks2.startStubbing();
        mocks2.when(mockSelector2.getSObjectType2())
            .thenReturn(Asset.SObjectType);
        mocks2.when(mockSelector2.selectCurrentSubscriptionsByOpportunityLineItems(new List<OpportunityLineItem> {oppLi}))
            .thenReturn(new Map<String,Id> {String.valueOf(ast.AccountId) + (((Product2) pr.toSObject()).Family) + ast.Provider__c => ast.Current_Product_Subscription__c});
        mocks2.stopStubbing();

        Application.Selector.setMock(mockSelector2);

        OpportunityLineItems opportunityLineItems = new OpportunityLineItems(new List<OpportunityLineItem>{ oppLi });         
        opportunityLineItems.updateAllOpplisOnOppModifiedSubscriptions = new Set<Id>();        
        opportunityLineItems.updateAllOpplisOnOppModifiedSubscriptions.Add(oppLi.OpportunityId); 
        opportunityLineItems.setModifiedSubscriptions(new List<OpportunityLineItem> {oppLi}, uow);
       
        System.assertEquals(1, uow.m_dirtyMapByType.get('OpportunityLineItem').size()); 
        System.assertEquals(ps2.Id, oppLi.Current_SR_Subscription__c); 
        System.assertEquals(ps2.Id, oppLi.Modified_Subscription__c);      
    }

    @isTest static void test_updateApprovalLevelRequired() 
    {       
        fflib_ApexMocks mocks = new fflib_ApexMocks();  

        sfab_FabricatedSObject pbe = TestUtilities2.newPricebookEntry();   

        sfab_FabricatedSObject oppFab = TestUtilities2.newOpportunity();            
        
        Opportunity opp = (Opportunity) oppFab.toSObject();
        
        sfab_FabricatedSObject oppLiFab = TestUtilities2.newOpportunityLineItem()
            .setField(OpportunityLineItem.OpportunityId, opp.Id) 
            .setField(OpportunityLineItem.UnitPrice, 100) 
            .setField(OpportunityLineItem.Approval_Level_Required_Price_Discount__c, 1) 
            .setField(OpportunityLineItem.Approval_Level_Required_Free_Months__c, 2) 
            .setField(OpportunityLineItem.Approval_Level_Required_Term__c, 3) 
            .setField(OpportunityLineItem.Approval_Level_Required_Trial__c, 4) 
            .setField(OpportunityLineItem.PricebookEntryId, ((PricebookEntry) pbe.toSObject()).Id)
            .setParent('Opportunity', oppFab)       
            .setParent('PricebookEntry', pbe); 

        OpportunityLineItem oppLi = (OpportunityLineItem) oppLiFab.toSObject();

        OpportunityLineItem existingOppLi = (OpportunityLineItem) TestUtilities2.existingOpportunityLineItem(oppLiFab)
            .setField(OpportunityLineItem.OpportunityId, opp.Id)            
            .setField(OpportunityLineItem.UnitPrice, 200)    
            .setField(OpportunityLineItem.PricebookEntryId, ((PricebookEntry) pbe.toSObject()).Id)
            .setParent('Opportunity', oppFab) 
            .setParent('PricebookEntry', pbe)           
            .toSObject();       

        PricebookEntriesSelector mockSelector = (PricebookEntriesSelector) mocks.mock(PricebookEntriesSelector.class);

        mocks.startStubbing();
        mocks.when(mockSelector.getSObjectType2())
            .thenReturn(PricebookEntry.SObjectType);
        mocks.when(mockSelector.selectByOpportunityLineItems(new List<OpportunityLineItem>{ oppLi }))
            .thenReturn(new List<PricebookEntry> { (PricebookEntry) pbe.toSObject() });
        mocks.stopStubbing();

        Application.Selector.setMock(mockSelector);

        OpportunityLineItems opportunityLineItems = new OpportunityLineItems(new List<OpportunityLineItem>{ oppLi });               
        opportunityLineItems.updateApprovalLevelRequired(oppLi, existingOppLi);
        
        System.assertEquals(oppLi.Approval_Level_Required_Trial__c, oppLi.Approval_Level_Required__c);      
    }

    @isTest static void test_validateProductFamily()
    {
        try{
            fflib_ApexMocks mocks = new fflib_ApexMocks();

            Account ac = (Account) TestUtilities2.newAccount().toSObject(); 

            Provider__c pv = (Provider__c) TestUtilities2.newProvider().toSObject(); 

            sfab_FabricatedSObject pr = TestUtilities2.newProduct()
                .setField(Product2.Family, 'SR Platform');
            
            sfab_FabricatedSObject opp = TestUtilities2.newOpportunity()
                .setField(Opportunity.AccountId, ac.Id);
                   
            OpportunityLineItem oppLi = (OpportunityLineItem) TestUtilities2.newOpportunityLineItem()
                .setField(OpportunityLineItem.OpportunityId, ((Opportunity) opp.toSObject()).Id)
                .setField(OpportunityLineItem.Product2Id, ((Product2) pr.toSObject()).Id)
                .setField(OpportunityLineItem.Provider__c, pv.Id)
                .setParent('Product2', pr)
                .setParent('Opportunity', opp)
                .toSObject();
            
            Map<Id, OpportunityLineItem>  mp = new Map<Id, OpportunityLineItem>(new List<OpportunityLineItem> { oppLi });

            OpportunityLineItemsSelector mockSelector = (OpportunityLineItemsSelector) mocks.mock(OpportunityLineItemsSelector.class);
           
            mocks.startStubbing();
            mocks.when(mockSelector.getSObjectType2())
               .thenReturn(OpportunityLineItem.SObjectType);
            mocks.when(mockSelector.selectByIdWithAccountOpportunityProductPricebookEntry(mp.keySet()))
               .thenReturn(new List<OpportunityLineItem> { oppLi });
            mocks.stopStubbing();
            
            Application.Selector.setMock(mockSelector);
            
            String result = oppLi.Opportunity.AccountId + oppLi.Product2.Family + oppLi.Provider__c;
            
            AssetsSelector mockSelector2 = (AssetsSelector) mocks.mock(AssetsSelector.class);
            
            mocks.startStubbing();
            mocks.when(mockSelector2.getSObjectType2())
               .thenReturn(Asset.SObjectType);
            mocks.when(mockSelector2.selectCurrentSubscriptionsByOpportunityLineItems(new List<OpportunityLineItem> { oppLi }))
               .thenReturn(new  Map<String,Id> { result => oppLi.Id });           
            mocks.stopStubbing();

           Application.Selector.setMock(mockSelector2);

           OpportunityLineItems opportunityLineItems = new  OpportunityLineItems (new List<OpportunityLineItem> { oppLi });
           opportunityLineItems.validateProductFamily(oppLi);  
           System.assert(false);        
       }
       catch(Exception e){
            System.assert(e.getMessage().contains('There is already an active subscription for this product family'));              
       }       
    }

    @isTest static void test_updateContractDates()
    {   
        fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
                
        sfab_FabricatedSObject oppFab = TestUtilities2.newOpportunity()
            .setField(Opportunity.IsClosed, false)
            .setField(Opportunity.RecordTypeId, SRUtilities.getRecordTypeMap('Opportunity').get('Add-On Business').getRecordTypeId())
            .setField(Opportunity.RecurSoft__Contract_Signed_Date__c, Date.today())
            .setField(Opportunity.RecurSoft__Initial_Contract_Term__c, 1);            
        
        Opportunity opp = (Opportunity) oppFab.toSObject();
       
        sfab_FabricatedSObject pr = TestUtilities2.newProduct()
            .setField(Product2.Default_Contract_Term__c, 2);
        
        OpportunityLineItem oppLi = (OpportunityLineItem) TestUtilities2.newOpportunityLineItem()
            .setField(OpportunityLineItem.OpportunityId, opp.Id)
            .setField(OpportunityLineItem.RecurSoft__Contract_Term_Start_Date_New__c, Date.newInstance(2018, 04, 27))
            .setField(OpportunityLineItem.RecurSoft__Contract_Term_End_Date_Editable__c, Date.today())
            .setParent('Product2', pr)
            .setParent('Opportunity', oppFab)
            .toSObject();
        
        OpportunityLineItems opportunityLineItems = new OpportunityLineItems(new List<OpportunityLineItem> { oppLi });
        opportunityLineItems.updateAllOpplisOnOppContractDates = new Set<Id>();
        opportunityLineItems.updateAllOpplisOnOppContractDates.Add(oppLi.OpportunityId);
        opportunityLineItems.opportunityIdToContractEndDateMap = new Map<Id, Date>();
        opportunityLineItems.opportunityIdToContractEndDateMap.put(oppLi.OpportunityId, Date.today());
        opportunityLineItems.updateContractDates(new List<OpportunityLineItem> { oppLi }, uow);
        String recursoftContractTerm = String.valueOf(oppLi.RecurSoft__Contract_Term_Start_Date_New__c.monthsBetween(oppLi.RecurSoft__Contract_Term_End_Date_Editable__c));

        System.assertEquals(1, uow.m_dirtyMapByType.get('OpportunityLineItem').size());
        System.assertEquals(recursoftContractTerm, oppLi.RecurSoft__Contract_Term1__c);       
    }
}