src.4/objects/Task_History__c.object
<CustomObject>
    <label>Task History</label>
    <nameField>
        <label>Task History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Value__c</fullName>
        <label>New Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Old_Value__c</fullName>
        <label>Old Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_ID__c</fullName>
        <label>Task ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

src.4/classes/ViewTaskFieldHistory_Controller.cls
public with sharing class ViewTaskFieldHistory_Controller 
{
	public Task_History__c[] taskHistory { get; set; }


	public ViewTaskFieldHistory_Controller(ApexPages.StandardController stdController) 
	{
		Id taskId = stdController.getId();
		taskHistory = [SELECT Task_Id__c, Field__c, Old_Value__c, New_Value__c, Owner.Name, CreatedDate 
			FROM Task_History__c 
			WHERE Task_Id__c = :taskId 
			ORDER BY CreatedDate DESC];		
	}
}